### ISSUE TITLE
Perfetto SDK support App tracing in production

### ISSUE THREAD

**Issue by Kyson** [google/perfetto#100]
Perfetto sdk size(.so about 1MB) is too large for app tracing in production

Can you trim out most of the unnecessary functionality and provide a lightweight SDK?

**Comment by primiano** [comment]
If you build with `-Wl,--gc-sections` the linker will strip most unused parts.
That should shrink it to ~200KB.
We are also working on a shlib C-only API, details on https://bit.ly/perfetto-c , but that will take some time to become a thing.

Note: you'll need to join this group to get access to the doc: https://groups.google.com/forum/#!forum/perfetto-dev
