### ISSUE TITLE
surfaceflinger is at the bottom of the trace

### ISSUE THREAD

**Issue by eric4337** [google/perfetto#101]
surfaceflinger is at the bottom of the trace
V12.1.269 both stable/Canary

duration_ms: 5000
buffers: {
    size_kb: 63488
    fill_policy: DISCARD
}
buffers: {
    size_kb: 2048
    fill_policy: DISCARD
}
data_sources: {
    config {
        name: "android.gpu.memory"
    }
}
data_sources: {
    config {
        name: "linux.process_stats"
        target_buffer: 1
        process_stats_config {
            scan_all_processes_on_start: true
            proc_stats_poll_ms: 1000
        }
    }
}
data_sources: {
    config {
        name: "android.log"
        android_log_config {
            log_ids: LID_DEFAULT
        }
    }
}
data_sources: {
    config {
        name: "linux.sys_stats"
        sys_stats_config {
            stat_period_ms: 1000
            stat_counters: STAT_CPU_TIMES
            stat_counters: STAT_FORK_COUNT
        }
    }
}
data_sources: {
    config {
        name: "android.heapprofd"
        target_buffer: 0
        heapprofd_config {
            sampling_interval_bytes: 4096
            process_cmdline: "composer"
            process_cmdline: "surfaceflinger"
            shmem_size_bytes: 8388608
            block_client: true
        }
    }
}
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            ftrace_events: "sched/sched_switch"
            ftrace_events: "power/suspend_resume"
            ftrace_events: "sched/sched_wakeup"
            ftrace_events: "sched/sched_wakeup_new"
            ftrace_events: "sched/sched_waking"
            ftrace_events: "power/cpu_frequency"
            ftrace_events: "power/cpu_idle"
            ftrace_events: "power/gpu_frequency"
            ftrace_events: "gpu_mem/gpu_mem_total"
            ftrace_events: "sched/sched_process_exit"
            ftrace_events: "sched/sched_process_free"
            ftrace_events: "task/task_newtask"
            ftrace_events: "task/task_rename"
            ftrace_events: "lowmemorykiller/lowmemory_kill"
            ftrace_events: "oom/oom_score_adj_update"
            ftrace_events: "ftrace/print"
            atrace_categories: "gfx"
            atrace_categories: "input"
            atrace_categories: "view"
            atrace_categories: "wm"
            atrace_categories: "am"
            atrace_categories: "video"
            atrace_categories: "rs"
            atrace_apps: "lmkd"
        }
    }
}

**Comment by primiano** [comment]
@eric4337 can you please explain what the bug is?
I don't know how to read "surfaceflinger is at the bottom of the trace".
Is it a statement? Is it a question? What did you expect to see? What did you see instead?

**Comment by eric4337** [comment]
![IMG_20210303_093800](https://user-images.githubusercontent.com/4446235/109739382-7b94e100-7c04-11eb-9b84-3496823e58fa.jpg)
The surfaceflinger process used to be on the top of list, but it is now always at the bottom of list

**Comment by eric4337** [comment]
Aa
![IMG_20210303_093800~3](https://user-images.githubusercontent.com/4446235/109739799-24434080-7c05-11eb-8df6-b39bd88e941a.jpg)

The surfaceflnger process used to be on the tip of list,
But now it is on the bottome of list

**Comment by primiano** [comment]
Ah i see. It's weird, processes should be ordered by their CPU activity (most active processes on the top).
 Could you share a trace where this happens? It doesn't seem to happen with the example trace checked in:

<img width="1412" alt="Screenshot 2021-03-03 at 11 33 50" src="https://user-images.githubusercontent.com/7137473/109799832-61fb9580-7c14-11eb-9fff-870206e121a9.png">

**Comment by LalitMaganti** [comment]
The recent refactor in track logic seems to have broken sorting of the tracks - there's also an internal bug at b/181672328 tracking something similar for profiles.

**Comment by primiano** [comment]
I don't think we ever had any special logic for surfaceflinger, was just based on CPU usage IIRC.
The internal bug you linked is for heap profiles, but turned out they never worked (see r.android.com/1614839)

**Comment by eric4337** [comment]
I'm not able to upload the trace in work environment, but my load is SP1A.210216.002-2021-03-03-01-42-16.
And i'm not sure it is allowed to upload trace for not disclosed load here?

Do you have contact window in Google that I can contact through corp-partner.google.com?

**Comment by primiano** [comment]
Can you email it to primiano@google.com ?

**Comment by eric4337** [comment]
I have submitted through buganizer,
bug id is 182096419
https://partnerissuetracker.corp.google.com/issues/182096419

**Comment by LalitMaganti** [comment]
Internal bug is fixed so mirroring here.
