### ISSUE TITLE
Flamegraph for function calls

### ISSUE THREAD

**Issue by gaogaotiantian** [google/perfetto#105]
Hi,

I noticed some flamegraph UI code is already in perfetto, but it seems like only heap profile is supported?

In theory, with all the function calls recorded, it is possible for perfetto to compute a flamegraph from any number of function calls right? It would be nice if after the user selects some function entries(or a thread), there's a button to compute and visualize the flamegraph of these calls, in addition to show the CPU/wall time of each function.

Is this a feature that's worth considering?

**Comment by primiano** [comment]
Yes that's the plan all along. We should be able to create flamegraphs of horizontal selections even from standard slices.
It will take a while because, in order to make this and many other things happen, we need some internal UI rearchitecturing.

**Comment by LalitMaganti** [comment]
Support for visualizing stack samples with flamegraphs using the UI has been implemented (and has existed for quite some time actually).
