### ISSUE TITLE
What does 'stack_id' mean?

### ISSUE THREAD

**Issue by Kyson** [google/perfetto#108]
I do not understand 'stack_id' meaning in slice table.

Is there a sample picture to illustrate this problem?

https://perfetto.dev/docs/analysis/sql-tables#slice

![image](https://user-images.githubusercontent.com/3901140/110232224-7e226e00-7f57-11eb-87df-5973e8683066.png)

Thx a lot.

**Comment by Kyson** [comment]
Does the same stack_id of slices means same stack traces from root stack to self?

**Comment by chromy** [comment]
Unfortunately I don't have a good diagram to hand that shows this. `stack_id` is a hash of the `name` and `category` fields for the given slice and all of it's parent slices. So yes, if the `stack_id` of two slices are the same it means the "stack trace" from root to self of those slices should be the same. 

The idea of `stack_id` is that it makes per-stack-trace aggregation in SQL easier. You can see the code that determines it [here](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/importers/common/slice_tracker.cc;l=352?q=f:perfetto%20slice_tracker%20).

Hope that helps! Let me know if you have further questions.

**Comment by Kyson** [comment]
@chromy Thx a lot , i got it :-)
