### ISSUE TITLE
[install error] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lolobug** [google/perfetto#109]
OS : mac 11.2.1
command: ./tools/install-build-deps --ui
error stack:

> 6785 verbose stack RangeError: Maximum call stack size exceeded
6785 verbose stack     at RegExp.test (<anonymous>)
6785 verbose stack     at isDepOptional (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:425:27)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:441:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6785 verbose stack     at failedDependency (/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/lib/install/deps.js:457:9)
6786 verbose cwd /Users/lolo/Documents/perfetto/perfetto/ui
6787 verbose Darwin 20.3.0
6788 verbose argv "/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/bin/node" "/Users/lolo/Documents/perfetto/perfetto/buildtools/mac/nodejs/lib/node_modules/npm/bin/npm-cli.js" "install" "--no-save"
6789 verbose node v14.15.4
6790 verbose npm  v6.14.10
6791 error Maximum call stack size exceeded
6792 verbose exit [ 1, true ]

**Comment by primiano** [comment]
Hmm this is weird. I am on mac 12.2.2 and it works fine.
```
$ tools/node --version
v14.15.4

$ tools/npm --version
6.14.10

$ rm -rf ui/node_modules/
$ tools/install-build-deps --ui
INFO:root:Running npm install in /Users/primiano/code/perfetto/ui

> node-sass@4.14.1 install /Users/primiano/code/perfetto/ui/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/darwin-x64-83_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /Users/primiano/code/perfetto/ui/node_modules/node-sass/vendor/darwin-x64-83/binding.node
Caching binary to /Users/primiano/.npm/node-sass/4.14.1/darwin-x64-83_binding.node

> puppeteer@1.20.0 install /Users/primiano/code/perfetto/ui/node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 110.2 Mb [====================] 100% 0.0s
Chromium downloaded to /Users/primiano/code/perfetto/ui/node_modules/puppeteer/.local-chromium/mac-686378

> node-sass@4.14.1 postinstall /Users/primiano/code/perfetto/ui/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/primiano/code/perfetto/ui/node_modules/node-sass/vendor/darwin-x64-83/binding.node
Testing binary
Binary is fine

> protobufjs@6.10.2 postinstall /Users/primiano/code/perfetto/ui/node_modules/protobufjs
> node scripts/postinstall

added 733 packages from 454 contributors and audited 733 packages in 109.367s

41 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
installing semver@^7.1.2
installing chalk@^4.0.0
installing jsdoc@^3.6.3
installing tmp@^0.2.0
installing uglify-js@^3.7.7
installing espree@^7.0.0
installing escodegen@^2.0.0
installing estraverse@^5.1.0
```

I wonder if the problem here is the path `/Users/lolo/Documents/perfetto/perfetto/`, i.e. the double "perfetto".
I wouldn't be surprise if that ends up breaking some regex in some npm package

**Comment by lolobug** [comment]
> Hmm this is weird. I am on mac 12.2.2 and it works fine.
> 
> ```
> $ tools/node --version
> v14.15.4
> 
> $ tools/npm --version
> 6.14.10
> 
> $ rm -rf ui/node_modules/
> $ tools/install-build-deps --ui
> INFO:root:Running npm install in /Users/primiano/code/perfetto/ui
> 
> > node-sass@4.14.1 install /Users/primiano/code/perfetto/ui/node_modules/node-sass
> > node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/darwin-x64-83_binding.node
> Download complete  ⸩ ⠋ :
> Binary saved to /Users/primiano/code/perfetto/ui/node_modules/node-sass/vendor/darwin-x64-83/binding.node
> Caching binary to /Users/primiano/.npm/node-sass/4.14.1/darwin-x64-83_binding.node
> 
> > puppeteer@1.20.0 install /Users/primiano/code/perfetto/ui/node_modules/puppeteer
> > node install.js
> 
> Downloading Chromium r686378 - 110.2 Mb [====================] 100% 0.0s
> Chromium downloaded to /Users/primiano/code/perfetto/ui/node_modules/puppeteer/.local-chromium/mac-686378
> 
> > node-sass@4.14.1 postinstall /Users/primiano/code/perfetto/ui/node_modules/node-sass
> > node scripts/build.js
> 
> Binary found at /Users/primiano/code/perfetto/ui/node_modules/node-sass/vendor/darwin-x64-83/binding.node
> Testing binary
> Binary is fine
> 
> > protobufjs@6.10.2 postinstall /Users/primiano/code/perfetto/ui/node_modules/protobufjs
> > node scripts/postinstall
> 
> added 733 packages from 454 contributors and audited 733 packages in 109.367s
> 
> 41 packages are looking for funding
>   run `npm fund` for details
> 
> found 1 high severity vulnerability
>   run `npm audit fix` to fix them, or `npm audit` for details
> installing semver@^7.1.2
> installing chalk@^4.0.0
> installing jsdoc@^3.6.3
> installing tmp@^0.2.0
> installing uglify-js@^3.7.7
> installing espree@^7.0.0
> installing escodegen@^2.0.0
> installing estraverse@^5.1.0
> ```
> 
> I wonder if the problem here is the path `/Users/lolo/Documents/perfetto/perfetto/`, i.e. the double "perfetto".
> I wouldn't be surprise if that ends up breaking some regex in some npm package

fix "perfetto/perfetto/" not work
and upgrade node version(v14.16.0) not work

**Comment by primiano** [comment]
I am sorry without further steps I don't know how to help. A number of us use macOs and has been working fine.
The local version of node or npm shouldn't matter because the UI has its own hermetic node/npm.
Maybe try to debug yourself or do some search and see if you can figure out the root cause.

Are you sure you don't have some weird `.npmrc` around (e.g. in your home). Try moving/removing that and try again.
(This seems similar to https://github.com/facebook/create-react-app/issues/7674)

**Comment by lolobug** [comment]
> facebook/create-react-app#7674

It's ok now after removing the http proxy in .npmrc
