### ISSUE TITLE
Support protobuf extensions

### ISSUE THREAD

**Issue by skyostil** [google/perfetto#11]
We should support protobuf extensions, so folks can define their own DataSource messages and TrackEvent arguments without having to check them in to Perfetto directly.

**Comment by Kyson** [comment]
Any update here?

**Comment by skyostil** [comment]
We've since landed [extension support in Protozero](https://android-review.googlesource.com/c/platform/external/perfetto/+/1327113), a way to use [custom extension fields inside TrackEvents](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/tracing/test/api_integrationtest.cc;drc=99bf23ef98c8082ce3d7309d9ee549b15ad43ad8;l=1797) and support for [bundling proto extension descriptors together with the trace](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/trace_packet.proto;drc=4bf3c0ed67bc6f4256dfe5412599e3aa7e250176;l=180) so that Trace Processor and Perfetto UI can make sense of the custom types.

So, in theory all the pieces are available, but perhaps the most important part is still work in progress: documentation. Stay tuned!

(@betasheet FYI)

**Comment by betasheet** [comment]
Some documentation exists in https://cs.android.com/android/platform/superproject/+/master:external/perfetto/docs/design-docs/extensions.md, but probably needs updating :) @ddrone FYI
