### ISSUE TITLE
[question] where to modify to trace custom proc/sysfs node?

### ISSUE THREAD

**Issue by jinwooahn** [google/perfetto#110]
Hello. I've noticed that perfetto is great project. My company released new device driver for Linux/Android and it provides proc/sysfs node(knob) for detailed status.
The QA team is going to test the device for a while and check the proc/sysfs node every second.
I'd like to introduce perfetto for tracing custom proc/sysfs node, and trying to find which code to modify. I guess it's similar to poll /proc/meminfo.
Could you guide me or give some hints? I'd like to add new trace point and maybe I could contribute :)

**Comment by primiano** [comment]
The code that polls meminfo is in https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/traced/probes/sys_stats/sys_stats_data_source.cc?q=meminfo%20f:perfetto%20f:%5C.cc

For something custom I'd advise to take a look at the SDK @ https://perfetto.dev/docs/instrumentation/tracing-sdk 
and create a dedicated process.

**Comment by jinwooahn** [comment]
@primiano  Thank you so much!
