### ISSUE TITLE
Duplicate section headers in docs.

### ISSUE THREAD

**Issue by dbaileychess** [google/perfetto#111]
The right-side Navigation sidebar for the sections 'Capturing the profile' under both Native and Java heap sections point to the same location. https://perfetto.dev/docs/case-studies/memory#capturing-the-profile

Looking at it here on github, they append a `-1` at the end to separate the two, but it doesn't look like the generated docs does this.

https://github.com/google/perfetto/blob/master/docs/case-studies/memory.md#capturing-the-profile
https://github.com/google/perfetto/blob/master/docs/case-studies/memory.md#capturing-the-profile-1

**Comment by primiano** [comment]
ah thanks for the report.
@fmayer  I think we should just change the header fragment like we do elsewhere with something like
```
## {#capture-profile-native} Capturing the profile

## {#capture-profile-java} Capturing the profile
```

**Comment by fmayer** [comment]
Thanks for reporting this. Fixed in https://r.android.com/1636480.

**Comment by dbaileychess** [comment]
I noticed the "viewing the data" sections are duplicated too :)
