### ISSUE TITLE
[Question] How to check frame drops from perfetto

### ISSUE THREAD

**Issue by rishikamaljha** [google/perfetto#113]
In systrace report we used to get frame drop data(red frames) i am not able to see that in perfetto. I am using below command

adb shell perfetto -o /data/misc/perfetto-traces/trace_file.perfetto-trace -t 20s sched freq idle am wm gfx view

can you please help me to get report for frame dropd/Jank

**Comment by LalitMaganti** [comment]
There is no direct replacement for the frame drop data from chrome://tracing. We found it to be inaccurate in a lot of cases  and it was highly complex so we decided not to port it over.

In S, we plan on introducing a much more detailed replacement called "frame timeline" but this is still work in progress so documentation on this is TBD.

**Comment by rishikamaljha** [comment]
Thanks for the update @LalitMaganti . 

What do u mean by "S" here ? 

In Pefetto UI i can see option for metrics -> Android_jank . Is this under progress ?

**Comment by LalitMaganti** [comment]
By S I mean Android 12.

Yes the jank metric and related UI is being worked on actively. You can follow the commits as they happen on this repo.
