### ISSUE TITLE
Instant event visualization

### ISSUE THREAD

**Issue by gaogaotiantian** [google/perfetto#120]
Hi,

I tried to use Instant Event from Chrome Trace Format, and did not see any visualization of it. Does perfetto support Instant Event, or will it do in the future?

**Comment by primiano** [comment]
@LalitMaganti @chromy @betasheet : one of them should know :)

**Comment by betasheet** [comment]
Not currently supported, I believe. See here for the supported phases: https://source.chromium.org/chromium/chromium/src/+/master:third_party/perfetto/src/trace_processor/importers/json/json_trace_parser.cc;l=129

I'd recommend using the proto trace format documented on perfetto.dev instead if you can.

**Comment by gaogaotiantian** [comment]
Okay. I'm gradually transitioning to perfetto now so I'll probably have to stick with json for a while, but thanks for the info! I'll try the proto trace format in the future!
