### ISSUE TITLE
minimum protoc version to build proto

### ISSUE THREAD

**Issue by gaogaotiantian** [google/perfetto#121]
Hi,

What is the minimum protoc version to build the trace proto? I'm using Ubuntu 18.04 and installed protoc by ``sudo apt install protobuf-compiler``. The version I got is ``libprotoc 3.0.0``. However, when I try to build the proto with ``protoc -I=./ --python_out=./ ./protos/perfetto/trace/trace.proto``, I got errors like ``protos/perfetto/common/builtin_clock.proto:31:12: Missing numeric value for enum constant.``

Is the because I'm using a not recent enough version of protoc and I should install from pre-built binaries from github, instead of using ``apt install``?

**Comment by primiano** [comment]
The version of protoc form apt should be irrelevant. WHen you build perfetto, the tools/install-build-deps script pulls the right version that is guaranteed to work.
3.0.0 should be fine TBH I don't think that explains the error.

**Comment by gaogaotiantian** [comment]
Is it possible to only build the proto I need, without building the whole perfetto? I only need the ``.py`` file to write trace proto on my own.

**Comment by primiano** [comment]
Oh I see. yes should be possible. I don't know what that error comes from. Maybe comment out the reserved fields? (But that syntax has been there since forever)

**Comment by gaogaotiantian** [comment]
Okay I just confirmed the latest protoc (3.15.5) works with the same command. It is the old version that stopped it from building. Close it.
