### ISSUE TITLE
TrackDescriptor emitted after TrackEvent

### ISSUE THREAD

**Issue by rickvanprim** [google/perfetto#123]
Inside of `TraceForCategoryImpl()`, the logic emits a `TrackEvent` and then checks if this is the first time that track has been seen, and if so emits the `TrackDescriptor`.  This guarantees that for `TrackDescriptor`s emitted this way, their first `TrackEvent` is always dropped.  Switching the emission order seems like it should fix the issue.

**Comment by LalitMaganti** [comment]
This was fixed a while back.
