### ISSUE TITLE
Question of how to modify UI correctly?

### ISSUE THREAD

**Issue by kyleada** [google/perfetto#13]
Hi, I want to add more info, such collect histories,  in UI page。
I met two poblems:
1.  Sometimes, I changed  fronted ts file, then compiled and run it. But web UI didn't show ‘New version, Reload', I'm not sure it's the cause of 'new version check' OR 'compiler not recognize correctly my changed files'.  How can I make it correct ?

2. Added scss files not worked.  I add new scss files in assets, also changed BUILD.gn
`scss_root = "src/assets/perfetto.scss"
scss_srcs = [
  "src/assets/typefaces.scss",
  "src/assets/sidebar.scss",
  "src/assets/topbar.scss",
  "src/assets/record.scss",
  "src/assets/common.scss",
  "src/assets/modal.scss",
  "src/assets/details.scss",
  "src/assets/extra.scss",
  "src/assets/history.scss",
]`
 I checked the out files <perfetto>, 'history.scss' content was not included.

I want to know where I was wrong.

Thank you for your reply

**Comment by primiano** [comment]
How are you building the ui? with `ninja -C out/xxx ui` ?
The steps you describe seem correct and whta we do every day.

Does it work if you ctrl+shift+R  (force reload) or open in incognito?
Does it work if you re-build from clean? (`gn clean out/xxx && ninja -C out/xxx`)

**Comment by kyleada** [comment]
These two days, "Reload" shown every time when I changed frontend ts file. :)
Thank you~
