### ISSUE TITLE
Perfetto UI crash when starting record

### ISSUE THREAD

**Issue by CaiChangShui** [google/perfetto#134]
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

NetworkError: Unable to reset the device.
{}

v14.0.231 465b9a4473353091c7048b53ad90607295f86a4a
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

**Comment by primiano** [comment]
This is a known issue, somehow the webusb logic doesn't work on Windows. 
We didn't have the time to look into that yet.

**Comment by primiano** [comment]
This has been fixed in r.android.com/1726091
