### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by gaogaotiantian** [google/perfetto#135]
Hi,

I know this might be a silly question but I'm a bit confused about what I should do when I use perfetto in my own project, so I'm trying to make it super clear.

I modified some source code in perfetto to make it suit my project. I only need the distributed files. My question is, what should I do to comply to the Apache License? My project is under Apache License V2 as well.

For the forked version that I modified and uploaded to github, do I need to label the files that I changed?

For my own project which contains the distributed version of perfetto, is there anything I should do? I put perfetto in my LICENSE file like some Apache project did, but not sure what is the perfect answer here.

Thanks

**Comment by LalitMaganti** [comment]
We're definitely not lawyers so I don't think it would be appropriate to comment on exactly what you should do in your particular case.

Reading the "HOW TO APPLY THE APACHE LICENSE TO YOUR WORK" section of https://www.apache.org/licenses/LICENSE-2.0 may be a good place to start research on what might be appropriate.
