### ISSUE TITLE
Assertion in UI due to timestamps

### ISSUE THREAD

**Issue by danielfriederich** [google/perfetto#137]
I'm running into an assertion in the UI code when I try to view a specific trace file.
I did collect the trace on our own internal device here, so sorry, cannot upload it here.

But basically, it contains both ftrace and logcat messages. But the logcat messages have some questionably old timestamps, way too old. Basically there is some bug somewhere else that occasionally causes incorrectly old logcat timestamps. I did see timestamps of 1980 in the past (oddly not just epoch 0, Jan 1970). Anyway, that is a bug on its own too, of course.

In the trace UI, it shows one pixel for the logcat messages on the left, and after zooming the ftrace messages on the right. Or more specifically it shows that after I did add one of the possible changes below. Out of the box, the code does run into the assert when zooming to the left, and after that, the UI is not responsive anymore.

The assertion is the 
assertTrue(start <= end);
code in the [TimeSpan constructor in time.ts](https://android.googlesource.com/platform/external/perfetto/+/refs/heads/master/ui/src/common/time.ts#85).
 Not sure this should assert, if it just logs an error, the UI keeps working. 

The caller is my case is this code in [search_controller.ts
](https://android.googlesource.com/platform/external/perfetto/+/refs/heads/master/ui/src/controller/search_controller.ts#91)
    this.previousSpan = new TimeSpan(
        Math.max(newSpan.start - newSpan.duration, -TRACE_MARGIN_TIME_S),
        newSpan.end + newSpan.duration);

Note that it uses Math.max() to limit the start of the TimeSpan to some fixed time just before 0 (-0.000001), but it does no do the same for the end. And in my case, the end is long before 0, e.g. one newSpan I did see the assert for:
newSpan:{"start":-803247.4333605997,"end":-649669.3316803429}

If I do the Math.max() also for the end, then the UI is once back to "working", at least back to showing what it can.

    this.previousSpan = new TimeSpan(
        Math.max(newSpan.start - newSpan.duration, -TRACE_MARGIN_TIME_S),
        Math.max(newSpan.end + newSpan.duration, -TRACE_MARGIN_TIME_S));

Not sure if this is the proper fix for the assert, if the code somehow should for example not create a time span with a negative start (and in this case, even a negative end).

So changes which fix the issue for me:
- not to assert, but to just log the failure in TimeSpan
- to also limit the end of the previousSpan to the same -TRACE_MARGIN_TIME_S area

The call stack shown in the error dialog:

Viewed on: http://localhost:10000

Uncaught Error: Failed assertion
Error: Failed assertion
    at Object.assertTrue (http://localhost:10000/v1.4/controller_bundle.js:336:15)
    at new TimeSpan (http://localhost:10000/v1.4/controller_bundle.js:655:17)
    at SearchController.run (http://localhost:10000/v1.4/controller_bundle.js:83599:29)
    at SearchController.invoke (http://localhost:10000/v1.4/controller_bundle.js:788:31)
    at http://localhost:10000/v1.4/controller_bundle.js:815:41
    at TraceController.invoke (http://localhost:10000/v1.4/controller_bundle.js:821:34)
    at http://localhost:10000/v1.4/controller_bundle.js:815:41
    at AppController.invoke (http://localhost:10000/v1.4/controller_bundle.js:821:34)
    at Globals.runControllers (http://localhost:10000/v1.4/controller_bundle.js:11253:71)
    at Globals.dispatchMultiple (http://localhost:10000/v1.4/controller_bundle.js:11230:14)

v1.4 f57ea2c14f2839ae6b3668709d485f969a404145
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

**Comment by LalitMaganti** [comment]
@chromy for thoughts.

**Comment by primiano** [comment]
@danielfriederich  Can you try again with ToT? We did a bunch of changes to the UI, this might be fixed now.

**Comment by LalitMaganti** [comment]
Considering the amount of changes the UI has gone through since this report, this should be fixed. Please reopen if you're still encountering this.
