### ISSUE TITLE
Install on Ubuntu 16.04

### ISSUE THREAD

**Issue by zaccharieramzi** [google/perfetto#139]
Hi,

Following [this piece of advice](https://github.com/google/trace-viewer/issues/298#issuecomment-846319027), I wanted to use perfetto for loading my big trace file.

Unfortunately my file was too big for the online app, and so I had to download the app.
When executing (`./trace_processor --httpd ~/Downloads/trace.json`), I am currently facing the following issue:

```
/tmp/trace_processor_shell-linux-a3ce2cbf4cbe4f86cc10b02957db727cecfafae8: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/trace_processor_shell-linux-a3ce2cbf4cbe4f86cc10b02957db727cecfafae8)
/tmp/trace_processor_shell-linux-a3ce2cbf4cbe4f86cc10b02957db727cecfafae8: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/trace_processor_shell-linux-a3ce2cbf4cbe4f86cc10b02957db727cecfafae8)
```

From what I see (`ldd --version`), I indeed have GLIBC version 2.23 installed.
[Apparently, it would be a bad idea](https://stackoverflow.com/questions/62324422/version-glibc-2-28-not-found#comment114239671_62390881) to try to install another version of GLIBC.

I would therefore like to know if there is a way to install perfetto on ubuntu 16.04 with GLIBC 2.23.

Thanks

**Comment by LalitMaganti** [comment]
This is problem is the same as #117.

You need to build trace processor on some machine that has a lower glibc (probably on the machine you are trying to load the trace on). See https://perfetto.dev/docs/contributing/build-instructions for details on how to do this

We are working on fixing this issue.
