### ISSUE TITLE
Fail to render Counter events on multi-thread trace

### ISSUE THREAD

**Issue by gaogaotiantian** [google/perfetto#140]
Perfetto can't render Counter events for multi-thread trace, not sure what went wrong.

```
{
	"traceEvents": [{
		"pid": 1,
		"tid": 1,
		"name": "test",
		"ts": 1,
		"dur": 1000,
		"ph": "X",
		"cat": "fee"
	}, {
		"pid": 1,
		"tid": 2,
		"name": "test",
		"ts": 1,
		"dur": 1000,
		"ph": "X",
		"cat": "fee"
	}, {
		"pid": 1,
		"tid": 2,
		"name": "counter",
		"ts": 5,
		"ph": "C",
		"args": {
			"value": 4
		}
	}]
}
```
![image](https://user-images.githubusercontent.com/13121107/120526759-6d369c80-c38e-11eb-9bb3-2b9e5e32682d.png)

It works if the Counter event does not have ``tid`` field. The chrome trace format mentioned the Counter events are "process-local", but the examples it gave in https://github.com/catapult-project/catapult/blob/master/tracing/test_data/instance_counters.json does have ``tid`` field.

It also works if there's only one thread in the process(and of course the Counter event has the same tid as that thread).

I think this should be considered as a Perfetto bug and should in theory be easy to fix?

**Comment by ys2843** [comment]
Observed the same issue, Counter event with `tid` works in catapult_trace_viewer, but not Perfetto. And after deleting `tid`, it works as expect.

**Comment by LalitMaganti** [comment]
Fixed by https://github.com/google/perfetto/commit/9953102813e473dba8cd7d714d70ca33d1a98fb7
