### ISSUE TITLE
Perfetto needs to display the untruncated name and timing on timeline hover

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#142]
Having to physically select every timeline track just to see the untruncated name and timing is tedious.   With hover, you can also compare a selected timing in the bottom, and another one in the timeline.  See https://github.com/jlfwong/speedscope for a good example of this, and that profiler is also WebGL accelerated and has a lot of vary nice analysis tools on the trace files.  The only downside is speedscope can only display a single thread on screen at a time.

**Comment by primiano** [comment]
I am not fully sure I understand which "truncated name" we are talking about. Sorry there are so many names around, mind being more specific?

As per WebGL acceleration, fun fact: in the early days of perfetto UI we tried a WebGL variant and it was actually slower (plus font rendering was worse). Turns out that 2d canvas operation can be actually faster on a canvas if the browser supports accelerated canvas (like Chrome does).
(But then I am not sure how webgl is related with the bug at all here)

**Comment by alecazam** [comment]
Here's what I get in speedscope when I hover over any of the flamechart sections.  Even if the name is truncated, the name and timing are still displayed.  Also the time is correct in milliseconds, not seconds as per the other bug I mentioned.  I'm suggesting that this is super convenient and means that I don't have to click on every bar and I can compare the hovered bar to a selected bar lower down the flame chart or in the next frame's worth of data by looking at the timings presented at the bottom for the selection.

![image](https://user-images.githubusercontent.com/3750359/120916268-888afb80-c65d-11eb-8937-ad430b511d65.png)

**Comment by alecazam** [comment]
For example, I have no idea what's in these bars, but I also don't want to zoom into the flame chart more since I have context that I'm looking at across the whole flame chart.  I just want to hover and see which of these 3 M's is the bar I'm looking for.

![image](https://user-images.githubusercontent.com/3750359/120916346-f7685480-c65d-11eb-8e79-e52da7d1e03d.png)

**Comment by primiano** [comment]
Ah I see, that's a good FR.
Thanks for the sreenshots, they help.

**Comment by alecazam** [comment]
Okay, looks like hover was added to display the full name, but where is the timing?   I need the name and the data without having to select a block.  Could times be added in as per above?

**Comment by alecazam** [comment]
I noticed this was added recently.  Thank you for implemeneting.  That really helps when hovering over tiny slivers, and gives useful feedback without having to change the selection (and detail pane).
