### ISSUE TITLE
Is there any guide to compile proto files?

### ISSUE THREAD

**Issue by shovsj** [google/perfetto#147]
Hi guys, 

First, thank you guys for developing and maintaining such a good open source software.

I am interested in visualizing my deep learning profiling result which is came from Nsight systems, nvidia's gpu profiler.
Actually, they provide a visualizer but there are several limitations.
So I am considering to use your fancy ui, and sql processor.

For this, what I want is that given a profiling result, I would like to convert this into your format.
Then, I can fully use your functionalities.

To my best knowledge, I need to compile your proto files (I prefer python, so .py files), and based on these files I can generate a trace file, right?

I just tried using protoc, but It seems like there is some proper way to profile, maybe the order?
So, if there is any reference, please let me know.

it seems like there was similar discussion,
https://github.com/google/perfetto/issues/121
https://github.com/google/perfetto/issues/122
But, I couldn't find any references.

Thanks.

**Comment by primiano** [comment]
Have a look to //test/trace_processor in the repo
You can either synthesize them in python (look at the .py files) or synthesize a pbtx proto and compile it with protoc.

**Comment by shovsj** [comment]
Thanks. I think this is exactly what I wanted! Closing the issue.

**Comment by shovsj** [comment]
Sorry I think I just misunderstood. so opening this issue again.

I get several questions related to this test codes.
According to the index file,
https://github.com/google/perfetto/blob/2d5f1e928ba4c311c9f7c911310e0d77d757222e/test/trace_processor/process_tracking/index#L4

I just ran the command but, got an error message.
According to the help, it requires the location of trace descriptor.

```
python3 synth_process_tracking.py --help
usage: synth_process_tracking.py [-h] trace_descriptor

positional arguments:
  trace_descriptor  location of trace descriptor

optional arguments:
  -h, --help        show this help message and exit

```

according to the source code,
https://github.com/google/perfetto/blob/2d5f1e928ba4c311c9f7c911310e0d77d757222e/test/synth_common.py#L765
this argument is passed to open the file and parse the string to generate descriptor
```
def read_descriptor(file_name):
  with open(file_name, 'rb') as f:
    contents = f.read()

  descriptor = descriptor_pb2.FileDescriptorSet()
  descriptor.MergeFromString(contents)

  return descriptor
```
Here I think the file should be the protoc compiled. (I misunderstood that I can use the .proto file without compiling)
```
protoc can output a FileDescriptorSet – which represents a set of .proto files – using the --descriptor_set_out option.
``` from https://developers.google.com/protocol-buffers/docs/techniques

So, I need to compile .proto files again. I need _pb2.py file or DescriptorSet file, which can be used like in the test scripts.
How can I get the DescriptorSet file? or should I complie all the .proto files?

As I mentioned earlier, I am new to protobuf, so correct me if I was wrong.

I think while building there seems to be a related logic, but I couldn't find this.

**Comment by LalitMaganti** [comment]
So your understanding of Python protobuf is correct - either you need _pb2.py files or DescriptorSet to use protos. Perfetto uses the DescriptorSet approach because it's more flexible for our needs but it's also more difficult to use that _pb2.py.

You can generate the trace.descriptor file by following the instructions at https://perfetto.dev/docs/contributing/build-instructions to setup your environment and build all the Perfetto targets. The trace.descriptor file will then be generated at `<your out directory>/gen/protos/perfetto/trace/trace.descriptor`

**Comment by shovsj** [comment]
Many thanks guys.
I just built all the Perfetto targets and I could find the DescriptorSet file according to your reply. 

Closing the issue.
