### ISSUE TITLE
NuGet package for trace_processor_shell

### ISSUE THREAD

**Issue by KyleStorck** [google/perfetto#148]
Hello. This is a follow-up to the discussion in [this issue](https://github.com/google/perfetto/issues/84) where @ivberg  and @primiano discussed building trace_processor for Windows in order to build a Perfetto plugin using the [Windows Performance Toolkit](https://github.com/microsoft/microsoft-performance-toolkit-sdk).

I have started that work and have a basic working version of that. We can now view basic Perfetto events in [WPA](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer). It works by kicking off trace_processor_shell and making SQL queries over HTTP.

We are thinking about how best to include trace_processor_shell.exe in our plugin. What are your thoughts on having a NuGet package for Perfetto binaries? We are currently using the Google.Protobuf NuGet package, so it would make it really nice if we could get trace_processor binaries the same way. If you wanted to provide guidance on creating a NuGet package we could help and submit the PR ourselves.

**Comment by primiano** [comment]
> Hello. This is a follow-up to the discussion in this issue where @ivberg and @primiano discussed building trace_processor for Windows in order to build a Perfetto plugin using the Windows Performance Toolkit.

Oh hey, yes remember that.

> I have started that work and have a basic working version of that. We can now view basic Perfetto events in WPA. It works by kicking off trace_processor_shell and making SQL queries over HTTP.

Oh wow whohoo. Is there something I can try / instructions?

> We are thinking about how best to include trace_processor_shell.exe in our plugin. What are your thoughts on having a NuGet package for Perfetto binaries? We are currently using the Google.Protobuf NuGet package, so it would make it really nice if we could get trace_processor binaries the same way. If you wanted to provide guidance on creating a NuGet package we could help and submit the PR ourselves.

Ah interesting, here's what's going on on our side.
Every month we tag a new release of perfetto (e.g. [v17.0](https://github.com/google/perfetto/tree/v17.0) few days ago).
Today we only release sources, however, this is going to change soon.

@LalitMaganti is working on integrating perfetto on the chromium [LUCI](https://chromium.googlesource.com/infra/infra/+/refs/heads/main/doc/users/services/about_luci.md) infrastructure to generate prebuilts for every release.

At the end of the day, our rough plan is that every month, for every release, we'll have prebuilts for (Linux, Mac, Windows, Android) for the main targets (traced, traced_probes, trace_processor_shell). Fine details are still TBD but those prebuilts will be available either on a GCS (google cloud storage) bucket and/or attached to on GitHub  under each release.

I am not familiar with NuGet (seems more a .net packate manager though no? TP is not .net, is a native executable).
If somebody wants to maintain packaging on NuGet on something else I'd be fine, but I'd ask for you to maintain that infra.

I think it's reasonable for us to stop to the point where we monthly publish executables on GitHub or GCS.

Does that make sense?

**Comment by KyleStorck** [comment]
Thanks for the info on your coming plans. It's exciting that there will be prebuilts coming soon. That sounds like a good start. Let me think if I can take advantage of GitHub/GCS releases and get back to you on the NuGet work.

**Comment by KyleStorck** [comment]
And I'll get back to you @primiano on how you can try out the plugin. We're working out the proper process for sharing the new plugin externally.

**Comment by KyleStorck** [comment]
Hi @primiano,

We have a version of the Perfetto plugin you can try. The [Perfetto_108](https://github.com/microsoft/Microsoft-Performance-Tools-Linux/tree/perfetto_108) branch in our repo works with the publicly available WPA. 

1. Checkout the [Perfetto_108](https://github.com/microsoft/Microsoft-Performance-Tools-Linux/tree/perfetto_108) branch and build the solution. See the [PreReqs ](https://github.com/microsoft/Microsoft-Performance-Tools-Linux/tree/perfetto_108#how-to-run-the-tools) in the ReadMe
2. You will need to manually copy trace_processor_shell.exe to the output directory for PerfettoCds (PerfettoCds\bin\Release\netstandard2.1). The shell from the current July release works.
3. Download WPA. See the [instructions ](https://github.com/microsoft/Microsoft-Performance-Tools-Linux/tree/perfetto_108#how-to-run-the-tools) in the ReadMe.
4. Start WPA from cmd line specifying the PerfettoCds output directory. This loads the Perfetto plugin. The directory should look like this after you added the trace_processor_shell.exe.
`wpa -addsearchdir c:\wpalttng\PerfettoCds\bin\Release\netstandard2.1`
![image](https://user-images.githubusercontent.com/1233941/126681828-10f2c91a-87fe-4f53-b8b0-efcaac2346c4.png)
5. Then you can load a Perfetto trace. It currently supports viewing basic app events and debug annotations.


Second topic: NuGet packaging. I see that you are currently working on uploading artifacts to GCS ([Perfetto.py](https://github.com/google/perfetto/blob/master/infra/luci/recipes/perfetto.py)). Is this still a work in progress? Will this be "released" in an upcoming release? I was thinking I could piggy-back on this for generating a NuGet release. Google.Protobuf does a similar thing where they pull all the binaries from a maven repository and generate a NuGet package out of it ([build_tools.sh](https://github.com/protocolbuffers/protobuf/blob/master/csharp/build_tools.sh)). I could either add another routine to Perfetto.py where I put all the artifacts into a NuGet package or I could make a separate script that pulls the artifacts out of GCS and then generates a NuGet package. Do these options sound okay?

**Comment by primiano** [comment]
Oh sweet will try out as soon as I have some spare time. Thanks a lot for the instructions.

> I see that you are currently working on uploading artifacts to GCS (Perfetto.py). Is this still a work in progress? Will this be "released" in an upcoming release?

Yes, this is very new. We just have the very first auto-built packages.
You can see them here: https://chrome-infra-packages.appspot.com/p/perfetto/trace_processor_shell/windows-amd64/+/
Right now they are built off a random version in master, but if there are no surprises the next monthly version will have prebuilts for the release tag.

The plan is that for every tag we will release the same binaries both on:
- the CIPD location mentioned above
- the GCS bucket gs://perfetto-luci-artifacts, e.g. gs://perfetto-luci-artifacts/aab2d4af0bbce0d8d5cc45202d6eec8d130dbea5/windows-amd64/trace_processor_shell.exe

eventually that sha1 will be v18.0 or similar for release tags.

This is not set in stone for now, want to see working for a couple of releases. But if something explodes we might stick with that.

>  I could either add another routine to Perfetto.py where I put all the artifacts into a NuGet package or I could make a separate script that pulls the artifacts out of GCS and then generates a NuGet package. Do these options sound okay?

I don't have strong opinions. Both work for me as long as we don't have to maintain some other packaging system.

**Comment by primiano** [comment]
Update we just released the first release that contains prebuilt built via Chromium's LUCI infrastructure.

I uploaded them here:
https://github.com/google/perfetto/releases/tag/v18.0

They are taken from 
`gs://perfetto-luci-artifacts/45571639857aa59be41f77a2d774f6577d03c86c` where 45571639 is the SHA1 of the v18.0 release.

**Comment by KyleStorck** [comment]
That's great, thanks primiano!

**Comment by LalitMaganti** [comment]
Closing as I think we've covered all the questions here.
