### ISSUE TITLE
Provide registration for custom analysis panes

### ISSUE THREAD

**Issue by kcoop** [google/perfetto#15]
Some background: we're building a tool to help us with post mortem log analysis, and we've been looking to use a customized catapult trace viewer as a component in our own page for log-oriented usage. Catapult has a fairly flexible and component driven architecture that we can work with - we hope to be able to do the same with Perfetto, as trace viewer is being sunsetted.

For our scenario, we're working to view our logs + crash stacks with a visual tool. This will help us visualize logs by process/thread/time, navigate thread flow, and superimpose crashes & exceptions near where they occurred. Also in general, we want to be able to browse the visual story of code execution, as kind of a living architectural document. So this is less about performance monitoring (though that will still be helpful), and more about sleuthing out problems.

A key feature of this is the ability to select a collection of events, whether they’re duration or instant, and view them like a super rich log file: in chronological order, with indentation/flyovers/coloring providing context when necessary. This in contrast with the analytics pane provided by trace viewer, where duration based events immediately aggregate for performance analysis.

We expect to write this pane ourselves (and would be happy to contribute back if desired), but need hooks to be able to register it.

**Comment by kcoop** [comment]
If api exposure  is an issue (https://github.com/google/perfetto/issues/14), would you be open to incorporating said pane that we offer up as a PR?

**Comment by primiano** [comment]
It depends on how much self-contained that is (vs making changes to state etc) .
Contributions are welcome in the project in general. it's just that the UI is in a state where we'd like to get some clean extension points / API, but this will get harder if we pile up features that we'd then need to refactor.

If you have a sketch PR we can definitely take a look before you go too deep. It doesn't have to be too polished, doesn't even have to work fully, it just needs to give a rough idea or where it's going.

@chromy @isabelle49 FYI

**Comment by kcoop** [comment]
Will do.
