### ISSUE TITLE
Support for "bottom up" and "top down"

### ISSUE THREAD

**Issue by mattgodbolt** [google/perfetto#151]
Coming from the in-built chrome tools, perfetto looks awesome, except for missing stack information like "bottom up" and "top down" aggregation views. Is this planned? Thanks so much!

**Comment by primiano** [comment]
Yes I fully agree, assuming you talk about the flamegraph.
There is a lot of work planned on the flamegraph we are admittedly very behind on it.

What we have right now is really just a v0 because we had to get something to work with some memory emergency and... something was better than nothing :)

Here's a bunch of things that need to happen on this front:

1. In general the flamegraph should not be just about heap dumps. What we really want is being able to select an arbitrary time-range of slices (e.g. TRACE_EVENT annotations) and flame-graphing them as well . This is more a priority now that we have callstack sampling integrated in perfetto. RIght now we have zero ui (neither top down or bottom up) for callstack samples (it works only for heap dumps), even though the data is [there](https://perfetto.dev/docs/analysis/sql-tables#callstack-profilers).

2. Yes, what we need here is the union of: (1) having the ability of inverting the callstack; (2) having the ability to "pivot" a frame in the middle, so you can have a "butterfly" where you pin a frame and break down in both directions (caller and callee)

Let's update this thread 1-2 months. We have somebody new on the team (@octaviantu ) who is ramping up on the UI. He'll start working on flamegraph soon after their initial rampup.

I am happy to have a public brainstorming doc with features / ranking before we start on it, feedback on this would be more than welcome, especially given the timing of the project.

**Comment by primiano** [comment]
Just to be clear, what I was talking about is really this:
https://ui.perfetto.dev/#!/?s=a3b5bc77e58cf46b344b89e8101c340e9193fc93d3fd91d3ab982ab7e2efa7a

![Screenshot 2021-07-14 at 22 38 18](https://user-images.githubusercontent.com/7137473/125696492-5655cf2c-adeb-438c-93bb-6ac6de7a5d51.png)

But as I mentioned today it only works for heap profiles and not for the rest.

**Comment by mattgodbolt** [comment]
100% yes, the flame graph but for CPU time. It's invaluable to work out what's going on in a large profile. Right now I "just" load it into Chrome tools but that's less than ideal if I can use perfetto instead!

**Comment by primiano** [comment]
Just to understand your case a bit better: what's your source of data right now? Do you have some callstacks coming from ...? I guess you have something that emits a JSON trace or similar? How does that look like?

**Comment by mattgodbolt** [comment]
We have a custom format which we convert to JSON chrome trace format. It's a sequence of heavily nested 'B' and 'E'  types (field `ph`) over multiple processes and threads.

**Comment by mattgodbolt** [comment]
Example output we see in Chrome when we load in our converted JSON (data is proprietary, hence my attempts to blur things!)
![image](https://user-images.githubusercontent.com/633973/125698664-1e97d50b-9b3d-44b5-ac51-b64e97074db9.png)

**Comment by mattgodbolt** [comment]
I guess this is related to #105

**Comment by primiano** [comment]
oh yeah the discussion here is really:

1. #105 -> selecting slices should generate flamegraph
2. This bug: flamegraphs should have bottom-up and butterfly/pivoting

I would still keep them separate, as #105 is really just about slices -> flamegraph

**Comment by chromy** [comment]
To update everyone our current plans for improving flamegraphs in the UI are detailed at: https://docs.google.com/document/d/1ARFinlfbSlnmTnr5d2D3obSb3CvzLMRXXi34V9qqZkg/edit?usp=sharing
To access the doc you'll need to join the following group: https://groups.google.com/forum/#!forum/perfetto-dev.

The first half covers the UX we're planning and the various sources of data we want to turn into flamegraphs. We would be super interested in any comments people have. The second half is implementation details which are probably not of much interest outside of the team.

**Comment by mnovakovic** [comment]
> To update everyone our current plans for improving flamegraphs in the UI are detailed at: https://docs.google.com/document/d/1ARFinlfbSlnmTnr5d2D3obSb3CvzLMRXXi34V9qqZkg/edit?usp=sharing
> To access the doc you'll need to join the following group: https://groups.google.com/forum/#!forum/perfetto-dev.
> 
> The first half covers the UX we're planning and the various sources of data we want to turn into flamegraphs. We would be super interested in any comments people have. The second half is implementation details which are probably not of much interest outside of the team.

Thanks for providing the links, I am really glad that flamegraph-like features are already planned!

Do you have any way to reasonably estimate the time it will take to add this feature, based on the current status, how many people you have working on this and how long it took for other similar features to be completed?

**Comment by q-flexai** [comment]
Hey guys, flamgegraphs visualization directly in perfetto would be awesome :)   I've had a look at the shared doc proposal and was wondering if any work had been done since its creation in 2021?

**Comment by LalitMaganti** [comment]
@stevegolton might be able to comment on plans around flamegraphs.

**Comment by lf-** [comment]
Hi! I am considering using Perfetto for profiling Nix expression evaluation in [Lix](https://lix.systems). Currently my prototype generates slices for each interpreter-level function call (at remarkably low overhead, great job by the way!), and I would love to be able to generate a flamegraph for those to understand what is particularly expensive evaluation wise in the nixpkgs standard library.

I am not using callstack sampling, and my traces are entirely synthetic. I am linking to protozero and wrote about 400 lines of code to replace the perfetto application-side library (the reason for this is that it's a large dependency and more crucially, the interning support did not appear to be exposed, and for performance reasons we would like to hook it to our own interner to avoid performing string lookups).

**Comment by LalitMaganti** [comment]
> I would love to be able to generate a flamegraph for those to understand what is particularly expensive evaluation wise in the nixpkgs standard library.

Funnily enough, I'm currently in the process of doing a root to stem rewrite of flamegraphs, should have the improvements landing over the next few weeks.

> the interning support did not appear to be exposed

Yeah the interning is an implementation detail of the SDK not a plug-and-play component that others can use.

**Comment by jordalgo** [comment]
Another vote for some generic flame graph support. I'm writing a tool to take the output from [bpftrace](https://github.com/bpftrace/bpftrace) and convert it to chrome trace format.

**Comment by LalitMaganti** [comment]
95% of this work has been done: we now have a flamegraph component which can visualize any tree like structure in a very generic way. 

The last missing piece is adding a button (similar to adding a debug track) to visualize as a flamegraph.

**Comment by jordalgo** [comment]
@LalitMaganti Great to hear! Will it be able to take a grouping of trace events with call stacks e.g. `"stack": ["frameA", "frameB", "frameC"]` and visualize that as well?

**Comment by LalitMaganti** [comment]
If that's some feature of the Chrome JSON format, not something I'm planning on: see https://perfetto.dev/docs/faq#why-does-perfetto-not-support-lt-some-obscure-json-format-feature-gt- for context.

**Comment by LalitMaganti** [comment]
https://r.android.com/3189530 fully implements the original request on this bug (top-down, bottom-up, pivot). Any other requests should be tracked in other bugs.
