### ISSUE TITLE
show args info as systrace

### ISSUE THREAD

**Issue by fireaxe-hq** [google/perfetto#152]
in systrace, "wakeup from tid" is shown by clicking "Runnable timeslice", which is useful for checking how wake the thread up.

**Comment by primiano** [comment]
Don't we have the same in Perfetto already? i.e. this:

![Screenshot 2021-07-15 at 11 15 19](https://user-images.githubusercontent.com/7137473/125771836-c2c6ae79-c455-4409-8bed-6145d4e78b2a.png)

**Comment by fireaxe-hq** [comment]
cool, it looks even better than systrace.
