### ISSUE TITLE
How can I see network traffic for my app using perfetto?

### ISSUE THREAD

**Issue by jay0129** [google/perfetto#156]
I tried various datasources but I **cannot** find **network** traffic for my application.

Can I have raw data of network traffic per each X-axis like AndroidStudio profiler does?
![image](https://user-images.githubusercontent.com/62974859/127098898-d42d8fd7-7fb8-4af6-b975-b29c175851c9.png)

**Comment by primiano** [comment]
There is no network information in traces yet.
Android studio likely takes that from something != trace (by polling at some /proc counter perhaps).

Nothing planned too soon on this front, so closing this.
