### ISSUE TITLE
Finding the absolute start and end time of a trace

### ISSUE THREAD

**Issue by KyleStorck** [google/perfetto#163]
I am interfacing the trace with SQL queries through trace_processor_shell. The values in the trace_bounds table appear to show timestamps for the first and last events, but I want the absolute time when a trace started and stopped. Looking at the clock_snapshot table and tracing_service_impl.cc, the very first clock snapshot appears to be from the start of the trace, but it's unclear to me if the final clock_snapshot is the absolute end of the trace. It seems like the final clock_snapshot is the last snap from sometime in the final 6ms. Can you help clarify? Thanks!

**Comment by LalitMaganti** [comment]
I think Hector's comment pretty comprehensively covers how to do this so closing.
