### ISSUE TITLE
UI feature request: Arrow keybindings for WASD

### ISSUE THREAD

**Issue by sudara** [google/perfetto#165]
I'm on a dvorak keyboard layout, so the WASD zoom keybindings are somewhat awkward since the letters are scattered and not physically in an up/down/left/right arrangement.

It would be amazing if the arrow keys could also be bound to the zoom functionality.

If not, I'll survive! I'm currently switching layouts every time I'm using perfetto.

Thanks for all your work on this tool, it's amazing and keeps getting better.

**Comment by sudara** [comment]
This is embarrassing, but apparently the WASD keys still work in the dvorak layout! I just never thought of trying it. 😆

**Comment by primiano** [comment]
Yes was going to say, at some point in the past we added also the corresponding dvorak bindings. :)

**Comment by sudara** [comment]
Blew my mind. What thoughtfulness :)
