### ISSUE TITLE
Customized plugin for perfetto UI

### ISSUE THREAD

**Issue by dionysus1016** [google/perfetto#168]
I am wondering whether perfetto UI support customzied plugin, what we want is showing query result in diagram by our customized plugin, e.g. drawing lines to show trend of numbers, even we can save results into csv and work on excel later, but it's not that convience. Will perfetto support such feature (show trend of numbers) or support customized plugins?

**Comment by LalitMaganti** [comment]
A plugin-based architecture is what we are striving towards but the UI needs some refactoring (currently under progress) to get there.

**Comment by LalitMaganti** [comment]
Plugin support has landed and is documented at https://perfetto.dev/docs/contributing/ui-plugins
