### ISSUE TITLE
Can not capture logcat logs on android p 

### ISSUE THREAD

**Issue by ricaisme** [google/perfetto#172]
Dear perfetto team

I'm using the code base  https://android.googlesource.com/platform/external/perfetto/ to build the perfetto standalone android builds to test my android p device.  it works fine on lightweight command mode but when I tried to trace logcat logs it dumps an  empty log file and I saw nothing. 
Could you please check is this a bug or I missed some configurations? 
my build conf:
target_os = "android"
target_cpu = "arm"
is_debug = true
monolithic_binaries = true
perfetto_build_standalone = true

my conf file: 
[conf.txt](https://github.com/google/perfetto/files/7142772/conf.txt)

perfetto output:
09-10 11:27:41.335 23809 23809 D perfetto: perfetto_cmd.cc:525     Parsing TraceConfig, 372 bytes
09-10 11:27:41.356 23809 23809 I perfetto: perfetto_cmd.cc:825     Connected to the Perfetto traced service, TTL: 5s
09-10 11:27:41.357   266   266 D perfetto: ing_service_impl.cc:455 Consumer 0xf6a4b280 connected from UID 0
09-10 11:27:41.357   266   266 D perfetto: ing_service_impl.cc:547 Enabling tracing for consumer 0xf6a33180
09-10 11:27:41.357   266   266 D perfetto: ng_service_impl.cc:2533 Setting up data source android.log with target buffer 3
09-10 11:27:41.358   266   266 I perfetto: ing_service_impl.cc:928 Configured tracing session 3, #sources:1, duration:5000 ms, #buffers:1, total buffer size:32768 KB, total sessions:1, uid:0 session name: ""
09-10 11:27:41.363   267   267 D perfetto: probes_producer.cc:158  SetupDataSource(id=3, name=android.log)
09-10 11:27:41.364   267   267 D perfetto: probes_producer.cc:198  StartDataSource(id=3, name=android.log)
09-10 11:27:41.373   267   267 D perfetto: _log_data_source.cc:172 Starting Android log data source: stream tail=1 lids=0,3,1,2,4,7
09-10 11:27:41.375   266   266 D perfetto: ng_service_impl.cc:1345 All data sources started
09-10 11:27:46.362   266   266 D perfetto: ng_service_impl.cc:1832 Triggering final flush for 3
09-10 11:27:46.364   267   267 D perfetto: probes_producer.cc:417  Flush 3 acked by data source 3
09-10 11:27:46.364   267   267 D perfetto: probes_producer.cc:429  All data sources acked to flush 3
09-10 11:27:46.365   266   266 I perfetto: ng_service_impl.cc:1837 FlushAndDisableTracing(3) done, success=1
09-10 11:27:46.365   267   267 I perfetto: probes_producer.cc:340  Producer stop (id=3)
09-10 11:27:46.371 23809 23809 I perfetto: perfetto_cmd.cc:949     Wrote 874 bytes into /data/misc/perfetto-traces/trace_file.perfetto-trace
09-10 11:27:46.372   266   266 D perfetto: ing_service_impl.cc:472 Consumer 0xf6a33180 disconnected
09-10 11:27:46.372   266   266 D perfetto: ng_service_impl.cc:2278 Freeing buffers for session 3
09-10 11:27:46.373   266   266 I perfetto: ng_service_impl.cc:2309 Tracing session 3 ended, total sessions:0
 
thank you

**Comment by primiano** [comment]
Are you running this as "shell" or "root"?
If you sideload perfetto, accessing logcat might require root.
Any selinux denials on /dev/logr?

**Comment by ricaisme** [comment]
> Are you running this as "shell" or "root"?
> If you sideload perfetto, accessing logcat might require root.
> Any selinux denials on /dev/logr?

hi Primiano, thanks for your reply. I was running this on root and SElinux was set on permissive via setenforce 0. so I do not think there was any permission denied.

**Comment by ricaisme** [comment]
indeed, with your hint, I found some traces through dmesg


[Fri Sep 10 14:02:23 2021] type=1400 audit(1631275344.174:213): avc: denied { write } for pid=267 comm="traced_probes" name="logdr" dev="tmpfs" ino=243 scontext=u:r:traced_probes:s0 tcontext=u:object_r:logdr_socket:s0 tclass=sock_file permissive=1
[Fri Sep 10 14:02:23 2021] type=1400 audit(1631275344.174:213): avc: denied { write } for pid=267 comm="traced_probes" name="logdr" dev="tmpfs" ino=243 scontext=u:r:traced_probes:s0 tcontext=u:object_r:logdr_socket:s0 tclass=sock_file permissive=1
[Fri Sep 10 14:02:23 2021] type=1400 audit(1631275344.174:214): avc: denied { connectto } for pid=267 comm="traced_probes" path="/dev/socket/logdr" scontext=u:r:traced_probes:s0 tcontext=u:r:logd:s0 tclass=unix_stream_socket permissive=1

it seems traced_probes still got permission denials on mode permissive.

**Comment by primiano** [comment]
permissive=1 shouldn't cause blockages though (did you restart traced_probes after setenforce 0 though?).

I can't explain why this shouldn't work with root with selinux disabled.
What's the size of the resulting trace?

**Comment by ricaisme** [comment]
after restart the traced suites via adb shell setprop persist.traced.enable 0 then 1.  perfetto dumped a slight different result. 

[177.668] perfetto_cmd.cc:825     Connected to the Perfetto traced service, TTL: 5s
[182.679] perfetto_cmd.cc:949     Wrote 1001 bytes into /data/misc/perfetto-traces/trace.test

I've a trace file with one line logcat 
0.000 000 100Dperfettong_service_impl.cc:1345 All data sources started  
[trace.test.zip](https://github.com/google/perfetto/files/7143865/trace.test.zip)

**Comment by primiano** [comment]
Hmmw which user is traced_probes running as?
Android's logd has a futher security check that works as follows, IIRC:
- If the connecting user id is shell or root (or some system service) allows to read all logs
- Otherwise it allows to read only logs emitted by the connecting UID.

Feels like this is what's happening here?

**Comment by ricaisme** [comment]
> Hmmw which user is traced_probes running as?
> Android's logd has a futher security check that works as follows, IIRC:
> 
> * If the connecting user id is shell or root (or some system service) allows to read all logs
> * Otherwise it allows to read only logs emitted by the connecting UID.
> 
> Feels like this is what's happening here?

nice catch, just checked, originally,  traced_probes is ran by nobody. 
I had a quick test with root, now it works like a charm

appreciate for your quick reply and help, sir.

**Comment by ricaisme** [comment]
just for curiosity, how to auto create the root or system running traced traced_probe via setprop ?

**Comment by primiano** [comment]
traced_probes doesn't run as root ever, always runs as nobody.
But there is a secret for accessing logcat, which works only on userdebug.

The secret is the union of:

1. perfetto.rc adding traced_probes to the "log" group:
   ```
   service traced_probes /system/bin/traced_probes
   ...
    # Despite the "log" group below, traced_probes is allowed to read log
    # only on userdebug/eng via selinux (see traced_probes.te).
    group nobody readproc log
    ```
   When I said "shell or root" above it was incomplete. It's really: shell, root or anything in the log group.

2. On top of that, it requires selinux rules. From traced_probes.te:
```
# On debug builds allow to ingest system logs into the trace.
userdebug_or_eng(`read_logd(traced_probes)')
```
