### ISSUE TITLE
Nested_value, array_value in SQL

### ISSUE THREAD

**Issue by KyleStorck** [google/perfetto#173]
Hello,

We have some debug annotations that are logged using nested_values. We are currently using SQL queries through trace_processor_shell to get the data out of traces, but I haven't seen a way to query the nested_values or array_values from debug annotations through SQL. Is there a way to do that?

**Comment by LalitMaganti** [comment]
Nested values and array values are available in the args table. You can join the `slice` table with the `args` table using the arg_set_id column and retrieve the debug annotations data there.

**Comment by KyleStorck** [comment]
Thanks for the response. I was able to take time and look at this issue again. I attached a sample trace where I have logged nested_value debug annotations, and they do not show up in the `args` table. I can see them in text output of the trace however. Is there something wrong with how we're logging these debug annotations?

[SampleTrace.zip](https://github.com/google/perfetto/files/7237534/SampleTrace.zip)

```
packet {
  trusted_uid: 2000
  timestamp: 98113518125229
  trusted_packet_sequence_id: 2

  track_event {
    category_iids: 1
    debug_annotations {
      nested_value {
        array_values {
          int_value: 1311807503828193853
        }
        array_values {
          int_value: -3459511085376249940
        }
      }
      name: "ProviderGUID"
    }
    debug_annotations {
      int_value: 2
      name: "OPCODE"
    }
    type: TYPE_INSTANT
    name_iid: 1
  }
  interned_data {
    event_categories {
      iid: 1
      name: "Info"
    }
    event_names {
      iid: 1
      name: "SleepOneSecond"
    }
  }
  sequence_flags: 2
}
```

**Comment by LalitMaganti** [comment]
The OPCODE you specify is actually showing up correctly in the args table under the `debug.OPCODE` key

As for your arrays, as stated on the [proto description](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/track_event/debug_annotation.proto;l=91?q=%22Deprecated%20legacy%20way%20to%20use%20nested%20values.%20Only%20kept%20for%22), nested_values is the deprecated way to use DebugAnnotations. Please use array_values instead which trace processor should parse correctly.

**Comment by KyleStorck** [comment]
Thanks, I'll give that a try.
