### ISSUE TITLE
Whitespace breaks RUN_METRIC

### ISSUE THREAD

**Issue by jstaahl** [google/perfetto#178]
The RUN_METRIC sql function implementation is brittle to whitespace. Supplying a sql file to RUN_METRIC() that contains certain whitespace can cause the following cryptic error:
```
RUN_METRIC: Error when running file xxx.sql: not an error
```

**Steps to reproduce:**
1) Create a SQL file (ex: `test_file.sql`) that contains valid SQL such as:
```sql
-- test_file.sql
SELECT 1;
 
```
2) Terminate the file in a newline followed by a space (as is shown above).
3) Invoke RUN_METRIC somewhere during trace processing over that file:
```
SELECT RUN_METRIC("test_file.sql");
```
4) Build and run the ui dev server
5) Import a trace and observe the error

**More info:**
The parsing logic [here](https://github.com/google/perfetto/blob/1ca3e3aad7533285a091fdb3ece47548d5666edb/src/trace_processor/metrics/metrics.cc#L687) assumes all statements end in a semicolon followed immediately by a newline character and that no additional whitespace follows the last statement (other than perhaps a single newline character).

**Comment by primiano** [comment]
Moving to @LalitMaganti who did some changes recently on this IIRC

**Comment by LalitMaganti** [comment]
https://android-review.googlesource.com/c/platform/external/perfetto/+/1840173 should fix.
