### ISSUE TITLE
rm /data/misc/perfetto-traces/xxx Permission Denied

### ISSUE THREAD

**Issue by xiaweizi** [google/perfetto#182]
![image](https://user-images.githubusercontent.com/18526994/136761308-3630a3e5-aa1b-4365-9cbb-d6d3dbab18b6.png)

https://github.com/google/perfetto/issues/22
I am executed in this way or fail.

Please help me~ thank you very much!

**Comment by Gohan** [comment]
I have similar issues below:
```
begonia:/data/misc/perfetto-traces $ ls
trace
begonia:/data/misc/perfetto-traces $ ls -l
total 7616
-rw------- 1 shell shell 7793068 2022-07-28 11:11 trace
begonia:/data/misc/perfetto-traces $ whoami
shell
begonia:/data/misc/perfetto-traces $ rm trace
rm ro trace (y/N):y
rm: trace: Permission denied
1|begonia:/data/misc/perfetto-traces $
```

don't know why the "trace" mentions for "ro"

My android version: 10 (ro.build.version.release)
SDK version: 29 (ro.build.version.sdk)

I runs:
```
```
adb shell perfetto \
  -c - --txt \
  -o /data/misc/perfetto-traces \
<<EOF

buffers: {
    size_kb: 63488
    fill_policy: RING_BUFFER
}
buffers: {
    size_kb: 2048
    fill_policy: RING_BUFFER
}
data_sources: {
    config {
        name: "android.gpu.memory"
    }
}
data_sources: {
    config {
        name: "linux.process_stats"
        target_buffer: 1
        process_stats_config {
            scan_all_processes_on_start: true
        }
    }
}
data_sources: {
    config {
        name: "android.log"
        android_log_config {
            log_ids: LID_CRASH
            log_ids: LID_DEFAULT
            log_ids: LID_SYSTEM
        }
    }
}
data_sources: {
    config {
        name: "linux.sys_stats"
        sys_stats_config {
            stat_period_ms: 1000
            stat_counters: STAT_CPU_TIMES
            stat_counters: STAT_FORK_COUNT
        }
    }
}
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            ftrace_events: "sched/sched_switch"
            ftrace_events: "power/suspend_resume"
            ftrace_events: "sched/sched_wakeup"
            ftrace_events: "sched/sched_wakeup_new"
            ftrace_events: "sched/sched_waking"
            ftrace_events: "power/cpu_frequency"
            ftrace_events: "power/cpu_idle"
            ftrace_events: "power/gpu_frequency"
            ftrace_events: "gpu_mem/gpu_mem_total"
            ftrace_events: "sched/sched_process_exit"
            ftrace_events: "sched/sched_process_free"
            ftrace_events: "task/task_newtask"
            ftrace_events: "task/task_rename"
            ftrace_events: "ftrace/print"
            atrace_categories: "am"
            atrace_categories: "dalvik"
            atrace_categories: "binder_driver"
            atrace_categories: "database"
            atrace_categories: "gfx"
            atrace_categories: "hal"
            atrace_categories: "input"
            atrace_categories: "res"
            atrace_categories: "rro"
            atrace_categories: "ss"
            atrace_categories: "view"
            atrace_categories: "wm"
            atrace_apps: "xxx.xxx.xxx"
            buffer_size_kb: 2048
            drain_period_ms: 250
        }
    }
}
duration_ms: 60000
write_into_file: true
file_write_period_ms: 2500
max_file_size_bytes: 100000000
flush_period_ms: 30000
incremental_state_config {
    clear_period_ms: 5000
}

EOF
```

**Comment by LalitMaganti** [comment]
Did you create the directory `/data/misc/perfetto-traces` manually as root?

If so, please run the following steps:
```
adb root
adb shell rm -rf /data/misc/perfetto-traces/
adb shell setprop persist.traced.enable 0
<wait a few seconds>
adb shell setprop persist.traced.enable 1
adb unroot
```

**Comment by LalitMaganti** [comment]
Can you run "ls -l /data/misc"?

**Comment by Gohan** [comment]
```
➜ adb shell ls -l /data/misc
ls: /data/misc: Permission denied
```

**Comment by LalitMaganti** [comment]
Can you change the -o option to instead -o
/data/misc/perfetto-traces/trace-other?

I have to wonder if your device OEM somehow broke something with that
directory - on Pixels this works as intended.

**Comment by Gohan** [comment]
> 

It works too, but the file won't be rm either. I already did it hours ago, before reset the factory setting this time. 

```
![CleanShot 2022-07-28 at 16 21 01](https://user-images.githubusercontent.com/212567/181457634-dfb6d041-451e-4415-8741-7da7b713c4c2.png)
(I change the size limit to avoid it take extra space)
```

**Comment by LalitMaganti** [comment]
Yeah I'm not sure what's going on your specific device but in general on
Pixels this is not a problem - we rely on this every day.

Maybe chromy@ might have more thoughts.
