### ISSUE TITLE
capture android device cpu_freq empty

### ISSUE THREAD

**Issue by wjj1928** [google/perfetto#184]
Hi,

I try to capture perfetto trace with below config:

duration_ms: 20000                                                                                                      
flush_period_ms: 1000
write_into_file: true

buffers: {
    size_kb: 1634880
    fill_policy: DISCARD
}
buffers: {
    size_kb: 120480
    fill_policy: DISCARD
}

data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            ftrace_events: "power/cpu_frequency"
            ftrace_events: "power/cpu_idle"
            ftrace_events: "power/suspend_resume"
        }
    }
}

But when open the trace in UI, nothing displayed. I only want to capture cpu_freq info not sure if the config is correct or not!

Hardware: motorola edge plus
software: android 10
[trace_file.zip](https://github.com/google/perfetto/files/7349072/trace_file.zip)

**Comment by wjj1928** [comment]
Thanks, update the information and output trace above!

**Comment by primiano** [comment]
anything interesting in `logcat -s perfetto -d` ?

Everything seems alright. Maybe something else is driving ftrace? What's the output of

`cat /d/tracing/tracing_on`

If it's 1 can you try resetting it to 0 (`echo 0 >  /d/tracing/tracing_on`) and trying again?

Logcat would really help though.
