### ISSUE TITLE
Add navigation history to browser

### ISSUE THREAD

**Issue by kcoop** [google/perfetto#19]
Proposal: to enable browsing back and forth through flow events, etc., update the browser navigation stack when view state changes significantly. This would include changing the query filter (omnibox text, time/selected tracks/view, selected categories), and selected slice. Maybe include view presentation state as well, like zoom/scroll, or track expand/collapse.

To deal with rapid movement through selections, should debounce to prevent clutter in the history.

**Comment by gramound** [comment]
I don't know if this is the same, but I often wish I could go peek at something else in the trace then come back to exactly what I was looking at before (same zoom level, same position, etc.)
