### ISSUE TITLE
Scaling thread duration part of a slice

### ISSUE THREAD

**Issue by SalvatoreDiGirolamo** [google/perfetto#191]
Hi, thanks for the amazing tool! When visualizing our traces with Perfetto UI, it seems that the thread duration (```tdur```) portion of a slice is not always scaled when zooming in and it remains fixed. Not sure whether this was intended and I'm misinterpreting it or it's a bug. I noticed that this happens in the canary version but not in the legacy one.

I attach a minimal example where the issue is visible. When I zoom in, I would expect the darker part of the first slice to expand but this does not happen (the time bar expands instead, so it is actually zooming in). 

Sample trace: [test4.json.gz](https://github.com/google/perfetto/files/7417043/test4.json.gz)

**Comment by LalitMaganti** [comment]
I don't think this happens anymore with the latest UI so closing.
