### ISSUE TITLE
new GpuCounterConfig counter_group field

### ISSUE THREAD

**Issue by djdeath** [google/perfetto#193]
I'm working with the perfetto integration added to the Mesa3D project for the Intel GPUs.

Our HW does not allow to report all the available counters at the same time.
We instead have to enable them by groups.

Would it be possible to add a string `counter_group` name in the `GpuCounterConfig` definition so that we can enable a given group rather than let the user specify all the counters of a given group.

We also tend to have fixed group names across generations but there can be a bit  of variability in the counters that are available within a group.

**Comment by pmuetschard** [comment]
> But we cannot enable counters from 2 different banks at the same time.

That's what I was worried about and the current design does not describe that. It is currently describing a system where blocks have `N` counters, but can only enable `M` at a time, where `M < N`, but any block can be used. We could extend the `GpuCounterBlock` structure to reference other blocks that it's exclusive with.

> way to specify the `GpuCounterBlock` name in the cfg file. 

I'm not sure what config file you are referring. From what you wrote, I'm deducing that you have a counter, say "counter 5", that can be enabled on one of two or more banks and you want the Perfetto trace config to be extended from just "enable counter 5" to "enable counter 5 on bank 1", is that correct? If so, that doesn't currently exist. I think a way to handle such a counter would be to have multiple versions of it with different IDs for each bank.

Note, nothing currently honors the `GpuCounterBlock` message, so we can re-design it to suit your needs, but then we will need to make AGI respect it and change the UI to make it clear to the user what counter combinations are possible.

I'm about to go on vacation and will be absent until Dec 1st. If you'd like we can take this conversation to email (my email is my GH username `@google.com`).

**Comment by djdeath** [comment]
> > But we cannot enable counters from 2 different banks at the same time.
> 
> That's what I was worried about and the current design does not describe that. It is currently describing a system where blocks have `N` counters, but can only enable `M` at a time, where `M < N`, but any block can be used. We could extend the `GpuCounterBlock` structure to reference other blocks that it's exclusive with.
> 
> > way to specify the `GpuCounterBlock` name in the cfg file.
> 
> I'm not sure what config file you are referring.

I was referring to files like `test/configs/scheduling.cfg`

> From what you wrote, I'm deducing that you have a counter, say "counter 5", that can be enabled on one of two or more banks and you want the Perfetto trace config to be extended from just "enable counter 5" to "enable counter 5 on bank 1", is that correct? If so, that doesn't currently exist. I think a way to handle such a counter would be to have multiple versions of it with different IDs for each bank.
> 
> Note, nothing currently honors the `GpuCounterBlock` message, so we can re-design it to suit your needs, but then we will need to make AGI respect it and change the UI to make it clear to the user what counter combinations are possible.
> 
> I'm about to go on vacation and will be absent until Dec 1st. If you'd like we can take this conversation to email (my email is my GH username `@google.com`).

It's not really urgent so we can deal with that when you come back.
I think a stop gap solution for us will be to load the provider with an option or env variable.

Have a good one!
