### ISSUE TITLE
perfetto tool trace_to_text eat too much memory

### ISSUE THREAD

**Issue by Ryan-Deng** [google/perfetto#195]
perfetto tool trace_to_text eat too much memory when processing large binary log to systrace text log.
when I record 1 hour long trace log (6.8G) and want to transform it to a systrace text log, my PC was crashed because the trace_to_text.exe occupied all memories. You know, my PC has 16G memory, even through it also not enough for processing the logs. 
Can we optimize it?

**Comment by primiano** [comment]
Add more swap, it's as easy as a dd + swapon (https://linuxize.com/post/create-a-linux-swap-file/)

It's a hard problem and no, you cannot expect that processing a trace takes just as much as the trace size itself. Unfortunately it's not a 1:1 transformation. Many things (even just emitting the right process names) requires first seeing all the set of ftrace events (To track thread start/end) and /proc pollers.

`trace_to_text systrace` is not as easy as a stream-transformation, it involves queries on the processed data.

If you want to operate with large traces, get more memory or just more swap. your OS can deal with a large swapfile, there is no reason why we should re-implement file-based paging within trace_to_text.
