### ISSUE TITLE
gpu_counters_missing_spec error in generated traces

### ISSUE THREAD

**Issue by djdeath** [google/perfetto#196]
I'm trying to find why most of our generated trace don't include the GPU counter names.
Or at least they don't show up in the UI and it does report the `gpu_counters_missing_spec` error.

The code we use to send counter names is pretty straightforward and I can't really see what could be going wrong :
https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/tool/pps/pps_datasource.cc#L172

Any tip?

**Comment by djdeath** [comment]
Sure : [trace.zip](https://github.com/google/perfetto/files/7496514/trace.zip)

**Comment by LalitMaganti** [comment]
This is extremely mysterious: your trace is totally missing the descriptors for all the counters but both the packets before (i.e. setting the SEQ_INCREMENTAL_STATE_CLEARED) and the packets after (i.e. the counter events themselves) are present.

To confirm, if you enable logging and take a trace do you see the "`Sending counter descriptors" message from https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/tool/pps/pps_datasource.cc#L256?

**Comment by djdeath** [comment]
> This is extremely mysterious: your trace is totally missing the descriptors for all the counters but both the packets before (i.e. setting the SEQ_INCREMENTAL_STATE_CLEARED) and the packets after (i.e. the counter events themselves) are present.
> 
> To confirm, if you enable logging and take a trace do you see the "`Sending counter descriptors" message from https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/tool/pps/pps_datasource.cc#L256?

Yep the message always appears, which is why I don't understand either :)

**Comment by djdeath** [comment]
Not sure if this is what you meant by trace :

```
$ ./build/src/tool/pps/pps-producer
[133.845] perfetto.cc:38744       Producer connected
[133.845] pps_driver.cc:88        Driver selected: i915
[133.845] pps_datasource.cc:137   Waiting for start
[133.846] perfetto.cc:38744       Producer connected
[136.083] perfetto.cc:39414       Setting up data source 3 gpu.counters.i915
[136.088] pps_datasource.cc:95    Sampling period set to 100000 ns
[136.088] perfetto.cc:39512       Starting data source 3
[136.093] pps_datasource.cc:285   Sending counter descriptors
[136.098] intel_pps_driver.cc:290 Records parsed bytes: 24552
[136.098] pps_datasource.cc:315   Skipping counter values coming before descriptors
[136.098] pps_datasource.cc:315   Skipping counter values coming before descriptors
[136.098] pps_datasource.cc:315   Skipping counter values coming before descriptors
[136.098] pps_datasource.cc:315   Skipping counter values coming before descriptors
[136.098] pps_datasource.cc:315   Skipping counter values coming before descriptors
[136.098] pps_datasource.cc:315   Skipping counter values coming before descriptors
[136.098] pps_datasource.cc:315   Skipping counter values coming before descriptors
[136.098] pps_datasource.cc:315   Skipping counter values coming before descriptors
[136.098] pps_datasource.cc:315   Skipping counter values coming before descriptors
[141.082] perfetto.cc:39535       Stopping data source 3
[141.082] pps_datasource.cc:116   Context flushed
[141.082] pps_datasource.cc:137   Waiting for start
[141.083] perfetto.cc:39575       Ending async stop of data source 3
```

**Comment by LalitMaganti** [comment]
Reflecting a bit more I have a couple of observations:
1. So your code doesn't set the field `timestamp_clock_id` but it's appearing in the trace which is a bit weird
2. It seems like you are not using the boot clock for your counter events so https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/tool/pps/pps_datasource.cc#L276 doesn't seem like a sensible check.

I'm pretty stumped to the exact cause here but a suggestion I have is to remove the braces in line 241/243 of https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/tool/pps/pps_datasource.cc#L241 And then also remove line 247 https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/tool/pps/pps_datasource.cc#L247

This should merge the incremental state cleared packet with the GPU descriptors making it a bit clearer as to what the problem might be. Can you attach a trace taken with this change made?

**Comment by djdeath** [comment]
> Reflecting a bit more I have a couple of observations:
> 
> 1. So your code doesn't set the field `timestamp_clock_id` but it's appearing in the trace which is a bit weird

Apologies, the trace was captured with a local branch that does add the timestamp_clock_id for gpu counters (now using a different clock for the GPU stuff and letting perfetto map CPU/GPU clock on its own).

> 2. It seems like you are not using the boot clock for your counter events so https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/tool/pps/pps_datasource.cc#L276 doesn't seem like a sensible check.

Yeah, I just defined a new one locally.

> 
> I'm pretty stumped to the exact cause here but a suggestion I have is to remove the braces in line 241/243 of https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/tool/pps/pps_datasource.cc#L241 And then also remove line 247 https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/tool/pps/pps_datasource.cc#L247
> 
> This should merge the incremental state cleared packet with the GPU descriptors making it a bit clearer as to what the problem might be. Can you attach a trace taken with this change made?

Sorry, I'll have to pick that up later (on a different machine) because while running this test I just run into a nasty kernel bug : https://gitlab.freedesktop.org/drm/intel/-/issues/4454

**Comment by djdeath** [comment]
The branch for reference : https://gitlab.freedesktop.org/llandwerlin/mesa/-/blob/20ef16fde76c368403404d4adc46e0c876364646/src/tool/pps/pps_datasource.cc#L280

**Comment by LalitMaganti** [comment]
> The branch for reference : https://gitlab.freedesktop.org/llandwerlin/mesa/-/blob/20ef16fde76c368403404d4adc46e0c876364646/src/tool/pps/pps_datasource.cc#L280

Aha but this makes it a lot more obvious what's going on! 

As you can see from the TracePacket proto (https://source.corp.google.com/android/external/perfetto/protos/perfetto/trace/perfetto_trace.proto;l=9072?q=f:perfetto%20clock_snapshot), the `clock_snapshot` and `gpu_counter_event` events are inside a `oneof` which means only one of these fields can be set in each TracePacket.

All you need to do to fix the issue is to have two different `auto packet = ctx.NewTracePacket()` lines one for each packet and that should fix the issue :)

**Comment by djdeath** [comment]
Ah thanks, makes sense now.

I'll try that later and report back :)

**Comment by djdeath** [comment]
Yep seems to work.

I have to be careful not to forget the timestamps and use the right packets not to mix the data.
