### ISSUE TITLE
No longer able to see Alloc Space & Alloc Objects in Perfetto UI when native heap profiling

### ISSUE THREAD

**Issue by HippyGumbo** [google/perfetto#197]
Hello,

Recently I have been doing some heap profiling using heapprofd & visualizing native allocations using the Perfetto's web UI. I followed the documentation here https://perfetto.dev/docs/data-sources/native-heap-profiler to do this and it was working well up until last week. I suddenly was on longer able to see  the `alloc space` and `alloc object` tabs in Perfetto for new or old symbolized heap traces.

**Previous UI**
![perfetto_ui_prev](https://user-images.githubusercontent.com/21062157/141826388-4973b2e4-0882-48a5-9a74-860df736040b.png)

**Current UI**
![perfetto_ui_issue](https://user-images.githubusercontent.com/21062157/141825427-932a6754-8a79-4480-8934-e0372db26d24.png)

I am wondering if anyone else has run into this issue?

**Comment by ddiproietto** [comment]
Hi,

thanks for the reporting this!

I believe you're correct, it looks like it's a simple problem with the UI. I've sent a fix in http://r.android.com/1893649

Can you confirm that [this version](https://storage.googleapis.com/perfetto-ci-artifacts/20211116152522--cls-1893649-1--ui-clang-x86_64-release/ui/index.html) of the perfetto UI fixes the problem for you?

**Comment by HippyGumbo** [comment]
No problem! Verified the version you linked me works as expected. I can see all 4 tabs again when loading my heap data
