### ISSUE TITLE
cpu_utilization enhancement

### ISSUE THREAD

**Issue by kimjihoon0301** [google/perfetto#198]
Hello.

When I use cpu_utilization tool, I want to make one more feature for profiling.
It's cpu core status check.

If user didn't input process id, cpu_utilization tool will check each core usage.
Is this fix worth applying?

If yes, I will send the full patch.

key contents is as below :

  base::ScopedFile fd = base::OpenFile(std::string("/proc/stat"), O_RDONLY);**
  PERFETTO_CHECK(fd);
 ...
    fd = base::OpenFile(std::string("/proc/stat"), O_RDONLY);
    lseek(fd.get(), 0, SEEK_SET);
    PERFETTO_CHECK(read(fd.get(), buf, sizeof(buf)) > 0);
    buf[sizeof(buf) - 1] = '\0';
    PERFETTO_LOG("----- interval begin. (%d / %d)) ----- ", i+1, sleep_interval);

    for(int j = 0; j < core_num; j++) {
      sscanf(buf + buf_cnt, "%*s %u %u %u %u%*[^\n]\n", &cores[j].user, &cores[j].nice, &cores[j].system, &cores[j].idle);
      buf_cnt++;
      while(buf[buf_cnt] != '\n')
        buf_cnt++;
      if (j == 0)
        PERFETTO_LOG("[total cpu\t] user : %u, nice : %u, system : %u, idle : %u", cores[j].user, cores[j].nice, cores[j].system, cores[j].idle);
      else
        PERFETTO_LOG("[core %d\t] user : %u, nice : %u, system : %u, idle : %u", j-1, cores[j].user, cores[j].nice, cores[j].system, cores[j].idle);

      sum =  cores[j].user + cores[j].nice + cores[j].system + cores[j].idle;
      cpu_delta = sum - cores[j].sum_last;
      cpu_idle = cores[j].idle - cores[j].idle_last;
      cpu_used = cpu_delta - cpu_idle;
      utilization = (100 * cpu_used) / cpu_delta;

      if (j == 0)
        PERFETTO_LOG("[total cpu\t] utilization : %u%%", utilization);
      else
        PERFETTO_LOG("[core %d\t] utilization : %u%%", j-1, utilization);
      cores[j].sum_last = sum;
      cores[j].idle_last = cores[j].idle;
    }
    PERFETTO_LOG(" -----  interval (%d / %d) end. -----", i+1, sleep_interval);
    buf_cnt = 0;
  }
  ...

**Comment by LalitMaganti** [comment]
If you mean the cpu_utilization tool under the tools/ folder, I doubt there would be any objects.

@primiano @rsavitski FYI
