### ISSUE TITLE
How to represent 3d pipeline draws?

### ISSUE THREAD

**Issue by djdeath** [google/perfetto#199]
Hi,

I'm trying to represent draws from our GPU HW and I'm running into an issue with the UI.
Here is how it looks : 
![Screenshot from 2021-11-22 11-05-06](https://user-images.githubusercontent.com/434333/142833294-94a5478c-1010-47f8-a774-bd1ccab4adcd.png)

As you can see there are multiple overlapping draw events. This is because our HW will receive multiple draw request and process them in parallel.
As a result draw started later might also complete before previous ones.

I'm looking for a way to make this visible in the UI (right now different draws are overlapping on the same row).
I'm not quite sure how to make this not overlap (different event_id? use a different stage_id?)

It might be possible to use a different stage id, but I would have to create as many as our HW can support (right now 32 parallel draws).
Maybe people know of an easier way?

Thanks!

**Comment by djdeath** [comment]
Another example with way more draws, stacking is really odd : 
![Screenshot from 2021-11-24 11-28-27](https://user-images.githubusercontent.com/434333/143211622-a25d4e5d-264c-401c-9e4d-7cffde53f39a.png)

**Comment by chromy** [comment]
Hey @djdeath! Sorry you are having issues. It sounds like you are using the [gpu_render_stage_event proto](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/gpu/gpu_render_stage_event.proto;l=22?q=external%2Fperfetto%2Fprotos%2Fperfetto%2Ftrace%2Fgpu%2Fgpu_render_stage_event.proto). If so I'm afraid we have limited insight. Your best bet is probably somebody on the https://github.com/google/agi team. @pmuetschard would you be able to help point them to someone?

Thanks!

**Comment by pmuetschard** [comment]
The gpu_render_stage_event proto is designed with the assumption that each HW queue can only work on a single thing at a time - like a single core in the CPU view. If the hardware can process multiple draws in parallel, you need to emit them each on its own queue. Otherwise, flatten out the draws into a single "drawing" event that starts when the earliest one starts, and ends when the latest one finishes.

**Comment by djdeath** [comment]
> The gpu_render_stage_event proto is designed with the assumption that each HW queue can only work on a single thing at a time - like a single core in the CPU view. If the hardware can process multiple draws in parallel, you need to emit them each on its own queue. Otherwise, flatten out the draws into a single "drawing" event that starts when the earliest one starts, and ends when the latest one finishes.

Thanks, I'm not quite clear on what you just wrote here.

Are you saying that each gpu_render_stage_event element of the timeline must not overlap with any other within a single queue?

**Comment by pmuetschard** [comment]
Essentially, yes. You can have a hierarchy (e.g. your cmd buffer -> rp -> dc tree), but it has to be a parent-child / stack relationship, not a "run in parallel" relationship. If you want to indicate that two "things" are running in parallel on the GPU, you need to emit two events with different hw queue ids (the `optional uint64 hw_queue_iid = 13` field in the proto). The UI will then create separate tracks, one for each queue.

**Comment by djdeath** [comment]
Thanks, I did not know that.

I have a followup question on `hw_queue_iid`. I'm still using the deprecated protos for all this. I gave a shot at the new `_iid` fields but that did not render anything on the web UI. And no errors were showing up for the trace.

Are the new `_iid` fields supports on the deployed UI?

**Comment by pmuetschard** [comment]
Yes trace processor should handle those correctly. Are you emitting [`InternedGpuRenderStageSpecification`](https://github.com/google/perfetto/blob/781bc4dd9be3e8a759eab920586fcab6ef8819d3/protos/perfetto/trace/interned_data/interned_data.proto) packets?

**Comment by djdeath** [comment]
Yep I was, I'll try again and open another bug if needed.

Closing this, thanks for the details.
