### ISSUE TITLE
Implement trace viewer flow events

### ISSUE THREAD

**Issue by kcoop** [google/perfetto#20]
Ingest trace events into the trace processor.

Proposal: provide indicators on slices in both the flame graph and details list for incoming and outgoing flow events. Clicking on either the incoming or outgoing indicators (at least from within the details list) would directly navigate to the incoming or outgoing slice. If there are more than one, it would present an intermediate list of links to slices to navigate to.

Rough straw man example:
![image](https://user-images.githubusercontent.com/761190/77937807-b5799c80-7269-11ea-8680-b03def63ea07.png)

**Comment by F3n67u** [comment]
see this doc: https://docs.google.com/document/d/1xJt059giD6ZwM0HdJ_xiVhD0pfwAXe_zPP1atnkEaRk/edit

**Comment by LalitMaganti** [comment]
We have reasonable support for flow events at this point so closing this bug.
