### ISSUE TITLE
Extract trace.dat from perfetto-trace

### ISSUE THREAD

**Issue by qais-yousef** [google/perfetto#201]
Hi

Is it possible to extract the original trace.dat from a perfetto-trace? I tried to search for this info but failed to find a clue if it is even possible or not.

Thanks!

**Comment by chromy** [comment]
Hi! 😃 

A `.perfetto-trace` doesn't directly contain the `trace.dat` data (we parse the kernel binary format into [our own protobuf](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/ftrace/ftrace_event.proto;l=67) at trace time) so it's not possible to extract it. We do support converting to/from `.perfetto-trace` and various formats including `systrace` which is what we call the textual format you get if you cat `/sys/kernel/debug/tracing/trace` so that might help depending on what you are trying to do. See [the traceconv docs](https://perfetto.dev/docs/quickstart/traceconv).

I'm not against adding the ability to convert to (or from) `trace.dat` to `traceconv` so if somebody wants to contribute that I'll be happy to review but it's not in our plans to work on at present.

Out of interest what do you want to use the trace.dat file for? There might be an alternative way to achieve what you want that we can help you with.

**Comment by qais-yousef** [comment]
Hey! :)

Thanks for the quick response.

Yeah I've seen the traceconv. I could try work on that if I get a helping hand and pointers where to start. I never looked at this codebase before. Is the conversion lossless?

The conversion is useful mostly to help working with others who have their own workflow based on `trace.dat`. When sharing data with the community basically being able to generate a trace.dat will be helpful when they ask for it. I work on Linux Kernel development.

I would have thought allowing `perfetto` (or `tracebox`) to dump `trace.dat` beside `.perfetto-trace` could work too. using `traceconv` would be more portable though. If it's not 'too' much work I could try to look at this.

**Comment by primiano** [comment]
What's trace.dat ? What is the format you'd expect to see there?

**Comment by qais-yousef** [comment]
It is the original binary format generated by kernel ftrace subsystem. It should be what perfetto parses to create its own .perfeto-trace. Or at least one of the things it parses.

**Comment by primiano** [comment]
Oh we don't retain it. We consume the binary trace data on the flight and decompose it into protos.
There is really no easy way to go back to the orginal ftrace data.
And even if we did, we don't keep around the events/**/format files either so you would have no way to make any use of that trace.

**Comment by primiano** [comment]
Closing this as this is unfeasible.

**Comment by qais-yousef** [comment]
kernelshark, trace-cmd and tools like https://github.com/ARM-software/lisa/ can parse trace.dat as it is.
Is it hard to make perfetto dump trace.dat when generating .perfetto-trace at least? No need for a conversion, just an option to save trace.dat when starting the collection.

**Comment by primiano** [comment]
> kernelshark, trace-cmd and tools like https://github.com/ARM-software/lisa/ can parse trace.dat as it is.

Maybe I am misunderstanding what's a trace.dat format then. How can you parse the binary ftrace data if you don't know how event IDs map to ftrace events? AFAICT those IDs are not stable, example:

From [android_walleye_OPM5.171019.017.A1_4.4.88/events/sched/sched_switch/format](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/traced/probes/ftrace/test/data/android_walleye_OPM5.171019.017.A1_4.4.88/events/sched/sched_switch/format?q=f:perfetto%20f:sched_switch%2F.*format)
```
name: sched_switch
ID: 47
format:
...
```

From [android_seed_N2F62_3.10.49/events/sched/sched_switch/format](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/traced/probes/ftrace/test/data/android_seed_N2F62_3.10.49/events/sched/sched_switch/format?q=f:perfetto%20f:sched_switch%2F.*format)
```
name: sched_switch
ID: 68
format:
...
```

> Is it hard to make perfetto dump trace.dat when generating .perfetto-trace at least?

It's a non-trivial feature that requires extra work and adding more complexity and mainteinance to some code path that is 
already complicated. I don't see a super strong reason for doing so though. If you want just the raw ftrace data, why not using trace-cmd? It's very small, minimal and extremely efficient for that use case.

**Comment by chromy** [comment]
> Maybe I am misunderstanding what's a trace.dat format then. How can you parse the binary ftrace data if you don't know how event IDs map to ftrace events? AFAICT those IDs are not stable, example:

I think the file starts with the text of the format files: https://man7.org/linux/man-pages/man5/trace-cmd.dat.5.html#FTRACE_EVENT_FORMATS. (So whoever reads them parses those embedded format files first then uses that information to parse the information from the ring buffers which makes up the rest of the file). So yeah while it would be a cool feature unfortunately it's not a simple job to fake some format files and carefully repack all the events them as the kernel would do 😞
