### ISSUE TITLE
How do I consume the ftrace events?

### ISSUE THREAD

**Issue by jiqimaogou** [google/perfetto#203]
Hello, perfetto can record the function events. but in the perfetto ui, I can't find some trace event. How do I consume the ftrace events in the perfetto ui?

**Comment by LalitMaganti** [comment]
Perfetto supports collecting events but only some events are parsed and visualized. If you want to add a new event which is not currently visualized, please see https://perfetto.dev/docs/contributing/common-tasks#add-a-new-ftrace-event for info on how to add this.
