### ISSUE TITLE
Provide ability to change use a single display unit

### ISSUE THREAD

**Issue by studgeek** [google/perfetto#206]
Perfetto shows duration as a mix of units (e.g. `1ms 50us 792ns`), while catapult would show duration as a single unit (e.g. `1,050,792 ns`). The latter can be much easier to read and compare in many situations (IMHO), so it would be very helpful if Perfetto could provide an option to use a single unit.

One small step in the right direction would be if Perfetto padded zeroes for sub-units. So `1ms 50us 792ns` would be displayed as `1ms 050us 792ns`

**Comment by studgeek** [comment]
As another example, Perfetto will skip in-between units which can be quite confusing when comparing - `1ms 583ns`. This would be more readable and comparable  as `1.000583ms` or even `1ms 000us 583ns`
--

**Comment by primiano** [comment]
Yeah TBH i introduced that weird format but over time I disliked it myself.
Will try to figure out some better alternative.
I like the 0 padding idea but I am torn between:
- Try to fix it via css, so the "ms" "us" part is less invasive (e.g. subscript)
- Just give up and use a timecode-like string, similar to the one you suggest, like  01:02:03 . 004,005,006 ns, where 01:02:03 is H:M:S and the rest ns. If the value is <1s that might be showed up just as 0.004,005,006 s

**Comment by studgeek** [comment]
It's an interesting idea to make the ms/us/ns parts smaller subscripts to the point where they almost act as a comma (plus padding of course).
I think there may be cases where folks will want to copy the value, then the latter would be helpful. Maybe there is some HTML trickery where the text can use comma, but comma is spanned to be transparent to show the ms/us/ns underneath - so they can still select it as normal number.

**Comment by primiano** [comment]
Yeah was thinking something along these lines: https://jsfiddle.net/ugfrwy1q/

**Comment by alecazam** [comment]
Commas and spaces interfere when one tries to build spreadsheets out of timings or do visual comparisons.   We would prefer just 1.00058ms.

**Comment by LalitMaganti** [comment]
Folding this into https://github.com/google/perfetto/issues/272
