### ISSUE TITLE
How can I change the color of events?

### ISSUE THREAD

**Issue by rkieslinger** [google/perfetto#208]
In [this](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview) document is stated, that to color the events someone can set `cname` to a specific color name. The link to the color scheme in the document is broken, but I found [a link](https://chromium.googlesource.com/external/trace-viewer/+/bf55211014397cf0ebcd9e7090de1c4f84fc3ac0/tracing/tracing/ui/base/color_scheme.html) with color names, which are working in the legacy UI.

Here's a sample trace file:

```json
[
    {
        "name": "Event 1",
        "ph": "X",
        "ts": 0,
        "dur": 100000,
        "pid": 1,
        "tid": 1,
        "cname": "good"
    },
    {
        "name": "Event 2",
        "ph": "X",
        "ts": 0,
        "dur": 100000,
        "pid": 1,
        "tid": 1,
        "cname": "bad"
    },
    {
        "name": "Event 3",
        "ph": "X",
        "ts": 0,
        "dur": 100000,
        "pid": 1,
        "tid": 1,
        "cname": "terrible"
    }
]
```

Legacy UI:

![image](https://user-images.githubusercontent.com/20225125/145553689-6c1c8bd2-beba-4780-a932-7c0780cd368c.png)

New UI:

![image](https://user-images.githubusercontent.com/20225125/145553751-66008287-fcdb-4861-875f-01726e0e9bdd.png)

Why do they don't work with the new UI?

**Comment by LalitMaganti** [comment]
The JSON trace format is a legacy format and is supported on a best effort basis. There are no plans to support this feature in the future.

For more context, have a look at https://github.com/google/perfetto/issues/60 which talks about our approach to the JSON format.

**Comment by rkieslinger** [comment]
@LalitMaganti Thanks for the clarification! Where do I find the specification of the new format?

**Comment by LalitMaganti** [comment]
The native Perfetto format is protobuf based and the documentation of "TracePacket" (the root protobuf message you emit) can be found at https://perfetto.dev/docs/reference/trace-packet-proto

The proto definition is available here: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/trace_packet.proto

**Comment by facewindu** [comment]
Looking at TracePacket protobuf definitions, how can I set something on them to decide which color they should be rendered with in perfetto ?

**Comment by LalitMaganti** [comment]
An intentional decision was made when building the UI to decouple rendering decisions from the contents of the trace. Because of this, such a feature is not supported.

**Comment by facewindu** [comment]
> An intentional decision was made when building the UI to decouple rendering decisions from the contents of the trace. Because of this, such a feature is not supported.

this is understandable.
So, asking a little different question:
even without having myself the control on the rendering, what is affecting the rendering ? i.e. what can I do so that they are rendered differently (leaving the differently as an implementation detail)

let's say I have a few events of some custom types, and I want them all to be rendered 'the same', or a bit differently based on some condition (like their duration, etc)
Can I write some logic to eventually set something on the trace packets (like a type or sth) to 'group' them or differentiate in a way that will affect (but consistently) the rendering ?

**Comment by LalitMaganti** [comment]
The color choice is entirely defined by the slice name at the moment. We do want to make this more customizable in the future but this is not supported at the moment.

**Comment by habaohaba** [comment]
Can I ask what kind of rule does perfetto use to define event color based on slice name? Since I can change the name to affect color visualization.

**Comment by LalitMaganti** [comment]
It uses a hash of the slice name.
