### ISSUE TITLE
UI crash on recorded file

### ISSUE THREAD

**Issue by djdeath** [google/perfetto#215]
I manage to record traces and inspect them without problems using `trace_to_text` but the UI is just failing on them.
Here is an example attached
[trace.perfetto.zip](https://github.com/google/perfetto/files/7738284/trace.perfetto.zip)
.

**Comment by LalitMaganti** [comment]
Opening this trace in trace processor shows that there is clock snapshot problems in this trace:
```
[643.972]    clock_tracker.cc:116 Clock sync error: the trace clock (id=6) is not monotonic at snapshot 8. 4537780665525 not >= 4537781729244.
```

And trace bounds is messed up as well:
```
> select * from trace_bounds
start_ts             end_ts
-------------------- --------------------
       4537780198122  1537231480228114943
```

Are you sure that the GPU producers in the trace are correctly setting the clocks they are using?

**Comment by djdeath** [comment]
Thanks for looking into this @LalitMaganti.

You're right, there appears to be a problem : 
```
packet {
  trusted_uid: 1000
  timestamp: 1537228616361490706
  trusted_packet_sequence_id: 7
  gpu_render_stage_event {
    event_id: 0
    duration: 16909517128760357226
    context: 676
    extra_data {
      name: "count"
      value: "0"
    }
    submission_id: 412
    gpu_id: -128
    hw_queue_iid: 662
    stage_iid: 663
  }
  timestamp_clock_id: 2578085395
}
```
