### ISSUE TITLE
How can we capture io event?

### ISSUE THREAD

**Issue by gospeljohn** [google/perfetto#219]
In ui.perfetto.dev site, we can config to enable advanced ftrace config for io event like: ext4/f2fs/block etc.

Then in recording command: 

  data_sources: {
      config {
          name: "linux.ftrace"
          ftrace_config {
              ftrace_events: "block/*"
              ftrace_events: "ext4/*"
              ftrace_events: "f2fs/*"
              buffer_size_kb: 2048
              drain_period_ms: 1000
          }
      }
  }
  
But in trace file, we can not get any event about io information. 

Please tell me how we can get io events in trace file. Thanks.

**Comment by LalitMaganti** [comment]
The trace file includes these ftrace data but these are not supported for analysis in trace processor or visualization in the UI. We may add support for this for one day but this is not planned in the immediate future.
