### ISSUE TITLE
Why perfetto hasn't vsync highlight menu that in legacy ui.

### ISSUE THREAD

**Issue by soolaugust** [google/perfetto#220]
In legacy ui,  there's a "vsync hightlight" menu which is very convenient to figure out each frame status.  but in new perfetto ui, I couldn't find this menu.

**Comment by LalitMaganti** [comment]
These markers are quite misleading and not useful on newer versions of Android so have been replaced with frame timeline - see https://perfetto.dev/docs/data-sources/frametimeline.
