### ISSUE TITLE
[UI][Android] Recording command never finishes

### ISSUE THREAD

**Issue by sergeys-opera** [google/perfetto#221]
I'm unable to record a trace file using Perfetto UI. Tried with two different phones (Pixel and Pixel 4).

**Steps:**
1. Add a new ADB device
2. Select it
3. Enable "Scheduling details" under CPU 
4. Press "Start recording"

**Result:** the command never finishes. "Stop" and "Pause" buttons are displayed along with the command line example.
![image](https://user-images.githubusercontent.com/20795972/147572587-11b1d544-da06-4337-b1ac-5c0aeeb815ad.png)

What am I doing wrong?

**Comment by sergeys-opera** [comment]
Here are some errors I got in the JS console:
![image](https://user-images.githubusercontent.com/20795972/147573377-90924e7c-6593-499e-8bce-8aaf1a166507.png)

Also, running `record_android_trace` in the CLI works well:
```
./record_android_trace -o trace_file.perfetto-trace -t 10s -b 32mb \
sched freq idle am wm gfx view binder_driver hal dalvik camera input res memory
```

**Comment by LalitMaganti** [comment]
Try running `adb kill-server` before recording the trace from the UI.

**Comment by sergeys-opera** [comment]
When I tried today, the Perfetto UI just worked.

> Try running adb kill-server before recording the trace from the UI.
I got a popup yesterday regarding this and I did kill the adb server. That didn't help yesterday. And today I cannot reproduce the issue,

**Comment by sergeys-opera** [comment]
I got the same issue again today.

**Comment by sergeys-opera** [comment]
`adb kill-server` doesn't help.

**Comment by LalitMaganti** [comment]
@octaviantu has been looking at adb recording a lot recently.

**Comment by sergeys-opera** [comment]
And the problem was fixed by disabling and reenabling "USB debugging" option in "Developer Options" on the tested phone. I had to authenticate the connected PC again.

**Comment by LalitMaganti** [comment]
Yes that will definitely mess with things - the UI needs exclusive access to the adb interface right now - see https://github.com/google/perfetto/issues/224 for work we're around relaxing this limitation.
