### ISSUE TITLE
Trace Event Format (TEF) - Flow events import error

### ISSUE THREAD

**Issue by rpereira-dev** [google/perfetto#222]
When migrating from the legacy UI to Perfetto, my flow-events disappeared, and here is the result of my investigation.
Consider this minimal Trace Event Format (TEF) file, that reproduce the issue

```
  1 {
  2     "traceEvents": [
  3         {
  4             "name": "first",
  5             "ph": "X",
  6             "ts": 0,
  7             "dur": 100,
  8             "pid": 0,
  9             "tid": 0
 10         },
 11         {
 12             "name": "second",
 13             "ph": "X",
 14             "ts": 200,
 15             "dur": 100,
 16             "pid": 0,
 17             "tid": 0
 18         },
 19         {
 20             "ph": "s",
 21             "name": "the flow event",
 22             "cat": "the category",
 23             "id": "id42",
 24             "ts": 99,
 25             "pid": 0,
 26             "tid": 0
 27         },
 28         {
 29             "ph": "t",
 30             "name": "the flow event",
 31             "cat": "the category",
 32             "id": "id42",
 33             "ts": 201,
 34             "pid": 0,
 35             "tid": 0
 36         }
 37     ]
 38 }
```

**Expected behaviour**
There is 2 events ("first" and "second") linked by a flow-events.
Catapult legacy UI encounters no errors and imports every events.

**Current behaviour**
Perfetto generates an error on import, that is

Name | Value | Type
-- | -- | --
flow_invalid_id | 2 | error (trace)

**Notes**
- Using string values for id fields works on Catapult, though, I am not sure this respect TEF specifications.
- Replacing the **id** field value by an integer (e.g: _42_ instead of _id42_) is a work-around to achieve the expected behaviour.

**References**
Trace Event Format (TEF) specifications - https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview

**Comment by LalitMaganti** [comment]
The JSON trace format is a legacy format and is supported on a best effort basis. There are no plans to support strings for flow IDs in the future.

For more context, have a look at #60 which talks about our approach to the JSON format.
