### ISSUE TITLE
 The TraceConfig is empty is shown always

### ISSUE THREAD

**Issue by artrointel** [google/perfetto#223]
I have Samsung Galaxy Note 9 which is Android Q OS, and Galaxy Watch 4 which is Android Wear OS (R).
Both device always show "The TraceConfig is empty" whatever I put config options.
What should I do?

For example,

adb shell perfetto \
  -c - --txt \
  -o /data/misc/perfetto-traces/trace \
<<EOF

buffers: {
    size_kb: 63488
    fill_policy: DISCARD
}
buffers: {
    size_kb: 2048
    fill_policy: DISCARD
}
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            ftrace_events: "power/cpu_frequency"
            ftrace_events: "power/cpu_idle"
            ftrace_events: "power/suspend_resume"
        }
    }
}
duration_ms: 10000

EOF
[858.641] perfetto_cmd.cc:460     The TraceConfig is empty

**Comment by primiano** [comment]
This looks like some issue when copy/pasting the command. That command definitely works.
 Are you using bash or some other shell?
Maybe try saving first the config into a file and piping that file instead of using the heredoc (<<EOF) syntax

**Comment by artrointel** [comment]
> 

It looks like something wrong with my Windows OS during copy&paste. bash fails but shell in linux with the command works. thanks.
