### ISSUE TITLE
trace config invalid

### ISSUE THREAD

**Issue by Sunghyeok93** [google/perfetto#230]
Hello, I got this error when I turn on the 'Scheduling details' on CPU Probes.
could you help me?

-:69:13 error: No field named "symbolize_ksyms" in proto FtraceConfig
            symbolize_ksyms: true
            ^~~~~~~~~~~~~~~ 
[452.354] perfetto_cmd.cc:476     The trace config is invalid, bailing out.

**Comment by LalitMaganti** [comment]
Please provide the Android version of the device you are collecting the trace from

@octaviantu - maybe you can take a look at this as part of your refactoring.

**Comment by primiano** [comment]
This seem simly an issue of passing a config to an older device that doesn't support `symbolize_ksyms`

**Comment by Sunghyeok93** [comment]
Actually, my device is quite new.. galaxy Z Fold 3. and the Android version is 11.

**Comment by LalitMaganti** [comment]
Unfortunately `symbolize_ksyms` was added in Android S/12 so even Android 11 is too old for this flag.

As Primiano said, we should just not enable this option if you specify/we detect an older version in the UI when generating the config.

**Comment by Sunghyeok93** [comment]
That's why there was a problem. Thank you!

**Comment by LalitMaganti** [comment]
I think we'd still keep this issue open to track the change in the UI to stop specifying this flag.

**Comment by Sunghyeok93** [comment]
symbolize_ksyms is added when I turn on 'Scheduling details'. If so, is there any other way to get CPU Scheduling details on the Android version 11?

**Comment by LalitMaganti** [comment]
If you mean collecting directly through the UI (i.e. without using the command line), then this is not possible until we fix this bug.

However, uou can just remove that line from the generated config and run the adb command the UI gives. Scheduling info will still be collected in that case (the only thing you'll miss is some information like the kernel blocked function in sched_blocked_reason).

**Comment by LalitMaganti** [comment]
Fixed in https://github.com/google/perfetto/commit/327ad962a59d149ad6662fcbd18e38d808f91a3f

**Comment by octaviantu** [comment]
For now the fix is only available on the Autopush branch.
(you can get to Autopush by writing ` localStorage.perfettoUiChannel = 'autopush'` in the dev console)

It will be rolled out to canary and stable in the next few weeks.
