### ISSUE TITLE
There are many slices with negative duration

### ISSUE THREAD

**Issue by basketgd** [google/perfetto#232]
Hello Perfetto team
Thank you so much for making a very useful tool.

I used perfetto for finding cause of android drawing performance problem.
But there are some cases slices doesn't have duration value.
[negative_dur.zip](https://github.com/google/perfetto/files/7901470/negative_dur.zip)
(Attached file was recorded with ring buffer with small in-memory-buffer size for getting this problem easily.)

There are many negative duration slices in SystemUI main thread track so it is really inconvenient and I can't sure what slices's ts is correct or not.

**Comment by LalitMaganti** [comment]
This is a known issue which happens in cases where the central ring-buffer wraps in a bad way.  I'm closing this one as this is tracked by internal bug b/192586066.

Here is the detail from the internal bug:
Imagine the following sequence of ftrace bundles which completely fills the central ringbuffer:

bundle {
  cpu: 0
  end_slice { ts: 11, tid: 1 }
}
bundle {
  cpu: 1
  begin_slice { ts:10, name: foo, tid: 1 }
}
bundle {
  cpu: 0
  begin_slice { ts:13, name: bar, tid: 1 }
}
bundle {
  cpu: 1
  end_slice { ts:14, tid: 1 }
}
The output we would see in the UI would be:

Tid 1:           [ foo ]. [ bar]
Now suppose that we get another bundle which pushes out the first bundle only. This leaves the ring buffer in the following state:

bundle {
  cpu: 1
  begin_slice { ts:10, name: foo, tid: 1 }
}
bundle {
  cpu: 0
  begin_slice { ts:13, name: bar, tid: 1 }
}
bundle {
  cpu: 1
  end_slice { ts:14, tid: 1 }
}
bundle {
  cpu: 0
  begin_slice { ts: 15, name: baz, tid: 1 }
}
As we've lost the end event for foo, this leads to the following UI result:

Tid 1:           [ foo                                     } (unfinished)
                  [ bar] [ baz                             }
which is clearly wrong.

One proposal to fix this would be to reject all atrace slices before we see at least one event for every CPU. This would ensure any slices in the first bucket which have a begin but their end was dropped would be dropped as well.

This proposal has two problems:

1. We need to know the number of CPUs on the device. This can be done using either hardcoding (like the power profile info) or we can poll some node in /proc
2. Dropping information like this is always risky as we could drop more than we intended.
Other proposals are welcome.
