### ISSUE TITLE
UI build failed in Docker python:3

### ISSUE THREAD

**Issue by ylz-at** [google/perfetto#234]
Here is my Dockerfile,

```Dockerfile
FROM python:3
WORKDIR /opt/perfetto
COPY . .
RUN tools/install-build-deps --ui
RUN tools/gn gen out/debug --args='is_debug=true'
RUN tools/ninja -C out/debug ui

ENTRYPOINT ['./ui/run-dev-server']
```

build failed with error log,

```
52/59  python3 ../../tools/gen_ui_imports ../../ui/src/tracks --out ../../ui/src/gen/al
--out (/opt/perfetto/ui/src/gen/all_tracks.ts) parent directory (/opt/perfetto/ui/src/gen) must exist
```

**Comment by primiano** [comment]
You are handling it wrong.
https://perfetto.dev/docs/contributing/build-instructions#ui-development

Take also look at https://cs.android.com/android/platform/superproject/+/master:external/perfetto/tools/run_test_like_ci
which it does the right setup for you.

**Comment by ylz-at** [comment]
I guess README is outdated, https://github.com/google/perfetto/blob/master/ui/README.md

**Comment by primiano** [comment]
Thanks for pointing out.
Sent out https://android-review.googlesource.com/c/platform/external/perfetto/+/1956097 to fix that readme.

**Comment by ylz-at** [comment]
Nice.

I fixed the build issue by `mkdir -p ui/out/tsc/gen` before build.

```Dockerfile
FROM python:3
WORKDIR /opt/perfetto
COPY . .
RUN mkdir -p ui/out/tsc/gen
RUN tools/install-build-deps --ui
RUN ui/build

ENTRYPOINT ['./ui/run-dev-server']
```
