### ISSUE TITLE
Slices are not properly rendered when have overlap in a single track

### ISSUE THREAD

**Issue by ztlevi** [google/perfetto#237]
slices are generated by `TRACE_EVENT_BEGIN` and `TRACE_EVENT_END`. For example, 0-5 means a slice begin at 0s and end at 5s.

When I have multiple slices in a single track have overlaps, it's not properly rendered. For example, 0-5 and 3-7 ends up 0-7 and 3-5. This is weird. Might be a bug you want to resolve on your end. 

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/16655096/151603690-a5fe5723-9c44-410b-9845-068f75e44af0.png">

Could you take a look?
Thanks,

**Comment by LalitMaganti** [comment]
This is working as intended. TRACE_EVENT_BEGIN is intended for slices on a single thread which perfectly nest inside each other; overlapping is not allowed. This is noted in the track_event header: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/include/perfetto/tracing/track_event.h;l=75?q=TRACE_EVENT_BEGIN

Please use *ASYNC* macros as described here: https://cs.android.com/android/platform/superproject/+/master:external/webrtc/rtc_base/trace_event.h;l=78?q=TRACE_EVENT_ASYNC_BEG
