### ISSUE TITLE
rror: ComputeMetric() error: Unknown metric chrome_dropped_frames

### ISSUE THREAD

**Issue by qais-yousef** [google/perfetto#239]
When capturing a long trace, I constantly hit this weird error:

```
Viewed on: https://ui.perfetto.dev

Query: COMPUTE_METRIC
Error: ComputeMetric() error: Unknown metric chrome_dropped_frames
QueryError@https://ui.perfetto.dev/v21.0-5e6f200f1/frontend_bundle.js:74784:9
onRpcResponseMessage@https://ui.perfetto.dev/v21.0-5e6f200f1/frontend_bundle.js:75580:27
onRpcResponseBytes@https://ui.perfetto.dev/v21.0-5e6f200f1/frontend_bundle.js:75499:18
endFetch/<@https://ui.perfetto.dev/v21.0-5e6f200f1/frontend_bundle.js:86676:19


v21.0-5e6f200f1 5e6f200f1188f87c3eab9c0e9cdc57e7c947d982
UA: Mozilla/5.0 (X11; Ubuntu; Linux aarch64; rv:96.0) Gecko/20100101 Firefox/96.0
```

Captured on Pixel 6 which runs my own compiled standad AOSP based on 12.0.0_r27. I haven't changed anything in AOSP stack.

Something wrong in my settings or old version of trace_processor? I did download the latest from:

`curl -LO https://get.perfetto.dev/trace_processor`

Apologies if this is the wrong place to report this.

**Comment by LalitMaganti** [comment]
It seems likely that you're using an old version of trace processor: this metric was added in Nov by https://android-review.googlesource.com/c/platform/external/perfetto/+/1880050

Can you please verify the contents of your trace_processor script matches the copy [here](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/tools/trace_processor;l=1?q=f:trace_processor%20f:tools&sq=) (specifically, the "Revision" comment and the "trace_processor_shell" SHA.

**Comment by qais-yousef** [comment]
Thanks. Downloading the latest perfetto release which includes the trace_processor_shell works. I'm sure I downloaded the 'latest' release not so long ago, but maybe my memory failed me. Sorry for the noise and thanks for the help.
