### ISSUE TITLE
Is llvm-symoblizer required, or is that what trace_to_text does now?

### ISSUE THREAD

**Issue by tmm1** [google/perfetto#24]
In the docs it mentions you need llvm-symbolizer and it only works on linux. https://docs.perfetto.dev/#/heapprofd?id=symbolization

Is this still accurate?

**Comment by segfaulthunter** [comment]
Yes, that is correct. For offline symbolization, we shell out to `llvm-symbolizer`. We use `elf.h` to read from ELF files, which is not available on macOS per default.
