### ISSUE TITLE
Add support for saving multiple sets of pinned tracks

### ISSUE THREAD

**Issue by kting28** [google/perfetto#242]
Hello,

Just want to check if there are any plans to support saving the trace viewer state - i.e. users like to customize the pinned items and order them on the UI but they have to do that every time after loading a new trace file.

Thanks!

**Comment by LalitMaganti** [comment]
@chromy are there any solid plans here?

**Comment by gramound** [comment]
I would like that feature too. I often find myself setting-up the same set of pinned rows to observe interactions between several processes only to realize that my trace missed something and I have to start over again with the next capture. If it's any easier to implement, I could do with a "replace current capture while keeping pinned rows (if they exist in the new capture)" feature...

**Comment by kting28** [comment]
keeping the pinned rows on reload will be a great first step. However for my use case that can't replace saving the pinned items so that we can share with other users.

**Comment by LalitMaganti** [comment]
Going to fold this into https://github.com/google/perfetto/issues/429

**Comment by kting28** [comment]
Hi , this is folded in #429 but I don't see any way to save pins. Is the feature request dropped?

**Comment by LalitMaganti** [comment]
This shouldn't have been folded, my mistake. There is no update on this: we don't have a solution for sharing the state of a trace for non-Googlers.

**Comment by kting28** [comment]
Thanks for the update. I guess I don't need the "state"  of a trace but just the pins. Today everytime I open a complicated trace I need manually select the pinned trace. Other users in my organization has other set of pins they want to share. Is that easier than sharing state of a trace?

**Comment by LalitMaganti** [comment]
We would not solve one without the other: we already have a permalink sharing system inside Google which persists not only pinned tracks but also selection state, flamegraph filters etc.

We would not do something different other than making that solution available to everyone.

**Comment by kting28** [comment]
btw I just realized save/restore feature:
![Image](https://github.com/user-attachments/assets/6da37e5c-e97c-44c7-bd1d-58448d1bfad6)
this is mostly there, just missing the saving different sets of pins. Thanks !

**Comment by LalitMaganti** [comment]
OK clearly I misunderstood what you were asking for: I thought you were asking to share the pins of a trace with another user. Reading closer, I think what you actually want is the ability to save a set of pins and use that on multiple trace files.

https://github.com/google/perfetto/issues/242#issuecomment-2479372290: I forgot that feature existed actually. That comment inspired me to write https://r.android.com/3366281

Basically now I added two commands to the UI: ![Image](https://github.com/user-attachments/assets/04fb128b-7aa5-460e-bb28-dbe5a6cd7ea9)

If I click "Save by name": I get the following prompt where I can type a name for the pins I have open: ![Image](https://github.com/user-attachments/assets/7d5e3c27-0e50-4184-9baa-b1db15d43fac)

Then I can restore these set of pins: ![Image](https://github.com/user-attachments/assets/bea27d55-ed12-4596-aa50-3199056729ef)

Which will cause all the tracks to be repinned:
![Image](https://github.com/user-attachments/assets/6b18ce01-4ace-4a77-8106-94dd0d8b7771)

**Comment by kting28** [comment]
Thanks @LalitMaganti  ! Yes this is mostly what we need. The only remaining thing is share the set of pins with another user. Here from the screen shot above, it seems it's only stored locally for 1 user right?

**Comment by LalitMaganti** [comment]
Yeah I don't have a good solution in mind for that. I agree it makes sense, not clear to me what a good UX for that should be. Maybe some export and import functions?

**Comment by kting28** [comment]
Sure, I think a simple import and export command (export <saved pinned name>) with a file selector dialog is enough. On import , select a file and ask the user for the name of the saved pins (or just take from the file content?). Overwite existing pins if they are named the same. 
Again thanks for the support !

**Comment by LalitMaganti** [comment]
https://r.android.com/3368501 will add support for this and I believe will close this issue out.
