### ISSUE TITLE
Does trace_processor or other existing implemented approach support multiple traces?

### ISSUE THREAD

**Issue by ztlevi** [google/perfetto#247]
Hi, 

I am aware of `cat` and `--full-sort` can be used for multiple traces from this ticket, https://github.com/google/perfetto/issues/43.

But I didn't see multiple files are supported by `trace_processor` https://github.com/google/perfetto/blob/master/src/trace_processor/trace_processor_shell.cc#L1316. 

Are there other approaches implemented to support serving multiple traces?

Thanks,

**Comment by LalitMaganti** [comment]
Trace processor supports handling exactly one trace only. For querying multiplke traces, we're actively working on batch trace processor (https://github.com/google/perfetto/blob/master/python/perfetto/batch_trace_processor/api.py#L49) but this is still a work in progress and there is no public documentation on this yet (but we're hoping to have this in the coming months)

**Comment by ztlevi** [comment]
Thanks, it would be really helpful
