### ISSUE TITLE
Is perfetto not support Android13 Developer Preview?

### ISSUE THREAD

**Issue by basketgd** [google/perfetto#248]
Hello Perfetto team
I flashed Pixel5 device with Android13 preview and then tried to recording perfetto using "Record new trace" menu in perfetto ui.
But there are no atrace slices in slice table.(I enabled all of atrace tag. But there are only about binder transaction)

Is perfetto doesn't support Android13 preview?

**Comment by primiano** [comment]
@ddiproietto ^

**Comment by primiano** [comment]
> The problem has been fixed now, I'll let you know when you can try another build of Android 13 with the fix applied.

I think the statement here is: will be fixed in the next Android 13 Developer Preview (DP2). DP1 was cut at an unfortunate time and that bug was caught in.

**Comment by basketgd** [comment]
Thank you for your quick response. :)
I really hope to using perfetto in next preview image.
