### ISSUE TITLE
heap_profile for my jni libs showing only first frame of stack trace

### ISSUE THREAD

**Issue by tmm1** [google/perfetto#25]
Firstly, thanks for all the fixes this morning. I'm now able to run `tools/heap_profile` on my mac and it works!

Now that I can capture some profiles, I'm noticing that calling stacks are missing for functions in my app's native libraries. Do I need to build with `-fno-omit-frame-pointer`, or is there something else I can do to get proper caller/callee information?

<img width="1214" alt="Screen Shot 2020-04-28 at 10 12 38 AM" src="https://user-images.githubusercontent.com/2567/80516757-ce44a300-8938-11ea-9c03-270c44bfbf0d.png">

<img width="1002" alt="Screen Shot 2020-04-28 at 10 12 00 AM" src="https://user-images.githubusercontent.com/2567/80516764-d00e6680-8938-11ea-892f-2629f66e8e9c.png">

**Comment by segfaulthunter** [comment]
Hey! Would it be possible for you upload  the `.so` so I can take a look? We unwind using DWARF data.

Feel free to join our Discord (https://discordapp.com/channels/629013440635207702/629013441096450058) for more real-time debugging help :)

**Comment by segfaulthunter** [comment]
Also, could you attach the output of `adb logcat | grep "perfetto\|heapprofd" ` so I can see if there is something suspicious there?

**Comment by tmm1** [comment]
```
04-28 09:49:18.836 19072 19072 I perfetto: perfetto_cmd.cc:604 Connected to the Perfetto traced service, starting tracing for 604800000 ms
04-28 09:49:18.839  7385  7385 I perfetto: tracing_service_impl.cc:529 Configured tracing, #sources:2, duration:604800000 ms, #buffers:1, total buffer size:32768 KB, total sessions:2
04-28 09:49:58.263 19072 19072 I perfetto: perfetto_cmd.cc:815 SIGINT/SIGTERM received: disabling tracing.
04-28 09:49:58.407  7386  7386 I perfetto: probes_producer.cc:314 Producer stop (id=7)
04-28 09:49:58.410 19072 19072 I perfetto: perfetto_cmd.cc:674 Trace written into the output file
04-28 09:49:58.425  7385  7385 I perfetto: tracing_service_impl.cc:1660 Tracing session 3 ended, total sessions:1
04-28 09:49:58.579  7102  7174 E perfetto: client.cc:375 Failed to send control socket byte. (errno: 32, Broken pipe)
04-28 09:49:58.579  7102 19125 E perfetto: client.cc:375 Failed to send control socket byte. (errno: 32, Broken pipe)
04-28 10:38:47.374  7600  7600 I perfetto: perfetto_cmd.cc:815 SIGINT/SIGTERM received: disabling tracing.
04-28 10:38:47.380  7386  7386 I perfetto: probes_producer.cc:314 Producer stop (id=4)
04-28 10:38:47.381  7600  7600 I perfetto: perfetto_cmd.cc:674 Trace written into the output file
04-28 10:38:47.391  7385  7385 I perfetto: tracing_service_impl.cc:1660 Tracing session 2 ended, total sessions:0
^C
```

I wasn't using `PERFETTO_BINARY_PATH` above, could that be part of the problem?

**Comment by segfaulthunter** [comment]
Ad `PERFETO_BINARY_PATH`: That shouldn't be the cause, as that would still show the unsymbolized frames.

**Comment by segfaulthunter** [comment]
The library had all the unwinding information stripped. We need one of 

* .gnu_debugdata
* .eh_frame (+ preferably .eh_frame_hdr)
* . debug_frame.

@tmm1 could you add your changes to your build to this bug for posterity?

**Comment by tmm1** [comment]
So the issue was that the android build process strips all the jniLibs. I tried `LOCAL_STRIP_MODE := none`, but ultimately what worked was adding `packagingOptions.doNotStrip "**/*.so"` to my app/build.grade

See https://stackoverflow.com/questions/40355200/how-to-avoid-stripping-for-native-code-symbols-for-android-app

**Comment by tmm1** [comment]
> ultimately what worked was adding `packagingOptions.doNotStrip "**/*.so"` to my app/build.grade

There is a way to do this with just debug builds now in AGP 7.0.0: https://issuetracker.google.com/issues/155215248#comment5
