### ISSUE TITLE
Suggestion about deep linking

### ISSUE THREAD

**Issue by basketgd** [google/perfetto#250]
Hello,
I use deep linking to the Perfetto UI feature very conveniently.
It is really easy to share to my co-worker and easy to collaborate on a specific perfetto.

Anyway, whenever I use deep linking, I have to give more information about what slice should be checked.
Like "Please check 3rd slice in binder:47 thread, SystemUI process." or "Please check longest slice in Gallery main thread."
And we can suppose that there are some slices(very short or having similar duration) can make confuse what slice is selected.

Would you check about any slice get the focus(like 'f' key function) after perfetto loaded?
Perfetto user can deliver slice id when post a message like below.
  {
    'perfetto': {
      buffer: ArrayBuffer;
      title: string;
      fileName?: string;  // Optional
      url?: string;       // Optional
      [anySlice ?: int;       // Optional]
    }
  }

Would you please check about this idea?

**Comment by LalitMaganti** [comment]
Something similar to this has been implemented by changing the URL to have arguments for timestamp/duration/pid etc. Code for this can be found [here](https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/ui/src/frontend/index.ts;l=330?q=maybeSetPendingDeeplink&ss=android%2Fplatform%2Fsuperproject%2Fmain)
