### ISSUE TITLE
Perfetto doesn't deal with overlapping async events

### ISSUE THREAD

**Issue by kwasimensah** [google/perfetto#254]
Bascially https://bugs.chromium.org/p/chromium/issues/detail?id=1295625#c1 but for perfetto. Copy-pasted here for convenience

The following JSON will cause the current logic to not match the begin/end of the events below because the the begin event for test1 will be sorted ahead of the end event of test0.

```
{
  "traceEvents": [
    {
      "name": "testparent",
      "cat": "profile",
      "ph": "b",
      "ts": 0,
      "pid": 1,
      "tid": 1,
      "id": "1"
    },
    {
      "name": "test0",
      "cat": "profile",
      "ph": "b",
      "ts": 0,
      "pid": 1,
      "tid": 1,
      "id": "1"
    },

    {
      "name": "test0",
      "cat": "profile",
      "ph": "e",
      "ts": 3,
      "pid": 1,
      "tid": 1,
      "id": "1"
    },

    {
      "name": "test1",
      "cat": "profile",
      "ph": "b",
      "ts": 1,
      "pid": 1,
      "tid": 1,
      "id": "1"
    },

    {
      "name": "test1",
      "cat": "profile",
      "ph": "e",
      "ts": 4,
      "pid": 1,
      "tid": 1,
      "id": "1"
    },
    {
      "name": "testparent",
      "cat": "profile",
      "ph": "e",
      "ts": 5,
      "pid": 1,
      "tid": 1,
      "id": "1"
    }
  ]
}
```

**Comment by kwasimensah** [comment]
Context: I'm trying to trace async javascript code by tracking the begin/end time of promises

**Comment by LalitMaganti** [comment]
Given that Perfetto doesn't even support JSON async events (see https://github.com/google/perfetto/issues/60), I doubt you're actually seeing this behaviour on the Perfetto UI.

Patches for that issue are very welcome: it should just be a matter of adding the relevant parsing code [here](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/importers/json/json_trace_parser.cc;l=149?q=f:json_trace_parser.cc)

**Comment by kwasimensah** [comment]
about://tracing tells me to try the new Perfetto UI and I was assuming that meant it accepted trace files in the trace_event format that my tool is generating. Digging through the code, it  actually uses it's one proto format that it allows to be converted to the trace_event format
