### ISSUE TITLE
Add Tracing for /proc/pic/smaps_rollup

### ISSUE THREAD

**Issue by moussaba** [google/perfetto#258]
smaps_rollup provides a more granular and accurate view of a process's memory usage. In particular it provides the Proportional Set Size (Pss) which provides the processes share of the resident memory usage if it uses shared pages with other processes. You will therefore be able to see the Rss vs. Pss in addtion to Swap vs. SwapPss. 

We would like to contribute and add tracing capability for the data contained in the smaps_rollup. Any guidance for a starting point would be helpful.

a52q:/proc/10660 # cat smaps_rollup
12c00000-7fd14f2000 ---p 00000000 00:00 0                                [rollup]
Rss:               55656 kB
Pss:                7071 kB
Shared_Clean:      31232 kB
Shared_Dirty:      18984 kB
Private_Clean:       240 kB
Private_Dirty:      5200 kB
Referenced:        32716 kB
Anonymous:         23876 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:              35232 kB
SwapPss:            1194 kB
Writeback:             0 kB
Locked:                0 kB

**Comment by funfoolsuzi** [comment]
@primiano I'd like to take this on with your suggestion that having an explicit opt-in option in process_stats_data_source.cc. I wonder if we can re-open this issue or start with a new one?
