### ISSUE TITLE
Chromium stack sampler in Perfetto?

### ISSUE THREAD

**Issue by ivberg** [google/perfetto#261]
How does the Chromium stack sampler data collection process work?

>cpu_profile_[stack_sample](https://perfetto.dev/docs/analysis/sql-tables#stack_sample)
>Extends stack_sample

>Samples from the Chromium stack sampler.

I tried these various workflows, and while all loaded in Perfetto UI, nothing showed up in the above table or that looked like Chromium stack samples (ideally with JS stacks decoded)

1. ui.perfetto.dev Chrome Trace Config
2. chrome://tracing including "State Sampling"
3. Chromium dev tools Performance trace, saving file, then loading in Perfetto

**Comment by LalitMaganti** [comment]
@ddrone @betasheet know more about Chrome related things.

**Comment by betasheet** [comment]
Some instructions are here: https://source.chromium.org/chromium/chromium/src/+/main:tools/tracing/README.md

The chrome-integrated profiler doesn't currently work well on Android though, because its unwinder has limitations.
IIRC it also only covers specific opted-in threads (likely just main & IO threads currently).

Both of these limitations are actively being worked on, as well as support for Perfetto's system-level stack sampling for Chromium.

**Comment by ivberg** [comment]
Thx for the link @betasheet ! 
>The chrome-integrated profiler doesn't currently work well on Android though, because its unwinder has limitations.

The linked [instructions ](https://source.chromium.org/chromium/chromium/src/+/main:tools/tracing/README.md) shows the table below and given the issues you just mentioned not working well on Android, it gives the appearance of nothing is supported??
<html>
<body>
<h2 style="margin: 1em 0px; padding: 0px; box-sizing: border-box; border-color: var(--border); font: 400 1.69231rem / 2.15385rem &quot;Google Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; letter-spacing: normal; color: rgb(232, 234, 237); orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(16, 16, 18); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">What's supported?</h2>

Platform | Trace Recording | Trace Symbolization
-- | -- | --
Android | ✔️ | ✔️
Linux | ❌ (use https://ui.perfetto.dev) | ✔️
MacOS | ❌ (use https://ui.perfetto.dev) | ✔️
Windows | ❌ | ❌

<br class="Apple-interchange-newline">
</body>
</html>What's supported?
Platform	Trace Recording	Trace Symbolization
Android	✔️	✔️
Linux	❌ (use https://ui.perfetto.dev/)	✔️
MacOS	❌ (use https://ui.perfetto.dev/)	✔️
Windows	❌	❌

**Comment by betasheet** [comment]
I believe you'd have to record a trace manually using the Perfetto UI on other platforms, I presume by manually enabling the "cpu_profiler" high-overhead category (disabled-by-default-cpu_profiler). @ssiddhartha would be the expert on this tooling, but he's moved on teams.

As I mentioned, we're focusing on Android stack sampling support improvements for chrome at the moment, so stay tuned ;)

**Comment by LalitMaganti** [comment]
I think we've done as much here as we plan on doing (V8 samples are available, on Mac we have instruments available, on Linux we have perf available).
