### ISSUE TITLE
I opened UI page failed, refresh not used, firefox

### ISSUE THREAD

**Issue by shisenxd** [google/perfetto#262]
the page shows:
Perfetto UI - An unrecoverable problem occurred

If you are seeing this message, something went wrong while loading the UI.
Please file a bug (details below) and try these remediation steps:

* Force-reload the page with Ctrl+Shift+R (Mac: Meta+Shift+R) or
  Shift + click on the refresh button.

* [Click here](javascript:clearAllCaches();) to clear all the site storage and caches and reload the page.

* Clear the site data and caches from devtools, following [these instructions](https://developers.google.com/web/tools/chrome-devtools/storage/cache#deletecache).

* If neither of these work, you can use an old fallback instance hosted at
  [staging-dot-perfetto-ui.appspot.com](https://staging-dot-perfetto-ui.appspot.com/)

In any case, **FILE A BUG** attaching logs and screenshots from devtools.
  Googlers:      [go/perfetto-ui-bug](http://go/perfetto-ui-bug)
  Non-googlers:  [github.com/google/perfetto/issues/new](https://github.com/google/perfetto/issues/new)

Timed out
Failed to load https://ui.perfetto.dev/v23.0-b574f45ca/frontend_bundle.js

Technical Information:
LocalStorage: {}

**Comment by primiano** [comment]
I just tried with Firefox 97.0.1 (64-bit) and it works.

I think what's happening here is that your connection is too slow and times out while fetching resources.
Try again, there is nothing more I can suggest.
