### ISSUE TITLE
Destination Slice lost on v24.2

### ISSUE THREAD

**Issue by liuhaiongl** [google/perfetto#264]
1. I saw your commit 6b51562404730712da2e8d2daf23085a364f7c1d remove "Destination Slice" which can direct to destination by click. 
why deleted this ? I just saw a flow from source to dest and can not click to destination thread.

2. the shortcut 
[/] (with event selected)
Select next/previous slice that is connected by a flow. If there are multiple flows,the one that is in focus (bold) is selected
how does this work ? I click '[' and nothing happen..

**Comment by primiano** [comment]
@ddrone @chromy @LalitMaganti I think we got some similar report about 1 from Tim yesterday. Seems mostly an accident. Can somebody check / confirm what's going on ?

**Comment by LalitMaganti** [comment]
So in response:
1) this was completely intetional. Destination slice was a hack invented before we introduced flow events in to the UI. I'd actually love to eventually rip all that code out of the UI entirely once we fix all the usability problems around flows and are sure we won't want to revert
2. This is the real problem why people want Destination Slice back. @ddrone is working on a CL (prototype at https://android-review.googlesource.com/c/platform/external/perfetto/+/2026584) to fix this.

**Comment by liuhaiongl** [comment]
Hi 
does that mean we can navigation source or dest by moving forward or backward ?

but the shortcut '[/]' do not work which they call moveByFocusedFlow. how does this work ?

Brs

**Comment by liuhaiongl** [comment]
Oh I got your point.
now moveByFocusedFlow only for flow event. i can use '[/]' and then press f to focus. 👍 
does perfetto support moving slice to next/prev slice by shortcut. like systrace in chrome://tracing which can use arrow key to next slice.

**Comment by LalitMaganti** [comment]
The idea is that [ and ] should not only change the selected slice but also shift focus.

**Comment by liuhaiongl** [comment]
Does google will support the feature? Now [ and ] only for flowevent
