### ISSUE TITLE
How to show "cpu frequency limits" metrics like legacy version?

### ISSUE THREAD

**Issue by soolaugust** [google/perfetto#268]
such as following screenshot.

![image](https://user-images.githubusercontent.com/10558124/161028968-4f5bd435-5d00-418e-91f1-3a563894e98b.png)

**Comment by LalitMaganti** [comment]
This has landed in https://github.com/google/perfetto/commit/56df5e60759763d5599b2e7edfa556acbb96a5ff and will make its way to stable shortly.

**Comment by soolaugust** [comment]
@LalitMaganti I change to `autopush` channel, still not found this metrics

**Comment by chromy** [comment]
I'm afraid the UI side still needs to land: https://android-review.googlesource.com/c/platform/external/perfetto/+/2032303
