### ISSUE TITLE
SDK support for nestable async events

### ISSUE THREAD

**Issue by rburchell** [google/perfetto#270]
I've used Chromium's macros (and JSON trace format) a lot in the past, and was pretty happy.

Perfetto looks like a very neat project, but I can't seem to find any mention of async begin/end events, which are very handy as not everything maps neatly to a begin/end that match a function's scope, and sometimes you have many of them ongoing at once (e.g. network upload/download).

Back when I last paid attention to tracing, this was via IIRC `TRACE_EVENT_ASYNC_BEGIN0` which has apparently since been replaced by NESTABLE_ASYNC_BEGIN in trace_event_common now, like so:

```
#define TRACE_EVENT_NESTABLE_ASYNC_BEGIN0(category_group, name, id)        \
  INTERNAL_TRACE_EVENT_ADD_WITH_ID(TRACE_EVENT_PHASE_NESTABLE_ASYNC_BEGIN, \
                                   category_group, name, id,               \
                                   TRACE_EVENT_FLAG_NONE)
```

Is this something that Perfetto's SDK will offer in the future? I would love to make use of it again, outside of Chromium...

**Comment by primiano** [comment]
@betasheet @chromy

**Comment by betasheet** [comment]
Perfetto generalizes the concept of async events to "track events" -- you can provide a custom track to the macros, e.g.

```
TRACE_EVENT_BEGIN("cat", "name", perfetto::Track(my_track_id));
```

See https://perfetto.dev/docs/instrumentation/track-events#tracks for details.

**Comment by rburchell** [comment]
Okay, that's good to know. I had read that section of the docs, but I assumed that events weren't typically nestable. I'll try that out, thanks!
