### ISSUE TITLE
absolute time support of 'Start time' 

### ISSUE THREAD

**Issue by severecold** [google/perfetto#272]
Could we have the absolute time ( would be 'trace_start_timestamp' + 'Start time' ) support in slice details ?  

Category	binder
Start time | 1s 341ms 3us 745ns
Duration | 0s

**Comment by LalitMaganti** [comment]
For Googlers, this is tracked internally by bug b/183628599

**Comment by tsarvey** [comment]
Seconded.  It looks like the first slice always appears to start at 100ns.

**Comment by LalitMaganti** [comment]
This has now be implemented.
