### ISSUE TITLE
Does current perfetto show "Uninterruptible reason"?

### ISSUE THREAD

**Issue by soolaugust** [google/perfetto#273]
If so , how to check?

**Comment by LalitMaganti** [comment]
![image](https://user-images.githubusercontent.com/679100/162951148-a0beb2e6-a5f2-4a85-bcd9-dac396f2f3e0.png)

If you collect the `sched_blocked_reason` ftrace event, the blocking function will appear in the thread state when in uninterruptible sleep as you can see in the screenshot above.

**Comment by primiano** [comment]
Note: that requires symbolize_ksyms=true in the trace config, which in turn works only on userdebug images.

**Comment by Bloodhoofwow** [comment]
> ![image](https://user-images.githubusercontent.com/679100/162951148-a0beb2e6-a5f2-4a85-bcd9-dac396f2f3e0.png)
> 
> If you collect the `sched_blocked_reason` ftrace event (only available on Android devices), the blocking function will appear in the thread state when in uninterruptible sleep as you can see in the screenshot above.

Tried not working
Only when tracing_on is turned off, perfetto can work, but when tracing_on is turned off, sched_blocked_reason will not output


config_full.pbtx
`buffers: {
    size_kb: 63488
    fill_policy: DISCARD
}
buffers: {
    size_kb: 2048
    fill_policy: DISCARD
}
data_sources: {
    config {
        name: "android.gpu.memory"
    }
}
data_sources: {
    config {
        name: "linux.process_stats"
        target_buffer: 1
        process_stats_config {
            scan_all_processes_on_start: true
            proc_stats_poll_ms: 1000
        }
    }
}
data_sources: {
    config {
        name: "android.log"
        android_log_config {
        }
    }
}
data_sources: {
    config {
        name: "android.surfaceflinger.frametimeline"
    }
}
data_sources: {
    config {
        name: "android.game_interventions"
    }
}
data_sources: {
    config {
        name: "linux.sys_stats"
        sys_stats_config {
            meminfo_period_ms: 1000
            vmstat_period_ms: 1000
            stat_period_ms: 1000
            stat_counters: STAT_CPU_TIMES
            stat_counters: STAT_FORK_COUNT
        }
    }
}
data_sources: {
    config {
        name: "android.heapprofd"
        target_buffer: 0
        heapprofd_config {
            sampling_interval_bytes: 4096
            continuous_dump_config {
                dump_interval_ms: 10000
            }
            shmem_size_bytes: 8388608
            block_client: true
            all_heaps: true
        }
    }
}
data_sources: {
    config {
        name: "android.java_hprof"
        target_buffer: 0
        java_hprof_config {
        }
    }
}
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            ftrace_events: "sched/sched_switch"
            ftrace_events: "power/suspend_resume"
            ftrace_events: "sched/sched_wakeup"
            ftrace_events: "sched/sched_wakeup_new"
            ftrace_events: "sched/sched_waking"
            ftrace_events: "power/cpu_frequency"
            ftrace_events: "power/cpu_idle"
            ftrace_events: "power/gpu_frequency"
            ftrace_events: "gpu_mem/gpu_mem_total"
            ftrace_events: "raw_syscalls/sys_enter"
            ftrace_events: "raw_syscalls/sys_exit"
            ftrace_events: "mm_event/mm_event_record"
            ftrace_events: "kmem/rss_stat"
            ftrace_events: "ion/ion_stat"
            ftrace_events: "dmabuf_heap/dma_heap_stat"
            ftrace_events: "kmem/ion_heap_grow"
            ftrace_events: "kmem/ion_heap_shrink"
            ftrace_events: "sched/sched_process_exit"
            ftrace_events: "sched/sched_process_free"
            ftrace_events: "task/task_newtask"
            ftrace_events: "task/task_rename"
            ftrace_events: "lowmemorykiller/lowmemory_kill"
            ftrace_events: "oom/oom_score_adj_update"
            ftrace_events: "ftrace/print"
            atrace_apps: "*"
            ftrace_events: "sched/sched_blocked_reason"
            symbolize_ksyms: true
            compact_sched {
                enabled: true
            }
        }
    }
}
duration_ms: 10000`



adb shell "cat /data/misc/perfetto-configs/config_full.pbtx | perfetto --txt -c - -o /data/misc/perfetto-traces/trace.perfetto-trace"
