### ISSUE TITLE
timestamp/duration no longer properly interpreted as `nanoseconds` when using TraceEvent JSON format

### ISSUE THREAD

**Issue by BKcore** [google/perfetto#274]
# Minimal repro
Open https://ui.perfetto.dev/#!/viewer

Load minimal JSON trace with nanosecond timestamps such as:
```
{
  "displayTimeUnit": "ns",
  "traceEvents": [
    {
      "name": "Frame",
      "ph": "X",
      "ts": 1236,
      "pid": 188088,
      "tid": 1,
      "cat": "Rendering",
      "dur": 13837451
    }
  ]
}
```

In perfetto we see
![image](https://user-images.githubusercontent.com/658297/163081828-75b180f5-37f9-4d19-b846-cd45eeb09528.png)

## Expected
Start time: 1us 236ns
Duration: 13ms 837us 451ns

## Actual (bug)
Start time: 100ns
Duration: 13s 837ms 451us

# Description of the bug

We have traces stored as JSON using the TraceEvent JSON format where timestamps and durations are stored as nanoseconds (long). These traces used to load fine a month ago, but today when I load the same traces the durations and timestamps are wrong and don't match the JSON data. It looks like durations are off by a factor of 1000 and interpreted as milliseconds instead of nanoseconds, while timestamps are just plain wrong.

Is this a known issue or a recent breaking change?

Thank you!

**Comment by chromy** [comment]
Hey! Thank you for the detailed bug report! I think this is the best issue report in the github tracker so far! 😄 

### Regarding duration:
The behaviour of `displayTimeUnit` was changed [here](https://android-review.googlesource.com/c/platform/external/perfetto/+/1888768) to better match the behaviour of chrome://tracing.

Here an email I wrote about that:

> Apologies to everyone for the mess around displayTimeUnit. That was my mistake implementing something in a hurry without properly reading the spec.
>
> To summarize my understanding of the current state:
> - chrome://tracing (aka catapult) expects timestamps and durations in .json trace files to always be recorded in us
>   - if displayTimeUnit is set then catapult:
>     - Uses higher precision in [some situations](https://source.corp.google.com/github/catapult-project/catapult/tracing/tracing/model/timed_event.html;l=58?q=TimeDisplayModes%20f:catapult)
>     - Shows timestamps & durations in the [supplied unit](https://source.corp.google.com/github/catapult-project/catapult/tracing/tracing/base/unit.html;l=411?q=preferredTimeDisplayMode%20f:catapult%20p:github)   
> - [ui.perfetto.dev](http://ui.perfetto.dev/) (and trace_processor_shell) by default assumes timestamps and durations in .json trace files are recorded in us
>   - if displayTimeUnit is set then [ui.perfetto.dev](http://ui.perfetto.dev/):
>     - interprets timestamps and durations as being in the [given](https://source.corp.google.com/android/external/perfetto/src/trace_processor/importers/json/json_trace_tokenizer.cc;l=435;bpv=1;bpt=1) [unit](https://source.corp.google.com/android/external/perfetto/src/trace_processor/importers/json/json_utils.cc;l=72;bpv=1;bpt=1;rcl=HEAD)

There is also some additional context on issue https://github.com/google/perfetto/issues/141

In short you should change the output of the file to be:
```
$ cat a.json
{
  "displayTimeUnit": "ns",
  "traceEvents": [
    {
      "name": "Frame",
      "ph": "X",
      "ts": 1.236,
      "pid": 188088,
      "tid": 1,
      "cat": "Rendering",
      "dur": 13837.451
    }
  ]
}
```
And it will look like this:
![image](https://user-images.githubusercontent.com/351085/163201537-d4596419-42ea-4196-8588-ed685fe43d01.png)

### Regarding start time:

The start time is shown approximately relative to the first event in trace (so the start time of the first event should always be 0ns). If you consider this file:

```
$cat ~/a.json
{
  "displayTimeUnit": "ns",
  "traceEvents": [
    {
      "name": "A",
      "ph": "X",
      "ts": 1.0,
      "pid": 188088,
      "tid": 1,
      "cat": "Rendering",
      "dur": 1000.123
    },

    {
      "name": "B",
      "ph": "X",
      "ts": 2.345,
      "pid": 188088,
      "tid": 2,
      "cat": "Rendering",
      "dur": 2000.456
    },

    {
      "name": "C",
      "ph": "X",
      "ts": 3.678,
      "pid": 188088,
      "tid": 3,
      "cat": "Rendering",
      "dur": 3000.789
    }

  ]
}
```

It looks like this:
![image](https://user-images.githubusercontent.com/351085/163203384-b18b0f73-01f5-49ec-9dca-18d267d89e74.png)

So there are two things here:
- There's an open feature request to also show the absolute time of the event.
- For some reason we have a 100ns offset. This is a bug. I'll look into it at some point but no promises when hopefully this is not too much of a critical issue for folks.

You can tell the data was parsed correctly by querying the tables:
![image](https://user-images.githubusercontent.com/351085/163203940-2154cfae-7b0c-463a-b59c-390b426411bb.png)

Hope that helps! Let me know if you have further questions.

**Comment by BKcore** [comment]
Thank you for the detailed reply. We can update our exporter to write microsecond timestamps. One thing I'd like to clarify if possible, you mention:

> if displayTimeUnit is set then [ui.perfetto.dev](http://ui.perfetto.dev/):
> interprets timestamps and durations as being in the given unit

Shouldn't this mean that by providing `"displayTimeUnit": "ns"` in the json, the perfetto viewer should still properly interpret durations and timestamps as nanoseconds? Or is this no longer the case and we have to write everything as microseconds regardless of the value of `displayTimeUnit`?

```
{
  "displayTimeUnit": "ns",
  "traceEvents": [
    {
      "name": "Frame",
      "ph": "X",
      "ts": 1236,
      "pid": 188088,
      "tid": 1,
      "cat": "Rendering",
      "dur": 13837451
    }
  ]
}
```

**Comment by chromy** [comment]
Yes it's the latter now (you have to write everything as microseconds regardless of the value of `displayTimeUnit`). 

Previously when I wrote that email we did the former which caused a lot of confusion (since then Perfetto does one thing and chrome://tracing does another). We 'fixed' it making our parser compliant with the spec and chrome://tracing ...but that had the unfortunate side effect of breaking folks like yourself who had come to rely on the new behaviour.
