### ISSUE TITLE
Chromium v8 JavaScript (JS) stacks in Perfetto?

### ISSUE THREAD

**Issue by ivberg** [google/perfetto#275]
It seems that the tracing probes and infrastructure are highly shared between F12 perf dev tools & Perfetto.

It seems F12 Dev Tools [enables some categories](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/devtools/front_end/timeline/TimelineController.js;drc=977fa8c33a878dd5e9f33ef5aa036aff86932e24;l=46) that Perfetto UI Chrome tracing supports. Things like these categories

- v8.runtime_stats_sampling
- v8.cpu_profiler

Again these can be collected by Perfetto. Additionally, a F12 profile with JS stacks can be saved and loaded by Perfetto.

However, it doesn't seem like Perfetto has support for these. There is no UI to show them and the SQL query interface does now show /expose data under [cpu_profile_stack_sample](https://perfetto.dev/docs/analysis/sql-tables#cpu_profile_stack_sample) no matter if the trace was taken in Perfetto or F12 Profile JSON

**Comment by primiano** [comment]
> However, it doesn't seem like Perfetto has support for these. There is no UI to show them and the SQL query interface does now show /expose data under [cpu_profile_stack_sample](https://perfetto.dev/docs/analysis/sql-tables#cpu_profile_stack_sample) no matter if the trace was taken in Perfetto or F12 Profile JSON

That's correct, perfetto UI and trace processor never had any support for JS callstack samples. The data is really just plumbed through (only some paths even, IIRC, only the JSON exported) and then the chrome devtools backend ingests it.

Historical reasons, if you ask. The v8 profilers were written by devtools and tracing was not fully there IIRC. Then tracing came along but nobody ever merged the two paths. There is no big plan to do so, because v8 profilers are typically aimed at web developers (who use devtools) and trace events are aimed at browser engineers.

Don't get me wrong, it would be nice if they were consistently supported in all tools. But this is by no means a priority for anybody, and as such will probably not bubble up in the next N years.

**Comment by ivberg** [comment]
Thx @primiano . It's always refreshing & nice to hear the context / history here and the reality with respect to priorities and feature support. I appreciate it! 

Since the title of this issue is "Chromium v8 JavaScript (JS) stacks in Perfetto?" I think that's 1 interesting future scenario. However, mixed with this is what you also responded to.
>  The data is really just plumbed through (only some paths even, IIRC, only the JSON exported) and then the chrome devtools backend ingests it.

From what I can tell, this scenario doesn't fully work. I am opening a 2nd issue on that #277  (Perfetto Chromium Trace Capture should support capturing / exporting to DevTools (bug?)) that more clearly outlines the issue and the scenario - which I think is more compelling priority wise than this issue IMO given everything you mentioned.

**Comment by camillobruni** [comment]
Abstractly speaking how does the sampling information get to?

I'd be willing to do build the sampling profiler UI as a side-project depending on how much complexity lies within accessing/providing the sampling information in perfetto.

**Comment by ivberg** [comment]
Is the [cpu_profile_stack_sample](https://perfetto.dev/docs/analysis/sql-tables#cpu_profile_stack_sample) a reasonable place for V8 JS stack samples to end up?

**Comment by camillobruni** [comment]
This looks like it would have all the necessary information to work with JS as well (unsurprisingly :P).

**Comment by LalitMaganti** [comment]
> Is the [cpu_profile_stack_sample](https://perfetto.dev/docs/analysis/sql-tables#cpu_profile_stack_sample) a reasonable place for V8 JS stack samples to end up?

Yes it should be. Pretty sure when we were defining the table, we had some consultation with the Chrome folks to ensure it would work for their usecase.

**Comment by LalitMaganti** [comment]
Primiano's comment from https://github.com/google/perfetto/issues/275#issuecomment-1097863044 is still the latest state of affairs: this is not considered a priority by us or any team we are aware of in Google so there is no timeline on when it might be addressed.

If there's interest from a team at Microsoft who wants to address this, we're very happy to help guide on the design and implementation.

**Comment by chromy** [comment]
Cc: @betasheet

**Comment by camillobruni** [comment]
Hi I'm from the V8 team and it is definitely been a prio for us (see internal doc https://docs.google.com/document/d/1UPZAWjLUNhEieAkzPU4Gp5xARuXGtu3IbxQqjAglAIk/edit?usp=sharing)

**Comment by camillobruni** [comment]
And the main issue is the same for us, switching between DevTools and perfetto is not particularly efficient. And DevTools has mostly opted for stripping low-level debugging features in favour of a simpler and more accessible UI.

**Comment by nornagon** [comment]
This is something that's keeping me on chrome://tracing and preventing me from switching to use Perfetto. Being able to correlate V8 samples with other things happening in a trace is pretty useful!

**Comment by LalitMaganti** [comment]
As part of some of the work I'm doing, I want to work on this bug. I've tried to capture traces with devtools and I don't see the stack frames which are indicated by the Trace event format [spec](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview).

Can someone provide me a trace with the samples included or alternatively tell me how to collect a trace with stack samples?

**Comment by LalitMaganti** [comment]
Ah of course, it uses a completely undocumented custom format (https://source.corp.google.com/piper///depot/google3/third_party/catapult/tracing/tracing/extras/importer/trace_event_importer.html;l=782?q=timedeltas%20f:tracing) which is undocumented 🙃 

(I managed to capture a trace with it, I just didn't realise because of the different format what I was seeing).

**Comment by LalitMaganti** [comment]
https://r.android.com/3235809 and https://r.android.com/3235810 together fix this issue.

**Comment by ivberg** [comment]
Thx for adding this support!  So I just tried this out and maybe I am missing something or using the wrong table.

1. Captured a Chromium dev tools trace and exported it as .json. Can see stacks in the Chrome dev tools
2. Download v48 (on Windows)
>trace_processor_shell.exe --version
Perfetto v48.0-bbbccf61e (bbbccf61e64a80276d635e12715263f09fea1705)
Trace Processor RPC API version: 13
3. Open trace 
>trace_processor_shell.exe "C:\Users\ivberg\Downloads\Chromium_Trace-20241014T163417.json"
4. Try to query for CPU sample but get nothing
[862.555] processor_shell.cc:1699 Trace loaded: 54.82 MB in 5.44s (10.1 MB/s)
Error stats for this trace:
                                    name                                      idx                                   source                                    value
---------------------------------------- ---------------------------------------- ---------------------------------------- ----------------------------------------
flow_no_enclosing_slice                  [NULL]                                   trace                                                                          42
> select * from cpu_profile_stack_sample;

Query executed in 0.432 ms

**Comment by LalitMaganti** [comment]
To be clear, support was only added for native proto traces, not traces collected with DevTools (i.e. not in the JSON format).

**Comment by ivberg** [comment]
Ok - that's nice but then this issue is not resolved and should be left open then?

**Comment by LalitMaganti** [comment]
By my understanding, the original primary ask was for traces to be collected by Perfetto to show V8 profiles (which is now supported) with a secondary (alternative) ask for DevTools exported traces to also be supported.

The primary ask has been done which is what I understood was the priority. Happy to reopen if you need the latter too.

**Comment by ivberg** [comment]
Thanks, yea I can see that I worded it like you interpreted it with 2 asks. Maybe I will just open another with the 2nd ask and we leave open, or whatever so folks know that scenario won't work (for now). 

I myself was confused in thinking the Chrome .json format would work now, but thanks for clarifying!

**Comment by LalitMaganti** [comment]
I'll just fix it now. It's not a lot of work.

**Comment by LalitMaganti** [comment]
https://r.android.com/3307377 adds support for importing V8 stack samples from the Chrome JSON format (i.e. the JSON devtools emits).

**Comment by ivberg** [comment]
You the man @LalitMaganti !

**Comment by ivberg** [comment]
> support was only added for native proto traces

Would you guys mind rev'ing to v48 https://www.ui.perfetto.dev/ ?  Even canary is 47. It would be great to test recording in the UI with native proto traces and test this out!

**Comment by LalitMaganti** [comment]
We can update canary for sure. Stable, things are under a lot of flux right now, I'd not feel comfortable uprevving until we have a bit more stability.

**Comment by LalitMaganti** [comment]
https://r.android.com/3314832 has landed which makes the above change available on canary.

**Comment by hardfist** [comment]
> [r.android.com/3314832](https://r.android.com/3314832) has landed which makes the above change available on canary.[r.android.com/3314832](https://r.android.com/3314832) 已经上线，这使得上述更改在 canary 上可用。

sorry, but I can't find any docs about what's the right format for generating v8 cpu profiler in chrome trace event which can be shown in perfetto UI, any guidance?

**Comment by LalitMaganti** [comment]
If you're looking to write events manually there is no documented format for these events and it's not something we which to support as such either.

**Comment by hardfist** [comment]
thanks for response, it seems I need to convert cpu-profiler to trace or convert cpu-profiler to supported`disabled-by-default-v8.cpu_profiler` format

**Comment by LalitMaganti** [comment]
Chrome CPU profiling events should already be supported. If something is not working I'd suggest trying to fix that instead of writing a hacky converter to a legacy and unmaintained format.

**Comment by hardfist** [comment]
Can I embed a Node.js cpu profiler(generated by node --cpu-prof) into trace.json and show it in perfetto?

**Comment by LalitMaganti** [comment]
I have no idea. That's something you need to figure out. I've not heard about anyone trying to do something like that.

**Comment by hardfist** [comment]
> Chrome CPU profiling events should already be supported
Is it only supported in perfetto format or also supported in legacy json format(if so can you help point the format)?

**Comment by LalitMaganti** [comment]
The Perfetto protobuf format: https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/protos/perfetto/trace/profiling/profile_packet.proto;drc=9377e0c0a10375a84c5bca8c52050e83dbfca691;l=235

**Comment by hardfist** [comment]
@LalitMaganti sorry to bother again, I'm trying merge trace and cpu profiler

[trace.json](https://github.com/user-attachments/files/19736248/trace.json)

which is working on firefox profiler https://share.firefox.dev/4lutgg9

![Image](https://github.com/user-attachments/assets/6acffd9b-2cd8-41ae-850a-767e1ab9c54d)

and seems semi-working on perfetto and the only problem is that perfetto doesn't show cpu profile as flamegraph as firefox did, I'm not sure whether I'm making wrong format or perfetto doesn't support flamegraph based on cpu profile

![Image](https://github.com/user-attachments/assets/0f5d7101-70bd-4f89-b93a-e464ce6286fb)

**Comment by hardfist** [comment]
@LalitMaganti that's weird, it seems Node.js's cpu profile is following standard CDP protocol https://chromedevtools.github.io/devtools-protocol/tot/Profiler/#type-ProfileNode while chrome's code profile doesn't follow.

**Comment by LalitMaganti** [comment]
Thanks for pointing me to that doc, I feel a lot better of supporting actual documented formats.

https://github.com/google/perfetto/pull/1267 adds support for Devtools/NodeJS traces.

**Comment by hardfist** [comment]
@LalitMaganti Thanks for considering support Node.js Profile that would save lots of my work，how can test it when the related PR is merged?

**Comment by LalitMaganti** [comment]
You can use the autopush UI. Click flags on the left sidebar change the release channel to autopush.

**Comment by hardfist** [comment]
@LalitMaganti it works perfectly for me now, thanks for you great help, Perfetto is such a great tool!
