### ISSUE TITLE
trace_processor_shell  binary is too big after built with gn 

### ISSUE THREAD

**Issue by yufailuvatar** [google/perfetto#276]
hi guys, 
    i am a blooding new user of the ownsome tool.  I have met a issue when built trace_processor_shell with gn. when the build args are linux/x64/is_debug=false, we still get much bigger size bin file , which is larger than 100MB. But the one downloaded by **curl -LO https://get.perfetto.dev/trace_processor** is much smaller , which is less than 8MB.  If i want to get customized  trace_processor_shell with this pretty file size, how could i do to build it?

**Comment by yufailuvatar** [comment]
and i have to post  another issue here.  we used the contents in ./out/dist folder to deploy a https server providing perfetto ui services. However, Chrome brower can not get service_worker.js due to security issues , but FireFox works well. Except this issue, all other features worked well in Chrome. How can we fixed this issue ?

**Comment by primiano** [comment]
About tpshell: look in the out/xxx/stripped folder. There are 2 outputs for each binary:
- out/xxx/trace_processor_shell -> unstripped (i.e. with debug symbols)
- out/xxx/stripped/trace_processor_shell -> stripped

> we used the contents in ./out/dist folder to deploy a https server providing perfetto ui services. However, Chrome brower can not get service_worker.js due to security issues , but FireFox works well. Except this issue, all other features worked well in Chrome. How can we fixed this issue ?

Where are you hosting this? One thing you need to know is that chrome (and IIRC Safari) are quite picky on security origins.
Service worker and many other features (e.g. webusb) require a secure origin. From the chrome viewpoint:

- http://127.0.0.1:*  is considered secure
- file://XXX is NOT considered secure
- https://example.com is considered secure
- http://example.com is NOT considered secure
- http://your-local-network-host is NOT considered secure

There is nothing else we can do about that. Also I guarantee that you will find issue elsewhere, it's not just the SW registration.
