### ISSUE TITLE
[Perfetto UI] On Android 12+, Perfetto "Record New Trace" should support capturing CPU Sampling

### ISSUE THREAD

**Issue by ivberg** [google/perfetto#280]
Under CPU UI you should be able to configure PerfEvent callstack sampling, at least when an Android 12+ device is present.

The user should be able to select if they want kernel sampling (or not), all processes or a specific process, and the sampling rate - e.g every 1ms or say every 100ms

See [PerfEventConfig](https://perfetto.dev/docs/reference/trace-config-proto#PerfEventConfig) & [PerfEventConfig.CallstackSampling](https://perfetto.dev/docs/reference/trace-config-proto#PerfEventConfig.CallstackSampling) for full syntax. [PerfEvents.Timebase](https://perfetto.dev/docs/reference/trace-config-proto#PerfEvents.Timebase) controls the frequency (in Hz)

Example config that might be generated.
```
data_sources: {
    config {
        name: "linux.perf"
        perf_event_config {
        timebase {
            frequency: 1000
        }
        callstack_sampling {
            kernel_frames: true
        }
        }
    }
}
```

**Comment by LalitMaganti** [comment]
@rsavitski FYI

**Comment by LalitMaganti** [comment]
We now have support for this.
