### ISSUE TITLE
[UI][Feature Request] Collapsible pinned tracks

### ISSUE THREAD

**Issue by gramound** [google/perfetto#281]
I often run out of vertical space after pining a few particularly high tracks (rows) to the top. I wish I could temporarily squish rows (without unpinning) to peek at some other rows below. I like the way collapsed processes are presented. I wish pinned rows could do the same.
Example:
![running-out-of-vertical-space](https://user-images.githubusercontent.com/16066120/165380814-6decf59f-3426-441c-ae9c-bdf8ffeb1177.png)
.

**Comment by LalitMaganti** [comment]
@octaviantu @chromy FYI

**Comment by horusli** [comment]
do we have any solid plan for this feature ?
I encounter this problem recently also.
and it would be more user friendly if we can add vertical scrollbar in the pin tracker area as well.

**Comment by LalitMaganti** [comment]
No further updates on this.

**Comment by Sincky** [comment]
i have same problem, this feature is very useful, please

**Comment by LalitMaganti** [comment]
Folding this into https://github.com/google/perfetto/issues/429
