### ISSUE TITLE
UI Inserts 2ns empty space between slices.

### ISSUE THREAD

**Issue by tsarvey** [google/perfetto#282]
I'm trying to display back-to-back slices in a single track.  The UI often (but not always) ends the first slice 1ns early and begins the next one 1ns late.  It seems to be related to the ordering of timestamps in the trace file.  I am able to create a single track with slices all aligned by making sure timestamps are monotonically increasing.  Once I have multiple tracks and interleaved TYPE_SLICE_STARTs and TYPE_SLICE_ENDs, I cannot reliably remove the gaps.  This is what it looks like:

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/600740/165636673-4563f903-a7b2-4c96-91e5-420c0a0bb119.png">

It can also be seen when zooming into sections of the Android trace example in the UI:
<img width="853" alt="image" src="https://user-images.githubusercontent.com/600740/165636810-2152cf57-8df0-4846-8c82-fb3095792aad.png">

**Comment by LalitMaganti** [comment]
@chromy @octaviantu FYI
