### ISSUE TITLE
Unexpected slice closing behavior with new 'T' and 'U' phase atrace events

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#283]
I'm seeing some unexpected behavior with these new 'T' and 'U' phase slices that were added recently. They appear to allow nesting, but when you try to close the root slice without closing the nested slice, then the wrong slices gets closed.

Take the following example the following hand-crafted atrace snippet:

```
# tracer: nop
MyProcess-1234  ( 1234) [000] .... 1.000000: tracing_mark_write: T|1234|TRACK_NAME|FIRST_CLOSED_SLICE|12345
MyProcess-1234  ( 1234) [000] .... 2.000000: tracing_mark_write: T|1234|TRACK_NAME|UNCLOSED_SLICE|12345
MyProcess-1234  ( 1234) [000] .... 3.000000: tracing_mark_write: T|1234|TRACK_NAME|SECOND_CLOSED_SLICE|54321
MyProcess-1234  ( 1234) [000] .... 4.000000: tracing_mark_write: U|1234|TRACK_NAME|FIRST_CLOSED_SLICE|12345
MyProcess-1234  ( 1234) [000] .... 9.000000: tracing_mark_write: U|1234|TRACK_NAME|SECOND_CLOSED_SLICE|54321
```

The expectation when loading the above simple trace into Perfetto UI is that on the 4th line we close the slice named FIRST_CLOSED_SLICE. However instead UNCLOSED_SLICE gets closed instead whereas FIRST_CLOSED_SLICE still remains unclosed:

This is reproducible from https://ui.perfetto.dev when using either "Canary" or "Autopush" channels.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/77857237/165651962-1718395e-8718-4b5a-85f0-5f9916573121.png">

<img width="260" alt="image" src="https://user-images.githubusercontent.com/77857237/165652525-f4ac6c8e-7ba2-4be8-9a9c-efd31c7492b0.png">

My expectations for the behavior of how these slices should be closed is based on 2 things:
- U phase events take the slice name as an argument. If not used to determine the matching slice to close, then why is it there?
- With the catapult trace viewer if you attempt to close the top slice in a stack of nested slices, that slice and all nested slices get auto-closed and marked as "Slice has no matching END. End time has been adjusted." This can be reproduced by loading [async_nestable.json](https://github.com/catapult-project/catapult/blob/main/tracing/test_data/nestable_async.json) into chrome://tracing

For reference, these new T & U phases were introduced in https://android-review.googlesource.com/c/platform/external/perfetto/+/2069118

**Comment by LalitMaganti** [comment]
This is being addressed in the framework in patches https://android-review.googlesource.com/c/platform/frameworks/base/+/2078718 and https://android-review.googlesource.com/c/platform/system/core/+/2078467

Concretely, you will no longer need to provide the slice name in U events: instead the cookie will need to be unique at the track level (i.e. you cannot have two slices with the same cookie but different names happening at the same time).

Note that T and U events will *not* be nestable unlike JSON async events.

**Comment by cphlipot1** [comment]
@LalitMaganti Thanks for the clarification and the fix! sounds like the existing behavior was unintentional.

> Concretely, you will no longer need to provide the slice name in U events: instead the cookie will need to be unique at the track level (i.e. you cannot have two slices with the same cookie but different names happening at the same time).

Based on this comment I had one followup question. Are these Atrace T events deliberately different than the T events in Chrome Trace JSON? Those seem to have slightly different behavior and seems to allow multiple T events to [have the same cookie/id](https://github.com/catapult-project/catapult/blob/main/tracing/test_data/async_begin_end.json#L19)? I'm only asking because most other Atrace phases appear to have a 1:1 mapping with their Trace Json counterpart.

**Comment by LalitMaganti** [comment]
Yes they are different.

I didn't know about the existence of these T events in JSON; I'll see if we can just change the phase to avoid clashing.

**Comment by cphlipot1** [comment]
> I didn't know about the existence of these T events in JSON

For future reference this [switch statment](https://github.com/catapult-project/catapult/blob/main/tracing/tracing/extras/importer/trace_event_importer.html#L1232) contains a list of all the JSON trace event types recognized by the Catapult trace viewer.
This [Google doc](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.puwqg050lyuy) contains documentation on the behavior of many, but not all, of those events.




>  I'll see if we can just change the phase to avoid clashing.

If the goal is to avoid clashing you might want to take a look at the new N event as well, as I think those are meant to be object events in the JSON format instead of instants.

**Comment by LalitMaganti** [comment]
Yeah I knew about the JSON spec doc but I didn't think to check as I thought I remembered the formats.

The N events, I don't think is worth not clashing. We'll never support anything similar to object events in systrace: we already have important trace points using those events we don't want to break parsing for. I only agreed to change T and U because a) async events were introduced very recently and so don't have a lot of tracepoints b) it's easy to confuse the JSON/systrace because they are both about async events: in the case of N, it's clear they are very different.

**Comment by cphlipot1** [comment]
Make sense. Thanks for the change and the thoughtful response!
