### ISSUE TITLE
[UI] Extra Tracks

### ISSUE THREAD

**Issue by tsarveyLM** [google/perfetto#286]
If I run this simple tracing example:
```cpp
void track0() {
    TRACE_EVENT("Stream", "Slice0::0");
    std::cout << "timing stuff.." << std::endl;
}
```

I get this rendering in the UI:
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/87037835/166741702-cb637ef1-29b7-49e1-9f27-4c3689a5aae0.png">

The main track is duplicated and there is an extra empty track for the process.  If I define a custom track, the duplicate track goes away, but there is still an empty track for the process.
```cpp
void track0() {
    TRACE_EVENT("Stream", "Slice0::0");
    std::cout << "timing stuff.." << std::endl;
}
```

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/87037835/166742428-66721938-e063-4298-b7d8-e2d078ab95e4.png">

I've tagged this as a UI issue because I've tried using custom data sources to mimic the output from above with custom data sources and things became more wonky.  I was able to make a custom embedding of tracks within processes, but all slices then appeared as the same color.  For now I just listed minimal examples, which I believe are supported.

**Comment by LalitMaganti** [comment]
Can you please link a trace which is demonstrating this behavior? This is likely a trace processor or SDK bug: it's unlikely the UI is creating tracks which are not in the data model.

**Comment by tsarveyLM** [comment]
Thanks for the quick response!

Github only supports certain file extensions, so I added `.txt` to the end of the binary file name before uploading here.
[simple_trace0.perfetto-trace.txt](https://github.com/google/perfetto/files/8626962/simple_trace0.perfetto-trace.txt)
I am opening this file at https://ui.perfetto.dev/.

I also converted the file to something human readable with
```./traceconv text simple_trace0.perfetto-trace simple_trace0.txt```
[simple_trace0.txt](https://github.com/google/perfetto/files/8626966/simple_trace0.txt)

From that human readable version, it looks to me like there is one track defined for the thread and one for the process (to make the drop down category in the GUI).  As a side note, is this the best way to debug?  I am creating a binary from C++ code, converting to a human readable format, and then going back to the C++ code to make changes.  Is there a way to edit a human readable file and then display it?

Anyway, I think this can be viewed as two issues, which may or may not be related.
1. The GUI displays duplicate tracks from the above trace.  I was a bit loose with my terminology, but it seems to me this is an issue with something post-SDK, like the trace processor.
2. An empty process track is displayed.  There is a track descriptor which defines the process in the trace, so maybe this is intended trace processor/GUI behavior for the given trace.  If that is the case, I suppose this would be an SDK issue.  What should the trace packets look like to group multiple tracks under a process without displaying an empty track?

**Comment by tsarveyLM** [comment]
There are two threads in the thread table.  One of them is swapper, which seems to have been added automatically.  Is this an ftrace thing?
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/87037835/166829026-9e7b92fd-6dc2-4752-8755-62a4ed94dad3.png">

**Comment by tsarveyLM** [comment]
Another issue which may actually be a UI issue can be seen with the trace I attached above.

When collapsed, the process shows what seems to be a sum of the active threads at that time.  It seems to be summing two things which are offset by 10.2ns and the whole thing does not align with the thread(s) inside.  I'll try to align the screenshots here so you can see what I mean:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/87037835/166836037-392c95a9-79ea-4fd5-8f1b-1179168d2660.png"><img width="1185" alt="image" src="https://user-images.githubusercontent.com/87037835/166836100-b6c2c920-7625-4600-8476-6b0598c16a33.png">


I created some traces where the two threads also appear misaligned (even through they show the exact same slices).  I can post those, but I figured I should stick with the one trace in this issue.

**Comment by LalitMaganti** [comment]
Sorry I would love to look at this but swamped with other stuff ATM.

If you just want to convert a textproto trace to protobuf to load in UI, have a look at the script tools/serialize_test_data.py. You'll need a full checkout and build of Perfetto to use it though.

If you have a minimal repro, then I will come back and look a bit further.

**Comment by LalitMaganti** [comment]
Ack thanks for the clarification. I'll try and look at this when I have some spare time.

**Comment by tsarveyLM** [comment]
Thanks Lalit!  One more piece of very relevant info:  I just noticed the duplicate Thread view was only happening in one browser and found that it is linked to the "Tracks V2" option in the GUI (which was set in one browser).  I disabled that and it only shows one thread now.  There is still a default empty process  and the process graph is misaligned, but I think those issues are less significant.

**Comment by ihavnoid** [comment]
Maybe this might deserve a separate ticket, but the 'default empty process' is also affecting me, too.  One possible usecase is for tracing applications with only counters (e.g., monitoring internal stats of a given application, while the traces are not interesting).  The empty tracks are not going to be a showstopper, but it gets annoying once we have a large number of processes.  I can create a ticket and a minimal repro if it seems worthy.
