### ISSUE TITLE
Android Log font color customize

### ISSUE THREAD

**Issue by wjj1928** [google/perfetto#288]
The Android log view text color is gray, it's very hard to read, I would like to change the color to black for easy to read. Please help instruct about how to customize it or add a new feature for user to adjust such UI elements.

**Comment by LalitMaganti** [comment]
The UI will never be as customisable as allow changing colors arbitrarily from the user end.

However, in this case, it makes sense to change this more generally. @octaviantu @chromy FYI

**Comment by primiano** [comment]
To be honest, the real issue is that there is a bug there.
The gray colour was supposed to be an indication of "log lines are out of sync vs the timeline, while I am refetching logs I will display the old lines rather than nothing".

However at some point this logic broke. You can see that if you scroll the log lines a little bit up and down eventually they become black.

Something in the logic that timesyncs the timeline an the log panel broke at some point. that's the thing to fix, not the font color.

**Comment by wjj1928** [comment]
try to scroll up then scroll down, no luck to saw black text. where is the code I can modify to workaround it? I downloaded the source code but want to know where to modify it then try.

**Comment by primiano** [comment]
Thanks a lot for taking a stab at it.

The code lives in `ui/src/frontend/logs_panel.ts` (https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/frontend/logs_panel.ts)

Look at the logic around `isStale`. The `.stale` css class makes it gray.

**Comment by wjj1928** [comment]
Thanks for your help!

I got nice black fonts with below patch:

diff --git a/ui/src/assets/details.scss b/ui/src/assets/details.scss
index a6ff835..61a5a61 100644
--- a/ui/src/assets/details.scss
+++ b/ui/src/assets/details.scss
@@ -430,7 +430,7 @@ table.half-width {
         &.W { color: hsl(45, 60%, 45%); }
         &.E { color: hsl(4, 90%, 58%); }
         &.F { color: hsl(291, 64%, 42%); }
-        &.stale { color: #aaa; }
+        &.stale { color: black; }
         &:nth-child(even) {
             background-color: hsl(214, 22%, 95%);
         }

**Comment by wjj1928** [comment]
@primiano Doubled confirmed that patch works. I change the color to red as well and text will changed to red. Maybe it's a bug but it really changed log fonts color right now!

Now the trouble is: when run ./trace_processor -D trace.bin, I got the link to official site, how can I replace this one with my local URL (http://127.0.0.1:10000/)?

**Comment by chromy** [comment]
https://android-review.googlesource.com/c/platform/external/perfetto/+/2093723 should improve this.
Please attach a problem trace so I can confirm.

Regarding `./trace_processor -D trace.bin` instead of clicking the link you can go to `http://localhost:10000/` and it will just work. If you want to change the text it's defined here: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/rpc/httpd.cc;l=101?q=%22erver%20can%20be%20used%20by%20reloading%22

**Comment by primiano** [comment]
> Now the trouble is: when run ./trace_processor -D trace.bin, I got the link to official site, how can I replace this one with my local URL (http://127.0.0.1:10000/)?

Sorry I don't see how that is a trouble. That message is supposed to work with the use case 99% people want, which is: open a link and get a UI that works.

If you want to do custom things, change that line of code in trace processor and give your users a different binary.

I don't see a way to solve this, which wouldn't involve passing the URL into trace processor in the first place via a cmdline argument. But then at that point your users will know already what's the URL, they would just get a printf of the same string they passed.

**Comment by wjj1928** [comment]
Thanks, yes, now I can open it in chrome, but got a warning: our Trace Processor binary is outdated

The Trace Processor instance on http://127.0.0.1:9001/ is too old.

This UI requires TraceProcessor features that are not present in the
Trace Processor native accelerator you are currently running.
If you continue, this is almost surely going to cause UI failures.

Please update your local Trace Processor binary:

curl -LO https://get.perfetto.dev/trace_processor
chmod +x ./trace_processor
./trace_processor --httpd

UI version: v25.0-74ed9a4ec
TraceProcessor RPC API required: 5 or higher

TraceProcessor version: Perfetto v25.0-7e8d6801d (7e8d6801dbf73936a916dbcd8ed06a758c8d989e)
RPC API: 3
Use builtin Wasm

I copied the trace_processor from my source folder but still the same! I only build the UI. should I built trace_processor tool as well? How to build it?

**Comment by chromy** [comment]
Yep you need a newer `trace_processor`. To build `trace_processor` follow https://perfetto.dev/docs/contributing/build-instructions#standalone-builds then do:

```
$ tools/ninja -C out/<your out directory name> trace_processor_shell
$ out/<your out directory name>/trace_processor_shell --httpd
```

**Comment by chromy** [comment]
this should be fixed on canary
