### ISSUE TITLE
docs about perfetto/ui

### ISSUE THREAD

**Issue by lihuakkk** [google/perfetto#29]
Hi, perfetto is very cool!!!
Recently, i am working base on perfetto/ui, but i can not find any documents about it .

I have some confusions:

1、When i load a new trace file , how trace data parsed and flow between entire app. Too much controllers and message channel.

2、Every time when  i modify files and reload the browser , that cost too much time waiting to show.

**Comment by primiano** [comment]
Hi,
sorry we don't have any good docs about the UI architecture. We are also in the process of changing it. I know it's complicated.

>  1、When i load a new trace file , how trace data parsed and flow between entire app. Too much controllers and message channel.

The short version is that all the data is parsed by the C++ code under src/trace_processor, which is wrapped in a WASM module.

> 2、Every time when i modify files and reload the browser , that cost too much time waiting to show.

Yes, UI builds, even incremental change, are O(several seconds) slow. Patches to make it faster are welcome.

**Comment by primiano** [comment]
Closing as there seem to be no bug / nothing actionable.
If you have specific questions ask them on the discord channel (see the contributing and community guide on https://perfetto.dev)
