### ISSUE TITLE
how can i open large trace file with mac m1?

### ISSUE THREAD

**Issue by Moreh-LeeJunhyeok** [google/perfetto#293]
hi.
I am trying to open big trace file(about 2~5 gig) in mac m1 
However instruction does not work with m1, so I build perfetto on my mac.
By doing so, I expected to see standalone executer(trace_processor file) in out/mac_debug.  
But I cant find one. 
What can be a problem? thanks in advance

**Comment by LalitMaganti** [comment]
I also am using an M1 device and I cannot repro this issue. I see `out/mac_debug/trace_processor_shell` in my out directory.

If you're just looking to open the trace, you don't need to build trace processor. We provide prebuilt binaries including for M1. You just need to follow the setup instructions at https://perfetto.dev/docs/quickstart/trace-analysis#setup

**Comment by Moreh-LeeJunhyeok** [comment]
well, thats odd. because in my mac it logs like this. So I thought it requires rebuild

`(base) ljh@192 ~ % ./trace_processor trace.perfetto-trace
This executable requires a cpu that supports SSE4.2 and AVX2.
Rebuild with enable_perfetto_x64_cpu_opt=false (ebx=10800, ecx=298220f).
`

**Comment by primiano** [comment]
You are probably using some older version. Where are you getting trace_processor from? can you paste the full command including the one you use to get trace_processor?

M1 has been fixed in v25.0 - 2022-04-01

**Comment by LalitMaganti** [comment]
Just run `curl -LO https://get.perfetto.dev/trace_processor` again to overwrite your current script. This will update the script with the latest binary SHAs and should give you the M1 version.

**Comment by Moreh-LeeJunhyeok** [comment]
still, I am getting the same error. here is my logs  
`(perfetto) ljh@ijunhyecBookPro perfetto_2 % ls
(perfetto) ljh@ijunhyecBookPro perfetto_2 % curl -LO https://get.perfetto.dev/trace_processor
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6940  100  6940    0     0   2763      0  0:00:02  0:00:02 --:--:--  2770
(perfetto) ljh@ijunhyecBookPro perfetto_2 % python -V
Python 3.9.0
(perfetto) ljh@ijunhyecBookPro perfetto_2 % chmod +x ./trace_processor
(perfetto) ljh@ijunhyecBookPro perfetto_2 % ./trace_processor trace.perfetto-trace --http
This executable requires a cpu that supports SSE4.2 and AVX2.
Rebuild with enable_perfetto_x64_cpu_opt=false (ebx=10800, ecx=298220f).
(perfetto) ljh@ijunhyecBookPro perfetto_2 % 
`
  
my mac version information  
macOS Monterey, ver 12.2, Apple M1,

**Comment by Moreh-LeeJunhyeok** [comment]
also, when using my build, it returns this error
`To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

Query: 
    select
      the_tracks.upid,
      the_tracks.utid,
      total_dur as hasSched,
      hasHeapProfiles,
      process.pid as pid,
      thread.tid as tid,
      process.name as processName,
      thread.name as threadName,
      process.arg_set_id as argSetId,
      (case process.name 
         when 'Browser' then 3
         when 'Gpu' then 2
         when 'Renderer' then 1
         else 0
      end) as chromeProcessRank
    from (
      select upid, 0 as utid from process_track
      union
      select upid, 0 as utid from process_counter_track
      union
      select upid, utid from thread_counter_track join thread using(utid)
      union
      select upid, utid from thread_track join thread using(utid)
      union
      select upid, utid from sched join thread using(utid) group by utid
      union
      select distinct(process.upid), 0 as utid from process
        join thread on process.upid = thread.upid
        join perf_sample on thread.utid = perf_sample.utid
      union
      select upid, utid from (
        select distinct(utid) from cpu_profile_stack_sample
      ) join thread using(utid)
      union
      select distinct(upid) as upid, 0 as utid from heap_profile_allocation
      union
      select distinct(upid) as upid, 0 as utid from heap_graph_object
    ) the_tracks
    left join (select upid, sum(dur) as total_dur
      from sched join thread using(utid)
      group by upid
    ) using(upid)
    left join (select upid, max(value) as total_cycles
      from android_thread_time_in_state_event
      group by upid
    ) using(upid)
    left join (
      select
        distinct(upid) as upid,
        true as hasHeapProfiles
      from heap_profile_allocation
      union
      select
        distinct(upid) as upid,
        true as hasHeapProfiles
      from heap_graph_object
    ) using (upid)
    left join thread using(utid)
    left join process using(upid)
    order by
      chromeProcessRank desc,
      hasHeapProfiles desc,
      total_dur desc,
      total_cycles desc,
      the_tracks.upid,
      the_tracks.utid;
  
Error: no such table: android_thread_time_in_state_event (errcode: 1)
Error: no such table: android_thread_time_in_state_event (errcode: 1)
    at QueryResultImpl.resolveOrReject (https://ui.perfetto.dev/v25.0-0a41dc68e/frontend_bundle.js:81889:28)
    at QueryResultImpl.appendResultBatch (https://ui.perfetto.dev/v25.0-0a41dc68e/frontend_bundle.js:81875:18)
    at WaitableQueryResultImpl.appendResultBatch (https://ui.perfetto.dev/v25.0-0a41dc68e/frontend_bundle.js:82225:26)
    at HttpRpcEngine.onRpcResponseMessage (https://ui.perfetto.dev/v25.0-0a41dc68e/frontend_bundle.js:82396:30)
    at HttpRpcEngine.onRpcResponseBytes (https://ui.perfetto.dev/v25.0-0a41dc68e/frontend_bundle.js:82326:18)
    at https://ui.perfetto.dev/v25.0-0a41dc68e/frontend_bundle.js:95608:19

v25.0-0a41dc68e 0a41dc68e03e358dba6beb400110d5329f21092e
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
`

**Comment by LalitMaganti** [comment]
If you run `python3 -c 'import platform; print(platform.machine())'` what do you get?

Also re. building TP yourself: yeah if you do that, you'll also need to use the latest version of the UI.

**Comment by Moreh-LeeJunhyeok** [comment]
@LalitMaganti x86_64, 
also re. is latest version of UI v25.0-0a41d?

**Comment by LalitMaganti** [comment]
Yeah so your Python installation is not correct: on M1 devices, you should install the M1 version of Python where you currently have the x86_64 version which is running using Rosetta. See the Python docs on how to do this.

When I say latest version, I mean building the UI from the repo directly (i.e. *not* using ui.perfetto.dev)

**Comment by primiano** [comment]
See also https://github.com/google/perfetto/issues/294
