### ISSUE TITLE
Extend valid objects for GpuRenderStageEvent::render_target_handle 

### ISSUE THREAD

**Issue by llandwerlin-intel** [google/perfetto#295]
With more recent versions of Vulkan, in particular with the VK_KHR_dynamic_rendering extension, VkFramebuffer objects are not required anymore.
The application directly render to a VkImageView.

Here are the rendering parameters recorded in the command buffer : https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkRenderingInfoKHR.html

It would great to extend the list of objects we can put into GpuRenderStageEvent::render_target_handle to VkImageView handles to cover this new use case.

**Comment by LalitMaganti** [comment]
I can safely say that we will not be implementing this ourselves.

However, if you want to send a patch for this, you're more than welcome!
