### ISSUE TITLE
"Report a bug" on ui.perfetto.dev goes to Google CorpSSO

### ISSUE THREAD

**Issue by pyricau** [google/perfetto#297]
Clicking on "Report a bug" links to https://goto.google.com/perfetto-ui-bug which redirects to Google's SSO first.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/557033/170323059-f74b46e0-3c82-40a4-aef4-c9b365af10a3.png">

<img width="516" alt="image" src="https://user-images.githubusercontent.com/557033/170323241-fd638586-f8a4-4c80-a483-7fe2f7e26e0c.png">

It wasn't until someone mentioned there's actually a github for perfetto that I found this issue tracker here :)

**Comment by LalitMaganti** [comment]
Agreed: we should change this link to point to GitHub for external users.

@chromy @octaviantu

**Comment by chromy** [comment]
Thanks for the report. I have sent https://android-review.googlesource.com/c/platform/external/perfetto/+/2108006/ to address this.
