### ISSUE TITLE
Android App Startups metric stopped working for trampolining activities.

### ISSUE THREAD

**Issue by pyricau** [google/perfetto#298]
Trampoline activities are launcher activities that redirect to another activity from their onCreate() method:

```
class TrampolineActivity : Activity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    finish()
    startActivity(Intent(this, MainActivity::class.java))
  }
}
```

As far as I could tell, as of a few days ago the `Android App Startups` Perfetto metric captured these activities as part of a startup just fine.

As of yesterday, the `Android App Startups` metric is missing when capturing a trace containing a launch with a trampoline activity. A quick look at the git history seem to indicate that there was a deploy yesterday, and that there's been a lot of rework of the `Android App Startups` metric to make it run faster, so I suspect support for this edge case was broken by recent changes.

Here are some example traces captured on a Pixel 6 with a demo app:

* This trace has a `com.squareup.tart.sample` launch with a trampoline activity. As you can see, there's  no `Android App Startups` metric, however the `system_server` process does show a `launching:` trace: https://drive.google.com/file/d/1CELBVcjs48SiL5WnqreYfoQQISaLWbB0/view

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/557033/170326654-107ffee7-f44e-475f-9995-520240f67722.png">

* This trace has a `com.squareup.tart.sample` launch with a classic activity. This time the `Android App Startups` metric shows up: https://drive.google.com/file/d/1j2EseAVAb3YwdxmD1eLz1rDcN573hlyg/view

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/557033/170326861-f85d3be6-205f-4e61-8204-8d6f75b7df52.png">

**Comment by LalitMaganti** [comment]
(@ilkos FYI)

So this is not at all related to the UI/trace processor side: there is actually a difference in the contents of the trace itself.

The "launching" slices in system_server is actually misleading. As described in [this](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/metrics/sql/android/startup/launches_minsdk29.sql;l=49) comment, it does not indicate by itself whether a launch was "successful" from the system perspective. Instead, we rely on an event called 'MetricsLogger:launchObserverNotifyActivityLaunchFinished'.

This event is present in the "ok" trace but is missing in the "not ok" trace. You can verify this by running the query:
```
SELECT ts FROM slice
WHERE name = 'MetricsLogger:launchObserverNotifyActivityLaunchFinished'
```
on each trace.

Realistically, this is a problem at the platform level about why this event is not firing: not sure we can do anything inside Perfetto without masking problems on the device.

**Comment by LalitMaganti** [comment]
Please reopen this bug if you think this is really still a problem on the Perfetto side.

**Comment by pyricau** [comment]
Thanks @LalitMaganti , and thanks for pointing me to how the end is determined.

I reopened the faulty trace that doesn't have `MetricsLogger:launchObserverNotifyActivityLaunchFinished` and found out that it has a `MetricsLogger:launchObserverNotifyActivityLaunchCancelled` which maps to when I called finish from the trampoline activity.

So.. I looked at the code again:

```
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    finish()
    startActivity(Intent(this, MainActivity::class.java))
  }
```

We call `finish()` before starting the next activity. I had always internalized that this didn't matter, that finishing + starting the next activity in "onCreate()" would behavior atomically... I tried again, inverting the start and finish:

```
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    startActivity(Intent(this, MainActivity::class.java))
    finish()
  }
```

This time I do get `MetricsLogger:launchObserverNotifyActivityLaunchFinished`

In a way, it makes sense, as (I think?) each of these call is a direct blocking IPC call. Still, that was interesting and surprising.

This might be considered a platform bug, idk.
