### ISSUE TITLE
How do we write out tid to threadName mapping for Perfetto

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#300]
In Catapult and Perfetto, I see only numbers 0, 1, 2, 3, ... instead of thread names from a json system trace file.  We wrote out traceEvents for Catapult, but now want to transition to using Perfetto.   Now that these can finally be read correctly as millseconds into Perfetto, how do I set a mapping in the json from tid (or pid) to a thread name?  Can I supply a table of tid to name?  I see nothing in the Catapult json format description about this either, and the Catapult github is now archived.

**Comment by chromy** [comment]
You can use the metadata (aka 'M') events [documented here](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#bookmark=id.iycbnb4z7i9g).
For example the following minimal example:

```json
{
  "traceEvents": [
    {
      "name": "process_name", "ph": "M", "pid": 22630, "tid": 22630,
      "args": {
        "name" : "My process name!"
      }
    },
    {
      "name": "thread_name", "ph": "M", "pid": 22630, "tid": 22630,
      "args": {
        "name" : "My thread name!"
      }
    },
    {"name": "My slice name!", "cat": "PERF", "ph": "B", "pid": 22630, "tid": 22630, "ts": 829},
    {"name": "My slice name!", "cat": "PERF", "ph": "E", "pid": 22630, "tid": 22630, "ts": 833}
  ],
  "otherData": {
    "version": "My Application v1.0"
  }
}
```

Looks like this:

<img width="1288" alt="Screen Shot 2022-05-26 at 10 56 17" src="https://user-images.githubusercontent.com/351085/170465051-17f7f330-d40c-4c33-96f6-06805a15e391.png">

[trace.json.txt](https://github.com/google/perfetto/files/8778134/trace.json.txt)


Let me know if you have any other questions!

**Comment by alecazam** [comment]
For some reason, I combed that doc and couldn't find that sample, but after you sent the link it "appeared" in that document.    That will be a big help to our perf analysis, so thanks!

**Comment by alecazam** [comment]
No questions right now, but some points. 

I've already posted about this on other Issues but hover names and timings are important.  These are in AGI, and prevent having to zoom in-out to see data or select tiny slivers.  AGI already has this.  Try Android Studio Profiler and see how hard it is to use with a hover tip and how much you have zoom in/out and lose context.

Tack pins and track reordering would be nice.  AGI has track pins, but not reordering.

Reasonable times that are just float like "1.0508 ms", instead of "1ms 50us 800 ns" which is way longer and harder to visually parse and/or copy-paste.   I think if these issues can be addressed, then Perfetto will be just about perfect.
