### ISSUE TITLE
Is there a translation plan for the document?

### ISSUE THREAD

**Issue by kirin521** [google/perfetto#302]
As mentioned,  want to build perfetto documents together.

**Comment by LalitMaganti** [comment]
No idea what this issue means sorry. Please reopen with much more detail if you have it.

**Comment by kirin521** [comment]
> No idea what this issue means sorry. Please reopen with much more detail if you have it.

Sorry for not being clear, I mean the perfetto only in English, are there any plans to translate it into other languages? like Chinese.
