### ISSUE TITLE
Star tracks quickly cause upper pane to run out of vertical real estate.

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#304]
I'd like to selectively star tracks, but the inability to scroll or shrink the view with the upper pane quickly results in very little real-estate to see and compare other tracks below, and also limits the ability to add more than the pane can display.  

Could both top and bottom view have scroll panes?  Also let me pick where the window split occurs?  Otherwise, I'm going to have to only use this profiler on a vertically oriented external monitor.   I'm on a 16" MBP and that has a lot of vertical resolution (1920px), but it's not enough for even one track with a flamegraph like we get using Atrace.

**Comment by LalitMaganti** [comment]
Folding this into https://github.com/google/perfetto/issues/429
