### ISSUE TITLE
Cannot enable generic ftrace events

### ISSUE THREAD

**Issue by wuzengshun** [google/perfetto#308]
Follow the Google groups discussion [](https://groups.google.com/g/perfetto-dev/c/RFJUJDNWvO0) , I tried to add some events that are not currently supported by perfetto, and then convert them to systrace files before continuing the analysis. But I found no success in enabling these generic events

**The version of perfetto I am using is:**
[Perfetto v25.0](https://github.com/google/perfetto/releases/tag/v25.0) [Latest](https://github.com/google/perfetto/releases/latest)

**Configuration file:**
```
data_sources {
   config {
        name: "linux.ftrace"
        target_buffer: 0
        ftrace_config {
         ftrace_events: "clk/*"
         ftrace_events: "power/wakeup_source_activate"
         ftrace_events: "power/wakeup_source_deactivate"
         ftrace_events: "sched/*"
         ftrace_events: "task/*"
         ftrace_events: "alarmtimer/alarmtimer_start"
         ftrace_events: "alarmtimer/alarmtimer_cancel"
         ftrace_events: "alarmtimer/alarmtimer_fired"
         ftrace_events: "alarmtimer/alarmtimer_suspend"
         ftrace_events: "ftrace/print"
         atrace_categories: "pm"
         atrace_categories: "power"
         atrace_categories: "rro"
         atrace_categories: "rs"
         atrace_categories: "sm"
         atrace_categories: "ss"
         atrace_categories: "vibrator"
         atrace_categories: "video"
         atrace_categories: "res"
         atrace_categories: "workq"
         atrace_categories: "webview"
         atrace_categories: "memory"
         atrace_categories: "idle"
         atrace_categories: "dalvik"
         atrace_categories: "freq"
         atrace_categories: "am"
         atrace_categories: "sync"
         atrace_categories: "binder_driver"
         atrace_categories: "input"
         atrace_categories: "hal"
         atrace_categories: "view"
         atrace_categories: "sched"
         atrace_categories: "wm"
         atrace_categories: "gfx"
         atrace_categories: "camera"
         atrace_categories: "memreclaim"
         atrace_apps: "*"
         compact_sched {
            enabled: true
         }
         buffer_size_kb: 100000
         drain_period_ms: 250
     }
   }
 }
```

Once perfetto was up and running, I checked the enable node for the event wakeup_source_activate and found that it was not successfully enabled, As shown below:

```
adb shell cat /sys/kernel/tracing/events/power/wakeup_source_activate/enable
0
```

**Comment by LalitMaganti** [comment]
Are you collecting this on a user or userdebug device? If on user, only selected events are allowlisted AFAIK so not all events can be collected by Perfetto.

See https://cs.android.com/android/platform/superproject/+/master:frameworks/native/cmds/atrace/atrace.rc;l=26?q=sched_switch%20f:%5C.rc&sq= and https://cs.android.com/android/platform/superproject/+/master:system/sepolicy/private/genfs_contexts;l=250?q=sched_switch%20f:sepolicy for the events which are supported

**Comment by wuzengshun** [comment]
When I execute the following command, run perfetto, and convert to systrace, I can see generic events

```
chmod 0777 /sys/kernel/tracing/events/ -R
chcon u:object_r:debugfs_tracing:s0 /sys/kernel/tracing/ -R
```
