### ISSUE TITLE
cpu_profile: Unable to download `traceconv` for symbolizing profiles.

### ISSUE THREAD

**Issue by pyricau** [google/perfetto#309]
I followed the steps documented at: https://perfetto.dev/docs/quickstart/callstack-sampling

```
curl -LO https://raw.githubusercontent.com/google/perfetto/master/tools/cpu_profile
chmod +x cpu_profile
./cpu_profile -n "com.squareup"
```

Output:

```
Configured profiling for these processes:

com.squareup

Profiling active. Press Ctrl+C to terminate.
^CFinishing profiling and symbolization...
Unable to download `traceconv` for symbolizing profiles.

 If this is unexpected, please consider filing a bug at:
https://perfetto.dev/docs/contributing/getting-started#bugs.
```

This error is raised here: https://github.com/google/perfetto/blob/master/tools/cpu_profile#L326-L331

I removed `soft_fail=True` and this time got:

```
No prebuilts available for darwin-arm64
```

I have a Mac M1 laptop. Looks like I'm going to have to build Perfetto myself, wish me luck! Anyway, this error could probably be made a bit more clear, e.g. by removing `soft_fail=True`.

**Comment by LalitMaganti** [comment]
The upcoming release of Perfetto (coming some time next week) will have M1 binaries as well so this should disappear by then.

**Comment by LalitMaganti** [comment]
The new SDK has been released :)
