### ISSUE TITLE
coredump while resolve trace

### ISSUE THREAD

**Issue by official-minister** [google/perfetto#31]
I use gapid to start a trace on android device and capture a file named *.perfetto;
I tried to resolve it in cmd :
 _out/android/trace_to_text text_
But it seems to be error:
_[858.045] trace_to_text.cc:187    Skipping invalid packet
[858.045] utils.cc:112            PERFETTO_CHECK(preamble == 0x0a) (errno: 0, Success)
------------------ BEGINNING OF CRASH ------------------
Signal: Illegal instruction (possibly unaligned access)
Fault addr: 0000000000521F11
Backtrace:
#00  0x00007F9B9328B390
#01  perfetto::trace_to_text::ForEachPacketBlobInTrace(std::__1::basic_istream<char, std::__1::char_traits<char> >*, std::__1::function<void (std::__1::unique_ptr<char [], std::__1::default_delete<char []> >, unsigned long)> const&)
     ../../tools/trace_to_text/utils.cc:112
#02  perfetto::trace_to_text::TraceToText(std::__1::basic_istream<char, std::__1::char_traits<char> >*, std::__1::basic_ostream<char, std::__1::char_traits<char> >*)
     ../../tools/trace_to_text/trace_to_text.cc:182
#03  perfetto::trace_to_text::(anonymous namespace)::Main(int, char**)
     ../../tools/trace_to_text/main.cc:178
#04  main
     ../../tools/trace_to_text/main.cc:196
#05  0x00007F9B92AC4830
#06  0x00000000004FA389
------------------ END OF CRASH ------------------
Illegal instruction (core dumped)_

Then I try to parse it in web:
_https://ui.perfetto.dev/#!/viewer_
And it can‘t load the file successfully and stop here:
_loading trace 93% - 246M/s_

Maybe there are some errors in my trace file?
How can I check it?

**Comment by primiano** [comment]
Looks like the trace is malformed.
Is there any chance you can shared the trace (here or in some drive link)?

Does that trace load in Gapid (I assume no).

@pmuetschard FYI

**Comment by official-minister** [comment]
Sorry, I can't upload the trace file and I try to use gapid to open it and failed:
_Error resolving capture
    Cause: Failed to convert proto from *capture.Record to capture.wrapper
    Cause: Not a recognized capture format._
I think the file is broken, but I don't have idea how it happened.

**Comment by primiano** [comment]
Well in this case there is nothing I can do to help, other than tell you the trace file is malformed.
