### ISSUE TITLE
Excuse me, how long can perfetto capture traces go forward? Or is the trace just real-time?

### ISSUE THREAD

**Issue by accsky** [google/perfetto#313]
Excuse me, how long can perfetto capture traces go forward? Or is the trace just real-time?Because the general recurrence of the problem is only a momentary thing, it is a bit late to capture the trace, I want to know whether it supports forward capture.

**Comment by primiano** [comment]
You can record traces that are as long as much as your storage holds.
See https://perfetto.dev/docs/concepts/config#long-traces
