### ISSUE TITLE
perfetto crashed unnamed_symbol

### ISSUE THREAD

**Issue by zerocom520** [google/perfetto#314]
**crash log**：
art_sigsegv_fault 0x0000007915a29908 art::FaultManager::HandleFault(int, siginfo*, void*) 0x0000007915a29e1c ___lldb_unnamed_symbol24$$app_process64 0x0000005561fc2e80 <unknown> 0x000000799d9df60c void perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceWithInstances<perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::DefaultTracePointTraits, perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush()::'lambda'(perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceContext)>(unsigned int, perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush()::'lambda'(perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceContext), perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::DefaultTracePointTraits::TracePointData) perfetto.h:10183 void perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::Trace<perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush()::'lambda'(perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceContext)>(perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush()::'lambda'(perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceContext))::'lambda'(unsigned int)::operator()(unsigned int) const perfetto.h:10123 void perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::CallIfEnabled<perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::DefaultTracePointTraits, void perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::Trace<perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush()::'lambda'(perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceContext)>(perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush()::'lambda'(perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceContext))::'lambda'(unsigned int)>(void perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::Trace<perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush()::'lambda'(perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceContext)>(perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush()::'lambda'(perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceContext))::'lambda'(unsigned int), perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush()::'lambda'(perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceContext)::TracePointData) perfetto.h:10152 void perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::Trace<perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush()::'lambda'(perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceContext)>(perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush()::'lambda'(perfetto::DataSource<perfetto::TrackEvent, perfetto::internal::TrackEventDataSourceTraits>::TraceContext)) perfetto.h:10122 perfetto::internal::TrackEventDataSource<perfetto::TrackEvent, &(perfetto::internal::kCategoryRegistry)>::Flush() perfetto.h:16667 bdtrace::stop_trace_session(unsigned long) trace_session_manager.cpp:85 art_quick_generic_jni_trampoline 0x000000791593ded8 art_quick_invoke_static_stub 0x00000079159347ec art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*) 0x0000007915998eb4 art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*) 0x0000007915b047d8 bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915aff8f0 void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*) 0x0000007915948364 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915aff8d4 void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*) 0x0000007915947758 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915aff8d4 void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*) 0x0000007915947758 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915aff8d4 void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*) 0x0000007915947758 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915b00274 void art::interpreter::ExecuteSwitchImplCpp<true, false>(art::interpreter::SwitchImplContext*) 0x000000791596d140 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915b00274 void art::interpreter::ExecuteSwitchImplCpp<true, false>(art::interpreter::SwitchImplContext*) 0x000000791596d140 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915aff8d4 void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*) 0x0000007915947758 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915aff8d4 void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*) 0x0000007915947758 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915aff8d4 void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*) 0x0000007915947758 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915aff8d4 void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*) 0x0000007915947758 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915aff8d4 void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*) 0x0000007915947758 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915aff8d4 void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*) 0x0000007915947758 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*) 0x0000007915afef94 bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x0000007915b00274 void art::interpreter::ExecuteSwitchImplCpp<true, false>(art::interpreter::SwitchImplContext*) 0x000000791596f3e8 ExecuteSwitchImplAsm 0x00000079159407dc art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10934500811037150869) 0x0000007915af73d4 artQuickToInterpreterBridge 0x0000007915e21d00 art_quick_to_interpreter_bridge 0x000000791593dffc <unknown> 0x000000791593e210

I Debug，found crash in：
<img width="847" alt="image" src="https://user-images.githubusercontent.com/5218480/175905245-0433048e-50a0-4d87-b5d3-335578788167.png">

looks like the "tls_state_" undefined.

**Comment by primiano** [comment]
This bug is very generic and unactionable.

1. What failed? Was an app? native? java? What were you trying to do?
2. Repro steps? Which OS? Which version of the SDK?
3. How does your code look like? What are you trying to do.

I mean, you can't just paste a callstack without any context and go "here, crash". (Or, better, you can, but nobody will do anything with the bug and eventually people will close it)
