### ISSUE TITLE
[UI][Feature Request] Support setting pinned tracks in config

### ISSUE THREAD

**Issue by FredLoh** [google/perfetto#315]
We create various async traces when profiling our android app. This leads to each trace being set up in an individual track. We would love the ability to be able to tell perfetto that we would like our main app process as well as various other tracks to be pinned by default when the trace is opened.

**Comment by LalitMaganti** [comment]
I don't think the UI should be configured by the config but I definitely think there is appetite for improving the pinned track UX. @chromy @octaviantu

**Comment by LalitMaganti** [comment]
Going to fold this into https://github.com/google/perfetto/issues/429
