### ISSUE TITLE
Visualize percentage metrics using Chrome Tracing Format in JSON

### ISSUE THREAD

**Issue by alizalisan** [google/perfetto#316]
I intend to visualize percentage metrics (e.g. CPU utilization, memory utilization) in Perfetto UI using Chrome Tracing Format in JSON. Does Perfetto provide support for data other than time, frequency, etc.? Percentage in particular. Thanks.

**Comment by LalitMaganti** [comment]
> Does Perfetto provide support for data other than time, frequency, etc.? Percentage in particular. Thanks.

Sorry you need to be more specific here. Do you mean at the trace level, at the trace processor level at the UI level? It's not clear what exactly you expect to see and where.
