### ISSUE TITLE
TrackEvent: Async thread tracks don't get grouped like async process tracks in the UI

### ISSUE THREAD

**Issue by betasheet** [google/perfetto#321]
From discussion around https://github.com/google/perfetto/issues/60#issuecomment-1173923766

It seems that two or more (async) child tracks of a thread track don't get grouped into a single vertical track in the Perfetto UI, even when they share the same name. For child tracks of process tracks, vertical merging does happen.

I imagine this should be reproducible via the SDK as well, e.g. with something like this (untested):
```
  TRACE_EVENT_BEGIN("cat", "AsyncTrack", perfetto::Track::ThreadScoped(obj1));
  TRACE_EVENT_BEGIN("cat", "AsyncTrack", perfetto::Track::ThreadScoped(obj2));
  TRACE_EVENT_END("cat", perfetto::Track::ThreadScoped(obj1));
  TRACE_EVENT_END("cat", perfetto::Track::ThreadScoped(obj2));
```

I believe, currently, such child tracks are imported as thread tracks in trace processor ([code](https://source.chromium.org/chromium/chromium/src/+/main:third_party/perfetto/src/trace_processor/importers/proto/track_event_tracker.cc;drc=d5c694fc357d3b1cb40b3d40bb0c1e1ca15d952f;l=447). I wonder if the collapsing/merging logic is only enabed for process tracks, not thread tracks, in the UI? Is there a reason for this / can we also extend it to thread tracks (e.g. those which share a name, possibly where track name != thread name)? :)

**Comment by nagua** [comment]
Hello everyone,
I wanted to ask if there is any progress on this issue?

Have a nice day!

**Comment by LalitMaganti** [comment]
There has been no user-visible progress but @stevegolton has done a bunch of work to simplify how track addition works which would make working on this issue significantly easier: https://r.android.com/3204614, https://r.android.com/3170406.

I'll discuss this with Steve next week and update based on what we decide.

**Comment by nagua** [comment]
Hi @LalitMaganti,
Did you find some time to discuss this? 

Have a nice week!

**Comment by LalitMaganti** [comment]
Yes we discussed this. We agreed the fix was simple and we should go ahead and implement it.

I'll send something when I get some time.

**Comment by LalitMaganti** [comment]
This will be fixed by https://r.android.com/3238039

**Comment by nagua** [comment]
Hi @LalitMaganti,
I looked at the linked PR and it seems that the PR only touches the UI.
If I understood the initial feature report correctly this is also about having an
API in the Perfetto SDK (C++) to produce such traces in the first place. Or do I miss something here?
At least in v47.0 there does not seem to exist a `perfetto::Flow::ThreadScoped` class to produce such traces.

**Comment by LalitMaganti** [comment]
> API in the Perfetto SDK (C++) to produce such traces in the first place. Or do I miss something here?

The API in the SDK exists [here](https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/include/perfetto/tracing/track.h;l=124?q=%20perfetto::Track::ThreadScoped): the initial comment shows how to use that.

`perfetto::Flow::ThreadScoped` references a flow: not sure how that's related here: this issue is purely around merging thread scoped tracks produced by the SDK/synthesised directly.

**Comment by nagua** [comment]
Sorry, you are right. I misread the initial post and used the `ProcessScoped` last and thought it would be in the same namespace. Thank you for fixing this issue!

**Comment by TApplencourt** [comment]
Thanks a lot, guys! Highly appreciated
