### ISSUE TITLE
SAVING ISSUE + home wifi randomly disconnects 

### ISSUE THREAD

**Issue by TheGithuber200** [google/perfetto#324]
WHY DO PERFETTO TRACES KEEP SAVING ON MY PHONE FOREVER UGHHH also I don't understand the network trace as I'm trying to find out why my phone randomly disconnects from home wifi.

**Comment by chromy** [comment]
Sorry I'm confused, do you want the traces or not?

Regarding network trace, sorry I'm not familiar with it.
However I would not necessarily expect it to be that helpful with debugging disconnects.
Have you tried looking at logcat and (if the device is rooted) dmsg?

In general it's hard to help without more details. For example:
- What device are you using?
- What Android version?
- What have you tried to do?
- What did you expect to happen when you did that?
- What actually happened when you did that?

Also if possible please keep it to one issue per issue :)

I'll close for now, please reopen if you have more information.

**Comment by TheGithuber200** [comment]
> Sorry I'm confused, do you want the traces or not?
> 
> Regarding network trace, sorry I'm not familiar with it. However I would not necessarily expect it to be that helpful with debugging disconnects. Have you tried looking at logcat and (if the device is rooted) dmsg?
> 
> In general it's hard to help without more details. For example:
> 
> * What device are you using?
> * What Android version?
> * What have you tried to do?
> * What did you expect to happen when you did that?
> * What actually happened when you did that?
> 
> Also if possible please keep it to one issue per issue :)
> 
> I'll close for now, please reopen if you have more information.

Oneplus nord 2 ce
Android 11
Save a network trace to see what a forcefull disconnect would look like to find out why my device randomly disconnects it doesn't wanna disconnect during the network trace cause it's a """""" 
I thought my trace would save BUT IT DOESN'T it just says saving trace for a millenia...

**Comment by TheGithuber200** [comment]
That should clarify things

**Comment by LalitMaganti** [comment]
It's really not clear what you mean by "network trace". How exactly are you collecting the trace: with an adb command, Perfetto UI or something else?

**Comment by TheGithuber200** [comment]
Network security from ANDROID DEVELOPER SETTINGS ok?

**Comment by TheGithuber200** [comment]
There

**Comment by LalitMaganti** [comment]
Perfetto is not really built to debug networking issues so I would advise you look elsewhere - I doubt you're going to find the cause of loss of network connectivity from a trace: try using a bugreport or logcat instead - that's more likely to give you some answers.

**Comment by TheGithuber200** [comment]
> Perfetto is not really built to debug networking issues so I would advise you look elsewhere - I doubt you're going to find the cause of loss of network connectivity from a trace: try using a bugreport or logcat instead - that's more likely to give you some answers.

But I'm on mobile how can I do that?

**Comment by TheGithuber200** [comment]
Android
