### ISSUE TITLE
Trace file data error when writing data directly to file on Windows

### ISSUE THREAD

**Issue by chenshaoyang0011** [google/perfetto#327]
I follow the instruction on the bottom of this doc:[https://perfetto.dev/docs/instrumentation/tracing-sdk](url).
Try to tell Perfetto to write directly to file.
```int fd = open("example.perfetto-trace", O_RDWR | O_CREAT | O_TRUNC, 0600);
tracing_session->Setup(cfg, fd);
tracing_session->StartBlocking();
// ...
tracing_session->StopBlocking();
close(fd);
```

I modify some code in examples/sdk/example.cc

```
std::unique_ptr<perfetto::TracingSession> StartTracing() {
  perfetto::TraceConfig cfg;
  cfg.add_buffers()->set_size_kb(1024);
  auto* ds_cfg = cfg.add_data_sources()->mutable_config();
  ds_cfg->set_name("track_event");

  fd = open("example.pftrace", O_RDWR | O_CREAT | O_TRUNC, 0600);
  auto tracing_session = perfetto::Tracing::NewTrace(perfetto::kInProcessBackend);
  tracing_session->Setup(cfg,fd);
  tracing_session->StartBlocking();
  return tracing_session;
}

void StopTracing(std::unique_ptr<perfetto::TracingSession> tracing_session) {
  // Make sure the last event is closed for this example.
  perfetto::TrackEvent::Flush();

  // Stop tracing and read the trace data.
  tracing_session->StopBlocking();

  close(fd);
}
```

Finally get the trace file , but when i try to open this file using TraceViewer，there is a error output

![image](https://user-images.githubusercontent.com/2214937/180215124-dcb05892-9f96-49dc-a607-a9b0d5d8d578.png)

**Comment by LalitMaganti** [comment]
@ddiproietto

**Comment by ddiproietto** [comment]
You're missing O_BINARY

fd = open("example.pftrace", O_RDWR | O_CREAT | O_TRUNC | O_BINARY, 0600);

IIRC from my windows days, without O_BINARY the C library tries to translate \n into \n\r and this messed up binary formats, such as the perfetto trace format.
