### ISSUE TITLE
trace_processor_shell is broken on x64 VirtualBox Linux VMs

### ISSUE THREAD

**Issue by qais-yousef** [google/perfetto#328]
I have a CI running in VirtualBox VM part of which I process perfetto traces via python API collected from Android devices.

Recently I started getting weird failures that I tracked down to the new optimization flags added to `trace_processor_shell` as part of `enable_perfetto_x64_cpu_opt` added by this commit: https://github.com/google/perfetto/commit/2277f0695ed61c8ebdd1e2a2d60f4eb3f306e82c

The error I was getting is:

```
This executable requires a x86_64 cpu that supports SSE4.2, BMI2 and AVX2.
Rebuild with enable_perfetto_x64_cpu_opt=false.
```

Worth noting is that I was using perfetto 0.3 from pypi to process the perfetto traces. Which automatically downloads the latest version. So this breakage was a bit surprising. (I did move to perfetto 0.5 pypi release as part of the investigation FWIW).

I used `TraceProcessorConfig()` to enable verbose output which allowed me to see the real error message above. My python script was failing with something very random about failing to allocate Random Port or something like this. I had to scratch my head for a bit thinking something went wrong with my system setup or a system update has gone wrong.

It turned out at the end that while my hardware does support BMI2, but VirtualBox doesn't pass this on to the guest. I do see SSE4.2 and AVX2 in `/proc/cpuinfo` but not BMI2. vbox.log also clearly shows that BMI2 is not enabled on guest but available on the host. It seems VBox is still working on getting BMI2 support although it's been there for a while..

https://www.virtualbox.org/ticket/15471

I managed to work around the problem by downloading v25 and use `TraceProcessorConfig()` to set `bin_path` after implementing a simple function to see if `trace_processor_shell` is somewhere in PATH to use a pre-installed version rather than always download the latest one. Otherwise fallback to downloading as usual.

I liked the idea of the auto download as I hit issues in the past with incompatibility between traces captures by `perfetto` and `trace_processor_shell`. I wonder if it would be simple to detect if the system has the required requirements and download a non-optimized version automatically. Just a thought. I'm happy with my current workaround, but thought at least worth documenting this with an issue in case others get  hit by it too. For me it suddenly stopped working and the symptom was hard to diagnose.

**Comment by chromy** [comment]
Glad you managed to work around this, and thanks for the detailed bug report!

In my mind there ideally there are three actions to take:
1. Better error message if Python library fails to start `trace_processor_shell`
2. Python library should detect if any of {SSE4.2, BMI2 and AVX2} are missing 
3. (maybe) we should provide `trace_processor_shell` binaries without `enable_perfetto_x64_cpu_opt`

The first one we can probably get too but I imagine the rest won't ever get prioritised high enough that we get to them ourselves.

**Comment by LalitMaganti** [comment]
+1 absolutely back up what Hector says. We should definitely expose the error message if trace processor binary fails to start but I think publishing x64 binaries/detecting CPU caps from Python is just not high prio enough.

**Comment by qais-yousef** [comment]
A more helpful error message would be great! Maybe a suggestion to use `TraceProcessorConfig()` to force use a specific installed version would be good too as I had to look at source code to find out about these things (maybe it's documented but I failed to see that). Not sure if that can be phrased generically without a problem.

Giving the option to specify which released version to Download might be useful too.

Just random suggestions, not saying you should do any of this! :-)

I don't think Python library should detect any hardware deps. IMHO, if anything to be done, it needs to be done in `trace_processor_shell` binary itself. You can use some GCC builtin intrinsics and see if it supports a feature before calling an optimized routine. And maybe there are already some libraries that does that already for you that you just need to link to.

See `__builtin_cpu_supports()` in GCC docs for an example. In theory, it shouldn't be that time consuming to use. But of course, the devil is always in the details :-)

https://gcc.gnu.org/onlinedocs/gcc/x86-Built-in-Functions.html

**Comment by LalitMaganti** [comment]
We turn on autovectorization so we cannot just say: check CPU features before calling a function because potentially any function can end up having AVX/BMI instructions :)

**Comment by qais-yousef** [comment]
Right :-)

**Comment by LalitMaganti** [comment]
The error message has been improved now: this is all we can commit to do now.
