### ISSUE TITLE
[UI] Perfetto UI struggles to open a very large (13MB) .ninja_log 

### ISSUE THREAD

**Issue by heatd** [google/perfetto#329]
Trying to open one of Fuchsia's .ninja_log from a past build (around 13MB of data, 100k lines), ui.perfetto.dev seems to get stuck loading it. If preprocessed into a chrome trace using https://github.com/nico/ninjatracing, it loads very quickly.

**Comment by chromy** [comment]
Thanks! Please attach the `.ninja_log` so we can look into this.

**Comment by heatd** [comment]
Attached the ninja_log. Note that you should decompress it (I only compressed it for uploading), as this particular issue doesn't seem to reproduce with a .gz (It loads fairly quickly, but you get an empty trace view).

[.ninja_log.gz](https://github.com/google/perfetto/files/9175846/default.ninja_log.gz)

**Comment by LalitMaganti** [comment]
This issue should now be fixed (including the ninja inside gzip one) - should rollout to the UI in the next release.
