### ISSUE TITLE
[UI] Trace Viewer adds 100 ns to every timestamp

### ISSUE THREAD

**Issue by kdt111** [google/perfetto#330]
When opening a trace file in the UI all of the timestamps are bigger by 100 ns than what is written in the file
![custom-trace-view](https://user-images.githubusercontent.com/62014573/181471567-cc1709d1-5451-4dbf-a9f0-81ec7d7e8bab.png)
When converting the binary file to text using `traceconv` the events look like this
```
packet {
  timestamp: 0
  trusted_packet_sequence_id: 0
  track_event {
    type: TYPE_SLICE_BEGIN
    track_uuid: 1
    name: "Slice"
  }
}
packet {
  timestamp: 20
  trusted_packet_sequence_id: 0
  track_event {
    type: TYPE_INSTANT
    track_uuid: 1
    name: "Instant"
  }
}
packet {
  timestamp: 100
  trusted_packet_sequence_id: 0
  track_event {
    type: TYPE_SLICE_END
    track_uuid: 1
  }
}
```
The above file was not generated using the Perfetto SDK, but manually by writing protobuf messages to a file. At first I thought that something may be incorrectly encoded on my side, but this behavior is also present when generating traces using the SDK
![sdk-trace-view](https://user-images.githubusercontent.com/62014573/181472726-76cd5a64-01d0-40e0-9c97-8a479b93164d.png)

```
packet {
  timestamp: 0
  sequence_flags: 2
  track_event {
    type: TYPE_INSTANT
    category_iids: 1
    name_iid: 1
  }
  interned_data {
    event_categories {
      iid: 1
      name: "execution"
    }
    event_names {
      iid: 1
      name: "Hello!"
    }
  }
  trusted_uid: 0
  trusted_packet_sequence_id: 2
  trusted_pid: 0
}
```
Both traces were generated on Debian 11.4 on kernel 5.10.0-16-amd64. The UI was opened on Firefox 91.11 and Chromium 103.0.5060.134. Both stable and canary versions of the UI were tested on both browsers

Both of the trace files:
[trace-files.zip](https://github.com/google/perfetto/files/9207753/trace-files.zip)

**Comment by primiano** [comment]
Uh, @kdt111 thanks a lot for filing an accurate bug first of all.

I looked a bit into the trace, interestingly the problem seems to be purely a UI problem.
The ingestion in TraceProcessor seems to work fine. Down into the TraceProcessor the timestamps are still correct.

If I run the query in the UI `select * from slices` I get the following result

![image](https://user-images.githubusercontent.com/7137473/181488371-3031f20b-278f-47b4-9e95-cf9d20e44198.png)

Both UI Canary and Stable exhibit the behaviour.

@chromy can you triage this. Something somewhere in the UI ends up with an extra 100ns ^__^.
I blame 2022's inflation.

**Comment by chromy** [comment]
Hey! Yes I do vaguely remember this coming up before with the magic-trace folks, I don't remember exactly where it gets added. Let me take a look if I can see where it gets added.

**Comment by Walton1128** [comment]
any updates about this issue?  Meet similar issue

**Comment by LiangliangSui** [comment]
Seems to be a problem introduced by **|TRACE_MARGIN_TIME_S|**, which makes the traceBound extend left and right respectively by |TRACE_MARGIN_TIME_S|(1/ 1e7 s).
In the TimeScale class, the rect is calculated in the timeToPx method, which will be calculated according to |this.timeBounds.start|, and finally the slice is delayed by 100ns.
|TRACE_MARGIN_TIME_S| seems to be introduced by this [change](https://android-review.googlesource.com/c/platform/external/perfetto/+/1559592) @chromy

**Comment by chromy** [comment]
@LiangliangSui ah thanks very much for the investigation!
I completely forgot where this happened.
We should just remove that, it's really not a good way to fix the bug that CL mentioned and in any case I think it causes more confusion than it solves. I can remove it, or if you want to send CL I would be super grateful :)

**Comment by LalitMaganti** [comment]
Thanks @LiangliangSui for fixing :)
