### ISSUE TITLE
How to record detail performance data on Windows?

### ISSUE THREAD

**Issue by chenshaoyang0011** [google/perfetto#331]
Is there a way to record data like cpu usage, memory usage on Windows?
I learn from docs and says it can be record on system wide mode, but not support on Windows. So is there a other way to record data like cpu usage?
And is there plan to support system wide mode on Windows?

**Comment by LalitMaganti** [comment]
No this is not supported on Windows not are their any plans for this from our side. External contributions are welcome.,
