### ISSUE TITLE
how to collect data from power rails?

### ISSUE THREAD

**Issue by VysotskiVadim** [google/perfetto#333]
I'm looking for a way to reliably measure battery consumption. [Power rails](https://perfetto.dev/docs/data-sources/battery-counters#power-rails) seems interesting as I don't need to unplug test device. But I just can't find a device which has an equipment needed for power rails.
Which devices do you use to collect those data?

**Comment by LalitMaganti** [comment]
Only the latest Pixels (6 series) have these rails on production devices. This requires dedicated hardware on device which (to the best of my knowledge) I do not believe any other OEM have included.

**Comment by tmpsantos** [comment]
@LalitMaganti thank you!
