### ISSUE TITLE
[trace_processor] update allowed origins for httpd connections?

### ISSUE THREAD

**Issue by kting28** [google/perfetto#335]
I have my own instance of perfetto hosted on a server. Not able to connect to trace_processor httpd since the allowed origin is hardcoded:

```
const char* kAllowedCORSOrigins[] = {
    "https://ui.perfetto.dev",
    "http://localhost:10000",
    "http://127.0.0.1:10000",
};
```

Anyway of getting around this without adding my perfetto ui server to the source and compile my own trace_process_shell ?

**Comment by LalitMaganti** [comment]
The best option would be to allow specifying your own custom CORS origins using a command line flag: patches for this are welcome. If you decide to send something, please follow the instructions at https://perfetto.dev/docs/contributing/getting-started and https://perfetto.dev/docs/contributing/build-instructions
