### ISSUE TITLE
how can i use perfetto to caputre the old gfx(Graphics) tag.

### ISSUE THREAD

**Issue by qingxianhao** [google/perfetto#336]
how can i use perfeto to caputre the gfx(Graphics) tag.

and are there a mapping table that list all of the new events and the old tags that could be mapped to?

**Comment by LalitMaganti** [comment]
If you are using [record_android_trace](https://perfetto.dev/docs/quickstart/android-tracing#recording-a-trace-through-the-cmdline), you can just pass gfx as a tag: Perfetto will map that to the appropriate events.

The atrace category to event mapping can be found in this [file](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/traced/probes/ftrace/ftrace_config_muxer.cc;l=144?q=gfx%20f:perfetto%20f:probes)

**Comment by qingxianhao** [comment]
thanks a lot @LalitMaganti.
