### ISSUE TITLE
Thread States with 'No Load(non-IO)'

### ISSUE THREAD

**Issue by CatDroid** [google/perfetto#337]
Use perfetto on Android 12.
sometime I get Thread State is "No Load(non-IO) + undefined + undefined+ undefined "
what it means ?

**Comment by LalitMaganti** [comment]
This is not expected. Can you please attach a trace so we can investigate further? We cannot do anything more without the trace.

**Comment by LalitMaganti** [comment]
Please reopen with a trace if you have it.

**Comment by CatDroid** [comment]
[link](https://ui.perfetto.dev/#!/viewer?local_cache_key=b13588fd-746b-24a3-7d42-d79bd1bed449)
VenusResource 9876 
time: 4.5s
the thread state is "blue", not Runnable or Running

**Comment by CatDroid** [comment]
I can not reopen the issuse myself ~

**Comment by CatDroid** [comment]
> Please reopen with a trace if you have it.

Please reopen the issue

**Comment by LalitMaganti** [comment]
I believe this should be fixed by https://android-review.googlesource.com/c/platform/external/perfetto/+/2221002
