### ISSUE TITLE
ui.perfetto run blocked when use stress-ng

### ISSUE THREAD

**Issue by jluyangsonghua** [google/perfetto#339]
PC C:\tools> adb shell
kona # stress-ng --cpu 1 --fork 4 --timeout=60s

PC C:\tools> python.exe systrace.py -a "*" -t 1 -b 50000 -o .\stress_1_cpu_4_fork.html

then,use chrome perfetto open the stress_1_cpu_4_fork.html

the ui run blocked.

**Comment by jluyangsonghua** [comment]
may u should read the html file,
how to upload the html file?

**Comment by LalitMaganti** [comment]
A few comments:
1) When you say "the ui run blocked." what do you mean?
2) If you want us to investigate this further, please attach the trace showing the problem
3) Please note html traces are supported on a best-effort basis
4) Please consider migrating from systrace.py to collecting traces using [Perfetto](https://perfetto.dev/docs/quickstart/android-tracing). systrace has been deprecated for several years at this point and Perfetto is the replacement.

**Comment by LalitMaganti** [comment]
The HTML file can be attached to this bug.

**Comment by jluyangsonghua** [comment]
i drag the html here, but failed;
and i click "attach files by dragging &...", then choose the html file, failed too...

**Comment by LalitMaganti** [comment]
Yeah I don't know why that's happening: maybe because the trace is too big? How big is the file?

**Comment by jluyangsonghua** [comment]
the file is 44MB

**Comment by jluyangsonghua** [comment]
I compress the file to 2.9MB，failed to upload too...

**Comment by jluyangsonghua** [comment]
I find the reason, The compute not allowed to send file to Intenet...
Maybe i send the file txt on comment
