### ISSUE TITLE
track_event coredump

### ISSUE THREAD

**Issue by official-minister** [google/perfetto#34]
branch: master
commit: f447425f9f7f676bf22d3c5e4a78f30d43c92c95

I find that I use trace_processor_shell to parse a trace.file and it will coredump like this :

(gdb) c
Continuing.
[117.115] ack_event_parser.cc:644 PERFETTO_CHECK(event_name.data()) (errno: 0, Success)
[Thread 0x7ffff7ff4740 (LWP 19420) exited]
Thread 1 "trace_processor" received signal SIGILL, Illegal instruction.
0x000000000071e85b in perfetto::trace_processor::TrackEventParser::EventImporter::ParseMetadataEvent (this=0x7fffffff50e0)
    at ../../src/trace_processor/importers/proto/track_event_parser.cc:644
644         PERFETTO_DCHECK(event_name.data());
(gdb) c
Continuing.
_------------------ BEGINNING OF CRASH ------------------
Signal: Illegal instruction (possibly unaligned access)
Fault addr: 000000000071E85B
Backtrace:
#00  0x00007FFFF79C5390
#01  perfetto::trace_processor::TrackEventParser::EventImporter::ParseMetadataEvent()
     ../../src/trace_processor/importers/proto/track_event_parser.cc:644
#02  perfetto::trace_processor::TrackEventParser::EventImporter::Import()
     ../../src/trace_processor/importers/proto/track_event_parser.cc:178
#03  perfetto::trace_processor::TrackEventParser::ParseTrackEvent(long, perfetto::trace_processor::TrackEventData*, protozero::ConstBytes)
     ../../src/trace_processor/importers/proto/track_event_parser.cc:1570
#04  perfetto::trace_processor::TrackEventModule::ParsePacket(perfetto::protos::pbzero::TracePacket_Decoder const&, perfetto::trace_processor::TimestampedTracePiece const&, unsigned int)
     ../../src/trace_processor/importers/proto/track_event_module.cc:76
#05  perfetto::trace_processor::ProtoTraceParser::ParseTracePacketImpl(long, perfetto::trace_processor::TimestampedTracePiece, perfetto::trace_processor::TracePacketData const*, perfetto::protos::pbzero::TracePacket_Decoder const&)
     ../../src/trace_processor/importers/proto/proto_trace_parser.cc:115
#06  perfetto::trace_processor::ProtoTraceParser::ParseTracePacket(long, perfetto::trace_processor::TimestampedTracePiece)
     ../../src/trace_processor/importers/proto/proto_trace_parser.cc:96
#07  perfetto::trace_processor::TraceSorter::SortAndExtractEventsBeyondWindow(long)
     ../../src/trace_processor/trace_sorter.cc:140
#08  perfetto::trace_processor::TraceSorter::ExtractEventsForced()
     ../../src/trace_processor/trace_sorter.h:158
#09  perfetto::trace_processor::TraceProcessorStorageImpl::NotifyEndOfFile()
     ../../src/trace_processor/trace_processor_storage_impl.cc:0
#0A  perfetto::trace_processor::TraceProcessorImpl::NotifyEndOfFile()
     ../../src/trace_processor/trace_processor_impl.cc:570
#0B  perfetto::trace_processor::ReadTrace(perfetto::trace_processor::TraceProcessor*, char const*, std::__1::function<void (unsigned long)> const&)
     ../../src/trace_processor/read_trace.cc:122
#0C  perfetto::trace_processor::(anonymous namespace)::TraceProcessorMain(int, char**)
     ../../src/trace_processor/trace_processor_shell.cc:951
#0D  main
     ../../src/trace_processor/trace_processor_shell.cc:1109
#0E  0x00007FFFF71FE830
#0F  0x00000000005A3D29
------------------ END OF CRASH ------------------_

and I use an old version can parse it(Jan 30 commit: 15c8c3e5af6e843dfcaf036333b7ccdfbb1b725f).

Then I use trace_to_text parseit, I find the error trace message like this:
_packet {
  trusted_uid: 10301
  timestamp: 704682336306572
  trusted_packet_sequence_id: 5
  track_event {
    category_iids: 1
    debug_annotations {
      name_iid: 1
      string_value: "XXXXXXXXXXXXX"
    }
    legacy_event {
      name_iid: 1
      phase: 77
    }
  }
  interned_data {
    event_categories {
      iid: 1
      name: "cat"
    }
    event_names {
      iid: 1
      name: "process_name"
    }
    debug_annotation_names {
      iid: 1
      name: "name"
    }
  }
  previous_packet_dropped: true
}_

I read the code and I think the problem generate while you update perfetto:
      NullTermStringView event_name = storage->GetString(name_id);
      PERFETTO_DCHECK(event_name.data());
In LookupInternedMessage func, interned_data_ map can't find FieldId. Maybe InternedFieldMap initialization has problem.(because my trace packet has name : process_name but can't find it.)

Is it a bug? Or how can I fix it?

**Comment by official-minister** [comment]
I think it's a compatibility problem. Old commit works well

**Comment by official-minister** [comment]
How to recurrent it:
use gapid(master branch newest code) and capture trace with systemprofile and config: vulkan track memory. The gapis will coredump becauseof this pro blem.
Use release gapid 1.7 it woks well because using old version

**Comment by primiano** [comment]
@tilal6991 can you take a look?

@official-minister can you attach a trace file (instead of text dump)? It would help a lot.
We don't ahve a good way to go back from the text dump to the file to feed in trace processor

**Comment by official-minister** [comment]
Sorry I can't push trace file for some reason. I just can write trace txt here. 
I described the situation how to recurrent it.

I avoid the proplem by doing this:
    src\trace_processor\importers\proto\track_event_parser.cc
    _// Parse process and thread names from correspondingly named events.
    NullTermStringView event_name = storage_->GetString(name_id_);
    //PERFETTO_DCHECK(event_name.data());
    if(!event_name.data()) {
        return util::OkStatus();
    }_

But I think it's not the root cause. I hope it will help you analysis the problem.

**Comment by tilal6991** [comment]
I took a look and I think returning ok when event_name is null is not the right solution.

@betasheet can you see anything wrong with the data in the trace? Seems from the code that name_id_ is being set to null id which should never happen.

**Comment by official-minister** [comment]
> I took a look and I think returning ok when event_name is null is not the right solution.
> 
> @betasheet can you see anything wrong with the data in the trace? Seems from the code that name_id_ is being set to null id which should never happen.


I agree with your opinion. I'm confused why name_id_ is null.

**Comment by betasheet** [comment]
Maybe the trace doesn't set the SEQ_INCREMENTAL_STATE_CLEARED flag?

In terms of the crash - good question. Maybe the early out should also check for name being the empty string, in addition to kNullStringId?

**Comment by betasheet** [comment]
Talking about this early-out: https://source.chromium.org/chromium/chromium/src/+/master:third_party/perfetto/src/trace_processor/importers/proto/track_event_parser.cc;l=681?q=track_event_parser.cc:644

FWIW, the packet should really also be setting SEQ_NEEDS_INCREMENTAL_STATE as it is using incremental state. In that case, it would likely be discarded during tokenization.

How did you generate this trace?

**Comment by tilal6991** [comment]
Re the crash: the string is actually null not empty (this is why the crash happens) which means the early return is not being hit correctly (https://source.chromium.org/chromium/chromium/src/+/master:third_party/perfetto/src/trace_processor/importers/proto/track_event_parser.cc;l=680?q=track_event_parser.cc:644)

**Comment by tilal6991** [comment]
@official-minister it would be really helpful if you could share the trace so I could repro this behaviour. Seems a pretty bad bug going on.

The easiest way to share a trace if Github doesn't allow it to be uploaded is to use something like Google Drive/Dropbox and share the link ehre.

**Comment by official-minister** [comment]
Sorry I can't upload file because of net environment. I can tell you how I get it.
I use gaid(master branch) code: (1.7 release works no bug.)
https://github.com/google/gapid
and complie it follow this:
https://github.com/google/gapid/blob/master/BUILDING.md
and I start trace with vulkan memory track. It will generate it. 

Maybe you can refer to : https://github.com/google/agi/issues/334

**Comment by tilal6991** [comment]
I don't have the cycles to try and get AGI compiling on my Mac unfortunately (I did try but I ran into errors which I didn't look into further). If I manage to get a trace (either from yourself or the AGI folk), I'd be happy to look into this but otherwise, I am putting this on pause.

**Comment by LalitMaganti** [comment]
Closing this issue as it's essentially unactionable as is and there's been a lot of changes in AGI <-> Perfetto integration since this bug was opened.
