### ISSUE TITLE
sys_write is not supported by ui.perfetto.dev

### ISSUE THREAD

**Issue by wenjianhn** [google/perfetto#340]
Expected: 
sys_write should show up in the ui.

Actual: 
only sys_read

Perfetto version: 
commit ee7e55c548972cb286c595a89e308768cff1f379

This seems to be a known issue or an expected behavior.
So I only add the `dd` command that is used to generate the ftrace events and the config here.
Let me know if more info is needed.

`dd if=/dev/zero of=./test oflag=sync bs=4096 count=100000`

[data_sources](https://perfetto.dev/docs/data-sources/syscalls#traceconfig):
```
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            ftrace_events: "raw_syscalls/sys_enter"
            ftrace_events: "raw_syscalls/sys_exit"
        }
    }
}
```

**Comment by LalitMaganti** [comment]
This is a KI and an unfortunate limitation [1] of the fact that atrace slices on Android also invoke a write syscall meaning that we lose proper stacking.

Contributions for both supporting Android traces without horribly mangling them while also supporting sys_write is welcome.

[1] https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/importers/syscalls/syscall_tracker.h;l=73?q=%22We%20see%20two%20write%20sys%20calls%20around%20each%20userspace%20slice%20that%20is%20going%20via%22

**Comment by LalitMaganti** [comment]
@rsavitski fixed this as much as possible in https://android-review.googlesource.com/c/platform/external/perfetto/+/2203569/ so I think this can be closed.
