### ISSUE TITLE
windows support for enable_perfetto_tools=true

### ISSUE THREAD

**Issue by blockspacer** [google/perfetto#341]
remove "src/websocket_bridge" from all_targets on windows

see in BUILD.gn

if (enable_perfetto_tools) {
  all_targets += [
    "src/tools",
    "src/websocket_bridge",
  ]
}

on WINDOWS enable_perfetto_tools error: assert(enable_perfetto_ipc)
because tools/websocket_bridge uses ipc:default_socket

(windows 10, clang-cl)

**Comment by primiano** [comment]
Closing as https://android-review.googlesource.com/c/platform/external/perfetto/+/2198419 landed
