### ISSUE TITLE
Does not show Unity's AddressablesBuildTEP.json file

### ISSUE THREAD

**Issue by UnityAnthony** [google/perfetto#350]
The UI for chrome://tracing shows the data for diagnostic tools for Unity's Addressable system  in the file AddressablesBuildTEP.json (https://docs.unity3d.com/Packages/com.unity.addressables@1.16/manual/DiagnosticTools.html) but when switching to perfetto nothing shows. Feel free to use attached file just change it back from txt to json

**Comment by UnityAnthony** [comment]
[AddressablesBuildTEP.txt](https://github.com/google/perfetto/files/9472716/AddressablesBuildTEP.txt)
This is the file

**Comment by LalitMaganti** [comment]
Fixed by https://android-review.googlesource.com/c/platform/external/perfetto/+/2200217

**Comment by UnityAnthony** [comment]
Ok I just looks (Updated to v27.1-c62a4851b) and it did work in Stable or Canary, I will check back in a month
