### ISSUE TITLE
How do you set the thread name programmatically?

### ISSUE THREAD

**Issue by eladmaimoni** [google/perfetto#351]
I use the C++ SDK to initiate a profiling session

```
auto tracing_session = perfetto::Tracing::NewTrace();
tracing_session->Setup(cfg);
tracing_session->StartBlocking();
...
TRACE_EVENT(...)
```

I would like to annotate each thread I create with a unique name so I can identify them in the UI.

I saw this related issue but it doesn't show how to do this programmatically [https://github.com/google/perfetto/issues/300](https://github.com/google/perfetto/issues/300)

So how do you set the thread name programmatically?

I'm looking for something like 

`SET_PERFETTO_THREAD_NAME(...)`

**Comment by LalitMaganti** [comment]
@betasheet @ddiproietto  can you help with this?

**Comment by ddiproietto** [comment]
It should be possible with `perfetto::TrackEvent::SetTrackDescriptor()`

here's an example of setting a thread's name in chromium:

https://source.chromium.org/chromium/chromium/src/+/main:base/tracing/perfetto_platform.cc;l=117-123;drc=e4622aaeccea84652488d1822c28c78b7115684f
