### ISSUE TITLE
out-of-date sde ftrace format 

### ISSUE THREAD

**Issue by severecold** [google/perfetto#352]
The format of qcom sde related tracepoints has changed two years ago, however, sde.proto in perfetto has not changed with it. This results in empty sde trace events in perfetto.

https://us.codeaurora.org/quic/femto5G/platform/vendor/opensource/display-drivers/tree/msm/sde/sde_trace.h?h=DISPLAY.LA.2.0.r1-05500-WAIPIO.0#n116

TRACE_EVENT(tracing_mark_write,
	TP_PROTO(char trace_type, const struct task_struct *task,
		const char *name, int value),
	TP_ARGS(trace_type, task, name, value),
	TP_STRUCT__entry(
			__field(char, trace_type)
			__field(int, pid)
			__string(trace_name, name)
			__field(int, value)
	),
	TP_fast_assign(
			__entry->trace_type = trace_type;
			__entry->pid = task ? task->tgid : 0;
			__assign_str(trace_name, name);
			__entry->value = value;
	),
	TP_printk("%c|%d|%s|%d", __entry->trace_type,
			__entry->pid, __get_str(trace_name), __entry->value)
)

https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/ftrace/sde.proto
message SdeTracingMarkWriteFtraceEvent {
  optional int32 pid = 1;
  optional string trace_name = 2;
  optional uint32 trace_type = 3;
  optional int32 value = 4;
  optional uint32 trace_begin = 5;
}

**Comment by LalitMaganti** [comment]
SDE events are not used by us anmore that's why the format file has not been updated. Contributions to fix this issue are welcome as it's not something we're going to get to.
