### ISSUE TITLE
Convert Perfetto UI Chrome extension to v3

### ISSUE THREAD

**Issue by ngaitonde** [google/perfetto#353]
Hi Perfetto community, would you consider publishing your extension (https://chrome.google.com/webstore/detail/perfetto-ui/lfmkphfpdbjijhpomgecfikhfohaoine/related) to the Microsoft Edge extension store? https://developer.microsoft.com/en-us/microsoft-edge/extensions/? I'd be happy to help in any way, including contributing. Thanks.

**Comment by ngaitonde** [comment]
Learned from the Edge extension team that the extension would need to be on v3: https://developer.chrome.com/docs/extensions/mv3/intro/#start-the-conversion.

**Comment by primiano** [comment]
Oh hey. I guess this is to allow edge tracing.
It makes sense to me. Can I just ask you folks to contribute with whatever code it takes to make the extension compatible with the Edge store (and still be compatible with Google's)?
Hopefully we can have the same source for both google store and Edge store.

@betasheet @skyostil @chromy FYI

**Comment by ngaitonde** [comment]
Thanks. Steps to migrate the Chrome Extension to V3 would work consistently for Chrome & Edge. V2 extensions are on a deprecation path, even with Chrome for mid-2023: https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/.

Looking at the code for the chrome-extension and the V3 migration guide, there are possibly changes needed for actions - https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/#api-browser-action-js.

**Comment by LalitMaganti** [comment]
The plugin should now be v3 as it's still in the store.
