### ISSUE TITLE
always show memory ftrace_events of linux.ftrace data_source

### ISSUE THREAD

**Issue by arthurlang** [google/perfetto#355]
I used perffeto to trace my android app by config:
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            ftrace_events: "gpu_mem/gpu_mem_total"
            ftrace_events: "mm_event/mm_event_record"
            ftrace_events: "kmem/rss_stat"
            ftrace_events: "kmem/ion_heap_grow"
            ftrace_events: "kmem/ion_heap_shrink"
            ftrace_events: "mm_event/mm_event_record"
            ftrace_events: "dmabuf_heap/dma_heap_stat"
            ftrace_events: "lowmemorykiller/lowmemory_kill"
            ftrace_events: "oom/oom_score_adj_update"
        }
    }
}

after trace many times, I delete ftrace_config,but delete invalid still show mem related ftrace_events in my trace
![image](https://user-images.githubusercontent.com/6771583/192777302-3841e1df-0ec4-4ff6-82bb-9a0c220ed7c6.png)

**Comment by arthurlang** [comment]
mac pro trace in chrome
![image](https://user-images.githubusercontent.com/6771583/192778066-8942f7ca-0e6d-4660-8dc2-fa56bc71b3af.png)

**Comment by LalitMaganti** [comment]
What does your config look like exactly? Do you also have process_stats enabled with proc_stats_poll_ms? If so, that'll be where those counters are coming from.
