### ISSUE TITLE
[Error] perfetto doesn't work with the error about TraceConfig & uid

### ISSUE THREAD

**Issue by witheunjin** [google/perfetto#358]
I got the error when I run perfetto by executing `adb shell perfetto` command.
`[914.319] perfetto_cmd.cc:506     The TraceConfig is empty`

Additionally, these are the error when I attempted to capture the system trace from the physical device.
`10-02 05:07:24.898 22554 27908 V Traceur : notify_traceur: true`
`10-02 05:07:25.003 22554 27908 V Traceur : exec: null [sh, -c, perfetto --is_detached=traceur]`
`10-02 05:07:25.026  1621  1621 E perfetto: ing_service_impl.cc:531 Failed to attach consumer, session 'traceur' not found for uid 10141`
`10-02 05:07:25.029 22554 27908 V Traceur : exec: null [sh, -c, perfetto --stop --attach=traceur]`
`10-02 05:07:25.046  1621  1621 E perfetto: ing_service_impl.cc:531 Failed to attach consumer, session 'traceur' not found for uid 10141`

Actually the perfetto worked well, but it doesn't with those errors after I removed data/local/traces directory (by using `rm -r data/local/traces`) and generated directory named `traces` (by using `mkdir traces`).

I thought there are just trace log data(*.perfetto-trace) so it will be okay to remove and re-generate the `traces` directory.
Yeah.. I know it's all my fault. I shouldn't have...

Anyway, the error says 'session tracer not found for **"uid"**.
Can this problem be solved if I set the "uid" again? Then.. how?
How about the **"TraceConfig"**? 
Can I solve this problem by just adding or editing any variables or settings or should I reset my phone to resolve this?(actually I don't want to reset it.. because my co-workers also use this device.. you know, this is quite complicated thing 😭 )
Please give some any solution, hint or anything you think it will be helpful.
I need your help deadly.

**Comment by LalitMaganti** [comment]
To fix the state of your device, please do the following:
```
adb shell rm -rf /data/misc/perfetto-traces
adb shell rm -rf /data/local/traces
adb shell setprop persist.traced.enable 0
<reboot the device>
adb shell setprop persist.traced.enable 1
<reboot the device>
```

Generally it's a good idea not to delete random directories on the device without knowing what you're doing as you'll get into a bad state.

As for collecting traces on device, please follow the instructions [here](https://perfetto.dev/docs/quickstart/android-tracing). Concretely, you're not specifying a TraceConfig when you run `adb shell perfetto`. A config needs to be provided as otherwise perfetto will not know what to trace.
