### ISSUE TITLE
How can i use `sdk` to trace event and generate full callstack sample.

### ISSUE THREAD

**Issue by elseyu** [google/perfetto#361]
I want to trace my native code in application without command line, expect to generate some method full callstack and cpu time.
Currently i use` sdk sample` to trace my method, but the result has no `callstack`,only trace event.
My question is: does `sdk` have the feature? And how?
![image](https://user-images.githubusercontent.com/17921788/195480587-109053f7-5591-4c26-a626-000166fc4c81.png)

**Comment by LalitMaganti** [comment]
If you are on Android, you can use callstack sampling as described on this page through Perfetto - https://perfetto.dev/docs/quickstart/callstack-sampling.
