### ISSUE TITLE
Thread names sometimes are not displayed

### ISSUE THREAD

**Issue by noomorph** [google/perfetto#363]
Please examine this payload on your live version of Perfetto:

[bug-report.json.txt](https://github.com/google/perfetto/files/9830668/bug-report.json.txt)

As you can see, I get an untitled `Thread 29` instead of `ipc 29` in my `primary 71556` process.

![Screen Shot 2022-10-20 at 16 49 57](https://user-images.githubusercontent.com/1962469/196967139-b26aa09c-28f9-43a5-8781-10333553535c.png)

This seems weird, because in the JSON attached I have thread 29 names for both the processes:

```diff
	{"ph":"M","args":{"name":"primary"},"ts":3150987578506433,"tid":0,"pid":71556,"name":"process_name"},
	{"ph":"M","args":{"name":"lifecycle"},"ts":3150987578507433,"tid":0,"pid":71556,"name":"thread_name"},
+	{"ph":"M","args":{"name":"ipc"},"ts":3150987578522433,"tid":29,"pid":71556,"name":"thread_name"},
...
	{"ph":"M","args":{"name":"secondary"},"ts":3150987578523433,"tid":0,"pid":71557,"name":"process_name"},
+	{"ph":"M","args":{"name":"ipc"},"ts":3150987578523433,"tid":29,"pid":71557,"name":"thread_name"},
...
```

Could you help, please?

**Comment by noomorph** [comment]
Is there a range limit for thread IDs? We generate fake thread IDs because it is JavaScript. 🤷‍♂️  I mean, is it 16-bit or 32-bit?

**Comment by LalitMaganti** [comment]
tids have to be 32-bit numbers so you have 2^32 options - this is plenty even for actual operating systems so should be sufficient for pretty much any use case you have :)

**Comment by noomorph** [comment]
@LalitMaganti, thank you for the insightful and prompt response (and the amazing tool which Perfetto is)! My question now is completely closed.
