### ISSUE TITLE
[UI] Can't open the UI in browser

### ISSUE THREAD

**Issue by Lin-Mao** [google/perfetto#364]
Hi there,
I build the perfetto UI in my WSL, but I can't open the UI via `http://localhost:10000` on windows.
I opened the UI successfully before but failed after changing the UI version (git reset to older commit). But I can't open it in any version now which is very strange to me.
I am using WSL2 and ubuntu20.04 now. I also tried ubuntu18.04 and ubuntu22.04, but it doesn't work.
I am sure perfetto has been successfully installed on WSL since `curl http://localhost:10000` can get the correct output.
I switched to WSL1, but it always prompts `Error: listen EACCES: permission denied 127.0.0.1:10000`.

I also thought the reason might be Windows can't access wsl2 via localhost, but I did it before. Also, I can access the jupyter on wsl2 via `localhost:8888`

I have no idea about this issue now, did anyone have any idea about it? I appreciate any feedback!

**Comment by Lin-Mao** [comment]
Hi @ddrone, @LalitMaganti, @chromy, and @octaviantu, could you please give me some insights to deal with this issue? Thanks so much for your time and consideration!

**Comment by LalitMaganti** [comment]
Sorry none of us use Windows or WSL for UI development so really don't have any insight to share here.

However when you say " But I can't open it in any version now which is very strange to me.", this feels like something went wrong without your specific setup so not sure we can do anything on our side.

**Comment by Lin-Mao** [comment]
Thanks so much for your response, @LalitMaganti! I originally thought it was not something related to perfetto but WSL. But I can use `localhost:8888` to access jupyter in WSL. So I am confused about it. Anyway, thanks for your feedback! I have a follow-up question, can I change the TCP port of perfetto and how can I do that?

**Comment by LalitMaganti** [comment]
You can use the `--serve-port`: [this](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/build.js;l=137?q=f:perfetto%20build.js) is the script which builds the UI so you can see the arguments there.

**Comment by Lin-Mao** [comment]
Hi @LalitMaganti, I solved this issue now. I just changed the TCP port and it works well now. I am updating it here for those who face this issue later. I guess the problem might be because windows blocked port 10000 on my machine. Thanks for your help!

**Comment by LalitMaganti** [comment]
Oohhhhhh you know what it might be: it might be Windows Defender blocking the port. I've encountered this issue in the past with SSH port forwarding in WSL. I'd check if Defender is blocking 10000 :)

**Comment by Lin-Mao** [comment]
I think so! Thanks for your sharing!
