### ISSUE TITLE
Track Events + system wide profiling example

### ISSUE THREAD

**Issue by gedalia** [google/perfetto#369]
Hello, I've been trying to use the example_system_wide as a starting point to integrating the profiler into my code base. The configuration wizard doesn't seem to show either trace or track events. And while I can get the simple track event configuration file to work (https://pastebin.com/embed_iframe/ufmtBBuq.) My attempts to get the whole system data + per process info has failed.  Can anyone enlighten me about what I'm doing wrong? Here is the config I'm using (I attempted to merge the snippet above with the gui generated one)
[trace_config.txt](https://github.com/google/perfetto/files/9864239/trace_config.txt)
Thanks

**Comment by LalitMaganti** [comment]
Some more information would be appreciated. Concretely:
1) Which platform are you looking to get this data on? Andorid? Linux? Chrome OS? Something else?
2) The config you are using: how are you passing this config to Perfetto? If on Android, I guess adb shell or record_android_trace helper script but on other platforms, you have options (e.g. tracebox, running it manually in a terminal, using the `tmux` script, using your own wrapper script etc.)

**Comment by gedalia** [comment]
1. Linux, ubuntu 18.04
2. I've been following the instructions in perfetto/examples/sdk/example_system_wide.cc
// 2). Run traced (long running process), and open another terminal tab.
// `./out/default/tracebox traced`
//
// 3). Run this file. This is main application to trace.
// `./out/default/example_system_wide`
//
// 4). Use perfetto client to start a session and record trace in a file.
// `./out/default/tracebox perfetto -c /tmp/trace_config.txt --txt
//      -o /tmp/trace_output`

**Comment by LalitMaganti** [comment]
You're missing an invocation of:
```
./out/default/tracebox traced_probes
```
which is necessary to obtain system data.

**Comment by gedalia** [comment]
thanks, I also discovered that part of the problem is that processes that are running the tracked events code are in a docker container and don't seem to hear the tracebox recording start up. Added a bit to my confusion
