### ISSUE TITLE
Content of multiple record sessions via Start Recording gets accumulated

### ISSUE THREAD

**Issue by danielfriederich** [google/perfetto#37]
When I collect multiple record sessions via Start Recording (WebUSB) the trace gets accumulated. Say I collect 10 seconds, then wait a minute and collect another 10 seconds (with possibly different settings), then the trace covers 80 seconds. And trace_to_text shows that it contains the content of both sessions. I only see this when using the socket connection (AdbSocketConsumerPort), not when using AdbConsumerPort or when collecting via command line. Is this known behavior or a bug (well or both?). This is with a custom device, but nothing customized in this area.

Was discussed on discord:
https://discord.com/channels/629013440635207702/629013441096450058/725016433481744504

The issue appears to be that we reuse the traceProtoWriter (a protobuf.Writer) in adb_socket_controller.ts, AdbSocketConsumerPort class.

**Comment by danielfriederich** [comment]
The fix proposed on discord by eseckler does fix the issue for me

  sendReadBufferResponse() {
    this.sendMessage(this.generateChunkReadResponse(
        this.traceProtoWriter.finish(), /* last */ true));
+    this.traceProtoWriter = protobuf.Writer.create();
  }

**Comment by tilal6991** [comment]
I think the above CL should fix this.
