### ISSUE TITLE
Getting catapult style json events nested within each other.

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#371]
Our profiler writes the longer scopes after the nested ones, since it's a scoped based profiler.  And occasionally we see events displayed nested inside them.   So this is an image where SkinMesh and SimMesh should be underneath the brown scope called AvatarBarn.    Note the later start time "ts" of SimMesh vs. the parent AvatarBarn.  This prevents selecting the sub events, and causes confusing when trying to read the flame chart.  It's like Perfetto periodically isn't tracking the timing stack correctly, but the profile in the same capture for the same events later on is correct.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/3750359/198408578-96c71390-ef9f-411b-ad2c-8d5fdf7a2d61.png">

This is the pink and brown bar in the json.
```
{
            "dur": 1222.31,
            "name": "SimMesh",
            "ph": "X",
            "tid": 2,
            "ts": 38538.161
        },

{
            "dur": 2490.403,
            "name": "AvatarBarn",
            "ph": "X",
            "tid": 2,
            "ts": 37747.046
        },
```

**Comment by LalitMaganti** [comment]
This should be supported - can you share a minimal trace which demonstrates the issue?

**Comment by alecazam** [comment]
I have a huge capture, but it's proprietary.  I tried splitting out the json above, and it's rendered correctly.

**Comment by alecazam** [comment]
Here's the bigger picture of that thread, but these timings shouldn't all overlap like this within a the thread, or even on their own tracks.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/3750359/198412133-b2e74f22-03ec-4883-a82a-6eefa2f6b559.png">

**Comment by alecazam** [comment]
Okay, so looks like the AvatarBarn scopes do overlap, but that's how they are in the file. Maybe we're looking up the wrong thread id, since there is no work on the job thread below this one.  Still might be something you could flag during parsing.

```
{
    "displayTimeUnit": "ms",
    "traceEvents": [

        {
            "args": {
                "name": "Job2"
            },
            "name": "thread_name",
            "ph": "M",
            "tid": 2
        },

{
            "dur": 1.473,
            "name": "AvatarBarn",
            "ph": "X",
            "tid": 2,
            "ts": 37743.714
        },


{
            "dur": 18.973,
            "name": "AvatarBarn",
            "ph": "X",
            "tid": 2,
            "ts": 37742.281
        },

{
            "dur": 63.476,
            "name": "AvatarBarn",
            "ph": "X",
            "tid": 2,
            "ts": 37762.248
        },

{
            "dur": 2490.403,
            "name": "AvatarBarn",
            "ph": "X",
            "tid": 2,
            "ts": 37747.046
        },

}
```

**Comment by alecazam** [comment]
There's no affinity control on macOS or iOS, so maybe the task scheduler is moving this work to another core before/after we record the timing.

**Comment by alecazam** [comment]
We had two different tracing system recording timings with the same names and overlapping times.  So I think I fixed that by renaming one of them.   This may be a case where the event start timings aren't always within the scope of the part.

**Comment by alecazam** [comment]
There are just too many weird cases like this.  Where we buffer scope with a threadID, and then write these out en-masse, but they end up overlapping.  So I have buffering like this disabled.

<img width="233" alt="image" src="https://user-images.githubusercontent.com/3750359/198425635-30b48a2c-a153-4038-a12a-63171604012d.png">

**Comment by LalitMaganti** [comment]
Sorry this is a data producer problem at this point not a trace processor or UI problem. The JSON spec [1] is very clear that B/E/X events cannot have overlaps only nesting.

You need to use async events (b/e) if you want to allow overlapping to happen.

[1] https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview
