### ISSUE TITLE
Help Needed to mock trackers belongs to two different processes using perfetto sdk.

### ISSUE THREAD

**Issue by horusli** [google/perfetto#372]
Hi, Is there any way to mock trace event into trackers that belongs to two different processes using perfetto sdk.

I try to do this by chaing the pid in TrackDescriptor, yet the trackers in the DrawGame2 function call always fails to show up.
Is there other steps needed also, thanks in advance.

  InitializePerfetto();
  auto tracing_session = StartTracing();

  perfetto::ProcessTrack process_track = perfetto::ProcessTrack::Current();
  perfetto::protos::gen::TrackDescriptor desc = process_track.Serialize();
  desc.mutable_process()->set_process_name("rendering");
  PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
  perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);
  DrawGame();

  perfetto::ProcessTrack process_track = perfetto::ProcessTrack::Current();
  perfetto::protos::gen::TrackDescriptor desc = process_track.Serialize();
  desc.mutable_process()->set_process_name("bining");
  desc.mutable_process()->set_pid(1);
  PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
  perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);
  DrawGame2();

  StopTracing(std::move(tracing_session));

**Comment by LalitMaganti** [comment]
@ddiproietto can you advise?

**Comment by LalitMaganti** [comment]
Can you share a trace which is being generated with this code so we can look into this further?

**Comment by horusli** [comment]
> Can you share a trace which is being generated with this code so we can look into this further?

sure, please check trace and code attached.

![image](https://user-images.githubusercontent.com/6522657/199257277-f8fd2373-881c-4242-89ee-6cbe17c88eda.png)


`
  void DrawPlayer2(int uuid, int player_number) {
    TRACE_EVENT("rendering", "DrawPlayer_rendering", perfetto::Track(uuid), "player_number", player_number);
    // Sleep to simulate a long computation.
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
  }

  void DrawGame2() {
    int uuid=11000;
    // This is an example of an unscoped slice, which begins and ends at specific
    // points (instead of at the end of the current block scope).
    TRACE_EVENT_BEGIN("rendering", "DrawGame_rendering",perfetto::Track(uuid));
    DrawPlayer2(uuid, 3);
    DrawPlayer2(uuid, 4);
    TRACE_EVENT_END("rendering",perfetto::Track(uuid));

    // Record the rendering framerate as a counter sample.
    TRACE_COUNTER("rendering", "Framerate", 120);
    TRACE_COUNTER("rendering", "test1_rendering", 120);
    TRACE_COUNTER("rendering", "test2_rendering", 120);
  }


  void DrawPlayer1(int uuid, int player_number) {
    TRACE_EVENT("binning", "DrawPlayer_binning", perfetto::Track(uuid), "player_number", player_number);
    // Sleep to simulate a long computation.
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
  }

  void DrawGame1() {
    int uuid =10000;
    // This is an example of an unscoped slice, which begins and ends at specific
    // points (instead of at the end of the current block scope).
    TRACE_EVENT_BEGIN("binning", "DrawGame_binning",perfetto::Track(uuid));
    DrawPlayer1(uuid, 1);
    DrawPlayer1(uuid, 2);
    TRACE_EVENT_END("binning",perfetto::Track(uuid));

    // Record the rendering framerate as a counter sample.
    TRACE_COUNTER("binning", "Framerate", 120);
    TRACE_COUNTER("binning", "test1_binning", 120);
    TRACE_COUNTER("binning", "test2_binning", 120);
  }

int main(int, const char**) {
  InitializePerfetto();
  auto tracing_session = StartTracing();

  int j, status;
  pid_t child_pid;
  child_pid = fork(); // Create a new child process;
  if (child_pid < 0) {
    PERFETTO_LOG("fork failed");
    return 1;
  } else if (child_pid == 0) {
      PERFETTO_LOG ("child process successfully created!");
      PERFETTO_LOG ("child_PID = %d,parent_PID = %d", getpid(), getppid());
      perfetto::ProcessTrack process_track = perfetto::ProcessTrack::Current();
      perfetto::protos::gen::TrackDescriptor desc = process_track.Serialize();
      desc.mutable_process()->set_process_name("compute");
      PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
      desc.mutable_process()->set_pid(getppid());
      perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);
      DrawGame1();
      exit(EXIT_SUCCESS);
  } else {
    j = wait(&status);
    PERFETTO_LOG ("parent process successfully created!");
    PERFETTO_LOG ("child_PID = %d, parent_PID = %d", getpid(), getppid());
    perfetto::ProcessTrack process_track = perfetto::ProcessTrack::Current();
    perfetto::protos::gen::TrackDescriptor desc = process_track.Serialize();
    desc.mutable_process()->set_process_name("rendering");
    PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
    perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);
    DrawGame2();
  }
  StopTracing(std::move(tracing_session));
  return 0;
}`


`[406.493]       perfetto.cc:59055 Configured tracing session 1, #sources:1, duration:0 ms, #buffers:1, total buffer size:1024 KB, total sessions:1, uid:0 session name: ""
[406.494]         multicat.cc:142 child process successfully created!
[406.494]         multicat.cc:143 child_PID = 4170,parent_PID = 4168
[406.494]         multicat.cc:149 pid: 4170
[407.496]         multicat.cc:156 parent process successfully created!
[407.496]         multicat.cc:157 child_PID = 4168, parent_PID = 16962
[407.496]         multicat.cc:161 pid: 4168
[408.499]          multicat.cc:84 Trace written in mulicat.pftrace file. To read this trace in text form, run `./tools/traceconv text mulicat.pftrace`
`

**Comment by horusli** [comment]
[mulicat.zip](https://github.com/google/perfetto/files/9910949/mulicat.zip)

here is the trace file generated

**Comment by LalitMaganti** [comment]
Oh hang on: you're forking and running two processes starting from the same binary. So when you're using the SDK, are you using the in-process backend or the system backend? If you're using the in-process backend, things cannot possibly work because each process would talk to its own copy of the SDK.

Even otherwise, the Perfetto SDK creates a new thread when you initialize it (correct me if I'm wrong @ddiproietto) and forking after you start a thread is not going to be pretty.

**Comment by horusli** [comment]
> 

Yes I am using the in-process backend. so you are suggesting to use system backend if using multi-threads in the application and initialize perfetto tracing for each individual threads? 

Let go back to our initial issue of creating multiple processing track and grouping some tracks in each of them.
below is what I try to do inside one process by changing the pid of the process, but it doesn't work as expected.

![image](https://user-images.githubusercontent.com/6522657/199629647-d5ee0452-0570-4b16-9b8e-4b5ec26ab026.png)
[example.zip](https://github.com/google/perfetto/files/9925035/example.zip)

`
  void DrawPlayer(int player_number) {
    TRACE_EVENT("rendering", "DrawPlayer", "player_number", player_number);
    // Sleep to simulate a long computation.
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
  }
    
  void DrawGame() {
    // This is an example of an unscoped slice, which begins and ends at specific
    // points (instead of at the end of the current block scope).
    TRACE_EVENT_BEGIN("rendering", "DrawGame");
    DrawPlayer(1);
    TRACE_EVENT_END("rendering");
  
    // Record the rendering framerate as a counter sample.
    TRACE_COUNTER("rendering", "Framerate", 120);
  }
  
  void DrawPlayer1(int player_number) {
    TRACE_EVENT("binning", "DrawPlayer1", "player_number", player_number);
    // Sleep to simulate a long computation.
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
  }
  
  void DrawGame1() {
    // This is an example of an unscoped slice, which begins and ends at specific
    // points (instead of at the end of the current block scope).
    TRACE_EVENT_BEGIN("binning", "DrawGame1");
    DrawPlayer1(2);
    TRACE_EVENT_END("binning");
  
    // Record the rendering framerate as a counter sample.
    TRACE_COUNTER("binning", "Framerate", 120);
  }
  
  int main(int, const char**) {
    InitializePerfetto();
    auto tracing_session = StartTracing();
  
    // Give a custom name for the traced process.
    perfetto::ProcessTrack process_track = perfetto::ProcessTrack::Current();
    perfetto::protos::gen::TrackDescriptor desc = process_track.Serialize();
    desc.mutable_process()->set_process_name("rendering");
    PERFETTO_LOG("Original Process:");
    PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
    PERFETTO_LOG("uuid: %d",desc.uuid());
    perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);
  
    // Simulate some work that emits trace events.
    DrawGame();
  
    perfetto::ProcessTrack process_track1 = perfetto::ProcessTrack::Current();
    perfetto::protos::gen::TrackDescriptor desc1 = process_track1.Serialize();
    desc1.mutable_process()->set_pid(1000);
    desc1.mutable_process()->set_process_name("binning");
    PERFETTO_LOG("Switched Process:");
    PERFETTO_LOG("pid: %d",desc1.mutable_process()->pid());
    PERFETTO_LOG("uuid: %d",desc1.uuid());
    perfetto::TrackEvent::SetTrackDescriptor(process_track1, desc1);
    // Simulate some work that emits trace events.
    DrawGame1();
    StopTracing(std::move(tracing_session));
    return 0;
  }
`

**Comment by LalitMaganti** [comment]
You need to pass a `perfetto::ProcessTrack::CurrentTrack()` to `TRACE_EVENT_BEGIN` and `TRACE_EVENT_END` macros. By default TRACE_EVENTs are associated with threads not processes.

See https://cs.android.com/android/platform/superproject/+/master:external/perfetto/include/perfetto/tracing/track.h for info on this.

**Comment by horusli** [comment]
``> You need to pass a `perfetto::ProcessTrack::CurrentTrack()` to `TRACE_EVENT_BEGIN` and `TRACE_EVENT_END` macros. By default TRACE_EVENTs are associated with threads not processes.
> 
> See https://cs.android.com/android/platform/superproject/+/master:external/perfetto/include/perfetto/tracing/track.h for info on this.

Sorry to raise the issue again, yes the processtrack is ignore in previous try, I give another try to specific the processtrack in the TRACE_EVENT_BEGIN/TRACE_EVENT_END macro, below is what I got.

![image](https://user-images.githubusercontent.com/6522657/199939248-ad8d2863-5adf-4cd7-8946-902a43050e2a.png)
[example.zip](https://github.com/google/perfetto/files/9936859/example.zip)

code as below:

`
    InitializePerfetto();
    auto tracing_session = StartTracing();
  
    // Simulate some work that emits trace events
    perfetto::ProcessTrack process_track = perfetto::ProcessTrack::Current();
    perfetto::protos::gen::TrackDescriptor desc = process_track.Serialize();
    desc.mutable_process()->set_process_name("rendering");
    PERFETTO_LOG("Original Process:");
    PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
    PERFETTO_LOG("uuid: %ld",desc.uuid());
    PERFETTO_LOG("parent_uuid: %d",desc.parent_uuid());
    perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);
    TRACE_EVENT_BEGIN("rendering", "DrawGame",process_track);
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
    TRACE_EVENT_END("rendering",process_track);
  
    desc.mutable_process()->set_process_name("binning");
    desc.mutable_process()->set_pid(desc.mutable_process()->pid()+1);
    //desc.set_parent_uuid(desc.parent_uuid()+1);
    desc.set_uuid(desc.uuid()+1);
    PERFETTO_LOG("Swithed Process:");
    PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
    PERFETTO_LOG("uuid: %ld",desc.uuid());
    PERFETTO_LOG("parent_uuid: %d",desc.parent_uuid());
    perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);
    TRACE_EVENT_BEGIN("binning", "DrawGame1",process_track);
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
    TRACE_EVENT_END("binning",process_track);
  
    desc.mutable_process()->set_process_name("compute");
    desc.mutable_process()->set_pid(desc.mutable_process()->pid()+1);
    //desc.set_parent_uuid(desc.parent_uuid()+1);
    desc.set_uuid(desc.uuid()+1);
    PERFETTO_LOG("Swithed Process:");
    PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
    PERFETTO_LOG("uuid: %ld",desc.uuid());
    PERFETTO_LOG("parent_uuid: %d",desc.parent_uuid());
    perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);
    TRACE_EVENT_BEGIN("compute", "DrawGame2",process_track);
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
    TRACE_EVENT_END("compute",process_track);
    StopTracing(std::move(tracing_session));
`

Log:

[071.177]          example.cc:188 Original Process:
[071.177]          example.cc:189 pid: 24370
[071.177]          example.cc:190 uuid: -6305056687177965657
[071.177]          example.cc:191 parent_uuid: 0

[071.677]          example.cc:201 Swithed Process:
[071.677]          example.cc:202 pid: 24371
[071.677]          example.cc:203 uuid: -6305056687177965656
[071.677]          example.cc:204 parent_uuid: 0

[072.178]          example.cc:214 Swithed Process:
[072.178]          example.cc:215 pid: 24372
[072.178]          example.cc:216 uuid: -6305056687177965655
[072.178]          example.cc:217 parent_uuid: 0

**Comment by ddiproietto** [comment]
So, ProcessTrack and ThreadTrack are really convenience classes to use the real thread and process, to do what you're doing, you really need to go one level below and manually understand and handle track uuids, (which is not very pleasant, since the rest of the code is optimized to understand real threads and processes)

In your example:

```
void DrawPlayer(int player_number) {
  TRACE_EVENT("rendering", "DrawPlayer", "player_number", player_number);
  // Sleep to simulate a long computation.
  std::this_thread::sleep_for(std::chrono::milliseconds(500));
}

void DrawGame() {
  // This is an example of an unscoped slice, which begins and ends at specific
  // points (instead of at the end of the current block scope).
  TRACE_EVENT_BEGIN("rendering", "DrawGame");
  DrawPlayer(1);
  TRACE_EVENT_END("rendering");

  // Record the rendering framerate as a counter sample.
  TRACE_COUNTER("rendering", "Framerate", 120);
}

void DrawPlayer1(int player_number) {
  TRACE_EVENT("binning", "DrawPlayer1", "player_number", player_number);
  // Sleep to simulate a long computation.
  std::this_thread::sleep_for(std::chrono::milliseconds(500));
}

void DrawGame1() {
  // This is an example of an unscoped slice, which begins and ends at specific
  // points (instead of at the end of the current block scope).
  TRACE_EVENT_BEGIN("binning", "DrawGame1");
  DrawPlayer1(2);
  TRACE_EVENT_END("binning");

  // Record the rendering framerate as a counter sample.
  TRACE_COUNTER("binning", "Framerate", 120);
}

int main(int, const char**) {
  InitializePerfetto();
  auto tracing_session = StartTracing();

  // Give a custom name for the traced process.
  perfetto::ProcessTrack process_track = perfetto::ProcessTrack::Current();
  perfetto::protos::gen::TrackDescriptor desc = process_track.Serialize();
  desc.mutable_process()->set_process_name("rendering");
  PERFETTO_LOG("Original Process:");
  PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
  PERFETTO_LOG("uuid: %d",desc.uuid());
  perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);

  // Simulate some work that emits trace events.
  DrawGame();

  perfetto::ProcessTrack process_track1 = perfetto::ProcessTrack::Current();
  perfetto::protos::gen::TrackDescriptor desc1 = process_track1.Serialize();
  desc1.mutable_process()->set_pid(1000);
  desc1.mutable_process()->set_process_name("binning");
  PERFETTO_LOG("Switched Process:");
  PERFETTO_LOG("pid: %d",desc1.mutable_process()->pid());
  PERFETTO_LOG("uuid: %d",desc1.uuid());
  perfetto::TrackEvent::SetTrackDescriptor(process_track1, desc1);
  // Simulate some work that emits trace events.
  DrawGame1();
  StopTracing(std::move(tracing_session));
  return 0;
}
```

Tracks are really identified by a uuid. Here you're using SetTrackDescriptor() twice with the same uuid. Since both descriptors share the same uuid, the UI considers them the same track (and picks the first descriptor)

In your last example:

```
TRACE_EVENT_BEGIN("compute", "DrawGame2",perfetto::Track(4000,perfetto::ProcessTrack::Current()));
```

These lines are really asking to create a new track under the current real process.

Here's an example (based on the last one you posted) that synthetizes process tracks and emits events from them:

```
  // Give a custom name for the traced process.
  perfetto::ProcessTrack process_track = perfetto::ProcessTrack::Current();
  perfetto::protos::gen::TrackDescriptor desc = process_track.Serialize();
  desc.mutable_process()->set_process_name("rendering");
  PERFETTO_LOG("Original Process:");
  PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
  PERFETTO_LOG("uuid: %ld",desc.uuid());
  PERFETTO_LOG("parent_uuid: %lu",desc.parent_uuid());
  perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);
  TRACE_EVENT_BEGIN("rendering", "DrawGame", process_track);
  std::this_thread::sleep_for(std::chrono::milliseconds(500));
  TRACE_EVENT_END("rendering",process_track);

  perfetto::Track process_track2 = perfetto::Track::Global(process_track.uuid + 1);
  perfetto::protos::gen::TrackDescriptor desc2 = process_track2.Serialize();
  desc2.mutable_process()->set_process_name("binning");
  desc2.mutable_process()->set_pid(desc.mutable_process()->pid()+1);
  PERFETTO_LOG("Swithed Process:");
  PERFETTO_LOG("pid: %d",desc2.mutable_process()->pid());
  PERFETTO_LOG("uuid: %ld",desc2.uuid());
  PERFETTO_LOG("parent_uuid: %lu",desc2.parent_uuid());
  perfetto::TrackEvent::SetTrackDescriptor(process_track2, desc2);
  TRACE_EVENT_BEGIN("binning", "DrawGame1", process_track2);
  std::this_thread::sleep_for(std::chrono::milliseconds(500));
  TRACE_EVENT_END("binning", process_track2);

  perfetto::Track process_track3 = perfetto::Track::Global(process_track.uuid + 2);
  perfetto::protos::gen::TrackDescriptor desc3 = process_track3.Serialize();
  desc3.mutable_process()->set_process_name("compute");
  desc3.mutable_process()->set_pid(desc.mutable_process()->pid()+2);
  PERFETTO_LOG("Swithed Process:");
  PERFETTO_LOG("pid: %d",desc3.mutable_process()->pid());
  PERFETTO_LOG("uuid: %ld",desc3.uuid());
  PERFETTO_LOG("parent_uuid: %lu",desc3.parent_uuid());
  perfetto::TrackEvent::SetTrackDescriptor(process_track3, desc3);
  TRACE_EVENT_BEGIN("compute", "DrawGame2",process_track3);
  std::this_thread::sleep_for(std::chrono::milliseconds(500));
  TRACE_EVENT_END("compute",process_track3);
```

**Comment by horusli** [comment]
> So, ProcessTrack and ThreadTrack are really convenience classes to use the real thread and process, to do what you're doing, you really need to go one level below and manually understand and handle track uuids, (which is not very pleasant, since the rest of the code is optimized to understand real threads and processes)
> 
> In your example:
> 
> ```
> void DrawPlayer(int player_number) {
>   TRACE_EVENT("rendering", "DrawPlayer", "player_number", player_number);
>   // Sleep to simulate a long computation.
>   std::this_thread::sleep_for(std::chrono::milliseconds(500));
> }
> 
> void DrawGame() {
>   // This is an example of an unscoped slice, which begins and ends at specific
>   // points (instead of at the end of the current block scope).
>   TRACE_EVENT_BEGIN("rendering", "DrawGame");
>   DrawPlayer(1);
>   TRACE_EVENT_END("rendering");
> 
>   // Record the rendering framerate as a counter sample.
>   TRACE_COUNTER("rendering", "Framerate", 120);
> }
> 
> void DrawPlayer1(int player_number) {
>   TRACE_EVENT("binning", "DrawPlayer1", "player_number", player_number);
>   // Sleep to simulate a long computation.
>   std::this_thread::sleep_for(std::chrono::milliseconds(500));
> }
> 
> void DrawGame1() {
>   // This is an example of an unscoped slice, which begins and ends at specific
>   // points (instead of at the end of the current block scope).
>   TRACE_EVENT_BEGIN("binning", "DrawGame1");
>   DrawPlayer1(2);
>   TRACE_EVENT_END("binning");
> 
>   // Record the rendering framerate as a counter sample.
>   TRACE_COUNTER("binning", "Framerate", 120);
> }
> 
> int main(int, const char**) {
>   InitializePerfetto();
>   auto tracing_session = StartTracing();
> 
>   // Give a custom name for the traced process.
>   perfetto::ProcessTrack process_track = perfetto::ProcessTrack::Current();
>   perfetto::protos::gen::TrackDescriptor desc = process_track.Serialize();
>   desc.mutable_process()->set_process_name("rendering");
>   PERFETTO_LOG("Original Process:");
>   PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
>   PERFETTO_LOG("uuid: %d",desc.uuid());
>   perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);
> 
>   // Simulate some work that emits trace events.
>   DrawGame();
> 
>   perfetto::ProcessTrack process_track1 = perfetto::ProcessTrack::Current();
>   perfetto::protos::gen::TrackDescriptor desc1 = process_track1.Serialize();
>   desc1.mutable_process()->set_pid(1000);
>   desc1.mutable_process()->set_process_name("binning");
>   PERFETTO_LOG("Switched Process:");
>   PERFETTO_LOG("pid: %d",desc1.mutable_process()->pid());
>   PERFETTO_LOG("uuid: %d",desc1.uuid());
>   perfetto::TrackEvent::SetTrackDescriptor(process_track1, desc1);
>   // Simulate some work that emits trace events.
>   DrawGame1();
>   StopTracing(std::move(tracing_session));
>   return 0;
> }
> ```
> 
> Tracks are really identified by a uuid. Here you're using SetTrackDescriptor() twice with the same uuid. Since both descriptors share the same uuid, the UI considers them the same track (and picks the first descriptor)
> 
> In your last example:
> 
> ```
> TRACE_EVENT_BEGIN("compute", "DrawGame2",perfetto::Track(4000,perfetto::ProcessTrack::Current()));
> ```
> 
> These lines are really asking to create a new track under the current real process.
> 
> Here's an example (based on the last one you posted) that synthetizes process tracks and emits events from them:
> 
> ```
>   // Give a custom name for the traced process.
>   perfetto::ProcessTrack process_track = perfetto::ProcessTrack::Current();
>   perfetto::protos::gen::TrackDescriptor desc = process_track.Serialize();
>   desc.mutable_process()->set_process_name("rendering");
>   PERFETTO_LOG("Original Process:");
>   PERFETTO_LOG("pid: %d",desc.mutable_process()->pid());
>   PERFETTO_LOG("uuid: %ld",desc.uuid());
>   PERFETTO_LOG("parent_uuid: %lu",desc.parent_uuid());
>   perfetto::TrackEvent::SetTrackDescriptor(process_track, desc);
>   TRACE_EVENT_BEGIN("rendering", "DrawGame", process_track);
>   std::this_thread::sleep_for(std::chrono::milliseconds(500));
>   TRACE_EVENT_END("rendering",process_track);
> 
>   perfetto::Track process_track2 = perfetto::Track::Global(process_track.uuid + 1);
>   perfetto::protos::gen::TrackDescriptor desc2 = process_track2.Serialize();
>   desc2.mutable_process()->set_process_name("binning");
>   desc2.mutable_process()->set_pid(desc.mutable_process()->pid()+1);
>   PERFETTO_LOG("Swithed Process:");
>   PERFETTO_LOG("pid: %d",desc2.mutable_process()->pid());
>   PERFETTO_LOG("uuid: %ld",desc2.uuid());
>   PERFETTO_LOG("parent_uuid: %lu",desc2.parent_uuid());
>   perfetto::TrackEvent::SetTrackDescriptor(process_track2, desc2);
>   TRACE_EVENT_BEGIN("binning", "DrawGame1", process_track2);
>   std::this_thread::sleep_for(std::chrono::milliseconds(500));
>   TRACE_EVENT_END("binning", process_track2);
> 
>   perfetto::Track process_track3 = perfetto::Track::Global(process_track.uuid + 2);
>   perfetto::protos::gen::TrackDescriptor desc3 = process_track3.Serialize();
>   desc3.mutable_process()->set_process_name("compute");
>   desc3.mutable_process()->set_pid(desc.mutable_process()->pid()+2);
>   PERFETTO_LOG("Swithed Process:");
>   PERFETTO_LOG("pid: %d",desc3.mutable_process()->pid());
>   PERFETTO_LOG("uuid: %ld",desc3.uuid());
>   PERFETTO_LOG("parent_uuid: %lu",desc3.parent_uuid());
>   perfetto::TrackEvent::SetTrackDescriptor(process_track3, desc3);
>   TRACE_EVENT_BEGIN("compute", "DrawGame2",process_track3);
>   std::this_thread::sleep_for(std::chrono::milliseconds(500));
>   TRACE_EVENT_END("compute",process_track3);
> ```

thank you for the promote reply.  it really works!
