### ISSUE TITLE
customize perfetto to read specific field of statm

### ISSUE THREAD

**Issue by wjj1928** [google/perfetto#374]
I would like to customize perfetto to read the second field of statm of all process, say system_server as below I want get value 28051, and draw graph with some interval.

adb shell cat /proc/$\(pidof system_server\)/statm
400801 28051 20156 6 0 202262 0

How can I do it?

**Comment by LalitMaganti** [comment]
You probably want to modify [1] to add polling for this. We're not going to be able to do it ourselves but contributions welcome.

[1] https://github.com/google/perfetto/blob/master/src/traced/probes/ps/process_stats_data_source.cc

**Comment by wjj1928** [comment]
Good, I read the code, and saw the value I want already saved in  cached.vm_rss_kb, so now I need to view  view this value in graphic view from the UI.

      } else if (strcmp(key.data(), "VmRSS") == 0) {
        auto counter = ToU32(value.data());
        if (counter != cached.vm_rss_kb) {
          GetOrCreateStatsProcess(pid)->set_vm_rss_kb(counter);
          cached.vm_rss_kb = counter;
        }

Maybe need some config to show that?

**Comment by LalitMaganti** [comment]
Documentation available here: https://perfetto.dev/docs/data-sources/memory-counters
