### ISSUE TITLE
Some thread's state is blank

### ISSUE THREAD

**Issue by hedehua** [google/perfetto#380]
![image](https://user-images.githubusercontent.com/7542900/200782882-4048327a-4cc1-4670-b5ca-c2183aa183a7.png)
as the picture shows, some thread states is blank,  anybody can help me?

**Comment by chromy** [comment]
Please share the whole trace so we can help you.

Is there data loss in the trace?

Thanks!

**Comment by hedehua** [comment]
[sgame_2022-11-09-20-40-15.zip](https://github.com/google/perfetto/files/9971163/sgame_2022-11-09-20-40-15.zip)
thanks for you reply @chromy

**Comment by LalitMaganti** [comment]
I believe this is WAI. Blank areas are actually just very close to white and represent the time the application is in interruptible sleep. We don't color those times because they would just dominate most processes and make the UI feel much more cluttered.

**Comment by hedehua** [comment]
@LalitMaganti well, 'Uninterruptible Sleep' is colored now, so 'interruptible sleep' is not colored may make developers confused. any way, thanks for you time.
