### ISSUE TITLE
Usages of sprintf cause build failures on Mac

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#381]
I'm currently seeing build failures on Mac. looks like Apple marked sprintf as deprecated, causing build failures:

```
../../src/kallsyms/kernel_symbol_map_unittest.cc:147:5: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
    sprintf(line, "%" PRIx64 " t %s\n", addr, sym_name);
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
```

how to reproduce:
1. git clone "https://android.googlesource.com/platform/external/perfetto"
2. cd perfetto
3. ./tools/install-build-deps
4. ./tools/setup_all_configs.py
5. ./tools/ninja -C out/mac_debug

Reproduced using Mac OS 12.6.1, MacOS SDK 13.0, clang/clang++ 14.0.0

**Comment by cphlipot1** [comment]
I currently see 23 usages of sprintf in the codebase. Unless there is an issue with my setup, to get the build working again I believe these sptrintf usages either need to be removed/migrated or we need to remove either -Werror or -Wdeprecated-declarations

If the choice is to move away from sprintf, most can safely be moved to snprintf, but care should be taken when the return value is used. for those cases SprintfTrunc from base/string_utils.h may be a better fit.

**Comment by primiano** [comment]
Note: I am addressing this in https://android-review.git.corp.google.com/c/platform/external/perfetto/+/2320549 as it became a problem for chromium as well. Should be fixed soon

**Comment by cphlipot1** [comment]
Thanks for the fix! Build issues appear to be resolved after that commit, so closing this issue.
