### ISSUE TITLE
[Feature Request] tracker highlighting when mouse move over

### ISSUE THREAD

**Issue by horusli** [google/perfetto#382]
Hi Perfetto Team,

Is it possible to add feature support for tracker hightlighting  when mouse floating on it so we can easily distinguish its names from adjacent ones, this will be very useful when we put many trackers together for analysis.

**Comment by primiano** [comment]
Can you expand a bit more. There are various part of the UI I am not 100% sure which one you are talking abut.
Maybe an annotated screenshot would help

**Comment by horusli** [comment]
> 
Maybe a little example will put it more clear.
when user moving mouse over the tracker panel, the corresponding tracker area is highlighted, so that one can easily identify the tracker with the name on the left most.
similiar effect plrease refer in below link(horiztontal highlight).

http://www.webkaka.com/tutorial/html/2020/021970/Table_Highlight_Vertical_Horizontal/

**Comment by LalitMaganti** [comment]
I think we now display slice names on hover which I believe fixes this issue in a slightly different way.
