### ISSUE TITLE
[Feature] Add ftrace capture support for trace_printk() messages

### ISSUE THREAD

**Issue by ciband** [google/perfetto#385]
If this feature doesn't already exist (I could not find it), it would be nice to be able to capture the trace_printk messages that can be pulled from /sys/kernel/debug/tracing/trace_pipe.  Using the current ftrace_events: "ftrace/print" feature does not seem to capture this data.

**Comment by LalitMaganti** [comment]
You can capture trace_printk with "ftrace/bprint" ftrace event.
