### ISSUE TITLE
ovelapped time slices on the same tracker not palced as expected

### ISSUE THREAD

**Issue by horusli** [google/perfetto#386]
Hi, 

I intend to draw some slices on the same tracker with ovelapped happened between them, but the result seems not within expectation.

tested with some simple code to reproduce the issue:

two slices with one start at a given timestamp and lasting 300ns, and the other one start 100ns later after the same given timestamp and also lasting 300ns. the expectation is that the seond slice should end later than the first one since they are with the same time duration and it start 100ns later.

`    uint64_t timestamp = perfetto::TrackEvent::GetTraceTimeNs();
    TRACE_EVENT("binning", "DrawPlayer6", tracker1, timestamp, "player_number",
                11);
    TRACE_EVENT_END("binning", tracker1, timestamp + 300000);

    TRACE_EVENT("binning", "DrawPlayer7", tracker1, timestamp + 100000,
                "player_number", 12);
    TRACE_EVENT_END("binning", tracker1, timestamp + 400000);`

from perfetto output, the first slice lasting 400ns and the second one only 200ns, and the second one ends earlier.
![image](https://user-images.githubusercontent.com/6522657/202227087-c4adc529-5a6a-4617-a567-2bb04c4eae20.png)

not sure whether it is a bug or not, but the output is certainly not as expected, please help to take a look?

**Comment by LalitMaganti** [comment]
Tracks cannot have events which overlap with each other: only nest. Please see perfetto::Track header [1] for how to emit events which overlap with each other. As long as tracks are named the same, the UI will coalesce them into a single horizontal timeline.

[1] https://cs.android.com/android/platform/superproject/+/master:external/perfetto/include/perfetto/tracing/track.h;l=60?q=f:track.h%20
