### ISSUE TITLE
Add support for posting CPU stack frames in the Chrome Trace Format

### ISSUE THREAD

**Issue by kenzieschmoll** [google/perfetto#387]
When loading a trace via postMessage, you can load the "traceEvents" and the "stackFrames":
```
{
  "traceEvents: [...],
  "stackFrames: [...],
}
```

However, in the Perfetto UI, the CPU samples do not show up.

**Comment by LalitMaganti** [comment]
Sorry the JSON trace format is supported on a best effort basis and there's never been a need to support importing these. Feel free to send CLs adding support for this but this is not going to be something we can do ourselves.
