### ISSUE TITLE
[Feature Request]Unit name to show up on CounterTrack

### ISSUE THREAD

**Issue by horusli** [google/perfetto#388]
Hi,

In perfetto there is api to set unit name for CounterTrack, is it possible to annotate it on the left most side of the tracker?
I saw in android trace, the annotation seems already there.
![image](https://user-images.githubusercontent.com/6522657/202883172-4cbdbf4d-a9ab-4f2b-b8f0-234a8a3119ff.png)

but local try do not found the '%' unit name set in code(please correct me if there is something I missed to make it work)
![image](https://user-images.githubusercontent.com/6522657/202883337-29a8d144-7335-4cf0-a542-9aaa2b5ad19f.png)
![image](https://user-images.githubusercontent.com/6522657/202884811-a5c26416-e061-4a11-a6d3-b83e55e6fd6c.png)

it would make perfetto close to perfect if we are able to have this  display on the tracker panel.

**Comment by LalitMaganti** [comment]
This should be fixed when https://r.android.com/3380352 lands.
