### ISSUE TITLE
dynamic Category report compiler time error when using  with TRACE_EVENT

### ISSUE THREAD

**Issue by horusli** [google/perfetto#389]
Hi,

In Perfetto, there is some note on Dynamic Category and its usage.

Ideally all trace categories should be defined at compile time as shown above, as this ensures trace points will have minimal runtime and binary size overhead. However, in some cases trace categories can only be determined at runtime (e.g., they come from instrumentation in a dynamically loaded JavaScript running in a WebView or in a NodeJS engine). These can be used by trace points as follows:

perfetto::DynamicCategory dynamic_category{"nodejs.something"};
TRACE_EVENT(dynamic_category, "SomeEvent", ...);

yet local try show that the dynamic category seems only works for TRACE_EVENT_INSTANT, when apply to TRACE_EVENT, it will report compiler time error as below:

error: use of local variable with automatic storage from containing function
  936 |                                 TRACE_EVENT(dyn_category, "test", curr_tracker1, timestamp);
      |                                             ^~~~~~~~~~~~
‘perfetto::DynamicCategory dyn_category’ declared here
  932 |                                 perfetto::DynamicCategory dyn_category{new_category};

`                                perfetto::DynamicCategory dyn_category{new_category};
                                 //works with dynamic category.
                                 TRACE_EVENT_INSTANT(dyn_category, tracker_name,
                                                    curr_tracker1, timestamp);
                                //not working, compiler report errors
                                TRACE_EVENT(dyn_category, "test", curr_tracker1, timestamp);
                                TRACE_EVENT_END(dyn_category, curr_tracker1, timestamp + 1000);`

Is this a known issue？

**Comment by LalitMaganti** [comment]
@ddiproietto seems like an SDK bug.
