### ISSUE TITLE
Add documentation for TRACE_EVENT_BEGIN/END

### ISSUE THREAD

**Issue by Nathan-Huckleberry** [google/perfetto#39]
The App Instrumentation docs use `TRACE_EVENT_BEGIN`/`TRACE_EVENT_END` in a code block without describing what they do.

The behavior of these macros should probably be explicitly documented as they are fairly useful.

**Comment by skyostil** [comment]
Sure thing :) Fixed with https://android-review.googlesource.com/c/platform/external/perfetto/+/1350103
