### ISSUE TITLE
Opening JSON trace files displays a warning every time

### ISSUE THREAD

**Issue by csmulhern** [google/perfetto#391]
This is quite a nuisance when repeatedly working with files of this format. It would be better to not show the warning repeatedly.

Reference:

<img width="738" alt="Screenshot 2022-11-27 at 11 50 30 AM" src="https://user-images.githubusercontent.com/1831562/204148977-6a18f928-543c-4058-8e95-64ce4f042bef.png">

**Comment by LalitMaganti** [comment]
I believe @ddrone is working on limiting this warning to Chrome traces.
