### ISSUE TITLE
Cannot open locally hosted traces in Safari

### ISSUE THREAD

**Issue by csmulhern** [google/perfetto#392]
`record_android_trace` opens local trace files by serving them through a local server on port 9001, which is explicitly whitelisted by the Content Security Policy (`http://127.0.0.1:9001`). See:

https://github.com/google/perfetto/blob/32e057826cb604da7f51f9f774e569f2b4884aa8/ui/src/frontend/index.ts#L166

Safari does not allow loading insecure content (i.e. HTTP) from a secure webpage (i.e. HTTPS), so these requests are blocked. There is an exception specifically for `localhost`. Can we update the CSP to allow `http://localhost:9001` rather than / in addition to `http://127.0.0.1:9001`?

**Comment by LalitMaganti** [comment]
Patches for this welcome. Please see https://perfetto.dev/docs/contributing/getting-started for guidance on this.

**Comment by csmulhern** [comment]
Small update: I started working on a patch, and discovered that the suggestion I had read that `localhost` would be allowed by Safari was incorrect. In actuality, Safari will not allow mixed active content from `localhost`.

Proper documentation: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#loading_locally_delivered_mixed-resources.

Marking this as closed. Thanks!
