### ISSUE TITLE
simple json file: Process 0 vs Process 1 question

### ISSUE THREAD

**Issue by mfbarad** [google/perfetto#394]
{    "traceEvents": [
    { "pid": 0,"tid": 0,"ts": 0,"dur":100,"ph": "X","name": "foo"},
    { "pid": 1,"tid": 0,"ts": 0,"dur":100,"ph": "X","name": "bar"}
] }

When I load that into ui.perfetto.dev the Process 0 and 1 durations appear different. What am I doing wrong?
Thanks,
Mike

**Comment by mfbarad** [comment]
<img width="1658" alt="Screen Shot 2022-11-29 at 9 34 16 PM" src="https://user-images.githubusercontent.com/36434726/204716125-4d5dc590-3422-485a-a1b1-1c6fbe86c714.png">

**Comment by primiano** [comment]
I think it's just a bug of the logic that generates the aggregated preview.
If you expand the tracks everything works as expected

![image](https://user-images.githubusercontent.com/7137473/204777332-3a255685-4246-4b09-aa37-b19594315316.png)

**Comment by chromy** [comment]
You should avoid using use pid = 0 if you are synthesizing a trace. pid = 0
is special in Linux Kernel and so has some special handling in the UI and
trace_processor. Please start from pid = 1 if possible.

**Comment by mfbarad** [comment]
When using pid 1 and 2 instead, they both show the same, but the aggregated preview shows half the time
