### ISSUE TITLE
Request for minimized sdk header

### ISSUE THREAD

**Issue by fundamental** [google/perfetto#395]
I've been using perfetto on a large codebase and while the single .h/.cpp file combo helps setup the system a ton, it does increase compilation times significantly. Would it be possible in future releases to minimize the .h file needed to support at least typical tracing macros (i.e. primarily TRACE_EVENT())?

I looked into disentangling the header myself, but didn't make much headway. If there is interest in this functionality I'll have my fingers crossed that the exposed interface doesn't require the full C++17 support noted in the most recent release notes since I'm currently stuck with a legacy codebase :-/

**Comment by LalitMaganti** [comment]
@ddiproietto FYI

> I looked into disentangling the header myself, but didn't make much headway. If there is interest in this functionality I'll have my fingers crossed that the exposed interface doesn't require the full C++17 support noted in the most recent release notes since I'm currently stuck with a legacy codebase :-/

I wouldn't count on this for too long. While for now we're not allowing C++17 features to creep in, this restriction will be lifted in ~3 months. In the meantime, we should hopefully have a C SDK.

**Comment by fundamental** [comment]
Yeah, that's fair enough. The UX of a C API would be non-ideal compared to the existing RAII used in the C++ API (due to illogical program flow/exceptions) in the app I'm working with, but it makes sense to move to newer C++ standards if there's useful features. Worst case if there's a C API it should be trivial to wrap it with a lightweight C++ class and accept a small amount of runtime overhead.

Overall though, kudos to all of the perfetto devs/contributors. It's a rad tool for program analysis and the extremely low runtime cost per trace event is superb.

**Comment by ddiproietto** [comment]
Hi,

* As you said, the amalgamated headers (the single .h .cc combo) are convenient for embedding, but the single header is not very convenient to include.
* You could avoid the amalgamated headers and import the single headers in [include/perfetto/](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/include/perfetto/). This involves a little bit more work for you, you need to integrate them in the build system, but updates might require a little bit of extra work. If you really care about compile times, I think this is more or less what you're looking for.
* A C SDK is coming (stay tuned!), the compile time of the headers is much faster. We could consider some RAII wrappers (with `#ifdef cplusplus` or using non standard `attribute cleanup`), but it's going to be a slightly different API.

Besides these, if you find that some change to the header improves compile time, patches are welcome!

Thanks!

**Comment by fundamental** [comment]
I wouldn't say the issue is resolved since the amalgamated headers is the canonical sdk install based on the docs, but I'm perfectly content with the request being out-of-scope. I'll look forward to the C SDK and possibly suggest changes once that additional layer is released.
