### ISSUE TITLE
aggregated preview shows the wrong duration

### ISSUE THREAD

**Issue by mfbarad** [google/perfetto#396]
See #394 

{    "traceEvents": [
    { "pid": 1,"tid": 0,"ts": 0,"dur":100,"ph": "X","name": "foo"},
    { "pid": 2,"tid": 0,"ts": 0,"dur":100,"ph": "X","name": "bar"},
] }

The aggregated preview, which is important for my usage case, shows the Process 1 and 2 durations as 50 instead of 100. Thanks

![Screen Shot 2022-12-01 at 10 47 04 AM](https://user-images.githubusercontent.com/36434726/205135114-a5f15195-cec4-44f7-b835-7d3cc5c70abf.png)

**Comment by TaoK** [comment]
I also see this - it took me a long time to understand that the strange markings in the aggregated view are actually supposed to be the overview of the expanded details.

**Comment by nikhilkalige** [comment]
I spent some time debugging this problem. I changed the line below to `select ts, dur`, and that does fix the problem for me.
https://github.com/google/perfetto/blob/92289f45c5f32e86f2f3c9c687306e637ba4e760/ui/src/tracks/process_summary/index.ts#L78

**Comment by mfbarad** [comment]
@nikhilkalige are you going to make a merge request? @chromy and @primiano might be able assist. They commented on a previous version of this issue: https://github.com/google/perfetto/issues/394 Thanks all!

**Comment by nikhilkalige** [comment]
@mfbarad I sure can.. But I wasn't sure if that is the expected behaviour. I also don't understand how utilization is supposed to impact the height of the summary bar. For example with the data, you see the width is correct with the change above, but the height stays the same for PID1, even though from 50 to 100, there are two threads doing some work.
```
{ "traceEvents": [
  { "pid": 1,"tid": 0,"ts": 0,"dur":100,"ph": "X","name": "foo"},
  { "pid": 1,"tid": 2,"ts": 50,"dur":100,"ph": "X","name": "doo"},
  
  { "pid": 4,"tid": 0,"ts": 0,"dur":100,"ph": "X","name": "foo1"},
  { "pid": 4,"tid": 2,"ts": 50,"dur":100,"ph": "X","name": "doo1"},

  { "pid": 2,"tid": 0,"ts": 50,"dur":50,"ph": "X","name": "bar"},
  { "pid": 3,"tid": 0,"ts": 100,"dur":50,"ph": "X","name": "car"},
]}
```
![Screenshot from 2023-03-11 23-52-43](https://user-images.githubusercontent.com/1267404/224531693-02edb887-c9b8-411c-827b-e607249a5028.png)

**Comment by nikhilkalige** [comment]
I am unsure about the `span_join` used to compute the utilization. In the case above,
```
select * from process_slice_view_542258dc_c3fc_4592_8af4_3bef476632a1
ts	dur
0	100000
50000	100000
select * from window_55e09221_7058_4685_8c7f_c94def855b75
this is just bunch of 640.. 
```
The `span_join` is supposed to add something up when there are overlaps right, but what does it add? In the test case written in C++, I see that it adds up `fvalue`, but I don't know what it does here. `select * from span_542258dc_c3fc_4592_8af4_3bef476632a1`, shows `ts, dur, quantum_ts`. I was expecting that there would be duplicate quantum_ts values for the overlaps, but I don't. Only overlapping value is below,
```
98560  640  389
99200  640  390
99840  160  391
99840  640  391
100480 640  392
```

**Comment by nikhilkalige** [comment]
I think we need to update the process_slice_view table to generate the following output
```
Ts Dur
100 10
105 15

this instead of above
ts  dur num_active_threads
100 5  1
105 5  2
110 10 1
```

**Comment by chromy** [comment]
@nikhilkalige: Thanks for looking into this!

Yes the line you linked above does seem pretty suspect 😦.
I need to re-familiarise myself with that file though which I will try to get to this week.

- If you want to learn more about span join see: https://perfetto.dev/docs/analysis/trace-processor#span-join
- If you are interested in sending a patch (which would be awesome 👍🏻 ) just an fyi that we can't accept patches through github, we use gerrit instead: https://perfetto.dev/docs/contributing/getting-started#code-reviews.

**Comment by mfbarad** [comment]
@chromy @nikhilkalige Is there any progress on this? Thanks so much.

**Comment by LalitMaganti** [comment]
https://r.android.com/3063232 fixes this.
