### ISSUE TITLE
Allow filtering/stripping of processes by name/pid

### ISSUE THREAD

**Issue by nhukc** [google/perfetto#40]
For mostly self contained processes it's useful to have a trace of only one process and it's children.

If we want scheduler/memory traces, a lot of unnecessary info gets added to the trace. Stripping this data from the protobuf or being able to filter it in the UI would be really useful.

It'd be nice to apply filters to ftrace by process name and remove any other processes from the trace.

**Comment by primiano** [comment]
@chromy as we have been discussing this (track filtering in the UI) at some point.

**Comment by LalitMaganti** [comment]
Going to fold this into https://github.com/google/perfetto/issues/429
