### ISSUE TITLE
Thread names being truncated

### ISSUE THREAD

**Issue by andredasilvapinto** [google/perfetto#400]
Not sure where it gets truncated, but is the maximum length for thread names configurable somewhere during the build or is this a limitation from the kernel itself?

![image](https://user-images.githubusercontent.com/2671593/206270201-ad07c997-0386-4fd8-9d83-a93dff3db7fc.png)

**Comment by LalitMaganti** [comment]
The limit is 16 characters and this is a Linux kernel limitation. There are two options for dealing with this:
1. If you're using the C++ SDK you can set the [thread_name](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/track_event/thread_descriptor.proto;l=29?q=f:perfetto%20thread_name%20f:track_even&sq=) field of the ThreadDescriptior.
2. You can enable the`record_thread_names` field of the [proc stats](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/config/process_stats/process_stats_config.proto;l=40?q=thread_name%20f:perfetto%20f:proc) scraper.
