### ISSUE TITLE
Make pan and zoom layout independent

### ISSUE THREAD

**Issue by ehermann** [google/perfetto#401]
Hello,
I'm using an azerty keyboard, and pan and zoom is impracticable with the current shortcuts.
It can be fixed buy using event code instead of event key as explained in this page. https://www.bram.us/2022/03/31/wasd-controls-on-the-web/
I already have a fix for it and will attach it to the issue as soon as possible.

**Comment by LalitMaganti** [comment]
Fixes welcome but this is just too low prio for us to look into ourselves. Feel free to send a patch though!

**Comment by stevegolton** [comment]
I believe this was actually fixed a while back with https://github.com/google/perfetto/commit/e4ea3ab396454357e6fde54744a9a7e8f0ca7d27
