### ISSUE TITLE
WebUSB Issues

### ISSUE THREAD

**Issue by b1foster** [google/perfetto#41]
I tested perfetto on linux and windows successfully on multiple machines, but not on the laptops we use for work when running windows. (A similar laptop running linux works.) 

Initially no devices showed up. I enabled chrome://flags/#new-usb-backend which showed the device but then it results in the following:
![image](https://user-images.githubusercontent.com/23458990/85639851-e4bc6180-b63e-11ea-91cb-7094c8db047e.png)
![image](https://user-images.githubusercontent.com/23458990/85639931-1f25fe80-b63f-11ea-8157-62e16e2b7153.png)

Any insight? Any thoughts on how to debug this?

Edit: I uninstalled dg_ssudbus driver. Slightly different results. With the new-usb-backend in default state, I can pair the device, but it doesn't do anything after I grant permissions. With new-usb-backend enabled, it yields the same error. This is the device log with new-usb-backend in default state:

![image](https://user-images.githubusercontent.com/23458990/85641492-93fb3780-b643-11ea-954c-189fd5dd5854.png)

**Comment by cutephoton** [comment]
Yeah. It definitely is not perfetto. We came to a similar conclusion:  ¯\_(ツ)_/¯ anti-malware? If it's ok, I'd like to keep this open for a couple days to see if anybody has further feedback before closing.

There wouldn't be a conflict with android studio, adb, etc, right?

**Comment by primiano** [comment]
> There wouldn't be a conflict with android studio, adb, etc, right?

In my experience that shows a different error "cannot claim interface". but maybe on windows that's different? Never played enough on Windows unforutnately.
