### ISSUE TITLE
Compiling error when try to run linux default build via ninja 

### ISSUE THREAD

**Issue by mhutestbyt** [google/perfetto#412]
Hi perfetto team,

I'm facing a problem when I tried to build linux build with perfetto trunk resource by ninja:

../../src/profiling/memory/malloc_interceptor_glibc_preload.cc:102:7: error: no previous prototype for function 'reallocarray' [-Werror,-Wmissing-prototypes]
void* reallocarray(void* ptr, size_t nmemb, size_t size) {
      ^
../../src/profiling/memory/malloc_interceptor_glibc_preload.cc:102:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
void* reallocarray(void* ptr, size_t nmemb, size_t size) {
^

is this a problem of my compiler or a breakage in code? 

thanks

**Comment by LalitMaganti** [comment]
This is almost certainly a problem with your environment. My suspicion is that your glibc is older that 2.29 which is when reallocarray was first introduced in stdlib.h according to https://www.unix.com/man-page/linux/3/reallocarray/

**Comment by mhutestbyt** [comment]
HI Lalit, yes, you were right, after updating my glibc, no more compiling errors. 
thanks and happy holiday
