### ISSUE TITLE
traceconv should use binary output on windows

### ISSUE THREAD

**Issue by CatDroid** [google/perfetto#415]
Host: Windows 10
Client:  realme X50,  Android 11 

Follow the step "
[symbolization](https://perfetto.dev/docs/data-sources/native-heap-profiler#symbolization)
" to symbolize, 
but upload "symbolized-trace"  to https://ui.perfetto.dev/ , it show "unknown" of call stack about my code.

my profile data:
[temp1.zip](https://github.com/google/perfetto/files/10318785/temp1.zip)

issue:
![image](https://user-images.githubusercontent.com/24932019/209935586-3b80afe9-fd9a-4159-9ffb-1928b30ecbdd.png)

my code is simple for test:
![image](https://user-images.githubusercontent.com/24932019/209935738-812c7e63-ca7b-45d3-a90b-1418fc7bed0f.png)

symbols maybe correct ? 
![symbols](https://user-images.githubusercontent.com/24932019/209936165-6cf7f51a-925f-491d-918c-8bd48c80103d.png)

**Comment by ddiproietto** [comment]
Your symbols file is corrupted. You can verify by running `traceconv text symbols`

Here's an hex dump of your file:

```
00000000  0d 0a e9 82 80 00 ea 03  e3 82 80 00 0d 0a 5f 2f  |.............._/|
00000010  64 61 74 61 2f 61 70 70  2f 7e 7e 61 4a 63 68 5f  |data/app/~~aJch_|
00000020  74 36 4a 5a 4b 4d 55 61  51 66 53 36 70 6b 4d 4e  |t6JZKMUaQfS6pkMN|
00000030  77 3d 3d 2f 63 6f 6d 2e  63 70 70 2e 6c 65 61 6b  |w==/com.cpp.leak|
00000040  2d 6a 4a 39 79 71 79 66  44 35 4f 73 50 4e 47 61  |-jJ9yqyfD5OsPNGa|
00000050  67 75 57 49 55 70 41 3d  3d 2f 6c 69 62 2f 61 72  |guWIUpA==/lib/ar|
00000060  6d 36 34 2f 6c 69 62 6c  65 61 6b 2e 73 6f 12 14  |m64/libleak.so..|
00000070  d9 a2 84 cf 39 a7 21 5e  e3 fe 80 21 1e 52 83 db  |....9.!^...!.R..|
00000080  5b b8 bf 7b 1a fd 80 80  00 08 c8 de 01 12 f4 80  |[..{............|
00000090  80 00 0d 0a 2c 4a 61 76  61 5f 63 6f 6d 5f 63 70  |....,Java_com_cp|
000000a0  70 5f 6c 65 61 6b 5f 4d  61 69 6e 41 63 74 69 76  |p_leak_MainActiv|
000000b0  69 74 79 5f 6d 61 6c 6c  6f 63 4e 6f 74 46 72 65  |ity_mallocNotFre|
000000c0  65 12 42 46 3a 2f 4d 79  50 72 6f 6a 65 63 74 2f  |e.BF:/MyProject/|
000000d0  43 70 70 4d 65 6d 6f 72  79 4c 65 61 6b 54 6f 6f  |CppMemoryLeakToo|
000000e0  6c 54 65 73 74 2f 61 70  70 2f 73 72 63 2f 6d 61  |lTest/app/src/ma|
000000f0  69 6e 2f 63 70 70 5c 6e  61 74 69 76 65 2d 6c 69  |in/cpp\native-li|
00000100  62 2e 63 70 70 18 2a 1a  e5 80 80 00 08 f8 de 01  |b.cpp.*.........|
00000110  12 dc 80 80 00 0d 0a 14  4d 79 4d 61 6c 6c 6f 63  |........MyMalloc|
00000120  46 61 63 74 6f 72 79 28  69 6e 74 29 12 42 46 3a  |Factory(int).BF:|
00000130  2f 4d 79 50 72 6f 6a 65  63 74 2f 43 70 70 4d 65  |/MyProject/CppMe|
00000140  6d 6f 72 79 4c 65 61 6b  54 6f 6f 6c 54 65 73 74  |moryLeakToolTest|
00000150  2f 61 70 70 2f 73 72 63  2f 6d 61 69 6e 2f 63 70  |/app/src/main/cp|
00000160  70 5c 6e 61 74 69 76 65  2d 6c 69 62 2e 63 70 70  |p\native-lib.cpp|
00000170  18 22                                             |."|
```

I think this happens because of a bug on windows.

We use std::cout to write the `symbols` files:

https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/traceconv/main.cc;l=149;drc=a9545e5e74a3c900eab175293d992b82a81ed789

Unfortunately std::cout on windows replaces all `"\n"` with `"\r\n"`

If you manually replace all the `0d 0a` bytes in your file with just `0a`, symbolization works.

We should fix the problem in the perfetto code.

For the case where we're outputting to a file we should just add a `std::ios_base::binary` here:

https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/traceconv/main.cc;l=144;drc=a9545e5e74a3c900eab175293d992b82a81ed789

For the case where we're outputting to std::cout, probably

```
#ifdef WIN32
_setmode( _fileno( stdout ), _O_BINARY );
#endif
```

would work?

Would you be able to test that code change? (I don't have a windows machine at the moment)

**Comment by CatDroid** [comment]
I hope to do so, but when I setup built-enviroment on window, some problems happen~

**Comment by CatDroid** [comment]
python tools/gn gen out/win  9009 error is fixed 
because I have another python install at 
C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/python3.exe,
del this one , and copy python.exe and rename to python3.exe at python3 install direcotry,  then it's ok

**Comment by CatDroid** [comment]
![image](https://user-images.githubusercontent.com/24932019/209970775-9a33af3b-4285-41dc-adc1-67d4b5dc30b9.png)

Yes, it's ok.
In my case , 
```
file_istream.open(file_path, std::ios_base::in | std::ios_base::binary);
``` not working, because i use > std::cout

the following is ok
```
#ifdef WIN32
#include <stdio.h>
#endif 

...
 #ifdef WIN32
	_setmode( _fileno( stdout ), _O_BINARY);
 #endif


  std::ostream* output_stream;
  std::ofstream file_ostream;
  if (positional_args.size() > 2) {
    const char* file_path = positional_args[2];
    file_ostream.open(file_path, std::ios_base::out | std::ios_base::trunc | std::ios_base::binary);
    if (!file_ostream.is_open())
      PERFETTO_FATAL("Could not open %s", file_path);
    output_stream = &file_ostream;
  } else {
    output_stream = &std::cout;
  }

```

**Comment by CatDroid** [comment]
GitHub\perfetto\src\traceconv
[main.cpp](https://github.com/google/perfetto/files/10320147/main.zip)

**Comment by ddiproietto** [comment]
Solved with https://r.android.com/2374032
