### ISSUE TITLE
Can perfetto capture trace points marked with ATRACE_COUNTER?

### ISSUE THREAD

**Issue by Shuang-Zi** [google/perfetto#416]
# Issue
We use ATRACE_COUNTER to mark trace points in the driver. Use the trace captured by atrace, and the result will be displayed with relevant trace points. But we directly use perfetto to capture the trace, and we cannot see the relevant trace points in the perfetto UI.
Any help is greatly appreciated！

**Comment by chromy** [comment]
It should work, does ATRACE_BEGIN/END work for you? Also please attach a trace showing the problem and it will be easier to see what is going on. Thanks!
