### ISSUE TITLE
improve ? Heap profiler record the meminfo and visualize  ?

### ISSUE THREAD

**Issue by CatDroid** [google/perfetto#417]
Is it possible to record certain process's memory usage info while profiling and visualize it on https://ui.perfetto.dev/
e.g
![show meminfo](https://user-images.githubusercontent.com/24932019/210028001-a24a8989-dede-4632-976a-441887ff3197.png)

I think it's helpful to overall trend and locate the time point of main leak.
hope the idea will be accepted, thanks.

**Comment by CatDroid** [comment]
another idea is,
just like “adb shell dumpsys meminfo pid ",  
I can fillter certain process's memory info , instead the whole system,
![image](https://user-images.githubusercontent.com/24932019/210031890-cfe006ce-60ec-4d7a-bc7e-96ae3d681bda.png)

**Comment by LalitMaganti** [comment]
You can visualize RSS on the timeline by enabling the "Per-process stats" data source: 
![image](https://user-images.githubusercontent.com/679100/210032547-223145dd-08fd-47ed-93d3-db3afbfee333.png)
