### ISSUE TITLE
traceconv use : to separate path from PERFETTO_BINARY_PATH

### ISSUE THREAD

**Issue by CatDroid** [google/perfetto#418]
I Built traceconv from source code on windows and I found it can not find the library path even I  set 
set PERFETTO_BINARY_PATH enviroment.
e.g
PERFETTO_BINARY_PATH=E:\orange_sdk\temp\build\android\build\intermediates\cmake\release\obj\arm64-v8a\

after debuging, I find this issue: 
```
//https://github.com/google/perfetto/blob/master/src/profiling/symbolizer/symbolize_database.cc
std::vector<std::string> GetPerfettoBinaryPath() {
  const char* root = getenv("PERFETTO_BINARY_PATH");
  if (root != nullptr)
    return base::SplitString(root, ":");
  return {};
}
```

then the one path will be sperated into two as follow:
```
mbolize_database.cc:159 GetPerfettoBinaryPath E
mbolize_database.cc:159 GetPerfettoBinaryPath \orange_sdk\temp\build\android\build\intermediates\cmake\release\obj\arm64-v8a\
```

is it possible to separate paths with ;  instead of :  ?

**Comment by LalitMaganti** [comment]
Patches for this welcome: I would only change the separator on Windows given we have a bunch of tooling in place which uses this already which we don't want to brea.

**Comment by listevemeta** [comment]
I had the same issue on my Widows desktop and tracked to that source.  Submitting patch https://android-review.googlesource.com/c/platform/external/perfetto/+/2780895/1
