### ISSUE TITLE
Perfetto cannot display the relevant information of the trace points marked by tracing_mark_write?

### ISSUE THREAD

**Issue by Shuang-Zi** [google/perfetto#419]
# issue
We use tracing_mark_write to mark trace points in the driver. There is no relevant information in the trace captured by perfetto, but it can be captured by atrace.

# atrace 
## command
`atrace -b 25000 video --async_start -o /data/local/tmp/trace1`
`atrace --async_stop -o /data/local/tmp/trace1`
## trace file
[https://github.com/Shuang-Zi/perfetto_issue_file/blob/main/trace.systrace](url)
## screenshot
![image](https://user-images.githubusercontent.com/75553381/210476997-eb5b6e2f-a87e-46ef-a7a3-1df4867db3f9.png)

# perfetto
## confige file & command
```shell
buffers: {
    size_kb: 14336
    fill_policy: DISCARD
}
buffers: {
    size_kb: 2048
    fill_policy: DISCARD
}
data_sources: {
    config {
        name: "linux.process_stats"
        target_buffer: 1
        process_stats_config {
            scan_all_processes_on_start: true
        }
    }
}
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            ftrace_events: "sched/sched_switch"
            ftrace_events: "power/suspend_resume"
            ftrace_events: "sched/sched_wakeup"
            ftrace_events: "sched/sched_wakeup_new"
            ftrace_events: "sched/sched_waking"
            ftrace_events: "raw_syscalls/sys_enter"
            ftrace_events: "raw_syscalls/sys_exit"
            ftrace_events: "sched/sched_process_exit"
            ftrace_events: "sched/sched_process_free"
            ftrace_events: "task/task_newtask"
            ftrace_events: "task/task_rename"
            ftrace_events: "ftrace/print"
            atrace_categories: "video"
            atrace_apps: "*"
        }
    }
}
duration_ms: 15000
```
` cat /data/misc/perfetto-configs/perfetto.cfg | perfetto --txt -c - -o /data/misc/perfetto-traces/trace`
## trace file
[https://github.com/Shuang-Zi/perfetto_issue_file/blob/main/trace.perfetto](url)
## screenshot
![image](https://user-images.githubusercontent.com/75553381/210477714-1c5d4a57-55b5-491a-b442-8fe607580cbc.png)
As can be seen from the figure above, there are no relevant trace points. Moreover, after converting the trace.perfetto file to systrace format with traceconv, there is no relevant trace point for directly viewing the text.
In addition, I directly cat the **/sys/kernel/debug/tracing/trace** node, which has relevant information.

# Questions
1.  Which node does traced_probes read? Is it **sys/kernel/debug/tracing/per_cpu/cpux/trace_pipe_raw**?
2.  I directly cat the trace_pipe_raw node, but the read data is garbled. Is there any way to serialize it?

# Related issue
I found a similar problem before： [https://github.com/google/perfetto/issues/67](url)

**Comment by LalitMaganti** [comment]
> Which node does traced_probes read? Is it sys/kernel/debug/tracing/per_cpu/cpux/trace_pipe_raw?

Yes

> I directly cat the trace_pipe_raw node, but the read data is garbled. Is there any way to serialize it?

Not unless you want to reverse engineer the binary format like we had to :)

When you say

> We use tracing_mark_write to mark trace points in the driver. 

What specifically are you doing to log the trace points?

**Comment by Shuang-Zi** [comment]
Hi, LalitMaganti:
 We roughly mark trace points in the driver in the following ways：
 ```c
TRACE_EVENT(tracing_mark_write,
	    TP_PROTO(const char *name, unsigned int flags, unsigned long value),
	    TP_ARGS(name, flags, value),

	TP_STRUCT__entry(__string(name, name)
			 __field(unsigned int, flags)
			 __field(unsigned long, value)
	),

	TP_fast_assign(__assign_str(name, name);
		       __entry->flags = flags;
		       __entry->value = value;
	),

	TP_printk("%s%s%s|%lu", print_flags_header(__entry->flags),
		  print_flags_delim(__entry->flags),
		  __get_str(name), __entry->value)
);

trace_tracing_mark_write(name, flags, value);
```

**Comment by LalitMaganti** [comment]
If this is some custom event, almost certainly the problem is that Perfetto does not know how to convert the event from ftrace to protobuf and trace processor does not know how to parse the event.

You can follow the instructions at https://perfetto.dev/docs/contributing/common-tasks#add-a-new-ftrace-event to add support.

Also, very recently someone added support for another group's tracing_mark_write which you might find useful to follow: https://android-review.git.corp.google.com/c/platform/external/perfetto/+/2352609 and https://android-review.git.corp.google.com/c/platform/external/perfetto/+/2373432

**Comment by Shuang-Zi** [comment]
I don't have an account, so I can't see the content in the above two URLs：
https://android-review.git.corp.google.com/c/platform/external/perfetto/+/2352609 and https://android-review.git.corp.google.com/c/platform/external/perfetto/+/2373432

**Comment by LalitMaganti** [comment]
Sorry I keep making this mistake. The links are https://r.android.com/2352609 and https://r.android.com/2373432
