### ISSUE TITLE
perfetto UI does not display custom ftrace_events

### ISSUE THREAD

**Issue by Shuang-Zi** [google/perfetto#422]
This is a follow-up to the issue: https://github.com/google/perfetto/issues/419

# Issue
Currently, we have added a custom ftrace_event according to https://perfetto.dev/docs/contributing/common-tasks, and have recorded the relevant trace files. When we directly view the text file, there are relevant trace points, but when we directly open the trace file with perfetto UI, no relevant information is displayed.

# trace file
https://github.com/Shuang-Zi/perfetto_issue_file/blob/main/trace-20230105_08-09-37-2.bin
![image](https://user-images.githubusercontent.com/75553381/210754728-28a449a0-8652-4252-82f3-eeb8728971f4.png)

# question
If I don't use trace_processer and open the trace file directly with ui, what do I need to do to see the custom trace_event on the UI?

**Comment by LalitMaganti** [comment]
This is WAI. If we don't know how to parse it, we cannot display it. It's just a fact of how the UI and whole stack works.

**Comment by LalitMaganti** [comment]
This is why we ask people contribute custom ftrace events to us by submitting a patch.

**Comment by Shuang-Zi** [comment]
@LalitMaganti 
Hi, LalitMaganti 
I think maybe my description above is not clear.
https://github.com/Shuang-Zi/perfetto_issue_file/blob/main/trace-20230105_08-09-37-2.bin I have opened this trace file in the UI before, but there is no relevant trace point in it（Marked by the red box above）, and the overall display is very strange：
![image](https://user-images.githubusercontent.com/75553381/210915235-b579df30-bef9-4baf-ba96-7ec96ce9e72b.png)

----
my custom steps：
1. Customized ftrace events according to https://perfetto.dev/docs/contributing/common-tasks documentation
2. Then compiled perfetto in the android-t source tree：`mmma external/perfetto`
3. Replace the compiled executable file: perfetto\traced\traced to system/bin in the Android environment. Replace libperfetto.so\libperfetto_android_internal.so to system/lib.
4. Finally, capture the trace through the command: `cat /data/perfetto.cfg | perfetto --txt -c - -o /data/misc/perfetto-traces/trace`

---
perfetto config content： 
```shell
buffers: {
    size_kb: 32768
    fill_policy: RING_BUFFER
}
buffers: {
    size_kb: 2048
    fill_policy: RING_BUFFER
}
data_sources: {
    config {
        name: "linux.process_stats"
        target_buffer: 1
        process_stats_config {
            scan_all_processes_on_start: true
        }
    }
}
data_sources: {
    config {
        name: "android.surfaceflinger.frametimeline"
    }
}
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            ftrace_events: "sched/sched_switch"
            ftrace_events: "power/suspend_resume"
            ftrace_events: "sched/sched_wakeup"
            ftrace_events: "sched/sched_wakeup_new"
            ftrace_events: "sched/sched_waking"
            ftrace_events: "sched/sched_process_exit"
            ftrace_events: "sched/sched_process_free"
            ftrace_events: "task/task_newtask"
            ftrace_events: "task/task_rename"
            ftrace_events: "ftrace/print"
            ftrace_events: "meson_atrace/tracing_mark_write"                 << Customize ftrace events
            atrace_categories: "audio"
            atrace_categories: "binder_driver"
            atrace_categories: "gfx"
            atrace_categories: "network"
            atrace_categories: "ss"
            atrace_categories: "video"
            atrace_apps: "*"
        }
    }
}
duration_ms: 15000
```
---
1.  Are there any errors in the above steps？Why open this trace file directly with the UI, the display is abnormal？
2.  Do we need to submit custom files to perfetto, after perfetto is merged, then the UI can parse?

**Comment by LalitMaganti** [comment]
> Are there any errors in the above steps？Why open this trace file directly with the UI, the display is abnormal？

The steps seem reasonable except that you probably didn't need to replace perfetto on your system image (or built in the Android tree) but instead could have used the standalone build + the record_android_trace helper script [1] with --sideload and --sideload-path pointing to a standalone build of tracebox. Anyway on the collection side things seem reasonable as I can say without actually seeing the patch you've written.

> Do we need to submit custom files to perfetto, after perfetto is merged, then the UI can parse?

Correct. This is pointed out by https://perfetto.dev/docs/contributing/common-tasks when we say "If special handling in trace_processor is desired update [src/trace_processor/importers/ftrace/ftrace_parser.cc](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/importers/ftrace/ftrace_parser.cc) to parse the event.". This code is used in the UI to visualize events: no event will appear in the UI which is not in one of the trace processor tables.

If you just want to test this locally though, you can build and run the UI locally at ui/run-dev-server to check the trace_processor changes.

> Is ui also like trace_process, through trace_processor_shell to parse the trace file？

The UI uses trace_processor under the hood, compiling it to webassembly and running it in your browser locally. This is why when you add support in trace processor for parsing the event, the UI is able to see and visualize it.

**Comment by Shuang-Zi** [comment]
@LalitMaganti 
Hi, LalitMaganti，thanks for your reply.
The following is our CL, please help to review it：
https://android-review.googlesource.com/c/platform/external/perfetto/+/2378295

---
We use this CL, we have captured the trace of relevant information and the parse is normal.
But these custom trace points appear in many processes, which is not expected. They should only be in one process.
The following two pictures are the trace display we opened in the localhost UI：
![2023-01-06 21-54-05 的屏幕截图](https://user-images.githubusercontent.com/75553381/211017952-b467e6e4-2e9c-4985-9173-7582a5a99671.png)
![2023-01-06 21-54-37 的屏幕截图](https://user-images.githubusercontent.com/75553381/211017974-d73f0e5c-a026-4a68-9695-7a6d6dbffdac.png)

**Comment by LalitMaganti** [comment]
Do you have process associations enabled (i.e. the `linux.process_stats` in your trace config?). If not, likely what we are calling "process" is just a thread in a single process but we're unable to know the tgid to group all the threads under.

**Comment by Shuang-Zi** [comment]
@LalitMaganti 
Hi, LalitMaganti ,thanks for your reply.
① `linux.process_stats` is not used in our trace config.
② Since these trace points are marked in the kernel thread, the tgid parameter here is 0.
![image](https://user-images.githubusercontent.com/75553381/211250681-aa82de2c-0881-40d3-8e72-75e8323fc35f.png)
Referring to the previous normal trace, the process in the above picture is a “process”, not a thread in a single process.

**Comment by LalitMaganti** [comment]
Are you sure that your code is not executing in an interrupt context? When I've seen issues like this in the past with kernel tracing_mark_write events, this has almost always been the cause.

You need some way to tell trace processor what the true PID the event should be associated with: at the moment you're associating with whatever event happens to be executing at that point in time.
