### ISSUE TITLE
0 duration "X" event is sometimes not rendered

### ISSUE THREAD

**Issue by facewindu** [google/perfetto#423]
With the attached json
[trace-tree-chrome.json.txt](https://github.com/google/perfetto/files/10353145/trace-tree-chrome.json.txt)
if you zoom in a lot near the bottom right, you can see
![image](https://user-images.githubusercontent.com/5922961/210810717-05d497a6-a70c-4f8a-bc1f-3d6ce5aa6660.png)
![image](https://user-images.githubusercontent.com/5922961/210810779-c4c295c8-af52-4dae-b8a7-99e4b8764fe6.png)
Notice the selection box, that should contain 2 "Identifying work" events, which are not displayed.
In the json, they correspond to events 4235 and 4238
<img width="253" alt="image" src="https://user-images.githubusercontent.com/5922961/210811213-23da1430-b3ce-43cb-a724-7f1aeb443ab4.png">

Later on, there is event 4250, that has a zero duration too
<img width="362" alt="image" src="https://user-images.githubusercontent.com/5922961/210811301-b339e211-fb7d-40df-b307-551a26515a54.png">
and it's properly displayed, see the "arrow" in the first screenshot

Is there a bug preventing the "Identifying work" events to be rendered properly ?

**Comment by LalitMaganti** [comment]
Almost certainly what's happening here is that you have two events with *identical* timestamps down to the nanosecond and these are causing depth computation to break due to event ordering. I remember seeing another bug filed for this recently.

This stuff only happens in JSON because of the lack of precision but the JSON format is also supported on a best-effort basis. Patches to fix this are welcome but it's reasonably unlikely we will get to this.

**Comment by LalitMaganti** [comment]
https://github.com/google/perfetto/issues/359 is what I was thinking about.

**Comment by facewindu** [comment]
@LalitMaganti thanks for the quick answer. I understand. We'll try to switch to the proto trace format then.

**Comment by facewindu** [comment]
@LalitMaganti sorry to bother you again
I'm now trying to switch to a protobuf-based solution (shifting the timestamp by 1 might cause some other troubles for us) IIUC it should be feasible.

First of all, are the `.proto` files the ones in https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/ ?
What's the best way to consume them ?
For now I copied them in my project.

Then, I'm generating Java classes from them, via the `com.google.protobuf` Gradle plugin.

I'm having trouble generating the given event types.
In my trace, I have [Complete Events](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.lpfof2aylapb) (phase `X`) and [Metadata Events](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.xqopa5m0e28f) (phase `M`).

How can I properly set the phase / event type for those kind of events ?
```

ChromeTraceEvent.newBuilder()
                    .setName("process_name")
                    .setPhase( ... )
```
How do I set the phase here, given it's an `int` ?
I tried to find enums in the proto files, corresponding to those types, but I only found `TrackEvent.Type`, which has `UNDEFINED`, `SLICE_BEGIN`, `SLICE_END`, `INSTANT`, `COUNTER`.
I can probably convert the Complete Events to pairs of `SLICE_BEGIN`/`SLICE_END`, but what about the metadata event (that I use for my process and thread names) ?

Also, the proto files says that `ChromeTraceEvent` is deprecated, and that I should use `TrackEvent` instead.
But then, how do I use `TrackEvent` or `TrackEvent.LegacyEvent` to generate Chrome trace events, as it seems to be way more generic and don't provide detailed fields as the chrome trace event has.


Eventually, what I need is to know how to convert in protobuf those kind of json chrome trace events
```
    {
        "name": "process_name",
        "ph": "M",
        "ts": 1672931379152000,
        "pid": 1,
        "tid": 1,
        "cat": "",
        "args": {
            "name": "Worker Lease "
        }
    }
```
and
```
    {
        "name": "Run build",
        "ph": "X",
        "ts": 1672931379152000,
        "dur": 122010000,
        "pid": 1,
        "tid": 1,
        "cat": "",
        "args": {
            "thread": "main @@ Daemon worker @@ 29"
        }
    }
```

**Comment by LalitMaganti** [comment]
> What's the best way to consume them ?

Copy https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/perfetto_trace.proto which is a single file amalgamation of all our protos.

> In my trace, I have [Complete Events](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.lpfof2aylapb) (phase X) and [Metadata Events](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.xqopa5m0e28f) (phase M).

Neither of these are 1:1 present in the new format. Complete events should be encoded as a pair of begin/end events. Metadata events usually can be represented some other way in the format

> How do I set the phase here, given it's an int ?

Yeah I wouldn't use ChromeTrackEvent. Just use TrackEvent directly as descrived in the comments of the [proto](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/perfetto_trace.proto;l=9421)

>I can probably convert the Complete Events to pairs of SLICE_BEGIN/SLICE_END, but what about the metadata event (that I use for my process and thread names) ?

Before you emit a packet for a tid/pid, emit a packet containing [TrackDescriptor](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/perfetto_trace.proto;l=11762) with the [thread_descriptor](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/perfetto_trace.proto;l=9717) field set for thread names. Set the UUID of this to some random value and then use this UUID to associate events to (i.e. you need a map<pid, map<tid, uuid>>). For process names emit a ProcessDescriptor for the first thread where you see pid is not in the map.

> But then, how do I use TrackEvent or TrackEvent.LegacyEvent to generate Chrome trace events, as it seems to be way more generic and don't provide detailed fields as the chrome trace event has.

TrackEvent is not going to be a 1:1 correspondence with the JSON format but it's much *much* more powerful in pretty much every respect.

> Eventually, what I need is to know how to convert in protobuf those kind of json chrome trace events

Yeah I've basically provided ad-hoc advice to this over the years (both internally and externally) and I've long wanted to write a guide but it never seems to be high priority. Let me know if you have trouble with this and I'll see if I can spare some time to write that up.

**Comment by facewindu** [comment]
awesome @LalitMaganti this is immensely helpful. I tried hard to find some guidance on the web, but failed and resorted to ask here.

**Comment by facewindu** [comment]
hmmm and now I have a list of TracePacket objects, but I don't know the logic to serialize it :/

**Comment by LalitMaganti** [comment]
If you're using java protobuf, isn't that just toByteArray() (see https://developers.google.com/protocol-buffers/docs/javatutorial#parsing-and-serialization)?

Note that also it's important you serialize Trace *not* a vector of TracePackets. You should add the vector of TracePackets into Trace before serialization.

**Comment by facewindu** [comment]
That's what's wrong. I was trying to serialize the vector of packets

**Comment by facewindu** [comment]
One thing that was also needed is to set the "trusted packet sequence ID" to some non-0 numbers on all my `TracePackets`
then all is good and can be displayed.

As you mentioned, I had to use the (deprecated) `setProcessDescriptor` to name my PIDs
I didn't manage to make it work by using a `setTrackDescriptor` where I use `setThread` and also `setProcess` inside.

**Comment by LalitMaganti** [comment]
> One thing that was also needed is to set the "trusted packet sequence ID" to some non-0 numbers on all my TracePackets
Yup this is a fair point - forgot to point this out to you!

> As you mentioned, I had to use the (deprecated) setProcessDescriptor to name my PIDs
Yeah ProcessDescriptor is easier but as you say it's deprecated and could be removed at some point (though the cost of keeping it around it around is low so there's no particular need to do so atm. TrackDescriptor is the supported way but it's a bit more tricky to get right.

**Comment by facewindu** [comment]
> Yeah ProcessDescriptor is easier but as you say it's deprecated and could be removed at some point (though the cost of keeping it around it around is low so there's no particular need to do so atm. TrackDescriptor is the supported way but it's a bit more tricky to get right.

would be good if you can explain how to work with track descriptor then, for setting process names.
I have
```
events.add(TracePacket.newBuilder()
                    .setTimestamp(beginTime)
                    .setTrustedPacketSequenceId(1)
                    .setProcessDescriptor(ProcessDescriptor.newBuilder()
                        .setPid(ctProcessId)
                        .setProcessName("my process name "+ctProcessId)
                    )
                    .build()
                )
```
and also
```
events.add(TracePacket.newBuilder()
                    .setTimestamp(beginTime)
                    .setTrustedPacketSequenceId(1)
                    .setTrackDescriptor(TrackDescriptor.newBuilder()
                        .setUuid(uuid)
                        .setThread(ThreadDescriptor.newBuilder()
                            .setPid(ctProcessId)
                            .setTid(ctThreadId)
                            .setThreadName(record.threadDescription)
                        )
                    )
                    .build()
                )
```

but I couldn't make it work when I tried to also declare my process (and thus its display name) in a track descriptor packet.


bonus question:
when setting a process (or thread name), Perfetto appends to it an internal index, eg
<img width="262" alt="image" src="https://user-images.githubusercontent.com/5922961/211321791-79e3c29a-d31d-4224-9ebb-eb0d29c5b5a0.png">


where the process name is `Worker Lease 2`, and the thread name is `main @@ Execution worker @@ 134`. Any way to prevent that from happening by default ?

**Comment by LalitMaganti** [comment]
You should *not* put both in the same packet: we parse only one of those two fields in each trace packet.

You should instead set the uuid of the process TrackDescriptor to some random value: doesn't matter what this is because you're not emitting any process scoped events (i.e. nestable async events in the json spec).

The association between the thread/process is not done by UUIDs but is handled by pid/tid. So to summarize the ordering of events is as:
* Emit the process descriptor at the start of the trace with uuid=random(), pid=your_pid
* Emit the thread descriptor at the start of the trace with uuid=random(), pid=your_pid, tid=tid
* Emit all your events with track_uuid=thread descriptor's track_uuid

**Comment by LalitMaganti** [comment]
The debug_annotations field is designed for exactly this purpose: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/perfetto_trace.proto;l=9613.

See the comment on the proto on how to fill it: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/perfetto_trace.proto;l=8599

**Comment by facewindu** [comment]
Closing this, as it's getting out of hand and talks about many different things. All resolved. Thanks for your help 👍
