### ISSUE TITLE
[feature request] Support per-thread display of perf samples

### ISSUE THREAD

**Issue by wangjiyang** [google/perfetto#425]
Hi, current perfetto ui seems not support displaying per-thread perf samples. Samples from multiple threads of same process show as one-line track in perfetto ui.
I found one submit which seems trying to solve this issue, however, this submit seems not active for half a year.

https://android-review.googlesource.com/c/platform/external/perfetto/+/2142174

**Comment by LalitMaganti** [comment]
@rsavitski FI

**Comment by linzj** [comment]
@rsavitski and Perfetto team,

Regarding issue #425 (Support per-thread display of perf samples), could you provide an update on the status of the referenced CL (<https://android-review.googlesource.com/c/platform/external/perfetto/+/2142174>) and its potential inclusion in a future Perfetto release? I am eagerly awaiting this feature for improved multi-threaded analysis. Thank you.

**Comment by linzj** [comment]
Great work!
