### ISSUE TITLE
Weird nanosecs timing data displayed in perfetto

### ISSUE THREAD

**Issue by facewindu** [google/perfetto#426]
Take these 2 events
```

    {
        "name": "Run build",
        "ph": "X",
        "ts": 1672924880617000,
        "dur": 104321000,
        "pid": 1,
        "tid": 1
    }
```
and
```
    {
        "name": "Load build",
        "ph": "X",
        "ts": 1672924881307000,
        "dur": 32786000,
        "pid": 1,
        "tid": 1
    }
```

This results in the following display 
<img width="736" alt="image" src="https://user-images.githubusercontent.com/5922961/211518470-e5f9cc98-4bb9-4a77-abfd-dbd2df78a30a.png">

all good
but the details of "Load build" show `Start time  690ms 296ns`. Why ?
1672924881307000 - 1672924880617000 = 690000 = exactly 690 ms in the JSON format.

Note that the problem appears also on ProtoBuf-based traces. What is causing these nanos to appear ?

**Comment by LalitMaganti** [comment]
This seems a legit issue: looking.

**Comment by LalitMaganti** [comment]
This is a Javascript precision issue unfortunately and fixing this is a bit tricky. @chromy is taking a look.

**Comment by facewindu** [comment]
FTR, I worked around the problem by generating "smaller timestamps" by using:
- a clock snapshot that
  - sets the Boot Time clock timestamp at my 'start timestamp'
  - sets a custom clock with timestamp = 0 and unit multiplierNs = 1000*1000 (I actually don't care about more than ms granularity)
-  using my timestamp clock ID on my packets
- set the timestamp of my packets to their proper timestamp - my "start timestamp"

Note that the problem could also be solved by using delta timestamps (which makes the timestamp values on each trace packets very small).

I'll keep the issue open in case you still want to give a shot at fixing the JS precision issue.

**Comment by LalitMaganti** [comment]
I believe this has been fixed with @stevegolton's work on bigint timestamps.

**Comment by stevegolton** [comment]
Can confirm this is fixed now. Note the printed timestamp format is slightly different but the value is as expected.

<img width="548" alt="image" src="https://github.com/google/perfetto/assets/6147146/4d681836-41cd-4356-aab0-90935d11e705">
