### ISSUE TITLE
Flow IDs UI representation

### ISSUE THREAD

**Issue by facewindu** [google/perfetto#427]
This is more a question than an issue.

Say I have a parent event with two child events. One of these child event is on another track.
All those events are modeled through TrackEvents with type slice_begin / slice_end (so 2 TrackEvent per event)

Track 1:
[  ----------- parent event --------------------]
     [   child event 1 ]

Track 2:
     [   child event 2 ]

I tried to use flow IDs to link the parent event with the 2 child events. I'm mainly interested in the link between the parent event and the "child event 2" since it's on another track, potentially visually far away, and the nesting is not obvious.
This works, but what I end up having is

=> a link from the END of parent event to the START of child 1 and child 2

is there a way to model a flow between the START of the parent and the START of the children ?

**Comment by LalitMaganti** [comment]
@betasheet I remember when we first discussed flows we considered whether or not to support a timestamp for start/end which allowed you to start the arrow from any point. We decided it was more complication than it was worth so we decided against it. Therefore, the direct answer to your question is, no there is no way to do this "natively".

The workaround for this is to emit an instant event (i.e. a slice with duration 0) at the start of the child slice and have a flow from *that* to track 2. It adds an extra thing you need to name but otoh it means we don't have to support very complicated arrow drawing logic in the UI.

**Comment by facewindu** [comment]
Got it.
The instant event is visible though, so the workaround is not quite what I'd want.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/5922961/212371215-b85de6ec-fb79-4064-a2bd-8cdaab7ef73b.png">

**Comment by LalitMaganti** [comment]
Yeah it's definitely visible but it's the best option today.
