### ISSUE TITLE
how to compile perfetto python package by arm archi?

### ISSUE THREAD

**Issue by mhutestbyt** [google/perfetto#428]
hi perfetto team,

A quick query, how to compile perfetto python package especially in arm architecture:
- batch_trace_processor (package)
- trace_processor (package)
- race_uri_resolver (package)

I tried to copy/paste the packages directly into my arm device, it does not work. 
I found there is a buind.gn in python repository but there's no definition to indicate cpu architecture.
thanks for your kind help

**Comment by LalitMaganti** [comment]
The Python modules themselves do not have any special x86-only logic so should work fine on arm. The modules do use trace_processor_shell through [this script](https://github.com/google/perfetto/blob/master/tools/trace_processor) which does have support for linux-arm so should work fine there.

Please check if you can run trace_processor manually by following the instructions here: https://perfetto.dev/docs/quickstart/trace-analysis
