### ISSUE TITLE
No track names when parsing a systrace

### ISSUE THREAD

**Issue by adobke** [google/perfetto#431]
When parsing a systrace, we end up with just process numbers for track names instead of something like a process name.  Would it be viable to extend the systrace parser to at least adopt the name of the "main" thread where "tid == tgid", as the track name as well? (perhaps via `SetProcessNameIfUnset` ?)

Example:
This can be seen by:
1. Open the "Android Example"
2. Convert to .systrace
3. Open the converted systrace 
(or load up a different systrace)

Initial
![image](https://user-images.githubusercontent.com/535393/213967156-db448183-826c-4a1d-ac85-20789cf0577a.png)

Loaded from systrace:
![image](https://user-images.githubusercontent.com/535393/213967187-7af29b23-f5d9-494f-ae39-dcb62e80093b.png)

**Comment by LalitMaganti** [comment]
Patches are welcome - it's very unlikely the Perfetto team will get to this.
