### ISSUE TITLE
Perfetto progress indicator does not stop

### ISSUE THREAD

**Issue by kenzieschmoll** [google/perfetto#434]
![perfetto-constant-loading-indicator](https://user-images.githubusercontent.com/43759233/214927947-b9b94472-ca37-4d14-b93c-f0d1ed04b2ad.gif)

This blue loading indicator across the top of the trace viewer is persistent. What could be causing this? This gif was recorded from the embedded perfetto view in Flutter DevTools (tracked there at https://github.com/flutter/devtools/issues/5119)

**Comment by primiano** [comment]
That's usually the sign of an outstanding query that didn't complete. Maybe something goes out of sync.

**Comment by kenzieschmoll** [comment]
By query, do you mean a search query from the search bar?

**Comment by primiano** [comment]
any form of query issued against trace processor, whether comes form user actions (e.g. search bar) or a track issuing a query to fetch data. Essentially that's a sign of "trace processor is busy"
