### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by benthevining** [google/perfetto#436]
On Windows, I'm getting this error when using MSVC:
```
C:\Users\benth\Documents\melatonin_perfetto\melatonin_perfetto\melatonin_perfetto.cpp(4,1): error C2766: explicit speci
alization; 'static_state_' has already been defined
```
The line it's complaining about contains
```
PERFETTO_TRACK_EVENT_STATIC_STORAGE();
```
and I've got `PERFETTO_DEFINE_CATEGORIES` in the associated header.

Has anyone ever seen a similar error or have any ideas?

The project is [here](https://github.com/sudara/melatonin_perfetto/tree/more-tests) if you'd like to try to reproduce.

**Comment by chromy** [comment]
Ah I was going to say sounds similar although not identical to the issues described in: https://android-review.googlesource.com/c/platform/external/perfetto/+/1541747 but I see from https://github.com/sudara/melatonin_perfetto/pull/12 you already found: https://github.com/google/perfetto/issues/214.

fyi @ddiproietto & @skyostil
