### ISSUE TITLE
Failed to set property 'persist.debug.perfetto.boottrace' to '1'

### ISSUE THREAD

**Issue by zoumy** [google/perfetto#439]
➜  ~ adb shell setprop persist.debug.perfetto.boottrace 1
Failed to set property 'persist.debug.perfetto.boottrace' to '1'
See dmesg for error reason.

Device: android 13.  google pixel 6

**Comment by chromy** [comment]
And what did `dmsg` say? ☺️ (The command is `adb shell dmesg`)
