### ISSUE TITLE
MSVC: C4003 in Perfetto v32.1

### ISSUE THREAD

**Issue by mlappo** [google/perfetto#441]
After updating to a new release following new warnings fail the build
```
<basepath>\src\PerfettoTraceCategories.cpp
<basepath>\include\PerfettoTraceCategories.h(33): error C2220: the following warning is treated as an error
<basepath>\include\PerfettoTraceCategories.h(33): warning C4003: not enough arguments for function-like macro invocation 'PERFETTO_INTERNAL_DECLARE_TRACK_EVENT_DATA_SOURCE'
<basepath>\src\PerfettoTraceCategories.cpp(26): warning C4003: not enough arguments for function-like macro invocation 'PERFETTO_INTERNAL_CATEGORY_STORAGE'
```

From what I can see in the code (perfetto.h) the number of arguments seems correct to me...

**Comment by ddiproietto** [comment]
I think MSVC is partially correct in this case, the argument is empty in the end.

I sent a patch to fix this (and another MSVC issue along the way): https://r.android.com/2422501

I'll tag another release if everything works.

Thanks for reporting this!

**Comment by mlappo** [comment]
Thanks a lot @ddiproietto!
