### ISSUE TITLE
[Feature Request] Backport asyncTraceForTrackBegin to older OS versions

### ISSUE THREAD

**Issue by benjaminRomano** [google/perfetto#444]
**Background**
We have very very many async spans in our application which leads to a large number of tracks. To mitigate this issue, we've created a customization to Perfetto to support grouping async spans by "categories" (e.g. group `some_category:async_span_1`, `some_category:async_span_2` will be grouped together on a track name `some_category`).

<img width="899" alt="Screenshot 2023-02-09 at 1 41 12 PM" src="https://user-images.githubusercontent.com/9221137/217945582-e6123571-59c9-4e41-8d03-d5ad6ae0c87c.png">

We achieved this by using the very janky patch: https://gist.github.com/benjaminRomano/d92c7d2d85848872e1df2dd27e542fbd.

John Reck recently mentioned that there is a new `android.os.Trace` API for putting async traces onto specific tracks with relevant support in Perfetto to parse the new event type from `tracefs`. 

**Ask**
If possible, it would be great to backport this `asyncTraceForTrackBegin` method to older os versions through `androidx.tracing` library if possible.

This is a cross-post of the following request:
https://partnerissuetracker.corp.google.com/issues/266120229

**Comment by LalitMaganti** [comment]
So the current state of affairs with os.trace is extremely sad and we're really not happy with the current state of affairs. Unfortunately simply backporting async events per track would be a patch over the much larger issues with the API. 

We are currently exploring a way to bring the full power of Perfetto as an androidx library. It's still early days but I'm hopeful we'll be able to share more concrete info on this soon. 

For this reason, I don't think we'll want to make any public API changes to os.trace.

**Comment by benjaminRomano** [comment]
Is it possible to write directly to tracefs from in-application? If there's an example of that we could try that while waiting for a more robust solution.

**Comment by LalitMaganti** [comment]
While I would generally advise against this, theoretically there is nothing stopping you from copying what the framework does under the hood. [This file](https://cs.android.com/android/platform/superproject/+/master:system/core/libcutils/trace-dev.cpp;l=93) should point you in the right direction if you really want to go there.
