### ISSUE TITLE
Timeline start and end time are hard to read for large values.

### ISSUE THREAD

**Issue by kenzieschmoll** [google/perfetto#446]
Quoting feedback from @loic-sharma:

> The timeline start time is in seconds. If my app has been running for some time, it's a huge value that's hard to read. Consider using minutes/hours for apps that have been running for some time.
> 
> ![image](https://user-images.githubusercontent.com/43759233/218564304-dbfe1431-bcd5-41d0-ab51-cfa336eb21a7.png)
> 
> I would consider adding tooltips to the timeline start time and end time as these values aren't obvious.

Original feedback from https://gist.github.com/loic-sharma/264ab999642a617f8e4490e4812ea411, which provides feedback of the embedded Perfetto trace viewer in Flutter DevTools. Some items are specific to Flutter DevTools, and some are for Perfetto proper.

**Comment by LalitMaganti** [comment]
Folding this into https://github.com/google/perfetto/issues/272
