### ISSUE TITLE
Timeline tracks overflow for long names and star button

### ISSUE THREAD

**Issue by kenzieschmoll** [google/perfetto#447]
Quoting feedback from @loic-sharma:

> Tracks with long names do not overflow well:
> ![image](https://user-images.githubusercontent.com/43759233/218564679-481a1d7d-5baa-459a-b590-0a39c5c4d1be.png)
> The `Pin to top` star button overflows as well:
> ![image](https://user-images.githubusercontent.com/43759233/218564857-72238976-5dce-4a0d-82b5-c751e6683741.png)

Original feedback from https://gist.github.com/loic-sharma/264ab999642a617f8e4490e4812ea411, which provides feedback of the embedded Perfetto trace viewer in Flutter DevTools. Some items are specific to Flutter DevTools, and some are for Perfetto proper.

**Comment by chromy** [comment]
Thanks for reporting this! My bad, however @stevegolton fixed this recently: https://android-review.git.corp.google.com/c/platform/external/perfetto/+/2514457 Should be live on autopush other channels following soon.
