### ISSUE TITLE
TraceProcessor' object has no attribute 'http'

### ISSUE THREAD

**Issue by chenxuanyu** [google/perfetto#449]
tp = TraceProcessor(trace='F:\\zhenlv\\tracenomapprio20_policnormal_nice9_2\\trace-kona-QKQ1.210910.001-2023-01-18-17-29-52.perfetto-trace')
  File "C:\Users\chen\AppData\Local\Programs\Python\Python310\lib\site-packages\perfetto\trace_processor\api.py", line 260, in __init__
    self.http = self._create_tp_http(addr)
  File "C:\Users\chen\AppData\Local\Programs\Python\Python310\lib\site-packages\perfetto\trace_processor\api.py", line 330, in _create_tp_http
    url, self.subprocess = load_shell(self.config.bin_path,
  File "C:\Users\chen\AppData\Local\Programs\Python\Python310\lib\site-packages\perfetto\trace_processor\shell.py", line 64, in load_shell
    raise Exception(
Exception: Trace processor failed to start. Try rerunning with verbose=True in TraceProcessorConfig for more detailed information and file a bug at https://goto.google.com/perfetto-bug or https://github.com/google/perfetto/issues if necessary.
Exception ignored in: <function TraceProcessor.__del__ at 0x0000022EF68D7370>
Traceback (most recent call last):
  File "C:\Users\chen\AppData\Local\Programs\Python\Python310\lib\site-packages\perfetto\trace_processor\api.py", line 373, in __del__
    self.close()
  File "C:\Users\chen\AppData\Local\Programs\Python\Python310\lib\site-packages\perfetto\trace_processor\api.py", line 370, in close
    self.http.conn.close()
AttributeError: 'TraceProcessor' object has no attribute 'http'

**Comment by chenxuanyu** [comment]
What is the reason for this error and what is the solution

**Comment by LiangliangSui** [comment]
@chenxuanyu Hi :smile:

**Comment by LiangliangSui** [comment]
@chenxuanyu Hi :smile: 

You can try to see if you can access http://get.perfetto.dev/trace_processor, I guess it is because the subprocess failed to start successfully due to the inability to download trace_processor

**Comment by chenxuanyu** [comment]
I use python to run:
from perfetto.trace_processor import TraceProcessor
tp = TraceProcessor(trace='xxx')




I can access 
http://get.perfetto.dev/trace_processor

**Comment by LiangliangSui** [comment]
Can you provide a log using the following code?

```python
from perfetto.trace_processor import TraceProcessor, TraceProcessorConfig


config = TraceProcessorConfig(verbose=True)
tp = TraceProcessor(trace='xxx', config=config)
```

The problem is not "TraceProcessor object has no attribute 'http'", but because `trace_processor_shell --httpd` has an unknown error and throws an exception. TraceProcessorHttp is not created, so the issue title appears when the TraceProcessor#close method is called at the end description content

**Comment by chenxuanyu** [comment]
ok know，when  I update perfetto，thanks for your help

pip install --user --upgrade perfetto
