### ISSUE TITLE
Perfetto SDK illegal instruction core dump when change trace buffer size in traceconfig

### ISSUE THREAD

**Issue by horusli** [google/perfetto#450]
Hi,

do you met this issue before.

I seems met this several times, it works well before I try to resize the trace buffer, and after I change it from something says 1GB to 4GB, or from 16GB to 1GB in the following line
![image](https://user-images.githubusercontent.com/6522657/218930390-9ba164d7-a9d7-4a4b-97d8-6a7d8eb7fe81.png)

I will report illegal instruction core dump and crash.

![image](https://user-images.githubusercontent.com/6522657/218930819-ff97f648-4002-495a-b533-88823f489b78.png)

I am using perfetto V30 release and under ubuntu 20.04.

**Comment by primiano** [comment]
Do you get any other log error?
This comes from [this check in paged_memory.cc](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/base/paged_memory.cc;l=107?q=f:paged_memory.cc)

Not fully clear to me how that can happen. If the paged memory allocation failed, that should return a 0 paged mem.

**Comment by ddiproietto** [comment]
There are a couple of problems in the perfetto code that cause this: https://r.android.com/2436215 should fix them.

That said, the tracing service does not support buffers larger than 4Gb, so it should just return an error.

**Comment by ddiproietto** [comment]
The crash has now been fixed.

As mentioned earlier, the tracing service still does not support buffers larger than 4Gb. There's a way to capture larger traces though:

https://perfetto.dev/docs/concepts/config#long-traces

Hope this helps, and thanks again for the report.
