### ISSUE TITLE
The names of syscall displayed in timeline are all wrong

### ISSUE THREAD

**Issue by cjb2003425** [google/perfetto#451]
platform: arm64 linux 
kernel: 5.4

> At import time, the Trace Processor uses an internal syscall mapping table, currently supporting x86, x86_64, ArmEabi, aarch32 and aarch64. These tables are generated through the [extract_linux_syscall_tables](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/tools/extract_linux_syscall_tables) script.

I checked the extract_linux_syscall_tables and i found that the _KSRC(https://raw.githubusercontent.com/torvalds/linux/v4.20) address has already unreachable.

Please help to fix this bug!

**Comment by LalitMaganti** [comment]
Unless we have a trace to debug this I'm afraid this bug is completely unactionable.
