### ISSUE TITLE
Want to select one line

### ISSUE THREAD

**Issue by hf7612** [google/perfetto#453]
Want to select one line,is it possible?

**Comment by aMayzner** [comment]
Do you mean you want to select one row from the table? If yes, you can just
do 'SELECT * FROM (whatever table you want to use) LIMIT 1'.

**Comment by hf7612** [comment]
![image](https://user-images.githubusercontent.com/4775175/221121089-cdc75552-e916-43f5-b9db-5b3c1472f136.png)
It is like this.

**Comment by aMayzner** [comment]
You are using legacy UI, which has a best effort support, and has very few
usages. Can you try to open the trace in ui.perfetto.dev and see if it
works?

**Comment by hf7612** [comment]
I can open ui.perfetto.dev,but I very want to have this function.

**Comment by aMayzner** [comment]
I don't really understand what you mean. You can start any track (there is
a toggleable star next to the name) and it will show at top of the UI.
