### ISSUE TITLE
Python and shell execution produce different results.

### ISSUE THREAD

**Issue by wanglong001** [google/perfetto#454]
expect same results

# python
```python
query = self.trace_processor.query(f"SELECT count(*) FROM slice ")
print(query.as_pandas_dataframe())

#count(*)
#963750

query = self.trace_processor.query(f"SELECT id, name FROM slice where id = 28531")
print(query.as_pandas_dataframe())

#      id name
#0  28531  DMA
```
# shell
```shell

> SELECT count(*) FROM slice
count(*)             
-------------------- 
              954036 


> SELECT id, name FROM slice where id = 28531
id                   name                 
-------------------- -------------------- 
               28531 synchronizeEvent (hl 

Query executed in 5.432 ms
```

# expect
python.id == shell.id , python.name == shell.name,

**Comment by primiano** [comment]
The slice id is not stable, it changes as new tracks are added/removed across different versions of perfetto and hence trace processor.
VEry likely you are using a different version of TraceProcessor across python API and shell

**Comment by wanglong001** [comment]
> The slice id is not stable, it changes as new tracks are added/removed across different versions of perfetto and hence trace processor. VEry likely you are using a different version of TraceProcessor across python API and shell

Not only the ids are different between python and shell, the count of slice table in python (count= 963750) is greater than shell (count=954036). I found duplicated items in python slice table (different ids with same content).
