### ISSUE TITLE
How can perfetto show the memory usage of Chrome?

### ISSUE THREAD

**Issue by maghsk** [google/perfetto#458]
I captured a chrome trace with `memory-infra` category enabled. I tried to import this record file to perfetto, but I couldn't find any counter tracks about memory usage.

How can perfetto show the memory usage? What is the correct way to trace the memory usage of Chrome?

Thanks!

**Comment by LalitMaganti** [comment]
@betasheet for comments. I am not aware of a Chrome-only data source which gives you memory use info which shows up natively in Perfetto.

**Comment by betasheet** [comment]
Yeah, memory-infra is only supported in the legacy catapult viewer at present (e.g. chrome://tracing or the "Open in Legacy UI" button in Perfetto UI). While we may integrate this into Perfetto UI in the future, we're not actively working on this currently.
