### ISSUE TITLE
docs typo "same example" 

### ISSUE THREAD

**Issue by yszmax** [google/perfetto#46]
https://github.com/google/perfetto/blob/master/docs/README.md

`
On Linux and Android, Perfetto bundles a number of data sources that are able to gather detailed performance data from different system interfaces. For the full sets and details see the Data Sources section of the documentation. Same examples:
`

last two words should be "Some examples"

**Comment by primiano** [comment]
Thanks. Fixed in https://android-review.googlesource.com/c/platform/external/perfetto/+/1358147
