### ISSUE TITLE
UI search only starts at 4 characters

### ISSUE THREAD

**Issue by pyricau** [google/perfetto#460]
Android section names are limited to 127 characters so when using identifiers in section names we try to use a little as we can, e.g. in this example "O22". Unfortunately Perfetto won't search if there are less than 4 chars.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/557033/222302175-ce65bb35-a271-48e7-99f3-94079867579e.png">
<img width="616" alt="image" src="https://user-images.githubusercontent.com/557033/222302191-fe332011-d6fd-44e1-b092-aa948372dbd0.png">

**Comment by LalitMaganti** [comment]
@chromy FYI

**Comment by LalitMaganti** [comment]
Duplicating against https://github.com/google/perfetto/issues/475
