### ISSUE TITLE
java heap continuous dump,trace open with problems

### ISSUE THREAD

**Issue by will7856** [google/perfetto#462]
<img width="858" alt="image" src="https://user-images.githubusercontent.com/33977657/224919400-39071aa4-3cca-444c-bbb6-007523a00d2c.png">

`adb shell perfetto \
  -c - --txt \
  -o /data/misc/perfetto-traces/trace \
<<EOF

buffers: {
    size_kb: 63488
    fill_policy: DISCARD
}
buffers: {
    size_kb: 2048
    fill_policy: DISCARD
}
data_sources: {
    config {
        name: "android.java_hprof"
        target_buffer: 0
        java_hprof_config {
            process_cmdline: "com.xxx.xxx"
            continuous_dump_config {
                dump_interval_ms: 5000
            }
        }
    }
}
duration_ms: 20000

EOF
`

**Comment by chromy** [comment]
@will7856: Could you try with a larger buffer size? 

E.g. rather than:
```
buffers: {
  size_kb: 63488
  fill_policy: DISCARD
}
```

Something like:
```
buffers: {
  size_kb: 256000
  fill_policy: DISCARD
}
```

**Comment by will7856** [comment]
@chromy Yes, it works

By the way, I have another problem. When I use tools/java_heap_dump to dump data, I added the -c 5000 parameter, but it does not work. The file can only see one trace

**Comment by chromy** [comment]
Sorry I'm not sure I follow :(

Could you explain:
1. What you did
2. What you expected the result to be
3. What the actual result was

In all cases showing the full copy paste from the terminal in code blocks
(using triple backticks) is helpful.

Thanks!

**Comment by will7856** [comment]
./java_heap_dump.sh  -n com.xxx.xxx -c 5000
I ran the above command and expected to record data every 5 seconds until I stop manually. The expected trace file is as follows。It is expected to get the trace file of the continuous dump
![image](https://user-images.githubusercontent.com/33977657/224959113-422c996c-970b-40c5-9cee-00c0fa66f33f.png)

But in fact, the command stops immediately after running. Open the resulting file, as shown below
![image](https://user-images.githubusercontent.com/33977657/224958913-73090aff-4fb7-43a2-80e4-b0f9d21480e3.png)

**Comment by ddiproietto** [comment]
Thanks for reporting this!

I think `--continuous-dump` used to run the trace for 20s. When we added support for data_source_stop_timeout_ms, it reduced the time to 1s.

I definitely think it makes sense to let the trace recording go on indefinitely and stop on CTRL+C. Technically, it's a breaking change, but I doubt the current behavior was useful to anybody.

I sent a change to fix this: https://r.android.com/2485087
