### ISSUE TITLE
WASD for panning not working on alternate keyboard layouts

### ISSUE THREAD

**Issue by stefnotch** [google/perfetto#463]
Perfetto should use https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code for the WASD input, otherwise keyboard layouts like the French keyboard, Dvorak, Colemak, etc. won't work correctly.

**Comment by primiano** [comment]
Ah TIL. I think you are right.
@chromy can you pass this to Steve (Can't find his github handle right now)

**Comment by stevegolton** [comment]
Hi @stefnotch, thanks for raising this! A fix for this should have landed on master & autopush channel.

See https://github.com/google/perfetto/commit/383bc717a4205c7e9e2b1811e6d00bc54f6a9d8d#diff-b4cf04584032ecdcf316dab4ff1baf6a1d0ec1dafc61cc1a8b5ec5daabbfb917

This fix also updates the glyphs on the "Keyboard Shortcuts" page based on the user's current keyboard layout (falling back to QWERTY on browsers that don't support `keyboard.getLayoutMap()`).

Closing for now, feel free to re-open if you have any issues.
