### ISSUE TITLE
Enhancement: hide fully empty track in trace viewer

### ISSUE THREAD

**Issue by xiaoas** [google/perfetto#466]
Currently, empty tracks are always displayed, as long as there's a `track_descriptor` containing `process` `data`:

![image](https://user-images.githubusercontent.com/14904657/227404243-fcacdf22-24ae-41ba-9318-1252a904798c.png)

This gives problems when user want to customize a process(for example, change the name), but don't want to show a separate track for it. 

# How to Reproduce
1. Generate the same trace file as described in https://perfetto.dev/docs/reference/synthetic-track-event#thread-scoped-sync-slices.
2. Open it in trace viewer.

Here's the same trace file that I generated:

[sync_slice.tgz](https://github.com/google/perfetto/files/11057811/sync_slice.tgz)

# Expected Behavior
Track "My process name 1234" should not appear.

**Comment by horusli** [comment]
@LalitMaganti Is there any clue that we can begin with to hidden the default track for each process group?

**Comment by LalitMaganti** [comment]
There's nothing you can do on the producer side: this is a bug in the Perfetto UI.

If you're interested in contributing, the place to start would be [1]. You want to filter the tracks added there to ensure that only tracks with slices should be added.

[1] https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/controller/track_decider.ts;l=1042?q=f:perfetto%20f:track_dec

**Comment by horusli** [comment]
> There's nothing you can do on the producer side: this is a bug in the Perfetto UI.
> 
> If you're interested in contributing, the place to start would be [1]. You want to filter the tracks added there to ensure that only tracks with slices should be added.
> 
> [1] https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/controller/track_decider.ts;l=1042?q=f:perfetto%20f:track_dec

thanks for the reminder, I create a PR to fix this issue by fulter the default null tracker
https://github.com/horusli/perfetto/pull/1/commits/203d0128119943d54dbaf8f8f9f10a6b5feb320d
