### ISSUE TITLE
crash when clicking and dragging from RHS of UI

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#467]
I've observed a crash when clicking and dragging on tracks on the right hand side of the UI. Verified repros on Autopush channel.

```
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

Uncaught Error: Failed assertion
Error: Failed assertion
    at assertTrue (https://ui.perfetto.dev/v33.0-f9bccac79/frontend_bundle.js:2185:15)
    at FrontendLocalState.selectArea (https://ui.perfetto.dev/v33.0-f9bccac79/frontend_bundle.js:4115:32)
    at PanAndZoomHandler.onSelection (https://ui.perfetto.dev/v33.0-f9bccac79/frontend_bundle.js:382161:40)
    at DragGestureHandler.onDrag (https://ui.perfetto.dev/v33.0-f9bccac79/frontend_bundle.js:335356:22)
    at DragGestureHandler.onMouseMove (https://ui.perfetto.dev/v33.0-f9bccac79/frontend_bundle.js:335210:18)

v33.0-f9bccac79 f9bccac79bd099457b4195da7b9acc28b33b666e
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
```

# How to reproduce issue:

This can be easily reproduced with the "test/data/async-trace-1.json" trace in the test/data folder. There is nothing special about this trace other than it makes a very simple reproducer. This happens with similar protobuf traces as well.

1. open the trace: `./tools/open_trace_in_ui -i test/data/async-trace-1.json` 
2. click and drag from the right hand side of the ui in one of the traces as shown in attached video:

https://user-images.githubusercontent.com/77857237/228052524-5e18b47f-e435-48e7-9bb9-0edaa9e61e6b.mov

**Comment by LalitMaganti** [comment]
Steve: can you PTAL at this?

**Comment by ALevansSamsung** [comment]
I noticed something similar in the overview section of the UI
The following is some info I've gathered on the issue:
```
Issue is caused in part by the additional space to the right of the overview timeline. In Chrome on Windows the scrollbar gave me space to drag, but on FireFox on Linux the scrollbar was on top of the overview, so it didn't create the necessary space to cause the issue.
```
https://github.com/google/perfetto/assets/121060410/ba544b84-bf46-4ac3-b5c2-d743a3d9c11d

**Comment by ALevansSamsung** [comment]
I noticed something similar in the overview section of the UI
The following is some information I've found about the issue:
```
By dragging a selection over the scrollbar and the overview at the same time it is possible to get an error stating you have made an impossible selection.
Issue seems to be caused in part by the additional space to the right of the overview timeline.
In Chrome on Windows the scrollbar gave me space to drag, but on FireFox on Linux the scrollbar was on top of the overview, so it didn't create the necessary space.
```
https://github.com/google/perfetto/assets/121060410/5ba3c2b0-abca-424b-8e29-a293667e0fba

**Comment by cphlipot1** [comment]
Closing the issue as this appears to have been fixed since I can no longer reproduce. Feel free to re-open if you feel different.
