### ISSUE TITLE
 chrome_example_wikipedia.perfetto_trace file is corrupted

### ISSUE THREAD

**Issue by Olivert007** [google/perfetto#470]
HI, I downloaded the chrome_example_wikipedia.perfetto_trace file, from https://ui.perfetto.dev/# , but it cannot be opened, and the file is corrupted

![image](https://user-images.githubusercontent.com/26530843/228458156-144acacf-b83a-4671-abff-c54429c432e8.png)

**Comment by LiangliangSui** [comment]
The downloaded file is a proto binary file, not a compressed file, you can use a text editor like UltraEdit to open and view it.

**Comment by Olivert007** [comment]
Is this like this
![image](https://user-images.githubusercontent.com/26530843/228463186-05d9c323-b797-4523-b44a-2a08eced9ced.png)

**Comment by primiano** [comment]
In some countries ISP block access to Google Cloud Storage . I think what you are seeing is the result of cloud storage being blocked and the result being mangled.

This used to be a big problem in chrome when people were trying to check out third party dependencies.

Can't do anything about it sorry. Maybe use a VPN to download the example traces.
