### ISSUE TITLE
The text on the right side of the page is blurry

### ISSUE THREAD

**Issue by hezhanbang** [google/perfetto#471]
perfetto is used in chrome. The text on the right side of the page is blurry as In the picture below.
![blurred](https://user-images.githubusercontent.com/5327771/228748269-118acb3e-3564-4454-8350-509280529b91.png)

Google Chrome	111.0.5563.147 (Official Build) (64-bit) (cohort: Stable) 
Revision	2b5ec366bb5b68dacca9719d5d83cb7e61fb6431-refs/branch-heads/5563@{#1238}
OS	Windows 10 Version 22H2 (Build 19045.2728)
JavaScript	V8 11.1.277.17
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Command Line	"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
Executable Path	C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Profile Path	C:\Users\liyou\AppData\Local\Google\Chrome\User Data\Default
Active Variations	272b4158-ca7d8d80
df319cb2-d0ae10cc
3e7d7783-377be55a
442fcbda-ca7d8d80
ae1f041e-377be55a
2fcbfa14-377be55a
586e7649-cc1e01dd
e5726113-377be55a
13acb500-12ede6a2
ba227809-91c810ef
c5480a51-377be55a
b05e1e6c-ca7d8d80
e1ce0680-377be55a
ce1fd4ce-ca7d8d80
aa21b4f1-1f8c5973
2d660aca-377be55a
e1995fc9-377be55a
3727bfd0-377be55a
e2074ad5-cb97e0a6
5f8ff765-a90f468e
9d165456-ca7d8d80
fd59f497-ca7d8d80
eddd0d82-7723ede9
1918042f-ca7d8d80
f0acab9b-33aab9fb
89a16501-ca7d8d80
42f0e0ea-ca7d8d80
29ea62bc-ca7d8d80
b10d8f16-ca7d8d80
87f33ad6-377be55a
3095aa95-3f4a17df
36c2f983-377be55a
250dda8b-8924bcae
f14c322f-f9a43703
5be458ba-ca7d8d80
3458307a-ca7d8d80
5c2a855d-377be55a
6c862974-e6976fae
896abce4-d6b1b76f
4749874c-360c6200
cd59be9a-ca7d8d80
638300a1-ca7d8d80
14246d0d-2bf32395
776f54ba-272792a5
e521d2ef-5890d18
119b6b69-ca7d8d80
cbc04857-eea70808
9ee43808-2c38a5a4
42f1f10d-ca7d8d80
363012bc-ca7d8d80
73afac8-ca7d8d80
f6f5c542-12ede6a2
1584cf60-ca7d8d80
81b1a2c3-ca7d8d80
8c82550d-377be55a
51460774-ca7d8d80
dfa02032-ca7d8d80
a582a1b8-ad75ce17
8ddeb5cd-ca7d8d80
d6b12c5a-3d47f4f4
d92d97b4-ca7d8d80
da2d8531-377be55a
dde50ff5-ca7d8d80
d4f1a7b9-ca7d8d80
3fd33f16-ca7d8d80
eac1a994-ca7d8d80
3a4ffe07-ca7d8d80
af8f17f-377be55a
19d422be-ca7d8d80
72fb77ee-ca7d8d80
829fa6ed-ca7d8d80
f782a8be-4362e5e8
c7c34e8b-ca7d8d80
bacf219a-ca7d8d80
61c68934-f9a43703
d86fca1c-e24121f6
89c2b373-ca7d8d80
5e3a236d-4113a79e
8659ca17-ca7d8d80
1f5f0f26-ca7d8d80
7e398fb8-377be55a
83b371a5-ca7d8d80
d637cfa9-377be55a
9e5f5129-ca7d8d80
5349039a-377be55a
2b4e7fda-62c84fa4
ea90e0df-ff877e05
9a9bd697-ca7d8d80
ed2101b4-377be55a
6a8d8a11-ca7d8d80
e226f568-ca7d8d80
75ffb03a-ca7d8d80
46ed6bea-ca7d8d80
ab1a849c-ca7d8d80
b3c9749a-ca7d8d80
25fa4483-eea70808
da493d3c-ca7d8d80
5c783e42-ca7d8d80
b3c54bb3-12ede6a2
bde7927d-ca7d8d80
cdf623ec-ca7d8d80
4ff8f5b5-9c1f9d3b
ad46906e-ca7d8d80
a4dcbdd6-f8e1fd0e
de2c80ca-8edc7cd2
ca12356a-98098cf6
741e95d4-ca7d8d80
64c559ec-ca7d8d80
b3f9e06f-ca7d8d80
ea23a088-3d3eae72
b16eab85-ca7d8d80
77b7ea96-ca7d8d80
45a2f2f-ca7d8d80
4ea303a6-ecbb250e
4949c1d8-fe879ad4
e3fd1192-6edc92c7
1e8383c7-ca7d8d80
de95f00f-377be55a
9fe21c85-377be55a
15d3083e-5ce60213
1edcddf4-659d13d5
c9e4cf65-12ede6a2
fe40074a-ca7d8d80
746780a8-ca7d8d80
f112d133-ca7d8d80
31af02a2-ca7d8d80
11b90bf1-377be55a
648cc0e9-ca7d8d80
8ee7d10d-c246b8d9
65bbdcad-ca7d8d80
371f259c-ca7d8d80
9635fb98-377be55a
3e99ae8f-12ede6a2
3f2823d1-ca7d8d80
90fa3bb1-ca7d8d80
9909b8ac-ca7d8d80
afa71e8b-ca7d8d80
78962b94-ca7d8d80
90860314-ca7d8d80
7954d827-377be55a
7ec047c2-ca7d8d80
494d8760-52325d43
f47ae82a-d77354d0
e71a2099-e1cc0f14
7b2873c2-c4a95556
3ac60855-486e2a9c
f48c01d3-197f11db
63dcb6a3-a5822863
e706e746-4c073154
f296190c-45641d72
4442aae2-d7f6b13c
f690cf64-6e3b1976
ed1d377-e1cc0f14
75f0f0a0-4ad60575
710c3f90-e1cc0f14
e2b18481-75cb33fc
e7e71889-e1cc0f14
57675af7-fd6a6507
160d8d8d-ca7d8d80
1d0518a-f0c4705c
76415c5-12ede6a2
595f5eb0-ca7d8d80
bef5c006-ca7d8d80
a8cfdb40-b435379e
f9f9ca72-ed148f65
f6e6ff36-6cad7f4b
b21d000-ca7d8d80
a8220f92-4d2fac87
66b74ead-ca7d8d80
e9ed3e6a-377be55a
8d7344de-7b16118d

**Comment by liyoubdu** [comment]
@chromy,  all text in `<div class="page" />`, as you can see in the attached screen shot look, is a little blurred and tiring to the eyes.
