### ISSUE TITLE
Can't drag to reorder tracks in track group

### ISSUE THREAD

**Issue by kenzieschmoll** [google/perfetto#472]
Only tracks in a pinned group or the scrolling group can be reordered by dragging and dropping. Any thread that is in a collapsible or expandable track group cannot be dragged for reordering.
![track-group-drag-broken](https://user-images.githubusercontent.com/43759233/228948999-5a446627-1260-4935-9afa-8df6ccd731b6.gif)
While investigating https://github.com/flutter/devtools/issues/5242, I discovered that this issue is not specific to the Flutter DevTools embedding, but actually is a bug with the Perfetto web app itself.

When the`moveTrack` action is triggered, it is only applied to pinned tracks and scrolling tracks. I think this action needs handling to apply the move function to tracks within a track group as well. @chromy @LalitMaganti
https://github.com/google/perfetto/blob/master/ui/src/common/actions.ts#L424-L425

**Comment by LalitMaganti** [comment]
@stevegolton can we mark this as wontfix: I think our attitude here is that we no longer want to support any reordering at all in workspaces, is that correct?

**Comment by LalitMaganti** [comment]
Closing: I'm pretty sure we don't want to support this. We only want to support reordering within pinned tracks.
