### ISSUE TITLE
Request: add affordance to min character requirement for search

### ISSUE THREAD

**Issue by craiglabenz** [google/perfetto#475]
On the Performance page, searching within the `Timeline Events` tab for a short category name (like "gc") does nothing because my query is > 4 characters. I have no idea if that search would even work, but it'd be nice to know that I needed more characters before the system will even try.

<img width="1431" alt="Screenshot 2023-04-05 at 4 01 59 PM" src="https://user-images.githubusercontent.com/855034/230230765-cd4a069e-53fc-4f1e-bf08-7e2eb87d8eb7.png">

cc @kenzieschmoll

**Comment by kenzieschmoll** [comment]
Maybe some affordance to "force" the search could be added if the char limit cannot be lowered.

**Comment by chromy** [comment]
Pressing enter now forces the search.
