### ISSUE TITLE
Missing diamond icons with continuous dumps enabled when memory is allocated + deallocated

### ISSUE THREAD

**Issue by tkuowork** [google/perfetto#477]
Hi @stevegolton @ddiproietto 

Thanks for this tool!
I've been able to successfully run this on my target and used this to debug memory leak issues.

This issue is related to https://github.com/google/perfetto/issues/473 but not exactly the same so i figured I would open a new issue.

I have written the following test script where I am properly cleaning up memory in one method, and leaking memory in a different method. I call both methods.

source code:
```
#include <iostream>
#include <chrono>
#include <thread>

using namespace std;

class MyClass1 {
public:
    MyClass1() {
    }

    void allocate() {
        cout << "Allocating and Deallocating data" << endl;

        data = new char[5000];
        for (int i = 0; i < 5000; i++) {
            data[i] = 'a';
        }
        delete[] data;
    }

    void leak_allocate() {
        cout << "Leaking memory" << endl;

        char* leaker = new char[5000];
        for (int i = 0; i < 5000; i++) {
            leaker[i] = 'a';
        }
    }

private:
    char* data;
};

int main() {
    MyClass1* obj1 = new MyClass1();

    for (int i = 0; i < 5; i++) {
        this_thread::sleep_for(chrono::seconds(1));
        obj1->allocate();
        this_thread::sleep_for(chrono::seconds(1));
        obj1->leak_allocate();
        cout << "count " << i << endl;
    }

    return 0;
}
```

when I run this class and generate a heap profile, this is what i see:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/129458877/230972528-ddf3bdda-5715-4d51-988e-c9484eb05dcc.png">

when I click the right most diamond, the data seems correct in that I have 5 counts of leaked memory from calling:
```
obj1->leak_allocate();
```

*issue*: however, i am surprised that I don't see any diamonds in the middle because even though I am properly cleaning up memory with `allocate`, the `leak_allocate` is leaking memory every 1s.

I would have expected to see diamonds every 1 second - which i would see if I removed the line `delete[] data;`.
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/129458877/230973891-14742748-8c7c-48de-8483-b95c4536662a.png">

here is the heaptrace: 
[heapprofd-trace.zip](https://github.com/google/perfetto/files/11193100/heapprofd-trace.zip)

here are the steps that I ran:
```
// compile the src code
tkuo@tkuo-HP-Z840-Workstation:~/Documents/test$ g++ -g nonthreadLeaky.cpp -o test

// run the exec
tkuo@tkuo-HP-Z840-Workstation:~/Documents/perfetto/out/tkuo$ LD_PRELOAD=~/Documents/perfetto/out/linux_clang_release/libheapprofd_glibc_preload.so ../../../test/test

// run profetto
tkuo@tkuo-HP-Z840-Workstation:~/Documents/perfetto$ tools/heap_profile -n test -c 5 --print-config  | out/linux_clang_release/perfetto   -c - --txt   -o ~/heapprofd-trace
[393.738]    perfetto_cmd.cc:1026 Connected to the Perfetto traced service, starting tracing
^C[406.559]    perfetto_cmd.cc:1227 SIGINT/SIGTERM received: disabling tracing.
[406.577]    perfetto_cmd.cc:1175 Trace written into the output file

// run traced
tkuo@tkuo-HP-Z840-Workstation:~/Documents/perfetto/out/linux_clang_release$ ./traced
```

 i am running this all on the following system:
 ```
 tkuo@tkuo-HP-Z840-Workstation:~/Documents/perfetto$ uname -ar
Linux tkuo-HP-Z840-Workstation 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
tkuo@tkuo-HP-Z840-Workstation:~/Documents/test$ g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

is this by design? or do I need to configure `heap_profile` in a different way?

thanks!

**Comment by ddiproietto** [comment]
> is this by design? or do I need to configure heap_profile in a different way?

Neither, this appears to be a bug.

For performance reason, we batch processing `free()` records: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/profiling/memory/unwinding.cc;l=434;drc=2e3a133b5f87be51ffb9e6945dd34dedf9ab4022

We can probably fix it by flushing the batch before emitting a dump. I'll send a fix in the next couple of days.

Thanks a lot for reporting this!

**Comment by tkuowork** [comment]
@ddiproietto awesome thanks!
