### ISSUE TITLE
Why is there no table to store deviceProperties?

### ISSUE THREAD

**Issue by wanglong001** [google/perfetto#478]
For a format like this, I need to use this attribute when analyzing.
Otherwise, I need to reload the source file, which is slow.

```json
{
  "schemaVersion": 1,
  "deviceProperties": [
    {
      "id": 0, "name": "NVIDIA GeForce RTX 3090", "totalGlobalMem": 25769279488,
      "computeMajor": 8, "computeMinor": 6,
      "maxThreadsPerBlock": 1024, "maxThreadsPerMultiprocessor": 1536,
      "regsPerBlock": 65536, "regsPerMultiprocessor": 65536, "warpSize": 32,
      "sharedMemPerBlock": 49152, "sharedMemPerMultiprocessor": 102400,
      "numSms": 82, "sharedMemPerBlockOptin": 101376
    }
  ]
}
```

**Comment by primiano** [comment]
I am not 100% sure I understand the question. I think that stuff is available in the "metadata" table in trace processor in the form of key-value pairs. See screenshot below

![image](https://user-images.githubusercontent.com/7137473/231111975-713a7eb9-cc80-4096-bc89-356846786eff.png)

**Comment by LalitMaganti** [comment]
JSON traces are parsed on a best-effort basis. Currently, we do not ingest the `deviceProperties` key and this is very far down on the priority list to be worth investigating.

Patches to add support for this are welcome by following the guidelines at https://perfetto.dev/docs/contributing/getting-started

**Comment by wanglong001** [comment]
I add a feature for this issue: https://android-review.googlesource.com/c/platform/external/perfetto/+/2535406

```json
{
  "schemaVersion": 1,
  "deviceProperties": [
    {
      "name": "NV AAAAA", "totalGlobalMem": 33822867456
    },
    {
      "name": "NVIDIA GeForce RTX 3090", "totalGlobalMem": 25769279488,
      "computeMajor": 8, "computeMinor": 6,
      "maxThreadsPerBlock": 1024, "maxThreadsPerMultiprocessor": 1536,
      "regsPerBlock": 65536, "regsPerMultiprocessor": 65536, "warpSize": 32,
      "sharedMemPerBlock": 49152, "sharedMemPerMultiprocessor": 102400,
      "numSms": 82, "sharedMemPerBlockOptin": 101376
    }
  ]
}
```

<img width="818" alt="image" src="https://user-images.githubusercontent.com/14817376/231770858-dc77c311-9314-4dc6-8896-f9d72fbe6b43.png">
<img width="1887" alt="image" src="https://user-images.githubusercontent.com/14817376/231770934-7970442a-894c-4428-b1de-8024aa4f197a.png">
<img width="1892" alt="image" src="https://user-images.githubusercontent.com/14817376/231771021-36e0086c-93d8-45d3-9efe-376751941086.png">
