### ISSUE TITLE
ATRACE capture fails when android:process includes ":" character

### ISSUE THREAD

**Issue by cutephoton** [google/perfetto#48]
I have two processes. xyz.qrs:tuv and abc.def; The xyz.qrs:tuv process is package xyz.qrs with service tuv. Specifying xyz.qrs yields no results for that process, but captures abc.def. As soon as I write "xyz.qrs:tuv", nothing is captured. What's going on here? Do I need the :tuv?
```
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            atrace_apps: "xyz.qrs:tuv" # fails to capture anything for all processes
            atrace_apps: "xyz.qrs" # OK
            atrace_apps: "abc.def" # OK
        }
    }
}
```
There is a bug: src/traced/probes/ftrace/ftrace_config_utils.cc
https://github.com/google/perfetto/blob/af5653134716efec117a9428c7f9b44d3e5fbb1d/src/traced/probes/ftrace/ftrace_config_utils.cc#L28-L30
Doesn't allow ':' characters which are used in multiple android processes via `android:process=":tuv"` in manifest.

**Comment by primiano** [comment]
yes, sad.
Would you mind sending a CL to fix that? 
See https://perfetto.dev/docs/contributing/getting-started

**Comment by cutephoton** [comment]
When I have a moment, I will try to remember to circle back to this. Do you think it should be limited to any character besides control, whitespace, or comma? Or should I limit to ':' specifically? Android does not document any limitations, just that ':' has a specific special meaning. Otherwise it accepts 'string'.

**Comment by tilal6991** [comment]
I don't think there should be any restrictions tbh - I feel maybe we were being a bit cautious. We should discuss more on the CL.

**Comment by primiano** [comment]
I would probably do anything >= 32 and < 127, which is the visible ascii range.
We should probably fix both ftrace and atrace and get rid of the IsGood*tracePunctuation methods altogether.

**Comment by primiano** [comment]
let me send a CL to fix this.

**Comment by primiano** [comment]
Fixed in https://android-review.googlesource.com/c/platform/external/perfetto/+/1372117
