### ISSUE TITLE
How to convert to .pftrace or .perf format

### ISSUE THREAD

**Issue by RishiTejaMadduri** [google/perfetto#482]
I have a trace in a json file that follows the google chrome trace event format and I am able to load this json directly into the Perfetto UI and everything works. What I want to know is how can I use Protozero to convert this json file into the native perfetto format? Assuming I have the `.proto` message

**Comment by LalitMaganti** [comment]
Information on writing TrackEvent manually can be found in our docs [here](https://perfetto.dev/docs/reference/synthetic-track-event)

**Comment by RishiTejaMadduri** [comment]
@LalitMaganti Thank you for getting back to me! I came across [this](https://github.com/google/perfetto/issues/99#issue-817798750) after opening this issue. But @chromy says converting from a json trace to .proto trace is not possible. Has that changed? 

I was able to follow the instructions [here](https://perfetto.dev/docs/design-docs/protozero) to generate a `test_msg.pbzero.h`. I am looking for more instructions on how to go to native perfetto trace format from there

**Comment by LalitMaganti** [comment]
If you are looking for a tool to "convert" JSON traces to Perfetto, that does not exist and will not do so. OTOH if you want to write protos in a way such that Perfetto can interpret it, the above guide I linked is the best advice I can provide. 

Note that you do not need to use protozero to write traces in a manner Perfetto can interpret. You can also just use the official protobuf library and likely that will be a lot easier to use.

**Comment by RishiTejaMadduri** [comment]
Thank you @LalitMaganti, this was very helpful!
