### ISSUE TITLE
`DynamicString` may call `strlen` on `nullptr`

### ISSUE THREAD

**Issue by drott** [google/perfetto#484]
The `DynamicString` constructor in https://github.com/google/perfetto/blob/ef2774e07ca5e6e6484c5dff043ebc331dd0de9d/include/perfetto/tracing/string_helpers.h#L50 in a non DCHECK build may call strlen on a nullptr. 

This can lead to crashes, when a passed in `char*` string is null.

More details in @bungeman's analysis in https://bugs.chromium.org/p/chromium/issues/detail?id=1431096#c35

In this issue: 
`  TRACE_EVENT1("fonts", "FontServiceThread::MatchFamilyName", "family_name",
               TRACE_STR_COPY(family_name));` 
occasionally lead to crashes.

**Comment by primiano** [comment]
I think the real issue there is that TRACE_STR_COPY should not be used with null strings.
The DCHECK enforces (at debug time) that.

In other words: tracing does not expect null strings to be traced, in the same way libc's strlen and other don't expect null strings.

Not sure what's the best course of action here. If we feel there are so many accidental-nullptr uses there, maybe we should reconsider and accept also nullstrings? 

@ddiproietto FYI

**Comment by drott** [comment]
Thanks for taking a look. While the `DCHECK` does check that this macro is not to be used with null strings, it's still easy to make that mistake for someone who places a `TRACE_...` macro (and doesn't read the TRACE_STR_COPY) source. It is at least surprising to me and @bungeman that trace macros introduce such a nullptr derefence risk. I see them as a performance analysis and debugging tool - in my view they should be very robust and avoid introducing additional crash risks if possible. Perhaps the `TRACE_STR_COPY` macro could then also use a placeholder string if a null string is specified. - Thanks for considering.

**Comment by ddiproietto** [comment]
I tend to agree with Primiano here.

I wouldn't expect printf nullptr or LOG(INFO) << (char*) nullptr to work. I think the same applies for the macros.

The difference is the tracing macros are only exercised if tracing is enabled, which makes it a little bit harder to cover.

@betasheet might have a different idea, based on the experience in chromium, otherwise I don't think we should change anything here.

**Comment by drott** [comment]
Please note that we ran into a P0 due to the surprising effect of this macro, which was a pain to debug. I don't agree with the evaluation here.  What would be the disadvantage of a null-check?

**Comment by betasheet** [comment]
Looks like the legacy macros did accept null strings in the past: https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:base/trace_event/trace_arguments.cc;drc=c4d973cb4150caeb418106a46709016d128e07b9;l=209

So I'd say for backwards-compat reasons we probably need to handle null string arguments in the legacy macros exposed by the SDK. I think this is likely a bug that was introduced by Chrome's migration to the SDK.

**Comment by ddiproietto** [comment]
> So I'd say for backwards-compat reasons we probably need to handle null string arguments in the legacy macros exposed by the SDK. I think this is likely a bug that was introduced by Chrome's migration to the SDK.

Oh, I didn't know that. Makes sense, thanks!

**Comment by drott** [comment]
Appreciate the additional info, @betasheet - and thanks @ddiproietto for considering a change here.
