### ISSUE TITLE
way of allowing event overlap in the same tracker using perfetto sdk

### ISSUE THREAD

**Issue by horusli** [google/perfetto#485]
Sorry to raise this issue again, still troubled by the event overlap issue and we want this badly to allow convient analysis purpose.

by searching the issue list I found a similar one with protobuf implemention, and seems there is walkaround.
https://github.com/google/perfetto/issues/438
Just want to make sure if this way also apply when using perfetto sdk?
I just try to change the uuid for before emit a event to make sure all event with the same trackername and different uuid.
But the output still the same.(Using perfetto v32.1 release)

**Comment by ddiproietto** [comment]
> Just want to make sure if this way also apply when using perfetto sdk?

If I understand correctly what you're asking, yes it should be possible to emit overlapping events with the SDK.

>I just try to change the uuid for before emit a event to make sure all event with the same trackername and different uuid.
But the output still the same.(Using perfetto v32.1 release)

I'm not sure I understand. Could you expand a little bit on:
* What does your code look like?
* What's the result that you get in the UI?
* What's the result that you instead expect/want to achieve?

Thanks!

**Comment by horusli** [comment]
> > Just want to make sure if this way also apply when using perfetto sdk?
> 
> If I understand correctly what you're asking, yes it should be possible to emit overlapping events with the SDK.
> 
> > I just try to change the uuid for before emit a event to make sure all event with the same trackername and different uuid.
> > But the output still the same.(Using perfetto v32.1 release)
> 
> I'm not sure I understand. Could you expand a little bit on:
> 
> * What does your code look like?
> * What's the result that you get in the UI?
> * What's the result that you instead expect/want to achieve?
> 
> Thanks!

I just found that I am creating a tracker with the same tracker id and after modifying the name & uuid with set_name() and set_uuid() function calls. the trace event b/e is dispatch, the problem might be I need to create a new tracker with different ids.

I changed my code a little bit.
below is what it looks like now:
![image](https://user-images.githubusercontent.com/6522657/233365710-6a4ce21a-5c91-4c68-9393-542d0bc8de01.png)

It indeed has expected output of early done event finish first. but there is still another problem.
I expect all slices to fall into the perf_event tracker, but it falls into different trackers named by the cmdtype.
not sure if I missed anything, could you kindly help to provide some suggestions?

![image](https://user-images.githubusercontent.com/6522657/233364628-81f426b4-40bb-4409-9761-11f1cc6a104d.png)

**Comment by ddiproietto** [comment]
I'm not sure I understand all the context from your code and your description, but the problem might be that you're incrementing `mem_trace_count` for each slice that you're emitting.

Since you're constructing the `Track` with an id (the first parameter) of `mem_trace_count + 100 + tracker_id`, each time you increment mem_trace_count, you're effectively asking for a different track.

Also maybe there's some other code above that I don't see, but normally you shouldn't use `TRACE_EVENT` and `TRACE_EVENT_END`. You should use `TRACE_EVENT_BEGIN` and `TRACE_EVENT_END`.

**Comment by horusli** [comment]
thanks for the reminder, I just fix the trace_event_begin issue
still they  shows up on top tracker when different cmdtype trackers instead of the perf_event tracker under the specified process group.

![image](https://user-images.githubusercontent.com/6522657/233512229-cf5a7e28-589d-4205-a7cb-28e7ddb629d0.png)


I just did a quick test by fixing the trackerid when constructing a track, the slice overlap is not as expect, ReleaseDesc end first, then Perfdump and LoadDesc, the actual situation is just the reverse. 
![image](https://user-images.githubusercontent.com/6522657/233511396-eb4421cc-88c2-4c21-8622-998d9a30bbdc.png)

I will shorten the test case and provide the src for you to further later on.

**Comment by horusli** [comment]
please check attach test case

test1:
![image](https://user-images.githubusercontent.com/6522657/233688869-4305f41f-f91d-4303-98a4-d238818b3988.png)

test2:
![image](https://user-images.githubusercontent.com/6522657/233689059-311e456c-4150-4aa4-90c8-59193b0fae5e.png)

both case are unexpected, as the intention is to place them in the default process track with tracker name perf_event and correct event ovelapping.
[event_overlap_test.cc.tar.gz](https://github.com/google/perfetto/files/11297643/event_overlap_test.cc.tar.gz)

**Comment by horusli** [comment]
> > test1
> 
> This is working as intended from perfetto POV. When you emit a TRACK_EVENT_END, you cannot specify which slice you're ending, the latest one (in terms of timestamp), is ended. The right thing to do is to emit them in different tracks.
> 
> > test2
> 
> I think you're close with this code. There are a couple of problems:
> 
> * `event_count` should start from 1, not 0. `perfetto::Track(0, perfetto::ProcessTrack::Current());` doesn't create a new track (the 0 is `xor`d with the process UUID, creating the same track).
> * you shouldn't do `desc.set_uuid`. If you compile without NDEBUG, perfetto will complain about this.
> 
> with these two changes, I think you can achieve your goal.

thanks for the reminder, I will take a try.
is there other alternatives to change the uuid of a tracker?

**Comment by ddiproietto** [comment]
> is there other alternatives to change the uuid of a tracker?

Instead of changing the UUID of a track, you should just use a different id when creating the Track object. You were already doing that correctly by using `event_count` (except that it shouldn't be 0).

**Comment by horusli** [comment]
> 

thanks it works as expected now.

![image](https://user-images.githubusercontent.com/6522657/234579931-2968bc03-1813-4d44-a38e-1ecebe762fa3.png)

paste the code below just in case someone has the same need in the further.

`    InitializePerfetto();
    auto tracing_session = StartTracing();
    uint64_t event_count = 1;
    uint64_t timestamp = perfetto::TrackEvent::GetTraceTimeNs();
    std::vector<std::string> event_list;
    event_list.insert(event_list.end(), {"setdesc", "releasedesc", "perfdump", "runtask", "runtask", "runtask"});

    for (const auto &event : event_list) {
        perfetto::DynamicString dyn_name = perfetto::DynamicString(event);
        perfetto::Track mytracker = perfetto::Track(event_count, perfetto::ProcessTrack::Current());

        perfetto::protos::gen::TrackDescriptor desc = mytracker.Serialize();
        desc.set_name("perf_event");
        perfetto::TrackEvent::SetTrackDescriptor(mytracker, desc);

        TRACE_EVENT_BEGIN("binning", dyn_name, mytracker, timestamp + +event_count * 100000);
        TRACE_EVENT_END("binning", mytracker, timestamp + 400000 * event_count);
        event_count++;
    }

    StopTracing(std::move(tracing_session));
    return 0;`
