### ISSUE TITLE
Arbitrary hierarchy using protobufs

### ISSUE THREAD

**Issue by tannery-cerebras** [google/perfetto#486]
I am using using the Perfetto protobuf to generate traces.
Ideally, I want to make hierarchies of arbitrary depth where each level of the hierarchy is expandable/collapsable.

Today I can create a hierarchy of process -> threads and the process row is collapsable, however I don't think there is a way to do this with threads.

Is there a way to do this with protobufs today?
If not, is it something worth supporting?

**Comment by LalitMaganti** [comment]
The protobuf format already supports arbitrary levels of nesting through the use of parent_uuid. This is really a question of adding arbitrary layers of nesting in the UI: this is something we are looking into adding but I'd not available at the moment.

**Comment by LalitMaganti** [comment]
Given the more extensive discussion on https://github.com/google/perfetto/issues/651, I'm going to merge this issue into that.
