### ISSUE TITLE
Feature request: support sql module for python api

### ISSUE THREAD

**Issue by kcwu** [google/perfetto#487]
With command line version of trace_processor_shell, we can split complex queries into different sql files and imported via `--add-sql-module`. However, python api doesn't support this kind of feature. It's inconvenient to write sql module and reuse.

**Comment by aMayzner** [comment]
This is a very good idea, but unfortunately not a high priority for us right now. Please, feel free add this (https://perfetto.dev/docs/contributing/getting-started) and we would be happy to review.
