### ISSUE TITLE
pip install perfetto-trace-processor and perfetto-trace-parser error 

### ISSUE THREAD

**Issue by zw-626** [google/perfetto#489]
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
ERROR: Could not find a version that satisfies the requirement perfetto-trace-parser (from versions: none)
ERROR: No matching distribution found for perfetto-trace-parser

**Comment by LalitMaganti** [comment]
The command to use is `pip install perfetto`
