### ISSUE TITLE
Add Tracing for /proc/<pid>/smaps_rollup Attempt # 2

### ISSUE THREAD

**Issue by funfoolsuzi** [google/perfetto#490]
Following up on the comment from @primiano in [the closed issue here](https://github.com/google/perfetto/issues/258#issuecomment-1058621648). I need an option to track PSS of certain processes in our system with Perfetto. There are already an initial version of this working in our internal version of Perfetto. But it is currently on by default and can't be turned off. Currently with our setup, the latency overhead doesn't seem to be big even polling `/proc/<pid>/smaps_rollup` for all processes. So I think it is reasonable to have this optional feature available. So I'm hoping to follow up the original issue and contribute to Perfetto to make this available for all.

Here is what I have in mind:
1. A toggle in trace config. Let's say `scan_processes_smaps_rollup`. Pls let me know if you better name for the toggle. Here is an example of what a working trace config would look like:
```
data_sources: {
  config {
      name: "linux.process_stats"
      process_stats_config {
          scan_all_processes_on_start: true
          scan_processes_smaps_rollup: true
          proc_stats_poll_ms: 1000
      }
  }
}
```
2. Having the above example trace config would make `/proc/<pid>/smaps_rollup` to be scanned along with ` /proc/<pid>/stats` at internal specified with `proc_stats_poll_ms`. The `smaps_rollup` numbers would be bundled up with `ProcessStats.Process` in `process_stats.proto` somehow. I'm thinking about having a Message defined like this:
```protobuf
message ProcessStats {
  message Thread {...}

  message SmapsRollup {
    optional uint64 rss_kb = 1;
    optional uint64 pss_kb = 2;
    optional uint64 pss_anon = 3;
    optional uint64 pss_file = 4;
    optional uint64 pss_shmem = 5;
    optional uint64 shared_clean = 6;
    ...
  }
  message Process {
    ...
    optional SmapsRollup smaps_rollup = 15;
  }
  repeated Process processes = 1;
  ...
}
```

Is the above a good starting point? Pls let me know what you guys think? If this looks good to you guys, I'm hoping to start drafting up the changes in the next few days. :)

**Comment by primiano** [comment]
I'm okay with this as proposed (i.e. with an extra toggle `scan_processes_smaps_rollup`).

Small note: I'd avoid nesting into a submessage (SmapsRollup) and just move fields to the `Process` message, e.g.:

```
message Process {
  // See /proc/[pid]/status in `man 5 proc` for a description of these fields.
  optional uint64 vm_size_kb = 2;
  ...
  optional uint64 vm_hwm_kb = 9;

  // These fields are set only when scan_smaps_rollup=true
  optional smr_rss_kb = 10;
  optional smr_pss_kb = 11;
  optional smr_pss_anon = 12;
  ...

}
```

rationale: submessages have a cost (~6 bytes IIRC), and they adds up when multiplying x 100-500 processes

**Comment by funfoolsuzi** [comment]
Submitted CL here: https://android-review.googlesource.com/c/platform/external/perfetto/+/2565650

![Screenshot of how it looked like with UI](https://user-images.githubusercontent.com/20995331/234761369-9e1ce686-d1a9-4602-b6cc-50316135877b.png)

**Comment by funfoolsuzi** [comment]
<img width="671" alt="Screenshot 2023-05-02 at 12 48 59 PM" src="https://user-images.githubusercontent.com/20995331/235770335-1d0adbb3-30e0-48bd-b9ae-217238a6ffbc.png">

**Comment by code4er** [comment]
Hello, have you encountered the permission problem?
I cannot  catch the smaps_rollup of  most processes except for traced and traced_probes

**Comment by primiano** [comment]
@code4er two things to check:

1. Make sure you run traced_probes as root
2. If you don't want to run it as root, you need to check hidepid in the /proc mount options. See https://man7.org/linux/man-pages/man5/proc.5.html
