### ISSUE TITLE
Why the UI  can not show a quantized view of CPU usage ?

### ISSUE THREAD

**Issue by LittleLmc** [google/perfetto#492]
In https://perfetto.dev/docs/data-sources/cpu-scheduling) ,it says "When zoomed out, the UI shows a quantized view of CPU usage, which collapses the scheduling information:"
But I  Can not show the cpu usage. Can you tell me the details step ?
![Uploading [image.png…]()]([url]([url](![Uploading cpu usage.jpg…]())))

**Comment by LalitMaganti** [comment]
This was removed some time ago from the UI because it caused more confusion than it helped. Basically, people did not realise that under the CPU usage graph, there was scheduling information present.

I've sent https://r.android.com/2570950 to update the documentation.

**Comment by LittleLmc** [comment]
@LalitMaganti  I  can not get the link:https://r.android.com/2570950  ,Can you give me directly?

**Comment by LalitMaganti** [comment]
There is no other link I can provide. The change just updated docs.perfetto.dev to remove reference to the quantized view. There is no replacement.
