### ISSUE TITLE
commandline generated by web ui contains invalid proto

### ISSUE THREAD

**Issue by fergald** [google/perfetto#495]
E.g. [this config](https://ui.perfetto.dev/#!/?s=c2fd1f1a9a6c97b7fa2fd261d11311ae28812a48a055444909af30f15894653c) fails to run. It's generated by web UI [32-1](https://android.googlesource.com/platform/external/perfetto/+/1f0f1aa6babb0b3ff273c5102aa677b2604e9a4e/ui) so I checked out perfetto at tab `v32.1` and built it.

The error is

```
-:25:31 error: Expected value of type enum for field client_priority in proto ChromeConfig instead saw 'USER_INITIATED'
            client_priority: "USER_INITIATED"
                              ^~~~~~~~~~~~~~ 
-:35:31 error: Expected value of type enum for field client_priority in proto ChromeConfig instead saw 'USER_INITIATED'
            client_priority: "USER_INITIATED"
                              ^~~~~~~~~~~~~~ 
-:56:41 error: Expected value of type uint64 for field timestamp_unit_multiplier in proto TrackEventConfig instead saw '1000'
            timestamp_unit_multiplier: "1000"
                                        ^~~~ 
-:69:31 error: Expected value of type enum for field client_priority in proto ChromeConfig instead saw 'USER_INITIATED'
            client_priority: "USER_INITIATED"
                              ^~~~~~~~~~~~~~ 
[587.813]     perfetto_cmd.cc:592 The trace config is invalid, bailing out.
```

It also failed when I build at head (e29cb505e86f2b3368e56f4c39399735dcfb5a90).

Doing `s/"USER_INITIATED"/USER_INITIATED/` and `s/"1000"/1000/` allows the command to run.

**Comment by LalitMaganti** [comment]
Looks like a bug in the config generation code. @chromy @stevegolton FYI

**Comment by chromy** [comment]
`USER_INITIATED` is a matter of adding add some strings here: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/controller/record_controller.ts;l=127?q=record_controller%20f:ts$

`timestamp_unit_multiplier` is adding something here: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/controller/record_controller.ts;l=139?q=ui%2Fsrc%2Fcontroller%2Frecord_controller.ts%20f:ts&ss=android%2Fplatform%2Fsuperproject

Although we should maybe use bigints now and reach record_controller to do the proper thing.

**Comment by chromy** [comment]
Should be fixed in canary, stable roll coming soon!
