### ISSUE TITLE
Counter track dropdown not visible on Canary & Autopush

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#496]
The Counter track dropdown not visible in the Perfetto UI. This appears to have broken recently and was working as recently as V31, but i have not checked all intermediate versions, so the regression could have happened at any point in that timeframe.

# How to reproduce:
2. Click "Open Android Example" on the left hand side of the UI
3. Expand the "com.google.android.GoogleCamera" process.
5. Click on the trend line icon next to the pin on the "GPU completion" track

# Expected behavior:
should look like this (screenshot from V31):
![image](https://user-images.githubusercontent.com/77857237/235767478-3bbdafa8-7588-4b57-ad91-e41fe6c73bb9.png)

# Actual behavior:
looks like this(screenshot from Autopush/V33.0 ): 
![image](https://user-images.githubusercontent.com/77857237/235767851-cc82baa2-abdf-43e2-9cda-b29299514373.png)
Note dropdown menu is missing

**Comment by LalitMaganti** [comment]
@chromy @stevegolton this may be a problem as we just pushed canary to stable today.

**Comment by chromy** [comment]
Yeah :/ I'll revert that once I get home.
