### ISSUE TITLE
AttributeError: 'TraceProcessor' object has no attribute 'http'

### ISSUE THREAD

**Issue by LittleLmc** [google/perfetto#497]
`from perfetto.trace_processor import TraceProcessor
from perfetto.trace_processor.api import TraceProcessorConfig
tp = TraceProcessor(trace='trace.perfetto-trace',config=TraceProcessorConfig(bin_path='trace_processor'))

qr_it = tp.query('SELECT name FROM slice') 
for row in qr_it: 
  print(row.name)`

Error:

Traceback (most recent call last):
  File "E:\04_Codeback\StudyCode\pyhon\process.py", line 3, in <module>
    tp = TraceProcessor(trace='trace.perfetto-trace',config=TraceProcessorConfig(bin_path='trace_processor'))
  File "D:\install\anaconda3\lib\site-packages\perfetto\trace_processor\api.py", line 260, in __init__
    self.http = self._create_tp_http(addr)
  File "D:\install\anaconda3\lib\site-packages\perfetto\trace_processor\api.py", line 330, in _create_tp_http
    url, self.subprocess = load_shell(self.config.bin_path,
  File "D:\install\anaconda3\lib\site-packages\perfetto\trace_processor\shell.py", line 66, in load_shell
    raise Exception(
Exception: Trace processor failed to start. Try rerunning with verbose=True in TraceProcessorConfig for more detailed information and file a bug at https://goto.google.com/perfetto-bug or https://github.com/google/perfetto/issues if necessary.
Exception ignored in: <function TraceProcessor.__del__ at 0x0000019A35CE1DC0>
Traceback (most recent call last):
  File "D:\install\anaconda3\lib\site-packages\perfetto\trace_processor\api.py", line 373, in __del__
    self.close()
  File "D:\install\anaconda3\lib\site-packages\perfetto\trace_processor\api.py", line 370, in close
    self.http.conn.close()
AttributeError: 'TraceProcessor' object has no attribute 'http'

**Comment by chromy** [comment]
Are you using Python3 or Python2?

**Comment by LittleLmc** [comment]
Python3

**Comment by LalitMaganti** [comment]
This a dupe of https://github.com/google/perfetto/issues/449.

 Generally the problem is that you do not have access to `https://get.perfetto.dev/trace_processor` or `https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v34.0/linux-amd64/trace_processor_shell`.

**Comment by LalitMaganti** [comment]
Those files are public so it's really a question of why your ISP or internet connection is blocking the download. An workaround might be to download the shell binary manually and pass it to bin_path but I'd suggest figuring out the root cause of your internet issue.

**Comment by LittleLmc** [comment]
@LalitMaganti  Can you send me the trace_processor_shell file? And tell me how to configure it?

**Comment by LalitMaganti** [comment]
I've provided the link above. Not sure what else I can do there really. You can also download the binary at the releases page of GitHub [here](https://github.com/google/perfetto/releases/tag/v34.0) - it's available inside the zip file for your architecture.

Configuration-wise, you just need to set the `bin_path` field of TraceProcessorConfig in your code to point to the downloaded binary.

**Comment by LittleLmc** [comment]
@LalitMaganti   Doese it like this?
tp = TraceProcessor(trace='trace.perfetto-trace',config=TraceProcessorConfig(bin_path='trace_processor_shell')) 
?

**Comment by LalitMaganti** [comment]
If the binary is in your working directory, then yes. You can also pass an absolute path to the binary.

**Comment by LittleLmc** [comment]
@LalitMaganti  Thanks!
