### ISSUE TITLE
Is there real-time mode for trace service?

### ISSUE THREAD

**Issue by dionysus1016** [google/perfetto#498]
in https://github.com/google/perfetto/issues/168, I was looking for an easy way to customize UI, but I am unsure whether it is in the roadmap, so I am trying to ingest the data from the tracing service directly, and draw the diagram by our UI framework, is this way encouraged? if so,  is it possible to tell the tracing service to stream the buffer to clients in real-time?

**Comment by LalitMaganti** [comment]
While a lot of the services of Perfetto were designed for this to be a
possibility at some point, there was never a strong enough usecase for us
to implement the end to end story.

The basic premise is: it's not impossible but given the maturity of the
project there will likely be some non trivial blockers which will need
investment to solve. That means out of the box, what you're looking for is
not possible.

However, if you do want to invest in making this possible by contributing
that would be something we're open to.

**Comment by dionysus1016** [comment]
Thanks for your reply!
