### ISSUE TITLE
Writing a custom importer for Perfetto

### ISSUE THREAD

**Issue by RishiTejaMadduri** [google/perfetto#499]
Is there any documentation on how to write a custom importer for Perfetto? I was able to implement a transcoder logic that converts files in my format `.xyz` to perfetto acceptable protobuf format and I am able to visualize the trace in perfetto. I was wondering if there was a way I could integrate this into my fork of perfetto so I could directly load the `.xyz` format and run the transcoder logic in the background instead of having to run the script manually. 

I can see that perfetto allows loading json and a few other file formats. I want to be able to add another option for my native format

**Comment by LalitMaganti** [comment]
There is no formal documentation for this but others have in the past been able to write their importers by looking at existing examples.

Here is probably the simplest importer which ingests ninja trace files: https://github.com/google/perfetto/tree/master/src/trace_processor/importers/ninja

The JSON importer can be found at: https://github.com/google/perfetto/tree/master/src/trace_processor/importers/json

And the systrace importer: https://github.com/google/perfetto/tree/master/src/trace_processor/importers/systrace

There should give enough of a starting point for writing your own importer.
