### ISSUE TITLE
Regarding the trace change of the new s32g kernel that cannot be opened by the ui program

### ISSUE THREAD

**Issue by aemonair** [google/perfetto#500]
Hello, I found that the trace file generated on the new kernel of s32g cannot be opened in perfetto ui. After comparison, I found that the kernel trace of s32g has several indicators, such as `need-resched-lazy`, `preempt-lazy-depth`, `migrate-disable`, if you encounter such a problem, you can modify the regular part in the file path `"perfetto/src/trace_processor/importers/systrace/systrace_line_tokenizer.cc"`, and set `R"( [a-zA-Z0-9.]{0,5}` is changed to `R"([a-zA-Z0-9.]{0,8}`, after recompiling the ui program, the trace under s32g can be loaded file up;

**Comment by primiano** [comment]
@ddiproietto @rsavitski

**Comment by primiano** [comment]
@aemonair thanks for the report. by any chance do you have a trace from a s32g handy? Happy to fix this

**Comment by LalitMaganti** [comment]
Do note that systrace parsing is handled on a best-effort basis in any case: consider using the Perfetto tooling to collect traces to be sure that it will be parsed correctly.

**Comment by aemonair** [comment]
Thank you very much for your reply. I directly took the trace file under s32g to open it in perfetto ui. It’s probably like this. It’s just because the kernel version is different, so it just doesn’t match. I will consider using perfetto tools. Thanks again for your reply. 
This issue can be closed.

```
TRACE:
# tracer: nop
#
# entries-in-buffer/entries-written: 34/34   #P:8
#
#                                          _-------=> irqs-off
#                                         / _------=> need-resched
#                                        | / _-----=> need-resched-lazy
#                                        || / _----=> hardirq/softirq
#                                        ||| / _---=> preempt-depth
#                                        |||| / _--=> preempt-lazy-depth
#                                        ||||| / _-=> migrate-disable
#                                        |||||| /     delay
#           TASK-PID       TGID    CPU#  |||||||  TIMESTAMP  FUNCTION
#              | |           |       |   |||||||      |         |
           <...>-1636    (-------) [000] .......  7784.438774: tracing_mark_write: trace_event_clock_sync: parent_ts=7784.394387
           <...>-1636    (-------) [000] .......  7784.438787: tracing_mark_write: trace_event_clock_sync: realtime_ts=7784
           <...>-1857    (-------) [004] .......  7795.782918: tracing_mark_write: B|1857|TraceLog
           <...>-1857    (-------) [004] .......  7795.782929: tracing_mark_write: E|1857
```
