### ISSUE TITLE
Duplicate tracks in UI when associated with a PID and/or TID

### ISSUE THREAD

**Issue by mrozekma** [google/perfetto#501]
I'm seeing a UI oddity where tracks associated with a PID and/or TID are displayed twice.

For example, following the first protobuf example on https://perfetto.dev/docs/reference/synthetic-track-event, I generated the following binary:

```
00000000  0a 1f e2 03 1c 08 a0 ff  db aa 03 1a 14 08 d2 09  |................|
00000010  32 0f 4d 79 20 70 72 6f  63 65 73 73 20 6e 61 6d  |2.My process nam|
00000020  65 0a 28 e2 03 25 08 86  ca f0 ec b6 01 22 16 08  |e.(..%......."..|
00000030  d2 09 10 ae 2c 2a 0e 4d  79 20 74 68 72 65 61 64  |....,*.My thread|
00000040  20 6e 61 6d 65 28 a0 ff  db aa 03 0a 27 40 c8 01  | name(......'@..|
00000050  50 c1 a2 ee 01 5a 1d 48  01 58 86 ca f0 ec b6 01  |P....Z.H.X......|
00000060  ba 01 11 4d 79 20 73 70  65 63 69 61 6c 20 70 61  |...My special pa|
00000070  72 65 6e 74 0a 26 40 fa  01 50 c1 a2 ee 01 5a 1c  |rent.&@..P....Z.|
00000080  48 01 58 86 ca f0 ec b6  01 ba 01 10 4d 79 20 73  |H.X.........My s|
00000090  70 65 63 69 61 6c 20 63  68 69 6c 64 0a 13 40 9d  |pecial child..@.|
000000a0  02 50 c1 a2 ee 01 5a 09  48 03 58 86 ca f0 ec b6  |.P....Z.H.X.....|
000000b0  01 0a 13 40 a2 02 50 c1  a2 ee 01 5a 09 48 02 58  |...@..P....Z.H.X|
000000c0  86 ca f0 ec b6 01 0a 13  40 ac 02 50 c1 a2 ee 01  |........@..P....|
000000d0  5a 09 48 02 58 86 ca f0  ec b6 01                 |Z.H.X......|
000000db
```

When I load this in the UI, I get:

![](https://github.com/google/perfetto/assets/444512/85c17a84-9a45-4e24-8426-7d9ff126edf7)

Versus this from the docs:

![](https://perfetto.dev/docs/images/synthetic-track-event-thread.png)

From experimenting with the fields, it seems like getting rid of the `process` and `thread` blocks from the first two packets makes the duplication go away.

**Comment by chromy** [comment]
Could you go to the flags page and ensure you have 'TracksV2' set to disabled then retry.

![image](https://github.com/google/perfetto/assets/351085/d0758fe8-240e-4f35-aaeb-4b453e99784b)

Thanks!

**Comment by chromy** [comment]
I really looks like TracksV2 flag is on here. I'm changing this in https://android-review.git.corp.google.com/c/platform/external/perfetto/+/2622872 to make this issue less likely to occur.
