### ISSUE TITLE
weird javascript error when I use chrome in my ubuntu to open perfetto UI trace viewer

### ISSUE THREAD

**Issue by seekdestiny** [google/perfetto#504]
Perfetto UI - An unrecoverable problem occurred

If you are seeing this message, something went wrong while loading the UI.
Please file a bug (details below) and try these remediation steps:

* Force-reload the page with Ctrl+Shift+R (Mac: Meta+Shift+R) or
  Shift + click on the refresh button.

* Clear all the site storage and caches and reload the page.

* Clear the site data and caches from devtools, following these instructions.

In any case, **FILE A BUG** attaching logs and screenshots from devtools.
  Googlers:      go/perfetto-ui-bug
  Non-googlers:  github.com/google/perfetto/issues/new

SyntaxError: expected expression, got '?'

Technical Information:
LocalStorage: {}

**Comment by primiano** [comment]
Hey could you grab a screenshot of chrome devtools and see the full error?
We use Chrome on Linux all the time in Google and never saw this.

Feels like you might have some extension that might mess up with the code in the website.
Can I also ask you to try from an incognito window?

Can you repro this issue 100% times?

Thanks

**Comment by primiano** [comment]
Can you also report the chrome version from chrome://version

**Comment by seekdestiny** [comment]
![Screen Shot 2023-05-31 at 11 41 48 AM](https://github.com/google/perfetto/assets/14968655/3a22cf72-74ba-4ce9-8427-a47e43a8f3bb)
this is the version

**Comment by seekdestiny** [comment]
![Screen Shot 2023-05-31 at 11 43 40 AM](https://github.com/google/perfetto/assets/14968655/b3c0b443-3391-429c-b23d-feab78e43919)
this is the error message
