### ISSUE TITLE
"An unrecoverable problem occurred" due to "[object PromiseRejectionEvent]"

### ISSUE THREAD

**Issue by RossComputerGuy** [google/perfetto#506]
I'm trying to figure out performance issues with an application in Flutter. It seems the Perfetto tracer is broken. I've followed all the steps listed in the error message but it does not resolve the issue.

![image](https://github.com/google/perfetto/assets/19699320/dd414c48-92f0-4b86-bab0-bde6d6d51cf0)

**Comment by chromy** [comment]
@kenzieschmoll

**Comment by kenzieschmoll** [comment]
Hi @RossComputerGuy - do you have consistent repro steps for this?

**Comment by RossComputerGuy** [comment]
Yeah, just run any flutter app. Go to performance, then timeline, and then it crashes.

**Comment by kenzieschmoll** [comment]
Can you paste the output of `flutter doctor -v` here?

**Comment by kenzieschmoll** [comment]
One other thing you could do that can help use reproduce - can you export the Performance data and attach it here? (download button in the upper right of the page)

**Comment by RossComputerGuy** [comment]
```
[!] Flutter (Channel master, 3.11.0-12.0.pre.25, on Freedesktop.org SDK 22.08 (Flatpak runtime) 5.15.96, locale ja_JP.UTF-8)
    • Flutter version 3.11.0-12.0.pre.25 on channel master at /home/ross/flutter
    ! The flutter binary is not on your path. Consider adding /home/ross/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /home/ross/flutter/bin to your path.
    • Upstream repository git@github.com:flutter/flutter
    • Framework revision 23fe4fca59 (10 days ago), 2023-05-23 23:26:05 +0000
    • Engine revision fc6df9512a
    • Dart version 3.1.0 (build 3.1.0-136.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/ross/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /app/extra/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    • cmake version 3.26.3
    • ninja version 1.11.1
    • pkg-config version 1.9.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • 22081283G (mobile) • SCQGPFXCMFOR8TDM • android-arm64 • Android 13 (API 33)
    • Linux (desktop)    • linux            • linux-x64     • Freedesktop.org SDK 22.08 (Flatpak runtime) 5.15.96

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.

```

**Comment by kenzieschmoll** [comment]
I am on the latest flutter and can load timeline events fine:
![Screenshot 2023-06-02 at 2 58 42 PM](https://github.com/google/perfetto/assets/43759233/62df9b88-0d0a-428e-92a4-325a296e7e8c)

```
Flutter 3.11.0-17.0.pre • channel [user-branch] • unknown source
Framework • revision f4662beeb6 (3 days ago) • 2023-05-30 23:09:32 -0400
Engine • revision 7a4a267d8a
Tools • Dart 3.1.0 (build 3.1.0-155.0.dev) • DevTools 2.23.1
```

If you can still reproduce on the latest master, it may be specific to timeline events that your app / platform are sending. If you can include an export of the Performance page data, I can try to repro.

**Comment by RossComputerGuy** [comment]
I still get it on master, I've had this issue with different apps. How do I export the performance page data?

**Comment by kenzieschmoll** [comment]
This button:
![Screenshot 2023-06-02 at 3 16 57 PM](https://github.com/google/perfetto/assets/43759233/8a4d1bbb-f6c8-4372-9a47-950f17784933)

Do you always run with an Android test device? I'd be curious if you still get this issue when you are running your app on iOS or any other platforms (desktop, web, etc.)?

**Comment by RossComputerGuy** [comment]
Yeah, I've only got Linux, web, and Android which I can try but I've only needed the timeline on Android. I can try a bit later.

**Comment by LalitMaganti** [comment]
I don't think there's any further action we can take from our side so closing this out.
