### ISSUE TITLE
[ui] track event log_message not rendering in UI

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#507]
The log message field in track_event packets seems to be accessible via SQL, but doesn't seem to be rendered in the UI.

## How to reproduce

I opened a protobuf trace used in one of the tests and noticed that the UI is not rendering logs at the bottom of the screen.

1. Copy-paste the text proto from [this text proto](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/test/trace_processor/diff_tests/chrome/tests.py;l=374-416) into a file, say mytrace.pbtxt. 
2. encode the text proto into a protobuf trace `cat mytrace.pbtxt | ./out/mac_debug/protoc --encode=perfetto.protos.Trace ./protos/perfetto/trace/perfetto_trace.proto > mytrace.pftrace`
3. open the trace in UI: ` ./tools/open_trace_in_ui -i mytrace.pftrace `
4. notice that log rows at the bottom shows 0 (expected 1)

<img width="1714" alt="image" src="https://github.com/google/perfetto/assets/77857237/dbe39dc2-4989-48a8-a44d-c08063975ce5">

**Comment by ddiproietto** [comment]
Thanks for the report.

I sent a fix at https://r.android.com/2613330

**Comment by cphlipot1** [comment]
Thanks for the fix! 

As an aside, do you think it would make sense to allow track_event to optionally supply a log level inside LogMessage?

**Comment by ddiproietto** [comment]
> As an aside, do you think it would make sense to allow track_event to optionally supply a log level inside LogMessage?

Good point, thanks! Yes, I sent https://r.android.com/2615289 for that

**Comment by ddiproietto** [comment]
The problem has been fix on autopush version of the UI. It will be available on [stable soon](https://perfetto.dev/docs/visualization/perfetto-ui-release-process).
