### ISSUE TITLE
traceconv lose process name 

### ISSUE THREAD

**Issue by lbknxy** [google/perfetto#515]
Hi,
I convert perfetto trace file to systarce by traceconv， but the result file lose all process names, check my pictures: 
![result](https://github.com/google/perfetto/assets/12200366/756bca20-9dae-427c-a3a5-06d76f9e86ac)

**Comment by chromy** [comment]
Please attach a trace to help with debugging, thanks!

**Comment by primiano** [comment]
I think this is WAI no? systrace has only thread names, not processes.
the perfetto -> systrace is a lossy conversion.

**Comment by lbknxy** [comment]
> Please attach a trace to help with debugging, thanks!

[traces.zip](https://github.com/google/perfetto/files/11766139/traces.zip)

I capture some new trace files and  upload as traces.zip:
`perfetto.trace  `   capture by perfetto
`perfetto_2_systrace.trace`  convert with traceconv [traceconv systrace perfetto.trace perfetto_2_systrace.trace]
`systrace.html` capture by systrace.py

**Comment by lbknxy** [comment]
> I think this is WAI no? systrace has only thread names, not processes. the perfetto -> systrace is a lossy conversion.
> 
> This is how ftrace looks like
> 
> ```
> #                              _-----=> irqs-off
> #                             / _----=> need-resched
> #                            | / _---=> hardirq/softirq
> #                            || / _--=> preempt-depth
> #                            ||| /     delay
> #           TASK-PID   CPU#  ||||    TIMESTAMP  FUNCTION
> #              | |       |   ||||       |         |
>           <idle>-0     [005] d...  2440.603828: sched_switch: prev_comm=swapper/5 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=snapshot-test-2 next_pid=2242 next_prio=120
>            sleep-2242  [005] d...  2440.603846: sched_switch: prev_comm=snapshot-test-2 prev_pid=2242 prev_prio=120 prev_state=R ==> next_comm=kworker/5:1 next_pid=60 next_prio=120
> [...]
>           <idle>-0     [002] d...  2440.707230: sched_switch: prev_comm=swapper/2 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=snapshot-test-2 next_pid=2229 next_prio=120
> 
>  # cat trace
> ```
> 
> In this case snapshot-test-2 is the name of the thread, not name of the process. There is no process name.

May you are right, almost all process in `systrace.html` are not have a name, but there are also processes, such as SurfaceFinger does has a name.

**Comment by lbknxy** [comment]
hello ?
