### ISSUE TITLE
Which proto holds the debug value field?

### ISSUE THREAD

**Issue by RishiTejaMadduri** [google/perfetto#521]
I am working on a project and I recorded a track event. I see this particular field in the slice details titled `debug value`
However, I couldnt find this particular field in any of the proto files. I need this to write synthetic track events.
I checked the [trace-packet-proto](https://perfetto.dev/docs/reference/trace-packet-proto) but could not come up with anything. 

When the perfetto trace is converted to json format using the web ui, this particular debug value field is shown as just value within the `args` section.

![Screenshot from 2023-06-29 12-17-57](https://github.com/google/perfetto/assets/53811188/d53e3983-87c2-4657-bb53-347a8670a375)

Can someone help me tracking down which `proto` does this particular field belong to?

**Comment by LalitMaganti** [comment]
Pretty sure you're looking for the DebugAnnotation proto [as described here](https://perfetto.dev/docs/reference/trace-packet-proto#DebugAnnotation)
