### ISSUE TITLE
artifact containing the protos or java generated classes

### ISSUE THREAD

**Issue by facewindu** [google/perfetto#524]
Is there a way to consume an artifact containing the JAVA generated classes out of the [protos](https://github.com/google/perfetto/tree/master/protos), or do I need to build them myself ?

or, is there a way to get the protos bundled from a published artifact (say in maven central)?
Currently, I'm getting them 'by hand' from this repo and integrate them in my project, but I don't like this solution

**Comment by LalitMaganti** [comment]
There's no artifact available atm with the protos bundled.
