### ISSUE TITLE
Xiaomi phone, can't use online record Trace

### ISSUE THREAD

**Issue by huawaii** [google/perfetto#528]
I have tried using many Xiaomi phones, all Android 12+ devices, but none of them work with online record Trace.
The chrome browser used, also has Enable WebUSB turned on.

Still getting error:
A WebUSB error occurred.
Is adb already running on the host? Run this command and try again.

**Comment by huawaii** [comment]
> Can you please try and record using the command line instead (https://perfetto.dev/docs/quickstart/android-tracing#recording-a-trace-through-the-cmdline)? It's not clear if this problem is a WebUSB issue or something bad happening on the Perfetto side.

**Comment by huawaii** [comment]
> Can you please try and record using the command line instead (https://perfetto.dev/docs/quickstart/android-tracing#recording-a-trace-through-the-cmdline)? It's not clear if this problem is a WebUSB issue or something bad happening on the Perfetto side.

Thank you very much for your reply. Using the command line is working. I just want to experience grabbing the trace directly from the line. i don't know what the cause of the problem is yet. If anyone has encountered a similar situation, please let me know, thanks!

**Comment by LalitMaganti** [comment]
AFAIK this is really a browser issue on the client side. I think everything on the Perfetto side is WAI: the error clearly indicates it's a WebUSB issue.

**Comment by louie-wh** [comment]
![image](https://github.com/user-attachments/assets/ec80bb39-3f24-49f8-8045-16db5751a031)
![image](https://github.com/user-attachments/assets/d01e87a2-bf72-48bd-8378-72d118f7b98c)

also happen to the problem
