### ISSUE TITLE
Can't find GC info for a running Android application

### ISSUE THREAD

**Issue by bolunli11** [google/perfetto#530]
Hello,

I generated a trace of a running Android application, and GC was triggered many times (tested with Android Studio Profiler). In the Perfetto UI, however, I can't find any GC info (searched for "GC", "Garbage", "GC Thread", etc.). I turned on all the CPU and Memory configurations in my config file.

I also opened the provided Android example trace in Perfetto and can't find any GC info. I searched how to check GC in Perfetto's official document and found no helpful tips. May I know how to check the GC in the provided Android example (if there's no GC in this example, then what's the correct way to monitor GC)? Big thanks in advance!

**Comment by LalitMaganti** [comment]
GC is available can be found by enabling the "dalvik" category of "Atrace userspace annotations" in the "Android apps and svcs" tab.

These show up as userspace slices in the associated app process:
![image](https://github.com/google/perfetto/assets/679100/ede77dc1-c1f5-48c8-b66c-5100910206f8)
