### ISSUE TITLE
Trace processor binary should be downloaded over HTTPS

### ISSUE THREAD

**Issue by ErnestChan** [google/perfetto#532]
**What's the issue**

Perfetto's Python package downloads the trace_processor binary over HTTP if the user doesn't explicitly provide a path to the binary. https://github.com/google/perfetto/blob/master/python/perfetto/trace_processor/platform.py#L31
This is insecure and opens users up to various threat vectors. The same URL supports HTTPS which the package should use instead.

**Proposal**
Download the trace_processor binary over HTTPS to get all the security properties of TLS.

**Comment by LalitMaganti** [comment]
https://r.android.com/2657159 fixes this.

**Comment by ErnestChan** [comment]
Thank you
