### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by scottwedge** [google/perfetto#54]

**Comment by tilal6991** [comment]
Thanks for the issue and the associated commit!

Unfortunately, this Github is a read-only mirror - all contributions need to go through our AOSP repo. You can find instructions on this at https://perfetto.dev/docs/contributing/getting-started.

Closing this bug - can follow up on the CL sent to AOSP :)

**Comment by primiano** [comment]
I just checked and given you have signed already the CLA I did manually port this patch on AOSP:
https://android-review.googlesource.com/c/platform/external/perfetto/+/1372116
Landing it there.

Thanks for the contrib.
