### ISSUE TITLE
Failed to Build SDK on Windows

### ISSUE THREAD

**Issue by theidexisted** [google/perfetto#547]
I encountered this error while compiling the SDK example on Windows, how to fix it? Thanks!

> C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\sdk\perfetto.cc(73560,10): fatal  error C1083: Cannot open include
>  file: 'sys/socket.h': No such file or directory [C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\_bu
> ild\perfetto.vcxproj]

Related info:
* perfetto release 36.1
* VS 2022
* Windows Server 2019

**Comment by primiano** [comment]
@theidexisted can I ask you to confirm that if you:
- take perfetto.cc
- wrap the code just below `#define SRC_BASE_VM_SOCKETS_H_` with ifdef guards as I'm doing in  r.android.com/2691827

Then the error goes away?

Thanks

**Comment by theidexisted** [comment]
> @theidexisted can I ask you to confirm that if you:
> 
> * take perfetto.cc
> * wrap the code just below `#define SRC_BASE_VM_SOCKETS_H_` with ifdef guards as I'm doing in  https://r.android.com/2691827
> 
> Then the error goes away?
> 
> Thanks

Thanks! I have picked the change except the line `cmake --build _build --config Release`, then the file perfetto.cc compiles, but the example.cc file failed to compile:

```
C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\example.cc(82,3): error C2760: syntax error: ')' was
unexpected here; expected 'expression' [C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\_build\exampl
e.vcxproj]
C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\example.cc(82,3): error C3553: decltype expects an ex
pression not a type [C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\_build\example.vcxproj]
C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\example.cc(82,3): error C2059: syntax error: ')' [C:\
Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\_build\example.vcxproj]
C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\example.cc(82,3): error C2059: syntax error: ',' [C:\
Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\_build\example.vcxproj]
C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\example.cc(82): error C2143: syntax error: missing ';
' before '{' [C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\_build\example.vcxproj]
C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\example.cc(82,3): error C2760: syntax error: ',' was
unexpected here; expected ')' [C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\_build\example.vcxproj
]
C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\example.cc(82,3): error C2760: syntax error: ',' was
unexpected here; expected ';' [C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\_build\example.vcxproj
]
C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\example.cc(82,3): error C2760: syntax error: ',' was
unexpected here; expected '}' [C:\Users\x\Downloads\perfetto-36.1\perfetto-36.1\examples\sdk\_build\example.vcxproj
```

Seems the macro `TRACE_EVENT` doesn't expand and compiles.

For the example files, only two of them compiles, could you please investigate how to fix it?

- example_custom_data_source.cc  **compiles**
- example_startup_trace.cc **compiles**
- example_system_wide.cc
- example.cc
- example_console.cc

**Comment by ddiproietto** [comment]
This new error was reported yesterday as well (https://github.com/google/perfetto/issues/540).

I'll close this when we have a new SDK release with the MSVC build fixed.

**Comment by ddiproietto** [comment]
We release v37.0, which should fix this specific problem
