### ISSUE TITLE
When selecting span, its args appear in random order

### ISSUE THREAD

**Issue by victor-homyakov** [google/perfetto#553]
<img width="466" alt="image" src="https://github.com/google/perfetto/assets/121449/299cdff1-17bf-4c55-8ed5-fb517ab80eac">

In `trace.json` file these args are saved in proper order, additionally they have explicit order in their names, e.g.

```
"args":{"name":"@some/Name","t_01_started":36,"t_02_shaped":38,"t_03_registered":38,"t_04_writeBegin":40,"t_05_writeWidgetCreated":40,"t_06_writeNextEventLoopTask":40,"t_07_stuffed":40,"t_08_writeStateReady":40,"t_09_renderStarted":139,"t_10_rendered":142,"t_11_writeChunksReady":197,"t_12_writePrologueDone":197,"t_13_writeEpilogueDone":2351,"t_14_writePatchesDone":2351,"t_15_shipped":2351}
```

**Comment by LalitMaganti** [comment]
Please provide a trace so we can verify the fix for this issue.

**Comment by victor-homyakov** [comment]
The trace: [ssr-crit-path.json.gz](https://github.com/google/perfetto/files/12304355/ssr-crit-path.json.gz)

**Comment by chromy** [comment]
@LalitMaganti sent a fix for this: https://r.android.com/2701235 😃 

<img width="1652" alt="Screenshot 2023-08-10 at 13 26 12" src="https://github.com/google/perfetto/assets/351085/6aaf45b0-d442-4b17-978a-864bcfd4bfc5">

Should be available on [autopush](https://perfetto.dev/docs/visualization/perfetto-ui-release-process#changing-release-channel) shortly (~hours).
