### ISSUE TITLE
Creating config file, full trace not captured

### ISSUE THREAD

**Issue by aphatke** [google/perfetto#556]
Hello, I created the trace file below using some of the examples from the repo. The trace duration should be 3 mins however, only 1:30 mins of the trace is being captured. 

buffers {
  size_kb: 655360
  fill_policy: RING_BUFFER
}

data_sources {
  config {
    name: "linux.ftrace"
    target_buffer: 0
    ftrace_config {
      buffer_size_kb: 1600
      drain_period_ms: 250
      ftrace_events: "cpu_frequency"
      ftrace_events: "cpu_idle"
      ftrace_events: "sched_process_exec"
      ftrace_events: "sched_process_exit"
      ftrace_events: "sched_process_fork"
      ftrace_events: "sched_process_free"
      ftrace_events: "sched_process_hang"
      ftrace_events: "sched_process_wait"
      ftrace_events: "sched_switch"
      ftrace_events: "sched_wakeup_new"
      ftrace_events: "sched_wakeup"
      ftrace_events: "sched_waking"
      ftrace_events: "task_newtask"
      ftrace_events: "task_rename"
      ftrace_events: "tracing_mark_write"
      ftrace_events: "power/cpu_frequency"
      ftrace_events: "power/cpu_idle"
      ftrace_events: "power/suspend_resume"
    }
  }
}

data_sources {
  config {
    name: "linux.process_stats"
    target_buffer: 0
  }
}

data_sources {
  config {
    name: "linux.inode_file_map"
    target_buffer: 0
    inode_file_config {
      scan_delay_ms: 1000
      scan_interval_ms: 1000
      scan_batch_size: 500
      mount_point_mapping: {
        mountpoint: "/data"
        scan_roots: "/data/app"
        scan_roots: "/data/misc/bootstat"
        scan_roots: "/data/misc/update_engine_log"
        scan_roots: "/data/misc/update_engine"
        scan_roots: "/data/misc/profiles/ref"
        scan_roots: "/data/misc/profiles/cur"
        scan_roots: "/data/dalvik-cache"
        scan_roots: "/data/data/android"
        scan_roots: "/data/backup"
      }
    }
  }
}

data_sources {
  config {
    name: "perfetto.metatrace"
    target_buffer: 0
  }
}

data_sources: {
    config {
        name: "linux.sys_stats"
        target_buffer: 0
        sys_stats_config {
            cpufreq_period_ms: 500
        }
    }
}

# Reporting the list of available frequency for each CPU.
data_sources {
    config {
        name: "linux.system_info"
        target_buffer: 0
    }
}

producers {
  producer_name: "perfetto.traced_probes"
  shm_size_kb: 4096
  page_size_kb: 4
}

duration_ms: 180000

**Comment by LalitMaganti** [comment]
This is working as intended: you are running out of ring buffer space. Please see the information on collecting long traces [here](https://perfetto.dev/docs/concepts/config#long-traces).

**Comment by aphatke** [comment]
The trace file I collected was only 6,757 KB while the buffer size is 655360 KB?  Shouldn't the trace file be larger if the ring buffer space was running out?

**Comment by LalitMaganti** [comment]
Without having access to your trace I would not be able to say. There simply not enough information in just the config file to pinpoint the problem: my previous comment was simply stating the overwhelmingly likely cause.

**Comment by aphatke** [comment]
I added in the following edits to the file however I'm not sure if the values are correct. It there more intuitive way to do this ? I just approximated the file_write_period_ms value etc badsed on the  long_trace.cfg file in the repo : 
write_into_file: true
duration_ms: 180000
file_write_period_ms: 250
flush_period_ms: 2000

**Comment by LalitMaganti** [comment]
Reasonable values are:
```
file_write_period: 5000
flush_period_ms: 10000
```

Tuning these values is discussed in our [docs](https://perfetto.dev/docs/concepts/buffers#buffer-sizing)

**Comment by LalitMaganti** [comment]
The values I provided should be good enough even with more events.
