### ISSUE TITLE
process_pid = 0 causes threads to be renamed to "swapper" is this documented?

### ISSUE THREAD

**Issue by lednakashim** [google/perfetto#560]
also are there any other reserved IDs that have special behavior?

**Comment by LalitMaganti** [comment]
It is not documented but is indeed the behaviour of trace processor if we detect a proto trace (happens in trace processor [here](https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/importers/common/process_tracker.cc;l=509?q=src%2Ftrace_processor%2Fimporters%2Fcommon%2Fprocess_tracker.cc)).

No other pids/tids are special.
