### ISSUE TITLE
[help] How to use viz panel to visualize data?

### ISSUE THREAD

**Issue by rollysys** [google/perfetto#561]
First of all, it's really a great feature for perfetto, because I just us trace_processor then python then vega-lite for offline visualization for now.
I tried vega-lite sample in viz panel, it works.
But, how to access perfetto trace data in viz?
Thanks

**Comment by chromy** [comment]
You can put a `trace_processor` SQL query where the URL would go. For example:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {"url": "select cpu, dur from sched where utid != 0"},
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "cpu"
    },
    "y": {"aggregate": "sum", "field": "dur"}
  }
}
```


<img width="1228" alt="Screenshot 2023-08-19 at 15 29 22" src="https://github.com/google/perfetto/assets/351085/0ca94f9e-ff91-4e2d-9507-cadc15184f62">

**Comment by rollysys** [comment]
Thanks so much!
Hope to see this in the official doc soon
