### ISSUE TITLE
Seeing Gaps in the Main Thread Timeline

### ISSUE THREAD

**Issue by dhruvkaushal11** [google/perfetto#562]
Hi Team, I am trying to improve app launch performance, I am primarily looking into time to initial display metrics.
I am seeing some gaps(high-lighted in screenshot below) where main thread is doing nothing.  But still TTID metrics is calculating in parallel.  Any thing that explains this?

<img width="1031" alt="image" src="https://github.com/google/perfetto/assets/16204255/ee7bfa0f-4fea-4c0d-838e-5c611e723b93">

**Comment by LalitMaganti** [comment]
Those gaps are cases where the thread was descheduled i.e. your app was doing something which caused it to start sleeping.

Unfortunately, as a team we are only staffed to help with bugs/problems with the Perfetto tooling itself *not* with helping people debug traces. I'd recommend asking on a public forum (StackOverlow/Reddit) if you need more guidance on why your main thread might be getting descheduled.
