### ISSUE TITLE
How to show debug track as counter by SQL query result?

### ISSUE THREAD

**Issue by c-jchen** [google/perfetto#565]
As Title.

I am trying to show debug track as counter by SQL query result.

However, it shows like slice view..

Can I show produced query reslut as counter view?

For example, add two original counters at the same time and shows by new debug track.

**Comment by LalitMaganti** [comment]
No this is not currently supported. One workaround is to convert counters to slices and visualize them that way.

**Comment by c-jchen** [comment]
Thanks,

Do you have plan to provide line chart like view?

or have some post-editor function for calculating between counters? like counter a / counter b *100 = % of usage.

**Comment by LalitMaganti** [comment]
> Do you have plan to provide line chart like view?

At some point yes but it's not too high on our priority list.

**Comment by c-jchen** [comment]
Thanks for your kind work
