### ISSUE TITLE
Is there an interface to align time across processes?

### ISSUE THREAD

**Issue by lednakashim** [google/perfetto#568]
Traces can be collected across nodes with the potential differences between nodes exceeding miliseconds

Rather than lets say subtracting time offsets from traces to align them, it would be desirable to wholesale shift time relative to some kind of alignment event(s) as a kind during data visualization. In some cases the synchronized times are relevant in other cases the times with divergent clocks may be relevant.

Does this kind of interface exist?

**Comment by LalitMaganti** [comment]
A mechanism to do this is provided in the Perfetto trace format: please see https://perfetto.dev/docs/concepts/clock-sync
