### ISSUE TITLE
client_api_factory_standalone error in rogue process spinning looping

### ISSUE THREAD

**Issue by tkuowork** [google/perfetto#569]
Hi

I have been using the perfetto heap profiler (https://perfetto.dev/docs/data-sources/native-heap-profiler#-non-android-linux-support) to analyze my process.

My process is normally managed using runsv (http://smarden.org/runit/runsv.8.html).

When starting my process without runsv management, I have no issues.

However, when starting my process with runsv I see a rogue process being spawned and it consumes a large amount of CPU spin looping.

I see a spam of the log lines:
```
2023-05-23_10:07:06.19812-0700 [598.344] ctory_standalone.cc:166 Receive (errno: 88, Socket operation on non-socket)
```

which points to: 
`/perfetto/src/profiling/memory/client_api_factory_standalone.cc`

Using the following diff, I no longer get this error:
```
diff --git a/src/profiling/memory/client_api_factory_standalone.cc b/src/profiling/memory/client_api_factory_standalone.cc
index 55a77bb22..3549012d3 100644
--- a/src/profiling/memory/client_api_factory_standalone.cc
+++ b/src/profiling/memory/client_api_factory_standalone.cc
@@ -163,6 +163,7 @@ void StartHeapprofdIfStatic() {
           task_runner.RemoveFileDescriptorWatch(srv_sock.fd());
         }
         if (r == -1 && !base::IsAgain(errno)) {
+          if (errno == ENOTSOCK) exit(0);
           PERFETTO_PLOG("Receive");
         }
         if (fd) {
```

would it be possible to merge something like this change to mainline?

**Comment by primiano** [comment]
I think what's happening here is that your `runsv` somehow reacts to the signal we use for heap profiling in some weird way that causes the socket to be destroyed (or to be created in an unusual way in the first place).

Realistically that error handling code should be changed to call `RemoveFileDescriptorWatch` in case of an error. What's happening is that somehow we end up in a state where the epoll() loop keeps waking up (maybe because of some error queued up), but the recv() fails.
Maybe we should just shutdown and remove the fd watch in case of errors. DOesn't make too much sense to me to maintain the FD watch in case of an error.

@ddiproietto @rsavitski  thoughts?

**Comment by ddiproietto** [comment]
> I think what's happening here is that your runsv somehow reacts to the signal we use for heap profiling in some weird way that causes the socket to be destroyed (or to be created in an unusual way in the first place).

We don't use signals for heap profiling on linux.

I'd like to understand how we get to that error: `srv_sock` should be a unix socket created a few lines above.

I tried running a simple program under runsv, but I cannot reproduce the problem.

Can you share a way to reproduce the problem? (Or do you understand the sequence of events that cause srv_sock.Receive to return ENOTSOCK?)

Is your process using fork()? If so, this can confuse the heap profiler. I'm not sure it's related to this problem, though

**Comment by tkuowork** [comment]
hm im having a hard time reproducing on an isolated system.

let me get back to you once i have a repo!

i did dig a little deeper and you're right, it does seem like its not specific to `runsv`.
using the instructions:
https://kchard.github.io/runit-quickstart/

in the `run` script from my daemon A, I start another process

i.e
```
#!/bin/sh

export LD_PRELOAD=/tmp/libheapprofd_glibc_preload.so

sv start daemon_B

exec chpst -u daemonA
```

it seems that there is something very specific about daemon_B because if i change it to daemon_C i don't see this error.
also if I move `export LD_PRELOAD=/tmp/libheapprofd_glibc_preload.so` below the `sv start daemon_B`, I also don't see this error.

it seems like the _something_ in the daemon_B flow is causing this spam of

**Comment by primiano** [comment]
Try wrapping the invocation in a `strace` command and follow carefully what happens to the FD that has the socket (on which we then spin). The culprit will probably be there.
