### ISSUE TITLE
Slice with same start time is not shown

### ISSUE THREAD

**Issue by zhqin** [google/perfetto#57]
Hi, I have a protobuf file [test.pb.zip](https://github.com/google/perfetto/files/4987696/test.pb.zip), in which there are six slice type TrackEvent, but when opening in [Trace Viewer](https://ui.perfetto.dev/#!/), some slices are not shown.

![not_shown](https://user-images.githubusercontent.com/4161910/88655932-16bf5880-d102-11ea-9de0-93bb29ae8fda.png)

We can still see five depth stacks. And after some zoom in, the slice with name 'third' is visible.

![shown](https://user-images.githubusercontent.com/4161910/88656113-61d96b80-d102-11ea-8e77-ec0b9f0f7626.png)

But the slice with name 'fifth' is always invisible. The data in the slice table:

![data](https://user-images.githubusercontent.com/4161910/88656236-8fbeb000-d102-11ea-9d39-601a7b830837.png)

It seems slice with same start time will be 'group by' after this [change](https://android-review.googlesource.com/c/platform/external/perfetto/+/1348785),  so it's not shown.  Is this a bug, or just same start time is not supported?

**Comment by primiano** [comment]
@tilal6991 this seems to be an issue with the quantization of async tracks

**Comment by tilal6991** [comment]
I think I accidentally am not taking layout_depth into account when doing the quantization. Will send a fix.

**Comment by tilal6991** [comment]
I've sent https://android-review.googlesource.com/c/platform/external/perfetto/+/1374577 which should fix this issue.

**Comment by tilal6991** [comment]
The fix has landed but will take a bit of time to roll out to ui.perfetto.dev (a few days at most).

**Comment by tilal6991** [comment]
This should have now rolled into the main UI.
