### ISSUE TITLE
android_startup is empty

### ISSUE THREAD

**Issue by notigit** [google/perfetto#570]
![image](https://github.com/google/perfetto/assets/18521772/2570f8b1-f1b5-4cbf-b9b1-b1c6f3fb2c56)

python record_android_trace -o trace.perfetto-trace -t 15s -b 200mb gfx input view webview wm am sm audio video camera hal res dalvik rs bionic power pm ss database network adb vibrator aidl nnapi rro pdx sched irq i2c freq idle disk sync workq memreclaim regulators binder_driver binder_lock pagecache memory gfx ion

**Comment by aMayzner** [comment]
Can you please share the trace so that we can repro the issue?

**Comment by notigit** [comment]
how to share the trace?

**Comment by aMayzner** [comment]
You can for example upload it to google drive, or if it's small enough you
can attach it to a comment on github.

**Comment by LalitMaganti** [comment]
We really need a trace to debug any further. Feel free to reopen with a trace if you have one.
