### ISSUE TITLE
python api can not get data from table raw or ftrace_event but web can

### ISSUE THREAD

**Issue by passionwang** [google/perfetto#573]
**I can get data from web** 
  like this:
  
  `SELECT EXTRACT_ARG(arg_set_id, 'prev_comm') as new_name FROM ftrace_event WHERE name='sched_switch'`
  new_name
  --
  swapper/3
  swapper/4
  traced_probes0
  traced_probes1
  ...
---------------------------------
**I can not get data from python api**
like this:

  fro```
  from perfetto.trace_processor import TraceProcessor
  from perfetto.trace_processor import TraceProcessorConfig
  config = TraceProcessorConfig(bin_path='/Users/xxx/code/perfetto/record-script/exe/trace_processor_shell')
  tp = TraceProcessor(trace='/Users/xxx/code/perfetto/record-script/traces/trace-2023-08-26-17-52-51.perfetto-trace',
                      config=config)
  
  cmdstr = ''' SELECT EXTRACT_ARG(arg_set_id, 'prev_comm') as new_name FROM ftrace_event WHERE name='sched_switch' '''
  print(cmdstr)
  qr_it = tp.query(cmdstr)
  for row in qr_it:
    print(row.new_name)

```
  /Users/xxx/code/venv3.9/bin/python /Users/xxx/code/perfetto/record-script/analysis-perfetto.py
   SELECT EXTRACT_ARG(arg_set_id, 'prev_comm') as new_name FROM ftrace_event WHERE name='sched_switch' 
  
  Process finished with exit code 0

**Comment by LalitMaganti** [comment]
This is WAI. Please see https://github.com/google/perfetto/issues/536.

**Comment by passionwang** [comment]
Thank you
