### ISSUE TITLE
How to use flow event at debug track by SQL?

### ISSUE THREAD

**Issue by c-jchen** [google/perfetto#574]
Can I create debug slice which have slice_in and slice_out args and it can have link to jump to slice_in.?

**Comment by LalitMaganti** [comment]
No this is not supported: debug slices cannot have flows coming in or out
at the moment.

**Comment by c-jchen** [comment]
I tried span_join() and others, it is a useful function.
However,  I can not identify or jump the original slice directly when I use debug track to indicate new slice.

Do you have any suggestion for this objective?

I can add some args, but can I add information like arguments's debug info at below web page?

**Comment by LalitMaganti** [comment]
Debug slices are still being developed at the moment so both the features you're looking for (linking to the original slice and debug aguments) are not supported at the moment but is something we would likely add in the future.

**Comment by c-jchen** [comment]
Many thanks for your response

Looking forward to have more functions.
