### ISSUE TITLE
Built UI faile

### ISSUE THREAD

**Issue by lianghx-319** [google/perfetto#58]
![image](https://user-images.githubusercontent.com/27187946/89395360-c9fe0200-d73f-11ea-8369-d9da27c194d4.png)

`tools/ninja -C out/debug ui` fail, error unsafe cross-compilation

**Comment by primiano** [comment]
Which OS is that Linux or Mac? That must be a new version of clang that has a newer warning/error.
Also not sure how you end up with /usr/local/include

**Comment by lianghx-319** [comment]
> Which OS is that Linux or Mac? That must be a new version of clang that has a newer warning/error.
> Also not sure how you end up with /usr/local/include

MacOS latest version

**Comment by primiano** [comment]
https://android-review.googlesource.com/c/platform/external/perfetto/+/1383619 should fix it
Could you try?

**Comment by lianghx-319** [comment]
It works! Thanks, next time when I want to update OS should be carefully.

![image](https://user-images.githubusercontent.com/27187946/89404600-db99d680-d74c-11ea-9d06-1e38d11305e8.png)
