### ISSUE TITLE
[UI] console.log() spam in android_binder metric

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#580]
Minor issue, but I'm seeing a spam in the console window whenever i navigate to the metrics page and select the andoid_binder metric. This does not happen with other metrics

I'm not 100% sure on the cause and why this only happens with this metric, but presumably because this this one has the new plugin visualization included as part of https://android-review.googlesource.com/c/platform/external/perfetto/+/2661177

## Steps To Reproduce:

1. navigate to https://ui.perfetto.dev
3. click "Open Android Example"
4. click on "Metrics"
5. select "android_binder" from the drop down
6. open the console in devtools

this line seems to be responsible for flooding the console: https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/ui/src/frontend/metrics_page.ts;l=127

<img width="1877" alt="image" src="https://github.com/google/perfetto/assets/77857237/f773076f-f6b3-4abb-a353-34d151988646">

**Comment by chromy** [comment]
My bad, https://r.android.com/2743793 for this.
