### ISSUE TITLE
[Question] Save timeline of a thread as an svg

### ISSUE THREAD

**Issue by 0x161e-swei** [google/perfetto#581]
Is there a way to dump/save SVG/pdf plots for each thread timeline?

**Comment by LalitMaganti** [comment]
No there is no such feature nor would we want to add any such feature to the Perfetto UI. Not sure what you're trying to accomplish but whatever it is can probably be done better by querying the trace programatically with trace processor (e.g. with the Python API: https://perfetto.dev/docs/analysis/trace-processor#python-api)
