### ISSUE TITLE
trace_processor endpoints return non-compilant http headers

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#582]
TraceProcessors RPC endpoints (eg. /compute_metric) will return HTTP headers that are not compliant with spec, and in cases where a strict HTTP header parser is used this will result in a failure.

This does not impact The Python parser used, nor trace_processor communication with the UI, but will impact other tools and libraries that attempt communicate with trace_processor over HTTP RPC and more strictly adhere to proper headers such as Node's http implementation.

The issues stems from both "Content-Length" and "Transfer-Encoding" encoding headers both appearing together which is in volation of spec:

https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2

> A sender MUST NOT send a Content-Length header field in any message
that contains a Transfer-Encoding header field.

## how to reproduce

This spec violation can easily be verified:

in one terminal run:
```
./tools/trace_processor --httpd test/data/android_sched_and_ps.pb
```

In a 2nd terminal run:
```
% curl -X POST http://localhost:9001/status -v   
*   Trying 127.0.0.1:9001...
* Connected to localhost (127.0.0.1) port 9001 (#0)
> POST /status HTTP/1.1
> Host: localhost:9001
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Content-Type: application/x-protobuf
< Transfer-Encoding: identity
< Content-Length: 114
< Connection: keep-alive
< 
```

notice that Tracefer-Encoding & Content-Length headers are both present.

**Comment by LalitMaganti** [comment]
I guess the fix would be to simply remove the `Transfer-Encoding` header where we have the  `Content-Length` header available?

@aMayzner can you take care of this bug? Should be a <5 line patch.

**Comment by cphlipot1** [comment]
I took a quick attempt at a fix in https://android-review.googlesource.com/c/platform/external/perfetto/+/2746493

If you'd prefer to handle this differently, let me know. 

Also if you'd prefer to implement your own CL to fix as well that works too.

**Comment by LalitMaganti** [comment]
> I took a quick attempt at a fix in https://android-review.googlesource.com/c/platform/external/perfetto/+/2746493

Looks great thanks so much!

> Also if you'd prefer to implement your own CL to fix as well that works too.

We're always happy to get patches from contributors, makes our life so much easier when we can just approve rather than context switch to something we might not have looked at for a while :)
