### ISSUE TITLE
Instant events do not display correctly if they have the same timestamp as a duration event

### ISSUE THREAD

**Issue by heatd** [google/perfetto#583]
Hi!

I've been using ui.perfetto.dev as a trace processor/viewer for my custom-generated Chrome JSON format traces.
I have an instant event that *usually* fires in the same uS as the duration event. However, that makes it so the UI never displays the instant event; searching for the event name moves me to the start of the duration events, though.
If I delay the instant event's timestamp for 1uS, such that it doesn't match the duration ev, it displays them normally.

Attached the JSON (as a .txt, dang github). This is trivially reproducible using ui.perfetto.dev and the vm.page_fault + vm.copy_on_write events.

[testprog.txt](https://github.com/google/perfetto/files/12561814/testprog.txt)

**Comment by LalitMaganti** [comment]
In our view, this is WAI. Handling these edge cases of identical timestamps induces a high amount of complexity throughout the trace processing and UI stack and is a non issue if you use the native proto format where timestamps can be specified in nanoseconds

Basically this falls under our JSON policy (https://perfetto.dev/docs/faq#why-does-perfetto-not-support-lt-some-obscure-json-format-feature-gt-) where the cost of supporting this case does not justify the benefit.

**Comment by heatd** [comment]
Thanks for the quick response. Would it be possible add a warning (if this occurs) somewhere in the UI then? I'm afraid this isn't obvious and even nanosecond-resolution trace formats can fall prey to this if e.g the clock's resolution is low.

In any case, JSON supports nanosecond resolution, and I already have timestamps in ns anyway, just didn't bother to plug in the support.

Thanks for the help :)

**Comment by LalitMaganti** [comment]
> Would it be possible add a warning (if this occurs) somewhere in the UI then?

From a technical perspective, yes it would certainly be possible. Would be be of a high enough priority for us to look at? Probably not: contributions for this
