### ISSUE TITLE
Whats the preferred way to trace data dependencies across threads?

### ISSUE THREAD

**Issue by lednakashim** [google/perfetto#589]
So I'm looking to trace how a datum is processed across multiple threads

So perfetto has something like a `sequence_id` field that I thought was used for tracing data flow but I don't see any way to see these grouping in https://ui.perfetto.dev/

Is there a way to connect packets by data flow in a way that the flow can be inspected in the web ui?

**Comment by lednakashim** [comment]
here is a small example file where I wrote two "sequences" of events with different sequence id
[perfetto.proto.zip](https://github.com/google/perfetto/files/12623847/perfetto.proto.zip)

**Comment by LalitMaganti** [comment]
I'm guessing you are manually generating these traces instead of using the SDK? In this case, the suggestion in this is to use flows as documented in this page: https://perfetto.dev/docs/reference/synthetic-track-event#flows
