### ISSUE TITLE
"Hide Panel" in Timeline section do not work after switching to another section

### ISSUE THREAD

**Issue by AndrewB330** [google/perfetto#59]
1. Load trace
2. Select any slice ( -> Slice Details Panel appeared)
3. Go to Query(SQL) or Stats section
4. Go back to timeline
5. Now details panel is hidden and and 'Hide Panel' is not working, so I can't open it
6. But: 'Open Fullscreen' button is working, and after clicking on it, it makes 'Hide Panel' button to work the same as 'Open Fullscreen'

Buttons:
<img width="97" alt="Screen Shot 2020-08-11 at 14 05 59" src="https://user-images.githubusercontent.com/11033336/89890307-cb19ae00-dbdb-11ea-96af-1d9fe0b5172d.png">

**Comment by chromy** [comment]
This issues seems to have got fixed at some point as I can no longer reproduce with v9.0.271.
