### ISSUE TITLE
spans linked by flow_ids render poorly with nesting

### ISSUE THREAD

**Issue by lednakashim** [google/perfetto#590]
With nesting flow_id arrows connect from end to start event 

This makes sense but is hard to understand when tracks form a parent child relationship (nesting).

Ideally the tool would connect parents to children via a down arrow, as well as provide drawings to trace tracks across parent spans. Discovery of nesting is one of the computations we rely on perfetto to perform.

<img width="802" alt="Screenshot 2023-09-17 at 4 53 32 PM" src="https://github.com/google/perfetto/assets/1728530/7935af30-f598-4f97-8ddf-5ad8ead61174">

**Comment by lednakashim** [comment]
Simple case with flow IDs set
[sequence_test.proto.zip](https://github.com/google/perfetto/files/12643707/sequence_test.proto.zip)

**Comment by stevegolton** [comment]
Hey @lednakashim,

Thanks for raising the bug, I can see the issue.

I can imagine two ways to address this:
- Detect the parent child relationship and draw a different style of arrow (i.e. a vertical arrow).
- Try to prevent arrows from going backwards as much as possible by sliding the ends forward or backward while keeping them within the bounds of their slices.

While the former would need some investiagtaion, the latter would be quite trivial and I *think* would acheive the desired effect - something like in the screenshot.

<img width="446" alt="image" src="https://github.com/google/perfetto/assets/6147146/e7367d05-f856-41df-b257-7516b703a0c9">

Let me know what you think.

**Comment by lednakashim** [comment]
Preference for down arrow as as the parent span is ran "simultaneously" with the child span

**Comment by stevegolton** [comment]
> The second version (what is drawn) is a bit ambiguous as it is not clear what the arrow start is used to denote.

Agreed. The difficulty is, the arrow has to begin somewhere, and unless it's at one of the ends of the slice I think it could be misinterpreted as significant.

> Ideally the tool would connect parents to children via a down arrow

Could you sketch out what you had in mind re "down arrow"?

A few suggestions:

| Name | Screenshot |
| --- | --- |
| No circle | <img width="357" alt="image" src="https://github.com/google/perfetto/assets/6147146/959e2b0e-c1ca-4ea2-a008-4bcb3ce854ac"> |
| Align start with destination slice | <img width="327" alt="image" src="https://github.com/google/perfetto/assets/6147146/9cda14de-17b2-466d-9600-499b4012f09f"> |
| Start down | <img width="270" alt="image" src="https://github.com/google/perfetto/assets/6147146/1feb2c17-0318-4b0a-9693-19abb643819a"> |
| Straight down | <img width="420" alt="image" src="https://github.com/google/perfetto/assets/6147146/96fe6059-d237-453d-ad14-f2194aef9184"> |
| Aligned start with start of source slice | <img width="324" alt="image" src="https://github.com/google/perfetto/assets/6147146/482f172d-acfb-406f-a69e-2361aec19289"> |
| Reversed (makes more sense when zoomed out) | <img width="214" alt="image" src="https://github.com/google/perfetto/assets/6147146/90f209d2-8e3b-44e1-b6b3-1310952e290b"> |

**Comment by lednakashim** [comment]
Wow, these are neat:
`Aligned start with start of source slice`
Seems to be the best bet because the meaning of the arrow location is clear and doesn't duplicate the meaning of the edge

<br class="Apple-interchange-newline">

**Comment by lednakashim** [comment]
For fun here is another synthetic sequence
[sequence_test.proto.zip](https://github.com/google/perfetto/files/12718663/sequence_test.proto.zip)

**Comment by stevegolton** [comment]
Thanks for the example trace :)

OK here's my latest thinking. You can try the result out [here](https://storage.googleapis.com/perfetto-ci-artifacts/20230928103046--cls-2753848-3--ui-clang-x86_64-release/ui/index.html) - just make sure to enable the "Neater Flow Arrows" flag.

Let me know what you think.

<img width="997" alt="image" src="https://github.com/google/perfetto/assets/6147146/04dec8bd-b593-4cbb-ab6a-27d968db0461">

**Comment by stevegolton** [comment]
Actually I think having arrows emenating from the left of the parent slice when there isn't much room makes a bit more sense - [Link](https://storage.googleapis.com/perfetto-ci-artifacts/20230928122817--cls-2753848-5--ui-clang-x86_64-release/ui/index.html)

![image](https://github.com/google/perfetto/assets/6147146/bdd4ef45-c974-4865-90aa-3d1120ae1f95)

**Comment by lednakashim** [comment]
> Actually I think having arrows emenating from the left of the parent slice when there isn't much room makes a bit more sense - [Link](https://storage.googleapis.com/perfetto-ci-artifacts/20230928122817--cls-2753848-5--ui-clang-x86_64-release/ui/index.html)
> 
> ![image](https://user-images.githubusercontent.com/6147146/271352314-bdd4ef45-c974-4865-90aa-3d1120ae1f95.png)

I've been using this branch for few weeks and it seams to help a lot. You guys going to merge it?

**Comment by lednakashim** [comment]
there is an adjacent issue with the time calculation of nested flows is seems to be always nailed 0 which is maybe additionally worth filing

**Comment by stevegolton** [comment]
Hey sorry for the delay, I haven't had a lot of time to work on this recently.

We just landed a patch (on autopush channel) which does a much better job of working out slice ancestors under the hood and draws arrows from the start of the parent slice which looks like this:

![image](https://github.com/google/perfetto/assets/6147146/365196a4-0a39-478a-95ae-1b53d564781f)

If this is enough, please close the issue. Otherwise I'll rebase my changes on top of this CL and try and get some opinions from the team.

> there is an adjacent issue where the time calculation of nested flow seems to be always nailed to 0 which is maybe additionally worth filing

Can you expand on this a little, maybe attach a screenshot?

**Comment by stevegolton** [comment]
Closing as this issue is addressed by the following patches:
- Nested slices: https://android-review.googlesource.com/c/platform/external/perfetto/+/2815711
- Any overlapping slices: https://android-review.googlesource.com/c/platform/external/perfetto/+/3001066
