### ISSUE TITLE
Try to rebuild for changing timestamp_clock_id?

### ISSUE THREAD

**Issue by c-jchen** [google/perfetto#591]
https://perfetto.dev/docs/concepts/clock-sync#operation

I noticed that this page mentioned multi-clock domain.

However,  I can not find how to rebuild for this "timestamp_clock_id ".

Would you please help to provide more information? or can I change default time by setting??

**Comment by LalitMaganti** [comment]
`timestamp_clock_id` is a field of the TracePacket proto. Information on it can be found at https://perfetto.dev/docs/reference/trace-packet-proto
