### ISSUE TITLE
Questions about how to use different clock domain?

### ISSUE THREAD

**Issue by c-jchen** [google/perfetto#592]
1. Do I need do trace_process again, after I set this setting at config and get pftrace file?

2. Another question is that I do not know how to check this setting is enable or not , after I apply primary_trace_clock?

>I want to change to BUILTIN_CLOCK_MONOTONIC_RAW, not default boot time.
>primary_trace_clock  :   I noticed that this setting.

>So I add below setting to my cocfig file.
>_________________________________________________________________
>builtin_data_sources: {
>			primary_trace_clock: BUILTIN_CLOCK_MONOTONIC_RAW
>}
>_______________________________________________________________

3. Does Trace Package need to re-build as a config? (Example I found from perfetto doc) 
    - I want to change "timestamp_clock_id" of package. 
>____________________________________________________
>protoc --encode=perfetto.protos.TraceConfig \
>       -I. protos/perfetto/config/perfetto_config.proto \
>        < config.txpb \
>        > config.bin
>________________________________________________________

**Comment by LalitMaganti** [comment]
> Do I need do trace_process again, after I set this setting at config and get pftrace file?

Well it will be a new trace so yes.

> Another question is that I do not know how to check this setting is enable or not , after I apply primary_trace_clock?

You need to recollect the trace. The trace will have the option set if it is present in the config.

> Does Trace Package need to re-build as a config? (Example I found from perfetto doc)

If you are passing the config as a binary proto, then yes.
