### ISSUE TITLE
how to merge trace file collected from different socs

### ISSUE THREAD

**Issue by hanbu111** [google/perfetto#594]
Stated in title, trace file is collected from different socs, how to merge them together into same timeline?

**Comment by aMayzner** [comment]
There is no supported way of merging two traces.

**Comment by LalitMaganti** [comment]
You might also want to consider the third-party tool vperfetto (https://github.com/741g/vperfetto) which can be used to merge traces but it is not supported by the Perfetto team. We do not have any tools on our side to do trace merging as Anna said.
