### ISSUE TITLE
Is there a python api to read perfetto line by line

### ISSUE THREAD

**Issue by GaoXing0608** [google/perfetto#597]
I have created a robot to analysis the app and system issue automatically base on android systrace. So I converted the perfetto to systrace by traceconv firstly.

I want to konw, is there a python api to read the perfetto line by line as the systrace file rather than convert it firstly and then read line by line.

**Comment by LalitMaganti** [comment]
I *strongly* recommend you switch approaches to instead use the Python API of Perfetto. the Perfetto format is very much *not* designed to be parsed in a line-based way. For efficiency, it makes use of a lot of tricks like interning, delta timestamps etc. which makes it impossible to parse line-by-line.

Documentation on the Python API is available at https://perfetto.dev/docs/analysis/trace-processor-python. If you insist on trying to do this with your current approach, converting to systrace will be your best bet but it is not something we have any capability of supporting from our side.
