### ISSUE TITLE
Flows do not render with `flow_ids`, as per guide

### ISSUE THREAD

**Issue by firebolt55439** [google/perfetto#601]
When attempting to follow the synthetic `TrackEvent` [guide](https://perfetto.dev/docs/reference/synthetic-track-event#flows) in the docs, I do not obtain the indicated output image (the three events with arrows between them, going left-to-right). Rather, I see no arrows at all.

Here is a minimal Protobuf reproduction of the 3-event example from the doc: [repro.pb.gz](https://github.com/google/perfetto/files/12745447/repro.pb.gz). (Note: it's actually a Protobuf file, not a gunzip archive, GitHub only allows certain file extensions).

Expected behavior: 
![image](https://github.com/google/perfetto/assets/1293223/46a8674d-9972-4ff0-adbd-bc30a0e14c30)

Actual behavior (see this by uploading above trace in ui.perfetto.dev):
<img width="1499" alt="image" src="https://github.com/google/perfetto/assets/1293223/c6973c06-8f7e-4093-abb6-f416e2064246">

For convenience, here's a textual dump of the Protobuf trace above (it is nearly identical to the example trace in the guide, modulo some different key sorting):
```
packet {
  track_descriptor {
    uuid: 93094
    thread {
      pid: 100
      tid: 100
      thread_name: "Main Thread"
    }
  }
}
packet {
  timestamp: 200
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_BEGIN
    track_uuid: 93094
    name: "Request generation"
    flow_ids: 1055895987
  }
}
packet {
  timestamp: 300
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_END
    track_uuid: 93094
  }
}
packet {
  timestamp: 400
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_BEGIN
    track_uuid: 93094
    name: "Process background result"
    flow_ids: 1055895987
  }
}
packet {
  timestamp: 500
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_END
    track_uuid: 93094
  }
}
packet {
  track_descriptor {
    uuid: 40489498
    thread {
      pid: 100
      tid: 101
      thread_name: "Background Thread"
    }
  }
}
packet {
  timestamp: 310
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_BEGIN
    track_uuid: 40489498
    name: "Background work"
    flow_ids: 1055895987
  }
}
packet {
  timestamp: 385
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_END
    track_uuid: 40489498
  }
}
```

Any help or guidance would be appreciated! Thanks :).

**Comment by firebolt55439** [comment]
Also, for convenience, here's a textual dump of the Protobuf trace above:
```
packet {
  track_descriptor {
    uuid: 93094
    thread {
      pid: 100
      tid: 100
      thread_name: "Main Thread"
    }
  }
}
packet {
  timestamp: 200
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_BEGIN
    track_uuid: 93094
    name: "Request generation"
    flow_ids: 1055895987
  }
}
packet {
  timestamp: 300
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_END
    track_uuid: 93094
  }
}
packet {
  timestamp: 400
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_BEGIN
    track_uuid: 93094
    name: "Process background result"
    flow_ids: 1055895987
  }
}
packet {
  timestamp: 500
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_END
    track_uuid: 93094
  }
}
packet {
  track_descriptor {
    uuid: 40489498
    thread {
      pid: 100
      tid: 101
      thread_name: "Background Thread"
    }
  }
}
packet {
  timestamp: 310
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_BEGIN
    track_uuid: 40489498
    name: "Background work"
    flow_ids: 1055895987
  }
}
packet {
  timestamp: 385
  trusted_packet_sequence_id: 3903809
  track_event {
    type: TYPE_SLICE_END
    track_uuid: 40489498
  }
}
```

**Comment by ddiproietto** [comment]
Unfortunately the textual dump of the Protobuf trace doesn't tell the whole story.

`flow_ids` type should be `repeated fixed64` (https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/protos/perfetto/trace/track_event/track_event.proto;l=221;drc=ce102357934e8bf42dc2fcc8a0b145a4faed4a9d), but in your trace it's encoded as `repeated fixed64 [packed=true]`.

Here's how we could fix this problem:
1. How are you encoding your protobufs? Which library are you using? Are you using a library that only supports "proto3" (In proto3 repeated fields are encoded as packed by default)? Can you switch to a library that supports encoding repeated fields as non packed?
2. As a workaround, you could reencode with protoc before passing it to ui.perfetto.dev. Here's a hacky way: `protoc --decode=perfetto.protos.Trace -Iperfetto perfetto/protos/perfetto/trace/trace.proto < repro.pb | protoc --encode=perfetto.protos.Trace -Iperfetto perfetto/protos/perfetto/trace/trace.proto > repro2.pb`, where `perfetto` is a directory where you have a checkout of the perfetto repo.
3. Ideally ui.perfetto.dev should accept your trace. https://protobuf.dev/programming-guides/encoding/#packed says
> Protocol buffer parsers must be able to parse repeated fields that were compiled as packed as if they were not packed, and vice versa.

Doing 3 requires a non trivial amount of work and I don't think fits nicely with the current parsing architecture, but I'm going to get @LalitMaganti comment on this.

**Comment by LalitMaganti** [comment]
> Doing 3 requires a non trivial amount of work and I don't think fits nicely with the current parsing architecture, but I'm going to get @LalitMaganti comment on this.

Yup agree with everything you say, you're absolutely right that if we follow the spec strictly, we would accept it. However,
* that would introduce a slight slowdown everywhere we parse repeated scalar fields which is in quite a few places
* it would add non-trivial complexity to the parsers

I would not do anything on our side for this issue.

**Comment by firebolt55439** [comment]
Thank you both for your help! I was using `betterproto` as the encoder -- I'll modify the generated bindings to ensure `flow_ids` are non-packed.

**Comment by ddiproietto** [comment]
> Thank you both for your help! I was using `betterproto` as the encoder -- I'll modify the generated bindings to ensure flow_ids are non-packed.

Great!
