### ISSUE TITLE
Dynamic height adjusment of y axis

### ISSUE THREAD

**Issue by lavanyaeswarappa** [google/perfetto#603]
Is it possible to increase the height of the y-axis in the perfetto UI based on the y axis value? 
Sort of missing on the granularity of the value change. 

![image](https://github.com/google/perfetto/assets/24353986/1f5386e5-eff7-44a7-9144-0cbddfd9f71f)

**Comment by LalitMaganti** [comment]
No there is no such functionality at the moment.

**Comment by LalitMaganti** [comment]
We now have support for expanding the height of counter tracks: this should solve the main usecase of this request.
