### ISSUE TITLE
Lost time information after converting trace file

### ISSUE THREAD

**Issue by Gitxg** [google/perfetto#607]
Using the traceconv tool, set Perfetto_ After the binary file is converted to trace file format, the timestamp identifier is discarded. Can it be converted completely?
![image](https://github.com/google/perfetto/assets/50760172/9eda5074-1059-42d7-86ed-61d7189b71b8)

**Comment by chromy** [comment]
The conversion can always be improved however we are unlikely to work on that.

Both:
- conversion to other trace formats (ftrace text, json)
- reading other trace formats (ftrace text, json)
are best effort.

Here I'm not sure what the upside of converting to another format then opening in the UI is given that the original file can already be opened in the UI.

Specifically "Absolute time" comes from here http://cs/h/android/platform/superproject/main/+/main:external/perfetto/ui/src/frontend/sql/slice.ts?l=122
. e.g. running  `ABS_TIME_STR` on the timestamp which in turns comes from here:
https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/trace_processor_impl.cc;l=418?q=ABS_TIME_STR which in turn comes from here: https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/perfetto_sql/intrinsics/functions/clock_functions.h;l=57;drc=5f8f8ab44b4ac659804a13fb75b6516f86f977e7;bpv=0;bpt=1

It's not immediately obvious why that fails for converted traces. Patches welcome to address that but we are unlikely to address it ourselves.
