### ISSUE TITLE
The captured trace tracks are disorderly and overlapping

### ISSUE THREAD

**Issue by Gitxg** [google/perfetto#608]
![image](https://github.com/google/perfetto/assets/50760172/2c29fe75-c855-4edc-abdc-26f1b876a296)

**Comment by primiano** [comment]
That is either:
1. a data loss
2. Some events that get in the way and break the begin/end slices

I think this is really related with aosp/2703534 where some mali events break the begin/end sequence.

Can you try the latest UI after that CL?

**Comment by Gitxg** [comment]
Could you please automatically eliminate these long and dazzling extra trajectories when generating the trace？

**Comment by LalitMaganti** [comment]
> Could you please automatically eliminate these long and dazzling extra trajectories when generating the trace？

We very intentionally do not hide issues like data loss as there can be real issues in the trace config/trace parsing causing them. Hiding this would be hiding the symptoms of a real problem instead of tackling the root case.
