### ISSUE TITLE
Can perfetto be used on Arm64 Debian system?

### ISSUE THREAD

**Issue by Leo-Yan** [google/perfetto#61]
Hi there,

I tried to follow up instructions in the page [1] to enable perfetto on my Arm64 SBC with Debian system:

$ git clone https://android.googlesource.com/platform/external/perfetto/ && cd perfetto
$ tools/install-build-deps
$ tools/build_all_configs.py

But it reports error as below:

~~~
root@linaro-developer:~/perfetto# tools/build_all_configs.py

Building linux_ubsan         [is_clang=true,is_debug=false,is_ubsan=true]
/root/perfetto/tools/gn gen /root/perfetto/out/linux_ubsan '--args=is_clang=true is_debug=false is_ubsan=true' --check
/root/perfetto/tools/run-buildtools-binary.sh: line 41: /root/perfetto/buildtools/linux64/gn: cannot execute binary file: Exec format error
~~~

So the installed binary "gn" is for x86 version and it cannot execute on Arm64 platform:

~~~
root@linaro-developer:~/perfetto# file /root/perfetto/buildtools/linux64/gn                                           
/root/perfetto/buildtools/linux64/gn: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2
.0, BuildID[xxHash]=95bb0d10452442f8, stripped                                                                        
~~~

Could you help confirm I am using correct steps to enable perfetto on Arm64?  Or am I missing anything for this?

Thank you for the guidance,
Leo

[1] https://android.googlesource.com/platform/external/perfetto/

**Comment by primiano** [comment]
Perfetto can definitely run on Arm64, but cannot be *built from* Arm64.
It needs to be cross-compiled from a x86_64 host.
Building from Arm64 would require porting the host tools on arm64, which is not impossible, but would represent extra maintenance burden.
Just grab a x86_64 machine and build using the following GN args:

```
target_os = "linux"
target_cpu = "arm64"
```

You'll need a arm64 capable compiler, both clang and gcc should work. clang is the default, gcc can be used setting `is_clang = false`

**Comment by Leo-Yan** [comment]
Sorry for I missed to reply to this ticket, thanks a lot for the info.
