### ISSUE TITLE
No intel version 

### ISSUE THREAD

**Issue by TheGithuber200** [google/perfetto#612]
No intel version

**Comment by TheGithuber200** [comment]
No intel version in the latest release

**Comment by primiano** [comment]
I opened https://github.com/google/perfetto/releases/tag/v38.0 and I definitely see
 - [linux-amd64.zip](https://github.com/google/perfetto/releases/download/v38.0/linux-amd64.zip)
 - [mac-amd64.zip](https://github.com/google/perfetto/releases/download/v38.0/mac-amd64.zip)
 - [android-x64.zip](https://github.com/google/perfetto/releases/download/v38.0/android-x64.zip)
 - [android-x86.zip](https://github.com/google/perfetto/releases/download/v38.0/android-x86.zip)


(historical reasons on why they are called amd64 vs x64, but they are practically the same).

What's missing?

**Comment by TheGithuber200** [comment]
Windows!
