### ISSUE TITLE
No Windows version 

### ISSUE THREAD

**Issue by TheGithuber200** [google/perfetto#613]
Add windows version

**Comment by TheGithuber200** [comment]
Doesn't work

**Comment by LalitMaganti** [comment]
Windows prebuilts are available at https://github.com/google/perfetto/releases/download/v38.0/windows-amd64.zip

If you are using x86, we have not and have no plans on supporting Windows versions of those prebuilts as Microsoft has been x64 only since Windows 11 in any case.
