### ISSUE TITLE
Perfetto UI - An unrecoverable problem occurred.

### ISSUE THREAD

**Issue by fujie2huang** [google/perfetto#616]
Perfetto UI - An unrecoverable problem occurred

If you are seeing this message, something went wrong while loading the UI.
Please file a bug (details below) and try these remediation steps:

* Force-reload the page with Ctrl+Shift+R (Mac: Meta+Shift+R) or
  Shift + click on the refresh button.

* [Clear all the site storage and caches](javascript:clearAllCaches();) and reload the page.

* Clear the site data and caches from devtools, following [these instructions](https://developers.google.com/web/tools/chrome-devtools/storage/cache#deletecache).

In any case, **FILE A BUG** attaching logs and screenshots from devtools.
  Googlers:      [go/perfetto-ui-bug](http://go/perfetto-ui-bug)
  Non-googlers:  [github.com/google/perfetto/issues/new](https://github.com/google/perfetto/issues/new)

Failed to load https://ui.perfetto.dev/v37.0-c69b33b9a/frontend_bundle.js

Technical Information:
LocalStorage: {}

**Comment by LalitMaganti** [comment]
This usually happens when the browser you are using is very old and does not support some modern web feature. The only way to debug this is that to check the devtools and see if there is an error there.

If this error is happening on some modern browser, feel free to reopen.

**Comment by primiano** [comment]
Also that can happen if the connection is incredibly slow and the assets don't load within 20 seconds
