### ISSUE TITLE
Question about counter's value

### ISSUE THREAD

**Issue by c-jchen** [google/perfetto#618]
There is a value 2.5GHz with White background  near counter name.

Would you please tell what the mean it is?

I can not find README for this vaule.

Thanks,
CJ

**Comment by chromy** [comment]
It's the scale of the counter. E.g. it's approximately the maximum value of
the counter over the lifetime of the track rounded up to the nearest useful
bucket.

Theres no specific documentation for that the idea is it's supposed to be
clear from context but I appreciate it was not in this case.

**Comment by c-jchen** [comment]
Thanks for your help.   
I checked that my max data is 5 or 3,  the scale will be changed automatilly.
