### ISSUE TITLE
Bazel build failure against latest protobuf

### ISSUE THREAD

**Issue by alokpr** [google/perfetto#621]
Bazel build fails against latest Protobuf v25.0:
```
perfetto/src/protozero/protoc_plugin/cppgen_plugin.cc:33:10: fatal error: google/protobuf/util/field_comparator.h: No such file or directory
   33 | #include <google/protobuf/util/field_comparator.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is because `@com_google_protobuf//src/google/protobuf/util:differencer` is no longer reachable via `@com_google_protobuf//:protoc_lib`. It can now only be used via `@com_google_protobuf//:protobuf`.

However `perfetto/src/protozero/protoc_plugin/cppgen_plugin.cc` does not need to include any files from the `@com_google_protobuf//src/google/protobuf/util` package. Those are unnecessary headers and can be completely removed from `cppgen_plugin.cc:`

**Comment by alokpr** [comment]
Attched patch fixes the issue
[fix-issue-621.patch](https://github.com/google/perfetto/files/13261101/fix-issue-621.patch)

**Comment by LalitMaganti** [comment]
Please see https://perfetto.dev/docs/contributing/getting-started#contributing on contributing. Otherwise, we'll likely only get to this issue when we uprev protobuf ourself (we need to keep in sync with the protobuf versions in both Chrome and Android).

**Comment by alokpr** [comment]
@LalitMaganti https://android-review.googlesource.com/c/platform/external/perfetto/+/2828342
