### ISSUE TITLE
Catapult json import with name: "" seems to break Perfetto

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#623]
I had several empty string named json blobs in Perfetto, and these seem to break Perfetto.  These are displayed as [null] and various error dialogs appear.   This meant I had to specify some non-empty string for every block.

And since Perfetto doesn't define a json format of it's own, deprecating the json doesn't seem like a great idea.   I'm writing this json from Python, so can't call through to protobuf based api easily.

```
{
"displayTimeUnit": "ns",
"systemTraceEvents": "SystemTraceData",
"traceEvents": [
{
"name": "thread_name",
"ph": "M",
"tid": 0,
"args": {
"name": "T0 block0 0"
}
},
{
"name": "",
"ph": "X",
"ts": 0,
"dur": 65536,
"tid": 0,
"cat": "TT"
}
]
}
```

**Comment by LalitMaganti** [comment]
Please see https://github.com/google/perfetto/issues/622#issuecomment-1793888912.

**Comment by alecazam** [comment]
This is pretty basic support to fail on this case.  I see the importer setting these on empty string in the source.  But then the rest of Perfetto seems to fail handling that null string id. 

https://github.com/google/perfetto/blob/master/src/trace_processor/importers/json/json_trace_parser.cc, line 112

StringId name_id = name.empty() ? kNullStringId : storage->InternString(name);

**Comment by LalitMaganti** [comment]
https://r.android.com/2817378 fixes.
