### ISSUE TITLE
Catapult json importer ignores cname

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#624]
cname field doesn't appear to get imported.  And while randomly assigning colors is one approach, I'd really like to assign my own colors to the memory blocks that I'm sending over.

Note that the capatpult names defined here seem limited.  So if there's anyway to expand those to full rgb control, that would help.

https://github.com/catapult-project/catapult/blob/master/tracing/tracing/base/color_scheme.html

```
{
"displayTimeUnit": "ns",
"systemTraceEvents": "SystemTraceData",
"traceEvents": [
{
"name": "thread_name",
"ph": "M",
"tid": 0,
"args": {
"name": "T0 block0 0"
}
},
{
"name": "SomeName",
"ph": "X",
"ts": 0,
"dur": 65536,
"tid": 0,
"cat": "TT",
"cname": "grey"
}
]
}
```

**Comment by LalitMaganti** [comment]
Please see https://github.com/google/perfetto/issues/622#issuecomment-1793888912.

**Comment by LalitMaganti** [comment]
cname specifically actually is something which we intentionally chose not to support. See context in https://github.com/google/perfetto/issues/620 and https://github.com/google/perfetto/issues/208.

**Comment by alecazam** [comment]
This was problematic, since I have types that should all be colored similarly.  Leaving this to the whims of randomly assigning colors to names also didn't work.  I had blocks labelled 0, 1, 2 and they all got the same colors.  But using unique names, then colors seem assigned more consistently different across the trace files.
