### ISSUE TITLE
Question about Vega and Vega-lite

### ISSUE THREAD

**Issue by c-jchen** [google/perfetto#625]
I noticed version 37 provided VIZ.

However, I can not find some User guide about this.

Would you please help me to understand when I hit VIZ button and UI shows "Unexpected end of JSON input"?

**Comment by LalitMaganti** [comment]
This feature is under heavy development and might well be reworked but the current documentation for this is available at https://perfetto.dev/docs/visualization/perfetto-ui#custom-visualisation-with-vega-and-vega-lite

**Comment by jamolama** [comment]
is this feature still under development? Checking because this ticket has been closed and the viz feature is mentioned in the [public docs](https://perfetto.dev/docs/visualization/perfetto-ui#custom-visualisation-with-vega-and-vega-lite) but I'm still encountering the previously reported error " "Unexpected end of JSON input""

**Comment by LalitMaganti** [comment]
It's an experiment which ended up not going anywhere. We should probably disable it to avoid people trying it and getting confused.

**Comment by jamolama** [comment]
appreciate the quick response! For what it's worth, I think this would be a great feature. An alternative is to export the json and use another visualization tool but that requires the user to be a bit more familiar with the schema. 

Anyways, agree it's less confusing to remove this from the docs or explicitly mention it's not functional.

**Comment by LalitMaganti** [comment]
We're definitely planning on improving the analytics experience inside the UI but the way the viz tab does it is not quite the right approach.

**Comment by james-aws** [comment]
great, thanks for the clarification

**Comment by jamolama** [comment]
Great, thanks for the clarification
