### ISSUE TITLE
None of the perfetto sql tables for Android have the data I need

### ISSUE THREAD

**Issue by TheGithuber200** [google/perfetto#628]
Which is data of the wifi hardware device/sim card. Since it disconnected randomly and is in my trace. Please provide SQL guidance.

**Comment by LalitMaganti** [comment]
Sorry we cannot help with general questions like this. We are not in the business of writing SQL queries for other people: if we did this for everyone, we'd spend all our time doing just this.

**Comment by TheGithuber200** [comment]
Then give guidance on the tables where device info is located

**Comment by TheGithuber200** [comment]
Don't fucking close this
