### ISSUE TITLE
PDB Symbols for Windows Perfetto build

### ISSUE THREAD

**Issue by ivberg** [google/perfetto#631]
Can the debugging .pdb symbol be included with the Perfetto Windows binary?

This is helpful for debugging, performance, and security checks. An alternative would to be publish the .pdb on a public pdb symbol server as well.

**Comment by ivberg** [comment]
For reference on a related project Protobuf is both signed by Google AND includes .pdbs
https://www.nuget.org/packages/Google.Protobuf/

**Comment by ivberg** [comment]
Ok - good news I was able to generate these and here is a patch. I can't submit it in the other source repro due to permissions and other blocking issues so if someone can on my behalf that is appreciated.

This issue comes about mostly likely because it's fairly common thing for devs on Windows to confuse a debugging symbol (.pdb files) with a non-optimized debug build that makes it easier to debug. Those are related concepts but 2 different things. All Windows binaries built by devs whether debug or release should produce debug .pdb symbols.

The below patch fixes some confusion in the build definitions that led to no .pdb on release builds (is_debug = false). You get both an optimized build AND a .pdb

--perfetto_patch_release_pdb.diff--
```
diff --git a/gn/standalone/BUILD.gn b/gn/standalone/BUILD.gn
index 19c802937..34f9ae1db 100644
--- a/gn/standalone/BUILD.gn
+++ b/gn/standalone/BUILD.gn
@@ -319,9 +319,11 @@ config("default") {
     include_dirs = win_msvc_inc_dirs  # Defined in msvc.gni.
   }
 
+  if (is_win) {
+    cflags += [ "/Zi" ]
+  }
   if (is_debug) {
     if (is_win) {
-      cflags += [ "/Z7" ]
       if (is_clang) {
         # Required to see symbols in windbg when building with clang-cl.exe.
         cflags += [ "-gcodeview-ghash" ]
@@ -394,7 +396,7 @@ config("default") {
   }
 }
 
-config("debug_symbols") {
+config("debug_noopt") {
   cflags = []
   if (is_win) {
     cflags = [ "/Od" ]
diff --git a/gn/standalone/BUILDCONFIG.gn b/gn/standalone/BUILDCONFIG.gn
index 3a1119dff..56ffc9671 100644
--- a/gn/standalone/BUILDCONFIG.gn
+++ b/gn/standalone/BUILDCONFIG.gn
@@ -63,7 +63,6 @@ declare_args() {
       target_cpu != host_cpu || target_os != host_os || target_triplet != ""
 }
 default_configs = [
-  "//gn/standalone:debug_symbols",
   "//gn/standalone:default",
   "//gn/standalone:extra_warnings",
   "//gn/standalone:no_exceptions",
@@ -78,9 +77,11 @@ if (is_win) {
   default_configs += [ "//gn/standalone:win32_lean_and_mean" ]
 }
 
+
 if (!is_debug) {
-  default_configs -= [ "//gn/standalone:debug_symbols" ]
   default_configs += [ "//gn/standalone:release" ]
+} else {
+  default_configs += [ "//gn/standalone:debug_noopt" ]
 }
 
 set_defaults("source_set") {
diff --git a/gn/standalone/toolchain/BUILD.gn b/gn/standalone/toolchain/BUILD.gn
index e462bd5a2..387733806 100644
--- a/gn/standalone/toolchain/BUILD.gn
+++ b/gn/standalone/toolchain/BUILD.gn
@@ -491,7 +491,7 @@ toolchain("msvc") {
     rspfile = "$exename.rsp"
 
     command =
-        "$linker /nologo /OUT:$exename ${sys_lib_flags} /PDB:$pdbname @$rspfile"
+        "$linker /nologo /OUT:$exename ${sys_lib_flags} /DEBUG /PDB:$pdbname @$rspfile"
     default_output_extension = ".exe"
     default_output_dir = "{{root_out_dir}}"
     outputs = [ exename ]

```

**Comment by ivberg** [comment]
Thx !

**Comment by primiano** [comment]
I'm re-opening this because, while the patch has landed, we need to update our bots / instructions to upload also pdbs in our prebuilts.

Also note that r.android.com/2828136 has also landed

**Comment by LalitMaganti** [comment]
From v40+, PDBs should be included in our releases so re-closing this.
