### ISSUE TITLE
What is the main purpose of Perfetto's code hosting on GitHub?

### ISSUE THREAD

**Issue by barnett-yuxiang** [google/perfetto#633]
This is the mirroring of the aosp subrepo. Will the issue here be handled? And can it be considered to be associated with Discord for developers to follow up?

**Comment by LalitMaganti** [comment]
GitHub is a pure read-only mirror repo. As developers (including ourselves) are familiar with GitHub, we can use it to easily browse the codebase without relying on the archaic way of navigation in AOSP.

Think of it as a pure convenience thing: we don't do any development here.

**Comment by primiano** [comment]
Also we publish prebuilt binaries for various platforms on a regular basis on the Github releases page.

**Comment by barnett-yuxiang** [comment]
> Also we publish prebuilt binaries for various platforms on a regular basis on the Github releases page.

I have a proposal to automatically synchronize everyone's issues on GitHub to discrod. There are actually quite a few people using perfetto, and the community cohesion is weaker. I am also in the Perfetto Discord community. If I have time, I can also work on it.

**Comment by barnett-yuxiang** [comment]
> > I have a proposal to automatically synchronize everyone's issues on GitHub to discrod. There are actually quite a few people using perfetto, and the community cohesion is weaker. I am also in the Perfetto Discord community. If I have time, I can also work on it.
> 
> I don't think we'd necessarily be opposed to that but I'm curious what the end result would look like (I've never seen anyone track issues on Discord). Do you have an example that we can see?

Ofc, these are quite common nowadays. I am more active in the [codium.ai](http://codium.ai/) pr-agent project.

Screenshot:
![20231109-010621](https://github.com/google/perfetto/assets/12042337/666c74ff-03d9-4ffd-8eb3-c8043ce7ae55)

Link: [JOIN OUR DISCORD](https://discord.gg/SgSxuQ65GF)

Younger developers prefer more efficient feedback tools

**Comment by LalitMaganti** [comment]
Personally, LGTM makes sense if it's just a mirror of GitHub issues. @primiano any objections to us doing this?

**Comment by primiano** [comment]
I'm fine with this in principle. The only question is really: which sort of permissions does this require?
If this requires oauth scopes that need to be granted at the org-level (Which for us is google) they might not get granted / the process for them might be complicated.
