### ISSUE TITLE
when using Perfetto，and record trace online, the browser notice"No device found: Error: WebUSB not supported by the browser (requires HTTPS)", but in chrome device list,, the mobile device show normally.

### ISSUE THREAD

**Issue by EthanGuser** [google/perfetto#637]
when using Perfetto，and record trace of  mobile phone online, 
the browser notice an error "No device found: Error: WebUSB not supported by the browser (requires HTTPS)",.
but in chrome device list,, the mobile device show normally.

so, what's the problem?

**Comment by primiano** [comment]
Are you using it via ui.perfetto.dev?
Looks like you are using a version of perfetto embedded somewhere else, and webusb is not available
