### ISSUE TITLE
Some tables are  not existed by using trace_processor_shell.exe ,but exist on perfetto ui

### ISSUE THREAD

**Issue by Shi-Yukun** [google/perfetto#639]
When I execute  "select * from cpu_freq_sched_per_thread" by using 'trace_processor_shell.exe', it show 'no such table: cpu_freq_sched_per_thread'.
However it can get result  when I execute the same sql on perfetto ui.

Platform: Windows 10
Python version: 3.8.7
trace_processor_shell.exe : V38

**Comment by aMayzner** [comment]
Perfetto UI is creating additional tables on top of Trace Processor shell,
but most of them can be found in Trace Processor Standard Library.

**Comment by Shi-Yukun** [comment]
How could I have access to these additional tables by using trace_processor_shell.exe
I have searched api.py , but I can not find a funtion to create a table.

**Comment by Shi-Yukun** [comment]
I also create these tables by using  its sql.
Thank you very much for your reply!

**Comment by LalitMaganti** [comment]
Note that the `cpu_freq_sched_per_thread` specificlally is part of the CPU metric so is not a stable API: it could change at any time.

The documentation for the standard library is found at https://perfetto.dev/docs/analysis/stdlib-docs which describes how it can be used.
