### ISSUE TITLE
Paser tracefile by UI has some problem?

### ISSUE THREAD

**Issue by zengjunjun** [google/perfetto#64]
**Error Info :**

[trace_file.pftrace.zip](https://github.com/google/perfetto/files/5352143/trace_file.pftrace.zip)

To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

Uncaught Error: abort("trap!"). Build with -s ASSERTIONS=1 for more info.

stderr: 
[094.852] oto_trace_reader.cc:254 incremental_state_cleared without trusted_packet_sequence_id
[094.852] oto_trace_reader.cc:254 incremental_state_cleared without trusted_packet_sequence_id
[094.852] oto_trace_reader.cc:282 TracePacketDefaults packet without trusted_packet_sequence_id
[094.852] wasm_bridge.cc:73       Fatal failure while parsing the trace: ClockSnapshot packet is specifying a sequence-scoped clock id (64) but the TracePacket sequence_id is zero (errno: 0, No error information)
trap!

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

Tracefiel has attaced.

**Comment by primiano** [comment]
@zengjunjun  how did you collect this trace?

**Comment by zengjunjun** [comment]
using command by config :
```
buffers: {
    size_kb: 63488
    fill_policy: DISCARD
}

data_sources: {
    config {
        name: "org.chromium.trace_event"
        chrome_config {
            trace_config: "{\"blink\",\"blink.animations\",\"blink.console\",\"blink_gc\",\"blink.net\",\"blink_style\",\"blink.user_timing\",\"blink.worker\",\"Blob\",\"browser\",\"browsing_data\",\"CacheStorage\",\"camera\",\"cast_perf_test\",\"cast.stream\",\"cc\",\"cc.debug\",\"cdp.perf\",\"chromeos\",\"cma\",\"compositor\",\"content\",\"content_capture\",\"devtools\",\"devtools.timeline\",\"devtools.timeline.async\",\"download\",\"download_service\",\"drm\",\"drmcursor\",\"dwrite\",\"DXVA Decoding\",\"EarlyJava\",\"evdev\",\"event\",\"exo\",\"explore_sites\",\"FileSystem\",\"file_system_provider\",\"fonts\",\"GAMEPAD\",\"gpu\"]}"
        }
    }
}
duration_ms: 10000
```

**Comment by primiano** [comment]
@betasheet @skyostil

**Comment by betasheet** [comment]
Chromium system traces require android 10. The tracing service shipped with android 9 is too old to support trusted_packet_sequence_id, which is required for chrome data sources.

**Comment by zengjunjun** [comment]
Thanks
