### ISSUE TITLE
convert systrace to perfetto trace

### ISSUE THREAD

**Issue by lbknxy** [google/perfetto#641]
Hi, 
it's very slow to open systrace file (captured by systrace.py)  with perfetto UI, I want to know if it's possible to convert systrace file to compressed perfetto trace file.

Thanks!

**Comment by LalitMaganti** [comment]
No this is not possible.

In any case, systrace.py is very much considered deprecated and you should be collecting traces in the Perfetto native format as described [here](https://perfetto.dev/docs/quickstart/android-tracing).
