### ISSUE TITLE
Add setting to suppress the thread id displayed with each thread name

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#644]
We set a thread name in our trace files, and just make up a unique id.  But would like to not have that displayed.  Seeing "JobThread1 2" where 2 is the thread id is just confusing.   Would be nice to have option to hide the thread id, and only display the thread name.   I can't imagine most people wanting to see a thread id, when they already have a name.  

![image](https://github.com/google/perfetto/assets/3750359/ab88389f-ea18-4c44-aeec-970c18e5406a)

**Comment by horusli** [comment]
it is coded @ui/src/public/utils.ts, by removing ${tid} and ${pid} related variables in the getTrackName function call, we can drop the unwanted number at the tail.

**Comment by primiano** [comment]
Yes, the problem is that we don't want to do that, because in most cases when we look at system traces that number is useful.

> I can't imagine most people wanting to see a thread id

I disagree as that-s useful to correlate traces with other logs
