### ISSUE TITLE
How to essentially optimize trace file size？

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#647]
hi~ 
First of all thank you very much for your work, I have some ideas.

For integrating perfetto into large projects, the data volume of the generated trace file will increase as the crawling time becomes longer. Although a mechanism similar to starting the trace_processor service locally is provided to load data. But still facing the problem of slow loading of trace files, Is there any other solution to improve the speed of loading large files?

**I think the essential reason lies in the trace file format and data storage method .** 

Take track event name as an example:

1. The longer the event name, the more data is stored.  Is it possible to abbreviate the long name string when storing, and then map it back to the original name when reading?
2. Each interface that calls track event will record complete data and store it in the trace file. This means that multiple strings with the same name are stored in the trace file.  Is it possible to store only one copy of all the same track event name strings?

I'm looking forward to your reply, thank you so much.

**Comment by primiano** [comment]
> The longer the event name, the more data is stored. Is it possible to abbreviate the long name string when storing, and then map it back to the original name when reading?

Yes using interning, if the cardinality of DISTINCT(event names) is low (i.e. the same event names are repeated over and over). Look for "interning" or "interned data" in the TracePacket proto

> Each interface that calls track event will record complete data and store it in the trace file. This means that multiple strings with the same name are stored in the trace file. Is it possible to store only one copy of all the same track event name strings?

IIRC when using the tracing SDK, track events by default are interned (per thread)

@ddiproietto to keep me honest
