### ISSUE TITLE
trace_processor_shell build on Windows

### ISSUE THREAD

**Issue by horusli** [google/perfetto#649]
Hi,

One quick question.
Can we build trace_processor_shell on windows platform with latest perfetto depo?
I just check tools/setup_all_configs and found currently only Linux/mac/android is supported.
I remember in v35.0 and before e can use tools/ninja to build it, do we have other alternative to generate executable under windows platform?

**Comment by primiano** [comment]
Can you be more specific? building trace_processor_shell on windows is still supported.

setup_all_configs doesn't build configs for windows, but you can simply build one doing:

```
gn args out\win
```
then typing

```
is_clang=true
is_debug=false
```

and then

```
ninja -C out\win trace_processor_shell
```

See also https://perfetto.dev/docs/contributing/build-instructions#building-on-windows

Also note that we periodically publish binaries on github, see https://github.com/google/perfetto/releases/tag/v39.0
