### ISSUE TITLE
[documentation] "duration_ms" is not working with trigger_mode: STOP_TRACING

### ISSUE THREAD

**Issue by bagobor** [google/perfetto#65]
Using 'duration_ms' config param will lead to immediate termination of trace session. But it's  mentioned in:
1. https://github.com/google/perfetto/blob/master/docs/concepts/config.md
2. compiled HTML version https://perfetto.dev/docs/concepts/config

So far it looks like that when stop trigger is used, duration is calculated as:
trigger_config.trigger_timeout_ms + trigger_config.triggers.stop_delay_ms

Please update the documentation, I've spent several hours to make stop trigger behave as intended ‼️

**Comment by chromy** [comment]
Yes that looks wrong, will send a patch for that. Thanks!

Hector

**Comment by bagobor** [comment]
@chromy btw, what is the best way to contribute? can I create a PR to this repo? (I'm a bit confused with its R/O state).

**Comment by chromy** [comment]
@bagobor The contribution instructions are at https://perfetto.dev/docs/contributing/getting-started :) We use a Gerrit instance for code reviews: https://android-review.googlesource.com/q/project:platform%252Fexternal%252Fperfetto+status:open

**Comment by bagobor** [comment]
@chromy 
> contribution instructions are at https://perfetto.dev/docs/contributing/getting-started
thanks, "Pull requests through GitHub are not accepted." :)

**Comment by chromy** [comment]
This should now be fixed :)
