### ISSUE TITLE
How to identify a kernel thread?

### ISSUE THREAD

**Issue by rollysys** [google/perfetto#650]
For example, the swapper/irq/kworker/rcu, and so on
I want to find out all these kernel threads in trace_processor, but not sure how to do this officially.
Thanks

**Comment by primiano** [comment]
All kernel threads are modelled a processes parented to a fictitious "kthreadd" process.
So you can just filter for threads belonging to processes parented to kthreadd

It becomes more evident from this query:
```
select
  t.name as tname, t.tid as tid,
  p.name as pname, p.pid as pid, pp.name as parent_name
  from thread t
     left join process p using(upid)
     left join process pp on p.parent_upid = pp.pid
```

![image](https://github.com/google/perfetto/assets/7137473/3ea0ee6c-1818-46c8-8e09-8fea74035c61)
