### ISSUE TITLE
Shared memory buffer overrun! Stalling

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#652]
hello~ 
When using perfetto to capture data, the following information is reported: Shared memory buffer overrun! Stalling

What is the cause of this and how to solve it?

Thank you

**Comment by primiano** [comment]
That is fine if the stall is temporary and the process recovers. 

If it doesn't it will lead to a crash.

Do you see the crash, or just the message? if just the message it is safe to ignore
