### ISSUE TITLE
Display problem of perfetto ui

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#653]
hello~
My configuration file uses the write_into_file field.
I captured 10s of data, but after loading it using perfetto UI, the timeline shows 20s of data.
What is the reason for this and how to solve it?

Thank you

**Comment by primiano** [comment]
sorry but this bug is completley unactionable as it's too generic.
Please provide a copy of the config used, and the trace you got back.

Too many things could go wrong and without  a specific example is impossible to help here.
