### ISSUE TITLE
HELP! The basic duration events "B" and "E" stopped working. The resulting span does not end and goes to the end of timeline

### ISSUE THREAD

**Issue by nickshrayer** [google/perfetto#659]
[sample.txt](https://github.com/google/perfetto/files/13552375/sample.txt)
![image](https://github.com/google/perfetto/assets/37577003/1fb71d33-1595-4c75-bdd3-b5864dd13d0d)

**Comment by primiano** [comment]
This is indeed weird. @aMayzner can you look at this?

This seems to happen because the "E" doesn't have a name.

The minimal repro is

```
{"traceEvents": [
,{"ph":"B", "name": "12345", "pid":1, "tid":123, "ts": 703}
,{"ph":"E", "ts": 750, "pid":1, "tid":123 }
]}
```

and gets fixed if you add a "name":"12345" to the end events.

But we should be able to close slices from the stack purely based on pid/tid

**Comment by nickshrayer** [comment]
@primiano , your statement is not correct. Adding "name" does not help either. I.e. following does not work exactly same:

```
{"traceEvents": [
,{"ph":"B", "name": "12345", "pid":1, "tid":123, "ts": 703}
,{"ph":"E", "name": "12345", "ts": 750, "pid":1, "tid":123 }
]}
```

**Comment by nickshrayer** [comment]
Correct @primiano

**Comment by noomorph** [comment]
Yes, I confirm this. This issue affects the infra team's work at Wix now.

cc @d4vidi for visibility (our trace logs are unusable on CI now)

**Comment by primiano** [comment]
Just to be clear, was this ever working at any point in the past?
i think this a bug that we always had since day 0, not a recent regression, right?

**Comment by LalitMaganti** [comment]
No this was a recent issue introduced by aosp/2817378.

**Comment by nickshrayer** [comment]
Sorry for the unrelated question but when should the fix be available at https://ui.perfetto.dev/#!/viewer ?

**Comment by LalitMaganti** [comment]
It should now be available (as of https://r.android.com/2859568)

**Comment by primiano** [comment]
Well, "now" in the autopush channel, in O(weeks) on canary and O(months) in stable

See also https://perfetto.dev/docs/visualization/perfetto-ui-release-process

**Comment by nickshrayer** [comment]
Yes, I realized that. Thanks a lot for a very prompt fix. That helped a lot and allowed for building the trust in outstanding solution you provide!

**Comment by noomorph** [comment]
@nickshrayer, do you also have your in-house tool using the Trace Events format? :)

**Comment by nickshrayer** [comment]
Tool? No, we open timing diagrams using the Python luncher referenced by you.
Or I didn't understand the question?

BTW, what we (really-really-really-really)^10 miss is the ability to:
1. Store pinned tracks layout
2. Having a scrollbar on pinned layouts part because when many tracks a pinned, it becomes impossible to operate the regular ("processes") area

I did see there are such requests in forum, but they are not addressed... Any chance to promote those?

**Comment by LalitMaganti** [comment]
> Store pinned tracks layout

This can be accomplished with plugin commands today: [Store pinned tracks layout](https://perfetto.dev/docs/contributing/ui-plugins#commands)

> Having a scrollbar on pinned layouts part because when many tracks a pinned, it becomes impossible to operate the regular ("processes") area

I think we've made quite clear over the years this would never happen because we think nested scrollability has terrible UX.

What might happen is something like "hide all tracks except...": when it does, it would also be implemented using plugins.

**Comment by LalitMaganti** [comment]
> My feature request (sorting threads) is likely to be never implemented.

Historically, the problem with requests like this is, yes we can do something custom for a particular user's usecase but every single different user of Perfetto has a different idea on what they consider "important" or what the think is the "right UX".

The solution for this is plugins: every user can have whatever plugin they deem is necessary to make the trace look the way they want without the Perfetto team needing to be involved.

The UI team have been very hard at work over the past several months on ~essentially rewriting the UI from the ground up (with a significant amount of tech debt reduction thrown in) to implement this API: once this is complete, anyone can write a plugin to do whatever they want re, creating new tracks, reordering tracks, showing/hiding tracks, nesting tracks etc.

**Comment by noomorph** [comment]
@LalitMaganti, I'm happy to hear that this problem will be eventually resolved, and I'll be looking forward to the plugins subsystem. Plugins are fun. 🥳
