### ISSUE TITLE
ATrace CPU time is not shown

### ISSUE THREAD

**Issue by bagobor** [google/perfetto#66]
New perfetto trace viewer is awesome!
But It's lacking 'cpu time', 'self cpu time' metrics comparing with obsolete catapult viewer. 
Is it by design?

**Comment by chromy** [comment]
Hi @bagobor!

CPU time is missing at the moment, we do want to add it but we haven't got around to it yet.
I'm afraid we don't have a specific timeline for this feature (it won't be added before the end of the year for sure).
If you want to chat about it more feel free to hop over onto Discord https://discord.gg/35ShE3A

Thanks,
Hector

**Comment by LalitMaganti** [comment]
We have no plans to add this at this point so closing. Contributions for this are welcome.

**Comment by benjaminRomano** [comment]
For future reference, it is possible to compute per-slice CPU time ad-hoc with trace processor using the query here:  https://perfetto.dev/docs/analysis/common-queries#computing-cpu-time-for-slices.

This was able to address my use case for Atrace CPU Time support
