### ISSUE TITLE
libperfetto_sdk.so coredump

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#662]
I compiled the perfetto sdk source code into the dynamic library libperfetto_sdk.so, and then the program called the library to execute some track_event events (such as TRACE_EVENT_BEGIN/END(category, name, ...)), but the program crashed, and I used gdb to debug the coredump file.
release libperfetto_sdk.so:
![image](https://github.com/google/perfetto/assets/31888567/f9b3f18d-38d8-4c09-bf2d-7b8f790ac980)
debug libperfetto_sdk.so:
![image](https://github.com/google/perfetto/assets/31888567/2ecf2668-6157-448f-8185-470bd2e044b8)

May I ask what is the reason and how to solve it? I look forward to your reply. Thank you.

**Comment by ddiproietto** [comment]
> I compiled the perfetto sdk source code into the dynamic library libperfetto_sdk.so

First of all this is [not officially supported](https://perfetto.dev/docs/design-docs/api-and-abi#static-linking-vs-shared-library), so it's possible that you run into unexpected issue when doing something like this.

> but the program crashed, and I used gdb to debug the coredump file.

Thanks for sharing the stack trace. Unfortunately it doesn't tell enough to understand and fix the problem.

Can you please share a minimal way to reproduce the problem?
