### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by SmallCookier** [google/perfetto#663]
Does the tool have any requirements for device memory?When I use it on 6 devices with 3G and 2G memory, the following error will be reported
Traceback (most recent call last):
  File "heap_profile", line 848, in <module>
    sys.exit(main(sys.argv))
  File "heap_profile", line 648, in main
    uuid_trace = release_or_newer('R')
  File "heap_profile", line 387, in release_or_newer
    sdk = int(
ValueError: invalid literal for int() with base 10: ''

**Comment by ddiproietto** [comment]
Thanks for reporting this.

This is just a problem with the `heap_profile` script. Can I ask you to run the command:

`adb shell getprop ro.system.build.version.sdk`

and copy the output here?

The `heap_profile` [script expects an integer](https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/tools/heap_profile;l=387;drc=e7df7ebaa80e2eb3e425765d047563bebb41c508), but you're getting something else.

On my device I get:

```
sh-5.2$ adb shell getprop ro.system.build.version.sdk
34
sh-5.2$ 
```

**Comment by LalitMaganti** [comment]
Given the lack of a response here, I'm going to close this out.
