### ISSUE TITLE
Is there a way to assign names to threads instead of just the thread id?

### ISSUE THREAD

**Issue by RishiTejaMadduri** [google/perfetto#664]
Currently Perfetto UI only shows unique thread IDs. Is there a way to also set or assign names to thread in the UI? For example: Easy profiler has a macro: `EASY_THREAD` that allows users to assign a name for each thread

**Comment by RishiTejaMadduri** [comment]
I am not manually writing traces. I am using Perfetto macros within my code to collect trace information. Right now there are macros that will collect `__FILE__ and `__LINE__` along with `functionName()`. 

Let us say my `thread 1` runs functions `foo()` & `bar()`. 
and I call perfetto trace macros here.

The trace would look something like:
`Thread 41789 - info about foo() and bar()`

Is there a way/macro to assign a thread name here instead of just the id:

`Thread FooBar - info about foo() and bar()`

**Comment by ddiproietto** [comment]
Yes, there should be a way. Check https://perfetto.dev/docs/instrumentation/track-events#tracks ("Threads and processes can also be named in a similar way"...)

You should be able to do something like this on your thread:

```
auto desc = perfetto::ThreadTrack::Current().Serialize();
desc.mutable_process()->set_thread_name("MyThreadName");
perfetto::TrackEvent::SetTrackDescriptor(
    perfetto::ThreadTrack::Current(), desc);
```
