### ISSUE TITLE
Misc Global Tracks => Screenshots track is always shown

### ISSUE THREAD

**Issue by niklaut** [google/perfetto#666]
Thanks for this awesome tool! I generate synthetic perfetto files from [tracing ARM Cortex-M devices](https://github.com/Auterion/embedded-debug-tools/tree/main/ext/orbetto) so I know that there are no screenshot events emitted.

The Misc Global Tracks is always showing up as a process and it's just a little annoying cos it takes away screen space.
![](https://github.com/google/perfetto/assets/121870655/bdff9491-1765-4f28-890f-122009531113)

If I recall correctly this is new behavior since v39.

**Comment by stevegolton** [comment]
This is actually a misbehaving builtin plugin.

I just pushed https://android-review.googlesource.com/c/platform/external/perfetto/+/2871474 to fix it.

@niklaut Can you let me know which release channel you're on?

**Comment by niklaut** [comment]
> I really love what I see here :)

Thanks! The goal is to add complete call stacks via ETM tracing soon and then use the trace processor to validate specific RTOS properties during refactoring/fixing.

> This is actually a misbehaving builtin plugin.

Thanks for fixing this!

I'm using what is served by ui.perfetto.dev. For me it's currently [v39.0-fa6ee](https://android.googlesource.com/platform/external/perfetto/+/fa6ee75b6f4a9374ade506697c65a8a73edc54be/ui) for release and [v40.0-46dae](https://android.googlesource.com/platform/external/perfetto/+/46dae5655847f65acd49cad6a24ef37c6a85383d/ui) for canary. Both have this issue.

**Comment by stevegolton** [comment]
No problem! The fix should make its way to canary next week.

Once the CL lands, you're welcome to use autopush in the meantime (this setting is available on the [flags](https://ui.perfetto.dev/#!/flags) page).
