### ISSUE TITLE
query uninterruptible sleep state with python sql 

### ISSUE THREAD

**Issue by wjj1928** [google/perfetto#668]
I Attached trace thread 3492 has a ANR happen, so I check the status from perfetto UI and got below image:
![image](https://github.com/google/perfetto/assets/65702/2ff84f53-523f-44ec-87ed-535b7bf339b9)

I would like to query "uninterruptible sleep" with python api.
I try below statement but not find "uninterruptible sleep" slice:
 `   sql = 'select ts, dur, cpu, end_state, priority, process.name, thread.name from sched_slice left join thread using(utid) left join process using(upid)'

And what maybe the reason cause a 39 secs "uninterruptible sleep"?
[Uploading boottrace.perfetto-trace.zip…]()
`

**Comment by aMayzner** [comment]
Hi. This issue is not related with python API, you are just not querying the right table. 
```
SELECT 
ts, 
dur, 
cpu, 
utid, 
upid, 
thread.name AS thread_name,
process.name AS process_name, 
state 
FROM thread_state 
LEFT JOIN thread USING (utid) 
LEFT JOIN process USING (upid)
```
