### ISSUE TITLE
visualization cpu utilization per process

### ISSUE THREAD

**Issue by wjj1928** [google/perfetto#669]
Hi,

I would like to show android system_server CPU utilization just like below:
![image](https://github.com/google/perfetto/assets/65702/bef9f60a-176f-47c1-8b7e-23e526072163)

Current UI looks like just show some short segments, it's not easy to understand.

Do we have plan to add such feature?
Or how can I do it? such as which sql to query and how to calculate the valid percentage? then we can graph it with python.

**Comment by LalitMaganti** [comment]
Couple of notes:
1) The slices correspond to the time the process was running. This allows you to pinpoint exactly on which CPU the process was running
2) CPU utilization is a terrible metric on Android because it doesn't take into account frequency, idle state, throttling, core type etc so gives a very inaccurate perspective of how much work the process is doing

If you insist on using CPU utilization, you can do something like this to get a utilization every 1ms:
```
DROP TABLE IF EXISTS win;
CREATE VIRTUAL TABLE win USING window;
UPDATE win SET window_start=TRACE_START(), window_dur=TRACE_DUR(), quantum=1e6;

CREATE OR REPLACE PERFETTO VIEW system_server_sched AS
SELECT ts, dur, utid, sched.id AS sched_id
FROM sched
JOIN thread USING (utid)
JOIN process USING (upid)
WHERE process.name = 'system_server';

DROP TABLE IF EXISTS sys_server_util;
CREATE VIRTUAL TABLE sys_server_util USING SPAN_LEFT_JOIN(win, system_server_sched PARTITIONED utid);

SELECT SUM(IIF(sched_id IS NOT NULL, dur, 0)) / 1e6 AS utilization, quantum_ts AS millisecond_since_start
FROM sys_server_util
GROUP BY 2;
```

**Comment by wjj1928** [comment]
Thanks, Is this sql command runnable in sqlite3? when I paste it in sqlite3 and run, report below error:

Runtime error: no such module: window

**Comment by LalitMaganti** [comment]
No. This is a [PerfettoSQL query](https://perfetto.dev/docs/analysis/perfetto-sql-syntax) which can only be executed by the [trace processor](https://perfetto.dev/docs/analysis/trace-processor).

**Comment by wjj1928** [comment]
Try trace_process with below command:

.\trace_processor_shell.exe -q .\sql.txt .\boottrace.perfetto-trace                              [638.424] oto_trace_reader.cc:254 It is strongly recommended to have flush_period_ms set when write_into_file is turned on. This trace will be loaded fully into memory before sorting which increases the likelihood of OOMs.
[640.325] processor_shell.cc:1627 Trace loaded: 79.69 MB in 1.90s (41.9 MB/s)
Traceback (most recent call last):
  File "stdin" line 3 col 29
    UPDATE win SET window_start=TRACE_START(), window_dur=TRACE_DUR(), quantum=1e6
                                ^
no such function: TRACE_START

Is this the proper way? or need some special config file to capture trace?

**Comment by LalitMaganti** [comment]
Sorry I was prototyping this query in the UI: I was missing the line:
```
INCLUDE PERFETTO MODULE common.timestamps;
```
at the start of the query.
