### ISSUE TITLE
How to show "trace_tracing_mark_write" function in perfetto

### ISSUE THREAD

**Issue by HelenXR** [google/perfetto#67]
Grabbing with systrace trace.html File, you can see trace_tracing_mark_write defines the string, while Perfetto can only see "running". How to see trace_tracing_mark_write define string(e.g.trace_tracing_mark_write('E', current, name, 0)) in Perfetto?

**Comment by chromy** [comment]
Hi @HelenXR! I'm not sure exactly what you had in mind. Could you add:

1) the list of commands you run
2) what you saw
3) what you expected to see

That will really help me fix this for you.
Cheers!
Hector

**Comment by HelenXR** [comment]
If I use the Android SDK“ monitor.exe "Grab systrace, and I can see the name of the kernel run function(like,complete_commit), as shown in the following figure
![image](https://user-images.githubusercontent.com/12227445/98065174-f0425380-1e8e-11eb-946a-63fa4df61b95.png)

Use the command to grab Perfetto trace, and you cannot see the name of the function executed
![image](https://user-images.githubusercontent.com/12227445/98065239-27186980-1e8f-11eb-9366-c68acdcfc7df.png)

adb push config.txt /data/local/tmp/trace_ config.txt
adb shell 'cat /data/local/tmp/trace_ config.txt | perfetto --txt -c - -o /data/misc/perfetto-traces/trace'
trace_ config.txt like below:
duration_ ms: 5000
buffers: {
size_ kb: 89600
fill_ policy: DISCARD

}

buffers: {

size_ kb: 89600

fill_ policy: DISCARD

}

data_ sources: {

config {

name: " linux.ftrace "

ftrace_ config {

ftrace_ events: "sched/sched_ switch"

ftrace_ events: "power/suspend_ resume"

ftrace_ events: "sched/sched_ switch"

ftrace_ events: "sched/sched_ wakeup"

ftrace_ events: "sched/sched_ blocked_ reason"

ftrace_ events: "sched/sched_ cpu_ hotplug"

ftrace_ events: "sched/sched_ waking"

ftrace_ events: "sched/sched_ wakeup_ new"

ftrace_ events: "sched/sched_ process_ exec"

ftrace_ events: "sched/sched_ process_ exit"

ftrace_ events: "sched/sched_ process_ fork"

ftrace_ events: "sched/sched_ process_ free"

ftrace_ events: "sched/sched_ process_ hang"

ftrace_ events: "sched/sched_ process_ wait"

ftrace_ events: "ftrace/print"

ftrace_ events: "workqueue/workqueue_ queue_ work"

ftrace_ events: "workqueue/workqueue_ execute_ start"

ftrace_ events: "workqueue/workqueue_ execute_ end"

ftrace_ events: "workqueue/workqueue_ activate_ work"

ftrace_ events: "mdss/tracing_ mark_ write"

ftrace_ events: "mdss/mdp_ cmd_ pingpong_ done"

ftrace_ events: "mdss/mdp_ compare_ BW "

ftrace_ events: "mdss/mdp_ perf_ set_ panic_ luts"

ftrace_ events: "mdss/mdp_ sspp_ set"

ftrace_ events: "mdss/mdp_ cmd_ readptr_ done"

ftrace_ events: "sde/tracing_ mark_ write"

ftrace_ events: "task/task_ newtask"

ftrace_ events: "task/task_ rename"

ftrace_ events: "task/task_ newtask"

atrace_ categories: "gfx"

atrace_ categories: "view"

atrace_ categories: "webview"

atrace_ categories: "camera"

atrace_ categories: "dalvik"

atrace_ categories: "power"

}

}

}

data_ sources: {

config {

name: " linux.process_ stats"

}

}

**Comment by HelenXR** [comment]
help~

**Comment by LalitMaganti** [comment]
Could you share the trace you captured where you are seeing this behaviour? tracing_mark_write events should be imported correctly if you're using Perfetto to collect traces.

**Comment by HelenXR** [comment]
thanks for  your replay
trace file upload:https://github.com/HelenXR/Documents/blob/master/picture/trace

**Comment by LalitMaganti** [comment]
Sorry for not responding - was OOO for the last week or so.

So interestingly, the data is missing at the trace level which is not what I was expecting. Can you provide the systrace file (and the command you used to collect the systrace - monitor.exe might print this out somewhere) where you see the events correctly?

**Comment by HelenXR** [comment]
emmmm.
Today, I use the same configuration and command as Perfetto to grab the trace file again. Open it with Perfetto UI. I can see the function. Thank you for your help

**Comment by S16201512** [comment]
> emmmm， 今天又用和Perfetto一样的配置和命令抓取trace文件，用Perfetto UI打开，可以看到功能了，谢谢帮助

Hi, how do you solve this problem?
I got runnning in UI-perfetto,too.
