### ISSUE TITLE
"CPU by Thread" view does not include  information (eg. thread_state etc.) associated with CPU0 

### ISSUE THREAD

**Issue by lileyang2000** [google/perfetto#670]
We found that the wall duration of a thread under Running state within a selected area from the  "Thread States " view in perfetto UI is not equal to that from the "CPU by Thread" view of the same selected area (with all the cpus check box checked ) as expected. And we think the reason is that the   "CPU by Thread" view does not include the information associated with CPU0 after we did a  comparision test using the following sql query  quoted from external/perfetto/ui/src/controller/aggregation/cpu_aggregation_controller.ts to  manually create "CPU by Thread" view
 
SELECT process.name as process_name, pid, thread.name as thread_name,
        tid, sum(dur) AS total_dur,
         sum(dur)/count(1) as avg_dur,
         count(1) as occurrences
         FROM process
         JOIN thread USING(upid)
         JOIN thread_state USING(utid)
         WHERE cpu IN (${selectedCpus})  
AND state = "Running" AND tid=3598
         AND thread_state.ts + thread_state.dur > 49480626338 AND thread_state.ts < 51576887005
The query result is that
     if we use (0, 1,2,3,4,5,6,7) for (${selectedCpus}  the wall duration value of tid 3598 from above manually created   "CPU by Thread" view equal to that from "Thread States " view  of Perfetto UI.
    if we skip cpu0 using (1,2,3,4,5,6,7) instead for (${selectedCpus}, the wall duration value of tid 3598 from above manually created   "CPU by Thread" view  is not equal to that from "Thread States " view   from Perfetto UI while equal to the value from  "CPU by Thread" view of Perfetto UI

And also if we only check the cpu0 box, the  "CPU by Thread" view would not even show on the perfetto UI which is not the case for other cpus.

**Comment by stevegolton** [comment]
You're totally right, thanks for pointing this out!

This is due to a number being used in a boolean expression and 0 is falsy. I've submitted a [patch](https://android-review.googlesource.com/c/platform/external/perfetto/+/2875340), and I've found an [eslint rule](https://typescript-eslint.io/rules/strict-boolean-expressions/) which I'll introduce in another patch to prohibit this practice in the future.
