### ISSUE TITLE
convert android command line parameters to config file

### ISSUE THREAD

**Issue by wjj1928** [google/perfetto#671]
Below android command line works fine. what I want is use the same parameter to capture bootup logs.

```
perfetto -o /data/misc/perfetto-traces/trace_file.perfetto-trace -t 20s \
sched freq idle am wm gfx view binder_driver hal dalvik camera input res memory
```

I need use a config file for bootup logs (/data/misc/perfetto-configs/boottrace.pbtxt), so wish how to convert it to config file.

**Comment by LalitMaganti** [comment]
The code to do the conversion can be found at https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/perfetto_cmd/config.cc but TLDR:
* `-t` maps to `duration_ms` in the config
* all of the atrace categories map to the `atrace_categories` section of the `linux.ftrace` datasource

see the "full trace config" section of https://perfetto.dev/docs/quickstart/android-tracing#recording-a-trace-through-the-cmdline for information on this.

**Comment by primiano** [comment]
In general the best way to solve this problem is:

1. Capture a trace via the cmdline (`-t 20s yada yada')
2. Open the trace with the UI and look at the 'Info and stats page'
3. Copy the full text config that is reported there. That is the translation that the code lalit linked does.
4. profit

**Comment by wjj1928** [comment]
Wow, that smart way! one question I have Trace.beginSection("MySection") in java code, but with that config, I still not see "MySection" keyword in trace, any other config should I add for this?

**Comment by LalitMaganti** [comment]
> I still not see "MySection" keyword in trace, any other config should I add for this?

You are likely not including your app's package in `atrace_apps` section of the config.

**Comment by primiano** [comment]
-a 'app name', which translates into atrace_apps: "app name" in the ftrace section of the config.
Example:
```
data_sources {
  config {
    name: "linux.ftrace"
    target_buffer: 0
    trace_duration_ms: 0
    tracing_session_id: 0
    enable_extra_guardrails: false
    ftrace_config {
      ftrace_events: "sched/sched_switch"
      ftrace_events: "power/suspend_resume"
      ...
      atrace_apps: "lmkd"   # !!!!!!!!!!!!!!!!! THIS
    }
```
