### ISSUE TITLE
About the bug in base_slice_track in Perfetto UI

### ISSUE THREAD

**Issue by LiangliangSui** [google/perfetto#673]
Hi @stevegolton @chromy ,

I found a problem in `base_slice_track.ts` and a place that can be optimized.

1.When I move left and right in the trace, some slices with extremely small width will appear on the left edge. These slices should not be displayed (because they are outside the visibleWindowTime range).
![image](https://github.com/google/perfetto/assets/116876207/46d04aee-3bea-4907-94d5-55b2f5186d0a)

The reason why it is displayed is that the `filterVisibleSlices` function filters out slices that are not within the range of visibleWindowTime.

The results queried through the SQL query engine are sorted according to depth and ts. The results of the elicitation query may be as follows (assuming that the start ts of visibleWindowTime is 10 and the end ts is 90)
&emsp;&emsp;slice(start=4, dur=3, depth=0),
&emsp;&emsp;slice(start=6, dur=3, depth=0),
&emsp;&emsp;slice(start=9, dur=6, depth=0),
&emsp;&emsp;slice(start=11, dur=7, depth=0),
&emsp;&emsp;slice(start=2, dur=3, depth=1),
&emsp;&emsp;slice(start=3, dur=3, depth=1),
&emsp;&emsp;slice(start=7, dur=6, depth=1),

After filtering through `filterVisibleSlices`, get the following slices
&emsp;&emsp;slice(start=9, dur=6, depth=0),
&emsp;&emsp;slice(start=11, dur=7, depth=0),
&emsp;&emsp;**slice(start=2, dur=3, depth=1),**
&emsp;&emsp;**slice(start=3, dur=3, depth=1),**
&emsp;&emsp;slice(start=7, dur=6, depth=1),

Some are filtered out in visibleWindowTime, such as **slice(start=2, dur=3, depth=1), slice(start=3, dur=3, depth=1)**, which will result in wrong UI display.

I tried to fix this problem through [2877537](https://android-review.googlesource.com/c/platform/external/perfetto/+/2877537), PTAL, thanks!

2.I think that in the `getVisibleSlicesInternal` function, incompleteSlices can also be filtered. We only care about the incompleteSlices where `slice.startNsQ <= visibleWindowTime.end`

                [ ---------visibleWindowTime--------- ]

                        [---------incomplete slice1----------

        [---------incomplete slice2-----------

                                                            [--------incomplete slice3-----------

As above, we should only care about incomplete slice1 and incomplete slice2, not incomplete slice3.

I optimized this problem in the change [2877540](https://android-review.googlesource.com/c/platform/external/perfetto/+/2877540), PTAL, thanks!

**Comment by stevegolton** [comment]
Hey @LiangliangSui, thanks so much for the detailed description and your contributions. Closing this issue for now.
