### ISSUE TITLE
sched_wakeup & sched_waking events are missing in lastet UI after loading from JSON result(converted from origin trace_file.perfetto-trace)

### ISSUE THREAD

**Issue by c6supper** [google/perfetto#676]
sched_wakeup & sched_waking events are missing in lastet UI after loading from JSON result(converted from origin trace_file.perfetto-trace).  I checked the json file, these two events are actually there , in the "systemTraceEvents" 's pair
![image](https://github.com/google/perfetto/assets/5347835/ca76f65c-1cea-4114-b228-923624cbaae9)
![image](https://github.com/google/perfetto/assets/5347835/7ad12ae3-91a2-4153-a453-8cf7fb94e356)
![image](https://github.com/google/perfetto/assets/5347835/8ec5c4ff-f253-48f4-9fac-cca2cd3190e1)

**Comment by LalitMaganti** [comment]
Just tested a converted JSON trace and it loaded totally fine in the UI, to the extent that it has always done so.

If you're expecting JSON traces to appear in the "ftrace events" section, that's never been supported and we have no plans to add support for that either given it's complexity for adding that.
