### ISSUE TITLE
How to collect track event data of a specified process？

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#678]
Currently, the following configuration file will be used to collect data from **all processes**.

```
data_sources: {
    config {
        name: "track_event"
    }
}
```
How to **only collect data of a specified process** (via pid or proc name) without collecting data from other processes？

Thanks~

**Comment by LalitMaganti** [comment]
You can use the [producer_name_filter](https://source.corp.google.com/piper///depot/google3/third_party/perfetto/protos/perfetto/config/trace_config.proto;l=88?q=producer_name_filter) option for this.
