### ISSUE TITLE
cpu freq captured time not the same between golden and silver core

### ISSUE THREAD

**Issue by wjj1928** [google/perfetto#679]
I try to capture a android 13 bootup trace. and run below query to get cpu freq data.

`select ts, t.name, cpu, value from counter as c left join cpu_counter_track as t on c.track_id = t.id where t.name = 'cpuidle' or t.name = 'cpufreq'`

I found golden core and silver core captured data not match.
e.g. CPU 0 max ts is 82.600177207 but cpu 4 max ts is 88.280182101

Is it a bug or need add some config to get the sample periodically?

**Comment by LalitMaganti** [comment]
This is working as intended. CPU frequency is an ftrace event so is a "push" event, that is, all CPU frequency changes are perfectly captured without the need for polling. This means that CPU frequency changes across cores will generally not match as the frequency changes will happen at different times for different cores.
