### ISSUE TITLE
Perfetto v40.0's Jump link invalid

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#680]
Perfetto v40.0 is deployed locally. When accessing the UI and clicking the detailed information of released thread states, it cannot jump to the corresponding thread or state. No response from these links.

![image](https://github.com/google/perfetto/assets/31888567/dc2e4aff-5183-489f-8f1c-7f30fdd08c4a)
![image](https://github.com/google/perfetto/assets/31888567/4bf0ff72-0d2b-44e2-b3d3-5d8f380aa8c1)

What is the reason and how to solve it? I would be grateful if you could reply.

**Comment by stevegolton** [comment]
Hi @duokuiwang, I can't seem to repo locally. Which version are you running exactly, and can you send a representative trace?

**Comment by duokuiwang** [comment]
> Hi @duokuiwang, I can't seem to repo locally. Which version are you running exactly, and can you send a representative trace?

Version: tag: v40.0, the displayed information of the `git log` command is as shown in the figure below:
![image](https://github.com/google/perfetto/assets/31888567/1de3cd88-05a0-4bbe-966e-66e76cdb9b69)

trace is [example.zip](https://github.com/google/perfetto/files/13861451/example.zip), you can view these two example processes:
![image](https://github.com/google/perfetto/assets/31888567/62688a70-0d82-420d-a264-42195ce47d39)

**Comment by stevegolton** [comment]
Ah OK I see the issue.

This is fixed in 010b702bcc463b893b9ceb57e1501bab8f6271b4 (see https://android-review.googlesource.com/c/platform/external/perfetto/+/2859128).

Either grab the tip of main, or otherwise we should be doing another release this week.
