### ISSUE TITLE
Using ftrace counters significantly slows down UI in Safari 17.1

### ISSUE THREAD

**Issue by niklaut** [google/perfetto#681]
I am creating a synthetic trace from a log via Cortex-M ITM output to debug DMA performance on STM32H7.
Here is [an example file](https://github.com/google/perfetto/files/13891357/orbetto.perf.gz) with counters for understanding how much each DMA channel has transferred. Each time a DMA transfer stops, the counters get incremented via a ftrace print message.

If I have the "DMA Channels 100000" process slice open with all the counter, the UI stutters to a halt. If I close the process slice, the UI runs smoothly again. I can pin every DMA channel print and everything is super smooth, but if I pin even just a single counter, everything crawls to a halt.

![](https://github.com/google/perfetto/assets/121870655/0a2c798b-ea4c-4100-970f-0f145cee6dd0)

The memory usage counters (eg. `mem.rss.*`) in the Android example also run smoothly, but they aren't prints, they are memory events. Am I using counters wrong?  I'm using the standard protobuf C++ libary to generate these events like so:

```cpp
auto *event = ftrace->add_event();
event->set_timestamp(ns);
event->set_pid(did);
auto *print = event->mutable_print();
char buffer[100];
snprintf(buffer, 100, "C|100000|DMA%u CH%u Transfer|%u", instance, channel, transfer_count);
print->set_buf(buffer);
```

**Comment by stevegolton** [comment]
Hi @niklaut, this seems like it might be a UI issue, but I can't seem to repro (Chrome, MacOS). What platform are you on, and which version of Perfetto are you using?

Cool use case BTW!

**Comment by niklaut** [comment]
Huh, interesting. But it works absolutely fine on Chrome Version 120.0.6099.216 (Official Build) (arm64), so I'll use that for now, thanks!

I'm on macOS 13.6.1 (22G313), Safari v17.1 (18616.2.9.11.10, 18616) and Perfetto [v39.0-ce5ca](https://android.googlesource.com/platform/external/perfetto/+/ce5cae18bd9a71f9948a6c33315a4cbd2df4c44b/ui). No difference if I switch to Perfetto Canary [v40.0-bf17f](https://android.googlesource.com/platform/external/perfetto/+/bf17fa38d78f9d0f1265859c4a5ca1c1fd23d71d/ui).

**Comment by stevegolton** [comment]
Glad you found a solution - unfortunately support for other browsers is a relatively low priority.

Oddly, I can't seem to repro on safari either: MacOS: 14.2.1, Safari: Version 17.2.1 (19617.1.17.11.12) - seems like we're both on arm64, different macos version maybe? 🤷 

I'll probably close this as I don't think we'll get round to it any time soon, sorry!

**Comment by niklaut** [comment]
It also works fine with Safari Technology Preview Release 186 (Safari 17.4, WebKit 18618.1.10.1.1) on my macOS 13.6.1. So it's definitely an issue with Safari 17.1 (perhaps also lower) and not related to the OS. Thanks!
Next time I'll test the browser directly, not sure why that didn't come to mind… 🤦

**Comment by stevegolton** [comment]
No worries, we should probably make it more obvious in the docs that we mainly test the UI against Chrome.
