### ISSUE TITLE
Interpreting Perfetto trace visualization

### ISSUE THREAD

**Issue by lucaslingle** [google/perfetto#684]
When collecting a trace using the [Jax](https://github.com/google/jax) profiler, the Perfetto UI shows an expanded view and a compact view. 
For example, in the attached screenshot, I have expanded the view for ```device:TPU:7``` only. 

Notably, the compact view looks very different, and appears to show a 1-second-long period of inactivity on all the TPUs between 00:00:01 and 00:00:02, whereas the expanded view does not. 

What does this compact view in Perfetto purport to show? Thanks for any insights you can provide. 

<img width="1140" alt="Screen Shot 2024-01-08 at 7 45 32 PM" src="https://github.com/google/jax/assets/10287371/da8cb5bf-8cd4-41cd-9faf-7b9bfec9c4ab">

**Comment by stevegolton** [comment]
Hey @lucaslingle 

It should represent a histogram of the density of slices from all tracks within the category, but I agree it looks like this isn't working as expected. This may well be a bug.

I'll look into it and get back to you.

**Comment by chromy** [comment]
(tracked internally at b/320660297)

**Comment by LalitMaganti** [comment]
This has been fixed.
