### ISSUE TITLE
Even if the id values in the flow event do not match, they are connected by a line.

### ISSUE THREAD

**Issue by jonghwan-choi-wdc** [google/perfetto#686]
Hi

While using flow event, I discovered one strange thing.

Even if the id values in the flow event do not match, they are connected by a line.
Please let me know if I misunderstood anything.
{
  "traceEvents": [
    {
      "cat": "ipc",
      "pid": 15903,
      "tid": 15904,
      "ts": 0,
      "ph": "X",
      "name": "SenderB",
      "args":{},
      "dur": 10
    },
    { 
      "cat": "ipc",
      "pid": 15903,
      "tid": 15904,
      "ts": 1,
      "ph": "s",
      "name": "IPC",
      "args":{},
      "id":"8780d404"
    },

    { 
      "cat": "ipc",
      "pid": 15875,
      "tid": 15895,
      "ts": 1001,
      "ph": "f",
      "name": "IPC",
      "args": {},
      "id":"4780d404"
    },
    { 
      "cat": "ipc",
      "pid": 15875,
      "tid": 15895,
      "ts": 1001,
      "ph": "X",
      "name": "Blergh",
      "args": {},
      "dur": 100
    }
  ]
}

![Screenshot 2024-01-19 at 1 39 19 PM](https://github.com/google/perfetto/assets/132034974/866f5f21-15ba-4972-b854-f66b367ae153)

Even if the ID values of flow events are different, they are connected by lines.
SenderB - "id":"8780d404"   vs Blergh -"id":"4780d404"

Is this behavior by design?
In my opinion, different id values should not be connected by a line.

thank you.!

**Comment by LalitMaganti** [comment]
Hi thanks for the report!

I'm currently travelling but will take a look at this when I get back to normal (likely in a week or so).

**Comment by LalitMaganti** [comment]
Looked into this: this is actually WAI according to the JSON tracing format specification [1]. ids are completely ignored when handling flows.

The Perfetto protobuf [2] tracing format does not have the limitations in the Chrome format and is anyway recommended as the JSON format is considered legacy and only supported by Perfetto in best-effort terms.

[1] https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.4qqub5rv9ybk
[2] https://perfetto.dev/docs/reference/synthetic-track-event#flows
