### ISSUE TITLE
about new ftrace event

### ISSUE THREAD

**Issue by hojihodi** [google/perfetto#688]
Hello, we are getting a lot of help in development using perfetto.
The question is about new ftrace event.

1) 
Even though we did not add a new ftrace event information in the code base as below,
it is displayed well with the structure variable in perfetto ui. Is the guide for other use cases?
- https://perfetto.dev/docs/contributing/common-tasks#add-a-new-ftrace-event

2)
Conversely, if i add a new ftrace event according to the guide, the following error occurs and it is not visible in perfetto ui
I would like to ask what to look at about the error
- ftrace_bundle_tokenizer_errors

I've really filled out all the new event information according to the guide, but I don't know what code to look at anymore.
Based on the perfetto code, it seems that cpu information or timestamp information are missing.

**Comment by hojihodi** [comment]
I don't think I understand what i needs to be modified yet ( for new ftrace event )
Do I need to update the perfetto ui code to add a new event and see it in ui?
( To be exact, it's about the trace processor ? )

**Comment by LalitMaganti** [comment]
The instructions at https://perfetto.dev/docs/contributing/common-tasks#add-a-new-ftrace-event explain exactly what you need to do. It's not just modifying trace processor, you also need to change the collection code so that we can generate the real proto events instead of generic events.
