### ISSUE TITLE
TimeLine  error 

### ISSUE THREAD

**Issue by louie-wh** [google/perfetto#689]
`buffers: {
    size_kb: 63488
    fill_policy: RING_BUFFER
}
buffers: {
    size_kb: 8192
    fill_policy: RING_BUFFER
}
data_sources: {
    config {
        name: "android.packages_list"
        target_buffer: 1
    }
}
data_sources: {
    config {
        name: "android.gpu.memory"
    }
}
data_sources: {
    config {
        name: "linux.process_stats"
        target_buffer: 1
        process_stats_config {
            scan_all_processes_on_start: true
            proc_stats_poll_ms: 1000
        }
    }
}
data_sources: {
    config {
        name: "android.surfaceflinger.frametimeline"
    }
}
data_sources: {
    config {
        name: "android.game_interventions"
    }
}
data_sources: {
    config {
        name: "android.packages_list"
    }
}
data_sources: {
    config {
        name: "linux.sys_stats"
        sys_stats_config {
            meminfo_period_ms: 1000
            vmstat_period_ms: 1000
            stat_period_ms: 1000
            stat_counters: STAT_CPU_TIMES
            stat_counters: STAT_FORK_COUNT
        }
    }
}
data_sources: {
    config {
        name: "android.heapprofd"
        target_buffer: 0
        heapprofd_config {
            sampling_interval_bytes: 4096
            #process_cmdline: "tech.autra.auto"
            #continuous_dump_config {
            #    dump_phase_ms: 1000
            #    dump_interval_ms: 10000
            #}
            shmem_size_bytes: 8388608
            block_client: true
        }
    }
}
data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            #buffer_size_kb: 16384
            #drain_period_ms: 150
            ftrace_events: "binder/*"
            ftrace_events: "sched/sched_switch"
            ftrace_events: "sched/sched_wakeup"
            ftrace_events: "sched/sched_wakeup_new"
            ftrace_events: "sched/sched_waking"
            ftrace_events: "power/suspend_resume"
            ftrace_events: "power/cpu_frequency"
            ftrace_events: "power/cpu_idle"
            ftrace_events: "power/gpu_frequency"
            ftrace_events: "gpu_mem/gpu_mem_total"
            ftrace_events: "power/gpu_work_period"
            #ftrace_events: "raw_syscalls/sys_enter"
            #ftrace_events: "raw_syscalls/sys_exit"
            ftrace_events: "mm_event/mm_event_record"
            ftrace_events: "kmem/rss_stat"
            ftrace_events: "ion/ion_stat"
            ftrace_events: "dmabuf_heap/dma_heap_stat"
            ftrace_events: "kmem/ion_heap_grow"
            ftrace_events: "kmem/ion_heap_shrink"
            ftrace_events: "sched/sched_process_exit"
            ftrace_events: "sched/sched_process_free"
            ftrace_events: "task/task_newtask"
            ftrace_events: "task/task_rename"
            ftrace_events: "lowmemorykiller/lowmemory_kill"
            ftrace_events: "oom/oom_score_adj_update"
            ftrace_events: "ftrace/print"

            atrace_categories: "sync"
            atrace_categories: "am"
            #atrace_categories: "adb"
            #atrace_categories: "aidl"
            #atrace_categories: "dalvik"
            #atrace_categories: "audio"
            #atrace_categories: "binder_lock"
            #atrace_categories: "binder_driver"
            #atrace_categories: "bionic"
            #atrace_categories: "camera"
            #atrace_categories: "database"
            atrace_categories: "gfx"
            #atrace_categories: "hal"
            atrace_categories: "input"
            #atrace_categories: "network"
            #atrace_categories: "nnapi"
            #atrace_categories: "pm"
            #atrace_categories: "power"
            #atrace_categories: "rs"
            #atrace_categories: "res"
            #atrace_categories: "rro"
            #atrace_categories: "sm"
            #atrace_categories: "ss"
            #atrace_categories: "vibrator"
            atrace_categories: "video"
            atrace_categories: "view"
            atrace_categories: "webview"
            atrace_categories: "wm"
            atrace_apps: "*"
        }
    }
}
duration_ms: 15000
write_into_file: true
file_write_period_ms: 2500
max_file_size_bytes: 500000000
flush_period_ms: 10000
incremental_state_config {
    clear_period_ms: 5000
}`

this is my perfeto config 

using cmd to run : ~/perfetto/record_android_trace -c auto.pbtx 

and run Success
Pulling into /home/huan.wang/traces/2024-01-24_15-22-4c116b.pftrace
pull /data/misc/perfetto-traces/2024-01-24_15-22-4c116b.pftrace /home/huan.wang/traces/2024-01-24_15-22-4c116b.pftrace
/data/misc/perfetto-traces/2024-01-24_15-22-4c116b.pftrace: 1 file pulled, 0 skipped. 40.5 MB/s (46403079 bytes in 1.093s)
shell rm -f /data/misc/perfetto-traces/2024-01-24_15-22-4c116b.pftrace

Opening the trace (/home/huan.wang/traces/2024-01-24_15-22-4c116b.pftrace) in the browser

but  perfetto timeline likethis:
![image](https://github.com/google/perfetto/assets/142218598/fe6a0224-d380-4087-a4e2-da088b3d1ae8)

[2024-01-24_15-22-4c116b.zip](https://github.com/google/perfetto/files/14034917/2024-01-24_15-22-4c116b.zip)

**Comment by LalitMaganti** [comment]
This is working as intended and comes from the fact that we automatically zoom into the region of the trace containing ftrace data (if it exists) as that's the part that most people care about. 

If you zoom out, then you'll see the rest of the trace contains counters corresponding to the "linux.process_stats" data source. Because you are putting this source into a different buffer, it will naturally cover a different (larger) time range to ftrace.

**Comment by louie-wh** [comment]
The trace is different of normal  perfetto UI. 
and what means 18:42:58 ?  which time is  18:42:58  mean?
android sometime the trace timeline is  normal ,  sometime the trace is exception

**Comment by LalitMaganti** [comment]
> The trace is different of normal perfetto UI.

That might be because the config is different to your "normal" traces. I don't see anything wrong from our side. 

> what means 18:42:58 ? which time is 18:42:58 mean?

The time since the start of the trace. Looks like it's been 18ish hours since the trace started.

**Comment by louie-wh** [comment]
the trace only capture  60 second.   
android the same config sometimes work good , sometime  work wrong. 
I doubt the buffer config lead to this.  
can you send the issue to some people who response  buffer config.

**Comment by LalitMaganti** [comment]
@stevegolton can you ptal at this?

**Comment by chromy** [comment]
![image](https://github.com/google/perfetto/assets/351085/ba1eb9d5-8ab2-436c-b495-bd77ed408b90)

There is a single expected frame timeline event about 19h before every other event in the trace.
Because of that the trace looks like:

[1 event].....................19 hours of nothing.......................[the rest of the trace]

We do not know why this occurs in your set up, it is not something we have encountered to my knowledge.

**Comment by rollysys** [comment]
Maybe there is time sync mechanism in your system, for example ptp
Which may cause your timestamp jump forward or backward


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Hector Dearman ***@***.***>
发送时间: Friday, January 26, 2024 2:17:42 AM
收件人: google/perfetto ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [google/perfetto] TimeLine error (Issue #689)


Closed #689<https://github.com/google/perfetto/issues/689> as completed.

―

**Comment by dfriederich** [comment]
Just for reference, I think the cause for this issue got fixed in aosp in surface flinger commit "SF: Do not trace FrameTimeline before start"

https://cs.android.com/android/_/android/platform/frameworks/native/+/43a68c3fd6da28753a612965b4072ef93f9f888e

but it will take a bit until all our devices include the fix, so we will see early surface flinger events for a while.
