### ISSUE TITLE
No tid and pid in android logs

### ISSUE THREAD

**Issue by PlasticUncle** [google/perfetto#69]
In "android logs" view, logs show as:
[time] [severty] [tag] [message]
I think pid and tid is necessary and logs should show as:
[time] [pid] [tid] [severty] [tag] [message]

Sometimes, some apps use 3rd SDK and some threads or process will finish after something done. It's troublesome to know who print the log without pid and tid

**Comment by chromy** [comment]
@PlasticUncle Thanks for the feature request!

**Comment by LalitMaganti** [comment]
I believe @octaviantu added support for this in the latest round of improvements in the UI so closing.
