### ISSUE TITLE
Perfetto UI building on Windows

### ISSUE THREAD

**Issue by ysyang-rtst** [google/perfetto#691]
Is there any reason why Perfetto UI doesn't support building on Windows?
I'm trying to build it on Windows without WSL, and I'm wondering if there are issues with certain libraries not being supported in the Windows environment.

**Comment by LalitMaganti** [comment]
I think it's just not a priority for us because none of us use windows. Things like the node binaries, all the file operations which is fine by the build script do not work on windows. 

This is absolutely not a priority for us, patches for fixing this welcome.

**Comment by primiano** [comment]
> Is there any reason why Perfetto UI doesn't support building on Windows?

As Lalit mentioned, nobody works on Windows, and that is going to be a burden to support, as things will break frequently.

I would not even take patches frankly.
Supporting this means having to roll windows executable for node.exe and npm.exe, which means every time we upgrade node, we have to go to the trouble of updating also the windows version.

So, sorry, this is one of the case where even if you contribute, I'm not willing to take the burden of uprev-ing node all the time.

Just use WSL2. I have a windows laptop and honestly works great.
