### ISSUE TITLE
Add min/max duration columns - Enhancement

### ISSUE THREAD

**Issue by jhbirdchoi** [google/perfetto#696]
https://github.com/google/perfetto/pull/695 -> Link

It is helpful to show the min/max  of some of the aggregation columns
    
It worked well.
![image](https://github.com/google/perfetto/assets/20182084/3406de7d-d407-4892-a001-e9cf319e1a77)

**Comment by LalitMaganti** [comment]
The pivot table supports min/max/count etc on any column you want.
