### ISSUE TITLE
After Loading Trace, no prompt 'Trace Processor native acceleration' dialog on ui.perfetto.dev. 

### ISSUE THREAD

**Issue by dhjoo98** [google/perfetto#697]
I'm following https://perfetto.dev/docs/visualization/large-traces to load large trace with native acceleration on a Macbook. 

Terminal prompt shows 'Trace loaded: 3239.81 MB in 82.43s (39.3 MB/s)', 
Then '[HTTP] Starting RPC server on localhost:9001'
But after '[HTTP] This server can be used by reloading https://ui.perfetto.dev and clicking on YES on the "Trace Processor native acceleration" dialog', 

this dialog does not show up once I visit ui.perfetto.dev on Safari.

**Comment by dhjoo98** [comment]
the same on a chromium-based browser as well.

**Comment by primiano** [comment]
Are you waiting that the trace load before showing the ui?
What happens if you curl https://127.0.0.1:9001 after the trace loads in trace processor?

It definitely works on my macbook.

**Comment by dhjoo98** [comment]
1) yeah I'm accessing ui.perfetto.dev after 'Trace loaded' prompt. 
2) curl localhost:9001 shows:

Perfetto Trace Processor RPC Server
This service can be used in two ways:
1. Open or reload https://ui.perfetto.dev/
It will automatically try to connect and use the server on localhost:9001 when
available. Click YES when prompted to use Trace Processor Native Acceleration
in the UI dialog.
See https://perfetto.dev/docs/visualization/large-traces for more.
2. Python API.
Example: perfetto.TraceProcessor(addr='localhost:9001')
See https://perfetto.dev/docs/analysis/trace-processor#python-api for more.
For questions:
https://perfetto.dev/docs/contributing/getting-started#community

But then, curl https://127.0.0.1:9001 shows 
curl: (35) OpenSSL/3.2.0: error:0A0000C6:SSL routines::packet length too long

**Comment by LalitMaganti** [comment]
`curl https://127.0.0.1:9001/` will not work since you the port is a plain HTTP port not a HTTPS one.

When you open ui.perfetto.dev.in, can you please Chrome devtools and see if an error is displayed there?

**Comment by dhjoo98** [comment]
> Are you waiting that the trace load before showing the ui? What happens if you curl https://127.0.0.1:9001 after the trace loads in trace processor?
> 
> It definitely works on my macbook.

I have been able to resolve this in a chronium-based brower(Naver Whale), but not in Safari. 
It seems like Primiano was correct in the sense that terminal prompt 'Traced Loaded' does not signify the actual completion of trace load. I waited 2~3 hours after load, then ui.perfetto correctly showed the option for native acceleration.
