### ISSUE TITLE
How to open the perfetto UI to last few us/ms based on the log

### ISSUE THREAD

**Issue by lavanyaeswarappa** [google/perfetto#699]
Hi, we are using perfetto trace.json to dum p our data and read the json file on UI. When we load the trace.json file on UI, the UI opens to the first timestamp of the log I believe. Is there a way to modify this to open towards the end of the visualization. Since most of our usecases are focused at the end of our logs, we want the UI to open at the end. Is there a way to customize this from trace.json file? 

The UI needs to automatically open at the end point as shown below. This would avoid the user to zoom in and scroll to the end

![image](https://github.com/google/perfetto/assets/24353986/a72b5f0b-1fb0-4d39-bc6b-1207de5e9379)

**Comment by LalitMaganti** [comment]
This is covered in our docs, please see https://perfetto.dev/docs/visualization/deep-linking-to-perfetto-ui#opening-the-trace-at-a-specific-event-or-time.

**Comment by lavanyaeswarappa** [comment]
Thanks Lalit, Is there a way to configure this on json file?

**Comment by LalitMaganti** [comment]
No there is not, nor is there such a plan on supporting that feature (note however changing this is sticky across traces, it's a global per-user setting).
