### ISSUE TITLE
Nagle's algorithm adds 40ms delay to trace_processor_shell queries on old Linux kernels

### ISSUE THREAD

**Issue by trishume** [google/perfetto#70]
Using the local `trace_processor_shell` binary on an old Linux distribution like CentOS 7 results in very slow loading since many queries are performed in serial and each takes ~40ms rather than <1ms. This is [the classic 40ms bug](https://vorner.github.io/2020/11/06/40-ms-bug.html) which affects older Linux kernels.

I've confirmed locally that setting the `TCP_NODELAY` socket option fixes this, although I did it in a hacky way for testing rather than putting it properly in the base socket abstraction.

I'm not sure which kernel version fixed the issue and if there's any Linux distributions supported by Perfetto that are affected by this. In order to build Perfetto on CentOS 7 I had to do some tinkering with the hermetic builds to create/find versions which didn't used GLIBC 2.18 which is too new for CentOS 7.

**Comment by primiano** [comment]
Thanks a lot fo the report.
Just to confirm does it go away just by adding TCP_NODELAY to the listening socket in trace_processor_shell?

**Comment by primiano** [comment]
@trishume  can you try  https://android-review.googlesource.com/c/platform/external/perfetto/+/1492639 and confirm it fixes for you?

**Comment by trishume** [comment]
Thanks! I haven't had a chance to test out your exact commit yet but that looks very similar to the working code I used so I suspect it does. I used `SOL_TCP` but a cursory internet search suggests `IPPROTO_TCP` does the same thing and is maybe the more correct one.
