### ISSUE TITLE
sync the trace.json with the absolute timestamps

### ISSUE THREAD

**Issue by lavanyaeswarappa** [google/perfetto#700]
The timestamps in the UI is displayed relative to the trace.json timestamp. Is it possible to provide the absolute timestamp that the UI needs to take from the json file.

**Comment by LalitMaganti** [comment]
The UI can be changed to work in absolute timestamps by opening the Command Palette (with Ctrl-Shift-P) (see [1]) and then choosing the "Set timestamp and duration format" to "Raw"

[1] ![image](https://github.com/google/perfetto/assets/679100/66df0349-4d5d-4a55-a57e-27b87b26ef48)

**Comment by lavanyaeswarappa** [comment]
Thanks Lalit, Is there a way to configure this on json file?

**Comment by LalitMaganti** [comment]
No there is not nor do we have any plans on supporting such a feature.
