### ISSUE TITLE
[BUG] The thread and process lost association

### ISSUE THREAD

**Issue by garretzou** [google/perfetto#701]
In the trace file generated using the following configuration,
```text
# Adds full process names and thread<>process relationships: 
data_sources: {
  config {
    name: "linux.process_stats"
  }
}
```
The threads were associated with processes initially, but lost the association later on. When using SQL to analyze per-process CPU time, threads belonging to a process were counted as independent processes, leading to erroneous results. This also caused poor visualizations in the UI. 

As shown in the figure below:

![Snipaste_2024-02-06_11-16-55](https://github.com/google/perfetto/assets/7679315/8c0f9efa-3d7b-4b9a-bec4-0fd9661bcbc6)

**Comment by LalitMaganti** [comment]
This is working as intended. The process stats poller simply dumps on the startup of the trace by default. The ftrace data source should be enabled for on-demand polling - when new PIDs are seen in ftrace they are passed to the process stats poller for capturing process associations.

Specifically, the: `task/task_newtask`, `task/task_rename` and `sched/sched_process_exit` ftrace events should be enabled to make sure there is accurate process tracking.
