### ISSUE TITLE
After the pin track fills up the page, you cannot use the mouse to scroll down.

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#703]
As shown in the title, when analyzing certain tracks, pin them to the top of the page. Then when the pin track fills up the page, you cannot use the mouse to scroll down to view unpinned track information.

How to solve this problem？

thanks.

**Comment by primiano** [comment]
That's WAI, as scrolling the pinned track list would create another scrolling container making the UX a nightmare.

The real solution is to have workspaces and APIs to hide/show/reorder tracks, so you can have a new (scrollable) workspace with only the tracks you care about.

@stevegolton

**Comment by stevegolton** [comment]
We prototyped a patch that allows tracks to scroll once the pinned panel gets too large. It'll be available on the autopush panel within the next hour or so.
