### ISSUE TITLE
Reorder traces 

### ISSUE THREAD

**Issue by lavanyaeswarappa** [google/perfetto#706]
Is there a way to reorder the visualization of Process based on requeirment?
For example I want process 'a' to be displayed on the top at the beginning. I sthere a way to configure this in trace.json?
Thanks

**Comment by stevegolton** [comment]
AFAIK there's no way to do this from within a trace. After a lot of experimenting we've concluded that traces should be entirely unopinionated about how they are represented in the UI.

We are planning to add a set of user configurable rules that can describe how to order processes, and also to allow everything to be reorderable within the UI, including process groups, but this would be per UI instance (stored in your local storage) so each user would need to configure this themselves. Does this work for your use case?

**Comment by lavanyaeswarappa** [comment]
Hi @stevegolton,

We could try this user configurable way. Could you please share the steps to do it?
