### ISSUE TITLE
Raw timestamp

### ISSUE THREAD

**Issue by lavanyaeswarappa** [google/perfetto#707]
Is there a way to set raw timestamp in Hex values? Right now when we set the command set timestamp raw it shows in ns I believe.

**Comment by stevegolton** [comment]
I assume you're using JSON as you mentioned this in your other issue. Unfortunately the original timestamps from the json file are converted to nanoseconds early on in the trace parsing process and the original value is is lost. AFAIK we have no plans to persist it through to the UI, and JSON support is best-effort anyway.

The purpose of the "raw" format is to show timestamps exactly as they are represented in the underlying SQL tables, which happens to be nanoseconds.

We could in theory add a hex representation of the nanosecond values, but I assume this is not what you're looking for, and it would be a very low priority for us anyway.

Hex timestamps are quite a niche use-case, mind if I ask what you're using it for?
