### ISSUE TITLE
The height of y axis is not significantly visible based on the value

### ISSUE THREAD

**Issue by lavanyaeswarappa** [google/perfetto#709]
Hi, 
Why is the value 1076.36 being so high still looking flat in the counter event representation? IS there a way we can specify the limit of y-axis? Cause visually the line looks completely flat but has a huge value change and we cant see that until we hover at that point. 

![image](https://github.com/google/perfetto/assets/24353986/4e3c75a3-54d2-470b-8b52-1b7700b9c480)

Thanks

**Comment by LalitMaganti** [comment]
We now have a bunch of options to expand counter tracks and also change the mode which should make any changes make obvious.
