### ISSUE TITLE
cannot build examples using "cmake --build build"

### ISSUE THREAD

**Issue by zxl5595** [google/perfetto#71]
I want to learn how to use the **Perfetto SDK by the examples**. 
However, when I run the "**cmake --build build**" in CMD, it comes a lot of error as the picture attached bellow. 
The first four errors are the same type error and I have serach through google I may cause by the **default constructor** (which is the new feature in C++11) in perfetto.cpp. 
At this point I don't know how can I solve this issue. Could someone help me?

Ps. I have using **cmake 3.18.4 and gcc 4.9.2** (download through Dev-Cpp 5.11), also tried **gcc10.1.0** (download through MSYS2). I use windows 10 system.

![p1](https://user-images.githubusercontent.com/43431494/99023444-9bde5880-259f-11eb-9ebd-edf75e9b3142.PNG)
![p2](https://user-images.githubusercontent.com/43431494/99023448-9da81c00-259f-11eb-8614-ff5016f6bf64.PNG)

**Comment by zxl5595** [comment]
sorry about the Chinese in the picture, this is the same error but in English:
![image](https://user-images.githubusercontent.com/43431494/99025201-4146fb80-25a3-11eb-85fd-21733dd3f358.png)

**Comment by skyostil** [comment]
It looks like cmake is trying to use the MSVC compiler instead of GCC. We don't currently support MSVC.

Could you try configuring your project again with the `-T` flag pointing to the GCC toolchain? (Sorry, I don't have a reference at hand of what the toolchain is called on Windows.)

**Comment by zxl5595** [comment]
I have tried to add "CC=C:\Program Files (x86)\Dev-Cpp\MinGW64\bin\gcc", and "CXX=C:\Program Files (x86)\Dev-Cpp\MinGW64\bin\g++" to the system variables. 
And then use "cmake --build build -T CC" to build, but it cannot work for the flag "-T". 
I have searched how to change the compiler for cmake, but didn't find a userful one.
Could you give me a little more hint? Or does this could not be used in windows?

**Comment by zxl5595** [comment]
Another issue is that when I run the system-wide example, the command "adb push build_android/example_system_wide ../system_wide_trace_cfg.pbtxt/data/local/tmp/" doesn't work. It has an error "adb push build_android/example_system_wide ../system_wide_trace_cfg.pbtxt/data/local/tmp/".

I use an rooted Android phone with Android 10, and tried to run "adb remount".
What could I do to solve this issue?
 
![image](https://user-images.githubusercontent.com/43431494/99366371-7b8e0100-28f3-11eb-9429-9c638c74ea0c.png)

**Comment by primiano** [comment]
Oh don't remount, that puts the phone in a weird state.
Just push to /data/local/tmp? There seems to be a missing space in your command, between pbtxt and /data/local

**Comment by zxl5595** [comment]
> Oh don't remount, that puts the phone in a weird state.
> Just push to /data/local/tmp? There seems to be a missing space in your command, between pbtxt and /data/local

Thank you for your replay.
I changed the command to "adb push build_android/example_system_wide  /data/local/tmp/', and the file "example_system_wide" is been successed pushed into the phone. However, I still have trouble to run the following adb shell command (attached as picture bellow) . 

Because there is no "system_wide_trace_cfg.pbtxt" in the phone, the cat command will rise an error. Also, if I run the command "./example_system_wide" separately, it will also rise an error "Android 5.0 and later only support position-independent executables (-fPIE)". How can I solve those errors? 

ps. I have tried on an Android 10 phone (rooted), and an Android 11 Google Pixel 4XL (not rooted), with Ubuntu system. They have the same error.
![image](https://user-images.githubusercontent.com/43431494/99481443-20144f80-2995-11eb-93c9-1823cf75d672.png)
![image](https://user-images.githubusercontent.com/43431494/99481530-4a660d00-2995-11eb-9ae3-223a33a6d2a6.png)

**Comment by zxl5595** [comment]
I have find solutions for those two errors. For the system-wide example: 
1) separately run the command (in file path perfetto/examples/sdk), they will push two files in the phone.
adb push build_android/example_system_wide data/local/tmp/
adb push system_wide_trace_cfg.pbtxt data/local/tmp/

2)add three lines in the perfettto/examples/sdk/CMakeList.txt (just after the line 9 "set(CMAKE_CXX_STANDARD_REQUIRED ON)"). They will solve the error of "-fPIE" :
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pie -fPIE -DPERFETTO_ENABLE_LEGACY_TRACE_EVENTS=1")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pie -fPIE -DPERFETTO_ENABLE_LEGACY_TRACE_EVENTS=1")
set(CMAKE_LDFLAGS "-pie -fPIE")

3) In addition, we also need to opeb adb shell, under path /data/local/tmp, open the permissions for the file. Or you will neet error "/system/bin/sh: ./example_system_wide: can't execute: Permission denied":
chmod 777 example_system_wide
chmod 777 system_wide_trace_cfg.pbtxt

**Comment by LalitMaganti** [comment]
Just to confirm: is the compilation working now with the changes in the previous comment? If so, can we close this bug? :)

**Comment by LalitMaganti** [comment]
Closing the bug - please reopen if you're still having the issue :)
