### ISSUE TITLE
The trace I added in the driver cannot be captured normally using perfetto app

### ISSUE THREAD

**Issue by DE-PARTURE** [google/perfetto#710]
I used the TRACE_EVENT macro in the driver code to try to add some trace logs. After I enabled these events through the file system, I used the `cat /sys/kernel/tracing/trace` command to obtain the trace logs. The following logs can be obtained normally.
```prolog
  irq/358-8030_io-1755 [000] ..... 128.982791: tracing_mark_write: B|1755|Nanosic_i2c_irq|0
  irq/358-8030_io-1755 [000] ..... 128.982792: tracing_mark_write: C|1755|work_buf|1
  irq/358-8030_io-1755 [000] ..... 128.982803: tracing_mark_write: C|1755|work_buf|0
  irq/358-8030_io-1755 [000] ..... 128.982805: tracing_mark_write: E|1755||0
```
But when I use perfetto app, I cannot see the trace log I added from the perfetto viewer. When I converted the product of perfetto app to .systrace, I found that the place where the above log should originally appear became like the following.
```prolog
  irq/362_8030_io-1764 (1764) [000] .... 415.238174: tracing_mark_write:|1764|Nanosic_i2c_irq
  irq/362_8030_io-1764 (1764) [000] .... 415.238176: tracing_mark_write:|1764|work_buf
  irq/362_8030_io-1764 (1764) [000] .... 415.238267: tracing_mark_write:|1764|work_buf
  irq/362_8030_io-1764 (1764) [000] .... 415.238269: tracing_mark_write:|1764|
```

**Comment by LalitMaganti** [comment]
Please provide the raw perfetto trace file for us to debug. This issue is very difficult to debug without the trace.
