### ISSUE TITLE
Deep linking with a string instead of ArrayBuffer

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#714]
I don't use binary Perfetto data.  All my data are json captures.  Is there a simpler way to just send a perfetto data chunk with a json string instead of trying to marshall an ArrayBuffer?  

I have a Swift app that has opened a request to ORIGIN = ui.perfetto.dev, and now wants to postMesage with the payload detailed in deep linking to Perfetto.  I'm not having any luck with serializing "buffer: Data" into an ArrayBuffer to then send to a WKWebView.  But I know I can encode a String easily and then send that over.

```
struct PerfettoFile : Codable {
        var bufferJson: String <- proposal to be able to send json
        //var buffer: Data <- trouble encoding ArrayBuffer to json
        var title: String
}

 struct Perfetto : Codable {
        var perfetto: PerfettoFile
  }

        let fileContent = try String(contentsOf: fileURL)
        let file = PerfettoFile(bufferJson: fileContent, title: fileURL.standardizedFileURL.absoluteString)

        //let fileContent = try Data(contentsOf: fileURL)
        // let file = PerfettoFile(buffer: fileContent, title: fileURL.standardizedFileURL.absoluteString)

        let perfetto = Perfetto(perfetto: file)
        
        let encoder = JSONEncoder()
        //encoder.outputFormatting = .prettyPrinted
        let data = try encoder.encode(perfetto)

        // This is to avoid JSON.stringify
        var json = String(data: data, encoding: .utf8)!
        
        json = json.replacingOccurrences(of: "\n", with: "\\\n")
        
        json = "window.postMessage(" + json
        json += ", \"" + ORIGIN + "\")"

        webView.evaluateJavaScript(json, completionHandler:nil)
        
```

**Comment by LalitMaganti** [comment]
Maybe I'm missing something but is there any reason why you cannot just use TextEncoder to convert the string to an ArrayBuffer on the Javascript side (e.g. https://stackoverflow.com/questions/6965107/converting-between-strings-and-arraybuffers)?

**Comment by alecazam** [comment]
Here's the data that I have serialized and trying to send to Perfetto.  I'm not loading any other JavaScrip, but might have some way to do so.    But this doesn't seem to load the file up.  I'm using a [Uint8] array here to supply the ArrayBuffer.   

webView.evaluateJavascript(
"window.postMessage({"perfetto":{"title":"squish.json","buffer":[123,34,116,114,97,99,101,69,118,101,110,116,115,34,58,91,123,34,112,105,100,34,58,52,...]}})")

**Comment by LalitMaganti** [comment]
Just to make sure this is not some weird problem with the iOS webview (e.g. not supporting postMessage properly), can you try the same Javascript you are executing on desktop Chrome?

**Comment by alecazam** [comment]
This tool is actually running all on macOS, but let me try that.  I could do a JSON.parse(), I'm assuming Perfetto wasts an object and not a string passed to postMessage.  But JSON.parse() complains about this which I assume is the array.  I did try Json.stringify(new ArrayBuffer()) and just got {} as output.  With more chars, I got {"0":123, "1":3, ...} as output. I thought ArrayBuffer wasn't truly serializable since it's not a stock Json type.  

Will test a few things in browser with ui.perfetto.dev as you suggested.  This is just way harder than it needs to be though.   A url param would have been more way simpler, but I get that CORS is painful. 

SyntaxError: JSON Parse error: Unexpected identifier "object"
 - parse ([native code])
 - global code (/:1:30)

**Comment by LalitMaganti** [comment]
> A url param would have been more way simpler,

Why this is not the case is very clearly spelled out in the docs - https://perfetto.dev/docs/visualization/deep-linking-to-perfetto-ui#why-can-39-t-i-just-pass-a-url-

Blame the state of the web, not us :)

**Comment by alecazam** [comment]
I realize that, and referenced it above on CORS.  I'm just trying to pull up files into Perfetto from a Swift list view.  The WKWebView hosts Perfetto, and I have the file read on the Swift side, and I just need to pass the JSON data to Perfetto to get it to load.  

With the JSON.parse, I get the object error.  Without the JSON.parse, I get the following.  So my JS skills must have gotten rusty over the years.   

Uncaught (in promise) Error: Failed assertion
    at assertTrue (frontend_bundle.js:4440:16)
    at TraceBufferStream.readChunk (frontend_bundle.js:428084:35)
    at TraceController.loadTrace (frontend_bundle.js:430132:48)
assertTrue @ frontend_bundle.js:4440
readChunk @ frontend_bundle.js:428084
loadTrace @ frontend_bundle.js:430132
Promise.catch (async)
run @ frontend_bundle.js:430007
invoke @ frontend_bundle.js:414078
(anonymous) @ frontend_bundle.js:414105
invoke @ frontend_bundle.js:414111
runControllers @ frontend_bundle.js:430871
setTimeout (async)
(anonymous) @ frontend_bundle.js:479880
(anonymous) @ frontend_bundle.js:5303
applyEdits @ frontend_bundle.js:5302
edit @ frontend_bundle.js:5288
dispatchMultiple @ frontend_bundle.js:479895
dispatch @ frontend_bundle.js:480005
openTrace @ frontend_bundle.js:442184
postMessageHandler @ frontend_bundle.js:442192
postMessage (async)
(anonymous) @ VM140:1

**Comment by LalitMaganti** [comment]
I copied and pasted our "example caller" part of our documentation into JSFiddle and it's successfully able to open a JSON trace no problem: https://jsfiddle.net/vrsofx1p/

**Comment by alecazam** [comment]
I finally got Perfetto to open the first JS payload send to it.  And I built the ArrayBuffer on the JS side.  But that's all Perfetto loads.  I can't send another file payload to it.   It continues to display only the first file that I send.    Your fiddle opens up the same file in a new window every time the button is pushed, so maybe if the target was set to open different traces in the same window, that would exhibit this same problem.

**Comment by alecazam** [comment]
This latching of state happens even in Chrome.  Is there a way to disable this, and have Pefetto respond each time a {"perfetto":...} payload is sent over.   I don't really want to have to reload the page due to the flash and loss of context for the user.  I just need it to reflect the current selected file.

**Comment by chromy** [comment]
Hey!

Do you set `keepApiOpen` on the version https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/ui/src/frontend/post_message_handler.ts;l=178?q=postMessage%20f:perfetto

You can see what Flutter devtools here: https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/performance/panes/timeline_events/perfetto/_perfetto_web.dart#L174

**Comment by alecazam** [comment]
That keepAPIOpen looks like exactly what I need, so thanks!   That wasn't in the deepLinking docs, so would help to detail that there.  Not quite sure where I set that (on my perfetto object?), but I'll dig through the sources you sent. 

Here's what I have so far.  I'll have a macOS build of this with my CI when I get a chance.  For now it's a small number of Swift files to build using Xcode.

https://github.com/alecazam/kram/blob/main/kram-profile/kram-profile/kram_profileApp.swift

**Comment by alecazam** [comment]
Worked like a charm!  App is all good now.  Will checkout the flutter setup more closely too.

**Comment by chromy** [comment]
Great! Glad it worked out. I will update the docs.
