### ISSUE TITLE
How to suppress the Perfetto sidebar when opening a file?

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#716]
The sidebar is open when there is no content loaded, and also every time that I load a new file from my tool, this re-opens.  I don't really need the "open trace file", since my app is opening the traces.   Also these popups don't work without more work on WKWebView to allow them.

If someone needs the Query/Viz/Metrics, then the hamburger menu can pop it back open.   I'm trying to look at profiles across all of clang, and it's a lot of trace files.  So having to constantly collapse that side-bar isn't ideal for the user.  

Seems like there are commands to suppress it, but these are only registered after a trace is loaded.  I want to post a "perfetto" object, and have the side-bar remain suppressed.  Eventually I'll even make my file list a popover, so it doesn't wasted profiling real-estate.

The idea here is to have a consistent timeline scale as you look across all files, sort the ones to the top that are the worst offenders, etc.

**Comment by chromy** [comment]
You can pass `hideSidebar=true` in the URL to suppress the sidebar entirely: https://ui.perfetto.dev/?hideSidebar=true This hides the sidebar forever (you can't bring it back) which is how the UI is used by some folks who embed it as a component (as done by Flutter devtools)

**Comment by alecazam** [comment]
Again, perfect!  Thanks for the responses.  The tool is looking much more usable now.
