### ISSUE TITLE
Question!. Does Perfetto UI also support  "displayTimeUnit": "us"?

### ISSUE THREAD

**Issue by jonghwan-choi-wdc** [google/perfetto#717]
Hi!
I have one question regarding timestamps.

[Trace Event Format ](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview)

If provided displayTimeUnit is a string that specifies in which unit timestamps should be displayed. This supports values of “ms” or “ns”. By default this is value is “ms”

According to the Trace Event Format specification, only "ms" and "ns" are supported.
Is it possible to use "us" like below?

 "displayTimeUnit": "us"?

thank you.!

**Comment by LalitMaganti** [comment]
No we don't support this. The context for why not is available at https://github.com/google/perfetto/issues/106
