### ISSUE TITLE
Setting to collapse the thread name column

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#719]
Just to free up more space, would be nice to be able to collapse the thread name view (keeping the pin).   Many Perfetto traces like these out of Clang's -ftime-trace have non-sensical thread names.   This would free up a lot of space for seeing more of the profile.     If not possible to hide, then to shink it to just the size of the pin.  Could then re-expand it later.

<img width="267" alt="image" src="https://github.com/google/perfetto/assets/3750359/958f8aad-09cf-48be-b5cf-2fb9dd79b814">

**Comment by LalitMaganti** [comment]
Merging into https://github.com/google/perfetto/issues/126 which this is really a special case of.
