### ISSUE TITLE
Race condition trying to load new content into Perfetto

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#721]
I'm using the following logic, but the UI is already up, it's already going through the ping/pong once.  And now I need to load another file.  Due to data race, the message handler from the previous load may still be working, and now this will try to add/replace that one.    Is there a better way to guard against this case?  This posts my json palyoad to the API once openTrace says everything is okay, but everything is not okay.  

JS is all single-threaded unless this loading is going to some WebWorker/ServiceWorker, so it's unclear why I'm getting failures trying to quickly cycle through files.   The page is never reloaded, and I just send perfetto json packets with Catapult-style json that's been base64 encoded and then decoded.

```
        // https://jsfiddle.net/vrsofx1p/
        function openTrace(obj)
        {
            const timer = setInterval(() => window.postMessage('PING', '\(ORIGIN)'), 50);
            
            const onMessageHandler = (evt) => {
                if (evt.data !== 'PONG') return;
                
                // We got a PONG, the UI is ready.
                window.clearInterval(timer);
                window.removeEventListener('message', onMessageHandler);
                
                window.postMessage(obj,'\(ORIGIN)');
            }
        
            window.addEventListener('message', onMessageHandler);
        }
        
        openTrace(obj);
```

**Comment by alecazam** [comment]
```
UI: https://ui.perfetto.dev/v40.0-c2c4bf187

PromiseRejection: Error: Failed assertion
 - assertTrue (frontend_bundle.js:4440:25)
 -  (frontend_bundle.js:430519:35)

Trace: not available (ARRAY_BUFFER). 
```

**Comment by stevegolton** [comment]
Hi @alecazam,

Your suspicions are correct, traces are loaded asynchronously. Trace processor runs inside a web worker, and the process of loading a trace involves executing a set of asynchronous calls to TP which can be seen in `trace_controller.ts`.

Can you describe in a little more detail what you're trying to achieve?

**Comment by alecazam** [comment]
I have a SwiftUI app that pulls a list of files, loads a Safari-backed WKWebView with ui.perfetto.dev, and then sends files as you advance through the list over to the web view via {“perfetto”:} objects.  It mostly works, but when advancing too quickly fwd/back even with the ping/pong wait logic, I get a giant ugly dialog about the array_buffer going missing.   That holds the json that I am sending over AFAIK.   So I suspect something in that worker isn’t accounted for in the ping/pong transmission.

**Comment by primiano** [comment]
I honestly would NOT try to load more than one trace into one UI instance. That was not even intended to work in the first place, I guess it just works by accident.

 Just spawn a new window for each trace

**Comment by alecazam** [comment]
I can't that's a whole new browser and all the memory associated with it.   There's no browser here, it's an embedded WKWebView in a SwiftUI.  That web view is already at 500mb for the tiniest of traces, and the docs state 2gb is the limit.  Wasm has 2gb limit (although really 4gb), but that doesn't mean that the data needs to live there. The gpu can pull data from the 64-bit address space, and that's all dynamic.  So don't store the dynamic timing data in the wasm addresses.  We could have never shipped Figma otherwise. This mostly works, and users can just live with the dialog popping up occasionally for now.

**Comment by primiano** [comment]
Then make sure you first reload the ui (so you start fresh) and only then postmessage. Don't rely on being able to post-message several time to the same instance. it might break in the future

> The gpu can pull data from the 64-bit address space, and that's all dynamic. So don't store the dynamic timing data in the wasm addresses. We could have never shipped Figma otherwise.

I don-t understand what any of this means "dynamic timing data into the wasm addresses" ???

**Comment by alecazam** [comment]
> I don-t understand what any of this means "dynamic timing data into the wasm addresses" ???

In the "How big is too big?".  I'm assuming that you're storing the trace data in the 32-bit wasm heap.  That's pretty limited.  Otherwise, why a 2gb limit.  Or maybe Perfetto uses a single Int32Array.

https://perfetto.dev/docs/visualization/large-traces

**Comment by alecazam** [comment]
I guess we moved the data out to the JS process to avoid fragmenting or needed to growth-double the wasm heap.  I thought wasm had extended their heap to 4gb.   And that 64-bit wasm was in development and making good progress.  Seems little point if the tab is going to limit the process to 2gb in the end.   Figma has a similar disclaimer about the 2gb limit.

**Comment by LalitMaganti** [comment]
Seems like everything is WAI on the Perfetto side so closing this out.
