### ISSUE TITLE
Perfetto can load gz files but not zip.

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#723]
The standard compress on macOS generates a zip file.   Would be nice to be able to drop these onto Perfetto.

**Comment by LalitMaganti** [comment]
I think we're @carlscabgro is working on adding zip file support for an unrelated reason so this might be solved as a result of that

**Comment by LalitMaganti** [comment]
This should now be fixed.

**Comment by alecazam** [comment]
Doesn't seem to work yet, but maybe this isn't in the current release.  I dropped a zip that I compressed on macOS, and ui.perfetto.dev didn't open any tracks.  Can still open with my kram-profile app.

**Comment by LalitMaganti** [comment]
Currently only rolled out to autopush.
