### ISSUE TITLE
When the same id is used in the Flow EVENT, it is drawn strangely.

### ISSUE THREAD

**Issue by jonghwan-choi-wdc** [google/perfetto#725]
[flow_simple.json](https://github.com/google/perfetto/files/14418847/flow_simple.json)

<img width="1217" alt="image" src="https://github.com/google/perfetto/assets/132034974/b747b524-fd17-49b7-9183-a8a2deb9d816">
Problem : SenderC does not connect to SenderD.  And SenderA is connected to SenderD.

There are cases where the flow ID value is reused.
However, this reused id value is used in other flow contexts.

I expect it to be drawn like below when using the attached json.
SenderA -> SenderB
SenderC -> SenderD

However, contrary to expectations, it is drawn as shown below.
SenderA -> SenderB / SenderD
SenderC -> X

Even if the same id is used, shouldn't the previous flow context be ignored when a new flow context starts?

thank you.!

**Comment by LalitMaganti** [comment]
This is working as intended see [1]. TLDR: the Chrome JSON tracing format does not take into account ids at all when considering how to link slices with flows. If you need this functionality, please use the Perfetto tracing format instead.

[1] https://github.com/google/perfetto/issues/686
