### ISSUE TITLE
Certain tables dont get populated with data 

### ISSUE THREAD

**Issue by amenbreaks** [google/perfetto#730]
Hey,
I want to profile a few apps, I am using a moto g40 fusion with android 12.
My perfetto settings are:-
![image](https://github.com/google/perfetto/assets/88613778/6fd008aa-61ff-489d-a727-8e5899d02957)
![image](https://github.com/google/perfetto/assets/88613778/e0430a08-003c-47d8-b82e-1c479219ebfd)
![image](https://github.com/google/perfetto/assets/88613778/2021cbad-4cbe-4ad3-9fa9-b7a279194a52)
![image](https://github.com/google/perfetto/assets/88613778/f4901cc6-40ed-40cb-873e-7cb26dcc7a5f)
![image](https://github.com/google/perfetto/assets/88613778/c3ab4ed6-31f7-403a-bad3-dadcb792235a)
![image](https://github.com/google/perfetto/assets/88613778/671b10c4-0c3f-4e38-b957-6d9879668509)
![image](https://github.com/google/perfetto/assets/88613778/0aefcda7-6816-40a0-a0dc-4ee1f3125ac7)
![image](https://github.com/google/perfetto/assets/88613778/b8099ea9-abff-4d90-bb37-e33c4a368871)
![image](https://github.com/google/perfetto/assets/88613778/4eb28f72-a524-4d56-a0ae-fa50f082741b)
![image](https://github.com/google/perfetto/assets/88613778/fc699856-5c0b-4368-857b-893516a26760)

I made a script to parse the trace file and convert it to csv's of various relevant tables

```python3
from perfetto.trace_processor import TraceProcessor

FILE="example.trace"

tp = TraceProcessor(trace=FILE)

def run(table):
        qr_it = tp.query(f'select * from {table};')
        qr_it.as_pandas_dataframe().to_csv(FILE[:-6]+f'.{table}.csv')

tp.query('INCLUDE PERFETTO MODULE android.dvfs;')
tp.query('INCLUDE PERFETTO MODULE common.slices;')
tp.query('INCLUDE PERFETTO MODULE android.anrs;')
tp.query('INCLUDE PERFETTO MODULE android.battery;')
tp.query('INCLUDE PERFETTO MODULE android.binder;')
tp.query('INCLUDE PERFETTO MODULE android.io;')
tp.query('INCLUDE PERFETTO MODULE android.monitor_contention;')
tp.query('INCLUDE PERFETTO MODULE android.network_packets;')
tp.query('INCLUDE PERFETTO MODULE android.process_metadata;')
tp.query('INCLUDE PERFETTO MODULE android.statsd;')
tp.query('INCLUDE PERFETTO MODULE linux.cpu_idle;')
tp.query('INCLUDE PERFETTO MODULE pkvm.hypervisor;')
tp.query('INCLUDE PERFETTO MODULE sched.thread_level_parallelism;')

tables = ["android_dvfs_counters", "thread_slice", "process_slice", "android_anrs", 
          "android_battery_charge","android_binder_metrics_by_process", "android_sync_binder_metrics_by_txn", 
          "android_sync_binder_thread_state_by_txn", "android_sync_binder_blocked_functions_by_txn", 
          "android_async_binder_metrics_by_txn", "android_binder_txns", "android_io_f2fs_counter_stats", 
          "android_io_f2fs_write_stats", "android_io_f2fs_aggregate_write_stats", "android_monitor_contention", 
          "android_monitor_contention_chain", "android_monitor_contention_chain_thread_state", 
          "android_monitor_contention_chain_thread_state_by_txn", "android_monitor_contention_chain_blocked_functions_by_txn", 
          "android_network_packets", "android_process_metadata", "android_statsd_atoms", "linux_cpu_idle_stats", 
          "pkvm_hypervisor_events", "sched_runnable_thread_count", "sched_active_cpu_count"]

for t in tables:
        run(t)
```

Using this code, a lot of tables are empty, namely, android_anrs, android_dvfs_counters, android_io_f2fs_aggregate_write_stats, android_io_f2fs_counter_stats, android_io_f2fs_write_stats, android_monitor_contention_chain, linux_cpu_idle_stats and  pkvm_hypervisor_events.

Now the problem is, with this app, I happen to interact with the filesystem as I saved a file in the storage so I expect the io f2fs tables to get populated, and the app is pretty slow so I believe ANRs should also be present.
I know nothing about dvfs counters, so if you could tell me what dvfs is, or point me to the right direction, then it would be much appreciated.

**Comment by aMayzner** [comment]
The way Trace Processor is written all of the tables will always be accessible, they might just be empty if there would be no data available from the trace to populate the tables. The best approach is to look for table/tables you know and understand why they would be populated, rather then trying a bunch of them without fully understanding what is the data they should contain. 

If you have a table that you expect to be populated with the config you have, please provide us with both
- config (load the trace in the UI, open the "Info and stats" tab, config is the "trace_config_pbtx" row) 
- trace
and we will try to debug the issue. 

Hope it helps. Feel free to ask for any explanation or give any suggestions if documentation is unclear.
