### ISSUE TITLE
Is it possible to show all dependencies at once?

### ISSUE THREAD

**Issue by xiaopi-ouo** [google/perfetto#731]
I wanto see all depdendencies in the time interval I select.
Image that slices and its depedencies formed a graph.
Now an dependency arrow is presented only when one of the slice in the graph the dependency involved in is selected.
Is there any way to show al the depedencies in the interval I select?

**Comment by stevegolton** [comment]
If I understand correctly, you want to see all flows in and out of all slices within an area selection.
This can be achieved by clicking on the "Flow Events" tab and selecting the "Show" checkbox as in the screenshot below.
![image](https://github.com/google/perfetto/assets/6147146/7da44b05-1cd4-42b1-9855-534d5f4a3294)
