### ISSUE TITLE
The priority of the same thread suddenly changes in a trace.

### ISSUE THREAD

**Issue by kongls2015** [google/perfetto#732]
Hello, I am trying to do tracing analysis using perfetto.
I caught this phenomenon: in a trace for a period of time, a certain process will correspond to multiple priorities.

For example, the kernel priority of ksoftirqd/0 is 120, but after preempted and resumed running, it becomes 49. The priority is restored to 120 after the next switch.
![img_v3_028o_ec343597-4999-408b-adda-d8d63b32f0dg](https://github.com/google/perfetto/assets/46475115/2e866124-d796-4823-b513-89c01ef48475)

Another case, one of my threads (log_collect) changed from 120 to 39 and then reverted to 120.
![img_v3_028o_59af0598-cbb2-4373-9bb5-c41a1113686g](https://github.com/google/perfetto/assets/46475115/71a89191-97a3-479d-aa36-6915739451a3)

How should this be explained? Is this caused by some behavior of the linux kernel? Or is it perfetto's problem?

**Comment by kongls2015** [comment]
Thanks a lot, could you give me some references to this behavior of the kernel? Or how do I retrieve this mechanism?

**Comment by LalitMaganti** [comment]
You might want to start at https://man7.org/linux/man-pages/man7/sched.7.html but this is not really in scope for Perfetto at this point. You have to look into which scheduler you are using and how that works to figure out why this priority change happened.

**Comment by primiano** [comment]
Also you might want to cross-check the raw trace if that's really what' happening under the hoods or we have some bug when parsing IRQ events.

I can see that behaviour could be due to the usage of priority inheritance mutexes

**Comment by kongls2015** [comment]
> You might want to start at https://man7.org/linux/man-pages/man7/sched.7.html but this is not really in scope for Perfetto at this point. You have to look into which scheduler you are using and how that works to figure out why this priority change happened.

Thanks for the tip.

**Comment by kongls2015** [comment]
> Also you might want to cross-check the raw trace if that's really what' happening under the hoods or we have some bug when parsing IRQ events.
> 
> I can see that behaviour could be due to the usage of priority inheritance mutexes or other forms of priority inheritance



> Also you might want to cross-check the raw trace if that's really what' happening under the hoods or we have some bug when parsing IRQ events.
> 
> I can see that behaviour could be due to the usage of priority inheritance mutexes or other forms of priority inheritance

Thank you. I'll do some research in this area

**Comment by kongls2015** [comment]
> Also you might want to cross-check the raw trace if that's really what' happening under the hoods or we have some bug when parsing IRQ events.
> 
> I can see that behaviour could be due to the usage of priority inheritance mutexes or other forms of priority inheritance

I checked trace and it did match the characteristics of priority inheritance. Thanks again.
