### ISSUE TITLE
UI enhancement: Exclude non-returning syscalls like sys_rt_sigreturn from processing to prevent endless slices

### ISSUE THREAD

**Issue by linzj** [google/perfetto#733]
The Perfetto UI currently does not account for system calls that do not return, such as `sys_rt_sigreturn`. This oversight leads to the generation of start slices that extend indefinitely and do not have a corresponding end slice, cluttering the UI with misleading information.

During my troubleshooting, I implemented a hard-coded patch to address this issue. Upon applying the patch, the perpetual slices were successfully eliminated from the UI, confirming that these non-returning syscalls can and should be excluded from UI processing.

I propose updating the UI's processing logic to automatically recognize and ignore these non-returning system calls to enhance the accuracy and clarity of the trace visualizations. This change will provide a more accurate representation of the system's behavior and improve the user experience when analyzing traces involving such syscalls.
![image](https://github.com/google/perfetto/assets/5935381/62487f01-3f60-4a09-bbbc-2d3d2af10ffa)

**Comment by LalitMaganti** [comment]
I'm not convinced that solving this problem at the trace processor level is necessarily the right one. Trace processor is used not just for UI visualization but also trace analysis and in those situations you might well want to see these syscalls in the tables.

Adding @stevegolton for thoughts on whether we can do something at the UI level to improve visualization of syscalls.

**Comment by stevegolton** [comment]
There's an ongoing discussion around how to render incomplete events in the UI.

We have an alternate render mode which renders them as a constant 20px wide box, rather than extending them to the end of the window. This can be enabled using the "Crop incomplete slices" flag on the [flags page](https://ui.perfetto.dev/#!/flags). This might help tidy up the timeline somewhat in your traces. Can you give it a try and let me know if it helps.

**Comment by linzj** [comment]
Thank you for the information. I will attempt to apply it and provide you with an update on the situation tomorrow.

**Comment by linzj** [comment]
![image](https://github.com/google/perfetto/assets/5935381/fbd9b6f2-c208-4aa5-8e6c-90f6e4fabcb4)
Upon reviewing the image provided, it appears that the results do not align with my expectations.

**Comment by linzj** [comment]
Unfortunately, the issue remains unresolved. I've attempted to address it using the approach you suggested at the UI level, but without success. It seems the root cause lies in the fact that row.depth is pre-calculated by the parser. In essence, the layout is already determined at the C++ level, and the UI simply renders the pre-arranged format. Therefore, it would be more appropriate to tackle this problem within the parser and layout stages.

**Comment by stevegolton** [comment]
Ah I see the problem now.

Do you have a trace you can share?

I'm out next week but the week after I'll investigate whether there's anything sensible we can do in the UI.

**Comment by linzj** [comment]
@stevegolton,

Thank you for your willingness to investigate this further. Here is the trace file for your reference. I appreciate your help with this issue, and I hope you have a relaxing and enjoyable vacation. Looking forward to picking this up once you're back.
[trace.tgz](https://github.com/google/perfetto/files/14544673/trace.tgz)

**Comment by linzj** [comment]
I've discovered that the excessive number of calls to sigreturn is actually caused by the implicit suspend check mechanism within the ART VM, which generates the instruction ldr x21, [x21, #0]. This particular instruction provokes a fault that is then handled by the ART VM's fault handler to perform a suspend check. The fault handling process generates a log as follows:

```
Handling SIGSEGV fault:
  si_signo: 11 (Segmentation fault)
  si_code: 1 (SEGV_MAPERR)
  si_addr: 0x0
Checking for generated code
In the generated code, looking for a handler
Invoking action on handler 0xb400007b157221f0
Checking suspend; instruction: f94002b5, check instruction: f94002b5
Suspend check match
Removed suspend trigger, invoking test suspend

```

This mechanism is orchestrated by the following segment of code in code_generator_arm64.cc:

```c++
void InstructionCodeGeneratorARM64::GenerateSuspendCheck(HSuspendCheck* instruction,
                                                         HBasicBlock* successor) {
  if (instruction->IsNoOp()) {
    if (successor != nullptr) {
      __ B(codegen_->GetLabelOf(successor));
    }
    return;
  }
  if (codegen_->CanUseImplicitSuspendCheck()) {
    // The triggering instruction for an implicit suspend check.
    __ Ldr(kImplicitSuspendCheckRegister, MemOperand(kImplicitSuspendCheckRegister));
    codegen_->RecordPcInfo(instruction, instruction->GetDexPc());
    if (successor != nullptr) {
      __ B(codegen_->GetLabelOf(successor));
    }
    return;
  }
  // Additional explicit suspend check code would likely follow here, if applicable.
}
```

This code is responsible for generating suspend checks during the execution of ART-compiled code. The Ldr instruction is used to load a register from the memory address pointed to by the same register; essentially, it is a self-referencing load. Due to the nature of this operation, it is expected to cause a fault, which is then intercepted by ART's fault handler as part of the implicit suspend check mechanism.

I hope this information provides clarity on the situation and assists in addressing the endless slices issue within the Perfetto UI.

**Comment by LalitMaganti** [comment]
Ok I looked a bit more into this and I think the correct thing to do would be to make sys_rt_sigreturn an instant event instead of starting the slice. It better matches the semantic.

@aMayzner can I ask you to look into this?

**Comment by LalitMaganti** [comment]
The above change should fix this issue, it should already be available in the autopush version of the UI and will make its way to canary/stable in the coming weeks.

**Comment by linzj** [comment]
@LalitMaganti @stevegolton @aMayzner @primiano

Thank you all for your efforts in investigating and addressing this issue with the endless slices caused by non-returning syscalls like sys_rt_sigreturn. I really appreciate the time and attention you have dedicated to understanding the root cause and implementing a solution to properly handle these syscalls as instant events in the Perfetto UI.

@LalitMaganti, thank you for recognizing the appropriate approach and assigning @aMayzner to work on it. @aMayzner, I'm grateful for your prompt action in implementing the necessary changes to parse sys_rt_sigreturn as an instant event. @primiano, thank you for contributing the commit to make this fix a reality.

@stevegolton, although the initial suggested approach didn't fully resolve the issue, I appreciate your willingness to investigate further and your openness to exploring alternative solutions. Your engagement and guidance throughout this process have been invaluable.

I sincerely appreciate the collaborative efforts of the entire team in resolving this issue. Your commitment to improving the Perfetto UI and providing an accurate representation of system behavior is truly commendable. Thank you all for your hard work and dedication.
