### ISSUE TITLE
Cannot open the settings page

### ISSUE THREAD

**Issue by GammaPi** [google/perfetto#736]
The contribution guide on https://perfetto.dev/docs/contributing/ui-plugins claims support for plugins.

But I can not access localhost:10000/settings. 

![20240308_193005.jpg](https://github.com/google/perfetto/assets/19838874/1dca6766-f296-4ee3-a11a-56ea34404ce9)

**Comment by GammaPi** [comment]
I found the solution. It looks like I need to visit the flags page.
The documentation is kind of outdated.

**Comment by stevegolton** [comment]
Thanks, looks like a typo in docs, we never had a settings page!

I believe it should just point to http://localhost:10000/
