### ISSUE TITLE
How to lock the range of Perfetto timeline

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#737]
I'm trying to lock a displayed range from Swift to WKWebView.   I'm trying to follow the Flutter sample, since this is something else not in the docs.  But there is a Time class that is not found.   This is typescript code, I'm sending over Javascript, but do I somehow need to include this source to call it.  This would be much simpler if I could just pass seconds in a Number.  The values for locking a range don't have to be nanosecond precise.

```
      // Time is not found, it's in ui/src/base/time.ts
        var obj = {
           perfetto: {
                timeStart: Time.fromSeconds(\(timeRange.timeStart)),
                timeEnd: Time.fromSeconds(\(timeRange.timeEnd)),
                viewPercentage: timeRange.viewPercentage,
                    
           }
        }
```

**Comment by alecazam** [comment]
I got something that finally worked.  Send the value down in nanos as an Int with the "n" after to indicate it's a number.  But unfortunately, Perfetto only honors the range the first time I send it, and then next one that loads resets the range.  

```
var obj = {
           "perfetto" : {
                //"timeStart": Time.fromSeconds(\(timeRange.timeStart)),
                //"timeEnd": Time.fromSeconds(\(timeRange.timeEnd)),
                "timeStart": \(timeStartInt)n,
                "timeEnd": \(timeEndInt)n,
                "viewPercentage": \(timeRange.viewPercentage),
                    
           }
        }
```

**Comment by alecazam** [comment]
So yeah, no matter when I send this string, if the browser has already received it once, the graph scale doesn't change after the first submission.  Is there some sort of latching happening.  Flutter dev originally send my the snippet where that is using the same mechanism.

**Comment by stevegolton** [comment]
I'm not familiar with the syntax you're using in your snippets, but the `n` suffix indicates a `bigint` literal in JavaScript. 
We use `bigint`s when representing time because `number`s don't have enough integer resolution to represent timestamps from trace processor - 53 bits vs 64 bits.

By default we stop listening after the first message, but you can counteract this by passing `keepApiOpen: true` along with the message when you open the trace.

**Comment by alecazam** [comment]
I tried "keepApiOpen: true".  That wasn't in the Flutter code I looked at.  It doesn't seem to make a difference.  It's like Perfetto is only expecting to receive and react to range one time.  And I thought that undocumented "keepApiOpen" flag was only for loading the file data.   Not sure how a tool like Perfetto benefits from closing its api by default.

**Comment by alecazam** [comment]
Here's the simplest form of what I'm trying to send.   A 10s range.

```
var objTime = {
    perfetto:{
        keepApiOpen: true,
        timeStart:0n,
        timeEnd:10000000000n,
        viewPercentage:0.8
    }};  
window.postMessage(objTime, 'https://ui.perfetto.dev');
```

**Comment by stevegolton** [comment]
> n is the notation for bigint. And bigint isn't really a marshalable type in json, so doesn't seem great for an api like this. Could just make it a string if the precision is that critical for a range.

I don't really follow your logic here. postMessage data doesn't need to be serialized to JSON, so bigints are perfectly fine.

> I tried "keepApiOpen: true". That wasn't in the Flutter code I looked at. It doesn't seem to make a difference. It's like Perfetto is only expecting to receive and react to range one time. And I thought that undocumented "keepApiOpen" flag was only for loading the file data. Not sure how a tool like Perfetto benefits from closing its api by default.
> 
> In my tool, I am looking across many clang build timings. And so I want the user to be able to optionally lock the range as you open new files, rather than have Perfetto adjust the timeline to the newly opened range.

I assuming you pass in the trace using postMessage as well (correct me if I'm wrong). As you mentioned, you need to set `keepApiOpen` to true when you pass in the trace, otherwise Perfetto will stop listening to message events.

Here's a minimal working example of a webpage that opens up perfetto in a new tab, opens a trace and starts scrolling around forever, which works for me in Chrome. Hopefully it should be adaptable to your Swift / WKWebView based tool.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfetto Scroller</title>
    <script>
        const PERFETTO_URL = "https://ui.perfetto.dev/";

        async function loadPerfetto() {
          let pong = false;

          window.addEventListener('message', (event) => {
            if (event.data === 'PONG') {
              pong = true;
            }
          });

          const tab = window.open(PERFETTO_URL);

          // Wait for the UI to be ready
          while (!pong) {
            tab.postMessage('PING', PERFETTO_URL);
            await new Promise((r) => setTimeout(r), 1000);
          }

          return tab;
        }

        async function loadTrace(tab) {
          const traceUrl = "https://storage.googleapis.com/perfetto-misc/example_android_trace_15s";
          const resp = await fetch(traceUrl);
          const blob = await resp.blob();
          const arrayBuffer = await blob.arrayBuffer();
          tab.postMessage({
            perfetto: {
              buffer: arrayBuffer,
              title: 'Example android trace',
              keepApiOpen: true,
          }}, PERFETTO_URL);
        }

        async function openAndStartScrolling() {
          const tab = await loadPerfetto();
          await loadTrace(tab);

          // Start scrolling the timeline forever...
          let offset = 261191739475112n;
          while (true) {
            await new Promise((r) => setTimeout(r), 1000);
            tab.postMessage({
              perfetto: {
                timeStart: offset,
                timeEnd: offset + 100000n,
                viewPercentage: 0.5,
              }
            }, PERFETTO_URL);
            offset += 10000n;
          }
        }
    </script>
</head>
<body>
    <h1>Perfetto scroller</h1>
    <button onclick="openAndStartScrolling()">Open ui.perfetto.dev, load a trace and start scrolling</button>
</body>
</html>

```

Serve this page - e.g.`python -m http.server` - and click the button to load Perfetto in a new tab.
