### ISSUE TITLE
Problem with parsing 64bits tid fields in JSON captures

### ISSUE THREAD

**Issue by epoupon** [google/perfetto#738]
Hello,

Parsing 64bits values in json may cause issues. I noticed this gets rendered with all threads merged:
```
{
	"traceEvents": [
		{ "name" : "thread_name", "pid" : 1, "tid" : 140589156634432, "ph" : "M", "args" : { "name" : "MainThread" } }, 
		{ "name" : "thread_name", "pid" : 1, "tid" : 140588800255680, "ph" : "M", "args" : { "name" : "SomeOtherThread" } }, 
		{ "name" : "WriteTransaction", "cat" : "Database", "pid": 1, "tid" : 140589156634432, "ts" : 55.303, "dur" : 3000.602, "ph" : "X" }, 
		{ "name" : "WriteTransaction", "cat" : "Database", "pid": 1, "tid" : 140588800255680, "ts" : 50.399, "dur" : 3122.675, "ph" : "X" } 
	],
}
```

Switching to strings is better, as each thread has now its own track:
```
{
	"traceEvents": [
		{ "name" : "thread_name", "pid" : 1, "tid" : "140589156634432", "ph" : "M", "args" : { "name" : "MainThread" } }, 
		{ "name" : "thread_name", "pid" : 1, "tid" : "140588800255680", "ph" : "M", "args" : { "name" : "SomeOtherThread" } }, 
		{ "name" : "WriteTransaction", "cat" : "Database", "pid": 1, "tid" : "140589156634432", "ts" : 55.303, "dur" : 3000.602, "ph" : "X" }, 
		{ "name" : "WriteTransaction", "cat" : "Database", "pid": 1, "tid" : "140588800255680", "ts" : 50.399, "dur" : 3122.675, "ph" : "X" } 
	],
}
```
But unfortunately, thread names are not resolved in the UI. They are displayed as:
"140589156634432 29510"
"140588800255680 29554"

Is there a way to work around this? (Apart from switching to protobuf messages or masking to 32 bits?)

**Comment by epoupon** [comment]
(Note this is working as expected with the legacy UI)

**Comment by LalitMaganti** [comment]
> Parsing 64bits values in json may cause issues.

Please see our FAQ at https://perfetto.dev/docs/faq#why-does-perfetto-not-support-lt-some-obscure-json-format-feature-gt-.

tids/pids which are uint64 fall into the category of "This is especially the case for traces which are programmatically generated outside of Chrome and depend on the implementation details of chrome://tracing.". As described in the FAQ, the Chrome JSON format is only supported as much as is required to support Chrome generated traces. Anything else is only supported if it is easy to do so and uint64 tids would require significant rearchitecting of trace processor.

> But unfortunately, thread names are not resolved in the UI. They are displayed as:

The representation of tids/pids as strings also causes the name to be marked as such. THis was a hidden feature for prototyping purposes but not really intended to be depended upon.

> Is there a way to work around this? (Apart from switching to protobuf messages or masking to 32 bits?)

These would be the suggested workarounds.

**Comment by epoupon** [comment]
Thanks for your answer!
