### ISSUE TITLE
How to merge same methods in Web UI?

### ISSUE THREAD

**Issue by scruel** [google/perfetto#739]
I want to profile to investigate which methods are the most time-consuming in my current multiple-threading program, currently, Web UI x-axis is time, so that I can only check those method blocks one by one based on the time, and it is not such obviously for me to check those repeatedly execution methods, consider the program also will contain many init methods which also consumed a lot of time.

You may check the UI style of `py-spy`.

**Comment by primiano** [comment]
It feels like what you should do is enabling the Pivot table in [the flags page](https://ui.perfetto.dev/#!/flags/pivotTable), and then range-select the methods and reason on the pivot table. Example:

![image](https://github.com/google/perfetto/assets/7137473/d551eb7b-5adc-44c7-9b38-194a2bf2635a)

The ideal solution would be to have flamegraphs generated out of slices, which is something we have long discussed but never got to it yet.
