### ISSUE TITLE
Feature Request: Tool to generate standalone html (similar to catapult's trace2html)

### ISSUE THREAD

**Issue by sujankh** [google/perfetto#74]
Hi, I have been enjoying using perfetto. Thanks a lot for working on this tool.
I was wondering if there are plans (or if it is even possible) to generate a standalone html for perfetto UI.
The reason I was asking is because of the trace2html tool found in catapult/tracing which is a neat tool to serve trace data.

Since perfetto can run on a server, maybe the alternative is to have the ability to share profiling data right?

Thank you.

**Comment by primiano** [comment]
There are no plans to support that feature. vulcanizing data+code into a html file opens the door to too many extra problems:
 - many web platform API don't work with file:// schemes and require https://
 - it creates a versioning issue where the UI for those traces will stay behind forever, hence after a while those traces will be impossible to open (Browsers keep evolving in breaking ways, whether we like it or not).

In essence it would be yet another surface to test and maintain and that extra cost is not worth the benefit.
 
What's the reason why this use case is necessary? Today there are various ways you can achieve a one-click solution using ui.perfetto.dev:
- If the file is hosted on GCS, just use the ?url= arg, i.e. https://ui.perfetto.dev/#!?url=https://commondatastorage.googleapis.com/bucket_name/file_name (note that the bucket config needs CORS settings for allowing ui.perfetto.dev to fetch)
- If not, you can build your own bridge that pushes traces into ui.perfetto.dev via window.open (Example here). See also related discussion in https://github.com/google/perfetto/issues/14 .

**Comment by sujankh** [comment]
Thank you for the explanation. Now i understand the cons of having html files.

`What's the reason why this use case is necessary?` -> The reason I wanted this was to have the ability to share profiles with a link and also to serve these files from a web server. Looks like the ways you listed are much better. I'll try serving trace files from our own server. Would be better if it could be shared with a sharable link (Looks like #14 has some discussions and will try those).

Want to say thanks again for a cool tool.
