### ISSUE TITLE
Unable to view the caller function of sched_blocked_reason using Perfetto

### ISSUE THREAD

**Issue by ZiqiangGe** [google/perfetto#743]
Hello, when I use Pertetto to capture the trace, the caller of sched_blocked_reason is a number, not a specific function name. Like this:
![image](https://github.com/google/perfetto/assets/18515372/93fb5e43-628c-45ce-b3a4-20349d72c2dd)

But It can be displayed normally using systrace.py or grabbing ftrace alone. Do you know how to solve it?

- echo 1 >/sys/kernel/tracing/events/sched/sched_blocked_reason/enable

- echo 1 > /sys/kernel/tracing/tracing_on

- cat /sys/kernel/tracing/trace

![image](https://github.com/google/perfetto/assets/18515372/2306245c-fce0-4123-9191-ef99fd823905)

**Comment by LalitMaganti** [comment]
Unfortunately, if you are running a user build, there is not way to solve this problem. The difference between Perfetto and systrace comes from the use of the text ftrace source for systrace wheras we use the binary ftrace source. This means that we need to symbolize kernel pointers out of band.

If you are running a userdebug build, you can enable the `symbolize_ksyms` option of ftrace [1] which will cause the function pointers to be correctly symbolized in the UI.

The restriction of userdebug exists for security reasons: it might be fixed one day but is currently not a priority for us. @rsavitski FYI.

[1] https://perfetto.dev/docs/reference/trace-config-proto#FtraceConfig
