### ISSUE TITLE
Can't buffer be used exclusively by a certain data source?

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#747]
Since duration ms is 0, data will always be collected into the ring buffer. When the ctrlc signal is used to trigger the end of the acquisition, **it is found that the data in the buffer with ID 1 does not have track event data, but is overwritten by ftrace.**

How to ensure that the buffer with ID 1 only stores track event data and will not be interfered by other data sources?

The config file is as follows:
```
duration_ms: 0

buffers {
  size_kb: 32768
  fill_policy: RING_BUFFER
}

buffers {
  size_kb: 32768
  fill_policy: RING_BUFFER
}

data_sources {
  config {
    name: "linux.ftrace"
    target_buffer: 0
    ftrace_config {
      compact_sched: {
        enabled: true
      }
      ftrace_events: "sched/sched_switch"
      ftrace_events: "sched/sched_wakeup_new"
      ftrace_events: "sched/sched_wakeup"
      ftrace_events: "sched/sched_waking"
    }
  }
}

data_sources: {
  config {
    name: "track_event"
    target_buffer: 1
  }
}

data_sources {
  config {
    name: "linux.process_stats"
    target_buffer: 0
  }
}
```

**Comment by LalitMaganti** [comment]
This is definitely supported and something we make use of *extensively* so it seems unlikely to be a bug in Perfetto. More seems like something is going wrong in track_event or in how you're starting/stopping the trace.

Specifically, what happens if you turn off ftrace and process_stats. Does the track_event show up then?

**Comment by duokuiwang** [comment]
If ftrace and process_stats are turned off, track_event data cannot be stored in the current RING_BUFFER, and it can be stored by changing the strategy to DISCARD.

**Comment by LalitMaganti** [comment]
I have no idea what that means. Ring buffer and discard do not affect what data can and cannot be stored in a buffer. They simply control the strategy followed when the buffer is full.
