### ISSUE TITLE
Coding error in counter track hue selection 

### ISSUE THREAD

**Issue by jcortell68** [google/perfetto#749]
Came across this while studying the code. Obviously, not a bug since color is subjective. If you don't want to change behavior (i.e., fix the typo), I suppose you can correct the comment so that it syncs with what the code is doing.

I believe the `Math.max()` call in [this line](https://github.com/google/perfetto/blob/b9ad55ca463ccb2ba217a5d7bc3f6dfb52f28a5a/ui/src/frontend/base_counter_track.ts#L532) accidentally has a minus character instead of a comma. It wouldn't make much sense to use that function on a single argument. I believe the code wants to use an exponent range of 3 through 9, but didn't get there.

So, the colors being used are not what's described in the comment. Do with this information what you wish :-)

**Comment by stevegolton** [comment]
Hey, thanks for letting us know 👍 

I think the intention was probably something like this:

```
const expCapped = Math.min(Math.max(exp, 3), 9) - 3;
```

I've put a patch together and notified the person responsible for the code to see if it matches their expectations.

**Comment by jcortell68** [comment]
Ah, yes.  That makes more sense. A net exponent range of 0 through 6 (not 3 through 9 as I stated) would give the color sequence described in the comment.

**Comment by jcortell68** [comment]
@stevegolton I don't know if you meant to mark this closed or whether that was accidental. I looked for the PR/commit with the adjustment and didn't find it.

**Comment by stevegolton** [comment]
Sorry, yes the patch is still in review. I was too trigger-happy with the close button. Reopening.

Here's the link to the patch.
https://android-review.googlesource.com/c/platform/external/perfetto/+/3027711

**Comment by stevegolton** [comment]
It turns out the functionality of the code was the correct and the comment was wrong. Besides, color scheme changes are difficult as folks get used to the way things look and it's jarring when things change.

I've removed the comment (and the superfluous `Math.max()`) under the assertion that no comment is better than a wrong comment.

**Comment by jcortell68** [comment]
Sounds good to me. I suspect changing the color algorithm at this point would probably be seen as undesirable for that very reason. So, removing the comment is very much a suitable resolution, IMO. Thanks!
