### ISSUE TITLE
Potential null-deref in TracingServiceImpl::CompleteFlush()

### ISSUE THREAD

**Issue by emaxx-google** [google/perfetto#75]
`TracingServiceImpl::CompleteFlush()` calls `SnapshotLifecyleEvent()` regardless of whether `tracing_session` is null. And `SnapshotLifecyleEvent()` unconditionally dereferences `tracing_session`. This looks like a potential crash, although I don't know the codebase in order to judge whether it's possible in practice.

This was found by clang-tidy's "clang-analyzer-core.NullDereference" diagnostics.

**Comment by primiano** [comment]
Oh well spotted, seems indeed a bug.  Rare (if the session gets destroyed in the middle of NotifyFlushDoneForProducer and the posted task), but still possible.
Thanks

**Comment by LalitMaganti** [comment]
This should now be fixed with the above patch :) Thanks for filing!
