### ISSUE TITLE
Is it possible to show the chain of flow events in the Perfetto Timeline, similar to Chrome Trace Viewer?

### ISSUE THREAD

**Issue by aaronenyeshi** [google/perfetto#750]
Hi Perfetto team, our team loves using both the Chrome Trace Viewer and Perfetto UI!

We have noticed a difference between the two: The chain of flows showing preceding events on Chrome Trace Viewer, but not on Perfetto. Is there any way to show it on Perfetto as well?

Trace file: 
[mock-chain-flow.json](https://github.com/google/perfetto/files/14794115/mock-chain-flow.json)

## Reproduction Steps:
Chrome Trace Viewer:
1) Click the kernel event, and click the link at "Preceding events	15 events of various types"
2) The Trace Viewer will show the two flows and 15 chained events.
<img width="1803" alt="image" src="https://github.com/google/perfetto/assets/17602366/dde6dd01-e2f4-4388-a2d0-387baf7f9b9c">

Perfetto UI:
1) Click the kernel event, there is only an option to click Preceding flow.
2) Perfetto will only show a single flow:
<img width="1629" alt="image" src="https://github.com/google/perfetto/assets/17602366/c57b89ca-155e-48c5-99b7-6a99a4a75caf">

## Request
Would it be possible to show all preceding events? Or show multiple flows if they are chained up? This is extremely helpful when the number of trace events is dense.

Thank you.

**Comment by stevegolton** [comment]
I think enabling the flag "Show indirect preceding flows" at least partially does what you want. It enables rendering of flows connected to ancestor slices of slices within the flow.

I.e.

<img width="1440" alt="image" src="https://github.com/google/perfetto/assets/6147146/d2c1fa53-cb1a-4785-a69d-9aaf59f2d4a8">

However, it only affects the rendering of flows on the timeline, not the listed flows in the slice details panel.

**Comment by stevegolton** [comment]
I'll close this issue for now, feel free to re-open if something's still missing.

**Comment by xiaopi-ouo** [comment]
Hi,
I'm curious about what does "ancestor" means in perfetto. Does it just like what this function defines ?https://github.com/google/perfetto/blob/0b70a44bffbc7fbe61e892bacc179ba54eda3071/src/trace_processor/perfetto_sql/stdlib/prelude/after_eof/slices.sql#L19

That is two slices should be in the same track and the descendant should end before the ancestor end.
Is it possible now to show all flows cross tracks without considering ancestor/descendant relationship?

For example, slice (1, 2) has a flow and (3, 4) has a flow.
<pre>
------------------------------------------------------------------------------------
Process_Track
------------------------------------------------------------------------------------
- Thread_Track_1 |      slice_1                 slice_3
--------------------------------↘----------------------↘-----------------------
- Thread_Track_2 |               slice_2                slice_4
------------------------------------------------------------------------------------
</pre>

**Comment by LalitMaganti** [comment]
> I'm curious about what does "ancestor" means in perfetto. Does it just like what this function defines ?

Ancestor is largely what that function defines. It basically considers the stack of slices and walks up the tree: all such slices are considered ancestors.

> Is it possible now to show all flows cross tracks without considering ancestor/descendant relationship?

We don't do this by default because we have many traces where there are hundreds of flows are rendering all of them would be both impossible to read and would really hurt performance.

If you want this, you can do this by doing an area select (box select) over the region of time/track you want to show flows for then go to 'Flow Events', then click on 'Show all', this renders flows for all events within the area selection.

![Image](https://github.com/user-attachments/assets/35ccd048-c1f2-48c8-9ca0-91d77d1748c9)

**Comment by xiaopi-ouo** [comment]
@LalitMaganti 
Thank you so much, this is exactly what I wanted!
