### ISSUE TITLE
Add support for range specifications in trace resolver

### ISSUE THREAD

**Issue by yunqu** [google/perfetto#752]
https://github.com/google/perfetto/blob/main/python/perfetto/trace_uri_resolver/resolver.py#L29

The current constraintClass only supports a couple of compactors. The API will parse an input URI into dict, if we specific a URI like "custom:time>123;time<456", from my understanding, the trace resolver won't work properly, since the key "time" in the dict will get overwritten. For example, if you see how the result is parsed: https://github.com/google/perfetto/blob/main/python/perfetto/trace_uri_resolver/resolver.py#L127, my guess is that only 'time<456' will take effect.

I am proposing that we add an additional OP to support ranges. e.g. the op "<>" can be added, so we can specify the above URI like "custom:time<>123,456". Also, the parsed results need to be specified in a list, something like
```
'key': [ConstraintClass(123, Op.GE), ConstraintClass(456, Op.LE)]
```
Then our customized trace resolver can take it over from there. 

Let me know if this makes sense. I can help contribute the code.

**Comment by LalitMaganti** [comment]
Yeah all seems reasonable. Contributions welcome.
