### ISSUE TITLE
Change the platform delegate to allow us to use a customized path for trace processor binaries

### ISSUE THREAD

**Issue by yunqu** [google/perfetto#753]
If you look at https://github.com/google/perfetto/blob/main/python/perfetto/trace_processor/api.py#L31C1-L31C18, you see the PLATFORM_DELEGATE is defined as a constant, then it is later provided to the __init__() function:
```
def __init__(self,
               trace: Optional[TraceReference] = None,
               addr: Optional[str] = None,
               config: TraceProcessorConfig = TraceProcessorConfig(), # we can also provide a None here, see below
               file_path: Optional[str] = None, # we want to add platform_delegate, see below
               ):
    ... 
    self.platform_delegate = PLATFORM_DELEGATE()
     ...
```
This is not easy for our cases where we have a customized binary path. To make our binary file downloadable from another place, we will have to make changes to both platform.py and api.py. 

I want to make the following changes on api.py:
```
def __init__(self,
               trace: Optional[TraceReference] = None,
               addr: Optional[str] = None,
               config: TraceProcessorConfig = None,
               file_path: Optional[str] = None,
               platform_delegate: Optional[PlatformDelegate] = None,
               ):
    if config is None:
        config = TraceProcessorConfig()
    self.config = config
    if platform_delegate is None:
        platform_delegate = PLATFORM_DELEGATE()
    self.platform_delegate = platform_delegate
    ...
```
What do you think about this change? Basically we allow users to provide their own version of PlatformDelegate class (this can be a child of the original PlatformDelegate class, with a customized shell path to download the binary though).

I can help contribute the code.

**Comment by LalitMaganti** [comment]
Seems reasonable except I'd actually put in the TraceProcessorConfig object. It was designed exactly for this.

**Comment by yunqu** [comment]
> Seems reasonable except I'd actually put in the TraceProcessorConfig object. It was designed exactly for this. Contributions welcome.

Understood. But I still have to call 
```
tp = TraceProcessor(trace=TRACE_FULL_PATH, config=TraceProcessorConfig(bin_path="some_temp_path"))
```
I would like to make the API look as easy as possible, so somewhere I want to overwrite the default bin path so I don't have to provide that every time.
```
from my.module.api import TraceProcessor
tp = TraceProcessor(trace=TRACE_FULL_PATH)
```

**Comment by LalitMaganti** [comment]
Hold on actually. Thought about this a bit more.  In your wrapper module why can't you just do:
```
import perfetto.trace_processor.api as tp

tp.PLATFORM_DELEGATE = <your custom impl here>

TraceProcessor = tp.TraceProcessor
```

Platform delegate was designed specifically to allow things like this. It's designed to be overridden in this way and I something we do ourselves.

**Comment by yunqu** [comment]
That's also possible. Thanks for the feedback.

I guess you have 2 ways:

1. Get customized TraceProcessor and PlatformDelegate classes. So 2 files are modified. Then you can use the simply import like ```
from my.module.api import TraceProcessor
tp = TraceProcessor(trace=TRACE_FULL_PATH)
```
2. Or you can use the following code, with 1 file (customized PlatformDelegate class) changed but extra line specifying the PLATFORM_DELEGATE.
```
import perfetto.trace_processor.api as api
api.PLATFORM_DELEGATE = <your custom impl here>
tp= api.TraceProcessor(trace=TRACE_FULL_PATH)
```

As I said, I want the API to be as easy as possible, so implementation detail (PlatformDelegate) should not be exposed to our internal users if possible. The current API will support it, but I personally prefer option 1 because API will look better.

**Comment by LalitMaganti** [comment]
Yup you have those two options. I'm not opposed to also having something like you originally proposed upstream but if the current way works, I'd just stick with it for simplicity's sake.
