### ISSUE TITLE
Counter unit name not taken into account

### ISSUE THREAD

**Issue by facewindu** [google/perfetto#754]
I'm trying to set some unit names and multipliers to my custom counter tracks like so
```
TracePacket.newBuilder()
            .setTrustedPacketSequenceId(...)
            .setTrackDescriptor(TrackDescriptor.newBuilder()
                .setUuid(...)
                .setName("AVAIL_MEM")
                .setCounter(CounterDescriptor.newBuilder().setUnitName("foo").setUnitMultiplier(1000))
            )
            .build()
```
Canary Perfetto displays
<img width="485" alt="image" src="https://github.com/google/perfetto/assets/5922961/e3d98675-0aa5-4d90-8e39-07382f9d6a26">
The multiplier is properly taken into account, but not the unit name. Am I doing something wrong ?

**Comment by LalitMaganti** [comment]
Nothing is wrong, the unit name is just not plumbed through correctly for track event: it was never a huge deal because the UI didn't display events anyway but now it does, we should definitely add support for that.

Patches welcome or otherwise we will get to this at some point.

**Comment by LalitMaganti** [comment]
https://github.com/google/perfetto/issues/754 actually tracks this already so closing as a dupe.
