### ISSUE TITLE
Display dma_fence events in a single row

### ISSUE THREAD

**Issue by gramound** [google/perfetto#755]
The "dma_fence" events currently show-up 1 per row (format "%s-%s%llu-%lld", driver_name, timeline_name, context, seqno).
I'm looking at a 25s trace with over 3000 rows under "Misc Global Tracks" named like driver-timelinex-1000,  driver-timelinex-1001,  driver-timelinex-1002,  driver-timelinex-1003, etc. Each row containing only 1 "fence" slice.

It would be nice if all the seqno of the same "driver_name,timeline_name,context" could be presented in the same row (with the seqno in the slice name).

Is this possible to do within the viewer, or does it require the Linux driver to present its events differently?

**Comment by LalitMaganti** [comment]
Yes it's possible to make the change within trace processor: you just need to change the code at https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/importers/ftrace/drm_tracker.cc;bpv=1

Patches to fix this welcome (contribution guide is available at https://perfetto.dev/docs/contributing/getting-started) but it's likely not something we will get to ourselves.

**Comment by gramound** [comment]
Thanks for the code link. I think I misunderstood the track name format in the issue description. According to GetFenceTimelineByContext, what I assumed to be seqno (number at the end of the track name) were actually contexts. It's probably something specific to the driver I'm investigating to increment contexts for each fence. I'll study this a bit more (might take a while).

**Comment by LalitMaganti** [comment]
Closing out as this might be WAI on the Perfetto side. Please reopen if you find more out here.

**Comment by gramound** [comment]
> It's probably something specific to the driver I'm investigating to increment contexts for each fence.

Confirmed the driver was using a unique context per fence (seqno=1) intentionally to prevent the automatic use of `fence_is_later()` (incorrect for this driver). I'm thankful the ui is opensource so I could use a custom workaround.

**Comment by LalitMaganti** [comment]
> I'm thankful the ui is opensource so I could use a custom workaround.

Seems rather overkill to maintain a fork just for this, it would probably be easy to visualize this using debug tracks (or if you wanted more control write + upstream a UI plugin to visualize this how you want). But whatever works :)

**Comment by gramound** [comment]
I agree it's overkill, not to mention inconvenient when sharing traces.

It's not just about visualizing the fences though. I also want to remove the thousands of single-slice tracks generated by those fences under "Misc Global Tracks". I tried to just fixup the `context` and `seqno` values with the trace processor, but it wouldn't let me modify the "internal_args" table. I was able to do it in sqlite, but I'm not sure if I how to bring this back into a trace format. (Pardon my ugly SQL. Could be prettier with `EXTRACT_ARGS` but it doesn't exist in mysql)
```
-- Copy value from context to seqno for mybadfence and myotherbadfence
UPDATE internal_args SET int_value = c.seqno
FROM (
  SELECT arg_set_id, context.int_value AS seqno
  FROM ftrace_event
    JOIN args AS context USING(arg_set_id)
    JOIN args AS timeline USING(arg_set_id)
  WHERE ftrace_event.name LIKE 'dma_fence_%'
    AND context.key = 'context'
    AND timeline.key = 'timeline'
    AND timeline.string_value IN ('mybadfence','myotherbadfence')
  ) AS c
WHERE key = 'seqno' AND internal_args.arg_set_id = c.arg_set_id;
-- Hardcode a unique context value for mybadfence
UPDATE internal_args SET int_value = 1000
FROM (
  SELECT arg_set_id
  FROM ftrace_event JOIN args AS timeline USING(arg_set_id)
  WHERE ftrace_event.name LIKE 'dma_fence_%'
    AND timeline.key = 'timeline'
    AND timeline.string_value = 'mybadfence'
  ) AS c
WHERE key = 'context' AND internal_args.arg_set_id = c.arg_set_id;
-- Do the same for myotherbadfence ...
```

**Comment by LalitMaganti** [comment]
> I also want to remove the thousands of single-slice tracks generated by those fences under "Misc Global Tracks".

You'd probably be using the upcoming work we are doing to have "custom workspaces" so that you can choose to show/hide whatever tracks you want. You can see the beginings of that feature emerging with the recently landed track filtering support on autopush UI. @stevegolton will certainly be interested in your usecase here.

> I tried to just fixup the context and seqno values with the trace processor, but it wouldn't let me modify the "internal_args" table.

That's not really how trace processor works: you cannot modify the tables generated at processing time to change how the UI works as everything is read-only. Instead, the way to do it is create new tables with new tracks. As I say, the right thing here is to just hide the tracks at the UI level even while preserving the tracks in TP.
