### ISSUE TITLE
INCLUDE: unknown module 'sched.time_in_state'

### ISSUE THREAD

**Issue by ChenJiahao-A** [google/perfetto#756]
E:\tools\anaAnaly_myself\perfetto-43.1\python
λ python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from perfetto.trace_processor import TraceProcessor
>>> tp = TraceProcessor(trace='trace')
>>> tp.query('INCLUDE PERFETTO MODULE sched.time_in_state')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\olib\python37\lib\site-packages\perfetto\trace_processor\api.py", line 284, in query
perfetto.trace_processor.api.TraceProcessorException: INCLUDE: unknown module 'sched.time_in_state'

>>> tp.query('INCLUDE PERFETTO MODULE sched.time_in_state;')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\olib\python37\lib\site-packages\perfetto\trace_processor\api.py", line 284, in query
perfetto.trace_processor.api.TraceProcessorException: INCLUDE: unknown module 'sched.time_in_state

**Comment by ChenJiahao-A** [comment]
Is there any other way I can obtain this table, sched_percentage_of_time_in_state?

**Comment by LalitMaganti** [comment]
Two options:
1) Wait for us to do a release
2) Copy the statement which creates the table (and its dependencies) from https://github.com/google/perfetto/blob/main/src/trace_processor/perfetto_sql/stdlib/sched/time_in_state.sql and run that directly instead.

**Comment by ChenJiahao-A** [comment]
Thank you!

**Comment by ddiproietto** [comment]
> @ddiproietto are we OK to do a release of Perfetto this week?

Yep, let's get that done today.

**Comment by ChenJiahao-A** [comment]
**Why do the same problems still occur？**
E:\tools\anaAnaly_myself\perfetto-44.0\python
λ python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

from perfetto.trace_processor import TraceProcessor
tp = TraceProcessor('trace101_1')
tp.query('INCLUDE PERFETTO MODULE sched.time_in_state;')
Traceback (most recent call last):
File "", line 1, in
File "E:\tools\anaAnaly_myself\perfetto-44.0\python\perfetto\trace_processor\api.py", line 284, in query
raise TraceProcessorException(response.error)
perfetto.trace_processor.api.TraceProcessorException: INCLUDE: unknown module 'sched.time_in_state'
tp.query('INCLUDE PERFETTO MODULE sched.states;')
<perfetto.trace_processor.api.TraceProcessor.QueryResultIterator object at 0x00000274BCC45EC8>

**Comment by LalitMaganti** [comment]
This should now be resolved with the latest release.
