### ISSUE TITLE
What is the method to obtain the duration of different states in slice？

### ISSUE THREAD

**Issue by ChenJiahao-A** [google/perfetto#757]
Slice
binder transaction
Details
Name
binder transaction
Category
binder
Start time
00:00:03.217450385
Absolute Time
2024-04-03T03:51:49.011813574

```
Duration
91ms 552us 692ns
Sleeping
75ms 387us 154ns (82.34%)
Runnable
16ms 142us 462ns (17.63%)
Running
23us 76ns (0.03%)
```

**Comment by aMayzner** [comment]
This join should give you what you want. It also uses function that might not yet be available in `sched.time_in_state` module, so you might have to run it directly from https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/perfetto_sql/stdlib/sched/time_in_state.sql

You can also make it a PERFETTO FUNCTION that takes `id` as an argument. 
```
INCLUDE PERFETTO MODULE sched.time_in_state;
INCLUDE PERFETTO MODULE slices.with_context;

SELECT s.*
FROM sched_time_in_state_for_thread_in_interval(t.ts, t.dur, t.utid) s 
JOIN thread_slice t WHERE id = 3;
```

**Comment by ChenJiahao-A** [comment]
**Why do the same problems still occur？**
E:\tools\anaAnaly_myself\perfetto-44.0\python
λ python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from perfetto.trace_processor import TraceProcessor
>>> tp = TraceProcessor('trace101_1')
>>> tp.query('INCLUDE PERFETTO MODULE sched.time_in_state;')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\tools\anaAnaly_myself\perfetto-44.0\python\perfetto\trace_processor\api.py", line 284, in query
    raise TraceProcessorException(response.error)
perfetto.trace_processor.api.TraceProcessorException: INCLUDE: unknown module 'sched.time_in_state'
>>> tp.query('INCLUDE PERFETTO MODULE sched.states;')
<perfetto.trace_processor.api.TraceProcessor.QueryResultIterator object at 0x00000274BCC45EC8>
