### ISSUE TITLE
Adding fastrpc related trace events

### ISSUE THREAD

**Issue by funfoolsuzi** [google/perfetto#758]
I have noticed a few trace events available on a few Android systems that can be useful for tracking system memory usage. 
These are
- [fastrpc/fastrpc_dma_map](https://git.codelinaro.org/clo/la/kernel/msm-5.4/-/blob/msm-5.4.r2/include/trace/events/fastrpc.h#L130)
- [fastrpc/fastrpc_dma_unmap](https://git.codelinaro.org/clo/la/kernel/msm-5.4/-/blob/msm-5.4.r2/include/trace/events/fastrpc.h#L162)
- [fastrpc/fastrpc_dma_alloc](https://git.codelinaro.org/clo/la/kernel/msm-5.4/-/blob/msm-5.4.r2/include/trace/events/fastrpc.h#L184)
- [fastrpc/fastrpc_dma_free](https://git.codelinaro.org/clo/la/kernel/msm-5.4/-/blob/msm-5.4.r2/include/trace/events/fastrpc.h#L212)

I want to perform the ftrace event addition procedure listed in https://perfetto.dev/docs/contributing/common-tasks#add-a-new-ftrace-event for those event.

**So my question is: Would this be an acceptable upstream contribution? Do people think these events can useful as well?**

If the above 4 events are acceptable, I am also open to all trace events available in [fastrpc.h](https://git.codelinaro.org/clo/la/kernel/msm-5.4/-/blob/msm-5.4.r2/include/trace/events/fastrpc.h). This is probably less important. I have less understanding of the other events except those 4 mentioned earlier. Having them may help me understand the fastrpc system better.

**Comment by LalitMaganti** [comment]
The fastrpc_dma_stat event is already parsed at [here](https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/importers/ftrace/ftrace_parser.cc;drc=3d19fbcc09b1b44928639b06cd0b88f735cd988d;l=2396?q=src%2Ftrace_processor%2Fimporters%2Fftrace%2Fftrace_parser.cc)

> So my question is: Would this be an acceptable upstream contribution? Do people think these events can useful as well?

Parsing of additional events would definitely be encouraged and is very much appreciated.
