### ISSUE TITLE
'CPU Time by cluster by process' query incorrect ordering

### ISSUE THREAD

**Issue by troy-lamerton** [google/perfetto#76]
The 'CPU Time by cluster by process' query, under the Metrics and auditors menu, is incorrectly ordering the data.

- Use the example fiddle to load a trace into perfetto: https://jsfiddle.net/g7oktr0q/5/
- Click Metrics and auditors > 'CPU Time by cluster by process'
- Rows should be ordered by `cpu_sec`, but they seem to be randomly ordered
![Screenshot 2020-11-27 at 10 58 33](https://user-images.githubusercontent.com/13446008/100436340-88eb7e00-309f-11eb-9473-dc4ab881932b.png)

I can also reproduce this problem with traces from my own device.
Most recorded traces have this issue, but about 1/5 recorded traces will be ordered correctly by this query (traces from same device).

**Comment by primiano** [comment]
Uhm @LalitMaganti , seems a bit worrying.
Can't tell right now if it's a SQL-query bug, or a SQL-engine bug.
If I look at the query I'd expect naively it should maintain the sorting by cpu_sec after the joins.
TBH I don't remember on top of my head the expected semantic of `group by x,y order by z` but I'd expect order by to happen last?

**Comment by LalitMaganti** [comment]
The bug is definitely in the query. The problem comes from doing a join *after* you do the group by/order by. There's not guarantee that order will be preserved after the join.

The correct query should be something like this:
```
select
  process.name as process,
  thread.name as thread,
  case when cpu/4 = 0 then 'little' else 'big' end as core,
  sum(dur) / 1e9 as cpu_sec
from sched
inner join thread using(utid)
inner join process using(upid)
group by utid, core
order by cpu_sec desc
limit 30;
```

(As an aside, this query is also using a *very old* definition of "core"; the cpu/4 logic is wrong for most devices these days)

I'm OOO until the 7th but will fix when I get back.

**Comment by LalitMaganti** [comment]
Fix is in https://android-review.googlesource.com/c/platform/external/perfetto/+/1518819

**Comment by LalitMaganti** [comment]
Fix has landed so closing this issue :)
