### ISSUE TITLE
Inconsistent properties displayed for counter values

### ISSUE THREAD

**Issue by facewindu** [google/perfetto#760]
See 
<img width="433" alt="image" src="https://github.com/google/perfetto/assets/5922961/a8b230b7-4d4d-4b2f-aef6-5efcb6adacce">

The selected counter value is "45", but the panel below actually displays "value 20" (and associated delta, etc), which is actually the value for the _next_ sample of that counter:

<img width="156" alt="image" src="https://github.com/google/perfetto/assets/5922961/8effed8c-d3eb-482c-88d4-6febbaefa9a6">

**Comment by LalitMaganti** [comment]
Steve: can you PTAL at this?

**Comment by stevegolton** [comment]
@facewindu Thanks for the bug report!

I uploaded a patch: https://android-review.googlesource.com/c/platform/external/perfetto/+/3033754

**Comment by stevegolton** [comment]
The CL has just been landed and should appear on autopush soon
