### ISSUE TITLE
using sql query via python library, throw a exception that no such table: android_startups

### ISSUE THREAD

**Issue by nutshell999** [google/perfetto#761]
as doc descrption, it seems like a metric table created while loading perfetto UI? if i want to use android_startups table in python, what should i do?  

my code:
```
from perfetto.trace_processor import TraceProcessor
tp = TraceProcessor(trace='trace')
qr_it = tp.query('select * from android_startups')
for row in qr_it:
  print(row.startup_id, row.ts, row.ts_end, row.dur, row.package)
```

error output:
    qr_it = tp.query('select * from android_startups')
  File "/home/mi/.local/lib/python3.7/site-packages/perfetto/trace_processor/api.py", line 284, in query
    raise TraceProcessorException(response.error)
perfetto.trace_processor.api.TraceProcessorException: Traceback (most recent call last):
  File "stdin" line 1 col 1
    select * from android_startups
    ^
no such table: android_startups

**Comment by LalitMaganti** [comment]
Please see https://perfetto.dev/docs/analysis/stdlib-docs which explains the perfetto module you should import.
