### ISSUE TITLE
Duplicate queries are being run when loading counter tracks

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#763]
I have a trace where counter track loading is expensive. after collecting a metatrace where i caused a counter track to load by expanding the track, i noticed that one of the expensive queries is being run twice.

<img width="1045" alt="image" src="https://github.com/google/perfetto/assets/77857237/98fd1e9d-bbc4-430c-90a9-49f633f4d9a8">

[metatrace.pftrace.gz](https://github.com/google/perfetto/files/14953895/metatrace.pftrace.gz)

I took a look at the query caching logic here: https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/ui/src/frontend/base_counter_track.ts;l=898-902

From that code it looks like it checks if the query results are in the cache. However, after this check the code then unconditionally re-runs the cached query regardless of if the results were in the cache or not: 

https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/ui/src/frontend/base_counter_track.ts;l=916-927

This appears to be a bug, and likely has an impact on counter track loading time.

**Comment by LalitMaganti** [comment]
@stevegolton can you PTAL at this?

**Comment by stevegolton** [comment]
Hi @cphlipot1,

Thanks for raising this issue.

There's actually a couple of bugs here: we don't use the cached data as you pointed out, but it turns out we also don't store the cache key if we get a cache miss.

The fix is in https://android-review.googlesource.com/c/platform/external/perfetto/+/3041779

**Comment by stevegolton** [comment]
Just landed that CL - should be on autopush shortly.

**Comment by cphlipot1** [comment]
Awesome! Thank you!
