### ISSUE TITLE
process_sort_index support or alternative suggestions

### ISSUE THREAD

**Issue by nikhilgdev** [google/perfetto#764]
Hi,
My team is working on a project that generates a flow of timed events in a system. I am using the trace event format as described here: https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview.
Each of these events is described as a process in the JSON file.

Unfortunately, perfetto UI does not order these processes by start time. It seems to order the processes by 'eventfulness' instead.

As a backup, I figured I would use the process_sort_index metadata item to re-order the processes as needed, however, perfetto UI does not respect that.

I see past issues where implementation of process_sort_index has been shot down. Is there an alternative you could suggest for this? Needing to order the processes chronologically is (I would imagine) a need for many projects adopting this UI.

**Comment by LalitMaganti** [comment]
I don't think there's any suggestion for now. Having arbitrary sorts at the UI level might be something supported at some point but is not a priority. 

Our priority is first features for native Perfetto traces (especially Android system tracing). If our project is used in other ways, we're very happy with that but it's not our focus.

**Comment by LalitMaganti** [comment]
This is now supported in the protobuf trace format: https://perfetto.dev/docs/reference/synthetic-track-event#track-sorting-order

We might also add support for this to the JSON format at some point but it requires signifcantly more work due to interactions with processes: the protobuf one works just on the tracks level, it does not touch processes. 

Closing this out because there is now a semi-reasonable workaround for this.

**Comment by LalitMaganti** [comment]
With https://github.com/google/perfetto/pull/3273 landing, we now support thread_sort_index and process_sort_index keys from JSON. Proto traces are still preferred to be written of course but for those writing JSON traces, it might be a nice quality of life improvement.

**Comment by nikhilgdev** [comment]
This is excellent. Also works for traces generated using Clang since they still generate the trace event file format.
How do we get access to this? I tried to use the canary version of perfetto today with a json trace events file and it didn't respect the process sort index.

**Comment by LalitMaganti** [comment]
We've not pushed to canary yet, it releases once a week. I think it should have released yesterday but didn't. Will check why.

It's available on autopush which you can switch to temporarily if you want to try it at Settings -> Release channel -> Autopush. I would *not* recommend staying on autopush for longer than testing to avoid unnecessarily being broken in the future.
