### ISSUE TITLE
How to update interned data after the first packet has been flushed?

### ISSUE THREAD

**Issue by xiaopi-ouo** [google/perfetto#765]
Hi, thank you for your work
Perfetto is a powerful UI to present core activity so I'm trying to show my custom data  on the UI.
I compiled Perfetto proto file to C++ by myself and found some problem when trying to use interned data (my goal is to reduce the file size as the this post #647 ) 

I new a first packet which defines the interned data and set it just like what the document says. 
```
auto interned_pack = trace.add_packet();
interned_pack->set_sequence_flags(perfetto::protos::TracePacket_SequenceFlags::TracePacket_SequenceFlags_SEQ_INCREMENTAL_STATE_CLEARED);
interned_pack->set_timestamp(0);
interned_pack->set_trusted_packet_sequence_id(1); // an arbitrary id, let it be 1
interned_pack->set_first_packet_on_sequence(true);
```

Then I periodically added serveral packets with the flag TracePacket_SequenceFlags_SEQ_NEEDS_INCREMENTAL_STATE on into the same trusted sequence 1, and serialze them to a file and then clear them. 

```
trace.SerialzeToOstream(&log_file);
trace.Clear();
```

I'm curious about how to update the interned data after the first interned data packet has been destroyed?
Should I issue another packet for that? If so, how to set something like `timestamp` , `first_packet_on_sequence`, `previous_packet_dropped`, `trusted_sequence_id` and `SEQ_INCREMENTAL_STATE_CLEARED`, etc. and can I add a EventName to the new packet's interned data only for unseen event name? (The enter seems yes according to the comment in the [protobuffer code](https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/protos/perfetto/trace/interned_data/interned_data.proto), which says that it will be built up gradually)

**Comment by LalitMaganti** [comment]
> Should I issue another packet for that?

Yes you append another packet with `SEQ_INCREMENTAL_STATE_CLEARED` set and the same `trusted_sequence_id`. The timestamp on a single `trusted_sequence_id` should always go forward so it doesn't matter what the value is as long as it increases.

From this packet onwards, all IIDs will be reset and only newly seen InternedData fields will be considered when looking up iids.
