### ISSUE TITLE
Slow track loading of rate type counters

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#767]
Rate counter tracks are slow to load in the UI. Each track results in 3 expensive queries. There are opportunities for optimization if these queries were merged.

Example trace that reproduces the issue
[large_power_rail_trace.pftrace.gz](https://github.com/google/perfetto/files/15000949/large_power_rail_trace.pftrace.gz)

**Comment by cphlipot1** [comment]
https://android-review.googlesource.com/c/platform/external/perfetto/+/3042576 is one proposed optimization to help address this. It drops the query time for loading the tracks in the above trace from ~50 sec to ~20 sec on an M1 Pro.

CC: @stevegolton

**Comment by LalitMaganti** [comment]
This issue should now be fixed with https://r.android.com/3053123 landing.
