### ISSUE TITLE
Steps necessary for Cuda kernel event tracking.

### ISSUE THREAD

**Issue by nikitablack** [google/perfetto#769]
Hello!
I'm new to Perfetto, I skimmed through the documentation but couldn't find answers for my questions. How can I record Cuda events with the tool? Basically, Cuda events are sort of GPU counters - I create an event, set it directly before and after a kernel, and some time later, after the synchronization, I can read these events to measure a rough kernel time.

**Comment by LalitMaganti** [comment]
We don't have any special support for logging CUDA counters natively in Perfetto and I'm not aware of anyone having done that before here.

If you're looking for a way to convert CUDA traces to Perfetto, have a look at https://perfetto.dev/docs/reference/synthetic-track-event but that wouldn't be something we would be doing.
