### ISSUE TITLE
NDEBUG builds of traced should work with both DEBUG and NDEBUG clients

### ISSUE THREAD

**Issue by batesj** [google/perfetto#77]
Based on discussions with Primiano and local testing, it does seem to be the case that a NDEBUG build of traced works fine with DEBUG producer clients. However, we currently get this warning:

[547.767] ducer_ipc_service.cc:95 The producer and the service binaries are built using different DEBUG/NDEBUG flags. This will likely cause crashes.

Can we change this so that there's only a warning with a DEBUG build of traced? Or alternatively, is it possible to move the debug memory test code into a unit or integration test or behind a custom build macro like RUNTIME_TEST?

**Comment by chromy** [comment]
Should be fixed as of https://android-review.googlesource.com/c/platform/external/perfetto/+/1540066. The fix will be in the v12 release.
