### ISSUE TITLE
After converting to systrace, the customized log cannot be saved.

### ISSUE THREAD

**Issue by TeedyBera** [google/perfetto#771]
Hi,

I tried adding a custom log to the block event, for example:

@@ -82,6 +83,8 @@ TRACE_EVENT(block_rq_requeue,
               __field(  unsigned int, ioprio_class            )
               __field(  unsigned int, ioprio_value            )

       TP_printk("%d,%d %s (%s) %llu + %u %s,%u [%d]",
                  MAJOR(__entry->dev), MINOR(__entry->dev),
                  __entry->rwbs, __get_str(cmd),
                 (unsigned long long)__entry->sector, __entry->nr_sector,
                 __print_symbolic(__entry->ioprio_class, IOPRIO_CLASS_STRINGS),
                 __entry->ioprio_value, 0)

then i found these logs were not saved after converting perfetto to systrace.

Is it because it was filtered out during the crawling process?

If so, is there a way to save these logs in perfetto?

thanks

**Comment by primiano** [comment]
I think what you are missing is the fact that you need to update perfetto's knowledge about the new block_eq_requeue event with your changes.

See https://perfetto.dev/docs/contributing/common-tasks#add-a-new-ftrace-event and https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/protos/perfetto/trace/ftrace/block.proto;l=110?q=BlockRqRequeueFtraceEvent%20f:perfetto

**Comment by TeedyBera** [comment]
Thank you very much!
