### ISSUE TITLE
BatchTraceProcessor FileNotFoundError: [Errno 2] No such file or directory: '.local/share/perfetto/prebuilts/trace_processor_shell.tmp' on first run

### ISSUE THREAD

**Issue by Sabaev** [google/perfetto#773]
**Description**
FileNotFoundError is raised when attempting the first run of BatchTraceProcessor with over 100 perfetto-trace files on a linux or MacOS.

**Environment**
- Python version: Python 3.9.6
- Perfetto version: 0.7.0
- MacOs 13.5 

**Steps to Reproduce**
- pip3 install perfetto
- enable verbose in TraceProcessorConfig
- run `BatchTraceProcessor` with over 100 perfetto-trace files

```python
config = TraceProcessorConfig(verbose=True)
batch_config = BatchTraceProcessorConfig(tp_config=config)
with BatchTraceProcessor(files, batch_config) as btp:
      batch.query(...)
 ```
    
**Expected behavior**
BatchTraceProcessor successfully loaded over 100 traces the first time it was loaded.

**Actual behavior**
I get below exception on first boot
```
Exception : Trace processor failed to start. Try rerunning with verbose=True in TraceProcessorConfig for more detailed information and file a bug at https://goto.google.com/perfetto-bug or https://github.com/google/perfetto/issues if necessary. 
```

**Possible Cause**
A possible race condition on `tmp_path` file in the `perfetto_prebuilt` function, specifically at https://github.com/google/perfetto/blob/main/python/perfetto/prebuilts/perfetto_prebuilts.py#L86.
due to several loading at https://github.com/google/perfetto/blob/main/python/perfetto/prebuilts/perfetto_prebuilts.py#L77

**Other Signs**
Two curl progress bars appear before the stack trace in the console.

**Stack Trace**
```
######################################################################## 100.0%
######################################################################## 100.0%
Traceback (most recent call last):
  File "/tmp/trace_processor_python_api", line 294, in <module>
    run_perfetto_prebuilt(TRACE_PROCESSOR_SHELL_MANIFEST)
  File "/tmp/trace_processor_python_api", line 286, in run_perfetto_prebuilt
    bin_path = get_perfetto_prebuilt(manifest)
  File "/tmp/trace_processor_python_api", line 279, in get_perfetto_prebuilt
    return download_or_get_cached(
  File "/tmp/trace_processor_python_api", line 249, in download_or_get_cached
    os.chmod(tmp_path, 0o755)
```

**posible solution**
Running `get_perfetto_prebuilt` just once fixed an issue I encountered. I run `get_perfetto_prebuilt` right before BatchTraceProcessorConfig.
You can review the function at https://github.com/google/perfetto/blob/main/python/perfetto/prebuilts/perfetto_prebuilts.py#L90

**Comment by LalitMaganti** [comment]
Can you please try https://r.android.com/3063233 which I believe should fix this issue?

**Comment by Sabaev** [comment]
Hi. It doesn't work. https://r.android.com/3063233 
The issue is that each thread uses its own `needs_download`, so even after one thread downloads the file and releases the lock, the next thread still `sees needs_download` as `True` and tries to download again.
