### ISSUE TITLE
Poll SwapPss in /proc/smaps_rollup

### ISSUE THREAD

**Issue by funfoolsuzi** [google/perfetto#777]
Following up on a previous issue: https://github.com/google/perfetto/issues/490. There is option to poll `/proc/smaps_rollup` in the process stats probe, but a few fields were left untracked. I'd like to include all available fields especially `SwapPss` while `scan_smaps_rollup` is set to true.
Do you think it is a acceptable feature? And if so, if you don't have bandwidth with this can I make a patch for this?

**Comment by LalitMaganti** [comment]
I think this should be fine to add if we're already polling the file and it's just a different field we're not reading.

**Comment by funfoolsuzi** [comment]
@LalitMaganti I noticed there is a CI failure in my change: https://android-review.googlesource.com/c/platform/external/perfetto/+/3087006 and I couldn't repro this issue by building the UI.
It looks like it's failure in ts code but my change doesn't touch any ts code.

Any suggestion on resolving the CI failure?

**Comment by LalitMaganti** [comment]
It was a preexisting failure, I rebased your CL and reran the CI.
