### ISSUE TITLE
Compile trace protobuf for Python

### ISSUE THREAD

**Issue by LinZhihao-723** [google/perfetto#779]
Hi, I'm trying to write a Python script to convert some JSON data into perfetto traces. From the doc it seems like protobuf format is preferred, but there's no official Python API to generate the trace. If I need to manually compile the proto files to Python, is there any formal doc how I should do that? Seems like I need to have everything under `https://github.com/google/perfetto/tree/main/protos/perfetto/trace` compiled?

**Comment by LalitMaganti** [comment]
While we don't provide bindings/libraries to generate the Python trace file (% if you build us using Bazel), we do provide an amalgamated .proto file which contains all of our protos which you can drop into any project to generate bindings for. This can be found at https://github.com/google/perfetto/blob/main/protos/perfetto/trace/perfetto_trace.proto

You can follow the official instrutions (https://protobuf.dev/getting-started/pythontutorial/) to turn this .proto file into Python modules which you can use.

**Comment by LinZhihao-723** [comment]
Thanks!
