### ISSUE TITLE
The Android log was truncated "..." with fixed width of the display area

### ISSUE THREAD

**Issue by phding** [google/perfetto#780]
In UI, the android log seems to be truncated from
```
StreamInPrimary: 4784: local : handle (7e) format(0x1) sample_rate(48000) channel_mask(0xc) devices(0x80000004) 
```

To 

```
StreamInPrimary: 4784: local : handle (7e) format(0x1) sample_rate(48000) channel_mask(0xc) devices...
```
Where the screen still have plenty of space for visualizing the logs. The message is now fixed width https://github.com/google/perfetto/blame/1f233121a8e6ce9b91e111aeff5118f9efb48823/ui/src/core_plugins/android_log/logs_panel.ts#L110
<img width="1001" alt="image" src="https://github.com/google/perfetto/assets/1287510/b4556401-5aae-4fbe-8068-0fa8e3785b29">

I have to go back to use v42 where the message is not truncated.

@stevegolton could we make it easy to adjust based on the screen size instead of fix size?

**Comment by stevegolton** [comment]
Thanks for raising the issue - we have a fix incoming

https://android-review.googlesource.com/c/platform/external/perfetto/+/3081309
