### ISSUE TITLE
How do I avoid counters from displaying as deltas?

### ISSUE THREAD

**Issue by jaywonchung** [google/perfetto#782]
<img width="706" alt="Screenshot 2024-05-12 at 2 01 24 PM" src="https://github.com/google/perfetto/assets/29395896/3dac361f-3ad4-4a93-96e7-37aed61e6111">

I have multiple counter types that I tracked and formatted into the chrome tracing JSON format.
Most counters are displayed as raw values, which is what I want, but somehow two of the counters that have "power" in their names are shown as deltas.
Is there a way to change this to raw counter values instead of deltas?

Thank a lot.

**Comment by jaywonchung** [comment]
I just randomly tried replacing `"power"` with `"pwr"` in the name of the counter and now it's displaying as raw counters. Regardless, I think the user should be able to choose between deltas or raw values.

**Comment by chromy** [comment]
I believe the default mode is currently applied here: https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/ui/src/core_plugins/counter/index.ts;l=54?q=power%20f:perfetto%2Fui%2Fsrc&ss=android%2Fplatform%2Fsuperproject%2Fmain

**Comment by stevegolton** [comment]
Unfortunately the UI is oriented towards Android tracing, and thus certain things like this are currently hard coded. If we remove this feature, a lot of folks would be disappointed.

We are however actively working on a way to remedy the problem by providing a more un-opinionated "core" with the ability for users to customize their workspaces with a combination of plugins & settings. While this is mainly aimed at customizing the loadout tracks & groups, the track options like this are likely be included as well.

I'm afraid we don't have any more details to share or a concrete timescale yet, but I'll try to update this issue when we do.

**Comment by jaywonchung** [comment]
Sounds good, thanks for your reply. If I want to fork the repo to change that part of the code, is there perhaps some guide on how to do a local deployment?

**Comment by LalitMaganti** [comment]
Actually just spoke with Steve: we used to have an option to change between normal/delta counters but that option is now gone. The logic for that still exists so we should fix that.

As for changing the defaults, yeah that might be a bit more involved but the fix for now is just to add the functionality to change away from rate back.

**Comment by LalitMaganti** [comment]
https://r.android.com/c/3091727/1 should expose the hidden menu items.

**Comment by jaywonchung** [comment]
<img width="289" alt="Screenshot 2024-05-20 at 11 15 28 PM" src="https://github.com/google/perfetto/assets/29395896/cd03568a-336b-4603-81d3-7a97b7d124a0">

Works well, thanks! Leaving screenshot for others just in case.
