### ISSUE TITLE
The recent updates seem to not support regular expression search.

### ISSUE THREAD

**Issue by wangkai0055** [google/perfetto#783]
The recent updates seem to not support regular expression search.

**Comment by wangkai0055** [comment]
SQL error: Traceback (most recent call last):
  File "stdin" line 1 col 1
    SELECT ts, dur, name FROM slice WHERE name REGEXP '.*vacCreate.*'
    ^
Value has to be a string

So I have to use LIKE, but our script also needs to be updated accordingly.

**Comment by aMayzner** [comment]
It doesn't repro on autopush. Can you tell me what trace processor version you are using? Or are you building from the HEAD?

**Comment by wangkai0055** [comment]
v44.0-257a02990
=======================================================
Query result (406 rows) - 62.9ms
SELECT * FROM slice WHERE name like '%xxxcost%'
=======================================================
SQL error: Traceback (most recent call last):
  File "stdin" line 1 col 1
    SELECT ts, dur, name FROM slice WHERE name REGEXP '.*xxxcost.*'
    ^
Value has to be a string
=======================================================

**Comment by aMayzner** [comment]
It should be fixed now.
