### ISSUE TITLE
still racy prebuilt download

### ISSUE THREAD

**Issue by Sabaev** [google/perfetto#786]
Hi. It doesn't work. https://r.android.com/3063233 
The issue is that each thread uses its own `needs_download`, so even after one thread downloads the file and releases the lock, the next thread still `sees needs_download` as `True` and tries to download again.

_Originally posted by @Sabaev in https://github.com/google/perfetto/issues/773#issuecomment-2111825602_

**Comment by LalitMaganti** [comment]
That's not accurate though: you are missing the part where the actual `needs_download` variable is changed inside the body of the locked section using the following:
```
    # Avoid recomputing the SHA-256 on each invocation. The SHA-256 of the last
    # download is cached into file_name.sha256, just check if that matches.
    if os.path.exists(bin_path) and os.path.exists(sha256_path):
      with open(sha256_path, 'rb') as f:
        digest = f.read().decode()
        if digest == sha256:
          needs_download = False
```

That should take care of any races.

**Comment by Sabaev** [comment]
You're right.
But the lock is only working within a single process, but since multiple processes are trying to access the same resource, the lock isn't effective. I've seen in the activity monitor that multiple instances of trace_processor_shell are attempting to load the resource simultaneously. 

Steps to Reproduce:
remove preloaded files froml ocal/share/perfetto/prebuilts
run butch processor with 100+ traces. 
I use macbook pro m2 max with 12 cores

<img width="939" alt="Screenshot 2024-05-15 at 13 40 37" src="https://github.com/google/perfetto/assets/25320938/4630fbcb-2912-495c-bc97-a4b1b68c9fe9">
<img width="1084" alt="Screenshot 2024-05-15 at 13 56 28" src="https://github.com/google/perfetto/assets/25320938/6c543f34-cc04-4a75-8d04-6696c148e1a1">

**Comment by LalitMaganti** [comment]
Unless you are overriding the executor, the executor used by the Python API is a ThreadPoolExecutor *not* a ProcessPoolExecutor so there shouldn't be multiple Python processes involved, only multiple threads.

The subprocesses you see are at the shell level and totally unrelated to all this code.

**Comment by Sabaev** [comment]
After that, I am not sure. I simply ran the command:
`pip3 install perfetto --no-cache-dir`
The version of perfetto is the same as it was a week ago, `0.7.0`.

But the link to the file with the error opens the file that already has the `DOWNLOAD_LOCK` added. Additionally, `perfetto-luci-artifacts/v45.0` is being downloaded instead of `perfetto-luci-artifacts/v44.0` as it was a week ago.
It looks like the changes have indeed been made.
May be some problems with caches.
 
I have attached screenshots.
<img width="1104" alt="Screenshot 2024-05-15 at 14 37 13" src="https://github.com/google/perfetto/assets/25320938/99f3f6c1-af15-4d58-82af-36ff90fd58be">
<img width="741" alt="Screenshot 2024-05-15 at 14 38 17" src="https://github.com/google/perfetto/assets/25320938/4a5afec8-1b4f-4d85-a808-5330c43670fb">

**Comment by LalitMaganti** [comment]
Can you try adding a `os.sync()` just before the finally? I wonder if the problem is that there is a kernel race going on between one thread writing the sha file and the other thread reading it.

**Comment by Sabaev** [comment]
Done. 
The trace_processor_python_api file appears to have been created using an "Amalgamator" tool from the repository. I modified trace_processor_python_api to identify the process ID, and it revealed that the code is running in separate processes. I also attempted to use os.sync(), but it was unsuccessful, even after adding it to trace_processor_python_api.

I have attached screenshots.
<img width="814" alt="Screenshot 2024-05-15 at 16 44 39" src="https://github.com/google/perfetto/assets/25320938/a82748fa-955f-41ed-b3c6-6393270c3baf">
<img width="1060" alt="Screenshot 2024-05-15 at 16 45 19" src="https://github.com/google/perfetto/assets/25320938/069c9079-8a80-4d36-be4f-0e9e9d51f05f">

**Comment by LalitMaganti** [comment]
`getpid` on Linux returns a thread id not a process id so that doesn't rule out anything. You want `os.getpgrp()` actually.

**Comment by Sabaev** [comment]
I added "hex(id(DOWNLOAD_LOCK))". And it became clear that DOWNLOAD_LOCK is a different object each time when download_or_get_cached is called within the context of the same program execution.

I have attached screenshots where I am running the script with over 100 traces.
<img width="1041" alt="Screenshot 2024-05-15 at 22 46 54" src="https://github.com/google/perfetto/assets/25320938/78511362-98ca-4b90-9be4-105a891a26f3">
<img width="580" alt="Screenshot 2024-05-15 at 22 47 04" src="https://github.com/google/perfetto/assets/25320938/488ab51e-7722-44be-8f61-497fde99a590">

**Comment by LalitMaganti** [comment]
OK I understand the problem now: the fact that we use a thread executor is a total red herring. The actual download is happening in the trace_processor script which happens *after* the subprocess execution so there are mutliple processes at play.

I have an idea on fixing this, will try and get to this in the next couple of days.

**Comment by LalitMaganti** [comment]
The above should now fix this.
