### ISSUE TITLE
Question about the perfetto UI

### ISSUE THREAD

**Issue by cos120** [google/perfetto#789]
Hello folks!
Thanks for the great project. I have some question about perfetto ui.

I am using the legacy chrome json format in perfetto for pytorch profiling, the trace file is generate by python. I noticed that perfetto can highlight releated trace spans. How can i use it for json format? If json format do not support it, can i use c++ sdk for generate binary trace file for the highlight feature?

We are focusing on distributed profiling, there are lots of process groups so i really want to use highlight feature! Thanks.

And i noticed binary file is much smaller than json file.

One more question about c++ sdk, I have some trace data which is not generated by perfetto tracing tools, does perfetto offers c++ api to generate trace file? Or I just use the proto define and fill it then serializing it?

![image](https://github.com/google/perfetto/assets/6364761/3bd1c3d3-0ba8-4b13-8219-f6f389b59fd0)

**Comment by primiano** [comment]
>  I noticed that

![image](https://github.com/google/perfetto/assets/7137473/09347044-1503-4793-a2c9-983e0f8f27f4)

**Comment by LalitMaganti** [comment]
> I noticed that perfetto can highlight releated trace spans

Can you please clarify what you mean by this? Your screenshot simply shows some pinned tracks and an empty selection: I don't understand what you mean by "related trace spans". 

> And i noticed binary file is much smaller than json file.

Yeah this is very WAI: the JSON format is much much less efficient in encoding than the protobuf format by design.

**Comment by cos120** [comment]
> > I noticed that
> 
> ![image](https://private-user-images.githubusercontent.com/7137473/331000535-09347044-1503-4793-a2c9-983e0f8f27f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjEwNjQsIm5iZiI6MTcxNTgyMDc2NCwicGF0aCI6Ii83MTM3NDczLzMzMTAwMDUzNS0wOTM0NzA0NC0xNTAzLTQ3OTMtYTJjOS05ODNlMGY4ZjI3ZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMDA1MjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWI5YzMzMzc0ZDc3NmRmMmFjNzJkNmMxMTA5NTBkZDMwYjI3MTE1ZmJkNDcyNDE2OTUwNmM2NTQ2MzJkNzhmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yyLwbCLZZmgERXBoNIT5e9dDSKPE1vQ8GqrptJjfoCE)

I press command+enter which is newline on my editor, when I realize it, it has published 😱

**Comment by cos120** [comment]
> > I noticed that perfetto can highlight releated trace spans
> 
> Can you please clarify what you mean by this? Your screenshot simply shows some pinned tracks and an empty selection: I don't understand what you mean by "related trace spans".
> 
> > And i noticed binary file is much smaller than json file.
> 
> Yeah this is very WAI: the JSON format is much much less efficient in encoding than the protobuf format by design.

My bad.
I will illustrate it by image.
In this trace file, there 8 process, [0,1,4,5] is a group1 and [2,3,6,7] is group2.
I want when i hover on span of any process in group1, all spans in process [0,1,4,5] will highlight, like the gif in https://perfetto.dev/docs/visualization/perfetto-ui shows.
![image](https://github.com/google/perfetto/assets/6364761/508ae2e2-a0a4-4cb2-bcad-a0ee7bf99b84)

**Comment by LalitMaganti** [comment]
That's a special property of scheduling tracks only and cannot be replicated with userspace slices on either the proto or JSON format. 

@stevegolton can comment further but seems very unlikely that we'd be looking to add any similar feature in the short to medium term for userspace slices b

**Comment by stevegolton** [comment]
The track highlighting differs depending on the track.

The only type of "bulk" highlighting we have on non-scheduling tracks (like in your latest screenshot) is that all tracks with the same title are highlighted. This is only on certain track impls, but I think that's what you're seeing.

On scheduling tracks as in your first screenshot and the gif on https://perfetto.dev/docs/visualization/perfetto-ui, all slices are grayed out apart from slices that originate from the same utid / pid, with slices from the same utid receiving a more pronounced highlight than slices just from the same pid.

As @LalitMaganti mentioned, there is no way to configure this from the trace aside from setting the slice titles to the same thing which probably isn't desirable.

**Comment by cos120** [comment]
@stevegolton thanks. So can i just generate "scheduling tracks" as my trace span and set them with same tid/pid or someother property to archive my goal?

**Comment by stevegolton** [comment]
Possibly, though scheduling tracks are designed to represent what's scheduled to run on each CPU at any given moment, so they have other limitations and are represented differently in the UI compared to userspace slices - e.g. limited number of tracks (one per CPU), no nested slices, different details panel, etc.

If they can be repurposed for your use case then that's great, but it might be a bit of a hack.

See https://perfetto.dev/docs/data-sources/cpu-scheduling

**Comment by cos120** [comment]
> Possibly, though scheduling tracks are designed to represent what's scheduled to run on each CPU at any given moment, so they have other limitations and are represented differently in the UI compared to userspace slices - e.g. limited number of tracks (one per CPU), no nested slices, different details panel, etc.
> 
> If they can be repurposed for your use case then that's great, but it might be a bit of a hack.
> 
> See https://perfetto.dev/docs/data-sources/cpu-scheduling

thanks, i will try it :)

**Comment by cos120** [comment]
Hi, all.

I have another issue. I have 2 spans, but they are very close, looks like perfetto ui merge them into longer one, but another one is displayed as 1ns.


Some spans data which cause merging spans.
| span name    | start | duration |
| -------- | ------- | ------|
|matmul_bmnk_1_8192_33936_16380_ |1717052741134262 |13303|
|matmul_bmnk_1_8192_16380_33936_ |1717052741147574 |13901|

The timeline displayed in perfetto ui.
![image](https://github.com/google/perfetto/assets/6364761/e84bc7b0-4b0d-4f8e-b4c5-782b73e97ff9)

I minus 10us for each duration in spans, it looks good, but i want to known how can i solve it in right way.

Thanks.

**Comment by LalitMaganti** [comment]
Spans cannot be overlapping on a single track. Not sure what your are emitting at the proto level at this point but if you are emitting track event (https://perfetto.dev/docs/reference/synthetic-track-event) then you want to emit each event on an async track with the same name so the UI would merge them together.

**Comment by cos120** [comment]
> Spans cannot be overlapping on a single track. Not sure what your are emitting at the proto level at this point but if you are emitting track event (https://perfetto.dev/docs/reference/synthetic-track-event) then you want to emit each event on an async track with the same name so the UI would merge them together.

I am using sync track, all spans are in same thread, may be there are some problem with the precision of my data. Thanks

**Comment by cos120** [comment]
Sorry to bother again.

I am using protobuf to generate my own trace, and i use interning data already. But i have lots of spans, and i merge the protobuf message in python, it eat lots of memory. The origin data size is about 2.6GiB, so the timeline maybe 3GiB, I noticed perfetto has util to [split traces](https://perfetto.dev/docs/visualization/large-traces), i want to known how can i generate partial of track events and use trace_processor to visualize it in UI? Is there any c++ interface of trace_processor?

**Comment by LalitMaganti** [comment]
>  i merge the protobuf message in python, it eat lots of memory. 

Instead of creating a single giant Trace message, I'd suggest creating a trace protobuf of a few thousand slices, flushing that to disk, clearing the trace protobuf and repeating. Trace messages can be directly concatenated together without any extra work.

> I noticed perfetto has util to [split traces](https://perfetto.dev/docs/visualization/large-traces),

Trace processor is not a utility to split traces, it is purely for analysing traces and can be used as the backend of the UI to visualize large traces.

> Is there any c++ interface of trace_processor?

Yes as mentioned in our docs (https://perfetto.dev/docs/analysis/trace-processor) but I'm pretty sure it's *not* what you want if you're struggling with putting together large trace files.

**Comment by cos120** [comment]
> Instead of creating a single giant Trace message, I'd suggest creating a trace protobuf of a few thousand slices, flushing that to disk, clearing the trace protobuf and repeating. Trace messages can be directly concatenated together without any extra work.

So once I create several protobuf binary files, how can perfetto ui load multiple binary files into same tab?

> Trace processor is not a utility to split traces, it is purely for analysing traces and can be used as the backend of the UI to visualize large traces.

My trace is huge, so can i just split repeated messages and use trace processor to visualize large traces?

**Comment by LalitMaganti** [comment]
> So once I create several protobuf binary files, how can perfetto ui load multiple binary files into same tab?

Just concatenate the protobufs into the same file by appending one chunk of protobuf after another. Trace protobufs can be freely concatenated at the byte level.

> so can i just split repeated messages and use trace processor to visualize large traces?

Sure but only in different UI instances. There is no way to split a trace into multiple files and then visualize everything at the same time: you should just generate the file in a merged way in the first place.

**Comment by cos120** [comment]
Thanks your quick reply. 

Let me clarify my process and please help me to check my understand, thanks!


> Just concatenate the protobufs into the same file by appending one chunk of protobuf after another. Trace protobufs can be freely concatenated at the byte level.


I am using multiprocessing to processing each data into `Trace`. And the proto define in perfetto is
```protobuf
message Trace {
  repeated TracePacket packet = 1;

  // Do NOT add any other field here. This is just a convenience wrapper for
  // the use case of a trace being saved to a file. There are other cases
  // (streaming) where TracePacket are directly streamed without being wrapped
  // in a Trace proto. Nothing should ever rely on the full trace, all the
  // logic should be based on TracePacket(s).
}
```
And at last, i will merge multiple `Trace` into one `Trace`, this merge processing eats lots of memory. As you mentioned, I just SerializeToString each `Trace` and flush them to disk one by one, no need to merge into one large `Trace`?

**Comment by LalitMaganti** [comment]
> As you mentioned, I just SerializeToString each Trace and flush them to disk one by one, no need to merge into one large Trace?

Correct.
