### ISSUE TITLE
Perfetto is crashed

### ISSUE THREAD

**Issue by miraclemore** [google/perfetto#791]
After update to perfetto version v44，some move behavior trigger crash

Pls refer to the below steps to reproduce.
1. open any trace file.
2. move any track row before CPU0 task row

Logs:
UI: https://ui.perfetto.dev/v44.0-c7da51a07

Error: Failed assertion
 - assertTrue (frontend_bundle.js:4635:16)
 - assertFalse (frontend_bundle.js:4640:6)
 - PanelContainer.renderPanel (frontend_bundle.js:500928:36)
 - PanelContainer.renderTree (frontend_bundle.js:500939:22)
 -  (frontend_bundle.js:500937:213)
 - Array.map (<anonymous>)
 - PanelContainer.renderTree (frontend_bundle.js:500937:186)
 -  (frontend_bundle.js:500943:67)
 - Array.map (<anonymous>)
 - PanelContainer.view (frontend_bundle.js:500943:40)

Trace: not available (FILE). Provide repro steps.
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Referrer:

**Comment by LalitMaganti** [comment]
I can repro this on stable and autopush. Specifically, a thread/process scoped track needs to be drag-dropped in to the global section. There's a big delay followed by the crash.

Filed b/341429501 to track internally.

**Comment by miraclemore** [comment]
Yeah, whatever stable or autopush, both will crash if u drag the track to the first one.
Is there any temporay method to work around that ?
@LalitMaganti

**Comment by LalitMaganti** [comment]
Not that I'm aware of apart from just not dragging the track.

**Comment by stevegolton** [comment]
Can repro, will take a look. Probably a good candidate for cherry picking once we find a fix
