### ISSUE TITLE
Feature request: support serving Perfetto UI resources from a different directory

### ISSUE THREAD

**Issue by saraadams** [google/perfetto#794]
I'd like to host the Perfetto UI, but the code seems to currently only support serving it from the root path.

It'd be nice to be able to configure the generated code to e.g. serve the resources from https://www.example.com/perfetto_ui

Edit:
Serving the `index.html` from `https://www.example.com/perfetto_ui/index.html` works, but from `https://www.example.com/perfetto_ui` does not.

**Comment by saraadams** [comment]
I've sent https://android-review.googlesource.com/c/platform/external/perfetto/+/3094811 with a proposed implementation.

**Comment by LalitMaganti** [comment]
I've sent to Primiano to take a look at as Steve is out for the rest of the week.

**Comment by primiano** [comment]
I don't understand, this seems to work already as you decribe.
It's precisely how the UI artifacs generated by ui.perfetto.dev work

Concrete example:
https://storage.googleapis.com/perfetto-ci-artifacts/20240523110307--cls-3098498-4--ui-clang-x86_64-release/ui/index.html

The existence of that link contraddicts the claim made in this bug.
What am I missing?

**Comment by saraadams** [comment]
> Concrete example: https://storage.googleapis.com/perfetto-ci-artifacts/20240523110307--cls-3098498-4--ui-clang-x86_64-release/ui/index.html
> 
> The existence of that link contraddicts the claim made in this bug. What am I missing?

Sorry, my initial description didn't quite capture the problem.

The problem occurs if you don't serve `index.html` from `/path/index.html` but instead from `/path`. In that case, the relative path doesn't resolve as desired.

**Comment by saraadams** [comment]
Additionally, there could be uses cases where you want to serve the files from a different path entirely, such as from `www.example.com/assets/perfetto`, i.e. locate the versioned directory in a different location than the `index.html`.

Do these sound like valid use cases to you?

**Comment by primiano** [comment]
Yeah I understand now, discussed in the CL.
Sorry this one case seems too niche. If you can't really have /perfetto/ with a trailing / (which would JustWork) maybe just have a downstream patch / your own index.html?
