### ISSUE TITLE
Why does The perfetto UI display The Trace Processor instance on X.X.X. x:9002 is too old?

### ISSUE THREAD

**Issue by yeziyang9173** [google/perfetto#796]
![image](https://github.com/google/perfetto/assets/84683426/bbed7102-2a81-42f5-b3e9-5b00499b967d)

I uploaded a large file on another host and wanted to trace this json, which I also did
https://perfetto.dev/docs/visualization/large-traces
But when I run the perfetto UI on my host, I get a message that the version does not match

**Comment by LalitMaganti** [comment]
Can you please provide some details on how you're using Perfetto?
* Are you using ui.perfetto.dev? If so what release track? (stable, canary, autopush)
* Are you using the trace processor script at https://get.perfetto.dev/trace_processor? If so, did you try and redownload? If not, did you compile it yourself?

The UI version and TP version both look very strange, they are missing commit shas and the trace processor version info is missing altogether which is unexpected if you are using our prebuilts.

**Comment by LalitMaganti** [comment]
If you are building the UI yourself, you also need to build trace processor shell from the same commit sha and use that instead.

See https://perfetto.dev/docs/contributing/getting-started#quickstart for build instrucitons.

From the Perfetto perspective, the trace processor prebuilts we provide only work with ui.perfetto.dev, they cannot possibly work with other UI builds.

**Comment by yeziyang9173** [comment]
> If you are building the UI yourself, you also need to build trace processor shell from the same commit sha and use that instead.
> 
> See https://perfetto.dev/docs/contributing/getting-started#quickstart for build instrucitons.
> 
> From the Perfetto perspective, the trace processor prebuilts we provide only work with ui.perfetto.dev, they cannot possibly work with other UI builds.

Is there any way I can build my UI and TC locally? I want to build locally so that I can read the json file of my local host B

**Comment by LalitMaganti** [comment]
> Is there any way I can build my UI and TC locally? I want to build locally so that I can read the json file of my local host B

No CORS will disallow you from making requests to any other host than localhost. You can use SSH port forwarding to make the remote trace processor appear as if it's on localhost with a remote trace processor (that's what we do internally at Google)

TBH if you're using JSON though, is there any reason you are not just using ui.perfetto.dev and just opening the file directly though? JSON traces cannot reasonably be big enough to OOM the UI.

Note that if you use ui.perfetto.dev, traces never leave your browser, there is no "server side component" to the Perfetto UI and may be far eaiser than whatever thing you are attempting to do.

**Comment by yeziyang9173** [comment]
> > Is there any way I can build my UI and TC locally? I want to build locally so that I can read the json file of my local host B
> 
> No CORS will disallow you from making requests to any other host than localhost. You can use SSH port forwarding to make the remote trace processor appear as if it's on localhost with a remote trace processor (that's what we do internally at Google)
> 
> TBH if you're using JSON though, is there any reason you are not just using ui.perfetto.dev and just opening the file directly though? JSON traces cannot reasonably be big enough to OOM the UI.
> 
> Note that if you use ui.perfetto.dev, traces never leave your browser, there is no "server side component" to the Perfetto UI and may be far eaiser than whatever thing you are attempting to do.

Thank you for your comments.
I deployed in this way to achieve faster loading speed and add some new content.
Could you explain the ‘build trace processor shell from the same commit sha‘?
I don't know 'the same commit sha', do I need to upload the code to github? So I can build my TP

**Comment by LalitMaganti** [comment]
> I deployed in this way to achieve faster loading speed and add some new content.

I can't possibly understand how you can get faster loading speed by having your own UI instance given everything runs in the browser anyway but OK.

> Could you explain the ‘build trace processor shell from the same commit sha‘?

Sorry but this is getting into the realm of general software engineering using Git not about Perfetto so I don't think it's really our responsibility to help on this part. By commit sha I mean you need to checkout the same commit that you built the UI with and build trace processor at that revision.

**Comment by primiano** [comment]
Documentation about how to build perfetto is available here https://perfetto.dev/docs/contributing/build-instructions

In general, as @LalitMaganti pointed out, we don't offer consultancy on how to check-out / build / use git etc.
