### ISSUE TITLE
ToTimecode function is not work properly 

### ISSUE THREAD

**Issue by altria-polaris** [google/perfetto#797]
It seems to be a bug in hh part when I try to use ToTimecode in Perfetto SQL.
https://github.com/google/perfetto/blob/main/src/trace_processor/perfetto_sql/intrinsics/functions/clock_functions.h#L191
`int64_t hh = mm % 60;`
It should be '/' operator rather than '%' to calculate hh.

Some test examples:
TO_TIMECODE(**3600123456789**)
return   **00:00:00 123 456 789**
but expected is **01:00:00 123 456 789**

TO_TIMECODE(**3599123456789**)
return   **59:59:59 123 456 789**
but expected is **00:59:59 123 456 789**

**Comment by LalitMaganti** [comment]
Yes seems like a real bug. @aMayzner can you PTAL?
