### ISSUE TITLE
Empty auxiliary tracks show up as crashed? 

### ISSUE THREAD

**Issue by lednakashim** [google/perfetto#799]
So empty tracks have two odd behaviors during rendering

1. Seems that the duration isn't inferred from the parent track causing it show up as crashed
2. Not automatically hidden
Wondering if we could have either of those two behaviors so that the perfetto writing software doesn't need to worry about pruning empty tracks etc

<img width="862" alt="Screenshot 2024-05-26 at 3 52 15 PM" src="https://github.com/google/perfetto/assets/1728530/578424c1-5e22-4d65-b10a-7b14ce7823fa">

You will need to change the extension to .proto
[sequence_test.proto.json](https://github.com/google/perfetto/files/15448727/sequence_test.proto.json)

**Comment by LalitMaganti** [comment]
We're missing the joins in track_decider (and the corresopnding plugins) for counter_tracks that we have slice_tracks where we ensure there is at least one row for every track (e.g. [1]). Will send something to fix this.

[1] https://github.com/google/perfetto/blob/e1634e2743438b14e143026b46f857461ff14b99/ui/src/controller/track_decider.ts#L1003

**Comment by LalitMaganti** [comment]
https://r.android.com/3106003 fixes
