### ISSUE TITLE
perfetto_cmd.cc:840

### ISSUE THREAD

**Issue by wingyippp** [google/perfetto#8]
```Failed to invoke perfetto: perfetto_cmd.cc:840      Failed to open /data/misc/perfetto-traces/profile-shell. If you get permission denied in /data/misc/perfetto-traces, the file might have been created by another user, try deleting it first. (errno: 2, No such file or directory)```

Got this error when running the cmd "tools/heap_profile [process_name]".
My device is not rooted, so I cannot access `/data/`.

**Comment by primiano** [comment]
@wingyippp , what happens if you do `adb shell rm /data/misc/perfetto-traces/profile-shell`
@segfaulthunter maybe the script should use unique file names (and delete them after pull)?

**Comment by wingyippp** [comment]
> @wingyippp , what happens if you do `adb shell rm /data/misc/perfetto-traces/profile-shell`
> @segfaulthunter maybe the script should use unique file names (and delete them after pull)?

adb shell rm /data/misc/perfetto-traces/profile-shell
rm: /data/misc/perfetto-traces/profile-shell: No such file or directory

Then run the cmd again "tools/heap_profile [process_name]", I got the same error show above.

P.S. My device is Android 10.0

**Comment by segfaulthunter** [comment]
Which device are you running on?

Could you try running `adb shell setprop persist.traced.enable 1` and then retrying?

**Comment by wingyippp** [comment]
> Which device are you running on?
> 
> Could you try running `adb shell setprop persist.traced.enable 1` and then retrying?

MY-MB2:perfetto wingyipye$ adb shell setprop persist.traced.enable 1
MY-MB2:perfetto wingyipye$ tools/heap_profile --name [process_name]
Profiling active. Press Ctrl+C to terminate.
You may disconnect your device.

Wrote profiles to /var/folders/s2/_l4q4mv16w3b_lrg1_p636jx49_ckw/T//heap_profile-ElYmfFC (symlink /var/folders/s2/_l4q4mv16w3b_lrg1_p636jx49_ckw/T/heap_profile-latest)
These can be viewed using pprof. Googlers: head to pprof/ and upload them.

It's OK now. Thank you!
My device is Galaxy S9+ (SM-G9650/DS)
