### ISSUE TITLE
How to split a big perfetto trace by given slice names?

### ISSUE THREAD

**Issue by dvdface** [google/perfetto#808]
I want to run a long time performance test, mark scene by scene trace with dedicated name.

for example:
   *  launching_from_standard_launcher
   *  open_folder_on_launcher

then,  I want to split this big perfetto trace by these scene name 

so I can categorize perfetto trace by scenes

finally, I use dedicated trace metric to get click/swipe/zoom in,out latency,    frame metric

then generate a report about test result.

so, my question is how to split perfetto trace by given slice names?

**Comment by LalitMaganti** [comment]
This question has been asked many times before (most recently at https://github.com/google/perfetto/issues/656) and the answer remains the same: this is a very hard problem we don't think our resources are best deployed in solving. Please collect smaller traces in the first place.
