### ISSUE TITLE
Perfetto no longer adjusting range to file min/max on Catapult json data

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#810]
This is a new instance of Perfetto in the browser, but the range isn't correct.  This is only on some files, and not all.  Then I end up having to pinch zoom way out to get it to fit to the range.  Having a button to reset the range would be welcome too.   Will try to post a sample file that illustrates this.  This seems to be due to some recent change in Perfetto.

min time is 0 in this case, so really it's just not adjusting to the max = ts + duration.

**Comment by LalitMaganti** [comment]
I think this might now be fixed with some changes Steve made. Please reopen if not.
