### ISSUE TITLE
"android.power_rails" Stdlib SQL implementation does not match the docs.

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#811]
For Android power rails, the raw value stored in the counters table is the cumulative energy consumed since boot. This is measured in micro Joules or uWS (micro watt seconds) as denoted in the track name and the trace proto spec: https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/protos/perfetto/trace/power/power_rails.proto;l=46

the android_power_rails_counters table simply contains the raw value from the counters table without converting it from energy to power. The android.power_rails implementation however documents that this value is in microwatts:

> Power rails counter value in micro watts.

https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/perfetto_sql/stdlib/android/power_rails.sql

Either the implementation or doc should probably be updated so that they match.

**Comment by LalitMaganti** [comment]
> Power rails counter value in micro watts.

Yeah I think this is a typo, there is a missing "seconds" here. Will take a look tomorrow.
