### ISSUE TITLE
ninja, gn and pnpm do not forward failures on Windows

### ISSUE THREAD

**Issue by dfriederich** [google/perfetto#814]
The python based helpers to invoke ninja, gn an pnpm do on Windows not use exec, but instead use subprocess.call to invoke the tools. This has the side effect of that the python environment remains active, and receives the exit code from subprocess.call.
The invocation of run_buildtools_binary inside of tools/run_buildtools_binary.py does surround the call with a sys.exit(x),
but the calls in the ninja, gn an pnpm do not. This causes that exit codes reported by ninja, gn an pnpm are not reported back to the caller of the helper, but instead just are dropped.
As fix we could either add a sys.exit(x) in all the 3 places it is currently missing, or, I think that is a bit cleaner add it inside of
the run_buildtools_binary function to exit right away, so Windows behaves a little bit more like Linux/OSX in this respect.
Adding a sys.exit() which is not used on Linux/OSX in code in which it appears to be seems like the less clean fix :-)

So here a proposed fix:

```
--- a/tools/run_buildtools_binary.py
+++ b/tools/run_buildtools_binary.py
@@ -56,10 +56,12 @@ def run_buildtools_binary(args):
   if sys_name == 'windows':
     # execl() behaves oddly on Windows: the spawned process doesn't seem to
     # receive CTRL+C. Use subprocess instead.
-    return subprocess.call([exe_path] + args)
+    exit_code = subprocess.call([exe_path] + args)
+    # exit from here to behave the same as when using os.execl
+    sys.exit(exit_code)
   else:
     os.execl(exe_path, os.path.basename(exe_path), *args)
 
 
 if __name__ == '__main__':
-  sys.exit(run_buildtools_binary(sys.argv[1:]))
+  run_buildtools_binary(sys.argv[1:])
```

**Comment by dfriederich** [comment]
I tries to upload this as a patch, but failed. I understand github is not the place for contributions, but I did not get
'git cl upload' to work for me :-(. Anyway, the issue is trivial, it is just dropping the exit code in windows for the main build tools. I understand that Windows is not high priority, but at least the fix is simple here :-)

**Comment by LalitMaganti** [comment]
Thanks for filing, https://r.android.com/3120751 fixes.

For future reference, if you follow the contributing instructions at https://perfetto.dev/docs/contributing/getting-started#contributing (specifically, downloading depot_tools and adding to your PATH), the `git cl upload` command should become available.
