### ISSUE TITLE
Interned event strings do not work on stable or canary

### ISSUE THREAD

**Issue by BGR360** [google/perfetto#819]
I'm trying to test out the interning functionality, and when I give `TrackEvent`s interned strings, they show up as NULL in the trace viewer.

The problem exists on both stable ([`v45.0-c0c52a371`](https://android.googlesource.com/platform/external/perfetto/+/c0c52a371ad978baf02fa7094140c6e95402bf22/ui)) and canary ([`v45.0-43cf00fbe`](https://android.googlesource.com/platform/external/perfetto/+/43cf00fbe761628c5552d85fd92f3490fbf301bc/ui)).

Example trace:

```pbtxt
packet {
  track_descriptor {
    uuid: 1
    process {
      pid: 1
    }
  }
}
packet {
  track_descriptor {
    uuid: 2
    thread {
      pid: 1
      tid: 1
    }
  }
}
packet {
  timestamp: 5
  trusted_packet_sequence_id: 1
  track_event {
    track_uuid: 2
    type: TYPE_SLICE_BEGIN
    name_iid: 0
  }
  interned_data {
    event_names {
      iid: 0
      name: "foo"
    }
  }
}
packet {
  timestamp: 10
  trusted_packet_sequence_id: 1
  track_event {
    track_uuid: 2
    type: TYPE_INSTANT
    name_iid: 1
  }
  interned_data {
    event_names {
      iid: 1
      name: "bar"
    }
  }
}
packet {
  timestamp: 15
  trusted_packet_sequence_id: 1
  track_event {
    track_uuid: 2
    type: TYPE_SLICE_END
    name_iid: 0
  }
}
```

Result:

<img width="1280" alt="image" src="https://github.com/google/perfetto/assets/13339928/6a0b9289-f2ec-466b-8d70-9fd21ec00a73">

<img width="169" alt="image" src="https://github.com/google/perfetto/assets/13339928/1874a0f3-3b40-476f-a80a-2ce89766facf">

<img width="190" alt="image" src="https://github.com/google/perfetto/assets/13339928/79c779c8-d94f-4c3c-9534-f0a0b5e7d617">

And when you try to click the slice or the instant event, you get a SQL error:

<img width="795" alt="image" src="https://github.com/google/perfetto/assets/13339928/3a1b8d60-2b9f-4e33-b652-78a43ff01ea7">

```
UI: https://ui.perfetto.dev/v45.0-c0c52a371

Error @ row: 0 col: 'name': SQL value is NULL but that was not expected (expected type: STR). Did you mean NUM_NULL, LONG_NULL, STR_NULL or BLOB_NULL?
Query:

    SELECT
      id,
      name,
      ts,
      dur,
      track_id as trackId,
      depth,
      parent_id as parentId,
      thread_dur as threadDur,
      thread_ts as threadTs,
      category,
      arg_set_id as argSetId,
      ABS_TIME_STR(ts) as absTime
    FROM slice
    WHERE id=0
 - QueryError (frontend_bundle.js:5830:11)
 - makeError (frontend_bundle.js:6220:18)
 - tryMoveToNextBatch (frontend_bundle.js:6359:30)
 - next (frontend_bundle.js:6246:25)
 - RowIteratorImpl (frontend_bundle.js:6214:16)
 - RowIteratorImplWithRowData (frontend_bundle.js:6374:24)
 - iter (frontend_bundle.js:5945:24)
 - getSliceFromConstraints (frontend_bundle.js:359540:23)

Trace: not available (FILE). Provide repro steps.
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0
Referrer:
```

**Comment by BGR360** [comment]
Same problem with category_iids, though the UI doesn't completely break. The category just shows as `unknown(<iid>)`.

```pbtxt
packet {
  timestamp: 10
  trusted_packet_sequence_id: 1
  track_event {
    track_uuid: 0
    type: TYPE_INSTANT
    name: "bar"
    category_iids: 1
  }
  interned_data {
    event_categories {
      iid: 1
      name: "cat1"
    }
  }
}
```

<img width="231" alt="image" src="https://github.com/google/perfetto/assets/13339928/2313d027-8299-4d96-95e0-f1a69f957351">

**Comment by LalitMaganti** [comment]
Correct me if I'm wrong but it feels like you're generating these protos manually? 

If so, please follow the guidance at https://perfetto.dev/docs/reference/synthetic-track-event#interning. Specifically note the flags you need to set on the first packet containing interned data (previous_packet_dropped, the flag indcating the clearing of the incremental state) and the fact that every packet afterwards requires the "needs incremental state" flag. 

Right now, the protos are not correctly formed according to the spec and so the behaviour of the UI and trace processor is largely WAI

**Comment by BGR360** [comment]
Thank you!

**Comment by BGR360** [comment]
The one piece of information missing from those docs is that `0` is not a valid iid.

**Comment by LalitMaganti** [comment]
Thanks for the suggestion: sent https://r.android.com/3131173 for adding this note to the docs.
