### ISSUE TITLE
about gpu_frequency capture

### ISSUE THREAD

**Issue by hojihodi** [google/perfetto#822]
I have a question about the principle of operation rather than the issue
I have confirmed that if i enable the atrace "freq", the power/gpu_frequency ftrace event is enabled and captured in the perfetto.
i'd like to check where the code that is related to atrace freq and gpu_frequency is.
In the path below, I am inquiring because it does not seem to be related to gpu_frequency in freq

frameworks/native/cmds/atrace/atrace.cpp

**Comment by LalitMaganti** [comment]
The link between freq category and the gpu_frequency event exists in this file: https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/traced/probes/ftrace/ftrace_config_muxer.cc;drc=10e7662e7dde44aff3188d1ef0ad7db3cbe379b1;l=293

The thing you found in atrace.cpp is a legacy mapping and no longer applies if you are using Perfetto natively.
