### ISSUE TITLE
Symbol issues in Perfetto UI

### ISSUE THREAD

**Issue by hanbim520** [google/perfetto#824]
I have set up a local Perfetto UI static website and used the "Record new trace" feature on the web to capture CPU native function call stacks. The web automatically opens the trace, but the symbols are not resolved. I have set the PERFETTO_BINARY_PATH and PERFETTO_SYMBOLIZER_MODE variables. If I use tools/trace_processor to process the trace, it resolves the symbols correctly. Is there a way to fix this? I looked at the UI source code and it seems that it doesn't handle symbol processing.

**Comment by hanbim520** [comment]
![image](https://github.com/google/perfetto/assets/7490792/99d8fe8c-1a5a-45e7-bfcf-989fdebff638)
like this

**Comment by hanbim520** [comment]
llvm-symbolizer is also set

**Comment by LalitMaganti** [comment]
Persisting symbol information in the trace is covered at https://perfetto.dev/docs/data-sources/native-heap-profiler#symbolize-your-profile

Quoting it
> You can persist symbols for a trace by running PERFETTO_BINARY_PATH=somedir tools/traceconv symbolize raw-trace > symbols. You can then concatenate the symbols to the trace ( cat raw-trace symbols > symbolized-trace) and the symbols will part of symbolized-trace. The tools/heap_profile script will also generate this file in your output directory, if PERFETTO_BINARY_PATH is used
