### ISSUE TITLE
Trace data convert to sqlite

### ISSUE THREAD

**Issue by hanbim520** [google/perfetto#826]
![image](https://github.com/google/perfetto/assets/7490792/ed2cc6d4-6491-44a2-9330-a7f21146bf79)
command ：python3 trace_processor -e trace.sqlite recorded_trace.perfetto-trace

**Comment by LalitMaganti** [comment]
Conversion to SQLite is really not a well supported feature. We built it at the very start when trace processor was a lot less mature to verify that it was returning the correct results by checking vs SQLite directly.

These days, the only supported way to query traces is to use trace processor directly. We might fix this at some point but it's not a priority and, tbh the fix might be to remove this feature entirely.

**Comment by hanbim520** [comment]
Okay, I tend to support this function, because after converting to a sqlite database, customized related data display can be done. More convenient for data analysis. Although perfetto UI can also be developed secondaryly, the cost is higher after all, and we prefer to use a lighter display method when data expansion is better. We have also completed the processor query method, but the data display is not convenient.

**Comment by LalitMaganti** [comment]
You can do the same SQL queries with trace processor that you can with SQLite. The Python API (https://perfetto.dev/docs/analysis/trace-processor-python) lets you integrate with all the standard Python data analytics and visualization libraries (Pandas, numpy, Altair etc) 

Not sure what you need beyond that.

**Comment by hanbim520** [comment]
yes  
 python3 H:\perfetto\tools\trace_processor  -q H:\分析工具\分析工具\sql.txt H:\分析工具\分析工具\symbolized-trace >query_results.txt
是的，这种方案我已经在使用了，我们公司内部做了一个轻量的分析工具，如果仅仅提供sqlite数据库过去就可以避免繁琐的脚本操作。

**Comment by LalitMaganti** [comment]
I'm not talking about using the trace processor as a script, I'm talking about using it as a library (see the link I provided).

In general, I feel that direction you are taking is not in the spirit of the design of the Perfetto analytics stack: you're going to constantly find weird quirks and issues like this if you try and reinvent the wheel. I'd very strongly suggest looking into the set of trace analytics tools and libraries we provide and work within those space: we're not staffed as a team to support anything beyond this.

**Comment by LalitMaganti** [comment]
Sent a fix for this in https://r.android.com/3139553, was easy enough so decided to just get it done.

**Comment by hanbim520** [comment]
Okay, I understand what you mean. It’s no problem to use the library solution to handle this. I also plan to use perfetto ui for secondary development to meet our analysis needs. We also have a ready-made data display platform, and the library solution can also meet the current needs. py api method is also consistent. It’s just that I think it would be better to have a standard sqlite database. Many software have introduced the sqlite library.

If this conversion function is no longer supported in the future, I will use the library solution you mentioned to handle it.

**Comment by LalitMaganti** [comment]
c4d6ffb fixes the export.
