### ISSUE TITLE
Question about the trace file in protobuf binary format

### ISSUE THREAD

**Issue by cos120** [google/perfetto#827]
Hello folks!
Thanks for the great project. I have some question about trace file in protobuf binary format.

I am using the [perfetto_trace.proto](https://github.com/google/perfetto/blob/main/protos/perfetto/trace/perfetto_trace.proto) to generate custom timeline for profiling.

I have lots of spans, but name of them are finite(less than 30), but spans can be 5000 for each process, there are thousands of processes. 1344 files of origin tracing data about 300MiB, when i merge them into tracefile, it's about 800MiB(json is 1.2GiB).

I noticed there is a message named `InternedData`, and have `iid`, can i use `iid` to encode name of spans to reduce the size of tracefile? 

Thanks.

**Comment by LalitMaganti** [comment]
Great to see you're liking the project :)

Yes you can use interning to reduce the size of the traces: please see https://perfetto.dev/docs/reference/synthetic-track-event#interning in our docs which explains how to use interning.

**Comment by cos120** [comment]
> Great to see you're liking the project :)
> 
> Yes you can use interning to reduce the size of the traces: please see https://perfetto.dev/docs/reference/synthetic-track-event#interning in our docs which explains how to use interning.

Thanks!
My trace reduce 800MiB to 450MiB, cool.
