### ISSUE TITLE
Why different trace on the same device, the type of cpu is different and max frequency is also different?

### ISSUE THREAD

**Issue by ZhangQinglian** [google/perfetto#829]
<img width="463" alt="SCR-20240621-jkkd" src="https://github.com/google/perfetto/assets/9946302/8c8e26c7-ba0e-47a9-9087-ca643c1b8a0b">
<img width="464" alt="SCR-20240621-jkhx" src="https://github.com/google/perfetto/assets/9946302/701169b9-1b20-4d46-a104-4605c44ce08d">

**Comment by ivan-chong** [comment]
This is fixed in https://r.android.com/3160741
