### ISSUE TITLE
Is it possible dispaly the time duration across multiple selcted portion on the timeline 

### ISSUE THREAD

**Issue by lavanyaeswarappa** [google/perfetto#832]
Hi,

I want to see the timeline between these multiple marked points and keep the display of the timeline even after I select a new window. 
Is it possible on perfetto to have that feature? 
![image](https://github.com/google/perfetto/assets/24353986/a0638903-6485-4095-bca7-bf325e19b451)

Thanks

**Comment by LalitMaganti** [comment]
Yes this feature exists. Press 'm' to mark the region of time and persist this independent of the selection you make.

**Comment by LalitMaganti** [comment]
Afaik you can do it as many times as you want. Just press m after each selection you want to persist.

**Comment by lavanyaeswarappa** [comment]
not sure if its working for me. Am able to select only 2 at a time

**Comment by LalitMaganti** [comment]
Sorry my mistake it's Shift + m to persist: see the Keyboard Shortcuts panel on the sidebar for all the useful shortcuts and what they do.

**Comment by lavanyaeswarappa** [comment]
Ok got it now. Thanks a lot
