### ISSUE TITLE
Json format to protobuff

### ISSUE THREAD

**Issue by lavanyaeswarappa** [google/perfetto#838]
Currently we are using json format to visualize data on perfetto, we want to know what is the main difference in using protobuff format and if there is anyway to move to protobuff from json format.

If possible could you please share an example protobuff file/format. What would be the file format for protobuff format( was unable to find on the website)

Thanks

**Comment by primiano** [comment]
> Currently we are using json format to visualize data on perfetto, we want to know what is the main difference in using protobuff format and if there is anyway to move to protobuff from json format.

More features, things that you cannot represent in JSON. e.g. flows and interning

> If possible could you please share an example protobuff file/format. What would be the file format for protobuff format( was unable to find on the website)

https://perfetto.dev/docs/reference/synthetic-track-event

**Comment by lavanyaeswarappa** [comment]
Hi,
The examples on perfetto docs can not be parsed directly. 
for these packet data, what is the correct file format?
 

![image (5)](https://github.com/user-attachments/assets/aca8da98-b1ea-4054-8823-0134e1c16f48)

**Comment by lavanyaeswarappa** [comment]
Can you share an working android trace example of protobuff?

**Comment by LalitMaganti** [comment]
As stated at the top of those page, you need to use protobuf libraries to generate binary versions of traces. The examples on that page are written as textprotos as it's easy to read and not language specific.
