### ISSUE TITLE
use perfetto in docker with ftrace

### ISSUE THREAD

**Issue by ChunelFeng** [google/perfetto#839]
```json
data_sources {
  config {
    name: "linux.ftrace"
    target_buffer: 0
    ftrace_config {
      compact_sched: {
        enabled: true
      }
      ftrace_events: "sched/sched_switch"
      ftrace_events: "sched/sched_wakeup_new"
      ftrace_events: "sched/sched_wakeup"
      ftrace_events: "sched/sched_waking"
    }
  }
}
```

hi, i run two same process named 'chunel_test', both on my host and in docker env，
and then run perfetto in docker env.

and then, i find both process id on host, is marked as thread-id.

![image](https://github.com/google/perfetto/assets/37905059/8a085c09-dc66-4596-968b-c9a5a2d761a8)

as shown in the picture, 2081102 and 2080195 is both process-id that worked on host.

![image](https://github.com/google/perfetto/assets/37905059/825f4082-31bc-4426-bb2d-177c1ff6d033)

i cannot get what to do, how to slove this mistake, please give me some helps.

**Comment by LalitMaganti** [comment]
Everything here seems working as intended? Perfetto inside a docker container (assuming you have given the container the permissions) will simply read ftrace data of the host: it will *not* read the pid info inside the container as there is no "ftrace inside a container" datasource to read from.

**Comment by ChunelFeng** [comment]
the important thing is, 
perfetto record process-id on host as thread-id,
and set them into internal_thread table.

**Comment by LalitMaganti** [comment]
This is correct: you have only enabled scheduling events which do not give any indication that a thread is actually a process so we assume everything is a thread (as is standard on Linux).

You should enable the process tracking events task_newtask, sched_process_free and task_rename to have accurate information as well the linux.process_stats data source.

**Comment by LalitMaganti** [comment]
We call this out in our docs at https://perfetto.dev/docs/data-sources/cpu-scheduling#traceconfig

**Comment by ChunelFeng** [comment]
sorry, i can not open page:  https://perfetto.dev/docs/data-sources/cpu-scheduling#traceconfig

you mean, i can use this config as follows?

```json

data_sources {
  config {
    name: "linux.ftrace"
    target_buffer: 0
    ftrace_config {
      compact_sched: {
        enabled: true
      }
      ftrace_events: "sched/sched_switch"
      ftrace_events: "sched/sched_wakeup_new"
      ftrace_events: "sched/sched_wakeup"
      ftrace_events: "sched/sched_waking"
      ftrace_events: "task_newtask"
      ftrace_events: "sched_process_free"
      ftrace_events: "task_rename"
    }
  }
}

data_sources {
  config {
    name: "linux.process_stats"
    target_buffer: 1
  }
}

```

**Comment by LalitMaganti** [comment]
```
# Scheduling data from the kernel.
data_sources: {
  config {
    name: "linux.ftrace"
    ftrace_config {
      compact_sched: {
        enabled: true
      }
      ftrace_events: "sched/sched_switch"
      # optional: precise thread lifetime tracking:
      ftrace_events: "sched/sched_process_exit"
      ftrace_events: "sched/sched_process_free"
      ftrace_events: "task/task_newtask"
      ftrace_events: "task/task_rename"
    }
  }
}

# Adds full process names and thread<>process relationships:
data_sources: {
  config {
    name: "linux.process_stats"
  }
}
```

This is what the docs say. What you have would also work except you need to make sure you have two buffers if you set target_buffer:1.

**Comment by ChunelFeng** [comment]
thank you,  i use the config, and then find the thread id in internal_thread table.

<img width="1658" alt="image" src="https://github.com/google/perfetto/assets/37905059/729c79ef-8318-4143-bcda-d076c37790cf">

but i can not find the process info in internal_process table,
and still i cannot match the relation between thread_id and process_id

<img width="1685" alt="image" src="https://github.com/google/perfetto/assets/37905059/13e9e626-0b72-4952-b43d-ff0fb8484b0a">

with the config:
```json

data_sources {
  config {
    name: "linux.ftrace"
    target_buffer: 0
    ftrace_config {
      compact_sched: {
        enabled: true
      }
      ftrace_events: "sched/sched_switch"
      ftrace_events: "sched/sched_wakeup_new"
      ftrace_events: "sched/sched_wakeup"
      ftrace_events: "sched/sched_waking"
      ftrace_events: "sched/sched_process_exit"
      ftrace_events: "sched/sched_process_free"
      ftrace_events: "task/task_newtask"
      ftrace_events: "task/task_rename"
    }
  }
}


```

**Comment by LalitMaganti** [comment]
The ftrace events only work if the processes were started during the trace. If they existed before the trace, you need to enable the process_stats data source. 

This is not a Perfetto issue: this is simply down to how the Linux kernel works: ftrace events are push events and are only sent when changed. They also don't provide actual process information. Therefore we need to scrape /proc to get this info: this is what the process_stats data source does.

**Comment by ChunelFeng** [comment]
i use the process_stats data source at last demo.
here is all my config file.

```json

write_into_file: true
file_write_period_ms: 2500
flush_period_ms: 3000

duration_ms: 10000

buffers {
  size_kb: 262144
  fill_policy: RING_BUFFER
}

buffers {
  size_kb: 262144
  fill_policy: RING_BUFFER
}

buffers {
  size_kb: 131072
  fill_policy: RING_BUFFER
}

buffers {
  size_kb: 131072
  fill_policy: RING_BUFFER
}

data_sources {
  config {
    name: "linux.ftrace"
    target_buffer: 0
    ftrace_config {
      compact_sched: {
        enabled: true
      }
      ftrace_events: "sched/sched_switch"
      ftrace_events: "sched/sched_wakeup_new"
      ftrace_events: "sched/sched_wakeup"
      ftrace_events: "sched/sched_waking"
      ftrace_events: "sched/sched_process_exit"
      ftrace_events: "sched/sched_process_free"
      ftrace_events: "task/task_newtask"
      ftrace_events: "task/task_rename"
    }
  }
}

data_sources: {
    config {
        name: "track_event"
        target_buffer: 1
        track_event_config {
            enabled_categories: "*"
            disabled_categories: "hobotsdk"
        }
    }
}

data_sources {
  config {
    name: "linux.sys_stats"
    target_buffer: 2
    sys_stats_config {
      meminfo_period_ms: 300
      meminfo_counters: MEMINFO_MEM_AVAILABLE
      meminfo_counters: MEMINFO_BUFFERS
      meminfo_counters: MEMINFO_CACHED
      meminfo_counters: MEMINFO_SWAP_CACHED
      meminfo_counters: MEMINFO_ACTIVE
      meminfo_counters: MEMINFO_INACTIVE
      meminfo_counters: MEMINFO_ACTIVE_ANON
      meminfo_counters: MEMINFO_INACTIVE_ANON
      meminfo_counters: MEMINFO_ACTIVE_FILE
      meminfo_counters: MEMINFO_INACTIVE_FILE
      meminfo_counters: MEMINFO_UNEVICTABLE
      
      vmstat_period_ms: 300
      vmstat_counters: VMSTAT_NR_FREE_PAGES
      vmstat_counters: VMSTAT_NR_ALLOC_BATCH
      vmstat_counters: VMSTAT_NR_ACTIVE_ANON
      vmstat_counters: VMSTAT_NR_ACTIVE_FILE
      vmstat_counters: VMSTAT_NR_UNEVICTABLE
      vmstat_counters: VMSTAT_NR_MLOCK
      vmstat_counters: VMSTAT_NR_ANON_PAGES
      vmstat_counters: VMSTAT_NR_MAPPED
      vmstat_counters: VMSTAT_NR_FILE_PAGES
      vmstat_counters: VMSTAT_NR_DIRTY
      vmstat_counters: VMSTAT_NR_WRITEBACK
      vmstat_counters: VMSTAT_NR_SLAB_RECLAIMABLE
      vmstat_counters: VMSTAT_NR_SLAB_UNRECLAIMABLE
      vmstat_counters: VMSTAT_NR_PAGE_TABLE_PAGES
      vmstat_counters: VMSTAT_NR_KERNEL_STACK
      vmstat_counters: VMSTAT_NR_OVERHEAD
      vmstat_counters: VMSTAT_NR_UNSTABLE
    }
  }
}

data_sources {
  config {
    name: "linux.process_stats"
    target_buffer: 3
  }
}
```

**Comment by LalitMaganti** [comment]
Make sure /proc inside the container is the same as outside the container. If it's a different pid namespace, you will end up with the pids inside the container not matching those outside and trace processor will not perform the mapping correctly.

**Comment by ChunelFeng** [comment]
not same in docker and host /proc filedir

<img width="1105" alt="image" src="https://github.com/google/perfetto/assets/37905059/623aefa0-7a98-4ab2-9834-ae5748560c51">

so may i use `docker -v /proc:/proc` to make sure the /proc is same ?

**Comment by LalitMaganti** [comment]
I guess though I'm not a docker expert. It's better to consult other sources of information at this point. From the Perfetto perspective this is why things are not working.

**Comment by ChunelFeng** [comment]
i tried -v /proc:/proc when i start my docker container, but container cannot start collectly.

i make a summary:

i use perfetto in container env with data source : linux.process_stats, 
and perfetto get process_stats in container /proc, 
which is different from host /proc

so i can get thread info only, and cannot get process info in my trace result.
is this summary right?

but i still want to know, which data source make me catch thread info on host env?

**Comment by LalitMaganti** [comment]
> is this summary right?

Essentially yes. Without being able to scrape host /proc, we cannot get the process information in the host pid namespace which we need to perform process associations with data coming from ftrace. 

> but i still want to know, which data source make me catch thread info on host env?

Thread information is inferred indirectly from the ftrace data source.

**Comment by ChunelFeng** [comment]
thank you very much.
i will try how to align proc space between container and host.

**Comment by ChunelFeng** [comment]
> Thread information is inferred indirectly from the ftrace data source.

and, is there any method to infer process info in ftrace data source?

**Comment by LalitMaganti** [comment]
> and, is there any method to infer process info in ftrace data source?

Only for processes started during the trace, not for preexisting processes.

**Comment by ChunelFeng** [comment]
oh, i know, thank you very much,

and thank you for so nice repo
