### ISSUE TITLE
[UI] Error when enabling service worker on autopush channel

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#841]
How to repro

1. navigate to https://ui.perfetto.dev
2. change channel in flags menu to autopush
3. refresh page
4. click on the green SW in bottom left to toggle off the service worker
5. click "disable and reload"
6. refresh the page
7. click the red SW to toggle the service worker back on
8. Observe the error:

```
UI: https://ui.perfetto.dev/v46.0-8e3b86fbe

Failed assertion
 -  (Error: Failed assertion)
 - assertTrue (frontend_bundle.js:4909:16)
 - getServingRoot (frontend_bundle.js:70810:35)
 - ServiceWorkerController.install (frontend_bundle.js:70922:61)
 - ServiceWorkerController.setBypass (frontend_bundle.js:70899:19)

Trace: not available (No trace loaded). Provide repro steps.
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Referrer: https://ui.perfetto.dev/
```

<img width="1848" alt="image" src="https://github.com/google/perfetto/assets/77857237/0909a74b-97e0-402a-bef9-e0dd64c5b0df">

**Comment by LalitMaganti** [comment]
Seems like the bypass code is failing to adhere to this comment in install:

```
// This must happen before any await, because in continuations
    // document.currentScript (which getServingRoot() depends on) is null
```

This code was recently refactored and this just looks like a missing oversight.

**Comment by LalitMaganti** [comment]
https://r.android.com/3165523 fixes.
