### ISSUE TITLE
Improve Randomness for Thread Naming and Thread Safety

### ISSUE THREAD

**Issue by AmarYasser1** [google/perfetto#844]
Improve the randomness for thread naming in the SetRandomThreadName function and enhances thread safety. Key changes include:

- Introduced a thread-local random device and Mersenne Twister engine for generating random numbers.
- Replaced the previous usage of rand() with a more robust and thread-safe random number generator.

Code:
void SetRandomThreadName(uint32_t thread_name_count) {
#if PERFETTO_HAVE_PTHREADS
  thread_local std::random_device rd;
  thread_local std::mt19937 gen(rd());
  std::uniform_int_distribution<> dis(0, thread_name_count - 1);
  base::StackString<16> name("busy-%" PRIu32, static_cast<uint32_t>(dis(gen)));
  pthread_setname_np(pthread_self(), name.c_str());
#endif
}

**Comment by LalitMaganti** [comment]
The code you found is only in a Perfetto developer tool which is very very rarely run so imo it's not worth trying to fix this really. I'm not sure I even really see it as a bug, as the randomness here is not really important.
