### ISSUE TITLE
how to get an event 10s before, and 5s after perfetto info?

### ISSUE THREAD

**Issue by ChunelFeng** [google/perfetto#845]
HI，i want to get perfetto trace info when an special event happen,

and dump the before 10s, after 5s trace info.

if the event do not happen, i would like to dump nothing.

can i finish the task by `duration_ms: 0` and `fill_policy: RING_BUFFER` ？

i tried, but failed.  need some help, thank you.

**Comment by ChunelFeng** [comment]
by origin config, i means:

```json

write_into_file: true
file_write_period_ms: 2500
flush_period_ms: 3000

Sampling duration: 10s
....

```

**Comment by LalitMaganti** [comment]
I forgot to mention: whenever you use `kill` you *must* wait for the PID of the perfetto process to go away before you pull the trace file. You can do this by polling every 50ms or so on `/proc/<pid>`. What I think might be happening here is that the trace is actually slightly corrupted as track_event events have not been written correctly to the Perfetto buffer.

**Comment by LalitMaganti** [comment]
> i thought, my perfetto process go away after trace.gz file dump finish.

The Perfetto process does go away but only *after* all the data is written to disk. If you send a kill command and then don't wait for the process to go away before you adb pull the trace file, you will end up with a corrupted file.

**Comment by ChunelFeng** [comment]
oh, i think i should do like this: 

when perfetto process receive a kill signal, 
sleep for some seconds, wait for adb pull trace.gz finished
and then, perfetto process quit.

for example :
# catch ctrl + c
trap 'echo "Received SIGINT signal. Waiting 30 seconds before exit..."; sleep 30; exit 0' SIGINT

30s is to wait trace.gz dump finish

**Comment by LalitMaganti** [comment]
You can wait 30s sure but it's easier and more reliable if you just poll for proc. In a bash script, that would look something like this:
```
kill -TERM $PID
while [ -e /proc/$PID ]; do
  sleep 1
done
```

**Comment by ChunelFeng** [comment]
so, $PID is my perfetto process id?
i should make sure the perfetto process finish, then adb pull?

but i am not worked on android, i worked on linux, with no adb

**Comment by LalitMaganti** [comment]
> so, $PID is my perfetto process id?

Yes

> but i am not worked on android, i worked on linux, with no adb

This would have been useful context to provide earlier on :) By default, we assume that people are working on Android unless they specify otherwise (given we are the default tracing system on Android and not on Linux).

Ignore `adb` command then, it's just the point where you are safe to do anything with the file (copying it, opening it in the Perfetto UI etc)

**Comment by ChunelFeng** [comment]
```bash
kill -TERM $PID
while [ -e /proc/$PID ]; do
  sleep 1
done
```

ok, i will try this mothed tomorrow morning at first time,
thank you for your help

**Comment by ChunelFeng** [comment]
i try kill my perfetto process in this way.

but still few track_event was get.


![image](https://github.com/user-attachments/assets/b9140ecb-60e4-43e9-8d00-8aaaea9f2547)

**Comment by LalitMaganti** [comment]
Sorry at this point I have to assume there is something not correct with your usage of track_event. From the Perfetto perspective I cannot think of anything else which is wrong and without logs or your traces, it's impossible to remotely debug further. 

We know that what I described works: we collect hundreds of thousands of traces per day with this sort of config.

**Comment by ChunelFeng** [comment]
```bash
write_into_file: true
file_write_period_ms: 2500
flush_period_ms: 3000

duration_ms: 10000
```

* start
```bash
/opt/ros/humble/perfetto/bin/perfetto --gz --txt --config/opt/ros/humble/perfetto/bin/all.cfg -o my_trace
```
wait for auto end, and result good.


-----


```bash
duration_ms: 0
```

* start
```bash
/opt/ros/humble/perfetto/bin/perfetto --gz --txt --config/opt/ros/humble/perfetto/bin/all.cfg -o my_trace
```

* kill
```
#bin/sh
kill -15 135652   # 135652 is the pid
while [ -e /proc/135652 ]; do
  sleep 1
done
```

wait for shell run finish, result no good.


i tried again and again, the result is same as this morning.
can you give me your email? i send my trace.gz to you, then you can get more details.


i believe this is for the reason that i make some mistake,
but i do not know why.

**Comment by LalitMaganti** [comment]
You can send the trace to lalitm@google.com. I'm not promising I will find something but I'll see what I can do.

**Comment by ChunelFeng** [comment]
thank you,
current, i cannot open the page: https://perfetto.dev/docs/concepts/buffers#incremental-state-in-trace-packets 
 , and i will try this config as soon as possible. 

```bash
incremental_state_config: {
  clear_period_ms: 5000
}

duration_ms: 0
......
```

**Comment by ChunelFeng** [comment]
thank you, it is really helpful and useful
