### ISSUE TITLE
How to copy heapprof callstack frame name (or function name)

### ISSUE THREAD

**Issue by lbknxy** [google/perfetto#846]
Hi, I want to copy function name, But **Callstack panel**  not support copy and **Selected function**: just show part of name.
Do you have plan to support copy function names or have idea to copy function names in this case ?

![heapprof_copy_framename](https://github.com/user-attachments/assets/4ac5b692-f630-43cb-86c3-81967c60d4d8)

**Comment by LalitMaganti** [comment]
This is already fixed on gbe autopush version of the UI where there is a fully rewritten version of flamegraph which supports copying the function name.

**Comment by lbknxy** [comment]
Where can I find this **autopush version ?**

**Comment by lbknxy** [comment]
my chrome shows, current perfetto UI are : 
![image](https://github.com/user-attachments/assets/c6f97e6b-fa5d-405d-8932-fec1708eddb0)    
and  

![image](https://github.com/user-attachments/assets/2e778637-29c7-4051-9241-0252b3e3e62a)

none of them can copy.

**Comment by LalitMaganti** [comment]
Go to flags, the top flag should be a version selector. Select autopush reload and then you should be using the new flamegraph.

**Comment by lbknxy** [comment]
Very good job! Thanks!

**Comment by lbknxy** [comment]
Please keep the so path!

From stable version:
![jfiGpOptX4](https://github.com/user-attachments/assets/71306e9c-ceba-4c86-bdef-ddeea57afb7a)

But, the autopush version,  I find so path not show any more, it will help us differentiate callstack libraries, please keep them on:
![2g4LGhngEW](https://github.com/user-attachments/assets/319670d1-87ce-4d65-b399-6a8f600608a6)

**Comment by LalitMaganti** [comment]
Thanks for the feedback. Reintroduced the mapping name in https://r.android.com/3184803 which should land next week.
