### ISSUE TITLE
How to get a normal event track, not call stack slice track

### ISSUE THREAD

**Issue by rollysys** [google/perfetto#848]
For example, I need to implement a event track like:
task a begin
task b begin
end(task a)
end(task b)

By default, perfetto sdk will treat the 2 end events as call stack, so we got track below:
```
|________________|
     |________|
```
But the correct track is:
```
|___________|
     |_____________|
```
So how to get the correct event track?
Actually I could use flow event, and then implement a debug track in the UI, with a bit bothering...
Thanks so much!

**Comment by LalitMaganti** [comment]
Use multiple tracks, name them the same. The UI will merge them correctly as you want.
