### ISSUE TITLE
feature request: open trace file keyboard shortcut

### ISSUE THREAD

**Issue by osievert-gpfw** [google/perfetto#849]
Thanks for a very useful tool.

I like to hide the left navigation panel to maximize the screen real estate for display of the timeline. I find that I spend most of my time in the timeline view, zooming in and out to discover both detailed and big-picture things about the performance trace. The inner loop of my workflow is to observe something in the Perfetto timeline, change my code and generate a new trace, and load that new trace to see how the system now behaves.

In this In this workflow and Perfetto view configuration, the one thing that is missing is a keyboard shortcut to open a new trace file. An "open trace file" keyboard shortcut would avoid the extra steps of un-hiding the left navigation panel, using the mouse to click on the "Open trace file" button, and then re-hiding the left navigation panel.

**Comment by LalitMaganti** [comment]
I don't think we'd be opposed to adding a shortcut but there's a couple of options you might not be aware of that may also help accelerate your workflow further:
1) [tools/open_trace_in_ui](https://github.com/google/perfetto/blob/main/tools/open_trace_in_ui) is a Python script which allows opening traces from the command line without needing to interact with the browser at all
2) the UI supports drag/drop so you can just drop the file from your file explorer into the UI without needing to click open/select/click ok.

**Comment by primiano** [comment]
On top of what Lalit said, I think this could be done by creating a core_plugins command and binding it to a key, so you can both do "ctrt-shift-p" -> "Open trace file" and using the hotkey.
Feel free to send a patch for it. (it's not going to be too much of a big deal for us to get there too soon)

**Comment by LalitMaganti** [comment]
r.android.com/3194929 tries to do this but there is some problem with the input not being added to the dom which is causing integration tests to fail. I need to show Steve this in person, will do this in a couple of weeks (I'm going to be out for the next couple of weeks).
