### ISSUE TITLE
[UI] "ftrace events" tab is checked, but not visible

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#851]
Currently the checked state of the "ftrace events" tab doesn't appear to. Reproduces on autopush only; canary and stable do not show this issue.

# How to Reproduce
1. open ui.perfetto.dev on autopush
2. open "example android trace" from left hand side-bar
3. click on the "3-dots" next to "Current selection" at the bottom of the window
4. note ftrace events is checked, but the tab is not visible.

<img width="603" alt="image" src="https://github.com/user-attachments/assets/699f88fb-6c8a-4638-9ac5-790bf853fd6c">

clicking on "ftrace events" checkbox causes the tab to appear, so this mostly appears that the "checked state" is always "checked" regardless of if the tabs are visible or not

**Comment by LalitMaganti** [comment]
Thanks for the succinct and precisee bugreports (as always!). Sent https://r.android.com/3194570 to fix this.
