### ISSUE TITLE
Can we use multiline sql query in viz page?

### ISSUE THREAD

**Issue by rollysys** [google/perfetto#852]
I really like vega-lite and enjoy perfetto viz page everyday, but it's painful for un-wrap long sql query...
So any idea for using multiline sql query in it?
Thanks!

**Comment by LalitMaganti** [comment]
No we will not be investing any more time to the viz page in the current. It was an interesting experiment but was not to our satisfaction so it will remain an experiment only.

We will be taking the analysis experience of the UI in a different direction, potentially with the presence of Vega-Lite but I anticipate the UX with be quite different and will certainly not involve pasting SQL inline into JSON
