### ISSUE TITLE
[UI] crash when selecting multiple running/runnable slices in thread scheduling track

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#853]
It appears i get a crash on the autopush channel if i try to click and drag to select multiple thread scheduling slices. This does not appear to affect current versions of stable or canary at this timee

This seems to happen only when selecting certain time regions of certain threads. I have yet to spot what pattern of events causes this, but can reproduce consistently if i select a large enough region of time on these tracks.

# How to Reproduce

1. Open ui.perfetto.dev on Autopush channel
2. Open "Example Android trace" in left hand sidebar
3. Expand the track group for the com.google.android.GoogleCamera process
4. click and drag over a large region of running/runnable slices on the main thread of that process, similar to what is shown below:  <img width="1550" alt="image" src="https://github.com/user-attachments/assets/74ae0ab9-b51d-4464-ab3f-f46a8132948f">
5. Observe crash
<img width="1782" alt="image" src="https://github.com/user-attachments/assets/6a37ab7b-78ee-4e14-b868-adccbd69951a">

```
UI: https://ui.perfetto.dev/v46.0-7053c260e

Traceback (most recent call last):
  File "stdin" line 1 col 1
    select process_name,pid,thread_name,tid,concat_state,total_dur,avg_dur,occurrences from thread_state_aggregation order by total_
    ^
no such column: io_wait
Query:
select process_name,pid,thread_name,tid,concat_state,total_dur,avg_dur,occurrences from thread_state_aggregation order by total_dur DESC
 -  (Error: Traceback (most recent call last):)
 - WasmEngineProxy.query (frontend_bundle.js:194668:14)
 - async ThreadAggregationController.getAggregateData (frontend_bundle.js:195067:25)
 - async Object.work (frontend_bundle.js:195040:35)
 - async AsyncLimiter.runTaskQueue (frontend_bundle.js:67916:22)

Trace: https://storage.googleapis.com/perfetto-misc/example_android_trace_15s
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Referrer: 
```

**Comment by LalitMaganti** [comment]
Thanks for filing. https://android-review.googlesource.com/c/platform/external/perfetto/+/3195221?usp=search will fix.
