### ISSUE TITLE
Next release? (v46.0)

### ISSUE THREAD

**Issue by saraadams** [google/perfetto#855]
I have a quick question on when we can expect the next release. The documentation states a new release about every 4 weeks: https://perfetto.dev/docs/visualization/perfetto-ui-release-process
However, the last release was on May 9th, 2024, just over 12 weeks ago.

Is there an open issue that is blocking the next release?

**Comment by LalitMaganti** [comment]
I believe @ddiproietto is going to push a release very shortly.

**Comment by ddiproietto** [comment]
Yep! We're working on a release this week.

**Comment by saraadams** [comment]
Great, thanks for the quick response!
