### ISSUE TITLE
Building ui on arm64 linux

### ISSUE THREAD

**Issue by gramound** [google/perfetto#857]
I was trying to build the ui yesterday on a Ubuntu 22.04 virtual machine on my M1 mac (so linux arm64, not darwin) and realized it wasn't able to install the build dependencies, because nodejs wasn't available (`install-build-deps --ui` failed in protobufjs postinstall).
```
UI_DEPS = [
    Dependency(
        'buildtools/mac/nodejs.tgz',
        'https://storage.googleapis.com/chromium-nodejs/20.11.0/5b5681e12a21cda986410f69e03e6220a21dd4d2',
        'cecb99fbb369a9090dddc27e228b66335cd72555b44fa8839ef78e56c51682c5',
        'darwin', 'arm64'),
    Dependency(
        'buildtools/mac/nodejs.tgz',
        'https://storage.googleapis.com/chromium-nodejs/20.11.0/e3c0fd53caae857309815f3f8de7c2dce49d7bca',
        '20affacca2480c368b75a1d91ec1a2720604b325207ef0cf39cfef3c235dad19',
        'darwin', 'x64'),
    Dependency(
        'buildtools/linux64/nodejs.tgz',
        'https://storage.googleapis.com/chromium-nodejs/20.11.0/????????????????????????????????????????',
        '????????????????????????????????????????????????????????????????',
        'linux', 'arm64'),
    Dependency(
        'buildtools/linux64/nodejs.tgz',
        'https://storage.googleapis.com/chromium-nodejs/20.11.0/f9a337cfa0e2b92d3e5c671c26b454bd8e99769e',
        '0ba9cc91698c1f833a1fdc1fe0cb392d825ad484c71b0d84388ac80bfd3d6079',
        'linux', 'x64'),
```
Unfortunately storage.googleapis.com is not browseable, so I did some searching to try to find the right hash, and found [this command](https://chromium.googlesource.com/apps/libapps/+/refs/heads/main/libdot/bin/node#32) that seems to be internal to Google:
```
gsutil ls gs://chromium-nodejs/
```

Can someone at Google run the command and confirm there is no arm64 linux tarball available?

**Comment by LalitMaganti** [comment]
Even if we had nodejs available, you would run into a problem with emscripten (which I think it also Linux x64 only ATM)

**Comment by LalitMaganti** [comment]
Also yes I can confirm that, even on the latest Chrome source-tree, there is no nodejs chromium binary available (you can see this at https://source.chromium.org/chromium/chromium/src/+/main:DEPS;l=728?q=chromium-nodejs%20f:DEPS&ss=chromium)

**Comment by primiano** [comment]
You cannot build the UI on arm64 linux. that's not a supported config.
