### ISSUE TITLE
perfetto seems not support MEMORY

### ISSUE THREAD

**Issue by forrestxu123** [google/perfetto#859]
I have added the below configuration: data_sources: {
    config {
        name: "android.heapprofd"
        target_buffer: 0
        heapprofd_config {
            sampling_interval_bytes: 4096
            continuous_dump_config {
                dump_phase_ms: 0
                dump_interval_ms: 1000
            }
            shmem_size_bytes: 536870912
            block_client: true
        }
    }
}
data_sources: {
    config {
        name: "android.java_hprof"
        target_buffer: 0
        java_hprof_config {
            continuous_dump_config {
                dump_phase_ms: 0
                dump_interval_ms: 1000
            }
        }
    }
}.  no snapshots are displayed in perfetto UI. seems a bug, right? I am using android os12 usedebug with selinux disabled.

**Comment by LalitMaganti** [comment]
If you're using the UI to record the generate the config, seems like you did not specify the process(es) to profile. This is mandatory and not happens if you don't do this. 

If you generated the config manually, please refer to this page: https://perfetto.dev/docs/case-studies/memory. You are missing the specification of the cmdline config option. It's also strongly recommended to use the tools/heap_profile script instead of manually writing configs.

**Comment by forrestxu123** [comment]
I can not use tools/heap_profile script, because i would like to make an unique UI with  configuration including memory, cpu,logcat and Callstack sampling together.   Meanwhile I tried both configuration file and  heap_profile (or java_heap_profile) tool script with name: "com.xxx.xxx.  For heap_profile and java_heap_profile tool , they can only show 1 snap.  for configuration file, it does not show any thing related with memory. However the Callstack sampling tools works great to me.  The work i am working is to collect the perfertto files when issue(such as anr, oom) is happened.

**Comment by LalitMaganti** [comment]
The memory profiler by default only output single profiles: you can turn on continuous for profilers by using the `continuous_dump_config` option (see https://perfetto.dev/docs/data-sources/native-heap-profiler#continuous-dumps). This will give you profiling over time similar to the callstack sampling.
