### ISSUE TITLE
lack one cpu frequency data

### ISSUE THREAD

**Issue by miniTsl** [google/perfetto#862]
I am using the following config to profile cpu frequency on my one plus 12 phone. There should be 8 cores but I just see 7 cpu frequency data in UI:

`duration_ms: 6000

buffers {
  size_kb: 655360
  fill_policy: RING_BUFFER
}

data_sources: {
    config {
        name: "android.power"
        android_power_config {
            battery_poll_ms: 250
            battery_counters: BATTERY_COUNTER_CHARGE
            battery_counters: BATTERY_COUNTER_CURRENT
            collect_power_rails: true
        }
    }
}

data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            ftrace_events: "sched/sched_switch"
            ftrace_events: "ftrace/print"
            ftrace_events: "power/cpu_frequency"
        }
    }
}`

<img width="1445" alt="image" src="https://github.com/user-attachments/assets/90800305-0f31-4f4b-8781-fb7665b43cf7">

**Comment by LalitMaganti** [comment]
Closing as without a trace, this bug cannot be actioned.
