### ISSUE TITLE
 fill_policy: DISCARD and RING_BUFFER setting is related with Callstack.

### ISSUE THREAD

**Issue by forrestxu123** [google/perfetto#863]
Callstack sampling call back works great.  but it is only available when
buffers: {
    size_kb: 1522240
    fill_policy: DISCARD
}
buffers: {
    size_kb: 4096
    fill_policy: DISCARD
} 
if fill_policy is set to RING_BUFFER, we can not see Callstack.

**Comment by LalitMaganti** [comment]
Please link your trace. This is impossible to debug without it.

There is no limitation on callstack profiling using DISCARD: we use ringbuffer callstack profiling all the time in Google.

**Comment by forrestxu123** [comment]
IF I USE ringbuffer, I CAN NOT SEE  callstack profiling?

**Comment by LalitMaganti** [comment]
Closing as without a trace, this bug cannot be actioned.
