### ISSUE TITLE
Trying to visualize call stacks for synthetic perf samples

### ISSUE THREAD

**Issue by jordalgo** [google/perfetto#865]
I'm creating synthetic events (with protobuf) and I want to visualize call stacks; similar to what I get when I import `perf.data`. Can someone help me understand what's wrong with my interned data or what's wrong with the trace in general:
```
packet {
  trace_config {
    data_sources {
      config {
        name: "linux.perf"
        perf_event_config {
          timebase {
            frequency: 99
            counter: HW_CPU_CYCLES
          }
          callstack_sampling {
            kernel_frames: true
          }
        }
      }
    }
  }
}
packet {
  track_descriptor {
    uuid: 1
    thread {
      pid: 3601426
      tid: 3601426
      thread_name: "unknown"
    }
  }
}
packet {
  timestamp: 6191769066840960
  trusted_packet_sequence_id: 1
  interned_data {
    function_names {
      iid: 1
      str: "tomato"
    }
    function_names {
      iid: 3
      str: "banana"
    }
    function_names {
      iid: 5
      str: "donut"
    }
    frames {
      iid: 2
      function_name_id: 1
    }
    frames {
      iid: 4
      function_name_id: 3
    }
    frames {
      iid: 6
      function_name_id: 5
    }
    callstacks {
      iid: 7
      frame_ids: 2
      frame_ids: 4
      frame_ids: 6
    }
  }
  sequence_flags: 3
  previous_packet_dropped: true
  perf_sample {
    cpu: 73
    pid: 3601426
    tid: 3601426
    callstack_iid: 7
    timebase_count: 1
  }
  first_packet_on_sequence: true
}
packet {
  timestamp: 6191769069819568
  trusted_packet_sequence_id: 1
  sequence_flags: 2
  perf_sample {
    cpu: 73
    pid: 3601426
    tid: 3601426
    callstack_iid: 7
    timebase_count: 1
  }
}
packet {
  track_descriptor {
    uuid: 2
    thread {
      pid: 0
      tid: 0
      thread_name: "unknown"
    }
  }
}
packet {
  timestamp: 6191769072062719
  trusted_packet_sequence_id: 1
  sequence_flags: 2
  perf_sample {
    cpu: 19
    pid: 0
    tid: 0
    callstack_iid: 7
    timebase_count: 1
  }
}
packet {
  timestamp: 6191769075014611
  trusted_packet_sequence_id: 1
  sequence_flags: 2
  perf_sample {
    cpu: 73
    pid: 3601426
    tid: 3601426
    callstack_iid: 7
    timebase_count: 1
  }
}
```

Thanks in advance!

**Comment by LalitMaganti** [comment]
If you open the "Info and Stats" page, you'll see: 
![image](https://github.com/user-attachments/assets/5aa83c5c-d5fd-4d7c-b8de-3d8e3eb4ba12)

This indicates that you have not correctly setting the mapping for the frames (https://cs.android.com/android/platform/superproject/+/android14-qpr3-release:external/perfetto/protos/perfetto/trace/perfetto_trace.proto;l=11124?q=mapping%20f:proto%20f:perfetto%20perfSample).

As an aside though, the `perf_sample` protos are not really designed for external writers to synthesise. As you can see, it's very much optimized for the data that traced_perf is emitting, not really for other people to add. It's also not a stable format, we can and do regularly change these prptos (it's also why we don't publicise our internal protos).

I'm planing on creating some custom protos which are optimized for external writers which will populate all the right callstack tables and show the right stuff in the UI. I'd strongly suggest waiting for that (should happen within the next O(weeks)).

**Comment by jordalgo** [comment]
@LalitMaganti Thanks for the quick response. Yes, I just needed a dummy mapping id and now I see the stacks. Thank you!

> I'm planing on creating some custom protos which are optimized for external writers which will populate all the right callstack tables and show the right stuff in the UI. I'd strongly suggest waiting for that (should happen within the next O(weeks)).

That's awesome. Looking forward to it.

**Comment by TannerFirl** [comment]
@LalitMaganti , piggybacking off this issue: 2 related use cases to external tools wanting to create synthetic records:

* "Synthetic callstacks", i.e. visualizing instances of a callstacks (as I think @jordalgo suggested). There may be no "time" component per se, but it may be useful to place instances of the callstack within a sequence (e.g. sampling). Synthetic callstacks may also want to be associated with counters or flags.
* Visualizing instances of a frame. Consider a case where A calls B calls C, and A and C are traced. Begin/end times for B is unknown. External tools can create synthetic records for A and C, but an unaware user may not realize A doesn't call C (as would be suggested by the timeline) and that inclusive time for B is simply unknown. It could be helpful to have a "synthetic frame/function" to represent this behavior in a more intuitive manner. 

I'm relatively new to Perfetto, so forgive any naïvety!

**Comment by LalitMaganti** [comment]
> "Synthetic callstacks", i.e. visualizing instances of a callstacks (as I think @jordalgo suggested). There may be no "time" component per se, but it may be useful to place instances of the callstack within a sequence (e.g. sampling). Synthetic callstacks may also want to be associated with counters or flags.

Yeah I think we'll definitely support this. This is just classic "I want to synthesise" callstacks in a very similar vein to above.

> Visualizing instances of a frame. Consider a case where A calls B calls C, and A and C are traced. Begin/end times for B is unknown. External tools can create synthetic records for A and C, but an unaware user may not realize A doesn't call C (as would be suggested by the timeline) and that inclusive time for B is simply unknown. It could be helpful to have a "synthetic frame/function" to represent this behavior in a more intuitive manner.

I don't think we're in a place to support something like this atm. I think this is more educating people how tracing works (i.e. it is not going to capture all the frames in your stack, it's only selected frames the user has decided to instrument). I cover this in https://perfetto.dev/docs/tracing-101.
