### ISSUE TITLE
request feature for concurrent queries for python

### ISSUE THREAD

**Issue by uu9** [google/perfetto#866]
I need to query trace files and perform some analysis on them. Since these analyses are rather slow, I opted to use multithreading to process them. 
However, since each TraceProcessor requires loading the trace file anew, and given that the HTTP client (http.client.HTTPConnection) used by the TraceProcessor does not support concurrent requests, so the overall speed is slower than expected.
Any way to get through that？

**Comment by LalitMaganti** [comment]
No sorry there is no plans to support concurrency in trace processor for the foreseeable future. It would be an enormous project to do so and not worth the investment.
