### ISSUE TITLE
When Perfetto fails to parse Catapult json it needs to provide a line number

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#867]
The current dialog pops up with a generic message like it couldn't parse a key for a value.

Failure parsing JSON: encountered fatal error while parsing key for value.

This provides no info to the caller a to where or what to fix in the json to get the parsing to work.

**Comment by LalitMaganti** [comment]
Makes sense but this is just very low priority I'm afraid. As ever the JSON format is supported best effort

Generally you can debug these issues by parsing with any other tool (e.g. jq) and they'll be able to find the problem for you very quickly.

**Comment by alecazam** [comment]
Found the issue, it was a json key without quotes around it.   So looked valid, until I dropped it onto a json validator.

**Comment by LalitMaganti** [comment]
https://r.android.com/3241120 fixes this issue.
