### ISSUE TITLE
Support access to large trace loaded by trace_processor on other computer.

### ISSUE THREAD

**Issue by jabin-ma** [google/perfetto#87]
i have a very large file, but since I am used to using visualization trace.
but my windows computer does not have enough memory to run trace_processor and chrome at the same time.
so i want to load the trace file on a large memory server and then analyze it on my laptop(in LAN).
but the current design seems to be unable to modify the RPC URL directly through the UI.
hope to allow RPC URL modify in the UI.

**Comment by primiano** [comment]
It seems that the right answer for this is

1. Load the trace on the bulky workstation via trace_processor_shell --httpd large_trace_file
That will start trace_processor in HTTP+RPC mode on port 9001.

Then you can
2A: Open ui.perfetto.dev. If you TCP-forward (e.g. via SSH or any other TCP proxy) the 127.0.0.1:9001 port to the workstation's 9001 port, then the UI will automatically use that instead fo the built-in web assembly

2B: Use the Python API documented here: https://perfetto.dev/docs/analysis/trace-processor#python-api , look at the `addr=...` part

Closing for now given that there are two solutions. Feel free to reopen.

**Comment by fzyzcjy** [comment]
Hi, is it possible to use custom ports instead of forcing 9001? Thanks!

**Comment by LalitMaganti** [comment]
Covered by https://perfetto.dev/docs/visualization/large-traces#using-more-than-one-instance-in-parallel

**Comment by fzyzcjy** [comment]
Thank you!

**Comment by fzyzcjy** [comment]
@LalitMaganti Then I wonder, is it possible to directly point to a non-localhost url?

**Comment by LalitMaganti** [comment]
Support for this was landed recently but had to be reverted because it caused some problems (https://github.com/google/perfetto/commit/e528ca7e440c5380f6137a491b55dc31bdae94f5). We expect to relax some time next week.

**Comment by fzyzcjy** [comment]
Ah I see, looking forward to it and thanks again for the quick reply!
