### ISSUE TITLE
without non-io block reason

### ISSUE THREAD

**Issue by passionwang** [google/perfetto#870]
Hello, 
may I ask if I need a separate parameter to open the perfetto trace that I captured but cannot see the information of non-io block reason？

**Comment by LalitMaganti** [comment]
Kernel blocked function require the sched_blocked_reason ftrace event which is only available on Android, requires kernel symbolisation to be enabled and requires the use of userbebug builds. 

If any of these options are not used, unfortunately collecting blocked functions is not supported.

**Comment by passionwang** [comment]
Thank you, I already know the method
