### ISSUE TITLE
heap_profile tool does not work for my test app. but it works on system_server.

### ISSUE THREAD

**Issue by forrestxu123** [google/perfetto#873]
the following command works fine to me, which is good.  **$./heap_profile -n system_server**
Profiling active. Press Ctrl+C to terminate.
You may disconnect your device.

Waiting for profiler shutdown...
Wrote profiles to /var/folders/gr/0q820dg12v18st1tq_bb5ybh0000gn/T/242a7f (symlink /var/folders/gr/0q820dg12v18st1tq_bb5ybh0000gn/T/heap_profile-latest)
The raw-trace file can be viewed using https://ui.perfetto.dev.
The heap_dump.* files can be viewed using pprof/ (Googlers only) or https://www.speedscope.app/.
The two above are equivalent. The raw-trace contains the union of all the heap dumps.

However, I cannot use the tool in in my app. see below:
 **$adb shell ps | grep com.ss.android.test.app**
u0_a195      32039   355   37875664 606544 futex_wait          0 S com.ss.android.test.app
u0_a195      32242   355   33646544 148488 do_epoll_wait       0 S com.ss.android.test.app:feedbacker
u0_a195      32500   355   33599912 145208 do_epoll_wait       0 S com.ss.android.test.app:push

 **$./heap_profile -n "com.ss.android.test.app"** 
Profiling active. Press Ctrl+C to terminate.
You may disconnect your device.

Waiting for profiler shutdown...
No profiles generated
If this is unexpected, check https://perfetto.dev/docs/data-sources/ 
**I used emulator for testing. it is  a ANDROID 14 user debug emulator with selinux disabled (setenforce 0).**. $ adb shell su 0 getenforce,             it returns 
Permissive

**Comment by LalitMaganti** [comment]
There is no restriction on using Perfetto on the emulator (as you found, it works fine for system_server)

Few avenues to explore:
1) Please check logcat for logs with the "perfetto" tag to see if there is any information there.
2) Are you sure there is a native component to your app? It's not meaningful to use heapprofiling unless you have some native .so that you are trying to profile.
3) "It is a user debug emulator with selinux disabled (setenforce 0).": please double check this is true. heapprofd will not work on non-profilable apps unless you are on userdebug.

**Comment by forrestxu123** [comment]
1. Please check logcat for logs with the "perfetto" tag to see if there is any information there.
answer:
$./heap_profile -n com.ss.android.test.app
Another terminal:
$ adb logcat | grep perfetto
08-31 11:20:38.994  4583  4583 I perfetto:    perfetto_cmd.cc:1051 Connected to the Perfetto traced service, TTL: 1s
08-31 11:20:38.996   434   434 I perfetto: ng_service_impl.cc:1042 Configured tracing session 1, #sources:2, duration:1000 ms, #buffers:1, total buffer size:63488 KB, total sessions:1, uid:2000 session name: ""
08-31 11:20:39.052  4584  4584 I perfetto: approfd_producer.cc:245 Connected to the service, mode [central].
08-31 11:20:39.053  4584  4584 I perfetto: a_hprof_producer.cc:174 Connected to the service.
08-31 11:20:39.053  4584  4584 I perfetto: approfd_producer.cc:367 Setting up datasource: non-statsd initiator.
08-31 11:20:39.998   434   434 I perfetto: ng_service_impl.cc:2009 FlushAndDisableTracing(1) done, success=1
08-31 11:20:39.998  4584  4584 I perfetto: approfd_producer.cc:576 Stopping data source 3
08-31 11:20:39.998   433   433 I perfetto:  probes_producer.cc:454 Producer stop (id=2)
08-31 11:20:40.002  4583  4583 I perfetto:    perfetto_cmd.cc:1210 Trace written into the output file
08-31 11:20:40.003   434   434 I perfetto: ng_service_impl.cc:2553 Tracing session 1 ended, total sessions:0
08-31 11:20:41.137  4600  4600 W rm      : type=1400 audit(0.0:8): avc:  denied  { write } for  name="profile-b97d3a" dev="dm-39" ino=24708 scontext=u:r:shell:s0 tcontext=u:object_r:perfetto_traces_data_file:s0 tclass=file **permissive=0**

  2. 	Are you sure there is a native component to your app? It's not meaningful to use heapprofiling unless you have some native .so that you are trying to profile.  Yes.  
  3 ”. It is a user debug emulator with selinux disabled (setenforce 0).": please double check this is true. heapprofd will not work on non-profilable apps unless you are on userdebug.. Yes. It is usedebug  and selinux disabled.

**Comment by LalitMaganti** [comment]
```
08-31 11:20:41.137 4600 4600 W rm : type=1400 audit(0.0:8): avc: denied { write } for name="profile-b97d3a" dev="dm-39" ino=24708 scontext=u:r:shell:s0 tcontext=u:object_r:perfetto_traces_data_file:s0 tclass=file permissive=0
```

This line indicates that there is an problem with SELinux: likely this means SELinux is not actually disabled as you think. If it was, you either would not see this line or you would see `permissive=1` instead.

Please run the following:
```
adb root
adb shell setenforce 0
```

and rerun the script.

**Comment by forrestxu123** [comment]
**sorry.  previous log is selinux enabled. after set selinux to permissive mode (see the log is below. permissive=1 means selinux disabled.), I still can not get heap dump** 08-31 14:04:23.828  5355  5355 I perfetto:    perfetto_cmd.cc:1051 Connected to the Perfetto traced service, TTL: 1s
08-31 14:04:23.828   434   434 I perfetto: ng_service_impl.cc:1042 Configured tracing session 2, #sources:2, duration:1000 ms, #buffers:1, total buffer size:63488 KB, total sessions:1, uid:2000 session name: ""
08-31 14:04:23.878  5356  5356 I perfetto: approfd_producer.cc:245 Connected to the service, mode [central].
08-31 14:04:23.878  5356  5356 I perfetto: a_hprof_producer.cc:174 Connected to the service.
08-31 14:04:23.878  5356  5356 I perfetto: approfd_producer.cc:367 Setting up datasource: non-statsd initiator.
08-31 14:04:24.833   434   434 I perfetto: ng_service_impl.cc:2009 FlushAndDisableTracing(2) done, success=1
08-31 14:04:24.833  5356  5356 I perfetto: approfd_producer.cc:576 Stopping data source 6
08-31 14:04:24.834   433   433 I perfetto:  probes_producer.cc:454 Producer stop (id=5)
08-31 14:04:24.843  5355  5355 I perfetto:    perfetto_cmd.cc:1210 Trace written into the output file
08-31 14:04:24.843   434   434 I perfetto: ng_service_impl.cc:2553 Tracing session 2 ended, total sessions:0
08-31 14:04:25.997  5372  5372 I rm      : type=1400 audit(0.0:30): avc:  denied  { write } for  name="profile-bf6f89" dev="dm-39" ino=24708 scontext=u:r:shell:s0 tcontext=u:object_r:perfetto_traces_data_file:s0 tclass=file permissive=1

**Comment by LalitMaganti** [comment]
Sorry really not sure what's going on there. According to everything from the logs, the profiling was successful. No idea why the trace is not appearing. 

You can try and check in `/data/misc/perfetto-traces` if there are some files there the script is not finding.

**Comment by forrestxu123** [comment]
emu64a:/data/misc/perfetto-traces $ ls -l
total 8
drwxrwx-wx 2 root shell 4096 2024-08-12 15:01 bugreport
-rw------- 1 root root   825 2024-08-30 16:34 trace.perfetto-trace **small size of the file.**

**Comment by LalitMaganti** [comment]
Can you try another app, maybe `com.android.systemui`? system_server is quite special and I'd like to narrow down where the problem might be.

**Comment by forrestxu123** [comment]
canot see any thing, because of small size.  $ mkdir result
$ ./heap_profile -n com.android.systemui -o result
Profiling active. Press Ctrl+C to terminate.
You may disconnect your device.

Waiting for profiler shutdown...
Wrote profiles to result
The raw-trace file can be viewed using https://ui.perfetto.dev.
The heap_dump.* files can be viewed using pprof/ (Googlers only) or https://www.speedscope.app/.
The two above are equivalent. The raw-trace contains the union of all the heap dumps.
R3WW5TX90K:tools bytedance$ cd tool
-bash: cd: tool: No such file or directory
$ cd result
$ ls -l

total 72
-rwx------  1 bytedance  staff   7640 Aug 31 19:10 heap_dump.1.784.libc.malloc.pb.gz
-rw-r--r--  1 bytedance  staff  28392 Aug 31 19:10 raw-trace **//can not see anything. too small size.**
$ $  adb logcat | grep perfetto
08-31 19:10:54.481  7789  7789 I perfetto:    perfetto_cmd.cc:1051 Connected to the Perfetto traced service, TTL: 1s
08-31 19:10:54.482   434   434 I perfetto: ng_service_impl.cc:1042 Configured tracing session 8, #sources:2, duration:1000 ms, #buffers:1, total buffer size:63488 KB, total sessions:1, uid:2000 session name: ""
08-31 19:10:54.543  7790  7790 I perfetto: approfd_producer.cc:245 Connected to the service, mode [central].
08-31 19:10:54.544  7790  7790 I perfetto: approfd_producer.cc:367 Setting up datasource: non-statsd initiator.
08-31 19:10:54.551  7790  7790 I perfetto: a_hprof_producer.cc:174 Connected to the service.
08-31 19:10:54.552   784  7801 I perfetto: client_api_factory_android.cc:43 Constructing client for central daemon.
08-31 19:10:54.558   784  7801 I perfetto: client_api.cc:544 com.android.systemui: heapprofd_client initialized.
08-31 19:10:55.484   434   434 I perfetto: ng_service_impl.cc:2009 FlushAndDisableTracing(8) done, success=1
08-31 19:10:55.485  7790  7790 I perfetto: approfd_producer.cc:576 Stopping data source 24
08-31 19:10:55.485   433   433 I perfetto:  probes_producer.cc:454 Producer stop (id=23)
08-31 19:10:55.497  7790  7790 I perfetto: pprofd_producer.cc:1228 784 disconnected from heapprofd (ds shutting down: 1).
08-31 19:10:55.501  7789  7789 I perfetto:    perfetto_cmd.cc:1210 Trace written into the output file
08-31 19:10:55.502   434   434 I perfetto: ng_service_impl.cc:2553 Tracing session 8 ended, total sessions:0
08-31 19:10:56.800  7807  7807 I rm      : type=1400 audit(0.0:147): avc:  denied  { write } for  name="profile-6c25a0" dev="dm-39" ino=24708 scontext=u:r:shell:s0 tcontext=u:object_r:perfetto_traces_data_file:s0 tclass=file permissive=1

**Comment by LalitMaganti** [comment]
Hmmmmmmm seems like there might be something strange going on with your app specifically in that case, if systemui and system_server are both working.

The only other thing is to try a very very simple Android app with profilable by shell in the manifest set to true. Otherwise, I have to conclude the problem has to be on something your app is doing (maybe using a custom allocator perhaps?)

**Comment by LalitMaganti** [comment]
Also please do make sure that your app is actually doing some allocations/frees during the time period: if the app is not doing anything the profile *will be* empty because there is no allocations.

**Comment by forrestxu123** [comment]
"./java_heap_dump -n 'com.ss.android.test.app' -o result works fine. The app is complex and has native components, with some memory allocation and deallocation features. However, I am not sure if the app is allocating or freeing memory at the time I am capturing the data."

**Comment by LalitMaganti** [comment]
> "./java_heap_dump -n 'com.ss.android.test.app' -o result works fine.

This goes through a completely different codepath so unsurprising it works.

> However, I am not sure if the app is allocating or freeing memory at the time I am capturing the data."

Yeah this might actually be your problem: as I say, if there is no allocations/frees during the time you are profiling, the "No profiles generated" message is exactly what you would expect to see.

**Comment by forrestxu123** [comment]
thanks. " if there is no allocations/frees during the time you are profiling, the "No profiles generated" message is exactly what you would expect to see.".   so i have to setup timeout in order to get data? say --duration=60 or something else？ if i want to get many snaps continuously , what is the best command for "./java_heap_dump ?

**Comment by LalitMaganti** [comment]
> so i have to setup timeout in order to get data? say --duration=60 or something else？

It's not about timeouts, it's about the period of time you are tracing not having allocations. No matter how long you trace, if there are no memory allocations, then there will be no native heap profiling information. Unlike Java heap dumps, we do not "snapshot" the heap (it doesn't really make sense in C++ because nothing is tracking the state of the heap).

> what is the best command for "./java_heap_dump ?

You can use the `-c` flag for continuous dumps. Note that Java heap dumps are *huge* so it's a really bad idea to make this number small: you only want 2 or 3 heap dumps in a trace or you will run out of space very very quickly.

**Comment by LalitMaganti** [comment]
Closing this bug as I don't think there is anything wrong on the Perfetto side here: you just need to make sure there are native allocations during the time you are running the profile.
