### ISSUE TITLE
[Musl] [Clang]: Double definition of prctl_mm_map

### ISSUE THREAD

**Issue by Kawanaao** [google/perfetto#874]
Hello! Today on my Gentoo I tried to compile electron, which pulls in perfetto via chromium, and it seems that clang doesn't like these two imports, since they contain duplicate identical structures `prctl_mm_map`

https://github.com/google/perfetto/blob/5a10c63885c6a5a3825f1c15a08d4fff5ec41906/src/base/utils.cc#L43-L44

**Comment by LalitMaganti** [comment]
https://man7.org/linux/man-pages/man2/prctl.2.html according to the man page for prctl though, both of those includes needs to be specified. Feels like some bug in the compiler or musl more than in Perfetto?

**Comment by LalitMaganti** [comment]
My pure coincidence, seems like someone hit this internally and sent https://r.android.com/3252813 to fix. Closing this out.
