### ISSUE TITLE
import TraceProcessor error 

### ISSUE THREAD

**Issue by ajer001** [google/perfetto#875]
is anyone met following error in python perfetto 0.9.0 ?

from perfetto.trace_processor import TraceProcessor
from perfetto.trace_processor.api import TraceProcessor
from perfetto.common.exceptions import PerfettoException
E   ModuleNotFoundError: No module named 'perfetto.common

**Comment by LalitMaganti** [comment]
Apologies for the breakage: I've released a new pip package which fixes this issue.

**Comment by LalitMaganti** [comment]
https://pypi.org/project/perfetto/0.10.0/#history
