### ISSUE TITLE
Can't see mem information.

### ISSUE THREAD

**Issue by wangkai0055** [google/perfetto#876]
Hi:
I used the following configuration to capture.
Only GPU Memory can be seen.
Is there any kernel switch that needs to be turned on?

data_sources: {
    config {
        name: "android.gpu.memory"
    }
}

data_sources: {
    config {
        name: "linux.sys_stats"
        sys_stats_config {
            meminfo_period_ms: 96
            meminfo_counters: MEMINFO_MEM_AVAILABLE
            meminfo_counters: MEMINFO_MEM_FREE
            cpufreq_period_ms: 1000
        }
    }
}
Thanks

**Comment by LalitMaganti** [comment]
Please provide the trace and logcat of the "perfetto" tag around time when the trace was being collected: these sort of issues are impossible to debug without those. 

Also is there a reason why your period is 96ms without something a bit more round like 100? It just feels like a very weird number.

**Comment by wangkai0055** [comment]
96ms is a non-integer multiple of time.
The problem is solved after modification.
Thank you so much.
