### ISSUE TITLE
Incorrect sorting with X events and identical timestamps

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#878]
When sorting events, the longest duration with the same time should be sorted higher up.  But that doesn't happen with the current sorting algorithm.

loadFileFromArchive should be at the top, but is intermingled with the other events.   This is incorrect. ZipExtractRaw with the same ts but shorter dur is sorted to the top of the flamegraph.  

This should be an easy fix to the sort algorithm, and would make the display of events correct.   This happens a lot when writing out X/duration events, since the parents submit last.   And here the ts values have been clamped to a startTime.

```
{"traceEvents":[
{"name":"process_name","ph":"M","pid":0,"args":{"name":"kram"}}
{"name":"thread_name","ph":"M","tid":0,"args":{"name":"Main"}}
{"name":"ZipExtractRaw","ph":"X","tid":0,"ts":0.000073,"dur":0.000296}
{"name":"ZipExtractNormal","ph":"X","tid":0,"ts":0.000398,"dur":0.002120}
{"name":"KTXOpen","ph":"X","tid":0,"ts":0.002523,"dur":0.005340}
{"name":"KTXOpenNormal","ph":"X","tid":0,"ts":0.007869,"dur":0.005141}
{"name":"KTXLoad","ph":"X","tid":0,"ts":0.013019,"dur":0.001124}
{"name":"loadFileFromArchive","ph":"X","tid":0,"ts":0.000073,"dur":0.019487}
]}
```

Incorrect:
<img width="913" alt="image" src="https://github.com/user-attachments/assets/f02c756d-1965-4590-bef0-f6f160e7ae5c">

**Comment by alecazam** [comment]
Looks like no timestamp event sorting occurs, so it's wrong unless json is sorted prior.  But that's not how events write out.  This draws the loadFileFromArchive in the write order, but isn't how dtors that are scoping timings fire.   

```
{"traceEvents":[
{"name":"process_name","ph":"M","pid":0,"args":{"name":"kram"}}
{"name":"thread_name","ph":"M","tid":0,"args":{"name":"Main"}}

{"name":"loadFileFromArchive","ph":"X","tid":0,"ts":0.000073,"dur":0.019487}

{"name":"ZipExtractRaw","ph":"X","tid":0,"ts":0.000073,"dur":0.000296}
{"name":"ZipExtractNormal","ph":"X","tid":0,"ts":0.000398,"dur":0.002120}
{"name":"KTXOpen","ph":"X","tid":0,"ts":0.002523,"dur":0.005340}
{"name":"KTXOpenNormal","ph":"X","tid":0,"ts":0.007869,"dur":0.005141}
{"name":"KTXLoad","ph":"X","tid":0,"ts":0.013019,"dur":0.001124}

]}
```

**Comment by alecazam** [comment]
Sorry this is missing commas, so will fix and re-test.

**Comment by LalitMaganti** [comment]
Trace processor does sort on timestamp but it's sorts stably on JSON ingestion order.  is

We cannot change this without breaking how every other importer works, as always JSON will contub

**Comment by alecazam** [comment]
There's no way to add perf scopes to a C++ app in the order that is correct for Perfetto then.  Something has to do the sort.  The longest scopes will hit their dtor after the shorter ones, and then all those longer 'X' events come in in the reverse scope order.   If the caller has to sort, then they can't just open a json file output from the app.  The entire file would have to be sorted in order, then sent to Perfetto.

**Comment by LalitMaganti** [comment]
If you had unique timestamps this would not be a problem: the timestamp sort would fix everything. 

This is only a issue because you have non integral timestamps which end up not being unique.

**Comment by alecazam** [comment]
Ah, I probably need to write them * 1e6, not * 1e-6.   Let me try that.

**Comment by alecazam** [comment]
Still is incorrect without resolving ts ties based on dur.

```
{"traceEvents":[
{"name":"process_name","ph":"M","pid":0,"args":{"name":"kram"}},
{"name":"thread_name","ph":"M","tid":0,"args":{"name":"Main"}},

{"name":"ZipExtractRaw","ph":"X","tid":0,"ts":8,"dur":942},
{"name":"ZipExtractNormal","ph":"X","tid":0,"ts":954,"dur":917},
{"name":"KTXOpen","ph":"X","tid":0,"ts":1873,"dur":1166},
{"name":"KTXOpenNormal","ph":"X","tid":0,"ts":3039,"dur":507},
{"name":"KTXLoad","ph":"X","tid":0,"ts":3547,"dur":73},
{"name":"loadFileFromArchive","ph":"X","tid":0,"ts":8,"dur":4147},
]}
```

**Comment by LalitMaganti** [comment]
Right: ties are what I said we have difficulty dealing with because X events need to be handled differently to every other type of event: other events want to preserve the trace order, X events need to invert the order. 

The fact that you need to reverse for this one corner case is exactly what makes it complex.

**Comment by alecazam** [comment]
it's just adjusting the timestamp sort.  Aras does this in his clang analyzer, and I do it in kram-profile.

```
if ( lhs.ts == rhs.ts )
   return lhs.dur < rhs.dur

return lhs.ts < rhs.ts
```

**Comment by LalitMaganti** [comment]
When you are trying to sort O(millions) of events from n+ different data sources without using lots of memory, the complexity goes up significantly

Just to give you some context: this is where the comparison for sorting happens. https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/sorter/trace_sorter.h;drc=093006735bd0c003e4259dcc6fc677b1615b87b9;l=334

You can see here that the notion of duration doesn't exist. If we plumb it through to here, we add an extra 8 bytes per event which when you are talking about millions of events adds up in both memory cost and the cost of CPU cache misses when doing sorting. This code is extremely performance sensitive to memory layout of this event which is why we've spent a bunch of time tuning it (including doing bitpacking). 

So yeah form the outside it looks like "this is so simple" there are a bunch of constraints because we need to be fast and efficient on O(GB) traces that means it's not so easy.

**Comment by alecazam** [comment]
Thanks for the link and all your great responses.  Maybe adjusting the ts for values that are equal on the startTime is the best approach then.  It's just an edge case like you said, and only a few ts that pass that startTime.  My only concern is that timestamp resolution could also lead to this problem where ts match, but dur is longer.

**Comment by LalitMaganti** [comment]
> The secondary data (dur) is only needed if there are exact match ts values. So maybe memory could be reduced based on that.

But then you need to keep track of every unique timestamp you've seen until now which is still 8 bytes per event :)

Thinking more the real way to fix this is to turn X events into pairs of B and E events in trace processor. Really I should just do that, would be simple and would let me close this and another internal issue which found the same issue as this bug.

**Comment by alecazam** [comment]
Ah yes, that would.  But for now adjusting the ts, provided the stack isn't too deep is working for me.   Appreciate the advice.   

```
    // zero out the time, so times are smaller to store
    time -= _startTime;
    
    // problem with duration is that events can occur outside the start time
    bool isClamped = time < 0.0;
    if (isClamped) {
        elapsed += time;
        time = 0.0;
    }
    if (elapsed <= 0.0)
        return;
    
    // convert to micros
    time *= 100000;
    elapsed *= 100000;

    // Perfetto only sorts by ts and not dur, so have to fudge timings
    // or later/longer dur X events will be lower and overlap.  This
    // is because X events occur in reverse order from the scopes.
    if (isClamped) {
        time -= gPerfStackDepth;
        
        // this may go negative if stack is too deep
        if (time < 0)
            time = 0;
    }
```

**Comment by alecazam** [comment]
I used to profile with B/E, and using -timestampStart, +timestampEnd for each.  But this required tracking open B events on the stack, and closing them so that they were paired with E events in the file.  The nice thing about X events is even though they are out-of-order, they are atomic.  So they can be skipped based on stack depth, or file size, etc.

**Comment by LalitMaganti** [comment]
Yeah I mean you have strayed quite far from the default operating model these events were designed for (which is tracing the program execution in a ring buffer and capturing all the events in a given time region). 

If you are making arbitrary edits to the trace events, can appreciate the atomicity of X events make that easier. 

This is a very different philosophy to how we work in Perfetto: we always prefer to put as much data in the trace and do post processing (i.e. with SQL queries, debug tracks etc) to reduce the amount of data being visualized on demand. It's a much more flexible way to do things when you are collecting traces from thousands of devices and you don't have easy ways to change what you collect very quickly.

**Comment by alecazam** [comment]
So this error occurs regardless of the startTime clamping.  It can happen anywhere in the file due to timestamp (ts) snapping.  So if I snap to microsecond precision in the file, then there are ts that are not at or prior to 0 that I can add the above fudge of stackDepth.  So maybe the only solution is to switch off X events to B/E, or have the importer do that.  I've viewed many of our traces with this issue, and they are basically unreadable once this happens.  And there's no explicit flamegraph stack depth to fix it.

```
{"name":"ZipExtractRaw","ph":"X","tid":0,"ts":2,"dur":746},
{"name":"loadFileFromArchive","ph":"X","tid":0,"ts":2,"dur":3964},
```

**Comment by LalitMaganti** [comment]
> have the importer do that

I did look at having importer do this and unfortunately it's not quite that easy: since you want to invert the sort order for X events, you actually do need to make changes to the `TimestampedEvent` struct and that will slow down sorting for every other type of event.

> Forcing callers to go to higher and higher precision timestamps to avoid this problem isn't ideal for file size

Only a problem because you are using JSON tbh, if you were using a binary encoding format this would be non-issue (i.e. your files with be a lot closer to the post-compression size than the precompression one)

> at some point, the timestamps run out of precision.

Yeah but in practice, if you are operating at nanoseconds, you will probably not have clashes anymore.

**Comment by alecazam** [comment]
The problem of sorting by duration falls on someone since ts can match up.  There are timers accurate to millis, micros, and nanos.  So ultimately there's going to be an overlap.  I just store the X events, and do the sort in my tools.  But that's the only way to have them be accurate.  And I'm talking about a few KB to 140MB captures, but the bulk are under 1MB.  They're all wrong and jumbled without the dur sorting.  

And clang is using the X events too, so this json is used in multiple utilities.   

```
std::sort(sortedIndices.begin(), sortedIndices.end(), [&](EventIndex ia, EventIndex ib){
        const auto& ea = events[ia];
        const auto& eb = events[ib];
        if (ea.ts != eb.ts)
            return ea.ts < eb.ts;
        // break start time ties by making longer events go first (they must be parent)
        if (ea.dur != eb.dur)
            return ea.dur > eb.dur;
        // break ties by assuming that later events in sequence must start parent
        return ia > ib;
    });
```

**Comment by LalitMaganti** [comment]
https://r.android.com/3254683 fixes this issue for good.

**Comment by alecazam** [comment]
It seems the sdk (perfetto.cc/h) is 10mb of source in 2 files.  So that's probably why I've avoided add it.  Writing the json is like 5 sprintfs.

**Comment by LalitMaganti** [comment]
You don't need the C++ SDK if you are synthetically generating traces: you just need to generate protobufs (using whatever language you want) according to https://perfetto.dev/docs/reference/synthetic-track-event

>  Writing the json is like 5 sprintfs.

Sure but then your traces are 10x bigger than the protobufs, you have to pay the cost somewhere or another :)

**Comment by alecazam** [comment]
Thanks I was going to pitch an interning for json.   But maybe if I can write my own protobuf binary data (f.e. kiwi) in a lot less code than the sdk, then that's another approach.

define the name id (only for events)
ph:"X", nid: id, name:"foo", ts: ..., dur:

ref the string
ph:"X", nid: id, ts: ..., dur:...

**Comment by LalitMaganti** [comment]
> Thanks I was going to pitch an interning for json. 

I think there's still value in this idea as it keeps an easy on-ramp for people migrating to Perfetto.

Taking a step back, one criticism of  https://perfetto.dev/docs/reference/synthetic-track-event is that it is difficult to write synthethcially. This mainly comes from the fact that this is optimized for people tracing their own C++ libraries/binaries with the Perfetto SDL with very low overhead. For that reason, it tries to be very implicit and thus is difficult to write for other poeple.

@primiano and I were discussing coming up with a new lightweight format which is optimised for people synthesising/converting traces. It would port a lot of the features of track_event (interning, delta timestamps) without the difficulties. We *believe* it is possible for this to be a dual JSON/protobuf format with the same structure and semantics. JSON could be used for those people who value ease of writing more than absolute smallest size. protobuf could be usefor those who want the smallest size or the strongly typed schema checking.

The tokenization, parsing and semantics between protobuf/JSON in this new format would be identical. We'd also autogenerate bindings for C++/Java/Kotlin/Python for people who want to just want to drop in a library to their project.

This is something I'm looking to build in the coming months. It's quite a big undertaking but I think it could provide a lot of value for bringing people into the Perfetto ecosystem.

**Comment by alecazam** [comment]
That sounds awesome.  I was working on my own tight binary format for traces, and then I'd convert that to Catapult json.  I'd looked at that page, and then looked at Protobufs, but it was a large codebase to build.  Today was my first look at the 2 sdk files.  The sdk at least has it all in C++, but I already have my own trace macros throughout, and just want to pass the data onto Perfetto.  So the json with gz (or zip) compression is a pretty small.  

I think one issue with json is that you end up wanting to store time deltas and intern to reduce bytes, where the delta maybe are less important for binary (but still help with compressed binary).  Also since most impls can accumulate timestamps, the export could ensure that events are all from the same tid, and so skip writing redundant data.
