### ISSUE TITLE
Perfetto json formatting doesn't display readable millisecond timings.

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#879]
Here's a file where I write mllisecond timings to a file.  Yes. the json is supposed to be in microseconds.  But Perfetto has the "raw" timestamp format which should show 52.497, but instead shows and adjusts the timeline to scale 52497.  This ignores the decimal point.  The graph then isn't marked to the correct millisecond timings.   

So these are being converted to nanos and displayed as such, but that wasn't the goal of the original output.  So raw really mean nanos, not the raw values in microseconds.  But then there isn't a microsecond scale which would also fix this.

Trying to use the seconds formatter, these display as [0.0052497 s] if I write them as the expected microsecond integers.  Which also isn't a great scale either.   

I've brought this up in past issues, that the time formatting is missing a milliseconds (and microseconds but I never work in those) format which is how I time most rendering.  We deal with 30Hz to 240Hz displays.   

```
{"traceEvents":[
{"name":"process_name","ph":"M","pid":0,"args":{"name":"kram"}},
{"name":"thread_name","ph":"M","tid":0,"args":{"name":"Main"}},
{"name":"ZipExtractRaw","ph":"X","tid":0,"ts":0.022,"dur":0.239},
{"name":"ZipExtractNormal","ph":"X","tid":0,"ts":0.285,"dur":28.678},
{"name":"KTXOpen","ph":"X","tid":0,"ts":28.971,"dur":12.621},
{"name":"KTXOpenNormal","ph":"X","tid":0,"ts":41.597,"dur":4.950},
{"name":"KTXLoad","ph":"X","tid":0,"ts":46.549,"dur":0.650},
{"name":"loadFileFromArchive","ph":"X","tid":0,"ts":0.021,"dur":52.497},
]}
```

<img width="932" alt="image" src="https://github.com/user-attachments/assets/5a749e54-a1d0-4197-8991-0f2b445458d5">

**Comment by LalitMaganti** [comment]
https://r.android.com/c/3259031 changes "Raw" -> "Trace nanoseconds" which is a more accurate reflection of what the option is doing.

https://r.android.com/c/3256641 adds support for milliseconds and microseconds formatting for timestamps and durations.

**Comment by alecazam** [comment]
Just make sure the hover tip reflects the correct unit if you didn't do so already.  That's a critical utility for me, and I'm really pleased that was added.
