### ISSUE TITLE
customize some information

### ISSUE THREAD

**Issue by wangkai0055** [google/perfetto#881]
Hi:
Just like the message below:
Misc Global Tracks
  MemAvailable
  MemFree
For easier analysis, we customize some information.

PD2339:/ #  cat /sys/rsc/system_heap/memory_info
NR_ION:            837660 KB
pool_free:         265240 KB
file_cache:        5910784 KB
defer list:        0 KB

How to add it to the trace?
Thanks.

**Comment by LalitMaganti** [comment]
The suggestion is to send a patch changing the Perfetto source code to collect these new events. We accept patches like this all the time.

For example recently we accepted https://r.android.com/c/3210391/6  for collecting /sys GPU frequency counters.

Please follow the process at https://perfetto.dev/docs/contributing/getting-started#contributing to do this.
