### ISSUE TITLE
irq swim lane not being shown in latest perfetto UI

### ISSUE THREAD

**Issue by rperi3679** [google/perfetto#882]
The IRQ slices not being displayed in the latest perfetto UI. They used to show up in the older versions of UI as shown in the attached screenshot.

![Screenshot 2024-09-09 at 9 50 14 AM](https://github.com/user-attachments/assets/64ecf8c3-b851-4571-944e-bfd9bf6c4d3b)

**Comment by LalitMaganti** [comment]
This was found internally as well, b/364855293. We'll be fixing this ASAP.

**Comment by rperi3679** [comment]
Any idea how to use an old version of the perfetto UI ? I always seem to get the latest version of the UI when i go for ui.perfetto.dev.

**Comment by LalitMaganti** [comment]
On ui.perfetto.dev, you can switch to the stable or canary branches which should not have this issue.

**Comment by LalitMaganti** [comment]
I take it back, this is affecting all currently released versions of the UI.

To go back to the previous version of the UI while you wait for this to be fixed you can use https://ui.perfetto.dev/v45.0-c4577456a/
