### ISSUE TITLE
How to control tracks sorting in perfetto UI

### ISSUE THREAD

**Issue by wangjiyang** [google/perfetto#885]
Hi,

I am trying to write TrackEvent by python converted from other data formats. By taking advantage of perfetto UI, everything seems works fine. However, I found I am unable to control Track sorting by TracePacket emited in perfetto trace file. Eg, the following thread sorting,  and also process sorting, is it able to be controled by track packets or other thing?

![image](https://github.com/user-attachments/assets/dd61da1b-643a-4fa1-9e6e-6d963adc1392)

Thanks

**Comment by LalitMaganti** [comment]
This is WAI. We intentionally separate the format of traces from their visualization to allow the same trace to be visualized in many different ways. 

In coming weeks, we'll be adding options in the UI so you can control how tracks are sorted.

**Comment by LalitMaganti** [comment]
This has been discussed in the past many times btw: https://github.com/google/perfetto/issues/378, https://github.com/google/perfetto/issues/555 for example

**Comment by wangjiyang** [comment]
Could you share some more details of your design/plan, so I can decide if
waiting for this feature or search some alternatives. Thanks.

Lalit Maganti ***@***.***> 于 2024年9月12日周四 20:42写道：

**Comment by LalitMaganti** [comment]
The plan is to add a bunch of sort types which people will generally find useful. Concretely, we'll definitely want the following:
1) Earliest event on track ordered first
2) By name
3) By event count
4) By tid

Suggestions on additional sorting types after those are implemented are welcome.

**Comment by wangjiyang** [comment]
My suggestion is to add an additional field specifically for sorting, which
is independent of the name, event count, tid, and other information. This
field would be an associated field of the track_event, allowing for more
customized sorting rules. This approach would also improve compatibility.

Lalit Maganti ***@***.***> 于 2024年9月13日周五 08:56写道：

**Comment by LalitMaganti** [comment]
I think we're pretty set on *not" doing that. As I've pointed out in the several bugs above, the decision to separate UI visualizations from trace contents was a very intentional one.

**Comment by wangjiyang** [comment]
I mean sort tracks by this associated field, not controling sorting by this
field. Think of SQL order by sementics like `select name, height from
student_table order by age`, here age is an associated internal field.

If that is not possible, what about sorting tracks by mouse drag and drop?

Lalit Maganti ***@***.***> 于 2024年9月21日周六 17:56写道：

**Comment by LalitMaganti** [comment]
> I mean sort tracks by this associated field, not controling sorting by this field.

I think we'd be open to supporting something like this. We need to figure out exactly how the mapping between the protos and the UI happens but seems possible.
