### ISSUE TITLE
Not able to view synthetic track events in the UI

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [google/perfetto#887]
Hello,

I'm trying to produce synthetic track events for one of my projects based on the instructions here - https://perfetto.dev/docs/reference/synthetic-track-event#process-scoped-async-slices

I have tried using both to produce protobuf files that look like the sample given in the reference doc but the events are not getting displayed in the UI. Here's a sample protobuf that I've been trying to get view in the UI - [https://github.com/ArulselvanMadhavan/toposim/blob/main/toposim.perfetto](url)

Any assistance in debugging or making this viewable in the UI would be a great help! I have tried viewing protobuf viewers on this file and it looks like the sample given in the doc. 

Thank you!

**Comment by LalitMaganti** [comment]
I had a look at you trace and I see there is use of the timestamp_clock_id field but no ClockSnapshot packets which tell us how these packets should be converted to trace time.

Please either remove the use of that field or emit a ClockSnapshot at the start of the trace which tells us how to convert all times into CLOCK_BOOOTIME (the default clock of all traces).
