### ISSUE TITLE
Error run metric android_startup in PerfettoUI

### ISSUE THREAD

**Issue by jabin-ma** [google/perfetto#89]
when the trace file is opened, the following metric will be automatically executed:
android_startup'
'android_ion'
'android_thread_time_in_state'
'android_surfaceflinger'
'android_batt'
'android_sysui_cuj'
causes these metrics can't be run again later via PerfettoUI -> Metric  and see output.
because when the trace file is opened  the table has already been created.

![image](https://user-images.githubusercontent.com/6481645/104092594-e6d6cc80-52bf-11eb-8efc-136d28cbc371.png)

**Comment by primiano** [comment]
@deepanjanroy @LalitMaganti  I know we discussed this and a systematic fix is hard.
meanwhile can we just add "DROP VIEW IF NOT EXISTS" to all these metrics? (internal bug b/170483683)

**Comment by LalitMaganti** [comment]
Fixed in the above commit. This should roll to the UI in a few days time.
