### ISSUE TITLE
perfetto 打开蓝屏

### ISSUE THREAD

**Issue by Seal-z** [google/perfetto#890]
Perfetto UI - An unrecoverable problem occurred

If you are seeing this message, something went wrong while loading the UI.
In most cases this is due to very slow or flaky network and it goes away by
disabling and re-enabling WiFi or trying reloading.

If the problem persists try these remediation steps:

* Force-reload the page with Ctrl+Shift+R (Mac: Meta+Shift+R) or
  Shift + click on the refresh button.

* [Clear all the site storage and caches](javascript:clearAllCaches();) and reload the page.

* Clear the site data and caches from devtools, following [these instructions](https://developers.google.com/web/tools/chrome-devtools/storage/cache#deletecache).

If none of this works, file a bug attaching logs and screenshots from devtools.
  Googlers:      [go/perfetto-ui-bug](http://go/perfetto-ui-bug)
  Non-googlers:  [github.com/google/perfetto/issues/new](https://github.com/google/perfetto/issues/new)

Uncaught ReferenceError: structuredClone is not defined

Technical Information:
LocalStorage: {"recordConfigs":"[]"}

**Comment by LalitMaganti** [comment]
Please update your browser: your browser version is too old as all modern browsers support the structurdClone feature the UI is crashing on: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
