### ISSUE TITLE
Flows for pinned tracks not working

### ISSUE THREAD

**Issue by ajanicijamd** [google/perfetto#898]
It looks like a regression: the latest Perfetto release does not behave the same way regarding showing event flow in the UI: when I open a trace in ui.perfetto.dev and pin two tracks, event flow is not shown in the section that displays pinned tracks. But when I open the same trace in the older version [https://ui.perfetto.dev/v46.0-35b3d9845/#!](https://ui.perfetto.dev/v46.0-35b3d9845/#!), event flow is shown.

## Steps to reproduce

- Open [https://ui.perfetto.dev/#!](https://ui.perfetto.dev/#!) in the browser.
- Click on Open Trace file and select a file.
- Pin some tracks.
- Click on an event to show event flow.

Expected: Event flow is shown in the section with the pinned tracks.
Actual: Event flow is shown in v46, but not in the latest release.

[https://ui.perfetto.dev/#!](https://ui.perfetto.dev/#!):

![2024-09-26-p1](https://github.com/user-attachments/assets/7eb88b39-d07a-467a-b3c5-038addabc63c)

[https://ui.perfetto.dev/v46.0-35b3d9845/#!](https://ui.perfetto.dev/v46.0-35b3d9845/#!):

![2024-09-26-p2](https://github.com/user-attachments/assets/dc57060b-6f76-48ae-b283-d00a311bd4d9)

**Comment by LalitMaganti** [comment]
@stevegolton

**Comment by LalitMaganti** [comment]
Yup I can repro on stable canary and autopush. Agree this is a regression and we should fix.

**Comment by stevegolton** [comment]
Good catch! A fix should be rolling out to all channels tonight or tomorrow.

**Comment by ajanicijamd** [comment]
Thanks! I can confirm that the fix is in ui.perfetto.dev.

**Comment by stevegolton** [comment]
Thanks for confirming
