### ISSUE TITLE
crash in function : NameMatchesPatternList

### ISSUE THREAD

**Issue by ChunelFeng** [google/perfetto#899]
hi, find a coredump question, have you ever meet?

when a kill a perfetto process to catch buffer, the process use write_api sometimes coredump on this function.
about happen once in 100 times dump file.

<img width="1304" alt="image" src="https://github.com/user-attachments/assets/41721b20-b52d-4776-93c3-1dc55e5b82e4">

we see that , patterns is error address.

<img width="1578" alt="image" src="https://github.com/user-attachments/assets/49242d78-b833-41a1-b3f3-f005b2052b0b">

config file is :

```bash
duration_ms: 0

incremental_state_config: {
  clear_period_ms: 500
}

buffers {
  size_kb: 96605
  fill_policy: RING_BUFFER
}


data_sources {
  config {
    name: "linux.ftrace"
    target_buffer: 0
    ftrace_config {
      drain_period_ms: 120
      compact_sched: {
        enabled: true
      }
    ftrace_events: "sched/*"
    ftrace_events: "irq/*"
    ftrace_events: "task/task_newtask"
    ftrace_events: "task/task_rename"
    }
  }
}

# User-defined data source
data_sources: {
    config {
        name: "track_event"
         track_event_config {
           enabled_categories: "ros2"
           enabled_categories: "fastdds"
           enabled_categories: "percep"
           enabled_categories: "pnc"
           enabled_categories: "hmi"
           enabled_categories: "sensor"
         }
        target_buffer: 0
    }
}

...

```

**Comment by LalitMaganti** [comment]
From what I know, we've never observed any similar crash and we trace a *lot*. Maybe @ddiproietto would have ideas.

**Comment by ddiproietto** [comment]
Thanks, no I've never observed a crash like this.

Can I ask you to share more?

* Can you copy paste the backtrace (at least the top of the stack with perfetto functions)
* Can you confirm the exact version of perfetto.h and perfetto.cc you're using?
* Can you share the line of your code that calls into perfetto on that backtrace? i.e. `TRACE_EVENT("category", ...)`
* If the "category" you're using a static or dynamic category (https://perfetto.dev/docs/instrumentation/track-events#dynamic-and-test-only-categories)? I.e. is the category you're using registered beforehand with `PERFETTO_DEFINE_CATEGORIES`?

Thanks

**Comment by ChunelFeng** [comment]
thank you very much.

some private code,  no good to show here.

can you send me your email, i well send details to you if it helps.

case the question is very low frequency occurs,
so i think we use PERFETTO_DEFINE_CATEGORIES registered correct.

**Comment by LalitMaganti** [comment]
Please send it to lalitm@google.com. I can forward to @ddiproietto and anyone else necesssary.

**Comment by ChunelFeng** [comment]
@LalitMaganti 

hi, send some important info to your email,
thanks for your help.

**Comment by LalitMaganti** [comment]
I've forwarded to ddiproietto.

**Comment by ChunelFeng** [comment]
thank you

**Comment by ChunelFeng** [comment]
hi, @ddiproietto   any new message?

**Comment by ddiproietto** [comment]
You mentioned that you're using v30.0, which is quite old at this point

Can you try with a more recent version? I suspect https://r.android.com/2406614 could be related.

Otherwise, with the info we have it's hard to understand what the problem could be.

**Comment by ChunelFeng** [comment]
many teams in company use this sdk together,
is is not easy to update perfetto version.

i write a simple perfetto write demo with asan, 
will provide more detail info when it crash.
please hold on this issue

and i will try to review the code.

**Comment by ChunelFeng** [comment]
> You mentioned that you're using v30.0, which is quite old at this point
> 
> Can you try with a more recent version? I suspect https://r.android.com/2406614 could be related.
> 
> Otherwise, with the info we have it's hard to understand what the problem could be.

i tried this method , still crashed at same point.

any article help me to know how `--config file info` worked and passed from perfetto to traced in my process?

**Comment by LalitMaganti** [comment]
> any article help me to know how `--config file info` worked and passed from perfetto to traced in my process?

https://perfetto.dev/docs/concepts/service-model is probably what you are looking for.

**Comment by ChunelFeng** [comment]
please tell me, is there any diff between i send sigterm and sigint to perfetto process by python?

```python
os.kill(perfetto_pid, signal.SIGINT)


os.kill(perfetto_pid, signal.SIGTERM)
```

something i can not understand.

**Comment by LalitMaganti** [comment]
There is no difference between INT and TERM for Perfetto. The important thing is that you wait for perfetto exiting by polling /prod/pid/status before you try and read the file.

**Comment by ChunelFeng** [comment]
the reason we think is:

we trigger dump.gz by kill perfetto process. 
and then, we restart perfetto process to wait for next tirgger source to catch.

>perfetto --txt --config test.cfg

in this trigger moment, perfetto process will send cfg info to clients

clients get this cfg info in function:
![Image](https://github.com/user-attachments/assets/8432fef3-dcb4-408a-9d27-83b052be8fe1)

this time, config_ will be changed.
and at the same time, client run: IsDynamicCategory()->NameMatchesPatternList(), which use config.enabled_categories().

so it crashed for the reason of multi thread write+read.

am i right?
do you think i can avoid this by using flowing code if my config file never changed?

```cpp
  void OnSetup(const DataSourceBase::SetupArgs& args) override {
    if (cfg_set_index_.load() == 0) {
      auto config_raw = args.config->track_event_config_raw();
      bool ok = config_.ParseFromArray(config_raw.data(), config_raw.size());
      PERFETTO_DCHECK(ok);
      cfg_set_index_.store(1);
    }

    TrackEventInternal::EnableTracing(*Registry, config_, args);
  }
```

**Comment by LalitMaganti** [comment]
That seems a pretty ugly hack. If there is a data race, we should really fix it rather than hacking around it.

Can you please confirm you tried witth the latest version of the SDK and were still seeing the same issue?

**Comment by ChunelFeng** [comment]
yes, i know it is ugly hack. because i can not understand the code as clear as you.

if you also think this sence may happen（coredump really happen every night's presure test in my env at func NameMatchesPatternList), hope you can fix or avoid it.

and sorry for cannot update perfetto version in my env,
too much related work must do around update,
and many other colleagues may challenge at the same time.

**Comment by LalitMaganti** [comment]
Well in that case it's very possible that the updated version would fix the issue as it's also solving a data race in the same area. 

I think I'd the hack works for you, feel free to use it. I'll close our this bug because without a repro on a new version of the code, we cannot investigate.

**Comment by ChunelFeng** [comment]
sorry, my words is not right. i fix codes like this:

```cpp
  // DataSource implementation.
  void OnSetup(const DataSourceBase::SetupArgs& args) override {
    protos::gen::TrackEventConfig tmp_cfg;
    auto config_raw = args.config->track_event_config_raw();
    bool ok = tmp_cfg.ParseFromArray(config_raw.data(), config_raw.size());
    PERFETTO_DCHECK(ok);
    if (config_.enabled_categories().size() != tmp_cfg.enabled_categories().size()) {
      // cfg is always same, i think this code only run once
      config_ = tmp_cfg;
    }
    TrackEventInternal::EnableTracing(*Registry, tmp_cfg, args);
  }
```

but the code still crash at the same time.

please reopen this issue, i need more time to comfirm this question, and your help.

**Comment by LalitMaganti** [comment]
To be clear it's impossible for us to help more unless you have a repro on a new version of the SDK. We do not have the bandwidth to support a year+ old versions of the SDK.

**Comment by ChunelFeng** [comment]
hi, we find in the newest version(2023/11/22) add the code to check if ds is valid(),
it probability the root case of our crash.

i fix the code, and begin to do our presure test as last night.

![Image](https://github.com/user-attachments/assets/7bab81a3-3160-4912-b4b4-0087c4c8d3f6)

and i want to know, in which case may leads ds is null ? 

`auto ds = ctx->GetDataSourceLocked();`

**Comment by LalitMaganti** [comment]
The reason for it being null is described at https://source.chromium.org/chromium/chromium/src/+/main:third_party/perfetto/include/perfetto/tracing/data_source.h;l=317;drc=d4a7d3fb6f5100019d6153d5cf00c60f06b1d0a2

Seems like https://r.android.com/2843534 landed late last year fixing this issue. You should be safe to cherry-pick that CL in to your SDK to fix the crash you are seeing.

This is precisely why I say that we cannot support 1+ year old SDK versions: it's very likely that things will have been fixed in the mean time and we cannot do remote bisection support.

Closing this out as it's clear now that this is just an issue which has been fixed for ~1 year.

**Comment by ChunelFeng** [comment]
sorry for cannot open the page.
 https://source.chromium.org/chromium/chromium/src/+/main:third_party/perfetto/include/perfetto/tracing/data_source.h;l=317;drc=d4a7d3fb6f5100019d6153d5cf00c60f06b1d0a2

may i just think:
data source will be create when i really start trace, and will be remove when i finish trace.
when i remove the data source, the ctx->GetDataSourceLocked() function will return null.

in a very small memont, client with perfetto sdk may still write after the data source removed,
so the function return val is null, and ds->config_ is also null, so it crashed.

**Comment by ChunelFeng** [comment]
ok, i see the page in my computer. thank you, it works well in 3 hours.
we still keep testing.


![Image](https://github.com/user-attachments/assets/f2124f0f-28a2-42c9-b654-af1259496280)
