### ISSUE TITLE
No Data Returned from wattson.system_state Query

### ISSUE THREAD

**Issue by ye3084** [google/perfetto#900]
Hello, I am trying to retrieve L3 data from a trace, so I checked the documentation and found that I could query the wattson.system_state table. I used the following query:
```sql
INCLUDE PERFETTO MODULE wattson.system_state;
SELECT * FROM wattson_system_states;
```
However, I received no data (0 rows returned).

Then, I looked into the files under perfetto-main\src\trace_processor\perfetto_sql\stdlib\wattson and tried executing the queries found there. I noticed that many of the tables were empty. For example:
```sql
SELECT
  ts, dur, TRUE AS suspended
FROM slice
WHERE name GLOB "timekeeping_freeze(0)";
```
I consulted ChatGPT, and it suggested adding the following lines to the config.pbtx file, but they didn’t seem to work:
```
ftrace_events: "power/suspend_resume" 
ftrace_events: "timekeeping/timekeeping_freeze" 
ftrace_events: "timekeeping/timekeeping_thaw"
```

**Comment by LalitMaganti** [comment]
I don't think the bulk of Wattson is what you're looking for: it's about estimating the CPU power draw by looking at characteristics of the device by looking at things like scheduling, CPU frequency, L3 data rates etc (see https://lpc.events/event/18/contributions/1842/ for more info). Specifically, it requires device-specific curves to be present which do not exist for all devices, only for certain devices (see https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/perfetto_sql/stdlib/wattson/curves/device.sql)

However, you *could* copy the queries from (https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/perfetto_sql/stdlib/wattson/arm_dsu.sql) and that might give you what you are looking for.  Really though we should extract those into proper modules in the standard library.

**Comment by ye3084** [comment]
@LalitMaganti 
Thank you for your response. I reviewed arm_dsu.sql and ran the following query:
```sql
CREATE PERFETTO FUNCTION _get_rate(event STRING)
RETURNS TABLE(ts LONG, dur INT, access_rate INT)
AS
SELECT
  ts,
  lead(ts) OVER (PARTITION BY track_id ORDER BY ts) - ts AS dur,
  -- Rate of event accesses in a section (i.e. count / dur).
  value / (lead(ts) OVER (PARTITION BY track_id ORDER BY ts) - ts) AS access_rate
FROM counter AS c
JOIN counter_track AS t
  ON c.track_id = t.id
WHERE t.name = $event;


SELECT
  ts, dur, access_rate AS l3_miss_rate
FROM _get_rate("arm_dsu_0/bus_access/_cpu0");
```
However, I still didn't receive any data. It seems this query might require support for the ARM DSU PMU, so I checked the list of PMU events using simpleperf list and only found ARMv8 PMUv3-related events:
```
  armv8_pmuv3/br_mis_pred/
  armv8_pmuv3/br_mis_pred_retired/
  armv8_pmuv3/br_pred/
  armv8_pmuv3/br_retired/
  armv8_pmuv3/bus_access/
  armv8_pmuv3/bus_cycles/
  armv8_pmuv3/cid_write_retired/
  armv8_pmuv3/cnt_cycles/
  armv8_pmuv3/cpu_cycles/
  armv8_pmuv3/dtlb_walk/
  armv8_pmuv3/exc_return/
  armv8_pmuv3/exc_taken/
  armv8_pmuv3/inst_retired/
  armv8_pmuv3/inst_spec/
  armv8_pmuv3/itlb_walk/
  armv8_pmuv3/l1d_cache/
  armv8_pmuv3/l1d_cache_lmiss_rd/
  armv8_pmuv3/l1d_cache_refill/
  armv8_pmuv3/l1d_cache_wb/
  armv8_pmuv3/l1d_tlb/
  armv8_pmuv3/l1d_tlb_refill/
  armv8_pmuv3/l1i_cache/
  armv8_pmuv3/l1i_cache_lmiss/
  armv8_pmuv3/l1i_cache_refill/
  armv8_pmuv3/l1i_tlb/
  armv8_pmuv3/l1i_tlb_refill/
  armv8_pmuv3/l2d_cache/
  armv8_pmuv3/l2d_cache_allocate/
  armv8_pmuv3/l2d_cache_lmiss_rd/
  armv8_pmuv3/l2d_cache_refill/
  armv8_pmuv3/l2d_cache_wb/
  armv8_pmuv3/l2d_tlb/
  armv8_pmuv3/l2d_tlb_refill/
  armv8_pmuv3/l3d_cache/
  armv8_pmuv3/l3d_cache_allocate/
  armv8_pmuv3/l3d_cache_lmiss_rd/
  armv8_pmuv3/l3d_cache_refill/
  armv8_pmuv3/ld_align_lat/
  armv8_pmuv3/ldst_align_lat/
  armv8_pmuv3/ll_cache_miss_rd/
  armv8_pmuv3/ll_cache_rd/
  armv8_pmuv3/mem_access/
  armv8_pmuv3/mem_access_checked/
  armv8_pmuv3/mem_access_checked_rd/
  armv8_pmuv3/mem_access_checked_wr/
  armv8_pmuv3/memory_error/
  armv8_pmuv3/op_retired/
  armv8_pmuv3/op_spec/
  armv8_pmuv3/remote_access/
  armv8_pmuv3/st_align_lat/
  armv8_pmuv3/stall/
  armv8_pmuv3/stall_backend/
  armv8_pmuv3/stall_backend_mem/
  armv8_pmuv3/stall_frontend/
  armv8_pmuv3/stall_slot/
  armv8_pmuv3/stall_slot_backend/
  armv8_pmuv3/stall_slot_frontend/
  armv8_pmuv3/sw_incr/
  armv8_pmuv3/ttbr_write_retired/
```
Does this indicate that my device doesn’t support DSU? If so, could I use armv8_pmuv3/bus_access/ as a substitute, or use Perfetto to directly collect data for the following events?
```
armv8_pmuv3/l3d_cache/
armv8_pmuv3/l3d_cache_allocate/
armv8_pmuv3/l3d_cache_lmiss_rd/
armv8_pmuv3/l3d_cache_refill/
```

**Comment by ye3084** [comment]
I have located the following directory on my device that contains PMU events:
```
/sys/bus/event_source/devices/armv8_pmuv3/events
```
How can I use Perfetto to collect this data?

**Comment by LalitMaganti** [comment]
OK actually it seems like this is injected by some sidechannel tool and that event I pointed you to is **not** natively collectible with Perfetto. So this was a total red herring and we should ignore anything with Wattson, everything they are doing is not really possible to replicate independently of collecting traces with them.

So unfortunately I have to say there's probably no easy way to collect this data with Perfetto. *Maybe* if you hack around with the [PerfEventConfig](https://perfetto.dev/docs/reference/trace-config-proto#PerfEventConfig) and raw perf counter configuration you collect the data directly from the hardware counter but that's well beyond our ability to support or guide for and would require significant tinkering on your side.

I'll be closing this issue because I think from our perspective, even though we could hypothetically invest a time to support this properly, it's not a high enough priority to do so in the near future.
