### ISSUE TITLE
pinned tab can not move the position

### ISSUE THREAD

**Issue by AlphaZhang1990** [google/perfetto#902]
![move](https://github.com/user-attachments/assets/3caca39b-a0fe-4ef4-b6e0-2bd1046e5eee)
In the old version, I can use mouse to change the pinned tab positon. But the new version, it doesn't work. The stable version can move but not work, the autopush version can not move.

**Comment by LalitMaganti** [comment]
Yup we're aware of the issue and will be fixing it before we roll autopush to canary/stable. @stevegolton

**Comment by stevegolton** [comment]
Hi @AlphaZhang1990,

Thanks for catching this!

A fix will land on autopush shortly, which will roll out to canary today or tomorrow.

I'll look into cherry-picking it for stable.
