### ISSUE TITLE
[feature request] Frame pointer unwinder support

### ISSUE THREAD

**Issue by simpleton** [google/perfetto#907]
Is there any plan to add support for a userspace frame pointer unwinder in the Perfetto project?

**Comment by LalitMaganti** [comment]
We don't have any existing plans to support frame pointer unwinding but we're open to contributions on it (actually on that point, I saw some CL in ci.perfetto.dev go by from an external contributor that I was hoping would be sent our way :))

**Comment by simpleton** [comment]
What is the recommended way to implement the frame pointer unwinder in Perfetto?

- Should we use the kernel’s perf_callchain with ustack?
- Or should we opt for a userspace frame pointer implementation similar to [aosp/3297215](https://android-review.googlesource.com/c/platform/external/perfetto/+/3297215)?

Any guidance on the preferred approach would be appreciated.

**Comment by LalitMaganti** [comment]
Is there any reason (beyond having to implement both) not have both as options? aosp/3297215 in particular seems very reasonable for option 2 to me but I could definitely imagine option 1 being useful for even higher performance as well where it's supported.

In general, we try not to be too opinionated on these things at the data collection level and give as many options and as much flexibility as possible.

**Comment by simpleton** [comment]
Thanks for the clarification!

Option 2 (userspace frame pointer unwinder) seems easier to implement, as we can reuse the same workflow as the DWARF unwinder (libunwindstack).

Option 1 (using the kernel’s perf_callchain with ustack) might require some refactoring of the current options and workflow, especially to normalize the addresses in ustack.

I’m interested in both solutions and would like to know more about the performance differences between them. let me try to publish the aosp/3297215 first.

**Comment by LalitMaganti** [comment]
Given the commit landed above, is there anything else we want to do here or can we close this?

Thanks a lot for the contribution btw and the patience while we got it in, very much appreciated!

**Comment by simpleton** [comment]
Thank you for your detailed review. I’m interested in trying the perf_callchain’s unwinder here as well. But I don’t have bandwidth right now. let me close this issue for now.
