### ISSUE TITLE
Enhancements from Perfetto

### ISSUE THREAD

**Issue by lavanyaeswarappa** [google/perfetto#914]
Hi,
I had few queries on how to add the following enhancements from Perfetto. These are mainly seen from android trace example. am using perfetto json format to visualize some logs. Could you please confirm which format of the perfetto the below features are supported. 

1. How do we add this hover feature (when hovered on duration event we see the details of that event)
![Image](https://github.com/user-attachments/assets/1df848b8-3436-4603-a384-679456ef73a8)

2. How to add the units to our counter events
![Image](https://github.com/user-attachments/assets/2c0a13dd-ace5-45c6-a31e-9db2e59d5259)

3. is there a way to visualize logs hierarchically

**Comment by LalitMaganti** [comment]
> How do we add this hover feature (when hovered on duration event we see the details of that event)

This is a property of CPU scheduling slices only. It's not supported for other types today (though we might add for other slice types including JSON slices at some point in the future).

> How to add the units to our counter events

This is not supported on JSON and never will be. Even in proto traces it's not really supported (it's only really available for very limited Android counters - e.g. CPU frequency as you highlight)

> is there a way to visualize logs hierarchically

I don't know what this question means.

**Comment by LalitMaganti** [comment]
> By this question I meant if we can group the multiple processes under one process.

Yes this is supported in the protobuf api: you can have a tree of tracks and that will be rendered correctly by the UI.

**Comment by lavanyaeswarappa** [comment]
Thanks Lalit. What is the main difference in feature that protobuf supports that json format is missing?

**Comment by LalitMaganti** [comment]
If you are synthesising traces the big ones are:
1) The much smaller trace sizes
2) Even more small trace sizes via interning (https://perfetto.dev/docs/reference/synthetic-track-event#interning)
3) You can build a tree of tracks totally decoupled from thread/process model

**Comment by lavanyaeswarappa** [comment]
Hi, could share the example/documentation where it shows tree of tracks and that will be rendered correctly by the UI. 
how do we do it on protobuf
