### ISSUE TITLE
Issue with Followers Not Collecting Data

### ISSUE THREAD

**Issue by ye3084** [google/perfetto#917]
Hello,
I'm trying to collect two perf_events simultaneously, and I've followed the guidelines in perf_events.proto and perf_event_config.proto. However, I’m encountering an issue where the followers are not collecting data as expected.

I’m using the latest version of Perfetto for android-arm64, and below is my config.pbtx:
```
duration_ms: 10000
buffers: {
    size_kb: 300000
    fill_policy: DISCARD
}
data_sources: {
    config {
        name: "linux.perf"
        perf_event_config {

            timebase {
                frequency: 100
                counter: HW_CACHE_MISSES
            }
            followers {
                counter: HW_CACHE_REFERENCES
            }
            callstack_sampling {
            }
        }
    }
}
```
Here’s the SQL query I used: I can see the cache-misses counter, but the cache_references counter is missing.
```sql
select * from perf_counter_track
```
![Image](https://github.com/user-attachments/assets/12520259-99c9-4f48-a4f5-5f76c6966e2e)

Here’s the error message I received: I noticed that in the trace_config_pbtxt, the followers field is being transformed into 19: "\b\f".
<img src="https://github.com/user-attachments/assets/417ada24-2b55-467c-9770-b0a2c7a47874" style="width: 65%;"/>
<img src="https://github.com/user-attachments/assets/61b80854-2c34-46bd-b6d4-5c4853c9f125" style="width: 65%;"/>

**Comment by LalitMaganti** [comment]
I believe there are a lot of caveats around follower events to the point we just don't even use them. I would recommend not using them:  if you need them just use simpleperf instead.

**Comment by ye3084** [comment]
@LalitMaganti 
Thank you for your response. I’d also like to know if Perfetto can collect PMU events at a fixed interval. I’m trying to set it up to read PMU events every 10ms, so I set the frequency to 100. However, I’ve noticed that the intervals between events are sometimes much longer than 10ms, and when the CPU load is low, no data is collected at all. I’ve read through the documentation but haven’t found a solution to this issue.

**Comment by LalitMaganti** [comment]
Yeah that's a consequence of trying to do unwinding on device. There's not a solution to it really: we have the same problem and it's extremely hard to fix.

**Comment by ye3084** [comment]
> Yeah that's a consequence of trying to do unwinding on device. There's not a solution to it really: we have the same problem and it's extremely hard to fix.

Thank! Could this issue be the reason for the import errors: perf_samples_skipped?
![Image](https://github.com/user-attachments/assets/6090c333-b39e-4841-a684-565b434b996d)

**Comment by LalitMaganti** [comment]
Yes.
