### ISSUE TITLE
Perfetto Initialization always connects a Producer

### ISSUE THREAD

**Issue by rickvanprim** [google/perfetto#92]
Running the following code causes `[329.254] perfetto.cc:33197       Producer connected` to be logged.  This is undesirable when trying to act as a Perfetto Consumer.

```
  perfetto::TracingInitArgs args;
  args.backends |= perfetto::kSystemBackend;
  perfetto::Tracing::Initialize(args);
```

**Comment by LalitMaganti** [comment]
Paging @skyostil @betasheet :)

**Comment by betasheet** [comment]
Looks like TracingMuxerImpl always registers the producer. Is this actually detrimental in your use case, @rickvanprim?

Adding a producer without any registered data sources should be minimal overhead, and doesn't prevent use of the consumer interface.

**Comment by skyostil** [comment]
Right, I don't think there's any significant downside to connecting the producer too. I wouldn't be opposed to a patch optionally disabling that, but I don't think we'll change this otherwise.

**Comment by rickvanprim** [comment]
I don't think it's a big deal, just unnecessary when the process will be strictly a Perfetto Consumer.  @primiano requested I file an issue so it didn't get lost.

**Comment by primiano** [comment]
Yeah ideally it's something we could improve (I agree with @rickvanprim the producer socket connection is unexpected) although not a high prio one as there is no concrete problem right now.

**Comment by LalitMaganti** [comment]
Realistically we're not going to be addressing this as it's so low prio. Closing.
