### ISSUE TITLE
[UI] Clicking and dragging on a pinned track highlights the underlying track instead

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#920]
If you try to select events in a pinned track it will select the events in the track beneath the pinned track instead of the events in the pinned track itself.

Currently it seems selecting events in a pinned track will only work properly if the user is scrolled all the way to the top of the trace.

This issue appears to reproduce on Stable, Canary, and Autopush channels.

# How to reproduce

1. navigate to ui.perfetto.dev 
2. open the example android trace from the sidebar
3. pin the first Surface flinger track
4. scroll down in the trace
5. click and drag over the events in the pinned track.

## Expected outcome

Events from the surface flinger track are are displayed in the "Area Selection" tab

## Actual outcome

Events from another track get displayed in the "Area Selection" tab instead, or the tab displays an error about being unable to aggregate events

See example where i select a track with atrace events and instead it aggregates events from the CPU tracks instead.

https://github.com/user-attachments/assets/59ef8755-5680-49e6-badd-debbf338d85c

**Comment by LalitMaganti** [comment]
Thanks for reporting. https://r.android.com/3327444 fixes this (and another issue I found with area selection with scrolling as well).
