### ISSUE TITLE
[UI] Search "next button" fails to cycle through all results in some traces

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#921]
I've seen a few traces where searching some text in the top bar and pressing next will fail to cycle though all of the events.

This behavior reproduces with the attached trace on Stable, Canary, and Autopush channels.

# How to reproduce

1. open attached trace [search_bug_repro.pftrace.gz](https://github.com/user-attachments/files/17591701/search_bug_repro.pftrace.gz) 
3. type "my_event" in the search bar and press enter
4. repeatedly click the next button in attempt to cycle though all results

https://github.com/user-attachments/assets/60fbffa1-6570-48e9-b952-e48b09a9cf3a

**Comment by LalitMaganti** [comment]
@stevegolton @primiano

**Comment by LalitMaganti** [comment]
Thanks for filing. https://r.android.com/c/3326034/1 should fix.
