### ISSUE TITLE
[UI] Android logs tab doesn't auto-refresh when entering text in log search filter

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#922]
If you enter search text in the android logs tab, the logs don't refresh until you attempt to scroll the logs, or take some other action that would normally cause that section of the UI to redraw. If there are not enough logs in the tab for a scroll bar to appear then this workaround can't be used.

This reproduces on Canary and Autopush (v48.1), but not on Stable (v47).

# How to reproduce:

1. open the android_log.pb from the test data in the perfetto git repo: `./tools/open_trace_in_ui test/data/android_log.pb`
2. enter text in the field labeled "Search logs..."
3. mouse wheel scroll down in the logs.
4. Observe the search filter is only applied once you start scrolling instead of immediately

https://github.com/user-attachments/assets/9b937daf-2cbf-4c6c-8c61-b38fd2e5582c

**Comment by LalitMaganti** [comment]
Thanks for filing. https://r.android.com/3326027 should fix.
