### ISSUE TITLE
how to fast find target in ui?

### ISSUE THREAD

**Issue by ChunelFeng** [google/perfetto#924]
SELECT * FROM args where flat_key = "debug.msg_id" and int_value = 1730449307563864

hi, i can use sql find our target slice, but i cannot fast locate to any of them

![Image](https://github.com/user-attachments/assets/48d5a7a9-96aa-4c56-9f30-8ae415c658a0)

**Comment by LalitMaganti** [comment]
You need the query:
```
SELECT * FROM slice where EXTRACT_ARG(arg_set_id, 'debug.msg_id') = 1730449307563864
```

The query table will then be clickable and will navigate you to the relevant slice.

**Comment by ChunelFeng** [comment]
thank you , it is really helpful.

**Comment by ChunelFeng** [comment]
hi， the sql is very useful, but when i select some of all, it cannot jump to source by click

![Image](https://github.com/user-attachments/assets/51286555-178f-4bc4-838f-c389db358907)


and a error heppen when i try to use newset ui in 
https://ui.perfetto.dev/

![Image](https://github.com/user-attachments/assets/52cdfaf8-216c-42e9-853a-0c7cf1a5ff26)

**Comment by ChunelFeng** [comment]
ok, now i can jump to source with select more info:

```bash
SELECT stack_id,id, type,ts,track_id,dur, category,name FROM slice where EXTRACT_ARG(arg_set_id, 'debug.msg_id') = 1730864432877225 order by ts
```
