### ISSUE TITLE
bootup trace has been removed after reboot in Android14

### ISSUE THREAD

**Issue by wjj1928** [google/perfetto#925]
In android13, when set property `persist.debug.perfetto.boottrace ` to `1` then reboot to capture the bootup trace,  then reboot again without set that property, the log file will still there: `/data/misc/perfetto-traces/boottrace.perfetto-trace`

But in Android14, the same steps but the log file will be deleted. which commit do it? is it from `perfetto.rc` config file?

I ask this since I am testing on a crash cause reboot issue, I wish to get the log after the second reboot.

**Comment by LalitMaganti** [comment]
Not sure how this was working on Android 13 as since 2021 when boot tracing was first implemented there was an rm of the trace file (https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/perfetto.rc;drc=da024db5c1695649a79c615816a8191e10c04d72;l=113)

**Comment by wjj1928** [comment]
This rm only happen when the property is set to 1, which will be done before bootup trace capture. after that, this property will be set to empty, so the rm logic will never run after that. so the second boot should not remove the bootup trace.

**Comment by LalitMaganti** [comment]
Ah you're right that makes sense.

I'm not aware of any changes we've made to bootup tracing process since implementation. Will need some more debugging on your side to figure out the root cause.

**Comment by wjj1928** [comment]
Just found if the caputre session ended then reboot device, the trace file will be still there.
But if the session not finished (say 5mins capture but reboot at 3 mins), then that file will be removed after reboot.

I am not sure if this is a bug or it's by design?

And the rc file show below section:

```
on property:sys.boot_completed=1
    exec -- /system/bin/perfetto -c /data/misc/perfetto-configs/stopboottracetrigger.pbtxt --txt

```

But /data/misc/perfetto-configs/stopboottracetrigger.pbtxt is not exist at device, is it a issue? I guess it's deleted by this command if session not end then reboot device.

**Comment by LalitMaganti** [comment]
> I am not sure if this is a bug or it's by design?

This is by design I think. You should kill -TERM $(pidof perfetto) before you reboot.

**Comment by LalitMaganti** [comment]
> But /data/misc/perfetto-configs/stopboottracetrigger.pbtxt is not exist at device, is it a issue? I guess it's deleted by this command if session not end then reboot device.

I think if the file does not exist nothing happens. This case is only designed for cases where you want tracing to stop when bootup is completed

**Comment by wjj1928** [comment]
The problem is the reboot is triggered by some crash event, which I want to get the trace when issue happen. so send a kill command to end the process looks not doable for this case.

Where is the logic do that? then I can comment it out to test this specific usecase.

**Comment by LalitMaganti** [comment]
> Where is the logic do that? then I can comment it out to test this specific usecase.

The problem is that you are relying on Perfetto terminating properly before tracing. This is not at all guaranteed: I'd a crash is happening we don't have time to actually write the trace file properly so anything can happen from the file not being there to being corrupted. I don't think Perfetto is designed to do what you are looking for, anything which is working just happens to work and is not by design. 

If you really insist on trying to use Perfetto you can use write_into_file and file_write_period_ms to try and flush the trace to a file every x ms and see if that works. But even there it's very possible for the file to be corrupted because of a partial file write.

**Comment by wjj1928** [comment]
Exactly, I have add below in my config:
```
write_into_file: true
file_write_period_ms: 1000                              

```
But file is there when first bootup, then removed the second bootup. it's not due to not write to file, but due to some code removed it maybe due to not finished yet.

**Comment by LalitMaganti** [comment]
I am not aware of any code in Perfetto which would delete a file like that. It's possible that it's something else, maybe even at the kernel level which is auto deleting files which have not been fsynced correctly to disk (we don't do any fsync on our side).
