### ISSUE TITLE
Perfetto viewer requires trailing `]` in JSON Array Format

### ISSUE THREAD

**Issue by jez** [google/perfetto#926]
Given this trace file:

```json
[
{"name":"typecheck","ph":"X","ts":4619295550.000,"dur":8000.000,"pid":306339,"tid":3},
```

the Perfetto trace viewer shows this error:

```
UI: https://ui.perfetto.dev/v47.0-1b4776303

Failed assertion
 -  (Error: Failed assertion)
 - assertTrue (frontend_bundle.js:3683:16)
 - QueryResultImpl.firstRow (frontend_bundle.js:71557:36)
 - TraceController.loadTrace (frontend_bundle.js:201663:35)

Trace: not available (FILE). Provide repro steps.
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Referrer: https://perfetto.dev/
```

When changing the trace file to include a trailing `]`, the trace loads successfully:

```json
[
{"name":"typecheck","ph":"X","ts":4619295550.000,"dur":8000.000,"pid":306339,"tid":3},
]
```

The documentation on the [Trace Event Format](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview?tab=t.0#heading=h.f2f0yd51wi15) declares that a trailing `]` is optional:

> When provided as a string to the importer the ] at the end of the JSON Array Format is optional. The Trace Viewer importer will automatically add a ] if needed to turn the string into valid JSON.. This is to support tracing systems that can not cleanly finish writing the trace. For example, when tracing the exit of a program.

In addition to the stated reason ("program did not exit cleanly"), it's also nice to be able to append to an existing file by simply seeking to the end of the file and writing, instead of having to deal with `]` matching.

The legacy chrome://tracing UI supports omitting the final `]`.

**Comment by LalitMaganti** [comment]
Fixed by https://r.android.com/3342433

**Comment by jez** [comment]
That was fast, thanks!
