### ISSUE TITLE
Perfetto SDK support counter

### ISSUE THREAD

**Issue by Kyson** [google/perfetto#93]
Hi,

Perfetto can not support counter event now.

I found TRACE_COUNTER1 method in sdk but is not public api

![image](https://user-images.githubusercontent.com/3901140/105960126-beb8dd00-60b7-11eb-8fed-bb72773ed76a.png)

**Comment by primiano** [comment]
Is this a question or a statement?

@betasheet @skyostil FYI

**Comment by Kyson** [comment]
> Is this a question or a statement?
> 
> @betasheet @skyostil FYI

This is a question.

Why not support counter api and how can i use counter api.

Thx.

**Comment by betasheet** [comment]
We're aware of this feature request and hope to get around to implement it soon! :)

**Comment by Kyson** [comment]
> We're aware of this feature request and hope to get around to implement it soon! :)

Thanks a lot ! Please update this issue if there is any update.

**Comment by primiano** [comment]
Fixed in r.android.com/1566122
