### ISSUE TITLE
404 GitHub gist in Doc 'Trace-based metrics'

### ISSUE THREAD

**Issue by Bingist** [google/perfetto#94]
When I tried to run a metric using Perfetto, I have followed steps in Doc, but the metric didn't work with an 'Error when computing metrics: Unknown metric xxx'. 
I noticed that there's note saying **If something doesn't work as intended, check that the workspace looks the same as the comtents of this** [GitHub gist](https://gist.github.com/tilal6991/c221cf0cae17e298dfa82b118edf9080), but the link is just a 404 page. 
What should the workspace look like to make the metric work?

**Comment by chromy** [comment]
I think the link should be: https://gist.github.com/LalitMaganti/c221cf0cae17e298dfa82b118edf9080 I'll send a change to update the docs.

**Comment by LalitMaganti** [comment]
This should now be fixed by the above :)
