### ISSUE TITLE
Uncaught TypeError: testPort.disconnect is not a function

### ISSUE THREAD

**Issue by roseline124** [google/perfetto#954]
I tried to open perfetto gui, but I got this error.
I did all instructions in the photo.
please check this issue, thank you :)

![Image](https://github.com/user-attachments/assets/adc5ce01-c48d-4461-a64a-2618b74a385e)

**Comment by LalitMaganti** [comment]
Are you using Chrome? From looking at the code looks like no which is causing the issue

We don't have the resources to test properly on other browsers unfortunately. We try our best to keep things working but things like this will creep in.

**Comment by LalitMaganti** [comment]
Actually it seems like this is some browser issue where the browser is sort of pretending to be chrome (i.e. chrome.runtime is defined) but it returns null for chrome.runtime.connect which Chrome does not do.

**Comment by roseline124** [comment]
It works for now. I think it was the slow wifi. I connected to a hotspot and everything is fine. thank you for your answer!
