### ISSUE TITLE
Add support for drag & drop to open files

### ISSUE THREAD

**Issue by marvinhagemeister** [google/perfetto#96]
Like the title says: It would be awesome if the perfetto UI supported drag & drop to open files. Out of habit I always try that first and get confused for a second why it doesn't work.

**Comment by primiano** [comment]
Oh sounds like a good idea:
https://android-review.googlesource.com/c/platform/external/perfetto/+/1594254

**Comment by primiano** [comment]
This is now live  @ ui.perfetto.dev

**Comment by marvinhagemeister** [comment]
Sweet, thank you so much for adding this 🙌
