### ISSUE TITLE
Setting time format to milliseconds, the duration label still stays in seconds with "s"

### ISSUE THREAD

**Issue by lunaleaps** [google/perfetto#967]
When changing the time format, the "duration" label uses the wrong unit. Currently it is displaying the correct milliseconds but using "s" when it should be "ms" like in "start time"

The value correctly scales with whatever time-unit I change it to, it's just the label that is wrong

![Image](https://github.com/user-attachments/assets/cba9f7dd-eea2-4134-8f08-9e3e1dd8c663)

**Comment by LalitMaganti** [comment]
This is already fixed by https://r.android.com/3369378 on HEAD. It doesn't look like it's on stable ATM though. I'll try to do a cherry-pick,
