### ISSUE TITLE
Private format into perfetto ui recognized proto binary.

### ISSUE THREAD

**Issue by Gummum** [google/perfetto#968]
I have a text file that records information about the cpu runtime. I wanted to use perfetto ui (I think it works really well). Then how do I compile the proto files in the project to python files?

**Comment by LalitMaganti** [comment]
We don't provide any step by step guide for this but it should just be a matter of taking the amalgamated proto file in our repo (https://github.com/google/perfetto/blob/main/protos/perfetto/trace/perfetto_trace.proto) and generating some python bindings with the protc compiler https://protobuf.dev/reference/python/python-generated/

**Comment by Gummum** [comment]
Thanks, I can use it now. But I think there may be a problem with the way I record, perfetto ui can't recognize my files.
```
import perfetto_trace_pb2 as trace
 
def run():
    data = trace.TracePacket()
    data.timestamp = 123123123123
    data.trace_uuid.msb=123123123
    data.trace_uuid.lsb=565465
    serialized = data.SerializeToString()
    print(f"serialized:{serialized}")
    new_person = trace.TracePacket()
    new_person.ParseFromString(serialized)
    print(new_person)
    with open('test.perfetto-trace', 'wb') as fb:
        fb.write(serialized)
 
if __name__ == '__main__':
    run()
```

**Comment by LalitMaganti** [comment]
Please follow https://perfetto.dev/docs/reference/synthetic-track-event which explains how to properly encode the trace protos.

**Comment by Gummum** [comment]
Thank you. It turns out that simply filling in the contents of proto won't work.
