### ISSUE TITLE
Unable to pin some thread tracks

### ISSUE THREAD

**Issue by tsniatowski** [google/perfetto#971]
Hi, I'm tracing a Chromium-derived app on Android and noticed I am sometimes unable to pin some thread tracks. This seems to happen when the track has a collapsed sub-track (?). I can click on the track to show the nested track, but the pin icon is only on the nested track and not on the outer one.

In the screenshot, I can pin the LongTaskTracker nested below the main thread, but there's no pin icon if I hover over the main thread.

![Image](https://github.com/user-attachments/assets/aab45daf-9e71-4100-9979-d44a8d5575b0)

Is this expected, or a bug?

**Comment by LalitMaganti** [comment]
This is a bug. We have an internal bug tracking the same issue actually.

**Comment by tsniatowski** [comment]
Thanks for the lightning-fast response and fingers crossed for a fix, then :)

**Comment by LalitMaganti** [comment]
Actually I already fixed this in https://r.android.com/3391370

I guess we just need to cherry-pick this to stable.
