### ISSUE TITLE
Encountering issue trying to replicate synthetic thread scoped slice

### ISSUE THREAD

**Issue by keviin0** [google/perfetto#974]
I've been following https://perfetto.dev/docs/reference/synthetic-track-event to create a tool to synthetically create perfetto traces for analyzing a game I'm developing. When replicating the thread scoped slice example (without the TYPE_INSTANT) packet, I get the following error:
![Image](https://github.com/user-attachments/assets/f74fefbb-3d7d-44e4-930c-1858e3d8146d)
Just was wondering if maybe I'm missing something, if this is an expected byproduct of synthetic traces, or if it's a bug (it seems to render fine after closing the error out).
Below is the traceconv'd text output of my generated proto:
```
packet {
  track_descriptor {
    uuid: 5458347387078959600
    process {
      pid: 1234
      process_name: "My process name"
    }
  }
}
packet {
  track_descriptor {
    uuid: 18409545874856999106
    thread {
      pid: 1234
      tid: 5678
      thread_name: "My thread name"
    }
  }
}
packet {
  timestamp: 200
  trusted_packet_sequence_id: 741490981
  track_event {
    type: TYPE_SLICE_BEGIN
    track_uuid: 18409545874856999106
    name: "My special parent"
  }
}
packet {
  timestamp: 250
  trusted_packet_sequence_id: 741490981
  track_event {
    type: TYPE_SLICE_BEGIN
    track_uuid: 18409545874856999106
    name: "My special child"
  }
}
packet {
  timestamp: 290
  trusted_packet_sequence_id: 741490981
  track_event {
    type: TYPE_SLICE_END
    track_uuid: 18409545874856999106
  }
}
packet {
  timestamp: 300
  trusted_packet_sequence_id: 741490981
  track_event {
    type: TYPE_SLICE_END
    track_uuid: 18409545874856999106
  }
}
```

**Comment by LalitMaganti** [comment]
This is very unrelated with the fact that it's a synthetic trace. This seems some UI bug around trace loads. It think we might actually be fixing this issue with https://r.android.com/3428304

Are you able to reproduce this consistently? does it happen when you open traces manually or only with the tool?

**Comment by LalitMaganti** [comment]
See also https://github.com/google/perfetto/issues/923 for another similar error.

**Comment by keviin0** [comment]
It has been happening pretty consistently. I'm not quite sure what you mean by opening traces manually or only with the tool but I've been opening my traces with the "Open Trace File" button.
![Image](https://github.com/user-attachments/assets/a1375c55-6de4-47cb-9169-633288d5d672)

**Comment by LalitMaganti** [comment]
Yes that's what I meant by opening manually.

That's quite surprising that you are hitting that issue, we haven't had any reproducible reports of this. From what we understand, this is a race condition so should only be happening every now and then. Also I just tried to open this trace and it opened fine for me with no dialog:
![Image](https://github.com/user-attachments/assets/8a564bb0-53c3-4356-8e51-65bebc585764)

Did you play around with any flags in the flags page? Does it also reproduce if you open the UI with an incognito window/private tab?

**Comment by LalitMaganti** [comment]
Here's the exact file I'm opening (zipped to allow uploading on GitHub)

[proto.trace.zip](https://github.com/user-attachments/files/18220458/proto.trace.zip)

**Comment by keviin0** [comment]
Ah, I can't seem to reproduce it in incognito. Seems to load fine there. I don't remember changing any flags (and just checked they're all set to default values).

**Comment by LalitMaganti** [comment]
Maybe try and clear the site storage on your profile for ui.perfetto.dev? Seems like something has got into a messed up state.

**Comment by keviin0** [comment]
Ah, it looks like something about Brave's browser shield messed things up. Disabling it did the trick. Thanks for the help!

**Comment by LalitMaganti** [comment]
Great glad to help :)
