### ISSUE TITLE
Poor rendering performance on trace

### ISSUE THREAD

**Issue by weijizhen** [google/perfetto#976]
Marking a trace on the perfetto UI can cause **significant lag** when zooming in or out. Cannot be used anymore.
![Image](https://github.com/user-attachments/assets/3806d75d-a63c-4a05-81d0-0cf2bc8408d2)

**Comment by LalitMaganti** [comment]
Also did you perhaps click the button to open all tracks? We're aware of some serious performance problems when you click that button because it causes a very large increase in the number of tracks visible.

Personally I find it difficult to believe that pinning tracks (what you call marking) causes this problem. I think it's much more likely you did something else.

**Comment by weijizhen** [comment]
No, I didn't do anything else. When I zoom in and out, a gray area appears that is currently loading. My classmate is the same, I updated Chrome and the same result compared to last week. This version of Perfetto UI is really difficult to use. I feel like I get carsick when I use it, and I feel nauseous when I look at it.

**Comment by weijizhen** [comment]
I see that there are many exceptions in the backend loading. Could it be due to some libraries or logical errors? Does this cause UI rendering to lag behind during zooming in and out operations, resulting in stuttering?![Image](https://github.com/user-attachments/assets/47600070-c1a6-4d64-b76d-445531e07173)

**Comment by LalitMaganti** [comment]
Again without the trace it is essentially impossible to debug these sort of issues. What I can say is that we do not experience such bad performance on the trace we load and we load 10s of thousands of traces per month. 

The errors are not related. We need the trace to make any progress here.

**Comment by weijizhen** [comment]
I suddenly understand why. Because when I use **'Open Android example'**, there won't be any lag, but when I use **config. pbtx** to capture the trace myself, there will be a lag.
Do you think this exception is caused by some fields being unable to load?

![Image](https://github.com/user-attachments/assets/bb8147d3-c986-421a-b132-2b904e1bced4)

**Comment by LalitMaganti** [comment]
As I've said there is something about your trace causing this issue. Those errors do not explain the issue. 

Once again please provide the trace if you want us to help on this issue.

**Comment by weijizhen** [comment]
- Failed to upload "Per_LongTime.zip" 
................................................................
I've passed it a few times, but I can't access it

**Comment by LalitMaganti** [comment]
You can send it to me via email at lalitm@google.com if GitHub refuses to work.

**Comment by weijizhen** [comment]
> You can send it to me via email at [lalitm@google.com](mailto:lalitm@google.com) if GitHub refuses to work.

Sorry for keeping you waiting. Sent to your email

**Comment by LalitMaganti** [comment]
Thanks received. Will take a look.

**Comment by LalitMaganti** [comment]
Courtesy of @stevegolton, https://r.android.com/3432420 fixed the issue and https://r.android.com/3432459 rolled it out. Things should be much better after these roll out.

Please refresh your UI and this problem should go away.

Closing out the bug as this should be fixed.

**Comment by stevegolton** [comment]
FYI this has now landed on stable. You're looking for v48.1-6f67beebb (in the bottom right of the sidebar).

![Image](https://github.com/user-attachments/assets/8d7f8486-103f-488a-8f26-bf02502b4df1)
