### ISSUE TITLE
UI RPC API not compatible with Trace processor

### ISSUE THREAD

**Issue by wjd6910502** [google/perfetto#977]
The Trace Processor instance on 127.0.0.1:9001 is a different build from the UI.

This may cause problems. Where possible it is better to use the matched version of the UI.
You can do this by clicking the button below.

UI version code: v48.1-94595b08a
UI RPC API: 14

Trace processor version: Perfetto v48.1-97f453dd8 (97f453dd8a07d39fe0046acaac1baccfa989c4ee)
Trace processor version code: v48.1-97f453dd8
Trace processor RPC API:

**Comment by LalitMaganti** [comment]
This is not a bug. The dialog is telling you exactly what the problem is and the suggested solution. All you need to do is accept the suggestion by clicking the button :)
