### ISSUE TITLE
Can perfetto support open file by bash/bat

### ISSUE THREAD

**Issue by Kyson** [google/perfetto#98]
I want to open trace file automatically using perfetto.dev

Can i open it by code in .bash or .bat?

**Comment by primiano** [comment]
Yes, see `open_trace_in_browser()` from https://github.com/google/perfetto/blob/master/tools/record_android_trace#L218
That has the code / logic you need for auto-opening.

**Comment by Kyson** [comment]
@primiano Thx a lot, i can auto open it now.
